# DAG Parameterization
The goal of this notebook is to assess which of the graphs (DAGs or PAGs) we generated during our causal structure learning step produces the best predictive model.

In [6]:
# Data manipulation and plotting
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import re
import glob

# Bayesian Networks
from pgmpy.models import LinearGaussianBayesianNetwork

# Metrics
from sklearn.calibration import calibration_curve
from pycalib.metrics import ECE

import xgboost
import shap

## Data preparation

In [7]:
# Load training data
X_train = pd.read_csv('../../Data Pre-processing/X_train_c12_w48_imp.csv', index_col=0)
X_test = pd.read_csv('../../Data Pre-processing/X_test_c12_w48_imp.csv', index_col=0)

print(X_train.shape, X_test.shape)

#Remove features with 0 variance
X_train = X_train.loc[:, X_train.var() >= 0.01]
X_test = X_test.filter(items=X_train.columns) # Keep only columns in X_train
print(X_train.shape, X_test.shape)

# # Impute missing values using Iterative Imputer (Linear Gaussian BN can't handle missing values)
# imputer = IterativeImputer(random_state=42, max_iter=100)
# X_train_imp = pd.DataFrame(imputer.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
# X_test_imp = pd.DataFrame(imputer.transform(X_test), columns=X_test.columns, index=X_test.index)

X_train_imp = pd.read_csv('../../Data Pre-processing/X_train_c12_w48_mice.csv', index_col=0)
X_test_imp = pd.read_csv('../../Data Pre-processing/X_test_c12_w48_mice.csv', index_col=0)

y_train = pd.read_csv('../../Data Pre-processing/y_train_c12_w48_imp.csv', index_col=[0,1]).groupby('uid').max()
y_test = pd.read_csv('../../Data Pre-processing/y_test_c12_w48_imp.csv', index_col=[0,1]).groupby('uid').max()

# Correlation feature selection
correlation_threshold = 0.3
X_train_corr = X_train_imp.loc[:, X_train_imp.corrwith(y_train['Outcome']).abs() >= correlation_threshold]
print(X_train_corr.shape)

(13054, 990) (3895, 990)
(13054, 811) (3895, 811)
(13054, 113)

# Loading DAGs

In [13]:
#Get all adjacency files
adjacency_files = glob.glob("../DAGs/*_adjacency.csv")

dags = {}
dags['Control'] = nx.from_edgelist([(col, 'Outcome') for col in X_train_imp.columns.str.replace(r'(_.+)?$', '', regex=True).unique().tolist() if col != 'Outcome'], create_using=nx.DiGraph())
dags['Correlation'] = nx.from_edgelist([(col, 'Outcome') for col in X_train_corr.columns.str.replace(r'(_.+)?$', '', regex=True).unique().tolist() if col != 'Outcome'], create_using=nx.DiGraph())
for file in adjacency_files:
    dag_name = re.search(r'../DAGs/(.*)_adjacency.csv', file).group(1)
    dag_name = re.sub(r'(?<![a-zA-Z])x(?![a-zA-Z])', lambda _: '$\\cap$', dag_name)
    dag_name = dag_name.replace(' + ', ' $\\cup$ ')
    dags[dag_name] = nx.DiGraph(pd.read_csv(file, index_col=0))

dags.pop('Golem $\\cap$ PCMB')  # Remove problematic DAG (has 0 nodes associated with Outcome)
list(dags.keys())

['Control',
 'Correlation',
 'Clinician Consensus $\\cup$ Golem',
 'Simplified Clinician Consensus $\\cup$ Simplified PCMB',
 'Simplified Clinician Consensus $\\cup$ Simplified Golem',
 'Clinician Consensus $\\cup$ PCMB',
 'Simplified Golem $\\cup$ Simplified PCMB',
 'Clinician Consensus',
 'Simplified Clinician Consensus',
 'Clinician Consensus $\\cap$ PCMB',
 'Golem',
 'PCMB',
 'Simplified Clinician Consensus $\\cap$ Simplified PCMB',
 'Simplified PCMB',
 'Clinician Consensus $\\cap$ Golem',
 'Simplified Golem',
 'Golem $\\cup$ PCMB',
 'Simplified Golem $\\cap$ Simplified PCMB',
 'Simplified Clinician Consensus $\\cap$ Simplified Golem']

In [18]:
list(dags['Simplified Golem'].nodes())

['Outcome',
 'Weight',
 'SpO2',
 'Creatinine',
 'Peds Coma Score',
 'Blood urea nitrogen',
 'Dopamine',
 'Sodium',
 'PTT',
 'Ventilated',
 'Potassium',
 'DBP']

# Model Training Functions
For each dag we train a Linear Gaussian Bayesian Network, an XGBoost

In [4]:
from MLstatkit import Bootstrapping, Delong_test, Permutation_test
from itertools import combinations

def compare_models(y, y_prob1, y_prob2):
        # DeLong Test for AUROC
        z, p = Delong_test(y.values, y_prob1, y_prob2, return_ci=False, return_auc=False)
        metric_a, metric_b, p_value, benchmark, samples_mean, samples_std = Permutation_test(y.values, y_prob1, y_prob2, metric_str='average_precision')
        return (z, p), (metric_a, metric_b, p_value, benchmark, samples_mean, samples_std)

def performance_report(X, y, model):
    try:
        y_prob = model.predict_proba(X)[:, 1] # Predict on test data
    except AttributeError:
        y_prob = model.predict(X)['Outcome'].to_numpy() # Predict on test data (LGBN fallback: pgmpy 1.x returns DataFrame w/ Outcome conditional mean)
        y_prob = np.where(y_prob > 1, 1, np.where(y_prob < 0, 0, y_prob))

    ## Calculate Performance Metrics with Bootstrapping
    n_bootstraps = 1000
    # Average Precision
    ap, ap_lower, ap_upper = Bootstrapping(y.values, y_prob, metric_str='average_precision', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # AUROC
    auroc, auroc_lower, auroc_upper = Bootstrapping(y.values, y_prob, metric_str='roc_auc', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # Precision 
    precision, precision_lower, precision_upper = Bootstrapping(y.values, y_prob, metric_str='precision', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # Recall
    recall, recall_lower, recall_upper = Bootstrapping(y.values, y_prob, metric_str='recall', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # F1 Score
    f1, f1_lower, f1_upper = Bootstrapping(y.values, y_prob, metric_str='f1', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # Accuracy
    accuracy, accuracy_lower, accuracy_upper = Bootstrapping(y.values, y_prob, metric_str='accuracy', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # ECE
    ece = ECE(y.values, y_prob.reshape(-1, 1), bins=50)

    return {'Average Precision': f"{ap:.2f} ({ap_lower:.2f}, {ap_upper:.2f})",
     'AUROC': f"{auroc:.2f} ({auroc_lower:.2f}, {auroc_upper:.2f})",
     'Precision': f"{precision:.2f} ({precision_lower:.2f}, {precision_upper:.2f})",
     'Recall': f"{recall:.2f} ({recall_lower:.2f}, {recall_upper:.2f})",
     'F1 Score': f"{f1:.2f} ({f1_lower:.2f}, {f1_upper:.2f})",
     'Accuracy': f"{accuracy:.2f} ({accuracy_lower:.2f}, {accuracy_upper:.2f})",
     'ECE': f"{ece:.3f}"}

def train_models(remove_drugs=False, remove_interventions=False):
        results = []
        shap_values = {}
        calibrations = {}
        model_preds = {}
        drugs = ['Midazolam', 'Fentanyl', 'Olanzapine', 'Haloperidol', 
                'Dexmedetomidine', 'Lorazepam', 'Morphine', 'Hydromorphone', 
                'Dopamine', 'Cisatracurium', 'Epinephrine', 'Norepinephrine', 
                'Milrinone', 'Dobutamine']
        

        for dag_name, dag in dags.items():
        
                # Simplified is not in the dag_name, skip
                if 'Simplified' not in dag_name and dag_name not in ['Control', 'Correlation']:
                        continue


                if dag is not None:
                        print(f"Processing {dag_name} with {dag.number_of_nodes()} nodes and {dag.number_of_edges()} edges")

                nodes_in_dag = list(dag.nodes())

                if 'Simplified' in dag_name or dag_name in ['Control', 'Correlation']:
                        if remove_drugs:
                                for drug in drugs:
                                        if drug in nodes_in_dag:
                                                nodes_in_dag.remove(drug)
                
                        if remove_interventions:
                                intervention_nodes = ['CRRT Therapy Type', 'ECMO Type', 'Ventilated', 'Pupillary Reaction', 'Peds Coma Score', 'Endotracheal tube']
                                for intervention in intervention_nodes:
                                        if intervention in nodes_in_dag:
                                                nodes_in_dag.remove(intervention)

                        if dag_name == 'Correlation':
                                features_in_dag = [col for col in X_train_corr.columns if any(re.search(rf'^{re.escape(node)}(_.+)?$', col) for node in nodes_in_dag)]
                        else:
                                features_in_dag = [col for col in X_train_imp.columns if any(re.search(rf'^{re.escape(node)}(_.+)?$', col) for node in nodes_in_dag)]

                        train_dag = nx.DiGraph()

                        # Map DAG nodes to features
                        for node in nodes_in_dag:
                                ends = list(dag.successors(node))
                                from_features = [col for col in features_in_dag + ['Outcome'] if re.search(rf'^{re.escape(node)}(_.+)?$', col)]
                                to_features = [col for col in features_in_dag + ['Outcome'] if any(re.search(rf'^{re.escape(end)}(_.+)?$', col) for end in ends)]
                                for from_feature in from_features:
                                        for to_feature in to_features:
                                                train_dag.add_edge(from_feature, to_feature)
                        
                        n_biomarkers = len(nodes_in_dag) - 1  # Exclude Outcome
                else:
                        # Use list comprehensions to avoid mutating nodes_in_dag while iterating
                        if remove_drugs:
                                nodes_in_dag = [node for node in nodes_in_dag if not any(drug in node for drug in drugs)]
                        if remove_interventions:
                                intervention_nodes = ['CRRT Therapy Type', 'ECMO Type', 'Ventilated', 'Pupillary Reaction', 'Peds Coma Score', 'Endotracheal tube']
                                nodes_in_dag = [node for node in nodes_in_dag if not any(intervention in node for intervention in intervention_nodes)]
                        
                        features_in_dag = X_train_imp.filter(items=nodes_in_dag).columns.tolist()
                        train_dag = dag.subgraph(features_in_dag + ['Outcome']).copy()
                        n_biomarkers = X_train_imp.filter(items=nodes_in_dag).columns.str.replace(r'(_.+)?$', '', regex=True).nunique() - 1  # Exclude Outcome

                # XGB trains on non-imputed X_train; restrict to columns actually present there
                xgb_features = [f for f in features_in_dag if f in X_train.columns]

                models = {}
                # Instantiate Models
                models['LGBN'] = LinearGaussianBayesianNetwork(train_dag.edges())
                # models['LR'] = LogisticRegression(max_iter=1000, random_state=42)
                models['XGB'] = xgboost.XGBClassifier(objective='binary:logistic', random_state=42, eval_metric='aucpr')
                

                for model_name, model in models.items():
                        metrics = {}
                        metrics['Model'] = model_name
                        metrics['DAG'] = dag_name

                        if model_name == 'LGBN':
                                # Fit the model
                                train = pd.concat([X_train_imp.filter(features_in_dag), y_train.filter(['Outcome']).astype(int)], axis=1)
                                model.fit(train)
                                metrics.update(performance_report(X_test_imp.filter(features_in_dag), y_test.Outcome, model))
                                metrics['# Features'] = len(features_in_dag)
                        elif model_name == 'LR':
                                model.fit(X_train_imp.filter(features_in_dag), y_train.Outcome)
                                model_preds[dag_name] = model.predict_proba(X_test_imp.filter(features_in_dag))[:, 1]
                                metrics.update(performance_report(X_test_imp.filter(features_in_dag), y_test.Outcome, model))
                                metrics['# Features'] = len(features_in_dag)
                        else:
                                X_train_filtered = X_train.filter(xgb_features)
                                X_test_filtered = X_test.filter(xgb_features)
                                model.fit(X_train_filtered, y_train.Outcome)
                                y_prob = model.predict_proba(X_test_filtered)[:, 1]
                                model_preds[dag_name] = y_prob
                                metrics.update(performance_report(X_test_filtered, y_test.Outcome, model))
                                calibrations[dag_name] = calibration_curve(y_test.Outcome, y_prob, n_bins=50)
                                metrics['# Features'] = len(xgb_features)

                        metrics['# Biomarkers'] = n_biomarkers

                        results.append(metrics)


                # SHAP feature importance
                X_test_shap = X_test.filter(xgb_features)
                explainer = shap.TreeExplainer(models['XGB'])
                values = explainer.shap_values(X_test_shap)
                values = pd.DataFrame(values, columns=X_test_shap.columns, index=X_test_shap.index)
                shap_values[dag_name] = values
        

        return results, shap_values, calibrations, model_preds

In [5]:
def shap_values_biomarker_summary(shap_values):
    vals = {} 
    for dag_name in shap_values:
        df = shap_values[dag_name].reset_index().melt(id_vars='uid')
        df.variable = df.variable.str.replace(r'(_.+)?$', '', regex=True)
        df.value = df.value.abs()                                   # abs before summing to prevent sign cancellation
        df = df.groupby(['uid', 'variable']).sum().reset_index()
        df = df.groupby('variable').value.mean().sort_values(ascending=True)
        vals[dag_name] = df
    return vals

# Model Training

## Bootstrapping
We simulate the potential performance of our models on an out of distribution dataset by performing a weighted bootstrap of our Test set. <br>
For context, our test set is already based on prospective samples. The training set comes from patients admitted up to 2019 and the test set is from patient admitted on or after 2020.

## Expriment 1: Comparing Feature Selection Approaches (DAGs)

In [50]:
results, shap_values, calibrations, model_preds = train_models(remove_drugs=False, remove_interventions=False)

Processing Control with 46 nodes and 45 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1578.80it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1044.13it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1150.83it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1170.52it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1154.31it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4174.39it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1446.23it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 985.57it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1158.03it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1160.90it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1167.20it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4127.87it/s]

Processing Correlation with 38 nodes and 37 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1515.63it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1016.04it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1160.07it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1092.73it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1116.74it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4071.63it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1453.21it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 986.80it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1110.14it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1107.10it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1166.19it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4244.54it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB with 19 nodes and 52 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1505.79it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1030.90it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1174.79it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1189.18it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1185.13it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4304.30it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1484.55it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1005.09it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1181.07it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1192.40it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1195.68it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4274.49it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem with 23 nodes and 34 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1541.86it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1063.67it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1180.89it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1121.65it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1149.34it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4282.23it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1441.76it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 990.54it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1201.92it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1168.57it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1194.40it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4462.91it/s]

Processing Simplified Golem $\cup$ Simplified PCMB with 24 nodes and 64 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1433.68it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1042.26it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1247.39it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1200.94it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1206.92it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4548.35it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1440.91it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1041.19it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1250.19it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1126.59it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1218.61it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4108.61it/s]

Processing Simplified Clinician Consensus with 16 nodes and 16 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1550.22it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1051.28it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1199.83it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1176.28it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1201.93it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4422.76it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1460.05it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1035.40it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1220.13it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1217.69it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1241.03it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4558.59it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB with 15 nodes and 14 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1578.60it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1055.08it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1279.28it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1236.18it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1214.43it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4506.01it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1547.75it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1074.06it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1212.94it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1216.50it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1243.73it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4684.00it/s]

Processing Simplified PCMB with 18 nodes and 50 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1613.47it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1095.31it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1238.35it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1233.45it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1238.14it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4548.12it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1565.13it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1076.86it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1230.66it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1237.75it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1234.66it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4600.60it/s]

Processing Simplified Golem with 12 nodes and 22 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1586.69it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1086.13it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1222.15it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1145.89it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1164.87it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4469.71it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1510.32it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1013.88it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1226.68it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1229.92it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1265.55it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4581.33it/s]

Processing Simplified Golem $\cap$ Simplified PCMB with 6 nodes and 5 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1623.98it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1046.16it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1260.28it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1275.62it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1234.51it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4606.13it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1553.26it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1075.52it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1278.55it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1243.53it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1219.02it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4402.69it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem with 5 nodes and 4 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1633.56it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1098.71it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1237.15it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1238.02it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1231.50it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4492.10it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1568.28it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1074.97it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1237.01it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1246.76it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1234.63it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4288.17it/s]

In [51]:
aurocs = []
auprcs = []
print(len(model_preds))
# Model Comparisons using DeLong Test
for (model1_name, model2_name) in combinations(model_preds.keys(), 2):
        if model1_name != 'Control': continue
        model1 = model_preds[model1_name]
        model2 = model_preds[model2_name]
        comparison_result1, comparison_result2 = compare_models(y_test.Outcome, model1, model2)
        aurocs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Z-score': f"{comparison_result1[0]:.4f}", 'P-value': f"{comparison_result1[1]:.3e}", 'p_numeric': comparison_result1[1]})
        auprcs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Avg Precision Model 1': f"{comparison_result2[0]:.4f}", 'Avg Precision Model 2': f"{comparison_result2[1]:.4f}", 'P-value': f"{comparison_result2[2]:.3e}", 'Benchmark': comparison_result2[3], 'Samples Mean': f"{comparison_result2[4]:.4f}", 'Samples Std': f"{comparison_result2[5]:.4f}"})
aurocs_df = pd.DataFrame(aurocs)
auprcs_df = pd.DataFrame(auprcs)
aurocs_df.to_csv('../Predictive Modeling/delong_test_biomarker_selection_auroc.csv', index=False)
auprcs_df.to_csv('../Predictive Modeling/delong_test_biomarker_selection_auprc.csv', index=False)
aurocs_df

11

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 788.90it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 818.66it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 822.09it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 810.22it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 774.95it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 814.84it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 805.62it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 788.52it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 797.97it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 774.42it/s]

,Model 1,Model 2,Z-score,P-value,p_numeric
0,Control,Correlation,-5.0469,4.491e-07,4.491476e-07
1,Control,Simplified Clinician Consensus $\cup$ Simplifi...,-3.1917,1.415e-03,1.414528e-03
2,Control,Simplified Clinician Consensus $\cup$ Simplifi...,-3.5661,3.623e-04,3.622732e-04
3,Control,Simplified Golem $\cup$ Simplified PCMB,-3.4346,5.934e-04,5.933930e-04
4,Control,Simplified Clinician Consensus,-3.8218,1.325e-04,1.324738e-04
5,Control,Simplified Clinician Consensus $\cap$ Simplifi...,-3.5869,3.346e-04,3.345848e-04
6,Control,Simplified PCMB,-3.7981,1.458e-04,1.457824e-04
7,Control,Simplified Golem,-3.1809,1.468e-03,1.468225e-03
8,Control,Simplified Golem $\cap$ Simplified PCMB,-3.7163,2.022e-04,2.021565e-04
9,Control,Simplified Clinician Consensus $\cap$ Simplifi...,-5.5644,2.630e-08,2.630400e-08

In [52]:
pd.DataFrame(results).to_csv('../Predictive Modeling/Biomarker Selection.csv', index=False)
pd.DataFrame(results)

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,LGBN,Control,"0.76 (0.72, 0.80)","0.90 (0.88, 0.92)","0.91 (0.89, 0.93)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.139,811,45
1,XGB,Control,"0.81 (0.78, 0.84)","0.93 (0.91, 0.95)","0.94 (0.92, 0.95)","0.80 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.089,811,45
2,LGBN,Correlation,"0.73 (0.69, 0.76)","0.87 (0.84, 0.89)","0.95 (0.93, 0.96)","0.74 (0.72, 0.77)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.133,113,37
3,XGB,Correlation,"0.75 (0.71, 0.78)","0.90 (0.88, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.108,113,37
4,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.76 (0.72, 0.79)","0.91 (0.89, 0.93)","0.93 (0.92, 0.95)","0.77 (0.74, 0.79)","0.83 (0.80, 0.85)","0.94 (0.94, 0.95)",0.136,315,18
5,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.79 (0.75, 0.82)","0.91 (0.89, 0.93)","0.92 (0.90, 0.93)","0.80 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.094,315,18
6,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.74 (0.70, 0.78)","0.90 (0.88, 0.92)","0.93 (0.92, 0.95)","0.77 (0.75, 0.79)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.140,389,22
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.92 (0.90, 0.94)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.092,389,22
8,LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.75 (0.71, 0.79)","0.91 (0.89, 0.92)","0.93 (0.92, 0.95)","0.77 (0.75, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.141,407,23
9,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.78 (0.75, 0.81)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.94 (0.94, 0.95)",0.093,407,23
10,LGBN,Simplified Clinician Consensus,"0.75 (0.72, 0.79)","0.90 (0.88, 0.92)","0.94 (0.93, 0.96)","0.76 (0.74, 0.78)","0.82 (0.80, 0.84)","0.94 (0.94, 0.95)",0.132,259,15
11,XGB,Simplified Clinician Consensus,"0.77 (0.74, 0.81)","0.91 (0.89, 0.93)","0.92 (0.90, 0.94)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.095,259,15
12,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.75 (0.72, 0.79)","0.90 (0.88, 0.92)","0.95 (0.93, 0.96)","0.76 (0.74, 0.78)","0.82 (0.80, 0.84)","0.94 (0.94, 0.95)",0.132,240,14
13,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.79 (0.75, 0.82)","0.91 (0.89, 0.93)","0.93 (0.91, 0.94)","0.80 (0.77, 0.82)","0.85 (0.82, 0.86)","0.95 (0.94, 0.96)",0.095,240,14
14,LGBN,Simplified PCMB,"0.76 (0.72, 0.79)","0.91 (0.89, 0.92)","0.94 (0.92, 0.95)","0.77 (0.74, 0.79)","0.83 (0.80, 0.85)","0.94 (0.94, 0.95)",0.136,296,17
15,XGB,Simplified PCMB,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.92 (0.91, 0.94)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.092,296,17
16,LGBN,Simplified Golem,"0.73 (0.70, 0.77)","0.90 (0.88, 0.91)","0.92 (0.90, 0.94)","0.75 (0.73, 0.78)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.138,199,11
17,XGB,Simplified Golem,"0.77 (0.74, 0.80)","0.91 (0.89, 0.93)","0.91 (0.90, 0.93)","0.79 (0.76, 0.81)","0.83 (0.82, 0.86)","0.94 (0.94, 0.95)",0.095,199,11
18,LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.71 (0.67, 0.76)","0.89 (0.87, 0.91)","0.93 (0.91, 0.94)","0.74 (0.71, 0.76)","0.80 (0.77, 0.82)","0.94 (0.93, 0.95)",0.131,88,5
19,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.76 (0.73, 0.80)","0.90 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,88,5
20,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.72 (0.67, 0.75)","0.88 (0.86, 0.90)","0.94 (0.92, 0.95)","0.73 (0.70, 0.75)","0.79 (0.77, 0.81)","0.94 (0.93, 0.94)",0.130,69,4
21,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.76, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.106,69,4

In [ ]:
# Plot calibration curves
for dag_name in calibrations:
    plt.figure(dpi=300, layout='constrained', figsize=(8, 5))
    plt.rcParams['font.size'] = 18
    prob_true, prob_pred = calibrations[dag_name]
    plt.plot(prob_pred, prob_true, marker='o', label='Calibration Curve')
    plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Perfect Calibration')
    plt.xlabel('Predicted Probability')
    plt.ylabel('True Probability')
    plt.xticks(np.arange(0, 1.1, 0.1))
    plt.grid()
    plt.savefig(f'../Predictive Modeling/Calibration Curves/Biomarker Selection - {dag_name.replace(" ", "_").replace("$\\cap$", "AND").replace("$\\cup$", "OR")}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

In [ ]:
vals = shap_values_biomarker_summary(shap_values)
auprc_top10 = pd.DataFrame(results).sort_values(by=['Average Precision'], ascending=False).head(10).DAG.unique().tolist()
plt.rcParams.update({  
'figure.figsize': (8, 10),   # Default figure size (inches)  
'figure.dpi': 300,          # Default DPI for figure creation  
'ytick.labelsize': 16,
'xtick.labelsize': 16,
'font.size': 18,
'lines.linewidth': 2,       # Default line width  
'figure.constrained_layout.use': True,
'pdf.fonttype': 42
}) 
for dag_name in auprc_top10:
    df = vals[dag_name].sort_values(ascending=True)
    plt.barh(df.index, df)
    plt.xlabel('Mean |SHAP value|')
    plt.ylabel('Biomarker')
    plt.savefig(f'../Predictive Modeling/Feature Importance/Biomarker Selection - {dag_name}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

## Experiment 2: No Drugs

In [55]:
results, shap_values, calibrations, model_preds = train_models(remove_drugs=True, remove_interventions=False)

Processing Control with 46 nodes and 45 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1555.14it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1051.90it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1103.63it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1142.17it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1127.26it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4002.31it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1469.21it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 996.69it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1198.94it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1198.42it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1149.53it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4433.90it/s]

Processing Correlation with 38 nodes and 37 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1508.92it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1057.76it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1180.43it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1156.69it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1193.61it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4310.03it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1493.06it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 975.86it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1199.34it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1189.01it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1183.40it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4447.55it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB with 19 nodes and 52 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1509.54it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1059.17it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1176.23it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1142.87it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1197.29it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4103.19it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1489.06it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1030.20it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1205.60it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1199.18it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1209.92it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4375.58it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem with 23 nodes and 34 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1533.18it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1066.15it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1168.65it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1173.59it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1163.08it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4249.15it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1494.11it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1008.75it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1198.27it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1198.87it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1168.14it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4319.54it/s]

Processing Simplified Golem $\cup$ Simplified PCMB with 24 nodes and 64 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1519.65it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1021.34it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1116.06it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1149.44it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1162.48it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4220.97it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1501.04it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 952.21it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1161.17it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1158.12it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1103.43it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3958.29it/s]

Processing Simplified Clinician Consensus with 16 nodes and 16 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1543.50it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1024.63it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1148.76it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1167.29it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1224.80it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4527.14it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1513.76it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 997.88it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1171.22it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1197.64it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1195.02it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4281.10it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB with 15 nodes and 14 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1499.23it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1067.44it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1194.57it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1223.61it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1174.07it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4330.47it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1494.00it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 970.46it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1198.57it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1213.21it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1200.72it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4558.38it/s]

Processing Simplified PCMB with 18 nodes and 50 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1513.64it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1018.23it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1152.89it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1195.37it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1182.77it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4246.05it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1498.08it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1037.78it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1187.99it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1231.25it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1109.31it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4231.03it/s]

Processing Simplified Golem with 12 nodes and 22 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1519.21it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1012.30it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1210.96it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1186.51it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1234.46it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4531.86it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1523.52it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1039.98it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1264.75it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1273.44it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1270.85it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4643.37it/s]

Processing Simplified Golem $\cap$ Simplified PCMB with 6 nodes and 5 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1551.73it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1040.17it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1232.16it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1217.94it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1201.53it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4544.48it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1400.08it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1047.50it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1237.93it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1263.83it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1162.39it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4593.12it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem with 5 nodes and 4 edges

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1607.18it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1072.87it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.02it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1207.52it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1205.26it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4502.46it/s]
Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1513.81it/s]
Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1010.30it/s]
Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1218.52it/s]
Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1230.23it/s]
Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1186.79it/s]
Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4453.05it/s]

In [56]:
pd.DataFrame(results).to_csv('../Predictive Modeling/No Drugs.csv', index=False)
pd.DataFrame(results)

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,LGBN,Control,"0.76 (0.71, 0.80)","0.90 (0.88, 0.92)","0.92 (0.91, 0.94)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.137,624,34
1,XGB,Control,"0.80 (0.77, 0.83)","0.92 (0.91, 0.94)","0.92 (0.90, 0.94)","0.80 (0.78, 0.82)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.090,624,34
2,LGBN,Correlation,"0.72 (0.68, 0.76)","0.86 (0.84, 0.89)","0.94 (0.93, 0.96)","0.73 (0.71, 0.75)","0.80 (0.77, 0.82)","0.94 (0.93, 0.95)",0.129,70,26
3,XGB,Correlation,"0.75 (0.71, 0.79)","0.89 (0.87, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.82 (0.80, 0.85)","0.94 (0.93, 0.95)",0.111,70,26
4,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.75 (0.71, 0.78)","0.90 (0.88, 0.92)","0.93 (0.91, 0.95)","0.75 (0.73, 0.78)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.133,198,11
5,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.77 (0.74, 0.81)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.81)","0.84 (0.81, 0.86)","0.94 (0.94, 0.95)",0.100,198,11
6,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.74 (0.70, 0.78)","0.90 (0.88, 0.92)","0.93 (0.91, 0.94)","0.76 (0.73, 0.78)","0.82 (0.79, 0.84)","0.94 (0.93, 0.95)",0.137,271,15
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.77 (0.74, 0.81)","0.91 (0.89, 0.93)","0.91 (0.89, 0.92)","0.80 (0.78, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.099,271,15
8,LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.74 (0.70, 0.78)","0.90 (0.88, 0.92)","0.92 (0.90, 0.94)","0.75 (0.73, 0.78)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.138,271,15
9,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.096,271,15
10,LGBN,Simplified Clinician Consensus,"0.75 (0.72, 0.79)","0.90 (0.88, 0.92)","0.94 (0.93, 0.96)","0.75 (0.73, 0.77)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.131,160,9
11,XGB,Simplified Clinician Consensus,"0.75 (0.72, 0.79)","0.90 (0.88, 0.92)","0.91 (0.90, 0.93)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.100,160,9
12,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.94 (0.92, 0.95)","0.74 (0.72, 0.77)","0.81 (0.78, 0.83)","0.94 (0.93, 0.95)",0.133,141,8
13,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.91 (0.89, 0.93)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.100,141,8
14,LGBN,Simplified PCMB,"0.74 (0.70, 0.77)","0.90 (0.88, 0.92)","0.93 (0.91, 0.95)","0.75 (0.72, 0.77)","0.81 (0.78, 0.83)","0.94 (0.93, 0.95)",0.134,179,10
15,XGB,Simplified PCMB,"0.78 (0.75, 0.81)","0.91 (0.89, 0.93)","0.92 (0.90, 0.93)","0.80 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.101,179,10
16,LGBN,Simplified Golem,"0.72 (0.68, 0.76)","0.89 (0.87, 0.91)","0.92 (0.90, 0.94)","0.74 (0.72, 0.76)","0.80 (0.78, 0.82)","0.94 (0.93, 0.95)",0.136,180,10
17,XGB,Simplified Golem,"0.78 (0.75, 0.81)","0.92 (0.90, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.098,180,10
18,LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.71 (0.67, 0.76)","0.89 (0.87, 0.91)","0.93 (0.91, 0.94)","0.74 (0.71, 0.76)","0.80 (0.77, 0.82)","0.94 (0.93, 0.95)",0.131,88,5
19,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.76 (0.73, 0.80)","0.90 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,88,5
20,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.72 (0.67, 0.75)","0.88 (0.86, 0.90)","0.94 (0.92, 0.95)","0.73 (0.70, 0.75)","0.79 (0.77, 0.81)","0.94 (0.93, 0.94)",0.130,69,4
21,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.76, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.106,69,4

In [57]:
aurocs = []
auprcs = []
print(len(model_preds))
# Model Comparisons using DeLong Test
for (model1_name, model2_name) in combinations(model_preds.keys(), 2):
        model1 = model_preds[model1_name]
        model2 = model_preds[model2_name]
        comparison_result1, comparison_result2 = compare_models(y_test.Outcome, model1, model2)
        aurocs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Z-score': f"{comparison_result1[0]:.4f}", 'P-value': f"{comparison_result1[1]:.3e}", 'p_numeric': comparison_result1[1]})
        auprcs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Avg Precision Model 1': f"{comparison_result2[0]:.4f}", 'Avg Precision Model 2': f"{comparison_result2[1]:.4f}", 'P-value': f"{comparison_result2[2]:.3e}", 'Benchmark': comparison_result2[3], 'Samples Mean': f"{comparison_result2[4]:.4f}", 'Samples Std': f"{comparison_result2[5]:.4f}"})
aurocs_df = pd.DataFrame(aurocs)
auprcs_df = pd.DataFrame(auprcs)
aurocs_df.to_csv('../Predictive Modeling/delong_test_no_drugs_auroc.csv', index=False)
auprcs_df.to_csv('../Predictive Modeling/delong_test_no_drugs_auprc.csv', index=False)

11

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 769.40it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 797.06it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 798.72it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 782.00it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 784.16it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 811.51it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 800.44it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 804.16it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 816.00it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 796.75it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 793.81it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 803.60it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 804.01it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 803.74it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 808.90it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 791.83it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 801.59it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 815.50it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 820.11it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 822.36it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 798.74it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 814.34it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 823.56it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 809.01it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 799.54it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 810.45it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 787.11it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 814.57it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 797.15it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 813.93it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 801.17it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 795.53it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 816.45it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 798.40it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 808.25it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 808.73it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 809.10it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 811.73it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 819.13it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 823.40it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 823.31it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 801.77it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 821.63it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 816.60it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 800.00it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 804.25it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 769.49it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 774.18it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 794.84it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 803.11it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 804.48it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 801.15it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 821.23it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 804.12it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 802.92it/s]

In [ ]:
# Plot calibration curves
for dag_name in calibrations:
    plt.figure(dpi=300, layout='constrained', figsize=(8, 5))
    plt.rcParams['font.size'] = 18
    prob_true, prob_pred = calibrations[dag_name]
    plt.plot(prob_pred, prob_true, marker='o', label=f'Calibration Curve')
    plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Perfect Calibration')
    plt.xlabel('Predicted Probability')
    plt.ylabel('True Probability')
    # plt.title(f'No Drugs - {dag_name}')
    plt.xticks(np.arange(0, 1.1, 0.1))
    plt.grid()
    plt.savefig(f'../Predictive Modeling/Calibration Curves/No Drugs - {dag_name.replace(" ", "_").replace("$\\cap$", "AND").replace("$\\cup$", "OR")}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

In [ ]:
vals = shap_values_biomarker_summary(shap_values)
auprc_top10 = pd.DataFrame(results).sort_values(by=['Average Precision'], ascending=False).head(10).DAG.unique().tolist()

plt.rcParams.update({  
'figure.figsize': (8, 10),   # Default figure size (inches)  
'figure.dpi': 300,          # Default DPI for figure creation  
'ytick.labelsize': 16,
'xtick.labelsize': 16,
'font.size': 18,
'lines.linewidth': 2,       # Default line width  
'figure.constrained_layout.use': True,
'pdf.fonttype': 42
}) 
for dag_name in auprc_top10:
    df = vals[dag_name].sort_values(ascending=True)
    plt.barh(df.index, df)
    plt.xlabel('Mean |SHAP value|')
    plt.ylabel('Biomarker')
    plt.savefig(f'../Predictive Modeling/Feature Importance/No Drugs - {dag_name}.pdf', bbox_inches='tight', dpi=300, transparent=False)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

## Experiment 3: No Drugs or Interventions

In [ ]:
results, shap_values, calibrations, model_preds = train_models(remove_drugs=True, remove_interventions=True)

In [ ]:
pd.DataFrame(results).to_csv('../Predictive Modeling/No Drugs or Interventions.csv', index=False)
pd.DataFrame(results)

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,LGBN,Control,"0.75 (0.71, 0.79)","0.90 (0.87, 0.92)","0.92 (0.90, 0.94)","0.77 (0.75, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.137,521,28
1,XGB,Control,"0.78 (0.75, 0.82)","0.92 (0.90, 0.93)","0.90 (0.88, 0.92)","0.80 (0.78, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.093,521,28
2,LGBN,Correlation,"0.69 (0.66, 0.74)","0.85 (0.82, 0.87)","0.94 (0.93, 0.96)","0.72 (0.70, 0.74)","0.78 (0.76, 0.81)","0.94 (0.93, 0.94)",0.130,53,20
3,XGB,Correlation,"0.75 (0.71, 0.78)","0.89 (0.87, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.83 (0.80, 0.85)","0.94 (0.93, 0.95)",0.114,53,20
4,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.69 (0.65, 0.74)","0.87 (0.85, 0.90)","0.91 (0.89, 0.93)","0.73 (0.70, 0.75)","0.78 (0.76, 0.81)","0.93 (0.93, 0.94)",0.145,131,7
5,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.89 (0.87, 0.91)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.104,131,7
6,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.72 (0.68, 0.75)","0.88 (0.86, 0.90)","0.90 (0.88, 0.93)","0.73 (0.71, 0.75)","0.79 (0.76, 0.81)","0.93 (0.93, 0.94)",0.142,204,11
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.77 (0.74, 0.81)","0.91 (0.90, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.101,204,11
8,LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.72 (0.68, 0.76)","0.88 (0.86, 0.90)","0.91 (0.89, 0.93)","0.73 (0.71, 0.76)","0.79 (0.77, 0.81)","0.93 (0.93, 0.94)",0.142,223,12
9,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.77 (0.73, 0.80)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.098,223,12
10,LGBN,Simplified Clinician Consensus,"0.68 (0.64, 0.72)","0.87 (0.84, 0.89)","0.92 (0.90, 0.94)","0.70 (0.68, 0.72)","0.76 (0.73, 0.78)","0.93 (0.92, 0.94)",0.146,93,5
11,XGB,Simplified Clinician Consensus,"0.73 (0.69, 0.76)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.75, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.108,93,5
12,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.68 (0.64, 0.72)","0.87 (0.84, 0.89)","0.92 (0.90, 0.94)","0.70 (0.68, 0.72)","0.76 (0.73, 0.78)","0.93 (0.92, 0.94)",0.146,93,5
13,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.73 (0.69, 0.76)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.75, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.108,93,5
14,LGBN,Simplified PCMB,"0.69 (0.65, 0.74)","0.87 (0.85, 0.90)","0.91 (0.89, 0.93)","0.73 (0.70, 0.75)","0.78 (0.76, 0.81)","0.93 (0.93, 0.94)",0.145,131,7
15,XGB,Simplified PCMB,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.89 (0.87, 0.91)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.104,131,7
16,LGBN,Simplified Golem,"0.69 (0.65, 0.73)","0.87 (0.85, 0.89)","0.91 (0.89, 0.93)","0.72 (0.70, 0.74)","0.78 (0.75, 0.80)","0.93 (0.92, 0.94)",0.142,149,8
17,XGB,Simplified Golem,"0.76 (0.72, 0.79)","0.91 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,149,8
18,LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.60 (0.56, 0.65)","0.85 (0.83, 0.87)","0.89 (0.86, 0.91)","0.67 (0.65, 0.69)","0.72 (0.70, 0.75)","0.92 (0.91, 0.93)",0.150,57,3
19,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.71 (0.68, 0.75)","0.89 (0.87, 0.91)","0.86 (0.84, 0.89)","0.77 (0.75, 0.80)","0.81 (0.79, 0.83)","0.93 (0.93, 0.94)",0.113,57,3
20,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.56 (0.51, 0.60)","0.82 (0.79, 0.84)","0.87 (0.84, 0.90)","0.63 (0.60, 0.65)","0.67 (0.64, 0.70)","0.91 (0.90, 0.92)",0.152,38,2
21,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.66 (0.62, 0.70)","0.86 (0.84, 0.88)","0.85 (0.82, 0.87)","0.74 (0.72, 0.76)","0.78 (0.76, 0.80)","0.93 (0.92, 0.93)",0.116,38,2

In [62]:
aurocs = []
auprcs = []
print(len(model_preds))
# Model Comparisons using DeLong Test
for (model1_name, model2_name) in combinations(model_preds.keys(), 2):
        model1 = model_preds[model1_name]
        model2 = model_preds[model2_name]
        comparison_result1, comparison_result2 = compare_models(y_test.Outcome, model1, model2)
        aurocs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Z-score': f"{comparison_result1[0]:.4f}", 'P-value': f"{comparison_result1[1]:.3e}", 'p_numeric': comparison_result1[1]})
        auprcs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Avg Precision Model 1': f"{comparison_result2[0]:.4f}", 'Avg Precision Model 2': f"{comparison_result2[1]:.4f}", 'P-value': f"{comparison_result2[2]:.3e}", 'Benchmark': comparison_result2[3], 'Samples Mean': f"{comparison_result2[4]:.4f}", 'Samples Std': f"{comparison_result2[5]:.4f}"})
aurocs_df = pd.DataFrame(aurocs)
auprcs_df = pd.DataFrame(auprcs)
aurocs_df.to_csv('../Predictive Modeling/delong_test_only_vitals_labs_auroc.csv', index=False)
auprcs_df.to_csv('../Predictive Modeling/delong_test_only_vitals_labs_auprc.csv', index=False)

11

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 744.26it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 766.78it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 775.51it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 774.32it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 763.76it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 773.86it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 792.26it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 798.02it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 782.39it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 783.82it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 765.82it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 772.61it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 757.75it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 777.60it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 768.86it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 758.10it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 777.40it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 798.21it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 802.88it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 800.46it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 757.26it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 774.25it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 795.68it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 808.77it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 770.43it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 761.53it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 774.65it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 765.64it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 761.74it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 774.52it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 747.74it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 766.73it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 753.98it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 762.79it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 760.36it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 771.24it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 769.72it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 737.93it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 743.89it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 773.58it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 815.30it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 777.73it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 784.27it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 760.41it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 766.04it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 789.30it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 752.50it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 760.26it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 746.13it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 774.45it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 753.62it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 762.11it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 755.12it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 746.39it/s]
Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 752.32it/s]

In [ ]:
# Plot calibration curves
for dag_name in calibrations:
    plt.figure(dpi=300, layout='constrained', figsize=(8, 5))
    plt.rcParams['font.size'] = 18
    prob_true, prob_pred = calibrations[dag_name]
    plt.plot(prob_pred, prob_true, marker='o', label=f'Calibration Curve')
    plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Perfect Calibration')
    plt.xlabel('Predicted Probability')
    plt.ylabel('True Probability')
    # plt.title(f'Only vitals and labs - {dag_name}')
    # plt.legend()
    plt.xticks(np.arange(0, 1.1, 0.1))
    plt.grid()
    plt.savefig(f'../Predictive Modeling/Calibration Curves/Only vitals and labs - {dag_name.replace(" ", "_").replace("$\\cap$", "AND").replace("$\\cup$", "OR")}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

In [64]:
vals = shap_values_biomarker_summary(shap_values)
auprc_top10 = pd.DataFrame(results).sort_values(by=['Average Precision'], ascending=False).head(10).DAG.unique().tolist()
plt.rcParams.update({  
'figure.figsize': (8, 10),   # Default figure size (inches)  
'figure.dpi': 300,          # Default DPI for figure creation  
'ytick.labelsize': 16,
'xtick.labelsize': 16,
'font.size': 18,
'lines.linewidth': 2,       # Default line width  
'figure.constrained_layout.use': True,
'pdf.fonttype': 42
}) 
for dag_name in auprc_top10:
    df = vals[dag_name].sort_values(ascending=True)
    plt.barh(df.index, df)
    plt.xlabel('Mean |SHAP value|')
    plt.ylabel('Biomarker')
    plt.savefig(f'../Predictive Modeling/Feature Importance/Only vitals and labs - {dag_name}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

INFO:fontTools.subset:maxp pruned
INFO:fontTools.subset:cmap pruned
INFO:fontTools.subset:kern dropped
INFO:fontTools.subset:post pruned
INFO:fontTools.subset:FFTM dropped
INFO:fontTools.subset:GPOS pruned
INFO:fontTools.subset:GSUB pruned
INFO:fontTools.subset:glyf pruned
INFO:fontTools.subset:Added gid0 to subset
INFO:fontTools.subset:Added first four glyphs to subset
INFO:fontTools.subset:Closing glyph list over 'MATH': 52 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'a', 'b', 'bar', 'c', 'd', 'e', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'x', 'y', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 16, 17, 19, 20, 21, 22, 23, 24, 25, 36, 37, 38, 39, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 92, 95]
INFO:fontTools.subset:Closed glyph list over 'MATH': 52 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'a', 'b', 'bar', 'c', 'd', 'e', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'x', 'y', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 16, 17, 19, 20, 21, 22, 23, 24, 25, 36, 37, 38, 39, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 92, 95]
INFO:fontTools.subset:Closing glyph list over 'GSUB': 52 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'a', 'b', 'bar', 'c', 'd', 'e', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'x', 'y', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 16, 17, 19, 20, 21, 22, 23, 24, 25, 36, 37, 38, 39, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 92, 95]
INFO:fontTools.subset:Closed glyph list over 'GSUB': 57 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'a', 'b', 'bar', 'c', 'd', 'e', 'f', 'fi', 'five', 'fl', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'six', 'space', 't', 'three', 'two', 'u', 'uniFB00', 'uniFB03', 'uniFB04', 'v', 'x', 'y', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 16, 17, 19, 20, 21, 22, 23, 24, 25, 36, 37, 38, 39, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 92, 95, 5038, 5039, 5040, 5041, 5042]
INFO:fontTools.subset:Closing glyph list over 'glyf': 57 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'a', 'b', 'bar', 'c', 'd', 'e', 'f', 'fi', 'five', 'fl', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'six', 'space', 't', 'three', 'two', 'u', 'uniFB00', 'uniFB03', 'uniFB04', 'v', 'x', 'y', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 16, 17, 19, 20, 21, 22, 23, 24, 25, 36, 37, 38, 39, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 92, 95, 5038, 5039, 5040, 5041, 5042]
INFO:fontTools.subset:Closed glyph list over 'glyf': 57 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'a', 'b', 'bar', 'c', 'd', 'e', 'f', 'fi', 'five', 'fl', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'six', 'space', 't', 'three', 'two', 'u', 'uniFB00', 'uniFB03', 'uniFB04', 'v', 'x', 'y', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 16, 17, 19, 20, 21, 22, 23, 24, 25, 36, 37, 38, 39, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 92, 95, 5038, 5039, 5040, 5041, 5042]
INFO:fontTools.subset:Retaining 57 glyphs
INFO:fontTools.subset:head subsetting not needed
INFO:fontTools.subset:hhea subsetting not needed
INFO:fontTools.subset:maxp subsetting not needed
INFO:fontTools.subset:OS/2 subsetting not needed
INFO:fontTools.subset:hmtx subsetted
INFO:fontTools.subset:cmap subsetted
INFO:fontTools.subset:fpgm subsetting not needed
INFO:fontTools.subset:prep subsetting not needed
INFO:fontTools.subset:cvt  subsetting not needed
INFO:fontTools.subset:loca subsetting not needed
INFO:fontTools.subset:post subsetted
INFO:fontTools.subset:gasp subsetting not needed
INFO:fontTools.subset:MATH subsetted
INFO:fontTools.subset:GDEF subsetted
INFO:fontTools.subset:GPOS subsetted
INFO:fontTools.subset:GSUB subsetted
INFO:fontTools.subset:name subsetting not needed
INFO:fontTools.subset:glyf subsetted
INFO:fontTools.subset:head pruned
INFO:fontTools.subset:OS/2 Unicode ranges pruned: [0]
INFO:fontTools.subset:OS/2 CodePage ranges pruned: [0]
INFO:fontTools.subset:glyf pruned
INFO:fontTools.subset:GDEF pruned
INFO:fontTools.subset:GPOS pruned
INFO:fontTools.subset:GSUB pruned
INFO:fontTools.subset:name pruned
INFO:fontTools.subset:maxp pruned
INFO:fontTools.subset:cmap pruned
INFO:fontTools.subset:kern dropped
INFO:fontTools.subset:post pruned
INFO:fontTools.subset:FFTM dropped
INFO:fontTools.subset:GPOS pruned
INFO:fontTools.subset:GSUB pruned
INFO:fontTools.subset:glyf pruned
INFO:fontTools.subset:Added gid0 to subset
INFO:fontTools.subset:Added first four glyphs to subset
INFO:fontTools.subset:Closing glyph list over 'MATH': 40 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'MATH': 40 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closing glyph list over 'GSUB': 40 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'GSUB': 40 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closing glyph list over 'glyf': 40 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'glyf': 40 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Retaining 40 glyphs
INFO:fontTools.subset:head subsetting not needed
INFO:fontTools.subset:hhea subsetting not needed
INFO:fontTools.subset:maxp subsetting not needed
INFO:fontTools.subset:OS/2 subsetting not needed
INFO:fontTools.subset:hmtx subsetted
INFO:fontTools.subset:cmap subsetted
INFO:fontTools.subset:fpgm subsetting not needed
INFO:fontTools.subset:prep subsetting not needed
INFO:fontTools.subset:cvt  subsetting not needed
INFO:fontTools.subset:loca subsetting not needed
INFO:fontTools.subset:post subsetted
INFO:fontTools.subset:gasp subsetting not needed
INFO:fontTools.subset:MATH subsetted
INFO:fontTools.subset:GDEF subsetted
INFO:fontTools.subset:GPOS subsetted
INFO:fontTools.subset:GSUB subsetted
INFO:fontTools.subset:name subsetting not needed
INFO:fontTools.subset:glyf subsetted
INFO:fontTools.subset:head pruned
INFO:fontTools.subset:OS/2 Unicode ranges pruned: [0]
INFO:fontTools.subset:OS/2 CodePage ranges pruned: [0]
INFO:fontTools.subset:glyf pruned
INFO:fontTools.subset:GDEF pruned
INFO:fontTools.subset:GPOS pruned
INFO:fontTools.subset:GSUB pruned
INFO:fontTools.subset:name pruned
INFO:fontTools.subset:maxp pruned
INFO:fontTools.subset:cmap pruned
INFO:fontTools.subset:kern dropped
INFO:fontTools.subset:post pruned
INFO:fontTools.subset:FFTM dropped
INFO:fontTools.subset:GPOS pruned
INFO:fontTools.subset:GSUB pruned
INFO:fontTools.subset:glyf pruned
INFO:fontTools.subset:Added gid0 to subset
INFO:fontTools.subset:Added first four glyphs to subset
INFO:fontTools.subset:Closing glyph list over 'MATH': 41 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 42, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'MATH': 41 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 42, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closing glyph list over 'GSUB': 41 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 42, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'GSUB': 41 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 42, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closing glyph list over 'glyf': 41 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 42, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'glyf': 41 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'G', 'H', 'L', 'M', 'O', 'P', 'S', 'T', 'W', 'a', 'bar', 'c', 'd', 'e', 'four', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'p', 'period', 'r', 's', 'six', 'space', 't', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 21, 23, 25, 36, 37, 38, 39, 42, 43, 47, 48, 50, 51, 54, 55, 58, 68, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Retaining 41 glyphs
INFO:fontTools.subset:head subsetting not needed
INFO:fontTools.subset:hhea subsetting not needed
INFO:fontTools.subset:maxp subsetting not needed
INFO:fontTools.subset:OS/2 subsetting not needed
INFO:fontTools.subset:hmtx subsetted
INFO:fontTools.subset:cmap subsetted
INFO:fontTools.subset:fpgm subsetting not needed
INFO:fontTools.subset:prep subsetting not needed
INFO:fontTools.subset:cvt  subsetting not needed
INFO:fontTools.subset:loca subsetting not needed
INFO:fontTools.subset:post subsetted
INFO:fontTools.subset:gasp subsetting not needed
INFO:fontTools.subset:MATH subsetted
INFO:fontTools.subset:GDEF subsetted
INFO:fontTools.subset:GPOS subsetted
INFO:fontTools.subset:GSUB subsetted
INFO:fontTools.subset:name subsetting not needed
INFO:fontTools.subset:glyf subsetted
INFO:fontTools.subset:head pruned
INFO:fontTools.subset:OS/2 Unicode ranges pruned: [0]
INFO:fontTools.subset:OS/2 CodePage ranges pruned: [0]
INFO:fontTools.subset:glyf pruned
INFO:fontTools.subset:GDEF pruned
INFO:fontTools.subset:GPOS pruned
INFO:fontTools.subset:GSUB pruned
INFO:fontTools.subset:name pruned
INFO:fontTools.subset:maxp pruned
INFO:fontTools.subset:cmap pruned
INFO:fontTools.subset:kern dropped
INFO:fontTools.subset:post pruned
INFO:fontTools.subset:FFTM dropped
INFO:fontTools.subset:GPOS pruned
INFO:fontTools.subset:GSUB pruned
INFO:fontTools.subset:glyf pruned
INFO:fontTools.subset:Added gid0 to subset
INFO:fontTools.subset:Added first four glyphs to subset
INFO:fontTools.subset:Closing glyph list over 'MATH': 41 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'D', 'G', 'H', 'L', 'M', 'P', 'S', 'T', 'a', 'bar', 'c', 'd', 'e', 'eight', 'five', 'four', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'seven', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 36, 37, 39, 42, 43, 47, 48, 51, 54, 55, 68, 70, 71, 72, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'MATH': 41 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'D', 'G', 'H', 'L', 'M', 'P', 'S', 'T', 'a', 'bar', 'c', 'd', 'e', 'eight', 'five', 'four', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'seven', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 36, 37, 39, 42, 43, 47, 48, 51, 54, 55, 68, 70, 71, 72, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closing glyph list over 'GSUB': 41 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'D', 'G', 'H', 'L', 'M', 'P', 'S', 'T', 'a', 'bar', 'c', 'd', 'e', 'eight', 'five', 'four', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'seven', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 36, 37, 39, 42, 43, 47, 48, 51, 54, 55, 68, 70, 71, 72, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'GSUB': 41 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'D', 'G', 'H', 'L', 'M', 'P', 'S', 'T', 'a', 'bar', 'c', 'd', 'e', 'eight', 'five', 'four', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'seven', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 36, 37, 39, 42, 43, 47, 48, 51, 54, 55, 68, 70, 71, 72, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closing glyph list over 'glyf': 41 glyphs before
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'D', 'G', 'H', 'L', 'M', 'P', 'S', 'T', 'a', 'bar', 'c', 'd', 'e', 'eight', 'five', 'four', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'seven', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 36, 37, 39, 42, 43, 47, 48, 51, 54, 55, 68, 70, 71, 72, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Closed glyph list over 'glyf': 41 glyphs after
INFO:fontTools.subset:Glyph names: ['.notdef', '.null', 'A', 'B', 'D', 'G', 'H', 'L', 'M', 'P', 'S', 'T', 'a', 'bar', 'c', 'd', 'e', 'eight', 'five', 'four', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'period', 'r', 's', 'seven', 'six', 'space', 't', 'three', 'two', 'u', 'v', 'zero']
INFO:fontTools.subset:Glyph IDs:   [0, 1, 2, 3, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 36, 37, 39, 42, 43, 47, 48, 51, 54, 55, 68, 70, 71, 72, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 95]
INFO:fontTools.subset:Retaining 41 glyphs
INFO:fontTools.subset:head subsetting not needed
INFO:fontTools.subset:hhea subsetting not needed
INFO:fontTools.subset:maxp subsetting not needed
INFO:fontTools.subset:OS/2 subsetting not needed
INFO:fontTools.subset:hmtx subsetted
INFO:fontTools.subset:cmap subsetted
INFO:fontTools.subset:fpgm subsetting not needed
INFO:fontTools.subset:prep subsetting not needed
INFO:fontTools.subset:cvt  subsetting not needed
INFO:fontTools.subset:loca subsetting not needed
INFO:fontTools.subset:post subsetted
INFO:fontTools.subset:gasp subsetting not needed
INFO:fontTools.subset:MATH subsetted
INFO:fontTools.subset:GDEF subsetted
INFO:fontTools.subset:GPOS subsetted
INFO:fontTools.subset:GSUB subsetted
INFO:fontTools.subset:name subsetting not needed
INFO:fontTools.subset:glyf subsetted
INFO:fontTools.subset:head pruned