# DAG Parameterization — Generative LGBN

This notebook implements a **generative classifier** using class-conditional Linear Gaussian Bayesian Networks.

Instead of treating `Outcome` as a Gaussian variable (the original LGBN approach, which misspecifies the binary outcome), this approach:
1. Fits separate LGBNs over the **feature sub-network only** — one for `Outcome=0`, one for `Outcome=1`
2. Applies Bayes rule: `P(Outcome=1 | X) ∝ P(X | Outcome=1) · P(Outcome=1)`
3. Computes likelihoods **node-by-node** using each CPD's linear parameters, avoiding the singular full covariance matrix issue at high feature counts

Results are structured identically to `DAG Parameterization.ipynb` for direct comparison.

In [1]:
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import re
import glob
from scipy.stats import norm

from sklearn.experimental import enable_iterative_imputer  # noqa
from sklearn.calibration import calibration_curve

from pgmpy.base import DAG
from pgmpy.models import LinearGaussianBayesianNetwork

from sklearn.metrics import roc_auc_score, average_precision_score
from pycalib.metrics import ECE

import xgboost
import shap

from MLstatkit import Bootstrapping, Delong_test, Permutation_test
from itertools import combinations

/Users/eddie/.pixi-envs/dag-parameterization-2248481784431669736/envs/default/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Data preparation

In [2]:
X_train = pd.read_csv('../../Data Pre-processing/X_train_c12_w48_imp.csv', index_col=0)
X_test  = pd.read_csv('../../Data Pre-processing/X_test_c12_w48_imp.csv',  index_col=0)

print(X_train.shape, X_test.shape)

X_train = X_train.loc[:, X_train.var() >= 0.01]
X_test  = X_test.filter(items=X_train.columns)
print(X_train.shape, X_test.shape)

X_train_imp = pd.read_csv('../../Data Pre-processing/X_train_c12_w48_mice.csv', index_col=0)
X_test_imp  = pd.read_csv('../../Data Pre-processing/X_test_c12_w48_mice.csv',  index_col=0)

y_train = pd.read_csv('../../Data Pre-processing/y_train_c12_w48_imp.csv', index_col=[0,1]).groupby('uid').max()
y_test  = pd.read_csv('../../Data Pre-processing/y_test_c12_w48_imp.csv',  index_col=[0,1]).groupby('uid').max()

correlation_threshold = 0.3
X_train_corr = X_train_imp.loc[:, X_train_imp.corrwith(y_train['Outcome']).abs() >= correlation_threshold]
print(X_train_corr.shape)

(13054, 990) (3895, 990)
(13054, 811) (3895, 811)

(13054, 113)

## Load DAGs

In [3]:
adjacency_files = glob.glob("../DAGs/*_adjacency.csv")

dags = {}
dags['Control']     = nx.from_edgelist([(col, 'Outcome') for col in X_train_imp.columns.str.replace(r'(_.+)?$', '', regex=True).unique().tolist() if col != 'Outcome'], create_using=nx.DiGraph())
dags['Correlation'] = nx.from_edgelist([(col, 'Outcome') for col in X_train_corr.columns.str.replace(r'(_.+)?$', '', regex=True).unique().tolist() if col != 'Outcome'], create_using=nx.DiGraph())

for file in adjacency_files:
    dag_name = re.search(r'../DAGs/(.*)_adjacency.csv', file).group(1)
    dag_name = dag_name.replace('x', '$\\cap$')
    dag_name = dag_name.replace(' + ', ' $\\cup$ ')
    dags[dag_name] = nx.DiGraph(pd.read_csv(file, index_col=0))

dags.pop('Golem $\\cap$ PCMB')
list(dags.keys())

['Control',
 'Correlation',
 'Clinician Consensus $\\cup$ Golem',
 'Simplified Clinician Consensus $\\cup$ Simplified PCMB',
 'Simplified Clinician Consensus $\\cup$ Simplified Golem',
 'Clinician Consensus $\\cup$ PCMB',
 'Simplified Golem $\\cup$ Simplified PCMB',
 'Clinician Consensus',
 'Simplified Clinician Consensus',
 'Clinician Consensus $\\cap$ PCMB',
 'Golem',
 'PCMB',
 'Simplified Clinician Consensus $\\cap$ Simplified PCMB',
 'Simplified PCMB',
 'Clinician Consensus $\\cap$ Golem',
 'Simplified Golem',
 'Golem $\\cup$ PCMB',
 'Simplified Golem $\\cap$ Simplified PCMB',
 'Simplified Clinician Consensus $\\cap$ Simplified Golem']

## Generative LGBN Classifier

### Design
- `Outcome` is **not** a node in either LGBN — it is the class label.
- Two separate LGBNs are fit: one on `Outcome=0` samples, one on `Outcome=1` samples.
- Prediction uses the node-by-node factored log-likelihood to avoid inverting a potentially singular full covariance matrix.
- `predict_proba` is sklearn-compatible so it drops into the existing `performance_report` function unchanged.

In [4]:
def lgbn_log_likelihood(model, data):
    """Sum of node-wise conditional log-likelihoods over all nodes in the LGBN.

    LinearGaussianCPD stores:
      cpd.beta     — array where beta[0] is the intercept and beta[1:] are
                     coefficients for cpd.evidence (in matching order)
      cpd.std      — standard deviation of the node's Gaussian noise
      cpd.evidence — list of parent variable names
    """
    log_lik = np.zeros(len(data))
    for node in model.nodes():
        cpd = model.get_cpds(node)
        parents = cpd.evidence if cpd.evidence else []
        if parents:
            mu = cpd.beta[0] + data[parents].values @ cpd.beta[1:]
        else:
            mu = np.full(len(data), cpd.beta[0])
        log_lik += norm.logpdf(data[node].values, loc=mu, scale=cpd.std)
    return log_lik


class GenerativeLGBN:
    """
    Generative classifier using class-conditional Linear Gaussian Bayesian Networks.

    Fits P(X | class) for each class via a separate LGBN over the feature
    sub-network, then computes P(class | X) via Bayes rule.

    Features with no edges to other features are added as isolated nodes so
    they are still modeled as marginal Gaussians — this handles star DAGs
    (e.g. Control) where all edges point to Outcome and feature_edges is empty.

    Parameters
    ----------
    feature_edges : list of (str, str)
        Directed edges among features only — must not include 'Outcome'.
    """

    def __init__(self, feature_edges):
        self.feature_edges = feature_edges

    def fit(self, X, y):
        y = np.asarray(y)
        self.classes_ = np.array([0, 1])
        self.log_prior_ = np.array([
            np.log((y == 0).mean()),
            np.log((y == 1).mean()),
        ])
        self.lgbn_neg_ = LinearGaussianBayesianNetwork(self.feature_edges)
        self.lgbn_pos_ = LinearGaussianBayesianNetwork(self.feature_edges)
        # Ensure every feature column is a node, even if it has no edges.
        # Without this, star-topology DAGs (all edges go to Outcome) produce
        # an empty graph and return constant log-likelihoods for all samples.
        for col in X.columns:
            if col not in self.lgbn_neg_.nodes():
                self.lgbn_neg_.add_node(col)
            if col not in self.lgbn_pos_.nodes():
                self.lgbn_pos_.add_node(col)
        self.lgbn_neg_.fit(X[y == 0].reset_index(drop=True))
        self.lgbn_pos_.fit(X[y == 1].reset_index(drop=True))
        return self

    def predict_proba(self, X):
        X = X.reset_index(drop=True)
        log_lik_pos = lgbn_log_likelihood(self.lgbn_pos_, X) + self.log_prior_[1]
        log_lik_neg = lgbn_log_likelihood(self.lgbn_neg_, X) + self.log_prior_[0]
        log_sum = np.logaddexp(log_lik_pos, log_lik_neg)
        p1 = np.clip(np.exp(log_lik_pos - log_sum), 0.0, 1.0)
        return np.column_stack([1 - p1, p1])

## Evaluation functions

In [5]:
def performance_report(X, y, model):
    y_prob = model.predict_proba(X)[:, 1]

    n_bootstraps = 1000
    ap,       ap_lo,        ap_hi       = Bootstrapping(y.values, y_prob, metric_str='average_precision', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    auroc,    auroc_lo,     auroc_hi    = Bootstrapping(y.values, y_prob, metric_str='roc_auc',           n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    prec,     prec_lo,      prec_hi     = Bootstrapping(y.values, y_prob, metric_str='precision',         n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    rec,      rec_lo,       rec_hi      = Bootstrapping(y.values, y_prob, metric_str='recall',            n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    f1,       f1_lo,        f1_hi       = Bootstrapping(y.values, y_prob, metric_str='f1',                n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    acc,      acc_lo,       acc_hi      = Bootstrapping(y.values, y_prob, metric_str='accuracy',          n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    ece = ECE(y.values, y_prob.reshape(-1, 1), bins=50)

    return {
        'Average Precision': f"{ap:.2f} ({ap_lo:.2f}, {ap_hi:.2f})",
        'AUROC':             f"{auroc:.2f} ({auroc_lo:.2f}, {auroc_hi:.2f})",
        'Precision':         f"{prec:.2f} ({prec_lo:.2f}, {prec_hi:.2f})",
        'Recall':            f"{rec:.2f} ({rec_lo:.2f}, {rec_hi:.2f})",
        'F1 Score':          f"{f1:.2f} ({f1_lo:.2f}, {f1_hi:.2f})",
        'Accuracy':          f"{acc:.2f} ({acc_lo:.2f}, {acc_hi:.2f})",
        'ECE':               f"{ece:.3f}",
    }


def compare_models(y, y_prob1, y_prob2):
    z, p = Delong_test(y.values, y_prob1, y_prob2, return_ci=False, return_auc=False)
    result = Permutation_test(y.values, y_prob1, y_prob2, metric_str='average_precision')
    return (z, p), result

## Model training

In [6]:
drugs = [
    'Midazolam', 'Fentanyl', 'Olanzapine', 'Haloperidol',
    'Dexmedetomidine', 'Lorazepam', 'Morphine', 'Hydromorphone',
    'Dopamine', 'Cisatracurium', 'Epinephrine', 'Norepinephrine',
    'Milrinone', 'Dobutamine',
]
intervention_nodes = [
    'CRRT Therapy Type', 'ECMO Type', 'Ventilated',
    'Pupillary Reaction', 'Peds Coma Score', 'Endotracheal tube',
]


def train_models(remove_drugs=False, remove_interventions=False):
    results = []
    calibrations = {}
    model_preds = {}

    for dag_name, dag in dags.items():

        print(f"Processing {dag_name} — {dag.number_of_nodes()} nodes, {dag.number_of_edges()} edges")

        nodes_in_dag = list(dag.nodes())

        if remove_drugs:
            nodes_in_dag = [n for n in nodes_in_dag if not any(d in n for d in drugs)]
        if remove_interventions:
            nodes_in_dag = [n for n in nodes_in_dag if n not in intervention_nodes]

        # --- feature expansion ---
        if dag_name == 'Correlation':
            source = X_train_corr
        else:
            source = X_train_imp

        if 'Simplified' in dag_name or dag_name in ['Control', 'Correlation']:
            # Node names are high-level biomarker names; expand to feature columns
            features_in_dag = [
                col for col in source.columns
                if any(re.search(rf'^{re.escape(node)}(_.+)?$', col) for node in nodes_in_dag)
            ]
            train_dag = nx.DiGraph()
            for node in nodes_in_dag:
                ends = list(dag.successors(node))
                from_features = [c for c in features_in_dag + ['Outcome'] if re.search(rf'^{re.escape(node)}(_.+)?$', c)]
                to_features   = [c for c in features_in_dag + ['Outcome'] if any(re.search(rf'^{re.escape(e)}(_.+)?$', c) for e in ends)]
                for f in from_features:
                    for t in to_features:
                        train_dag.add_edge(f, t)
        else:
            # Node names are already feature column names
            features_in_dag = X_train_imp.filter(items=nodes_in_dag).columns.tolist()
            train_dag = dag.subgraph(features_in_dag + ['Outcome']).copy()

        n_biomarkers = len(set(re.sub(r'(_.+)?$', '', c) for c in features_in_dag))

        # Feature-only edges — Outcome stripped from the LGBN structure
        feature_edges = [
            (u, v) for u, v in train_dag.edges()
            if u != 'Outcome' and v != 'Outcome'
        ]

        X_tr = X_train_imp[features_in_dag] if dag_name != 'Correlation' else X_train_corr[features_in_dag]
        X_te = X_test_imp[features_in_dag]  if dag_name != 'Correlation' else X_test_imp.filter(features_in_dag)

        # --- Generative LGBN ---
        gen_lgbn = GenerativeLGBN(feature_edges)
        gen_lgbn.fit(X_tr, y_train['Outcome'].values)

        row = {'Model': 'Generative LGBN', 'DAG': dag_name}
        row.update(performance_report(X_te, y_test.Outcome, gen_lgbn))
        row['# Features']   = len(features_in_dag)
        row['# Biomarkers'] = n_biomarkers
        results.append(row)

        # --- XGBoost ---
        xgb = xgboost.XGBClassifier(
            objective='binary:logistic', random_state=42, eval_metric='aucpr'
        )
        X_tr_xgb = X_train[features_in_dag] if dag_name != 'Correlation' else X_train.filter(features_in_dag)
        X_te_xgb = X_test[features_in_dag]  if dag_name != 'Correlation' else X_test.filter(features_in_dag)
        xgb.fit(X_tr_xgb, y_train.Outcome)

        row_xgb = {'Model': 'XGB', 'DAG': dag_name}
        row_xgb.update(performance_report(X_te_xgb, y_test.Outcome, xgb))
        row_xgb['# Features']   = len(features_in_dag)
        row_xgb['# Biomarkers'] = n_biomarkers
        results.append(row_xgb)

        model_preds[dag_name] = {
            'Generative LGBN': gen_lgbn.predict_proba(X_te)[:, 1],
            'XGB':             xgb.predict_proba(X_te_xgb)[:, 1],
        }

        calibrations[dag_name] = calibration_curve(
            y_test.Outcome, xgb.predict_proba(X_te_xgb)[:, 1], n_bins=50
        )

    return results, calibrations, model_preds

## Experiment 1: All features

In [7]:
results1, calibrations1, model_preds1 = train_models(remove_drugs=False, remove_interventions=False)

Processing Control — 46 nodes, 45 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1356.75it/s]

Bootstrapping average_precision:  28%|██▊       | 275/1000 [00:00<00:00, 1375.57it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1379.84it/s]

Bootstrapping average_precision:  56%|█████▌    | 555/1000 [00:00<00:00, 1390.86it/s]

Bootstrapping average_precision:  70%|██████▉   | 697/1000 [00:00<00:00, 1399.71it/s]

Bootstrapping average_precision:  84%|████████▍ | 839/1000 [00:00<00:00, 1403.43it/s]

Bootstrapping average_precision:  98%|█████████▊| 980/1000 [00:00<00:00, 1402.50it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1393.58it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 90/1000 [00:00<00:01, 890.44it/s]

Bootstrapping roc_auc:  18%|█▊        | 180/1000 [00:00<00:00, 878.88it/s]

Bootstrapping roc_auc:  27%|██▋       | 269/1000 [00:00<00:00, 882.48it/s]

Bootstrapping roc_auc:  36%|███▌      | 358/1000 [00:00<00:00, 884.91it/s]

Bootstrapping roc_auc:  45%|████▍     | 447/1000 [00:00<00:00, 884.15it/s]

Bootstrapping roc_auc:  54%|█████▎    | 537/1000 [00:00<00:00, 886.37it/s]

Bootstrapping roc_auc:  63%|██████▎   | 627/1000 [00:00<00:00, 889.06it/s]

Bootstrapping roc_auc:  72%|███████▏  | 716/1000 [00:00<00:00, 877.80it/s]

Bootstrapping roc_auc:  80%|████████  | 805/1000 [00:00<00:00, 879.87it/s]

Bootstrapping roc_auc:  89%|████████▉ | 894/1000 [00:01<00:00, 882.58it/s]

Bootstrapping roc_auc:  98%|█████████▊| 984/1000 [00:01<00:00, 887.22it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 883.89it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1214.61it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1215.11it/s]

Bootstrapping precision:  37%|███▋      | 368/1000 [00:00<00:00, 1223.18it/s]

Bootstrapping precision:  49%|████▉     | 491/1000 [00:00<00:00, 1220.34it/s]

Bootstrapping precision:  61%|██████▏   | 614/1000 [00:00<00:00, 1223.44it/s]

Bootstrapping precision:  74%|███████▎  | 737/1000 [00:00<00:00, 1221.90it/s]

Bootstrapping precision:  86%|████████▌ | 860/1000 [00:00<00:00, 1221.55it/s]

Bootstrapping precision:  98%|█████████▊| 984/1000 [00:00<00:00, 1227.25it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1222.40it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 124/1000 [00:00<00:00, 1234.22it/s]

Bootstrapping recall:  25%|██▍       | 248/1000 [00:00<00:00, 1224.49it/s]

Bootstrapping recall:  37%|███▋      | 371/1000 [00:00<00:00, 1207.68it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1198.73it/s]

Bootstrapping recall:  61%|██████    | 612/1000 [00:00<00:00, 1194.46it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1194.31it/s]

Bootstrapping recall:  85%|████████▌ | 852/1000 [00:00<00:00, 1181.80it/s]

Bootstrapping recall:  97%|█████████▋| 971/1000 [00:00<00:00, 1169.21it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1185.70it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1164.92it/s]

Bootstrapping f1:  23%|██▎       | 234/1000 [00:00<00:00, 1160.48it/s]

Bootstrapping f1:  35%|███▌      | 353/1000 [00:00<00:00, 1171.48it/s]

Bootstrapping f1:  48%|████▊     | 475/1000 [00:00<00:00, 1187.91it/s]

Bootstrapping f1:  60%|█████▉    | 598/1000 [00:00<00:00, 1200.63it/s]

Bootstrapping f1:  72%|███████▏  | 720/1000 [00:00<00:00, 1205.24it/s]

Bootstrapping f1:  84%|████████▍ | 841/1000 [00:00<00:00, 1205.09it/s]

Bootstrapping f1:  96%|█████████▋| 963/1000 [00:00<00:00, 1208.45it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1197.55it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 361/1000 [00:00<00:00, 3602.87it/s]

Bootstrapping accuracy:  72%|███████▏  | 722/1000 [00:00<00:00, 3545.73it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3510.37it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1361.88it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1341.85it/s]

Bootstrapping average_precision:  41%|████      | 409/1000 [00:00<00:00, 1333.56it/s]

Bootstrapping average_precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1349.78it/s]

Bootstrapping average_precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1313.84it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1330.24it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1341.68it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1338.95it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 859.66it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 862.64it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 870.88it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 873.62it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 871.32it/s]

Bootstrapping roc_auc:  53%|█████▎    | 526/1000 [00:00<00:00, 868.77it/s]

Bootstrapping roc_auc:  61%|██████▏   | 613/1000 [00:00<00:00, 866.83it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 866.93it/s]

Bootstrapping roc_auc:  79%|███████▊  | 787/1000 [00:00<00:00, 866.39it/s]

Bootstrapping roc_auc:  87%|████████▋ | 874/1000 [00:01<00:00, 863.34it/s]

Bootstrapping roc_auc:  96%|█████████▌| 961/1000 [00:01<00:00, 863.77it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.05it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 123/1000 [00:00<00:00, 1224.02it/s]

Bootstrapping precision:  25%|██▍       | 248/1000 [00:00<00:00, 1234.51it/s]

Bootstrapping precision:  37%|███▋      | 373/1000 [00:00<00:00, 1239.40it/s]

Bootstrapping precision:  50%|████▉     | 498/1000 [00:00<00:00, 1240.02it/s]

Bootstrapping precision:  62%|██████▏   | 623/1000 [00:00<00:00, 1243.01it/s]

Bootstrapping precision:  75%|███████▍  | 748/1000 [00:00<00:00, 1242.79it/s]

Bootstrapping precision:  87%|████████▋ | 873/1000 [00:00<00:00, 1242.92it/s]

Bootstrapping precision: 100%|█████████▉| 998/1000 [00:00<00:00, 1242.56it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1239.93it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 124/1000 [00:00<00:00, 1236.40it/s]

Bootstrapping recall:  25%|██▍       | 249/1000 [00:00<00:00, 1242.40it/s]

Bootstrapping recall:  37%|███▋      | 374/1000 [00:00<00:00, 1238.22it/s]

Bootstrapping recall:  50%|████▉     | 499/1000 [00:00<00:00, 1240.66it/s]

Bootstrapping recall:  62%|██████▏   | 624/1000 [00:00<00:00, 1239.40it/s]

Bootstrapping recall:  75%|███████▍  | 748/1000 [00:00<00:00, 1236.74it/s]

Bootstrapping recall:  87%|████████▋ | 873/1000 [00:00<00:00, 1239.39it/s]

Bootstrapping recall: 100%|█████████▉| 998/1000 [00:00<00:00, 1242.55it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1239.41it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 124/1000 [00:00<00:00, 1239.97it/s]

Bootstrapping f1:  25%|██▍       | 248/1000 [00:00<00:00, 1234.94it/s]

Bootstrapping f1:  37%|███▋      | 373/1000 [00:00<00:00, 1238.11it/s]

Bootstrapping f1:  50%|████▉     | 498/1000 [00:00<00:00, 1239.23it/s]

Bootstrapping f1:  62%|██████▏   | 623/1000 [00:00<00:00, 1239.25it/s]

Bootstrapping f1:  75%|███████▍  | 748/1000 [00:00<00:00, 1241.27it/s]

Bootstrapping f1:  87%|████████▋ | 873/1000 [00:00<00:00, 1237.64it/s]

Bootstrapping f1: 100%|█████████▉| 997/1000 [00:00<00:00, 1236.53it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1236.73it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▋      | 363/1000 [00:00<00:00, 3622.43it/s]

Bootstrapping accuracy:  73%|███████▎  | 726/1000 [00:00<00:00, 3615.76it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3618.99it/s]

Processing Correlation — 38 nodes, 37 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1377.41it/s]

Bootstrapping average_precision:  28%|██▊       | 277/1000 [00:00<00:00, 1384.32it/s]

Bootstrapping average_precision:  42%|████▏     | 417/1000 [00:00<00:00, 1390.45it/s]

Bootstrapping average_precision:  56%|█████▌    | 557/1000 [00:00<00:00, 1391.95it/s]

Bootstrapping average_precision:  70%|██████▉   | 698/1000 [00:00<00:00, 1396.70it/s]

Bootstrapping average_precision:  84%|████████▍ | 838/1000 [00:00<00:00, 1392.75it/s]

Bootstrapping average_precision:  98%|█████████▊| 978/1000 [00:00<00:00, 1388.02it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1388.54it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 89/1000 [00:00<00:01, 881.42it/s]

Bootstrapping roc_auc:  18%|█▊        | 178/1000 [00:00<00:00, 884.86it/s]

Bootstrapping roc_auc:  27%|██▋       | 267/1000 [00:00<00:00, 883.96it/s]

Bootstrapping roc_auc:  36%|███▌      | 356/1000 [00:00<00:00, 881.33it/s]

Bootstrapping roc_auc:  44%|████▍     | 445/1000 [00:00<00:00, 881.14it/s]

Bootstrapping roc_auc:  53%|█████▎    | 534/1000 [00:00<00:00, 884.11it/s]

Bootstrapping roc_auc:  62%|██████▏   | 623/1000 [00:00<00:00, 883.63it/s]

Bootstrapping roc_auc:  71%|███████   | 712/1000 [00:00<00:00, 884.92it/s]

Bootstrapping roc_auc:  80%|████████  | 801/1000 [00:00<00:00, 884.75it/s]

Bootstrapping roc_auc:  89%|████████▉ | 890/1000 [00:01<00:00, 884.84it/s]

Bootstrapping roc_auc:  98%|█████████▊| 979/1000 [00:01<00:00, 884.16it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 883.47it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1210.57it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1213.50it/s]

Bootstrapping precision:  37%|███▋      | 368/1000 [00:00<00:00, 1223.52it/s]

Bootstrapping precision:  49%|████▉     | 491/1000 [00:00<00:00, 1219.49it/s]

Bootstrapping precision:  61%|██████▏   | 613/1000 [00:00<00:00, 1216.82it/s]

Bootstrapping precision:  74%|███████▎  | 735/1000 [00:00<00:00, 1214.42it/s]

Bootstrapping precision:  86%|████████▌ | 857/1000 [00:00<00:00, 1215.17it/s]

Bootstrapping precision:  98%|█████████▊| 979/1000 [00:00<00:00, 1215.11it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1214.80it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1195.27it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1202.83it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1202.23it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1204.56it/s]

Bootstrapping recall:  60%|██████    | 605/1000 [00:00<00:00, 1209.26it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 1212.31it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1215.73it/s]

Bootstrapping recall:  97%|█████████▋| 973/1000 [00:00<00:00, 1218.64it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1211.64it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 123/1000 [00:00<00:00, 1221.47it/s]

Bootstrapping f1:  25%|██▍       | 246/1000 [00:00<00:00, 1218.80it/s]

Bootstrapping f1:  37%|███▋      | 368/1000 [00:00<00:00, 1216.19it/s]

Bootstrapping f1:  49%|████▉     | 490/1000 [00:00<00:00, 1217.68it/s]

Bootstrapping f1:  61%|██████▏   | 613/1000 [00:00<00:00, 1218.87it/s]

Bootstrapping f1:  74%|███████▎  | 736/1000 [00:00<00:00, 1222.34it/s]

Bootstrapping f1:  86%|████████▌ | 859/1000 [00:00<00:00, 1221.72it/s]

Bootstrapping f1:  98%|█████████▊| 982/1000 [00:00<00:00, 1222.09it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1219.73it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3566.54it/s]

Bootstrapping accuracy:  72%|███████▏  | 716/1000 [00:00<00:00, 3579.90it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3588.23it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1365.79it/s]

Bootstrapping average_precision:  28%|██▊       | 278/1000 [00:00<00:00, 1385.83it/s]

Bootstrapping average_precision:  42%|████▏     | 417/1000 [00:00<00:00, 1382.20it/s]

Bootstrapping average_precision:  56%|█████▌    | 556/1000 [00:00<00:00, 1384.96it/s]

Bootstrapping average_precision:  70%|██████▉   | 695/1000 [00:00<00:00, 1379.80it/s]

Bootstrapping average_precision:  83%|████████▎ | 833/1000 [00:00<00:00, 1378.20it/s]

Bootstrapping average_precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1378.30it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1378.16it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 872.73it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 876.09it/s]

Bootstrapping roc_auc:  26%|██▋       | 265/1000 [00:00<00:00, 878.91it/s]

Bootstrapping roc_auc:  35%|███▌      | 353/1000 [00:00<00:00, 874.16it/s]

Bootstrapping roc_auc:  44%|████▍     | 441/1000 [00:00<00:00, 870.45it/s]

Bootstrapping roc_auc:  53%|█████▎    | 529/1000 [00:00<00:00, 868.89it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 868.74it/s]

Bootstrapping roc_auc:  70%|███████   | 705/1000 [00:00<00:00, 872.47it/s]

Bootstrapping roc_auc:  79%|███████▉  | 793/1000 [00:00<00:00, 871.28it/s]

Bootstrapping roc_auc:  88%|████████▊ | 881/1000 [00:01<00:00, 872.84it/s]

Bootstrapping roc_auc:  97%|█████████▋| 969/1000 [00:01<00:00, 873.91it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 872.59it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 113/1000 [00:00<00:00, 1129.69it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1163.12it/s]

Bootstrapping precision:  35%|███▌      | 352/1000 [00:00<00:00, 1176.56it/s]

Bootstrapping precision:  47%|████▋     | 470/1000 [00:00<00:00, 1163.77it/s]

Bootstrapping precision:  59%|█████▉    | 589/1000 [00:00<00:00, 1171.90it/s]

Bootstrapping precision:  71%|███████   | 709/1000 [00:00<00:00, 1179.48it/s]

Bootstrapping precision:  83%|████████▎ | 830/1000 [00:00<00:00, 1186.68it/s]

Bootstrapping precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1191.84it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1179.67it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1207.69it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1209.61it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1209.18it/s]

Bootstrapping recall:  49%|████▊     | 487/1000 [00:00<00:00, 1210.31it/s]

Bootstrapping recall:  61%|██████    | 609/1000 [00:00<00:00, 1206.27it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1211.88it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1210.91it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1216.08it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1211.60it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 123/1000 [00:00<00:00, 1223.64it/s]

Bootstrapping f1:  25%|██▍       | 247/1000 [00:00<00:00, 1229.91it/s]

Bootstrapping f1:  37%|███▋      | 370/1000 [00:00<00:00, 1229.54it/s]

Bootstrapping f1:  50%|████▉     | 495/1000 [00:00<00:00, 1234.49it/s]

Bootstrapping f1:  62%|██████▏   | 619/1000 [00:00<00:00, 1235.42it/s]

Bootstrapping f1:  74%|███████▍  | 743/1000 [00:00<00:00, 1229.97it/s]

Bootstrapping f1:  87%|████████▋ | 867/1000 [00:00<00:00, 1221.88it/s]

Bootstrapping f1:  99%|█████████▉| 990/1000 [00:00<00:00, 1224.42it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1226.71it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 359/1000 [00:00<00:00, 3580.48it/s]

Bootstrapping accuracy:  72%|███████▏  | 722/1000 [00:00<00:00, 3603.83it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3592.40it/s]

Processing Clinician Consensus $\cup$ Golem — 213 nodes, 387 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 140/1000 [00:00<00:00, 1392.55it/s]

Bootstrapping average_precision:  28%|██▊       | 282/1000 [00:00<00:00, 1403.02it/s]

Bootstrapping average_precision:  42%|████▏     | 423/1000 [00:00<00:00, 1393.23it/s]

Bootstrapping average_precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1378.26it/s]

Bootstrapping average_precision:  70%|███████   | 701/1000 [00:00<00:00, 1360.28it/s]

Bootstrapping average_precision:  84%|████████▍ | 838/1000 [00:00<00:00, 1359.35it/s]

Bootstrapping average_precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1367.69it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1372.29it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 871.46it/s]

Bootstrapping roc_auc:  18%|█▊        | 177/1000 [00:00<00:00, 880.51it/s]

Bootstrapping roc_auc:  27%|██▋       | 266/1000 [00:00<00:00, 870.91it/s]

Bootstrapping roc_auc:  36%|███▌      | 355/1000 [00:00<00:00, 876.44it/s]

Bootstrapping roc_auc:  44%|████▍     | 444/1000 [00:00<00:00, 880.59it/s]

Bootstrapping roc_auc:  53%|█████▎    | 533/1000 [00:00<00:00, 882.47it/s]

Bootstrapping roc_auc:  62%|██████▏   | 622/1000 [00:00<00:00, 882.65it/s]

Bootstrapping roc_auc:  71%|███████   | 711/1000 [00:00<00:00, 878.04it/s]

Bootstrapping roc_auc:  80%|███████▉  | 799/1000 [00:00<00:00, 871.96it/s]

Bootstrapping roc_auc:  89%|████████▊ | 887/1000 [00:01<00:00, 870.70it/s]

Bootstrapping roc_auc:  98%|█████████▊| 976/1000 [00:01<00:00, 874.79it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 875.67it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1200.86it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1203.79it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1203.64it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1206.84it/s]

Bootstrapping precision:  61%|██████    | 606/1000 [00:00<00:00, 1195.93it/s]

Bootstrapping precision:  73%|███████▎  | 726/1000 [00:00<00:00, 1175.27it/s]

Bootstrapping precision:  84%|████████▍ | 845/1000 [00:00<00:00, 1179.80it/s]

Bootstrapping precision:  96%|█████████▋| 965/1000 [00:00<00:00, 1184.22it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1189.12it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1194.75it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1200.79it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1196.12it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1200.92it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1202.52it/s]

Bootstrapping recall:  72%|███████▎  | 725/1000 [00:00<00:00, 1203.55it/s]

Bootstrapping recall:  85%|████████▍ | 846/1000 [00:00<00:00, 1204.50it/s]

Bootstrapping recall:  97%|█████████▋| 967/1000 [00:00<00:00, 1205.17it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1202.24it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1215.11it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1214.95it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1210.40it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1212.87it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1213.31it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1215.20it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1209.91it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1210.18it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1210.76it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3554.21it/s]

Bootstrapping accuracy:  72%|███████▏  | 716/1000 [00:00<00:00, 3578.37it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3589.46it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1361.48it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1334.93it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1347.10it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1350.43it/s]

Bootstrapping average_precision:  68%|██████▊   | 684/1000 [00:00<00:00, 1352.64it/s]

Bootstrapping average_precision:  82%|████████▏ | 821/1000 [00:00<00:00, 1355.85it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1354.69it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1352.35it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 869.45it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 876.45it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 875.20it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 873.40it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 872.51it/s]

Bootstrapping roc_auc:  53%|█████▎    | 529/1000 [00:00<00:00, 875.16it/s]

Bootstrapping roc_auc:  62%|██████▏   | 617/1000 [00:00<00:00, 873.37it/s]

Bootstrapping roc_auc:  70%|███████   | 705/1000 [00:00<00:00, 875.22it/s]

Bootstrapping roc_auc:  79%|███████▉  | 793/1000 [00:00<00:00, 875.20it/s]

Bootstrapping roc_auc:  88%|████████▊ | 881/1000 [00:01<00:00, 875.41it/s]

Bootstrapping roc_auc:  97%|█████████▋| 969/1000 [00:01<00:00, 873.15it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 873.73it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 123/1000 [00:00<00:00, 1223.17it/s]

Bootstrapping precision:  25%|██▍       | 246/1000 [00:00<00:00, 1221.10it/s]

Bootstrapping precision:  37%|███▋      | 369/1000 [00:00<00:00, 1217.06it/s]

Bootstrapping precision:  49%|████▉     | 491/1000 [00:00<00:00, 1211.91it/s]

Bootstrapping precision:  61%|██████▏   | 613/1000 [00:00<00:00, 1211.49it/s]

Bootstrapping precision:  74%|███████▎  | 735/1000 [00:00<00:00, 1207.30it/s]

Bootstrapping precision:  86%|████████▌ | 857/1000 [00:00<00:00, 1208.89it/s]

Bootstrapping precision:  98%|█████████▊| 979/1000 [00:00<00:00, 1210.63it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1209.63it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1200.63it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1210.10it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1218.01it/s]

Bootstrapping recall:  49%|████▉     | 490/1000 [00:00<00:00, 1223.31it/s]

Bootstrapping recall:  61%|██████▏   | 613/1000 [00:00<00:00, 1224.37it/s]

Bootstrapping recall:  74%|███████▎  | 736/1000 [00:00<00:00, 1223.28it/s]

Bootstrapping recall:  86%|████████▌ | 859/1000 [00:00<00:00, 1217.12it/s]

Bootstrapping recall:  98%|█████████▊| 981/1000 [00:00<00:00, 1216.76it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1216.97it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1208.42it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1220.19it/s]

Bootstrapping f1:  37%|███▋      | 368/1000 [00:00<00:00, 1226.65it/s]

Bootstrapping f1:  49%|████▉     | 491/1000 [00:00<00:00, 1221.70it/s]

Bootstrapping f1:  62%|██████▏   | 615/1000 [00:00<00:00, 1224.59it/s]

Bootstrapping f1:  74%|███████▍  | 738/1000 [00:00<00:00, 1221.64it/s]

Bootstrapping f1:  86%|████████▌ | 861/1000 [00:00<00:00, 1219.96it/s]

Bootstrapping f1:  98%|█████████▊| 984/1000 [00:00<00:00, 1220.59it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1220.08it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▋      | 364/1000 [00:00<00:00, 3634.65it/s]

Bootstrapping accuracy:  73%|███████▎  | 728/1000 [00:00<00:00, 3566.08it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3568.25it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB — 19 nodes, 52 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 140/1000 [00:00<00:00, 1392.84it/s]

Bootstrapping average_precision:  28%|██▊       | 280/1000 [00:00<00:00, 1393.04it/s]

Bootstrapping average_precision:  42%|████▏     | 420/1000 [00:00<00:00, 1395.79it/s]

Bootstrapping average_precision:  56%|█████▌    | 561/1000 [00:00<00:00, 1400.31it/s]

Bootstrapping average_precision:  70%|███████   | 702/1000 [00:00<00:00, 1399.52it/s]

Bootstrapping average_precision:  84%|████████▍ | 843/1000 [00:00<00:00, 1400.34it/s]

Bootstrapping average_precision:  98%|█████████▊| 984/1000 [00:00<00:00, 1400.07it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1397.80it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 877.31it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 869.61it/s]

Bootstrapping roc_auc:  26%|██▋       | 265/1000 [00:00<00:00, 877.81it/s]

Bootstrapping roc_auc:  35%|███▌      | 354/1000 [00:00<00:00, 881.92it/s]

Bootstrapping roc_auc:  44%|████▍     | 443/1000 [00:00<00:00, 882.43it/s]

Bootstrapping roc_auc:  53%|█████▎    | 532/1000 [00:00<00:00, 883.56it/s]

Bootstrapping roc_auc:  62%|██████▏   | 621/1000 [00:00<00:00, 883.48it/s]

Bootstrapping roc_auc:  71%|███████   | 710/1000 [00:00<00:00, 883.18it/s]

Bootstrapping roc_auc:  80%|███████▉  | 799/1000 [00:00<00:00, 884.51it/s]

Bootstrapping roc_auc:  89%|████████▉ | 888/1000 [00:01<00:00, 885.76it/s]

Bootstrapping roc_auc:  98%|█████████▊| 978/1000 [00:01<00:00, 887.07it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 883.40it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1191.22it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1192.50it/s]

Bootstrapping precision:  36%|███▌      | 360/1000 [00:00<00:00, 1194.92it/s]

Bootstrapping precision:  48%|████▊     | 480/1000 [00:00<00:00, 1192.71it/s]

Bootstrapping precision:  60%|██████    | 601/1000 [00:00<00:00, 1197.40it/s]

Bootstrapping precision:  72%|███████▏  | 721/1000 [00:00<00:00, 1193.04it/s]

Bootstrapping precision:  84%|████████▍ | 841/1000 [00:00<00:00, 1191.93it/s]

Bootstrapping precision:  96%|█████████▋| 963/1000 [00:00<00:00, 1198.18it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1195.09it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1213.19it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1210.07it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1210.58it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1211.92it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1209.99it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1197.54it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1204.93it/s]

Bootstrapping recall:  98%|█████████▊| 976/1000 [00:00<00:00, 1206.03it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1206.50it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1208.13it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1208.79it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1209.09it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1210.00it/s]

Bootstrapping f1:  61%|██████    | 608/1000 [00:00<00:00, 1211.89it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1213.87it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1212.44it/s]

Bootstrapping f1:  97%|█████████▋| 974/1000 [00:00<00:00, 1212.35it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1210.79it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3542.77it/s]

Bootstrapping accuracy:  71%|███████   | 710/1000 [00:00<00:00, 3543.36it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3553.45it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1350.91it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1365.63it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1365.97it/s]

Bootstrapping average_precision:  55%|█████▍    | 549/1000 [00:00<00:00, 1370.87it/s]

Bootstrapping average_precision:  69%|██████▊   | 687/1000 [00:00<00:00, 1367.11it/s]

Bootstrapping average_precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1365.69it/s]

Bootstrapping average_precision:  96%|█████████▌| 961/1000 [00:00<00:00, 1360.75it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1361.50it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 855.63it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 864.62it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 869.93it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 873.06it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 873.25it/s]

Bootstrapping roc_auc:  53%|█████▎    | 526/1000 [00:00<00:00, 873.76it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 876.21it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 870.04it/s]

Bootstrapping roc_auc:  79%|███████▉  | 791/1000 [00:00<00:00, 868.17it/s]

Bootstrapping roc_auc:  88%|████████▊ | 878/1000 [00:01<00:00, 866.59it/s]

Bootstrapping roc_auc:  96%|█████████▋| 965/1000 [00:01<00:00, 861.12it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.60it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1198.45it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1211.05it/s]

Bootstrapping precision:  37%|███▋      | 367/1000 [00:00<00:00, 1220.08it/s]

Bootstrapping precision:  49%|████▉     | 491/1000 [00:00<00:00, 1223.64it/s]

Bootstrapping precision:  61%|██████▏   | 614/1000 [00:00<00:00, 1223.09it/s]

Bootstrapping precision:  74%|███████▎  | 737/1000 [00:00<00:00, 1222.35it/s]

Bootstrapping precision:  86%|████████▌ | 860/1000 [00:00<00:00, 1221.05it/s]

Bootstrapping precision:  98%|█████████▊| 983/1000 [00:00<00:00, 1223.82it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1220.58it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1219.36it/s]

Bootstrapping recall:  24%|██▍       | 245/1000 [00:00<00:00, 1216.67it/s]

Bootstrapping recall:  37%|███▋      | 368/1000 [00:00<00:00, 1221.85it/s]

Bootstrapping recall:  49%|████▉     | 491/1000 [00:00<00:00, 1213.85it/s]

Bootstrapping recall:  61%|██████▏   | 613/1000 [00:00<00:00, 1214.87it/s]

Bootstrapping recall:  74%|███████▎  | 736/1000 [00:00<00:00, 1219.14it/s]

Bootstrapping recall:  86%|████████▌ | 860/1000 [00:00<00:00, 1224.29it/s]

Bootstrapping recall:  98%|█████████▊| 983/1000 [00:00<00:00, 1219.45it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1218.01it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 123/1000 [00:00<00:00, 1226.58it/s]

Bootstrapping f1:  25%|██▍       | 246/1000 [00:00<00:00, 1171.91it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1162.63it/s]

Bootstrapping f1:  48%|████▊     | 481/1000 [00:00<00:00, 1141.33it/s]

Bootstrapping f1:  60%|█████▉    | 596/1000 [00:00<00:00, 1143.27it/s]

Bootstrapping f1:  71%|███████   | 712/1000 [00:00<00:00, 1148.45it/s]

Bootstrapping f1:  83%|████████▎ | 827/1000 [00:00<00:00, 1143.47it/s]

Bootstrapping f1:  94%|█████████▍| 942/1000 [00:00<00:00, 1136.80it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1147.30it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 334/1000 [00:00<00:00, 3336.37it/s]

Bootstrapping accuracy:  67%|██████▋   | 672/1000 [00:00<00:00, 3355.73it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3375.86it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem — 23 nodes, 34 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1314.21it/s]

Bootstrapping average_precision:  26%|██▋       | 264/1000 [00:00<00:00, 1310.54it/s]

Bootstrapping average_precision:  40%|███▉      | 396/1000 [00:00<00:00, 1292.54it/s]

Bootstrapping average_precision:  53%|█████▎    | 526/1000 [00:00<00:00, 1290.68it/s]

Bootstrapping average_precision:  66%|██████▋   | 664/1000 [00:00<00:00, 1321.82it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1339.21it/s]

Bootstrapping average_precision:  94%|█████████▍| 939/1000 [00:00<00:00, 1346.20it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1329.28it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 845.74it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 842.98it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 848.66it/s]

Bootstrapping roc_auc:  34%|███▍      | 341/1000 [00:00<00:00, 846.59it/s]

Bootstrapping roc_auc:  43%|████▎     | 427/1000 [00:00<00:00, 849.02it/s]

Bootstrapping roc_auc:  51%|█████     | 512/1000 [00:00<00:00, 841.99it/s]

Bootstrapping roc_auc:  60%|█████▉    | 598/1000 [00:00<00:00, 844.55it/s]

Bootstrapping roc_auc:  68%|██████▊   | 683/1000 [00:00<00:00, 845.59it/s]

Bootstrapping roc_auc:  77%|███████▋  | 768/1000 [00:00<00:00, 844.53it/s]

Bootstrapping roc_auc:  85%|████████▌ | 853/1000 [00:01<00:00, 836.20it/s]

Bootstrapping roc_auc:  94%|█████████▍| 940/1000 [00:01<00:00, 843.93it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 845.06it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1173.63it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1176.12it/s]

Bootstrapping precision:  36%|███▌      | 357/1000 [00:00<00:00, 1187.43it/s]

Bootstrapping precision:  48%|████▊     | 477/1000 [00:00<00:00, 1190.12it/s]

Bootstrapping precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1181.10it/s]

Bootstrapping precision:  72%|███████▏  | 716/1000 [00:00<00:00, 1174.30it/s]

Bootstrapping precision:  83%|████████▎ | 834/1000 [00:00<00:00, 1152.75it/s]

Bootstrapping precision:  95%|█████████▌| 950/1000 [00:00<00:00, 1146.77it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1165.50it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1192.58it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1189.01it/s]

Bootstrapping recall:  36%|███▌      | 359/1000 [00:00<00:00, 1181.03it/s]

Bootstrapping recall:  48%|████▊     | 478/1000 [00:00<00:00, 1155.67it/s]

Bootstrapping recall:  59%|█████▉    | 594/1000 [00:00<00:00, 1151.56it/s]

Bootstrapping recall:  71%|███████   | 710/1000 [00:00<00:00, 1147.13it/s]

Bootstrapping recall:  82%|████████▎ | 825/1000 [00:00<00:00, 1139.98it/s]

Bootstrapping recall:  94%|█████████▍| 940/1000 [00:00<00:00, 1135.71it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1150.59it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1119.21it/s]

Bootstrapping f1:  23%|██▎       | 227/1000 [00:00<00:00, 1128.09it/s]

Bootstrapping f1:  34%|███▍      | 344/1000 [00:00<00:00, 1147.08it/s]

Bootstrapping f1:  46%|████▌     | 460/1000 [00:00<00:00, 1150.00it/s]

Bootstrapping f1:  58%|█████▊    | 576/1000 [00:00<00:00, 1099.25it/s]

Bootstrapping f1:  69%|██████▉   | 689/1000 [00:00<00:00, 1108.96it/s]

Bootstrapping f1:  80%|████████  | 802/1000 [00:00<00:00, 1114.41it/s]

Bootstrapping f1:  91%|█████████▏| 914/1000 [00:00<00:00, 1113.93it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1117.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 335/1000 [00:00<00:00, 3347.45it/s]

Bootstrapping accuracy:  67%|██████▋   | 670/1000 [00:00<00:00, 3328.14it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3364.52it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 131/1000 [00:00<00:00, 1307.96it/s]

Bootstrapping average_precision:  26%|██▋       | 265/1000 [00:00<00:00, 1323.12it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1332.22it/s]

Bootstrapping average_precision:  53%|█████▎    | 534/1000 [00:00<00:00, 1329.33it/s]

Bootstrapping average_precision:  67%|██████▋   | 668/1000 [00:00<00:00, 1329.65it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 1336.18it/s]

Bootstrapping average_precision:  94%|█████████▍| 940/1000 [00:00<00:00, 1344.62it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1336.55it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 824.31it/s]

Bootstrapping roc_auc:  17%|█▋        | 167/1000 [00:00<00:01, 828.96it/s]

Bootstrapping roc_auc:  25%|██▌       | 250/1000 [00:00<00:00, 827.80it/s]

Bootstrapping roc_auc:  33%|███▎      | 333/1000 [00:00<00:00, 828.61it/s]

Bootstrapping roc_auc:  42%|████▏     | 418/1000 [00:00<00:00, 833.68it/s]

Bootstrapping roc_auc:  50%|█████     | 505/1000 [00:00<00:00, 842.53it/s]

Bootstrapping roc_auc:  59%|█████▉    | 591/1000 [00:00<00:00, 846.30it/s]

Bootstrapping roc_auc:  68%|██████▊   | 677/1000 [00:00<00:00, 849.33it/s]

Bootstrapping roc_auc:  76%|███████▋  | 764/1000 [00:00<00:00, 852.63it/s]

Bootstrapping roc_auc:  85%|████████▌ | 850/1000 [00:01<00:00, 854.82it/s]

Bootstrapping roc_auc:  94%|█████████▎| 936/1000 [00:01<00:00, 853.89it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 845.68it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1204.95it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1207.30it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1179.78it/s]

Bootstrapping precision:  48%|████▊     | 483/1000 [00:00<00:00, 1184.69it/s]

Bootstrapping precision:  60%|██████    | 604/1000 [00:00<00:00, 1190.71it/s]

Bootstrapping precision:  72%|███████▏  | 724/1000 [00:00<00:00, 1193.12it/s]

Bootstrapping precision:  85%|████████▍ | 847/1000 [00:00<00:00, 1202.61it/s]

Bootstrapping precision:  97%|█████████▋| 968/1000 [00:00<00:00, 1182.22it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1188.07it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1158.09it/s]

Bootstrapping recall:  23%|██▎       | 232/1000 [00:00<00:00, 1135.24it/s]

Bootstrapping recall:  35%|███▍      | 346/1000 [00:00<00:00, 1131.91it/s]

Bootstrapping recall:  46%|████▋     | 463/1000 [00:00<00:00, 1145.21it/s]

Bootstrapping recall:  58%|█████▊    | 579/1000 [00:00<00:00, 1148.15it/s]

Bootstrapping recall:  70%|██████▉   | 695/1000 [00:00<00:00, 1149.77it/s]

Bootstrapping recall:  81%|████████▏ | 813/1000 [00:00<00:00, 1156.88it/s]

Bootstrapping recall:  93%|█████████▎| 931/1000 [00:00<00:00, 1161.87it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1150.89it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1179.55it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1162.63it/s]

Bootstrapping f1:  35%|███▌      | 354/1000 [00:00<00:00, 1168.01it/s]

Bootstrapping f1:  47%|████▋     | 473/1000 [00:00<00:00, 1175.73it/s]

Bootstrapping f1:  59%|█████▉    | 591/1000 [00:00<00:00, 1172.55it/s]

Bootstrapping f1:  71%|███████   | 709/1000 [00:00<00:00, 1172.40it/s]

Bootstrapping f1:  83%|████████▎ | 827/1000 [00:00<00:00, 1158.15it/s]

Bootstrapping f1:  94%|█████████▍| 943/1000 [00:00<00:00, 1147.07it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1159.63it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3525.69it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3503.38it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3480.76it/s]

Processing Clinician Consensus $\cup$ PCMB — 215 nodes, 430 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1326.80it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1349.37it/s]

Bootstrapping average_precision:  41%|████      | 409/1000 [00:00<00:00, 1366.90it/s]

Bootstrapping average_precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1371.63it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1373.01it/s]

Bootstrapping average_precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1377.86it/s]

Bootstrapping average_precision:  96%|█████████▌| 962/1000 [00:00<00:00, 1377.16it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1370.65it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 867.19it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 873.65it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 846.95it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 837.34it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 843.93it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 829.48it/s]

Bootstrapping roc_auc:  60%|██████    | 603/1000 [00:00<00:00, 818.53it/s]

Bootstrapping roc_auc:  68%|██████▊   | 685/1000 [00:00<00:00, 816.05it/s]

Bootstrapping roc_auc:  77%|███████▋  | 767/1000 [00:00<00:00, 801.76it/s]

Bootstrapping roc_auc:  85%|████████▍ | 848/1000 [00:01<00:00, 799.97it/s]

Bootstrapping roc_auc:  93%|█████████▎| 930/1000 [00:01<00:00, 804.34it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 819.69it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 113/1000 [00:00<00:00, 1129.65it/s]

Bootstrapping precision:  23%|██▎       | 228/1000 [00:00<00:00, 1136.50it/s]

Bootstrapping precision:  35%|███▍      | 346/1000 [00:00<00:00, 1151.76it/s]

Bootstrapping precision:  46%|████▋     | 465/1000 [00:00<00:00, 1162.57it/s]

Bootstrapping precision:  58%|█████▊    | 582/1000 [00:00<00:00, 1149.26it/s]

Bootstrapping precision:  70%|██████▉   | 699/1000 [00:00<00:00, 1154.44it/s]

Bootstrapping precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1160.53it/s]

Bootstrapping precision:  93%|█████████▎| 934/1000 [00:00<00:00, 1150.32it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1148.97it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 112/1000 [00:00<00:00, 1118.28it/s]

Bootstrapping recall:  23%|██▎       | 229/1000 [00:00<00:00, 1146.81it/s]

Bootstrapping recall:  34%|███▍      | 344/1000 [00:00<00:00, 1143.66it/s]

Bootstrapping recall:  46%|████▌     | 459/1000 [00:00<00:00, 1139.60it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1143.36it/s]

Bootstrapping recall:  69%|██████▉   | 691/1000 [00:00<00:00, 1148.13it/s]

Bootstrapping recall:  81%|████████  | 808/1000 [00:00<00:00, 1155.03it/s]

Bootstrapping recall:  92%|█████████▏| 924/1000 [00:00<00:00, 1156.34it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1151.11it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1159.19it/s]

Bootstrapping f1:  23%|██▎       | 233/1000 [00:00<00:00, 1131.52it/s]

Bootstrapping f1:  35%|███▍      | 348/1000 [00:00<00:00, 1136.30it/s]

Bootstrapping f1:  46%|████▌     | 462/1000 [00:00<00:00, 1129.80it/s]

Bootstrapping f1:  57%|█████▊    | 575/1000 [00:00<00:00, 1127.77it/s]

Bootstrapping f1:  69%|██████▉   | 688/1000 [00:00<00:00, 1127.10it/s]

Bootstrapping f1:  80%|████████  | 801/1000 [00:00<00:00, 1061.92it/s]

Bootstrapping f1:  91%|█████████▏| 913/1000 [00:00<00:00, 1077.86it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1104.76it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 342/1000 [00:00<00:00, 3415.22it/s]

Bootstrapping accuracy:  68%|██████▊   | 684/1000 [00:00<00:00, 3368.58it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3390.44it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  11%|█         | 109/1000 [00:00<00:00, 1089.37it/s]

Bootstrapping average_precision:  24%|██▍       | 239/1000 [00:00<00:00, 1211.21it/s]

Bootstrapping average_precision:  36%|███▌      | 362/1000 [00:00<00:00, 1217.80it/s]

Bootstrapping average_precision:  48%|████▊     | 484/1000 [00:00<00:00, 1128.80it/s]

Bootstrapping average_precision:  61%|██████    | 607/1000 [00:00<00:00, 1161.15it/s]

Bootstrapping average_precision:  73%|███████▎  | 727/1000 [00:00<00:00, 1173.50it/s]

Bootstrapping average_precision:  85%|████████▌ | 852/1000 [00:00<00:00, 1196.37it/s]

Bootstrapping average_precision:  98%|█████████▊| 975/1000 [00:00<00:00, 1205.51it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1186.19it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   7%|▋         | 73/1000 [00:00<00:01, 710.36it/s]

Bootstrapping roc_auc:  15%|█▍        | 147/1000 [00:00<00:01, 724.24it/s]

Bootstrapping roc_auc:  23%|██▎       | 226/1000 [00:00<00:01, 753.82it/s]

Bootstrapping roc_auc:  30%|███       | 304/1000 [00:00<00:00, 763.73it/s]

Bootstrapping roc_auc:  38%|███▊      | 381/1000 [00:00<00:00, 764.24it/s]

Bootstrapping roc_auc:  46%|████▌     | 458/1000 [00:00<00:00, 765.73it/s]

Bootstrapping roc_auc:  54%|█████▎    | 536/1000 [00:00<00:00, 769.48it/s]

Bootstrapping roc_auc:  62%|██████▏   | 617/1000 [00:00<00:00, 779.50it/s]

Bootstrapping roc_auc:  70%|██████▉   | 699/1000 [00:00<00:00, 791.40it/s]

Bootstrapping roc_auc:  78%|███████▊  | 783/1000 [00:01<00:00, 804.27it/s]

Bootstrapping roc_auc:  86%|████████▋ | 865/1000 [00:01<00:00, 807.24it/s]

Bootstrapping roc_auc:  95%|█████████▍| 946/1000 [00:01<00:00, 805.63it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 782.22it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1140.85it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1113.99it/s]

Bootstrapping precision:  35%|███▍      | 346/1000 [00:00<00:00, 1130.86it/s]

Bootstrapping precision:  46%|████▋     | 464/1000 [00:00<00:00, 1148.32it/s]

Bootstrapping precision:  58%|█████▊    | 579/1000 [00:00<00:00, 1139.46it/s]

Bootstrapping precision:  69%|██████▉   | 693/1000 [00:00<00:00, 1075.37it/s]

Bootstrapping precision:  80%|████████  | 802/1000 [00:00<00:00, 1059.48it/s]

Bootstrapping precision:  91%|█████████ | 912/1000 [00:00<00:00, 1069.07it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1093.22it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1143.79it/s]

Bootstrapping recall:  23%|██▎       | 234/1000 [00:00<00:00, 1166.70it/s]

Bootstrapping recall:  35%|███▌      | 351/1000 [00:00<00:00, 1162.73it/s]

Bootstrapping recall:  47%|████▋     | 468/1000 [00:00<00:00, 1153.76it/s]

Bootstrapping recall:  58%|█████▊    | 584/1000 [00:00<00:00, 1146.93it/s]

Bootstrapping recall:  70%|███████   | 702/1000 [00:00<00:00, 1157.93it/s]

Bootstrapping recall:  82%|████████▏ | 821/1000 [00:00<00:00, 1165.95it/s]

Bootstrapping recall:  94%|█████████▍| 941/1000 [00:00<00:00, 1174.89it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1159.77it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1175.51it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1187.70it/s]

Bootstrapping f1:  36%|███▌      | 358/1000 [00:00<00:00, 1191.59it/s]

Bootstrapping f1:  48%|████▊     | 478/1000 [00:00<00:00, 1190.84it/s]

Bootstrapping f1:  60%|█████▉    | 598/1000 [00:00<00:00, 1188.91it/s]

Bootstrapping f1:  72%|███████▏  | 717/1000 [00:00<00:00, 1186.37it/s]

Bootstrapping f1:  84%|████████▎ | 836/1000 [00:00<00:00, 1186.16it/s]

Bootstrapping f1:  96%|█████████▌| 957/1000 [00:00<00:00, 1190.30it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1188.12it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 352/1000 [00:00<00:00, 3510.70it/s]

Bootstrapping accuracy:  70%|███████   | 704/1000 [00:00<00:00, 3455.06it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3460.16it/s]

Processing Simplified Golem $\cup$ Simplified PCMB — 24 nodes, 64 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1323.57it/s]

Bootstrapping average_precision:  27%|██▋       | 267/1000 [00:00<00:00, 1331.25it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 1334.58it/s]

Bootstrapping average_precision:  54%|█████▎    | 537/1000 [00:00<00:00, 1344.26it/s]

Bootstrapping average_precision:  67%|██████▋   | 672/1000 [00:00<00:00, 1330.14it/s]

Bootstrapping average_precision:  81%|████████  | 808/1000 [00:00<00:00, 1337.02it/s]

Bootstrapping average_precision:  94%|█████████▍| 942/1000 [00:00<00:00, 1327.46it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1330.39it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 82/1000 [00:00<00:01, 814.05it/s]

Bootstrapping roc_auc:  16%|█▋        | 165/1000 [00:00<00:01, 819.44it/s]

Bootstrapping roc_auc:  25%|██▍       | 247/1000 [00:00<00:00, 813.11it/s]

Bootstrapping roc_auc:  33%|███▎      | 330/1000 [00:00<00:00, 817.90it/s]

Bootstrapping roc_auc:  41%|████▏     | 414/1000 [00:00<00:00, 822.17it/s]

Bootstrapping roc_auc:  50%|████▉     | 497/1000 [00:00<00:00, 820.78it/s]

Bootstrapping roc_auc:  58%|█████▊    | 580/1000 [00:00<00:00, 820.99it/s]

Bootstrapping roc_auc:  66%|██████▋   | 663/1000 [00:00<00:00, 816.33it/s]

Bootstrapping roc_auc:  74%|███████▍  | 745/1000 [00:00<00:00, 812.93it/s]

Bootstrapping roc_auc:  83%|████████▎ | 827/1000 [00:01<00:00, 810.25it/s]

Bootstrapping roc_auc:  91%|█████████ | 909/1000 [00:01<00:00, 803.72it/s]

Bootstrapping roc_auc:  99%|█████████▉| 993/1000 [00:01<00:00, 812.13it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 814.22it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 112/1000 [00:00<00:00, 1111.26it/s]

Bootstrapping precision:  22%|██▏       | 224/1000 [00:00<00:00, 1071.82it/s]

Bootstrapping precision:  34%|███▎      | 337/1000 [00:00<00:00, 1096.98it/s]

Bootstrapping precision:  45%|████▍     | 449/1000 [00:00<00:00, 1102.98it/s]

Bootstrapping precision:  56%|█████▌    | 561/1000 [00:00<00:00, 1107.74it/s]

Bootstrapping precision:  67%|██████▋   | 672/1000 [00:00<00:00, 1105.60it/s]

Bootstrapping precision:  78%|███████▊  | 784/1000 [00:00<00:00, 1109.06it/s]

Bootstrapping precision:  90%|████████▉ | 897/1000 [00:00<00:00, 1114.53it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1108.90it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 112/1000 [00:00<00:00, 1117.70it/s]

Bootstrapping recall:  22%|██▏       | 224/1000 [00:00<00:00, 1118.02it/s]

Bootstrapping recall:  34%|███▎      | 336/1000 [00:00<00:00, 1116.11it/s]

Bootstrapping recall:  45%|████▍     | 448/1000 [00:00<00:00, 1090.01it/s]

Bootstrapping recall:  56%|█████▌    | 558/1000 [00:00<00:00, 1079.10it/s]

Bootstrapping recall:  67%|██████▋   | 666/1000 [00:00<00:00, 1072.47it/s]

Bootstrapping recall:  78%|███████▊  | 777/1000 [00:00<00:00, 1081.80it/s]

Bootstrapping recall:  89%|████████▉ | 891/1000 [00:00<00:00, 1097.22it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1093.50it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 108/1000 [00:00<00:00, 1070.60it/s]

Bootstrapping f1:  22%|██▏       | 217/1000 [00:00<00:00, 1080.10it/s]

Bootstrapping f1:  33%|███▎      | 330/1000 [00:00<00:00, 1100.71it/s]

Bootstrapping f1:  44%|████▍     | 441/1000 [00:00<00:00, 1089.56it/s]

Bootstrapping f1:  55%|█████▌    | 550/1000 [00:00<00:00, 1084.54it/s]

Bootstrapping f1:  66%|██████▋   | 664/1000 [00:00<00:00, 1103.11it/s]

Bootstrapping f1:  78%|███████▊  | 775/1000 [00:00<00:00, 1078.87it/s]

Bootstrapping f1:  88%|████████▊ | 884/1000 [00:00<00:00, 1067.90it/s]

Bootstrapping f1: 100%|█████████▉| 998/1000 [00:00<00:00, 1088.24it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1084.66it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 340/1000 [00:00<00:00, 3396.30it/s]

Bootstrapping accuracy:  69%|██████▊   | 687/1000 [00:00<00:00, 3435.11it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3456.60it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1282.99it/s]

Bootstrapping average_precision:  26%|██▌       | 258/1000 [00:00<00:00, 1285.77it/s]

Bootstrapping average_precision:  39%|███▊      | 387/1000 [00:00<00:00, 1285.58it/s]

Bootstrapping average_precision:  52%|█████▏    | 518/1000 [00:00<00:00, 1292.65it/s]

Bootstrapping average_precision:  65%|██████▍   | 648/1000 [00:00<00:00, 1292.28it/s]

Bootstrapping average_precision:  78%|███████▊  | 781/1000 [00:00<00:00, 1302.91it/s]

Bootstrapping average_precision:  91%|█████████▏| 914/1000 [00:00<00:00, 1309.64it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1301.42it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 830.45it/s]

Bootstrapping roc_auc:  17%|█▋        | 169/1000 [00:00<00:00, 837.47it/s]

Bootstrapping roc_auc:  25%|██▌       | 253/1000 [00:00<00:00, 837.42it/s]

Bootstrapping roc_auc:  34%|███▍      | 338/1000 [00:00<00:00, 841.49it/s]

Bootstrapping roc_auc:  42%|████▏     | 424/1000 [00:00<00:00, 845.64it/s]

Bootstrapping roc_auc:  51%|█████     | 511/1000 [00:00<00:00, 850.64it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 850.81it/s]

Bootstrapping roc_auc:  68%|██████▊   | 683/1000 [00:00<00:00, 848.41it/s]

Bootstrapping roc_auc:  77%|███████▋  | 770/1000 [00:00<00:00, 852.41it/s]

Bootstrapping roc_auc:  86%|████████▌ | 856/1000 [00:01<00:00, 846.31it/s]

Bootstrapping roc_auc:  94%|█████████▍| 941/1000 [00:01<00:00, 841.90it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 845.55it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1184.66it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1184.35it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1194.04it/s]

Bootstrapping precision:  48%|████▊     | 479/1000 [00:00<00:00, 1172.25it/s]

Bootstrapping precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1169.05it/s]

Bootstrapping precision:  72%|███████▏  | 716/1000 [00:00<00:00, 1172.95it/s]

Bootstrapping precision:  83%|████████▎ | 834/1000 [00:00<00:00, 1171.55it/s]

Bootstrapping precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1160.72it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1168.90it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1199.04it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1200.99it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1202.20it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1205.64it/s]

Bootstrapping recall:  60%|██████    | 605/1000 [00:00<00:00, 1204.74it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1205.08it/s]

Bootstrapping recall:  85%|████████▍ | 847/1000 [00:00<00:00, 1203.42it/s]

Bootstrapping recall:  97%|█████████▋| 968/1000 [00:00<00:00, 1196.51it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1200.13it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1204.62it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1197.66it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1204.35it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1209.10it/s]

Bootstrapping f1:  61%|██████    | 607/1000 [00:00<00:00, 1208.20it/s]

Bootstrapping f1:  73%|███████▎  | 728/1000 [00:00<00:00, 1206.35it/s]

Bootstrapping f1:  85%|████████▍ | 849/1000 [00:00<00:00, 1204.84it/s]

Bootstrapping f1:  97%|█████████▋| 971/1000 [00:00<00:00, 1208.23it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1206.02it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3564.40it/s]

Bootstrapping accuracy:  72%|███████▏  | 715/1000 [00:00<00:00, 3567.29it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3553.67it/s]

Processing Clinician Consensus — 204 nodes, 372 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1339.61it/s]

Bootstrapping average_precision:  27%|██▋       | 269/1000 [00:00<00:00, 1342.61it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1349.65it/s]

Bootstrapping average_precision:  54%|█████▍    | 542/1000 [00:00<00:00, 1355.21it/s]

Bootstrapping average_precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1364.58it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1371.16it/s]

Bootstrapping average_precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1376.42it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1365.50it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 851.38it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 860.51it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 863.15it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 845.26it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 838.84it/s]

Bootstrapping roc_auc:  52%|█████▏    | 516/1000 [00:00<00:00, 828.82it/s]

Bootstrapping roc_auc:  60%|██████    | 600/1000 [00:00<00:00, 830.55it/s]

Bootstrapping roc_auc:  69%|██████▊   | 687/1000 [00:00<00:00, 839.98it/s]

Bootstrapping roc_auc:  77%|███████▋  | 772/1000 [00:00<00:00, 836.89it/s]

Bootstrapping roc_auc:  86%|████████▌ | 856/1000 [00:01<00:00, 827.10it/s]

Bootstrapping roc_auc:  94%|█████████▍| 939/1000 [00:01<00:00, 821.73it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 832.15it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1134.41it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1160.78it/s]

Bootstrapping precision:  35%|███▍      | 349/1000 [00:00<00:00, 1150.40it/s]

Bootstrapping precision:  46%|████▋     | 465/1000 [00:00<00:00, 1148.70it/s]

Bootstrapping precision:  58%|█████▊    | 581/1000 [00:00<00:00, 1151.33it/s]

Bootstrapping precision:  70%|███████   | 700/1000 [00:00<00:00, 1161.55it/s]

Bootstrapping precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1173.48it/s]

Bootstrapping precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1167.90it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1159.46it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1179.46it/s]

Bootstrapping recall:  24%|██▍       | 239/1000 [00:00<00:00, 1193.32it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1202.51it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1206.33it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1191.63it/s]

Bootstrapping recall:  72%|███████▏  | 724/1000 [00:00<00:00, 1184.72it/s]

Bootstrapping recall:  84%|████████▍ | 843/1000 [00:00<00:00, 1184.20it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1189.84it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1190.91it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1205.01it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1203.60it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1208.02it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1209.68it/s]

Bootstrapping f1:  61%|██████    | 607/1000 [00:00<00:00, 1201.44it/s]

Bootstrapping f1:  73%|███████▎  | 728/1000 [00:00<00:00, 1195.12it/s]

Bootstrapping f1:  85%|████████▍ | 848/1000 [00:00<00:00, 1170.92it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1162.17it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1179.99it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 336/1000 [00:00<00:00, 3352.35it/s]

Bootstrapping accuracy:  69%|██████▊   | 687/1000 [00:00<00:00, 3442.61it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3463.35it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 131/1000 [00:00<00:00, 1308.44it/s]

Bootstrapping average_precision:  26%|██▌       | 262/1000 [00:00<00:00, 1295.74it/s]

Bootstrapping average_precision:  39%|███▉      | 392/1000 [00:00<00:00, 1296.10it/s]

Bootstrapping average_precision:  52%|█████▏    | 523/1000 [00:00<00:00, 1297.96it/s]

Bootstrapping average_precision:  65%|██████▌   | 654/1000 [00:00<00:00, 1297.86it/s]

Bootstrapping average_precision:  78%|███████▊  | 785/1000 [00:00<00:00, 1301.31it/s]

Bootstrapping average_precision:  92%|█████████▏| 917/1000 [00:00<00:00, 1304.68it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1301.38it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 841.70it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 834.28it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 833.36it/s]

Bootstrapping roc_auc:  34%|███▍      | 338/1000 [00:00<00:00, 835.00it/s]

Bootstrapping roc_auc:  42%|████▏     | 422/1000 [00:00<00:00, 832.84it/s]

Bootstrapping roc_auc:  51%|█████     | 506/1000 [00:00<00:00, 829.04it/s]

Bootstrapping roc_auc:  59%|█████▉    | 589/1000 [00:00<00:00, 823.64it/s]

Bootstrapping roc_auc:  67%|██████▋   | 672/1000 [00:00<00:00, 823.86it/s]

Bootstrapping roc_auc:  76%|███████▌  | 755/1000 [00:00<00:00, 821.71it/s]

Bootstrapping roc_auc:  84%|████████▍ | 838/1000 [00:01<00:00, 823.42it/s]

Bootstrapping roc_auc:  92%|█████████▏| 922/1000 [00:01<00:00, 827.36it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 829.66it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1201.30it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1201.11it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1206.15it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1207.82it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1201.41it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1203.47it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1206.30it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1208.34it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1205.24it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1201.12it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1199.18it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1202.41it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1208.92it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1208.37it/s]

Bootstrapping recall:  73%|███████▎  | 728/1000 [00:00<00:00, 1209.14it/s]

Bootstrapping recall:  85%|████████▍ | 849/1000 [00:00<00:00, 1206.69it/s]

Bootstrapping recall:  97%|█████████▋| 970/1000 [00:00<00:00, 1199.71it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1202.62it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1203.88it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1205.30it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1199.45it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1201.52it/s]

Bootstrapping f1:  61%|██████    | 606/1000 [00:00<00:00, 1206.44it/s]

Bootstrapping f1:  73%|███████▎  | 727/1000 [00:00<00:00, 1193.54it/s]

Bootstrapping f1:  85%|████████▍ | 847/1000 [00:00<00:00, 1184.01it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1178.94it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1189.66it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3524.43it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3537.36it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3538.18it/s]

Processing Simplified Clinician Consensus — 16 nodes, 16 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1314.40it/s]

Bootstrapping average_precision:  27%|██▋       | 267/1000 [00:00<00:00, 1332.98it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1352.00it/s]

Bootstrapping average_precision:  54%|█████▍    | 541/1000 [00:00<00:00, 1345.37it/s]

Bootstrapping average_precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1347.47it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1358.78it/s]

Bootstrapping average_precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1368.08it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1356.15it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 862.72it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 865.29it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 871.82it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 873.31it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 873.39it/s]

Bootstrapping roc_auc:  53%|█████▎    | 526/1000 [00:00<00:00, 865.62it/s]

Bootstrapping roc_auc:  61%|██████▏   | 613/1000 [00:00<00:00, 858.55it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 860.95it/s]

Bootstrapping roc_auc:  79%|███████▊  | 787/1000 [00:00<00:00, 855.36it/s]

Bootstrapping roc_auc:  87%|████████▋ | 873/1000 [00:01<00:00, 849.02it/s]

Bootstrapping roc_auc:  96%|█████████▌| 958/1000 [00:01<00:00, 846.87it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 857.70it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1200.33it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1202.70it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1209.30it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1207.05it/s]

Bootstrapping precision:  61%|██████    | 606/1000 [00:00<00:00, 1206.58it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1209.36it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1204.84it/s]

Bootstrapping precision:  97%|█████████▋| 970/1000 [00:00<00:00, 1206.12it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1205.51it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1190.75it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1200.98it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1199.91it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1202.49it/s]

Bootstrapping recall:  60%|██████    | 605/1000 [00:00<00:00, 1208.39it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1206.40it/s]

Bootstrapping recall:  85%|████████▍ | 849/1000 [00:00<00:00, 1211.58it/s]

Bootstrapping recall:  97%|█████████▋| 971/1000 [00:00<00:00, 1206.62it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1204.42it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1175.19it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1188.52it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1196.27it/s]

Bootstrapping f1:  48%|████▊     | 481/1000 [00:00<00:00, 1202.76it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1203.61it/s]

Bootstrapping f1:  72%|███████▏  | 724/1000 [00:00<00:00, 1205.67it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1207.63it/s]

Bootstrapping f1:  97%|█████████▋| 968/1000 [00:00<00:00, 1208.38it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1202.61it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3565.08it/s]

Bootstrapping accuracy:  71%|███████▏  | 714/1000 [00:00<00:00, 3561.17it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3562.05it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1350.52it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1358.47it/s]

Bootstrapping average_precision:  41%|████      | 409/1000 [00:00<00:00, 1358.22it/s]

Bootstrapping average_precision:  55%|█████▍    | 545/1000 [00:00<00:00, 1357.10it/s]

Bootstrapping average_precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1356.43it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1354.14it/s]

Bootstrapping average_precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1351.74it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1352.65it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 839.49it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 850.05it/s]

Bootstrapping roc_auc:  26%|██▌       | 257/1000 [00:00<00:00, 858.61it/s]

Bootstrapping roc_auc:  34%|███▍      | 343/1000 [00:00<00:00, 843.88it/s]

Bootstrapping roc_auc:  43%|████▎     | 428/1000 [00:00<00:00, 839.56it/s]

Bootstrapping roc_auc:  51%|█████▏    | 513/1000 [00:00<00:00, 843.02it/s]

Bootstrapping roc_auc:  60%|█████▉    | 599/1000 [00:00<00:00, 847.63it/s]

Bootstrapping roc_auc:  69%|██████▊   | 686/1000 [00:00<00:00, 854.04it/s]

Bootstrapping roc_auc:  77%|███████▋  | 772/1000 [00:00<00:00, 855.67it/s]

Bootstrapping roc_auc:  86%|████████▌ | 858/1000 [00:01<00:00, 855.14it/s]

Bootstrapping roc_auc:  94%|█████████▍| 945/1000 [00:01<00:00, 857.17it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 852.06it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1181.27it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1184.43it/s]

Bootstrapping precision:  36%|███▌      | 357/1000 [00:00<00:00, 1185.47it/s]

Bootstrapping precision:  48%|████▊     | 476/1000 [00:00<00:00, 1173.23it/s]

Bootstrapping precision:  60%|█████▉    | 595/1000 [00:00<00:00, 1178.24it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1191.49it/s]

Bootstrapping precision:  84%|████████▍ | 839/1000 [00:00<00:00, 1199.64it/s]

Bootstrapping precision:  96%|█████████▌| 961/1000 [00:00<00:00, 1203.24it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1192.60it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1212.57it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1211.30it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1212.53it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1197.46it/s]

Bootstrapping recall:  61%|██████    | 608/1000 [00:00<00:00, 1165.62it/s]

Bootstrapping recall:  73%|███████▎  | 728/1000 [00:00<00:00, 1174.13it/s]

Bootstrapping recall:  85%|████████▍ | 847/1000 [00:00<00:00, 1178.40it/s]

Bootstrapping recall:  97%|█████████▋| 967/1000 [00:00<00:00, 1182.90it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1183.18it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1183.10it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1175.26it/s]

Bootstrapping f1:  36%|███▌      | 356/1000 [00:00<00:00, 1165.13it/s]

Bootstrapping f1:  47%|████▋     | 474/1000 [00:00<00:00, 1168.09it/s]

Bootstrapping f1:  60%|█████▉    | 595/1000 [00:00<00:00, 1180.89it/s]

Bootstrapping f1:  72%|███████▏  | 715/1000 [00:00<00:00, 1185.55it/s]

Bootstrapping f1:  84%|████████▎ | 835/1000 [00:00<00:00, 1189.44it/s]

Bootstrapping f1:  95%|█████████▌| 954/1000 [00:00<00:00, 1188.97it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1182.45it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3533.84it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3555.06it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3551.44it/s]

Processing Clinician Consensus $\cap$ PCMB — 21 nodes, 20 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1357.83it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1366.75it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1365.25it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1324.40it/s]

Bootstrapping average_precision:  68%|██████▊   | 684/1000 [00:00<00:00, 1335.82it/s]

Bootstrapping average_precision:  82%|████████▏ | 821/1000 [00:00<00:00, 1345.76it/s]

Bootstrapping average_precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1350.39it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1347.57it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 869.74it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 860.68it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 843.59it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 837.53it/s]

Bootstrapping roc_auc:  43%|████▎     | 430/1000 [00:00<00:00, 833.02it/s]

Bootstrapping roc_auc:  51%|█████▏    | 514/1000 [00:00<00:00, 829.43it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 826.43it/s]

Bootstrapping roc_auc:  68%|██████▊   | 680/1000 [00:00<00:00, 825.63it/s]

Bootstrapping roc_auc:  76%|███████▋  | 764/1000 [00:00<00:00, 829.94it/s]

Bootstrapping roc_auc:  85%|████████▍ | 849/1000 [00:01<00:00, 835.55it/s]

Bootstrapping roc_auc:  93%|█████████▎| 933/1000 [00:01<00:00, 835.03it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 834.22it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 110/1000 [00:00<00:00, 1096.92it/s]

Bootstrapping precision:  23%|██▎       | 227/1000 [00:00<00:00, 1138.51it/s]

Bootstrapping precision:  35%|███▍      | 348/1000 [00:00<00:00, 1168.24it/s]

Bootstrapping precision:  47%|████▋     | 470/1000 [00:00<00:00, 1186.29it/s]

Bootstrapping precision:  59%|█████▉    | 592/1000 [00:00<00:00, 1196.65it/s]

Bootstrapping precision:  71%|███████▏  | 714/1000 [00:00<00:00, 1203.68it/s]

Bootstrapping precision:  84%|████████▎ | 835/1000 [00:00<00:00, 1193.02it/s]

Bootstrapping precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1175.72it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1176.76it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1208.15it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1200.58it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1206.86it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1207.53it/s]

Bootstrapping recall:  61%|██████    | 607/1000 [00:00<00:00, 1210.16it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1205.80it/s]

Bootstrapping recall:  85%|████████▌ | 851/1000 [00:00<00:00, 1208.97it/s]

Bootstrapping recall:  97%|█████████▋| 973/1000 [00:00<00:00, 1209.45it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1205.82it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1189.19it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1204.73it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1204.41it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1207.20it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1206.64it/s]

Bootstrapping f1:  73%|███████▎  | 728/1000 [00:00<00:00, 1212.14it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1212.29it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1214.88it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1209.80it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3558.26it/s]

Bootstrapping accuracy:  72%|███████▏  | 715/1000 [00:00<00:00, 3574.74it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3567.89it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1339.56it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1353.14it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1344.33it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1349.07it/s]

Bootstrapping average_precision:  68%|██████▊   | 678/1000 [00:00<00:00, 1345.41it/s]

Bootstrapping average_precision:  81%|████████▏ | 814/1000 [00:00<00:00, 1347.79it/s]

Bootstrapping average_precision:  95%|█████████▍| 949/1000 [00:00<00:00, 1347.49it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1346.66it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 863.54it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 856.49it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 858.90it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 852.22it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 852.96it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 857.54it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 859.64it/s]

Bootstrapping roc_auc:  69%|██████▉   | 694/1000 [00:00<00:00, 861.08it/s]

Bootstrapping roc_auc:  78%|███████▊  | 781/1000 [00:00<00:00, 862.26it/s]

Bootstrapping roc_auc:  87%|████████▋ | 869/1000 [00:01<00:00, 866.68it/s]

Bootstrapping roc_auc:  96%|█████████▌| 956/1000 [00:01<00:00, 867.47it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 861.43it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1208.24it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1206.57it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1211.96it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1194.11it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1191.83it/s]

Bootstrapping precision:  73%|███████▎  | 727/1000 [00:00<00:00, 1189.86it/s]

Bootstrapping precision:  85%|████████▍ | 847/1000 [00:00<00:00, 1189.88it/s]

Bootstrapping precision:  97%|█████████▋| 969/1000 [00:00<00:00, 1197.38it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.33it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1203.78it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1205.19it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1209.01it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1213.02it/s]

Bootstrapping recall:  61%|██████    | 609/1000 [00:00<00:00, 1215.90it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1217.85it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1218.53it/s]

Bootstrapping recall:  98%|█████████▊| 976/1000 [00:00<00:00, 1216.18it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1213.42it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1207.67it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1212.89it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1216.71it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1216.86it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1214.67it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1213.62it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1212.80it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1213.86it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1213.40it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3567.50it/s]

Bootstrapping accuracy:  71%|███████▏  | 714/1000 [00:00<00:00, 3535.31it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3543.47it/s]

Processing Golem — 17 nodes, 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1334.80it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1317.13it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 1324.73it/s]

Bootstrapping average_precision:  54%|█████▎    | 535/1000 [00:00<00:00, 1322.06it/s]

Bootstrapping average_precision:  67%|██████▋   | 670/1000 [00:00<00:00, 1328.90it/s]

Bootstrapping average_precision:  81%|████████  | 807/1000 [00:00<00:00, 1339.89it/s]

Bootstrapping average_precision:  94%|█████████▍| 944/1000 [00:00<00:00, 1348.54it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1338.04it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 861.40it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 860.02it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 865.21it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 867.72it/s]

Bootstrapping roc_auc:  44%|████▎     | 437/1000 [00:00<00:00, 868.30it/s]

Bootstrapping roc_auc:  52%|█████▏    | 524/1000 [00:00<00:00, 868.55it/s]

Bootstrapping roc_auc:  61%|██████    | 612/1000 [00:00<00:00, 869.07it/s]

Bootstrapping roc_auc:  70%|██████▉   | 699/1000 [00:00<00:00, 868.29it/s]

Bootstrapping roc_auc:  79%|███████▊  | 786/1000 [00:00<00:00, 866.90it/s]

Bootstrapping roc_auc:  87%|████████▋ | 873/1000 [00:01<00:00, 866.44it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 864.93it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 865.53it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1204.75it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1210.71it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1192.27it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1195.26it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1202.83it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1208.09it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1210.25it/s]

Bootstrapping precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1205.03it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1202.53it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1191.35it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1195.42it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1200.41it/s]

Bootstrapping recall:  48%|████▊     | 482/1000 [00:00<00:00, 1199.91it/s]

Bootstrapping recall:  60%|██████    | 602/1000 [00:00<00:00, 1198.92it/s]

Bootstrapping recall:  72%|███████▏  | 722/1000 [00:00<00:00, 1189.84it/s]

Bootstrapping recall:  84%|████████▍ | 842/1000 [00:00<00:00, 1191.72it/s]

Bootstrapping recall:  96%|█████████▌| 962/1000 [00:00<00:00, 1191.88it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1193.02it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1200.65it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1207.34it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1208.34it/s]

Bootstrapping f1:  48%|████▊     | 485/1000 [00:00<00:00, 1195.81it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1196.15it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1196.40it/s]

Bootstrapping f1:  84%|████████▍ | 845/1000 [00:00<00:00, 1194.23it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1198.67it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1198.71it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3496.82it/s]

Bootstrapping accuracy:  70%|███████   | 702/1000 [00:00<00:00, 3509.33it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3524.50it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1342.61it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1352.29it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1357.41it/s]

Bootstrapping average_precision:  55%|█████▍    | 545/1000 [00:00<00:00, 1359.88it/s]

Bootstrapping average_precision:  68%|██████▊   | 682/1000 [00:00<00:00, 1361.56it/s]

Bootstrapping average_precision:  82%|████████▏ | 819/1000 [00:00<00:00, 1361.22it/s]

Bootstrapping average_precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1355.76it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1353.40it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 860.93it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 861.40it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 866.47it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 867.47it/s]

Bootstrapping roc_auc:  44%|████▎     | 437/1000 [00:00<00:00, 868.80it/s]

Bootstrapping roc_auc:  52%|█████▏    | 524/1000 [00:00<00:00, 867.74it/s]

Bootstrapping roc_auc:  61%|██████    | 611/1000 [00:00<00:00, 868.12it/s]

Bootstrapping roc_auc:  70%|██████▉   | 698/1000 [00:00<00:00, 868.58it/s]

Bootstrapping roc_auc:  79%|███████▊  | 786/1000 [00:00<00:00, 869.34it/s]

Bootstrapping roc_auc:  87%|████████▋ | 874/1000 [00:01<00:00, 869.54it/s]

Bootstrapping roc_auc:  96%|█████████▌| 961/1000 [00:01<00:00, 869.62it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 868.23it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1214.98it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1209.44it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1212.33it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1211.17it/s]

Bootstrapping precision:  61%|██████    | 611/1000 [00:00<00:00, 1215.59it/s]

Bootstrapping precision:  73%|███████▎  | 734/1000 [00:00<00:00, 1217.16it/s]

Bootstrapping precision:  86%|████████▌ | 857/1000 [00:00<00:00, 1219.53it/s]

Bootstrapping precision:  98%|█████████▊| 979/1000 [00:00<00:00, 1215.86it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1214.17it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1218.45it/s]

Bootstrapping recall:  24%|██▍       | 245/1000 [00:00<00:00, 1221.71it/s]

Bootstrapping recall:  37%|███▋      | 368/1000 [00:00<00:00, 1223.53it/s]

Bootstrapping recall:  49%|████▉     | 491/1000 [00:00<00:00, 1224.57it/s]

Bootstrapping recall:  61%|██████▏   | 614/1000 [00:00<00:00, 1225.16it/s]

Bootstrapping recall:  74%|███████▎  | 737/1000 [00:00<00:00, 1222.32it/s]

Bootstrapping recall:  86%|████████▌ | 860/1000 [00:00<00:00, 1224.00it/s]

Bootstrapping recall:  98%|█████████▊| 984/1000 [00:00<00:00, 1226.84it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1223.99it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1219.15it/s]

Bootstrapping f1:  24%|██▍       | 245/1000 [00:00<00:00, 1222.58it/s]

Bootstrapping f1:  37%|███▋      | 368/1000 [00:00<00:00, 1221.90it/s]

Bootstrapping f1:  49%|████▉     | 491/1000 [00:00<00:00, 1218.50it/s]

Bootstrapping f1:  62%|██████▏   | 615/1000 [00:00<00:00, 1223.52it/s]

Bootstrapping f1:  74%|███████▍  | 738/1000 [00:00<00:00, 1222.45it/s]

Bootstrapping f1:  86%|████████▌ | 861/1000 [00:00<00:00, 1219.77it/s]

Bootstrapping f1:  98%|█████████▊| 983/1000 [00:00<00:00, 1198.38it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1211.10it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 360/1000 [00:00<00:00, 3592.10it/s]

Bootstrapping accuracy:  72%|███████▏  | 721/1000 [00:00<00:00, 3601.26it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3585.76it/s]

Processing PCMB — 32 nodes, 78 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1362.82it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1373.19it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1368.53it/s]

Bootstrapping average_precision:  55%|█████▌    | 551/1000 [00:00<00:00, 1367.63it/s]

Bootstrapping average_precision:  69%|██████▉   | 689/1000 [00:00<00:00, 1369.09it/s]

Bootstrapping average_precision:  83%|████████▎ | 826/1000 [00:00<00:00, 1366.01it/s]

Bootstrapping average_precision:  96%|█████████▋| 963/1000 [00:00<00:00, 1362.60it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1364.08it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 857.97it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 854.53it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 856.71it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 859.43it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 861.32it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 862.48it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 864.25it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 862.99it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 864.83it/s]

Bootstrapping roc_auc:  87%|████████▋ | 867/1000 [00:01<00:00, 857.51it/s]

Bootstrapping roc_auc:  95%|█████████▌| 953/1000 [00:01<00:00, 854.02it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 859.14it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1201.02it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1203.60it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1208.11it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1209.53it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1208.48it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1200.18it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1206.13it/s]

Bootstrapping precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1206.66it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1205.16it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1204.67it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1205.83it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1204.04it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1201.50it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1206.05it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 1207.34it/s]

Bootstrapping recall:  85%|████████▍ | 848/1000 [00:00<00:00, 1207.19it/s]

Bootstrapping recall:  97%|█████████▋| 969/1000 [00:00<00:00, 1207.51it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1205.49it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1213.58it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1209.05it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1211.17it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1211.21it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1209.89it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1212.09it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1213.28it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1208.30it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1209.03it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3563.76it/s]

Bootstrapping accuracy:  72%|███████▏  | 717/1000 [00:00<00:00, 3580.98it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3575.01it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1351.61it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1349.14it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1359.48it/s]

Bootstrapping average_precision:  55%|█████▍    | 546/1000 [00:00<00:00, 1357.32it/s]

Bootstrapping average_precision:  68%|██████▊   | 682/1000 [00:00<00:00, 1343.74it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1334.84it/s]

Bootstrapping average_precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1334.04it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1341.09it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 852.34it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 846.96it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 852.80it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 856.93it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 859.34it/s]

Bootstrapping roc_auc:  52%|█████▏    | 518/1000 [00:00<00:00, 859.50it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 861.44it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 864.94it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 866.17it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 867.38it/s]

Bootstrapping roc_auc:  96%|█████████▌| 956/1000 [00:01<00:00, 868.73it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 862.86it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1213.83it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1215.31it/s]

Bootstrapping precision:  37%|███▋      | 367/1000 [00:00<00:00, 1221.16it/s]

Bootstrapping precision:  49%|████▉     | 490/1000 [00:00<00:00, 1222.65it/s]

Bootstrapping precision:  61%|██████▏   | 613/1000 [00:00<00:00, 1221.62it/s]

Bootstrapping precision:  74%|███████▎  | 736/1000 [00:00<00:00, 1221.44it/s]

Bootstrapping precision:  86%|████████▌ | 859/1000 [00:00<00:00, 1222.05it/s]

Bootstrapping precision:  98%|█████████▊| 982/1000 [00:00<00:00, 1222.66it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1220.60it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1219.72it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1218.59it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1218.96it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1219.35it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1217.41it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1210.81it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1216.59it/s]

Bootstrapping recall:  98%|█████████▊| 978/1000 [00:00<00:00, 1219.02it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1216.86it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1192.45it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1187.50it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1198.33it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1202.89it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1201.26it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1205.79it/s]

Bootstrapping f1:  85%|████████▍ | 849/1000 [00:00<00:00, 1211.54it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1217.82it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1207.80it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  32%|███▏      | 315/1000 [00:00<00:00, 3142.74it/s]

Bootstrapping accuracy:  67%|██████▋   | 673/1000 [00:00<00:00, 3393.98it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3422.35it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB — 15 nodes, 14 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1370.91it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1370.58it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1370.63it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1373.13it/s]

Bootstrapping average_precision:  69%|██████▉   | 691/1000 [00:00<00:00, 1378.46it/s]

Bootstrapping average_precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1378.47it/s]

Bootstrapping average_precision:  97%|█████████▋| 968/1000 [00:00<00:00, 1380.59it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1376.25it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 876.55it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 875.92it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 870.96it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 871.02it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 872.69it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 873.85it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 874.26it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 874.38it/s]

Bootstrapping roc_auc:  79%|███████▉  | 792/1000 [00:00<00:00, 875.23it/s]

Bootstrapping roc_auc:  88%|████████▊ | 881/1000 [00:01<00:00, 877.40it/s]

Bootstrapping roc_auc:  97%|█████████▋| 969/1000 [00:01<00:00, 877.54it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 873.75it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1186.66it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1184.99it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1195.64it/s]

Bootstrapping precision:  48%|████▊     | 480/1000 [00:00<00:00, 1199.74it/s]

Bootstrapping precision:  60%|██████    | 600/1000 [00:00<00:00, 1197.15it/s]

Bootstrapping precision:  72%|███████▏  | 721/1000 [00:00<00:00, 1201.42it/s]

Bootstrapping precision:  84%|████████▍ | 842/1000 [00:00<00:00, 1201.43it/s]

Bootstrapping precision:  96%|█████████▋| 963/1000 [00:00<00:00, 1202.33it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.91it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1204.23it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1209.50it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1214.26it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1208.02it/s]

Bootstrapping recall:  61%|██████    | 609/1000 [00:00<00:00, 1205.08it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1210.03it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1211.41it/s]

Bootstrapping recall:  98%|█████████▊| 976/1000 [00:00<00:00, 1200.28it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1202.85it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1200.02it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1166.72it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1161.06it/s]

Bootstrapping f1:  48%|████▊     | 476/1000 [00:00<00:00, 1150.98it/s]

Bootstrapping f1:  59%|█████▉    | 592/1000 [00:00<00:00, 1149.68it/s]

Bootstrapping f1:  71%|███████   | 707/1000 [00:00<00:00, 1146.70it/s]

Bootstrapping f1:  82%|████████▏ | 822/1000 [00:00<00:00, 1141.54it/s]

Bootstrapping f1:  94%|█████████▎| 937/1000 [00:00<00:00, 1142.28it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1151.26it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3528.94it/s]

Bootstrapping accuracy:  71%|███████   | 707/1000 [00:00<00:00, 3530.90it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3528.46it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1316.05it/s]

Bootstrapping average_precision:  26%|██▋       | 265/1000 [00:00<00:00, 1319.51it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 1333.83it/s]

Bootstrapping average_precision:  54%|█████▎    | 537/1000 [00:00<00:00, 1342.64it/s]

Bootstrapping average_precision:  67%|██████▋   | 674/1000 [00:00<00:00, 1350.14it/s]

Bootstrapping average_precision:  81%|████████  | 810/1000 [00:00<00:00, 1351.21it/s]

Bootstrapping average_precision:  95%|█████████▍| 947/1000 [00:00<00:00, 1354.73it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1346.28it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 867.13it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 867.71it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 865.69it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 866.62it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 863.95it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 860.17it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 864.43it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 864.77it/s]

Bootstrapping roc_auc:  78%|███████▊  | 785/1000 [00:00<00:00, 867.09it/s]

Bootstrapping roc_auc:  87%|████████▋ | 872/1000 [00:01<00:00, 864.86it/s]

Bootstrapping roc_auc:  96%|█████████▌| 959/1000 [00:01<00:00, 862.73it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 862.45it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1191.29it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1199.32it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1209.43it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1213.15it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1213.04it/s]

Bootstrapping precision:  73%|███████▎  | 731/1000 [00:00<00:00, 1215.73it/s]

Bootstrapping precision:  85%|████████▌ | 854/1000 [00:00<00:00, 1218.51it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1220.23it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1214.07it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1223.43it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1223.07it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1208.77it/s]

Bootstrapping recall:  49%|████▉     | 490/1000 [00:00<00:00, 1205.70it/s]

Bootstrapping recall:  61%|██████    | 612/1000 [00:00<00:00, 1208.48it/s]

Bootstrapping recall:  73%|███████▎  | 733/1000 [00:00<00:00, 1208.19it/s]

Bootstrapping recall:  86%|████████▌ | 856/1000 [00:00<00:00, 1212.29it/s]

Bootstrapping recall:  98%|█████████▊| 979/1000 [00:00<00:00, 1216.53it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1212.74it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 123/1000 [00:00<00:00, 1223.25it/s]

Bootstrapping f1:  25%|██▍       | 246/1000 [00:00<00:00, 1226.48it/s]

Bootstrapping f1:  37%|███▋      | 369/1000 [00:00<00:00, 1224.83it/s]

Bootstrapping f1:  49%|████▉     | 492/1000 [00:00<00:00, 1222.82it/s]

Bootstrapping f1:  62%|██████▏   | 615/1000 [00:00<00:00, 1220.85it/s]

Bootstrapping f1:  74%|███████▍  | 738/1000 [00:00<00:00, 1213.69it/s]

Bootstrapping f1:  86%|████████▌ | 860/1000 [00:00<00:00, 1211.33it/s]

Bootstrapping f1:  98%|█████████▊| 982/1000 [00:00<00:00, 1211.58it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1214.48it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3559.42it/s]

Bootstrapping accuracy:  71%|███████▏  | 714/1000 [00:00<00:00, 3571.47it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3568.52it/s]

Processing Simplified PCMB — 18 nodes, 50 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 140/1000 [00:00<00:00, 1392.04it/s]

Bootstrapping average_precision:  28%|██▊       | 280/1000 [00:00<00:00, 1395.38it/s]

Bootstrapping average_precision:  42%|████▏     | 420/1000 [00:00<00:00, 1388.97it/s]

Bootstrapping average_precision:  56%|█████▌    | 560/1000 [00:00<00:00, 1392.75it/s]

Bootstrapping average_precision:  70%|███████   | 700/1000 [00:00<00:00, 1380.13it/s]

Bootstrapping average_precision:  84%|████████▍ | 839/1000 [00:00<00:00, 1361.15it/s]

Bootstrapping average_precision:  98%|█████████▊| 976/1000 [00:00<00:00, 1346.80it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1364.35it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 80/1000 [00:00<00:01, 795.35it/s]

Bootstrapping roc_auc:  16%|█▋        | 163/1000 [00:00<00:01, 814.32it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 820.63it/s]

Bootstrapping roc_auc:  33%|███▎      | 332/1000 [00:00<00:00, 835.37it/s]

Bootstrapping roc_auc:  42%|████▏     | 420/1000 [00:00<00:00, 850.33it/s]

Bootstrapping roc_auc:  51%|█████     | 507/1000 [00:00<00:00, 854.90it/s]

Bootstrapping roc_auc:  59%|█████▉    | 593/1000 [00:00<00:00, 851.37it/s]

Bootstrapping roc_auc:  68%|██████▊   | 679/1000 [00:00<00:00, 840.01it/s]

Bootstrapping roc_auc:  76%|███████▋  | 764/1000 [00:00<00:00, 833.93it/s]

Bootstrapping roc_auc:  85%|████████▍ | 849/1000 [00:01<00:00, 837.42it/s]

Bootstrapping roc_auc:  94%|█████████▎| 937/1000 [00:01<00:00, 848.26it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 842.92it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1149.66it/s]

Bootstrapping precision:  23%|██▎       | 233/1000 [00:00<00:00, 1163.50it/s]

Bootstrapping precision:  35%|███▌      | 353/1000 [00:00<00:00, 1179.35it/s]

Bootstrapping precision:  47%|████▋     | 474/1000 [00:00<00:00, 1189.07it/s]

Bootstrapping precision:  59%|█████▉    | 593/1000 [00:00<00:00, 1176.24it/s]

Bootstrapping precision:  71%|███████   | 711/1000 [00:00<00:00, 1167.51it/s]

Bootstrapping precision:  83%|████████▎ | 828/1000 [00:00<00:00, 1149.96it/s]

Bootstrapping precision:  94%|█████████▍| 945/1000 [00:00<00:00, 1153.02it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1160.59it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1145.06it/s]

Bootstrapping recall:  23%|██▎       | 234/1000 [00:00<00:00, 1167.24it/s]

Bootstrapping recall:  35%|███▌      | 352/1000 [00:00<00:00, 1169.65it/s]

Bootstrapping recall:  47%|████▋     | 469/1000 [00:00<00:00, 1154.06it/s]

Bootstrapping recall:  58%|█████▊    | 585/1000 [00:00<00:00, 1139.68it/s]

Bootstrapping recall:  70%|███████   | 703/1000 [00:00<00:00, 1151.02it/s]

Bootstrapping recall:  82%|████████▏ | 819/1000 [00:00<00:00, 1151.00it/s]

Bootstrapping recall:  94%|█████████▍| 938/1000 [00:00<00:00, 1163.08it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1159.18it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1209.61it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1208.33it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1206.51it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1180.46it/s]

Bootstrapping f1:  60%|██████    | 603/1000 [00:00<00:00, 1170.15it/s]

Bootstrapping f1:  72%|███████▏  | 721/1000 [00:00<00:00, 1157.21it/s]

Bootstrapping f1:  84%|████████▎ | 837/1000 [00:00<00:00, 1150.83it/s]

Bootstrapping f1:  95%|█████████▌| 953/1000 [00:00<00:00, 1153.29it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1166.06it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 342/1000 [00:00<00:00, 3411.47it/s]

Bootstrapping accuracy:  68%|██████▊   | 685/1000 [00:00<00:00, 3417.56it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3455.32it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 128/1000 [00:00<00:00, 1277.52it/s]

Bootstrapping average_precision:  26%|██▌       | 258/1000 [00:00<00:00, 1285.79it/s]

Bootstrapping average_precision:  39%|███▉      | 389/1000 [00:00<00:00, 1295.37it/s]

Bootstrapping average_precision:  52%|█████▏    | 519/1000 [00:00<00:00, 1296.96it/s]

Bootstrapping average_precision:  65%|██████▌   | 650/1000 [00:00<00:00, 1299.80it/s]

Bootstrapping average_precision:  78%|███████▊  | 782/1000 [00:00<00:00, 1303.66it/s]

Bootstrapping average_precision:  91%|█████████▏| 913/1000 [00:00<00:00, 1304.09it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1298.85it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 832.16it/s]

Bootstrapping roc_auc:  17%|█▋        | 169/1000 [00:00<00:00, 837.34it/s]

Bootstrapping roc_auc:  25%|██▌       | 253/1000 [00:00<00:00, 838.39it/s]

Bootstrapping roc_auc:  34%|███▎      | 337/1000 [00:00<00:00, 835.33it/s]

Bootstrapping roc_auc:  42%|████▏     | 421/1000 [00:00<00:00, 836.54it/s]

Bootstrapping roc_auc:  50%|█████     | 505/1000 [00:00<00:00, 833.71it/s]

Bootstrapping roc_auc:  59%|█████▉    | 590/1000 [00:00<00:00, 835.20it/s]

Bootstrapping roc_auc:  68%|██████▊   | 675/1000 [00:00<00:00, 837.19it/s]

Bootstrapping roc_auc:  76%|███████▌  | 761/1000 [00:00<00:00, 840.91it/s]

Bootstrapping roc_auc:  85%|████████▍ | 846/1000 [00:01<00:00, 824.57it/s]

Bootstrapping roc_auc:  93%|█████████▎| 931/1000 [00:01<00:00, 831.23it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 834.36it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1203.05it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1196.07it/s]

Bootstrapping precision:  36%|███▌      | 362/1000 [00:00<00:00, 1180.97it/s]

Bootstrapping precision:  48%|████▊     | 482/1000 [00:00<00:00, 1185.03it/s]

Bootstrapping precision:  60%|██████    | 603/1000 [00:00<00:00, 1193.73it/s]

Bootstrapping precision:  72%|███████▏  | 723/1000 [00:00<00:00, 1187.53it/s]

Bootstrapping precision:  84%|████████▍ | 844/1000 [00:00<00:00, 1191.25it/s]

Bootstrapping precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1190.84it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1186.29it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1164.22it/s]

Bootstrapping recall:  23%|██▎       | 234/1000 [00:00<00:00, 1160.20it/s]

Bootstrapping recall:  35%|███▌      | 351/1000 [00:00<00:00, 1145.47it/s]

Bootstrapping recall:  47%|████▋     | 468/1000 [00:00<00:00, 1151.84it/s]

Bootstrapping recall:  59%|█████▉    | 588/1000 [00:00<00:00, 1165.36it/s]

Bootstrapping recall:  71%|███████   | 706/1000 [00:00<00:00, 1169.58it/s]

Bootstrapping recall:  82%|████████▏ | 823/1000 [00:00<00:00, 1163.55it/s]

Bootstrapping recall:  94%|█████████▍| 940/1000 [00:00<00:00, 1149.86it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1150.23it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 112/1000 [00:00<00:00, 1111.60it/s]

Bootstrapping f1:  22%|██▎       | 225/1000 [00:00<00:00, 1118.41it/s]

Bootstrapping f1:  34%|███▎      | 337/1000 [00:00<00:00, 1118.23it/s]

Bootstrapping f1:  45%|████▌     | 451/1000 [00:00<00:00, 1123.78it/s]

Bootstrapping f1:  57%|█████▋    | 567/1000 [00:00<00:00, 1135.01it/s]

Bootstrapping f1:  68%|██████▊   | 683/1000 [00:00<00:00, 1143.18it/s]

Bootstrapping f1:  80%|████████  | 804/1000 [00:00<00:00, 1162.24it/s]

Bootstrapping f1:  93%|█████████▎| 926/1000 [00:00<00:00, 1177.52it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1154.93it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3549.81it/s]

Bootstrapping accuracy:  71%|███████   | 711/1000 [00:00<00:00, 3536.91it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3534.94it/s]

Processing Clinician Consensus $\cap$ Golem — 8 nodes, 7 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 127/1000 [00:00<00:00, 1266.71it/s]

Bootstrapping average_precision:  26%|██▌       | 257/1000 [00:00<00:00, 1284.11it/s]

Bootstrapping average_precision:  39%|███▉      | 392/1000 [00:00<00:00, 1311.12it/s]

Bootstrapping average_precision:  53%|█████▎    | 526/1000 [00:00<00:00, 1321.63it/s]

Bootstrapping average_precision:  66%|██████▌   | 659/1000 [00:00<00:00, 1318.95it/s]

Bootstrapping average_precision:  79%|███████▉  | 791/1000 [00:00<00:00, 1317.68it/s]

Bootstrapping average_precision:  92%|█████████▏| 923/1000 [00:00<00:00, 1314.33it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1306.50it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 82/1000 [00:00<00:01, 817.31it/s]

Bootstrapping roc_auc:  17%|█▋        | 167/1000 [00:00<00:00, 834.72it/s]

Bootstrapping roc_auc:  25%|██▌       | 251/1000 [00:00<00:00, 828.55it/s]

Bootstrapping roc_auc:  34%|███▎      | 335/1000 [00:00<00:00, 829.50it/s]

Bootstrapping roc_auc:  42%|████▏     | 422/1000 [00:00<00:00, 839.86it/s]

Bootstrapping roc_auc:  51%|█████     | 506/1000 [00:00<00:00, 824.21it/s]

Bootstrapping roc_auc:  59%|█████▉    | 589/1000 [00:00<00:00, 818.10it/s]

Bootstrapping roc_auc:  67%|██████▋   | 672/1000 [00:00<00:00, 819.35it/s]

Bootstrapping roc_auc:  76%|███████▌  | 757/1000 [00:00<00:00, 828.37it/s]

Bootstrapping roc_auc:  84%|████████▍ | 842/1000 [00:01<00:00, 831.56it/s]

Bootstrapping roc_auc:  93%|█████████▎| 926/1000 [00:01<00:00, 833.20it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 830.66it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 111/1000 [00:00<00:00, 1108.87it/s]

Bootstrapping precision:  22%|██▏       | 222/1000 [00:00<00:00, 1108.43it/s]

Bootstrapping precision:  34%|███▍      | 342/1000 [00:00<00:00, 1149.57it/s]

Bootstrapping precision:  46%|████▌     | 457/1000 [00:00<00:00, 1146.25it/s]

Bootstrapping precision:  57%|█████▊    | 575/1000 [00:00<00:00, 1157.51it/s]

Bootstrapping precision:  70%|██████▉   | 696/1000 [00:00<00:00, 1172.38it/s]

Bootstrapping precision:  81%|████████▏ | 814/1000 [00:00<00:00, 1168.25it/s]

Bootstrapping precision:  93%|█████████▎| 931/1000 [00:00<00:00, 1154.20it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1148.45it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 113/1000 [00:00<00:00, 1124.61it/s]

Bootstrapping recall:  23%|██▎       | 229/1000 [00:00<00:00, 1142.84it/s]

Bootstrapping recall:  35%|███▍      | 348/1000 [00:00<00:00, 1161.48it/s]

Bootstrapping recall:  47%|████▋     | 468/1000 [00:00<00:00, 1175.31it/s]

Bootstrapping recall:  59%|█████▉    | 590/1000 [00:00<00:00, 1188.77it/s]

Bootstrapping recall:  71%|███████   | 712/1000 [00:00<00:00, 1197.82it/s]

Bootstrapping recall:  83%|████████▎ | 833/1000 [00:00<00:00, 1201.62it/s]

Bootstrapping recall:  96%|█████████▌| 955/1000 [00:00<00:00, 1204.44it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1189.59it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1212.51it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1214.89it/s]

Bootstrapping f1:  37%|███▋      | 367/1000 [00:00<00:00, 1219.25it/s]

Bootstrapping f1:  49%|████▉     | 489/1000 [00:00<00:00, 1217.87it/s]

Bootstrapping f1:  61%|██████    | 611/1000 [00:00<00:00, 1190.01it/s]

Bootstrapping f1:  73%|███████▎  | 731/1000 [00:00<00:00, 1175.29it/s]

Bootstrapping f1:  85%|████████▍ | 849/1000 [00:00<00:00, 1173.32it/s]

Bootstrapping f1:  97%|█████████▋| 969/1000 [00:00<00:00, 1179.09it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1189.78it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 358/1000 [00:00<00:00, 3570.44it/s]

Bootstrapping accuracy:  72%|███████▏  | 718/1000 [00:00<00:00, 3582.02it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3578.89it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1366.94it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1368.22it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1362.25it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1359.38it/s]

Bootstrapping average_precision:  68%|██████▊   | 684/1000 [00:00<00:00, 1320.54it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1298.54it/s]

Bootstrapping average_precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1295.00it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1316.03it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 857.84it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 862.91it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 863.82it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 866.74it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 866.68it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 867.46it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 867.61it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 869.98it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 868.11it/s]

Bootstrapping roc_auc:  87%|████████▋ | 871/1000 [00:01<00:00, 867.66it/s]

Bootstrapping roc_auc:  96%|█████████▌| 958/1000 [00:01<00:00, 867.04it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.67it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1218.39it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1217.96it/s]

Bootstrapping precision:  37%|███▋      | 367/1000 [00:00<00:00, 1219.97it/s]

Bootstrapping precision:  49%|████▉     | 489/1000 [00:00<00:00, 1217.45it/s]

Bootstrapping precision:  61%|██████    | 612/1000 [00:00<00:00, 1221.62it/s]

Bootstrapping precision:  74%|███████▎  | 735/1000 [00:00<00:00, 1220.07it/s]

Bootstrapping precision:  86%|████████▌ | 858/1000 [00:00<00:00, 1221.90it/s]

Bootstrapping precision:  98%|█████████▊| 981/1000 [00:00<00:00, 1221.74it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1219.91it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1226.75it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1224.99it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1224.19it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1225.97it/s]

Bootstrapping recall:  62%|██████▏   | 616/1000 [00:00<00:00, 1227.59it/s]

Bootstrapping recall:  74%|███████▍  | 739/1000 [00:00<00:00, 1225.20it/s]

Bootstrapping recall:  86%|████████▌ | 862/1000 [00:00<00:00, 1224.06it/s]

Bootstrapping recall:  98%|█████████▊| 985/1000 [00:00<00:00, 1224.92it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1224.45it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 123/1000 [00:00<00:00, 1224.02it/s]

Bootstrapping f1:  25%|██▍       | 246/1000 [00:00<00:00, 1223.42it/s]

Bootstrapping f1:  37%|███▋      | 370/1000 [00:00<00:00, 1226.65it/s]

Bootstrapping f1:  49%|████▉     | 493/1000 [00:00<00:00, 1227.70it/s]

Bootstrapping f1:  62%|██████▏   | 617/1000 [00:00<00:00, 1228.56it/s]

Bootstrapping f1:  74%|███████▍  | 740/1000 [00:00<00:00, 1228.41it/s]

Bootstrapping f1:  86%|████████▋ | 863/1000 [00:00<00:00, 1227.17it/s]

Bootstrapping f1:  99%|█████████▊| 986/1000 [00:00<00:00, 1224.60it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1224.85it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 358/1000 [00:00<00:00, 3573.70it/s]

Bootstrapping accuracy:  72%|███████▏  | 719/1000 [00:00<00:00, 3593.20it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3592.97it/s]

Processing Simplified Golem — 12 nodes, 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1325.12it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1356.06it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1372.22it/s]

Bootstrapping average_precision:  55%|█████▌    | 550/1000 [00:00<00:00, 1377.59it/s]

Bootstrapping average_precision:  69%|██████▉   | 688/1000 [00:00<00:00, 1377.82it/s]

Bootstrapping average_precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1379.10it/s]

Bootstrapping average_precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1384.93it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1376.71it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 875.33it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 877.26it/s]

Bootstrapping roc_auc:  26%|██▋       | 265/1000 [00:00<00:00, 878.97it/s]

Bootstrapping roc_auc:  35%|███▌      | 353/1000 [00:00<00:00, 877.10it/s]

Bootstrapping roc_auc:  44%|████▍     | 441/1000 [00:00<00:00, 877.48it/s]

Bootstrapping roc_auc:  53%|█████▎    | 529/1000 [00:00<00:00, 872.30it/s]

Bootstrapping roc_auc:  62%|██████▏   | 617/1000 [00:00<00:00, 862.08it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 853.75it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 850.84it/s]

Bootstrapping roc_auc:  88%|████████▊ | 876/1000 [00:01<00:00, 848.35it/s]

Bootstrapping roc_auc:  96%|█████████▋| 964/1000 [00:01<00:00, 857.21it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 862.60it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1219.64it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1219.74it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1205.41it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1207.88it/s]

Bootstrapping precision:  61%|██████    | 609/1000 [00:00<00:00, 1208.40it/s]

Bootstrapping precision:  73%|███████▎  | 730/1000 [00:00<00:00, 1199.19it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1179.48it/s]

Bootstrapping precision:  97%|█████████▋| 969/1000 [00:00<00:00, 1178.32it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1193.00it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1160.22it/s]

Bootstrapping recall:  23%|██▎       | 234/1000 [00:00<00:00, 1132.42it/s]

Bootstrapping recall:  35%|███▍      | 348/1000 [00:00<00:00, 1132.89it/s]

Bootstrapping recall:  46%|████▋     | 465/1000 [00:00<00:00, 1143.46it/s]

Bootstrapping recall:  59%|█████▊    | 586/1000 [00:00<00:00, 1166.29it/s]

Bootstrapping recall:  71%|███████   | 707/1000 [00:00<00:00, 1180.68it/s]

Bootstrapping recall:  83%|████████▎ | 828/1000 [00:00<00:00, 1189.65it/s]

Bootstrapping recall:  95%|█████████▍| 947/1000 [00:00<00:00, 1187.71it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1168.68it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1152.37it/s]

Bootstrapping f1:  23%|██▎       | 232/1000 [00:00<00:00, 1155.79it/s]

Bootstrapping f1:  35%|███▍      | 349/1000 [00:00<00:00, 1159.40it/s]

Bootstrapping f1:  47%|████▋     | 466/1000 [00:00<00:00, 1162.22it/s]

Bootstrapping f1:  59%|█████▊    | 587/1000 [00:00<00:00, 1179.20it/s]

Bootstrapping f1:  71%|███████   | 706/1000 [00:00<00:00, 1182.34it/s]

Bootstrapping f1:  82%|████████▎ | 825/1000 [00:00<00:00, 1177.51it/s]

Bootstrapping f1:  94%|█████████▍| 943/1000 [00:00<00:00, 1172.43it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1170.52it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 342/1000 [00:00<00:00, 3417.84it/s]

Bootstrapping accuracy:  69%|██████▉   | 692/1000 [00:00<00:00, 3465.14it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3478.72it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1339.79it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1350.78it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 1350.63it/s]

Bootstrapping average_precision:  54%|█████▍    | 542/1000 [00:00<00:00, 1353.74it/s]

Bootstrapping average_precision:  68%|██████▊   | 678/1000 [00:00<00:00, 1338.94it/s]

Bootstrapping average_precision:  81%|████████  | 812/1000 [00:00<00:00, 1321.49it/s]

Bootstrapping average_precision:  94%|█████████▍| 945/1000 [00:00<00:00, 1308.83it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1324.94it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 829.93it/s]

Bootstrapping roc_auc:  17%|█▋        | 167/1000 [00:00<00:01, 817.87it/s]

Bootstrapping roc_auc:  25%|██▌       | 252/1000 [00:00<00:00, 828.86it/s]

Bootstrapping roc_auc:  34%|███▎      | 336/1000 [00:00<00:00, 832.38it/s]

Bootstrapping roc_auc:  42%|████▏     | 420/1000 [00:00<00:00, 819.91it/s]

Bootstrapping roc_auc:  50%|█████     | 503/1000 [00:00<00:00, 809.25it/s]

Bootstrapping roc_auc:  58%|█████▊    | 584/1000 [00:00<00:00, 805.43it/s]

Bootstrapping roc_auc:  66%|██████▋   | 665/1000 [00:00<00:00, 804.88it/s]

Bootstrapping roc_auc:  75%|███████▍  | 747/1000 [00:00<00:00, 808.58it/s]

Bootstrapping roc_auc:  83%|████████▎ | 829/1000 [00:01<00:00, 811.80it/s]

Bootstrapping roc_auc:  91%|█████████ | 911/1000 [00:01<00:00, 810.53it/s]

Bootstrapping roc_auc:  99%|█████████▉| 993/1000 [00:01<00:00, 812.10it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 813.37it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1173.22it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1199.43it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1201.16it/s]

Bootstrapping precision:  48%|████▊     | 482/1000 [00:00<00:00, 1199.25it/s]

Bootstrapping precision:  60%|██████    | 603/1000 [00:00<00:00, 1200.56it/s]

Bootstrapping precision:  72%|███████▏  | 724/1000 [00:00<00:00, 1198.24it/s]

Bootstrapping precision:  84%|████████▍ | 844/1000 [00:00<00:00, 1191.64it/s]

Bootstrapping precision:  97%|█████████▋| 966/1000 [00:00<00:00, 1199.77it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1198.03it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1214.39it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1215.23it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1216.02it/s]

Bootstrapping recall:  49%|████▉     | 489/1000 [00:00<00:00, 1218.05it/s]

Bootstrapping recall:  61%|██████    | 611/1000 [00:00<00:00, 1217.28it/s]

Bootstrapping recall:  73%|███████▎  | 733/1000 [00:00<00:00, 1217.85it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1207.99it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1209.13it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1212.24it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1215.77it/s]

Bootstrapping f1:  24%|██▍       | 245/1000 [00:00<00:00, 1219.70it/s]

Bootstrapping f1:  37%|███▋      | 367/1000 [00:00<00:00, 1192.83it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1183.85it/s]

Bootstrapping f1:  61%|██████    | 608/1000 [00:00<00:00, 1191.75it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1201.05it/s]

Bootstrapping f1:  85%|████████▌ | 851/1000 [00:00<00:00, 1182.70it/s]

Bootstrapping f1:  97%|█████████▋| 970/1000 [00:00<00:00, 1174.82it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1183.63it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 331/1000 [00:00<00:00, 3304.09it/s]

Bootstrapping accuracy:  67%|██████▋   | 669/1000 [00:00<00:00, 3347.86it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3398.60it/s]

Processing Golem $\cup$ PCMB — 48 nodes, 100 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1342.57it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1362.87it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1357.31it/s]

Bootstrapping average_precision:  55%|█████▍    | 546/1000 [00:00<00:00, 1353.17it/s]

Bootstrapping average_precision:  68%|██████▊   | 682/1000 [00:00<00:00, 1334.57it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1337.21it/s]

Bootstrapping average_precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1344.23it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1345.63it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 870.67it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 872.42it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 872.75it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 871.32it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 873.08it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 873.32it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 874.54it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 874.83it/s]

Bootstrapping roc_auc:  79%|███████▉  | 792/1000 [00:00<00:00, 874.87it/s]

Bootstrapping roc_auc:  88%|████████▊ | 880/1000 [00:01<00:00, 873.88it/s]

Bootstrapping roc_auc:  97%|█████████▋| 968/1000 [00:01<00:00, 873.01it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 873.09it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1192.35it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1174.51it/s]

Bootstrapping precision:  36%|███▌      | 358/1000 [00:00<00:00, 1165.17it/s]

Bootstrapping precision:  48%|████▊     | 475/1000 [00:00<00:00, 1151.47it/s]

Bootstrapping precision:  59%|█████▉    | 593/1000 [00:00<00:00, 1158.97it/s]

Bootstrapping precision:  71%|███████   | 711/1000 [00:00<00:00, 1164.25it/s]

Bootstrapping precision:  83%|████████▎ | 828/1000 [00:00<00:00, 1152.11it/s]

Bootstrapping precision:  94%|█████████▍| 944/1000 [00:00<00:00, 1148.04it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1158.87it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1194.96it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1199.16it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1186.13it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1186.18it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1192.76it/s]

Bootstrapping recall:  72%|███████▏  | 721/1000 [00:00<00:00, 1176.06it/s]

Bootstrapping recall:  84%|████████▍ | 839/1000 [00:00<00:00, 1163.56it/s]

Bootstrapping recall:  96%|█████████▌| 956/1000 [00:00<00:00, 1163.20it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1175.75it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1186.08it/s]

Bootstrapping f1:  24%|██▍       | 239/1000 [00:00<00:00, 1192.85it/s]

Bootstrapping f1:  36%|███▌      | 360/1000 [00:00<00:00, 1196.82it/s]

Bootstrapping f1:  48%|████▊     | 481/1000 [00:00<00:00, 1201.81it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1203.84it/s]

Bootstrapping f1:  72%|███████▏  | 723/1000 [00:00<00:00, 1191.17it/s]

Bootstrapping f1:  84%|████████▍ | 843/1000 [00:00<00:00, 1188.94it/s]

Bootstrapping f1:  96%|█████████▌| 962/1000 [00:00<00:00, 1165.37it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1181.17it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 347/1000 [00:00<00:00, 3466.85it/s]

Bootstrapping accuracy:  69%|██████▉   | 694/1000 [00:00<00:00, 3403.79it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3417.92it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1351.91it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1322.40it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1307.30it/s]

Bootstrapping average_precision:  54%|█████▎    | 536/1000 [00:00<00:00, 1304.14it/s]

Bootstrapping average_precision:  67%|██████▋   | 671/1000 [00:00<00:00, 1319.30it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 1316.76it/s]

Bootstrapping average_precision:  94%|█████████▎| 935/1000 [00:00<00:00, 1314.41it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1307.38it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 80/1000 [00:00<00:01, 790.20it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 805.33it/s]

Bootstrapping roc_auc:  25%|██▍       | 248/1000 [00:00<00:00, 827.64it/s]

Bootstrapping roc_auc:  33%|███▎      | 334/1000 [00:00<00:00, 837.77it/s]

Bootstrapping roc_auc:  42%|████▏     | 420/1000 [00:00<00:00, 844.59it/s]

Bootstrapping roc_auc:  51%|█████     | 507/1000 [00:00<00:00, 851.99it/s]

Bootstrapping roc_auc:  59%|█████▉    | 593/1000 [00:00<00:00, 853.05it/s]

Bootstrapping roc_auc:  68%|██████▊   | 679/1000 [00:00<00:00, 835.83it/s]

Bootstrapping roc_auc:  76%|███████▋  | 763/1000 [00:00<00:00, 831.53it/s]

Bootstrapping roc_auc:  85%|████████▍ | 847/1000 [00:01<00:00, 827.34it/s]

Bootstrapping roc_auc:  93%|█████████▎| 930/1000 [00:01<00:00, 825.36it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 830.83it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1137.53it/s]

Bootstrapping precision:  23%|██▎       | 229/1000 [00:00<00:00, 1141.09it/s]

Bootstrapping precision:  34%|███▍      | 344/1000 [00:00<00:00, 1123.41it/s]

Bootstrapping precision:  46%|████▌     | 457/1000 [00:00<00:00, 1122.59it/s]

Bootstrapping precision:  57%|█████▋    | 570/1000 [00:00<00:00, 1119.08it/s]

Bootstrapping precision:  68%|██████▊   | 684/1000 [00:00<00:00, 1125.19it/s]

Bootstrapping precision:  80%|████████  | 802/1000 [00:00<00:00, 1140.68it/s]

Bootstrapping precision:  92%|█████████▏| 917/1000 [00:00<00:00, 1136.07it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1130.93it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 114/1000 [00:00<00:00, 1138.05it/s]

Bootstrapping recall:  23%|██▎       | 229/1000 [00:00<00:00, 1140.62it/s]

Bootstrapping recall:  34%|███▍      | 345/1000 [00:00<00:00, 1144.42it/s]

Bootstrapping recall:  46%|████▌     | 460/1000 [00:00<00:00, 1143.31it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1128.45it/s]

Bootstrapping recall:  69%|██████▉   | 690/1000 [00:00<00:00, 1135.14it/s]

Bootstrapping recall:  81%|████████  | 807/1000 [00:00<00:00, 1145.08it/s]

Bootstrapping recall:  92%|█████████▏| 923/1000 [00:00<00:00, 1148.00it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1141.00it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1193.27it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1205.03it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1201.05it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1192.55it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1171.03it/s]

Bootstrapping f1:  72%|███████▏  | 722/1000 [00:00<00:00, 1166.07it/s]

Bootstrapping f1:  84%|████████▍ | 839/1000 [00:00<00:00, 1152.09it/s]

Bootstrapping f1:  96%|█████████▌| 955/1000 [00:00<00:00, 1151.60it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1166.43it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 341/1000 [00:00<00:00, 3404.28it/s]

Bootstrapping accuracy:  68%|██████▊   | 683/1000 [00:00<00:00, 3408.67it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3452.07it/s]

Processing Simplified Golem $\cap$ Simplified PCMB — 6 nodes, 5 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1333.85it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1315.90it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1303.12it/s]

Bootstrapping average_precision:  53%|█████▎    | 531/1000 [00:00<00:00, 1302.16it/s]

Bootstrapping average_precision:  66%|██████▌   | 662/1000 [00:00<00:00, 1304.79it/s]

Bootstrapping average_precision:  80%|███████▉  | 795/1000 [00:00<00:00, 1311.77it/s]

Bootstrapping average_precision:  93%|█████████▎| 928/1000 [00:00<00:00, 1317.26it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1312.70it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 866.98it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 872.04it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 872.61it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 873.88it/s]

Bootstrapping roc_auc:  44%|████▍     | 439/1000 [00:00<00:00, 872.33it/s]

Bootstrapping roc_auc:  53%|█████▎    | 527/1000 [00:00<00:00, 860.89it/s]

Bootstrapping roc_auc:  61%|██████▏   | 614/1000 [00:00<00:00, 848.57it/s]

Bootstrapping roc_auc:  70%|██████▉   | 699/1000 [00:00<00:00, 847.06it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 844.10it/s]

Bootstrapping roc_auc:  87%|████████▋ | 869/1000 [00:01<00:00, 839.17it/s]

Bootstrapping roc_auc:  95%|█████████▌| 953/1000 [00:01<00:00, 837.01it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 842.81it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1141.21it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1138.45it/s]

Bootstrapping precision:  34%|███▍      | 345/1000 [00:00<00:00, 1138.48it/s]

Bootstrapping precision:  46%|████▌     | 461/1000 [00:00<00:00, 1142.51it/s]

Bootstrapping precision:  58%|█████▊    | 577/1000 [00:00<00:00, 1146.63it/s]

Bootstrapping precision:  70%|██████▉   | 695/1000 [00:00<00:00, 1155.08it/s]

Bootstrapping precision:  81%|████████  | 811/1000 [00:00<00:00, 1154.75it/s]

Bootstrapping precision:  93%|█████████▎| 929/1000 [00:00<00:00, 1159.86it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1148.21it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 112/1000 [00:00<00:00, 1119.37it/s]

Bootstrapping recall:  23%|██▎       | 230/1000 [00:00<00:00, 1149.76it/s]

Bootstrapping recall:  35%|███▌      | 352/1000 [00:00<00:00, 1178.81it/s]

Bootstrapping recall:  47%|████▋     | 472/1000 [00:00<00:00, 1186.21it/s]

Bootstrapping recall:  59%|█████▉    | 591/1000 [00:00<00:00, 1168.71it/s]

Bootstrapping recall:  71%|███████   | 708/1000 [00:00<00:00, 1154.29it/s]

Bootstrapping recall:  82%|████████▏ | 824/1000 [00:00<00:00, 1153.18it/s]

Bootstrapping recall:  94%|█████████▍| 940/1000 [00:00<00:00, 1148.09it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1156.38it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 114/1000 [00:00<00:00, 1139.14it/s]

Bootstrapping f1:  23%|██▎       | 228/1000 [00:00<00:00, 1134.89it/s]

Bootstrapping f1:  35%|███▍      | 346/1000 [00:00<00:00, 1155.11it/s]

Bootstrapping f1:  46%|████▌     | 462/1000 [00:00<00:00, 1155.97it/s]

Bootstrapping f1:  58%|█████▊    | 583/1000 [00:00<00:00, 1175.03it/s]

Bootstrapping f1:  70%|███████   | 703/1000 [00:00<00:00, 1183.39it/s]

Bootstrapping f1:  82%|████████▏ | 824/1000 [00:00<00:00, 1190.18it/s]

Bootstrapping f1:  94%|█████████▍| 945/1000 [00:00<00:00, 1196.40it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1179.87it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3528.62it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3442.13it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3430.78it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1339.68it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1351.56it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 1353.18it/s]

Bootstrapping average_precision:  54%|█████▍    | 542/1000 [00:00<00:00, 1324.58it/s]

Bootstrapping average_precision:  68%|██████▊   | 675/1000 [00:00<00:00, 1312.92it/s]

Bootstrapping average_precision:  81%|████████  | 807/1000 [00:00<00:00, 1303.07it/s]

Bootstrapping average_precision:  94%|█████████▍| 942/1000 [00:00<00:00, 1316.07it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1319.80it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 821.28it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 818.09it/s]

Bootstrapping roc_auc:  25%|██▍       | 248/1000 [00:00<00:00, 817.84it/s]

Bootstrapping roc_auc:  33%|███▎      | 330/1000 [00:00<00:00, 816.99it/s]

Bootstrapping roc_auc:  41%|████▏     | 413/1000 [00:00<00:00, 818.25it/s]

Bootstrapping roc_auc:  50%|████▉     | 496/1000 [00:00<00:00, 819.12it/s]

Bootstrapping roc_auc:  58%|█████▊    | 580/1000 [00:00<00:00, 822.34it/s]

Bootstrapping roc_auc:  66%|██████▋   | 663/1000 [00:00<00:00, 820.65it/s]

Bootstrapping roc_auc:  75%|███████▍  | 746/1000 [00:00<00:00, 820.49it/s]

Bootstrapping roc_auc:  83%|████████▎ | 829/1000 [00:01<00:00, 819.84it/s]

Bootstrapping roc_auc:  91%|█████████ | 912/1000 [00:01<00:00, 821.47it/s]

Bootstrapping roc_auc: 100%|█████████▉| 997/1000 [00:01<00:00, 829.29it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 821.81it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1188.47it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1205.47it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1210.53it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1210.47it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1207.51it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1206.78it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1210.06it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1211.95it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1208.65it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1215.47it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1208.25it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1179.07it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1172.62it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1168.85it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1166.56it/s]

Bootstrapping recall:  84%|████████▎ | 835/1000 [00:00<00:00, 1162.06it/s]

Bootstrapping recall:  95%|█████████▌| 952/1000 [00:00<00:00, 1156.61it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1166.44it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1194.98it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1209.10it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1213.77it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1204.73it/s]

Bootstrapping f1:  61%|██████    | 607/1000 [00:00<00:00, 1195.79it/s]

Bootstrapping f1:  73%|███████▎  | 727/1000 [00:00<00:00, 1177.93it/s]

Bootstrapping f1:  84%|████████▍ | 845/1000 [00:00<00:00, 1174.33it/s]

Bootstrapping f1:  96%|█████████▋| 964/1000 [00:00<00:00, 1178.67it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1187.22it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3530.68it/s]

Bootstrapping accuracy:  71%|███████   | 709/1000 [00:00<00:00, 3539.29it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3548.93it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem — 5 nodes, 4 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1360.79it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1366.06it/s]

Bootstrapping average_precision:  41%|████▏     | 413/1000 [00:00<00:00, 1372.43it/s]

Bootstrapping average_precision:  55%|█████▌    | 551/1000 [00:00<00:00, 1374.10it/s]

Bootstrapping average_precision:  69%|██████▉   | 690/1000 [00:00<00:00, 1376.89it/s]

Bootstrapping average_precision:  83%|████████▎ | 828/1000 [00:00<00:00, 1374.73it/s]

Bootstrapping average_precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1376.98it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1373.59it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 864.08it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 869.55it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 872.88it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 873.43it/s]

Bootstrapping roc_auc:  44%|████▍     | 439/1000 [00:00<00:00, 874.41it/s]

Bootstrapping roc_auc:  53%|█████▎    | 527/1000 [00:00<00:00, 871.95it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 869.51it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 870.45it/s]

Bootstrapping roc_auc:  79%|███████▉  | 791/1000 [00:00<00:00, 868.92it/s]

Bootstrapping roc_auc:  88%|████████▊ | 878/1000 [00:01<00:00, 863.09it/s]

Bootstrapping roc_auc:  96%|█████████▋| 965/1000 [00:01<00:00, 858.66it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 865.45it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1192.42it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1182.15it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1185.03it/s]

Bootstrapping precision:  48%|████▊     | 480/1000 [00:00<00:00, 1193.94it/s]

Bootstrapping precision:  60%|██████    | 602/1000 [00:00<00:00, 1200.68it/s]

Bootstrapping precision:  72%|███████▏  | 724/1000 [00:00<00:00, 1205.58it/s]

Bootstrapping precision:  84%|████████▍ | 845/1000 [00:00<00:00, 1206.91it/s]

Bootstrapping precision:  97%|█████████▋| 966/1000 [00:00<00:00, 1206.17it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1200.23it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1211.45it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1211.33it/s]

Bootstrapping recall:  37%|███▋      | 367/1000 [00:00<00:00, 1215.15it/s]

Bootstrapping recall:  49%|████▉     | 489/1000 [00:00<00:00, 1212.29it/s]

Bootstrapping recall:  61%|██████    | 611/1000 [00:00<00:00, 1209.22it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1208.44it/s]

Bootstrapping recall:  85%|████████▌ | 853/1000 [00:00<00:00, 1207.89it/s]

Bootstrapping recall:  98%|█████████▊| 975/1000 [00:00<00:00, 1208.58it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1208.72it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1208.28it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1211.44it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1212.95it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1212.92it/s]

Bootstrapping f1:  61%|██████    | 609/1000 [00:00<00:00, 1211.59it/s]

Bootstrapping f1:  73%|███████▎  | 731/1000 [00:00<00:00, 1208.92it/s]

Bootstrapping f1:  85%|████████▌ | 853/1000 [00:00<00:00, 1209.81it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1213.32it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1211.35it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3492.36it/s]

Bootstrapping accuracy:  70%|███████   | 705/1000 [00:00<00:00, 3523.98it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3521.48it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 130/1000 [00:00<00:00, 1292.22it/s]

Bootstrapping average_precision:  26%|██▋       | 264/1000 [00:00<00:00, 1319.93it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1337.26it/s]

Bootstrapping average_precision:  54%|█████▍    | 538/1000 [00:00<00:00, 1350.47it/s]

Bootstrapping average_precision:  67%|██████▋   | 674/1000 [00:00<00:00, 1352.64it/s]

Bootstrapping average_precision:  81%|████████  | 810/1000 [00:00<00:00, 1352.97it/s]

Bootstrapping average_precision:  95%|█████████▍| 947/1000 [00:00<00:00, 1357.11it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1348.28it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 850.66it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 844.13it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 849.42it/s]

Bootstrapping roc_auc:  34%|███▍      | 343/1000 [00:00<00:00, 848.93it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 856.75it/s]

Bootstrapping roc_auc:  52%|█████▏    | 518/1000 [00:00<00:00, 859.89it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 860.14it/s]

Bootstrapping roc_auc:  69%|██████▉   | 692/1000 [00:00<00:00, 858.56it/s]

Bootstrapping roc_auc:  78%|███████▊  | 778/1000 [00:00<00:00, 855.29it/s]

Bootstrapping roc_auc:  86%|████████▋ | 865/1000 [00:01<00:00, 857.08it/s]

Bootstrapping roc_auc:  95%|█████████▌| 952/1000 [00:01<00:00, 859.30it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 856.49it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1187.53it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1166.71it/s]

Bootstrapping precision:  36%|███▌      | 358/1000 [00:00<00:00, 1177.69it/s]

Bootstrapping precision:  48%|████▊     | 479/1000 [00:00<00:00, 1188.81it/s]

Bootstrapping precision:  60%|██████    | 602/1000 [00:00<00:00, 1200.26it/s]

Bootstrapping precision:  72%|███████▏  | 724/1000 [00:00<00:00, 1205.89it/s]

Bootstrapping precision:  84%|████████▍ | 845/1000 [00:00<00:00, 1203.11it/s]

Bootstrapping precision:  97%|█████████▋| 966/1000 [00:00<00:00, 1204.66it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.17it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1205.44it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1212.54it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1215.25it/s]

Bootstrapping recall:  49%|████▊     | 487/1000 [00:00<00:00, 1215.51it/s]

Bootstrapping recall:  61%|██████    | 609/1000 [00:00<00:00, 1213.43it/s]

Bootstrapping recall:  73%|███████▎  | 731/1000 [00:00<00:00, 1213.55it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1216.34it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1218.18it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1214.71it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1212.51it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1211.59it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1210.12it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1212.76it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1211.84it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1212.11it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1210.53it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1210.47it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1210.10it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3532.61it/s]

Bootstrapping accuracy:  71%|███████   | 710/1000 [00:00<00:00, 3547.37it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3548.17it/s]

In [8]:
df1 = pd.DataFrame(results1)
df1.to_csv('Generative LGBN - Biomarker Selection.csv', index=False)
df1

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,Generative LGBN,Control,"0.48 (0.44, 0.52)","0.84 (0.82, 0.86)","0.77 (0.74, 0.79)","0.78 (0.75, 0.80)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.116,811,45
1,XGB,Control,"0.81 (0.78, 0.84)","0.93 (0.91, 0.95)","0.94 (0.92, 0.95)","0.80 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.089,811,45
2,Generative LGBN,Correlation,"0.51 (0.47, 0.56)","0.80 (0.78, 0.83)","0.81 (0.78, 0.83)","0.74 (0.72, 0.77)","0.77 (0.75, 0.79)","0.92 (0.91, 0.93)",0.085,113,37
3,XGB,Correlation,"0.75 (0.71, 0.78)","0.90 (0.88, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.108,113,37
4,Generative LGBN,Clinician Consensus $\cup$ Golem,"0.53 (0.49, 0.58)","0.84 (0.82, 0.86)","0.77 (0.75, 0.79)","0.77 (0.74, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.108,212,22
5,XGB,Clinician Consensus $\cup$ Golem,"0.79 (0.75, 0.82)","0.92 (0.90, 0.93)","0.91 (0.89, 0.93)","0.80 (0.78, 0.82)","0.85 (0.83, 0.87)","0.95 (0.94, 0.95)",0.096,212,22
6,Generative LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.53 (0.49, 0.58)","0.87 (0.85, 0.89)","0.79 (0.77, 0.81)","0.79 (0.76, 0.81)","0.79 (0.77, 0.81)","0.92 (0.91, 0.93)",0.110,315,18
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.79 (0.75, 0.82)","0.91 (0.89, 0.93)","0.92 (0.90, 0.93)","0.80 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.094,315,18
8,Generative LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.51 (0.46, 0.55)","0.84 (0.82, 0.87)","0.77 (0.75, 0.80)","0.77 (0.75, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.109,389,22
9,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.92 (0.90, 0.94)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.092,389,22
10,Generative LGBN,Clinician Consensus $\cup$ PCMB,"0.52 (0.47, 0.56)","0.84 (0.82, 0.87)","0.77 (0.75, 0.80)","0.78 (0.75, 0.80)","0.77 (0.75, 0.80)","0.91 (0.90, 0.92)",0.112,209,18
11,XGB,Clinician Consensus $\cup$ PCMB,"0.76 (0.73, 0.80)","0.90 (0.88, 0.92)","0.92 (0.90, 0.93)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.094,209,18
12,Generative LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.51 (0.47, 0.56)","0.86 (0.83, 0.88)","0.77 (0.75, 0.79)","0.78 (0.76, 0.80)","0.78 (0.76, 0.80)","0.91 (0.90, 0.92)",0.115,407,23
13,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.78 (0.75, 0.81)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.94 (0.94, 0.95)",0.093,407,23
14,Generative LGBN,Clinician Consensus,"0.52 (0.48, 0.57)","0.84 (0.82, 0.86)","0.77 (0.75, 0.80)","0.77 (0.75, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.109,203,15
15,XGB,Clinician Consensus,"0.77 (0.74, 0.80)","0.90 (0.88, 0.92)","0.92 (0.91, 0.94)","0.80 (0.77, 0.82)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.096,203,15
16,Generative LGBN,Simplified Clinician Consensus,"0.52 (0.47, 0.57)","0.84 (0.82, 0.87)","0.78 (0.76, 0.81)","0.77 (0.75, 0.79)","0.78 (0.76, 0.80)","0.91 (0.90, 0.92)",0.106,259,15
17,XGB,Simplified Clinician Consensus,"0.77 (0.74, 0.81)","0.91 (0.89, 0.93)","0.92 (0.90, 0.94)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.095,259,15
18,Generative LGBN,Clinician Consensus $\cap$ PCMB,"0.59 (0.55, 0.64)","0.82 (0.79, 0.84)","0.83 (0.80, 0.85)","0.74 (0.71, 0.76)","0.77 (0.75, 0.80)","0.92 (0.91, 0.93)",0.078,20,12
19,XGB,Clinician Consensus $\cap$ PCMB,"0.68 (0.64, 0.72)","0.85 (0.83, 0.88)","0.87 (0.85, 0.90)","0.74 (0.72, 0.77)","0.79 (0.77, 0.81)","0.93 (0.92, 0.94)",0.115,20,12
20,Generative LGBN,Golem,"0.26 (0.22, 0.30)","0.70 (0.67, 0.72)","0.63 (0.60, 0.67)","0.57 (0.55, 0.59)","0.59 (0.56, 0.61)","0.87 (0.86, 0.88)",0.061,16,11
21,XGB,Golem,"0.56 (0.51, 0.60)","0.84 (0.82, 0.86)","0.79 (0.77, 0.82)","0.70 (0.68, 0.72)","0.74 (0.71, 0.76)","0.91 (0.90, 0.92)",0.116,16,11
22,Generative LGBN,PCMB,"0.59 (0.54, 0.63)","0.84 (0.82, 0.87)","0.78 (0.75, 0.80)","0.75 (0.73, 0.77)","0.76 (0.74, 0.78)","0.91 (0.90, 0.92)",0.099,26,15
23,XGB,PCMB,"0.71 (0.67, 0.75)","0.87 (0.85, 0.89)","0.89 (0.88, 0.92)","0.77 (0.75, 0.79)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.114,26,15
24,Generative LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.50 (0.46, 0.55)","0.83 (0.81, 0.85)","0.77 (0.75, 0.80)","0.76 (0.74, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.105,240,14
25,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.79 (0.75, 0.82)","0.91 (0.89, 0.93)","0.93 (0.91, 0.94)","0.80 (0.77, 0.82)","0.85 (0.82, 0.86)","0.95 (0.94, 0.96)",0.095,240,14
26,Generative LGBN,Simplified PCMB,"0.53 (0.49, 0.58)","0.87 (0.85, 0.89)","0.78 (0.76, 0.81)","0.79 (0.76, 0.81)","0.78 (0.76, 0.81)","0.92 (0.91, 0.92)",0.111,296,17
27,XGB,Simplified PCMB,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.92 (0.91, 0.94)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.092,296,17
28,Generative LGBN,Clinician Consensus $\cap$ Golem,"0.18 (0.15, 0.21)","0.55 (0.52, 0.58)","0.63 (0.59, 0.67)","0.54 (0.52, 0.55)","0.55 (0.52, 0.57)","0.88 (0.87, 0.89)",0.189,7,4
29,XGB,Clinician Consensus $\cap$ Golem,"0.25 (0.21, 0.29)","0.65 (0.62, 0.68)","0.70 (0.65, 0.74)","0.56 (0.54, 0.57)","0.57 (0.55, 0.59)","0.89 (0.88, 0.90)",0.124,7,4
30,Generative LGBN,Simplified Golem,"0.52 (0.48, 0.57)","0.85 (0.83, 0.87)","0.76 (0.74, 0.79)","0.77 (0.75, 0.80)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.116,199,11
31,XGB,Simplified Golem,"0.77 (0.74, 0.80)","0.91 (0.89, 0.93)","0.91 (0.90, 0.93)","0.79 (0.76, 0.81)","0.83 (0.82, 0.86)","0.94 (0.94, 0.95)",0.095,199,11
32,Generative LGBN,Golem $\cup$ PCMB,"0.58 (0.54, 0.63)","0.85 (0.82, 0.87)","0.78 (0.76, 0.80)","0.76 (0.74, 0.78)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.104,42,21
33,XGB,Golem $\cup$ PCMB,"0.74 (0.71, 0.78)","0.90 (0.88, 0.92)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.108,42,21
34,Generative LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.55 (0.51, 0.60)","0.85 (0.82, 0.87)","0.78 (0.76, 0.80)","0.76 (0.74, 0.78)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.101,88,5
35,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.76 (0.73, 0.80)","0.90 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,88,5
36,Generative LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.57 (0.52, 0.61)","0.85 (0.82, 0.87)","0.78 (0.76, 0.81)","0.76 (0.74, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.102,69,4
37,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.76, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.106,69,4

In [9]:
# DeLong / permutation comparisons: Generative LGBN vs XGBoost within each DAG
aurocs1, auprcs1 = [], []
for dag_name, preds in model_preds1.items():
    p_lgbn = preds['Generative LGBN']
    p_xgb  = preds['XGB']
    (z, p_delong), perm = compare_models(y_test.Outcome, p_lgbn, p_xgb)
    aurocs1.append({'DAG': dag_name, 'Z-score': f"{z:.4f}", 'P-value': f"{p_delong:.3e}"})
    auprcs1.append({'DAG': dag_name,
                    'Avg Precision LGBN': f"{perm[0]:.4f}",
                    'Avg Precision XGB':  f"{perm[1]:.4f}",
                    'P-value': f"{perm[2]:.3e}"})

aurocs1_df = pd.DataFrame(aurocs1)
auprcs1_df = pd.DataFrame(auprcs1)
aurocs1_df.to_csv('Generative LGBN - delong_biomarker_selection_auroc.csv', index=False)
auprcs1_df.to_csv('Generative LGBN - delong_biomarker_selection_auprc.csv', index=False)
aurocs1_df

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 698.72it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 710.79it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 718.17it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:00, 721.77it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 362/1000 [00:00<00:00, 726.32it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 435/1000 [00:00<00:00, 727.54it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 508/1000 [00:00<00:00, 724.55it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 581/1000 [00:00<00:00, 723.70it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 654/1000 [00:00<00:00, 725.20it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 728/1000 [00:01<00:00, 727.26it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 801/1000 [00:01<00:00, 722.41it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 874/1000 [00:01<00:00, 723.44it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 947/1000 [00:01<00:00, 724.27it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 723.34it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 721.39it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 721.38it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 723.34it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 293/1000 [00:00<00:00, 725.95it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 366/1000 [00:00<00:00, 725.53it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 439/1000 [00:00<00:00, 718.86it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 722.64it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 587/1000 [00:00<00:00, 725.85it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 660/1000 [00:00<00:00, 726.31it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 733/1000 [00:01<00:00, 723.96it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 806/1000 [00:01<00:00, 724.34it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 879/1000 [00:01<00:00, 724.31it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 953/1000 [00:01<00:00, 726.23it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 724.74it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 731.28it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 731.36it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 733.37it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 731.68it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 370/1000 [00:00<00:00, 725.25it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 444/1000 [00:00<00:00, 726.98it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 517/1000 [00:00<00:00, 721.54it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 590/1000 [00:00<00:00, 720.53it/s]

Computing average_precision Permutation Test p-value:  66%|██████▋   | 663/1000 [00:00<00:00, 720.63it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 736/1000 [00:01<00:00, 714.63it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 808/1000 [00:01<00:00, 707.34it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 879/1000 [00:01<00:00, 706.94it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 950/1000 [00:01<00:00, 705.56it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 715.97it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 718.29it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 711.97it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 721.69it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 726.28it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 726.41it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 727.51it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 512/1000 [00:00<00:00, 729.25it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 586/1000 [00:00<00:00, 729.60it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 660/1000 [00:00<00:00, 731.90it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 734/1000 [00:01<00:00, 732.81it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 808/1000 [00:01<00:00, 732.99it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 882/1000 [00:01<00:00, 734.19it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 956/1000 [00:01<00:00, 734.80it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 730.06it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 727.58it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 719.56it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 708.21it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 290/1000 [00:00<00:00, 710.95it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 363/1000 [00:00<00:00, 713.79it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 435/1000 [00:00<00:00, 714.73it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 507/1000 [00:00<00:00, 714.33it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 579/1000 [00:00<00:00, 712.80it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 651/1000 [00:00<00:00, 712.10it/s]

Computing average_precision Permutation Test p-value:  72%|███████▎  | 725/1000 [00:01<00:00, 717.60it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 797/1000 [00:01<00:00, 714.85it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 869/1000 [00:01<00:00, 712.21it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 942/1000 [00:01<00:00, 715.58it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 714.79it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 725.80it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 725.88it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 721.87it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 293/1000 [00:00<00:00, 725.66it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 367/1000 [00:00<00:00, 729.51it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 441/1000 [00:00<00:00, 732.72it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 515/1000 [00:00<00:00, 734.75it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 589/1000 [00:00<00:00, 734.87it/s]

Computing average_precision Permutation Test p-value:  66%|██████▋   | 663/1000 [00:00<00:00, 733.45it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 737/1000 [00:01<00:00, 734.21it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 811/1000 [00:01<00:00, 735.61it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 885/1000 [00:01<00:00, 735.87it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 960/1000 [00:01<00:00, 737.32it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 733.18it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 735.24it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 737.02it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 737.42it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 736.54it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 370/1000 [00:00<00:00, 735.99it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 444/1000 [00:00<00:00, 736.94it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 518/1000 [00:00<00:00, 736.87it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 592/1000 [00:00<00:00, 736.94it/s]

Computing average_precision Permutation Test p-value:  67%|██████▋   | 666/1000 [00:00<00:00, 736.94it/s]

Computing average_precision Permutation Test p-value:  74%|███████▍  | 740/1000 [00:01<00:00, 735.79it/s]

Computing average_precision Permutation Test p-value:  81%|████████▏ | 814/1000 [00:01<00:00, 735.96it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 888/1000 [00:01<00:00, 736.33it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▋| 963/1000 [00:01<00:00, 737.80it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 736.66it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 733.48it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 731.46it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 731.53it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 722.15it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 369/1000 [00:00<00:00, 724.30it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 443/1000 [00:00<00:00, 727.49it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 516/1000 [00:00<00:00, 722.74it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 589/1000 [00:00<00:00, 724.63it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 662/1000 [00:00<00:00, 718.54it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 734/1000 [00:01<00:00, 716.33it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 807/1000 [00:01<00:00, 718.70it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 879/1000 [00:01<00:00, 717.64it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 951/1000 [00:01<00:00, 712.19it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 719.72it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 689.14it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 685.34it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 208/1000 [00:00<00:01, 687.84it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 279/1000 [00:00<00:01, 694.55it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 696.29it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 420/1000 [00:00<00:00, 695.09it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 491/1000 [00:00<00:00, 699.80it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 564/1000 [00:00<00:00, 709.05it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 635/1000 [00:00<00:00, 701.60it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 706/1000 [00:01<00:00, 694.67it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 777/1000 [00:01<00:00, 697.21it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 849/1000 [00:01<00:00, 700.95it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 920/1000 [00:01<00:00, 698.97it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 992/1000 [00:01<00:00, 704.57it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 698.92it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 707.67it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 703.54it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 704.60it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 713.93it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 359/1000 [00:00<00:00, 717.48it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 431/1000 [00:00<00:00, 713.52it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 503/1000 [00:00<00:00, 711.89it/s]

Computing average_precision Permutation Test p-value:  57%|█████▊    | 575/1000 [00:00<00:00, 713.52it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 647/1000 [00:00<00:00, 712.88it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 721/1000 [00:01<00:00, 718.19it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 793/1000 [00:01<00:00, 712.75it/s]

Computing average_precision Permutation Test p-value:  86%|████████▋ | 865/1000 [00:01<00:00, 705.21it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▎| 936/1000 [00:01<00:00, 702.75it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 706.29it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 676.24it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 137/1000 [00:00<00:01, 679.44it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 208/1000 [00:00<00:01, 690.75it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 701.50it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 351/1000 [00:00<00:00, 703.66it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 708.58it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 495/1000 [00:00<00:00, 709.06it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 566/1000 [00:00<00:00, 708.02it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 637/1000 [00:00<00:00, 707.48it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 709/1000 [00:01<00:00, 708.79it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 781/1000 [00:01<00:00, 710.14it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 853/1000 [00:01<00:00, 711.48it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 926/1000 [00:01<00:00, 714.22it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 998/1000 [00:01<00:00, 715.80it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 707.23it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 723.55it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 720.70it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 719.94it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 721.39it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 366/1000 [00:00<00:00, 724.47it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 439/1000 [00:00<00:00, 724.66it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 727.15it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 587/1000 [00:00<00:00, 728.86it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 660/1000 [00:00<00:00, 722.62it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 733/1000 [00:01<00:00, 717.44it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 805/1000 [00:01<00:00, 714.62it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 877/1000 [00:01<00:00, 708.70it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 948/1000 [00:01<00:00, 704.82it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 715.68it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 695.11it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 141/1000 [00:00<00:01, 701.91it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 701.61it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 712.97it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 359/1000 [00:00<00:00, 716.33it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 431/1000 [00:00<00:00, 692.65it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 501/1000 [00:00<00:00, 686.45it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 688.35it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 643/1000 [00:00<00:00, 694.36it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 714/1000 [00:01<00:00, 696.65it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 785/1000 [00:01<00:00, 699.78it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 857/1000 [00:01<00:00, 704.43it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 929/1000 [00:01<00:00, 706.78it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 702.25it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 676.34it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 648.25it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 203/1000 [00:00<00:01, 654.84it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 269/1000 [00:00<00:01, 656.47it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 338/1000 [00:00<00:00, 668.35it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 410/1000 [00:00<00:00, 683.02it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 482/1000 [00:00<00:00, 691.67it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 555/1000 [00:00<00:00, 701.47it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 629/1000 [00:00<00:00, 712.48it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 701/1000 [00:01<00:00, 704.66it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 772/1000 [00:01<00:00, 697.76it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 842/1000 [00:01<00:00, 696.25it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 912/1000 [00:01<00:00, 661.09it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 979/1000 [00:01<00:00, 653.98it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 676.00it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   6%|▌         | 62/1000 [00:00<00:01, 619.89it/s]

Computing average_precision Permutation Test p-value:  13%|█▎        | 128/1000 [00:00<00:01, 642.04it/s]

Computing average_precision Permutation Test p-value:  20%|█▉        | 196/1000 [00:00<00:01, 654.86it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 266/1000 [00:00<00:01, 669.34it/s]

Computing average_precision Permutation Test p-value:  34%|███▎      | 337/1000 [00:00<00:00, 681.70it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 407/1000 [00:00<00:00, 684.86it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 476/1000 [00:00<00:00, 668.23it/s]

Computing average_precision Permutation Test p-value:  54%|█████▍    | 543/1000 [00:00<00:00, 649.91it/s]

Computing average_precision Permutation Test p-value:  61%|██████    | 609/1000 [00:00<00:00, 639.06it/s]

Computing average_precision Permutation Test p-value:  67%|██████▋   | 674/1000 [00:01<00:00, 640.21it/s]

Computing average_precision Permutation Test p-value:  74%|███████▍  | 739/1000 [00:01<00:00, 642.21it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 805/1000 [00:01<00:00, 646.16it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 872/1000 [00:01<00:00, 652.25it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 941/1000 [00:01<00:00, 661.96it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 658.22it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 703.60it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 709.09it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 697.04it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 695.08it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 687.56it/s]

Computing average_precision Permutation Test p-value:  42%|████▎     | 425/1000 [00:00<00:00, 694.74it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 498/1000 [00:00<00:00, 705.97it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 570/1000 [00:00<00:00, 710.32it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 642/1000 [00:00<00:00, 706.12it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 715/1000 [00:01<00:00, 712.94it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 788/1000 [00:01<00:00, 715.77it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 860/1000 [00:01<00:00, 716.97it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 932/1000 [00:01<00:00, 714.79it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 709.19it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 730.23it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 729.17it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 730.11it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 731.12it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 370/1000 [00:00<00:00, 730.47it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 444/1000 [00:00<00:00, 728.54it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 517/1000 [00:00<00:00, 728.82it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 591/1000 [00:00<00:00, 729.47it/s]

Computing average_precision Permutation Test p-value:  66%|██████▋   | 664/1000 [00:00<00:00, 728.27it/s]

Computing average_precision Permutation Test p-value:  74%|███████▍  | 738/1000 [00:01<00:00, 729.50it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 812/1000 [00:01<00:00, 729.60it/s]

Computing average_precision Permutation Test p-value:  89%|████████▊ | 886/1000 [00:01<00:00, 730.67it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 960/1000 [00:01<00:00, 731.05it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 729.43it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 717.62it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 145/1000 [00:00<00:01, 720.80it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 725.56it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 293/1000 [00:00<00:00, 728.42it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 366/1000 [00:00<00:00, 727.09it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 728.27it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 727.52it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 587/1000 [00:00<00:00, 728.95it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 661/1000 [00:00<00:00, 729.50it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 735/1000 [00:01<00:00, 730.93it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 809/1000 [00:01<00:00, 730.25it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 883/1000 [00:01<00:00, 722.88it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 956/1000 [00:01<00:00, 712.52it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 721.50it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 704.95it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 702.92it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 698.18it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 688.00it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 693.58it/s]

Computing average_precision Permutation Test p-value:  42%|████▎     | 425/1000 [00:00<00:00, 697.81it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 495/1000 [00:00<00:00, 697.85it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 568/1000 [00:00<00:00, 706.40it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 640/1000 [00:00<00:00, 708.66it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 712/1000 [00:01<00:00, 709.57it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 783/1000 [00:01<00:00, 707.31it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 855/1000 [00:01<00:00, 708.90it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 926/1000 [00:01<00:00, 709.17it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 999/1000 [00:01<00:00, 713.49it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 705.09it/s]

                                                  DAG Z-score    P-value
0                                             Control  8.8821  6.562e-19
1                                         Correlation  7.7685  7.941e-15
2                    Clinician Consensus $\cup$ Golem  7.2008  5.985e-13
3   Simplified Clinician Consensus $\cup$ Simplifi...  4.5700  4.878e-06
4   Simplified Clinician Consensus $\cup$ Simplifi...  6.1230  9.184e-10
5                     Clinician Consensus $\cup$ PCMB  5.4507  5.017e-08
6             Simplified Golem $\cup$ Simplified PCMB  5.3593  8.352e-08
7                                 Clinician Consensus  5.7698  7.939e-09
8                      Simplified Clinician Consensus  6.1615  7.205e-10
9                     Clinician Consensus $\cap$ PCMB  2.8826  3.944e-03
10                                              Golem  9.4665  2.893e-21
11                                               PCMB  2.6557  7.914e-03
12  Simplified Clinician Consensus $\cap$ Simplifi...  6.8042  1.016e-11
13                                    Simplified PCMB  4.2337  2.299e-05
14                   Clinician Consensus $\cap$ Golem  5.0653  4.077e-07
15                                   Simplified Golem  6.0062  1.899e-09
16                                  Golem $\cup$ PCMB  5.2149  1.839e-07
17            Simplified Golem $\cap$ Simplified PCMB  5.5593  2.709e-08
18  Simplified Clinician Consensus $\cap$ Simplifi...  3.7647  1.667e-04

## Experiment 2: No drugs

In [10]:
results2, calibrations2, model_preds2 = train_models(remove_drugs=True, remove_interventions=False)

Processing Control — 46 nodes, 45 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1332.51it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1324.46it/s]

Bootstrapping average_precision:  40%|████      | 403/1000 [00:00<00:00, 1335.00it/s]

Bootstrapping average_precision:  54%|█████▎    | 537/1000 [00:00<00:00, 1278.84it/s]

Bootstrapping average_precision:  67%|██████▋   | 666/1000 [00:00<00:00, 1268.83it/s]

Bootstrapping average_precision:  80%|███████▉  | 798/1000 [00:00<00:00, 1282.03it/s]

Bootstrapping average_precision:  93%|█████████▎| 927/1000 [00:00<00:00, 1262.79it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1267.43it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 79/1000 [00:00<00:01, 786.07it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 806.79it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 804.92it/s]

Bootstrapping roc_auc:  33%|███▎      | 326/1000 [00:00<00:00, 812.69it/s]

Bootstrapping roc_auc:  41%|████      | 412/1000 [00:00<00:00, 827.14it/s]

Bootstrapping roc_auc:  50%|████▉     | 495/1000 [00:00<00:00, 823.12it/s]

Bootstrapping roc_auc:  58%|█████▊    | 578/1000 [00:00<00:00, 806.13it/s]

Bootstrapping roc_auc:  66%|██████▌   | 661/1000 [00:00<00:00, 812.74it/s]

Bootstrapping roc_auc:  75%|███████▍  | 748/1000 [00:00<00:00, 827.58it/s]

Bootstrapping roc_auc:  84%|████████▎ | 836/1000 [00:01<00:00, 841.10it/s]

Bootstrapping roc_auc:  92%|█████████▏| 921/1000 [00:01<00:00, 841.05it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 825.69it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 112/1000 [00:00<00:00, 1117.42it/s]

Bootstrapping precision:  22%|██▏       | 224/1000 [00:00<00:00, 1114.39it/s]

Bootstrapping precision:  34%|███▍      | 339/1000 [00:00<00:00, 1128.65it/s]

Bootstrapping precision:  46%|████▌     | 458/1000 [00:00<00:00, 1149.03it/s]

Bootstrapping precision:  57%|█████▊    | 575/1000 [00:00<00:00, 1154.72it/s]

Bootstrapping precision:  69%|██████▉   | 691/1000 [00:00<00:00, 1135.73it/s]

Bootstrapping precision:  80%|████████  | 805/1000 [00:00<00:00, 1130.43it/s]

Bootstrapping precision:  92%|█████████▏| 919/1000 [00:00<00:00, 1132.69it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1132.94it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 114/1000 [00:00<00:00, 1134.29it/s]

Bootstrapping recall:  23%|██▎       | 230/1000 [00:00<00:00, 1144.68it/s]

Bootstrapping recall:  35%|███▌      | 351/1000 [00:00<00:00, 1173.40it/s]

Bootstrapping recall:  47%|████▋     | 470/1000 [00:00<00:00, 1178.20it/s]

Bootstrapping recall:  59%|█████▉    | 588/1000 [00:00<00:00, 1169.33it/s]

Bootstrapping recall:  71%|███████   | 706/1000 [00:00<00:00, 1172.15it/s]

Bootstrapping recall:  82%|████████▎ | 825/1000 [00:00<00:00, 1176.47it/s]

Bootstrapping recall:  94%|█████████▍| 943/1000 [00:00<00:00, 1176.17it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1169.59it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 112/1000 [00:00<00:00, 1111.93it/s]

Bootstrapping f1:  22%|██▏       | 224/1000 [00:00<00:00, 905.48it/s]

Bootstrapping f1:  33%|███▎      | 327/1000 [00:00<00:00, 953.33it/s]

Bootstrapping f1:  43%|████▎     | 434/1000 [00:00<00:00, 995.68it/s]

Bootstrapping f1:  55%|█████▍    | 545/1000 [00:00<00:00, 1034.49it/s]

Bootstrapping f1:  66%|██████▌   | 656/1000 [00:00<00:00, 1058.58it/s]

Bootstrapping f1:  77%|███████▋  | 766/1000 [00:00<00:00, 1071.50it/s]

Bootstrapping f1:  87%|████████▋ | 874/1000 [00:00<00:00, 1072.93it/s]

Bootstrapping f1:  98%|█████████▊| 982/1000 [00:00<00:00, 1027.19it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1026.14it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  31%|███       | 312/1000 [00:00<00:00, 3111.07it/s]

Bootstrapping accuracy:  63%|██████▎   | 628/1000 [00:00<00:00, 3135.82it/s]

Bootstrapping accuracy:  95%|█████████▌| 952/1000 [00:00<00:00, 3179.67it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3154.27it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1332.67it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1343.46it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1334.50it/s]

Bootstrapping average_precision:  54%|█████▍    | 541/1000 [00:00<00:00, 1344.07it/s]

Bootstrapping average_precision:  68%|██████▊   | 678/1000 [00:00<00:00, 1352.88it/s]

Bootstrapping average_precision:  82%|████████▏ | 815/1000 [00:00<00:00, 1357.83it/s]

Bootstrapping average_precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1359.77it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1352.21it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 838.98it/s]

Bootstrapping roc_auc:  17%|█▋        | 171/1000 [00:00<00:00, 852.36it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 857.89it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 862.10it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 857.24it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 858.32it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 846.70it/s]

Bootstrapping roc_auc:  69%|██████▉   | 690/1000 [00:00<00:00, 840.68it/s]

Bootstrapping roc_auc:  78%|███████▊  | 776/1000 [00:00<00:00, 843.80it/s]

Bootstrapping roc_auc:  86%|████████▌ | 861/1000 [00:01<00:00, 798.86it/s]

Bootstrapping roc_auc:  94%|█████████▍| 942/1000 [00:01<00:00, 786.23it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 812.32it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  10%|█         | 100/1000 [00:00<00:00, 993.19it/s]

Bootstrapping precision:  21%|██▏       | 214/1000 [00:00<00:00, 1078.10it/s]

Bootstrapping precision:  33%|███▎      | 330/1000 [00:00<00:00, 1111.99it/s]

Bootstrapping precision:  44%|████▍     | 444/1000 [00:00<00:00, 1121.23it/s]

Bootstrapping precision:  56%|█████▌    | 557/1000 [00:00<00:00, 1068.44it/s]

Bootstrapping precision:  66%|██████▋   | 665/1000 [00:00<00:00, 1050.18it/s]

Bootstrapping precision:  77%|███████▋  | 771/1000 [00:00<00:00, 1051.16it/s]

Bootstrapping precision:  88%|████████▊ | 877/1000 [00:00<00:00, 1026.37it/s]

Bootstrapping precision:  98%|█████████▊| 980/1000 [00:00<00:00, 1000.30it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1038.34it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:   9%|▉         | 92/1000 [00:00<00:00, 910.76it/s]

Bootstrapping recall:  20%|█▉        | 199/1000 [00:00<00:00, 1000.36it/s]

Bootstrapping recall:  31%|███       | 306/1000 [00:00<00:00, 1031.04it/s]

Bootstrapping recall:  42%|████▏     | 417/1000 [00:00<00:00, 1061.29it/s]

Bootstrapping recall:  53%|█████▎    | 533/1000 [00:00<00:00, 1096.07it/s]

Bootstrapping recall:  65%|██████▌   | 654/1000 [00:00<00:00, 1132.19it/s]

Bootstrapping recall:  77%|███████▋  | 772/1000 [00:00<00:00, 1146.28it/s]

Bootstrapping recall:  89%|████████▉ | 894/1000 [00:00<00:00, 1168.20it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1122.50it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1196.06it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1174.96it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1177.45it/s]

Bootstrapping f1:  48%|████▊     | 481/1000 [00:00<00:00, 1191.67it/s]

Bootstrapping f1:  60%|██████    | 603/1000 [00:00<00:00, 1200.54it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1207.36it/s]

Bootstrapping f1:  85%|████████▍ | 847/1000 [00:00<00:00, 1200.14it/s]

Bootstrapping f1:  97%|█████████▋| 968/1000 [00:00<00:00, 1182.67it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1186.80it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 338/1000 [00:00<00:00, 3376.21it/s]

Bootstrapping accuracy:  68%|██████▊   | 678/1000 [00:00<00:00, 3385.76it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3350.69it/s]

Processing Correlation — 38 nodes, 37 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  12%|█▏        | 118/1000 [00:00<00:00, 1177.54it/s]

Bootstrapping average_precision:  24%|██▍       | 245/1000 [00:00<00:00, 1228.54it/s]

Bootstrapping average_precision:  38%|███▊      | 376/1000 [00:00<00:00, 1263.58it/s]

Bootstrapping average_precision:  51%|█████     | 509/1000 [00:00<00:00, 1289.39it/s]

Bootstrapping average_precision:  65%|██████▍   | 648/1000 [00:00<00:00, 1323.39it/s]

Bootstrapping average_precision:  78%|███████▊  | 783/1000 [00:00<00:00, 1331.60it/s]

Bootstrapping average_precision:  92%|█████████▏| 917/1000 [00:00<00:00, 1318.50it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1298.07it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 79/1000 [00:00<00:01, 787.76it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 832.63it/s]

Bootstrapping roc_auc:  25%|██▌       | 252/1000 [00:00<00:00, 844.56it/s]

Bootstrapping roc_auc:  34%|███▎      | 337/1000 [00:00<00:00, 837.99it/s]

Bootstrapping roc_auc:  42%|████▏     | 423/1000 [00:00<00:00, 842.58it/s]

Bootstrapping roc_auc:  51%|█████     | 509/1000 [00:00<00:00, 845.35it/s]

Bootstrapping roc_auc:  60%|█████▉    | 596/1000 [00:00<00:00, 850.51it/s]

Bootstrapping roc_auc:  68%|██████▊   | 682/1000 [00:00<00:00, 847.37it/s]

Bootstrapping roc_auc:  77%|███████▋  | 767/1000 [00:00<00:00, 848.05it/s]

Bootstrapping roc_auc:  85%|████████▌ | 852/1000 [00:01<00:00, 847.03it/s]

Bootstrapping roc_auc:  94%|█████████▎| 937/1000 [00:01<00:00, 844.30it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 843.27it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1190.64it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1187.23it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1170.72it/s]

Bootstrapping precision:  48%|████▊     | 478/1000 [00:00<00:00, 1176.97it/s]

Bootstrapping precision:  60%|█████▉    | 596/1000 [00:00<00:00, 1170.66it/s]

Bootstrapping precision:  72%|███████▏  | 716/1000 [00:00<00:00, 1178.28it/s]

Bootstrapping precision:  84%|████████▍ | 838/1000 [00:00<00:00, 1191.14it/s]

Bootstrapping precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1189.19it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1181.76it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 108/1000 [00:00<00:00, 1073.27it/s]

Bootstrapping recall:  22%|██▏       | 221/1000 [00:00<00:00, 1106.25it/s]

Bootstrapping recall:  34%|███▍      | 340/1000 [00:00<00:00, 1144.10it/s]

Bootstrapping recall:  46%|████▌     | 462/1000 [00:00<00:00, 1172.05it/s]

Bootstrapping recall:  58%|█████▊    | 580/1000 [00:00<00:00, 1166.93it/s]

Bootstrapping recall:  70%|██████▉   | 697/1000 [00:00<00:00, 1155.27it/s]

Bootstrapping recall:  81%|████████▏ | 813/1000 [00:00<00:00, 1079.55it/s]

Bootstrapping recall:  92%|█████████▏| 922/1000 [00:00<00:00, 1071.44it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1104.49it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1124.51it/s]

Bootstrapping f1:  23%|██▎       | 226/1000 [00:00<00:00, 1084.93it/s]

Bootstrapping f1:  34%|███▎      | 335/1000 [00:00<00:00, 1059.71it/s]

Bootstrapping f1:  44%|████▍     | 442/1000 [00:00<00:00, 1042.56it/s]

Bootstrapping f1:  55%|█████▍    | 547/1000 [00:00<00:00, 1034.95it/s]

Bootstrapping f1:  65%|██████▌   | 651/1000 [00:00<00:00, 1012.68it/s]

Bootstrapping f1:  75%|███████▌  | 753/1000 [00:00<00:00, 997.62it/s]

Bootstrapping f1:  85%|████████▌ | 853/1000 [00:00<00:00, 984.18it/s]

Bootstrapping f1:  96%|█████████▋| 964/1000 [00:00<00:00, 1020.42it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1029.89it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 337/1000 [00:00<00:00, 3365.93it/s]

Bootstrapping accuracy:  67%|██████▋   | 674/1000 [00:00<00:00, 3364.47it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3289.56it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  11%|█         | 112/1000 [00:00<00:00, 1118.35it/s]

Bootstrapping average_precision:  23%|██▎       | 228/1000 [00:00<00:00, 1139.72it/s]

Bootstrapping average_precision:  35%|███▌      | 354/1000 [00:00<00:00, 1194.12it/s]

Bootstrapping average_precision:  49%|████▊     | 487/1000 [00:00<00:00, 1244.82it/s]

Bootstrapping average_precision:  62%|██████▏   | 622/1000 [00:00<00:00, 1281.41it/s]

Bootstrapping average_precision:  75%|███████▌  | 752/1000 [00:00<00:00, 1287.41it/s]

Bootstrapping average_precision:  88%|████████▊ | 881/1000 [00:00<00:00, 1285.35it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1254.58it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 853.44it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 856.76it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 862.08it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 864.21it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 859.53it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 857.62it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 843.87it/s]

Bootstrapping roc_auc:  69%|██████▉   | 690/1000 [00:00<00:00, 806.16it/s]

Bootstrapping roc_auc:  77%|███████▋  | 771/1000 [00:00<00:00, 803.42it/s]

Bootstrapping roc_auc:  85%|████████▌ | 854/1000 [00:01<00:00, 808.65it/s]

Bootstrapping roc_auc:  94%|█████████▎| 937/1000 [00:01<00:00, 813.87it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 830.25it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1187.83it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1149.57it/s]

Bootstrapping precision:  35%|███▌      | 354/1000 [00:00<00:00, 1137.11it/s]

Bootstrapping precision:  47%|████▋     | 473/1000 [00:00<00:00, 1155.36it/s]

Bootstrapping precision:  59%|█████▉    | 589/1000 [00:00<00:00, 1141.23it/s]

Bootstrapping precision:  71%|███████   | 707/1000 [00:00<00:00, 1151.27it/s]

Bootstrapping precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1166.39it/s]

Bootstrapping precision:  95%|█████████▍| 947/1000 [00:00<00:00, 1174.42it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1163.36it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1198.34it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1176.48it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1187.62it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1198.23it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1201.47it/s]

Bootstrapping recall:  72%|███████▎  | 725/1000 [00:00<00:00, 1203.01it/s]

Bootstrapping recall:  85%|████████▍ | 846/1000 [00:00<00:00, 1196.52it/s]

Bootstrapping recall:  97%|█████████▋| 966/1000 [00:00<00:00, 1181.87it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1187.75it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1168.89it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1177.15it/s]

Bootstrapping f1:  36%|███▌      | 358/1000 [00:00<00:00, 1194.64it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1203.80it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1209.18it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1214.21it/s]

Bootstrapping f1:  85%|████████▍ | 847/1000 [00:00<00:00, 1208.96it/s]

Bootstrapping f1:  97%|█████████▋| 968/1000 [00:00<00:00, 1197.56it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1197.88it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3497.14it/s]

Bootstrapping accuracy:  70%|███████   | 704/1000 [00:00<00:00, 3519.62it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3517.99it/s]

Processing Clinician Consensus $\cup$ Golem — 213 nodes, 387 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1368.51it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1376.15it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1359.91it/s]

Bootstrapping average_precision:  55%|█████▌    | 551/1000 [00:00<00:00, 1344.17it/s]

Bootstrapping average_precision:  69%|██████▊   | 686/1000 [00:00<00:00, 1335.85it/s]

Bootstrapping average_precision:  82%|████████▏ | 823/1000 [00:00<00:00, 1344.49it/s]

Bootstrapping average_precision:  96%|█████████▌| 962/1000 [00:00<00:00, 1357.27it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1353.68it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 874.53it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 862.16it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 867.39it/s]

Bootstrapping roc_auc:  35%|███▌      | 353/1000 [00:00<00:00, 873.98it/s]

Bootstrapping roc_auc:  44%|████▍     | 441/1000 [00:00<00:00, 869.88it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 864.98it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 869.08it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 872.26it/s]

Bootstrapping roc_auc:  79%|███████▉  | 792/1000 [00:00<00:00, 873.23it/s]

Bootstrapping roc_auc:  88%|████████▊ | 880/1000 [00:01<00:00, 868.02it/s]

Bootstrapping roc_auc:  97%|█████████▋| 967/1000 [00:01<00:00, 862.86it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.32it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 117/1000 [00:00<00:00, 1168.88it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1188.37it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1195.73it/s]

Bootstrapping precision:  48%|████▊     | 480/1000 [00:00<00:00, 1200.12it/s]

Bootstrapping precision:  60%|██████    | 601/1000 [00:00<00:00, 1170.84it/s]

Bootstrapping precision:  72%|███████▏  | 719/1000 [00:00<00:00, 1156.95it/s]

Bootstrapping precision:  84%|████████▎ | 835/1000 [00:00<00:00, 1152.58it/s]

Bootstrapping precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1157.63it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1167.17it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1174.15it/s]

Bootstrapping recall:  24%|██▍       | 239/1000 [00:00<00:00, 1190.58it/s]

Bootstrapping recall:  36%|███▌      | 359/1000 [00:00<00:00, 1192.79it/s]

Bootstrapping recall:  48%|████▊     | 479/1000 [00:00<00:00, 1181.34it/s]

Bootstrapping recall:  60%|█████▉    | 598/1000 [00:00<00:00, 1183.40it/s]

Bootstrapping recall:  72%|███████▏  | 719/1000 [00:00<00:00, 1189.10it/s]

Bootstrapping recall:  84%|████████▍ | 838/1000 [00:00<00:00, 1186.20it/s]

Bootstrapping recall:  96%|█████████▌| 957/1000 [00:00<00:00, 1181.99it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1183.28it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1158.17it/s]

Bootstrapping f1:  23%|██▎       | 233/1000 [00:00<00:00, 1164.58it/s]

Bootstrapping f1:  35%|███▌      | 353/1000 [00:00<00:00, 1176.78it/s]

Bootstrapping f1:  47%|████▋     | 474/1000 [00:00<00:00, 1187.92it/s]

Bootstrapping f1:  60%|█████▉    | 596/1000 [00:00<00:00, 1196.05it/s]

Bootstrapping f1:  72%|███████▏  | 718/1000 [00:00<00:00, 1201.05it/s]

Bootstrapping f1:  84%|████████▍ | 839/1000 [00:00<00:00, 1190.11it/s]

Bootstrapping f1:  96%|█████████▌| 959/1000 [00:00<00:00, 1182.56it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1182.57it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3531.99it/s]

Bootstrapping accuracy:  71%|███████   | 711/1000 [00:00<00:00, 3549.42it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3547.74it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1323.83it/s]

Bootstrapping average_precision:  27%|██▋       | 266/1000 [00:00<00:00, 1294.63it/s]

Bootstrapping average_precision:  40%|███▉      | 398/1000 [00:00<00:00, 1305.63it/s]

Bootstrapping average_precision:  53%|█████▎    | 532/1000 [00:00<00:00, 1317.47it/s]

Bootstrapping average_precision:  67%|██████▋   | 667/1000 [00:00<00:00, 1328.46it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 1337.75it/s]

Bootstrapping average_precision:  94%|█████████▍| 940/1000 [00:00<00:00, 1345.52it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1331.40it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 863.71it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 865.05it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 867.27it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 867.98it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 857.31it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 857.11it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 852.17it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 840.40it/s]

Bootstrapping roc_auc:  78%|███████▊  | 779/1000 [00:00<00:00, 846.09it/s]

Bootstrapping roc_auc:  86%|████████▋ | 864/1000 [00:01<00:00, 842.18it/s]

Bootstrapping roc_auc:  95%|█████████▍| 949/1000 [00:01<00:00, 844.45it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 849.89it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1159.98it/s]

Bootstrapping precision:  24%|██▎       | 235/1000 [00:00<00:00, 1172.22it/s]

Bootstrapping precision:  36%|███▌      | 355/1000 [00:00<00:00, 1184.05it/s]

Bootstrapping precision:  47%|████▋     | 474/1000 [00:00<00:00, 1176.48it/s]

Bootstrapping precision:  59%|█████▉    | 592/1000 [00:00<00:00, 1174.60it/s]

Bootstrapping precision:  71%|███████   | 710/1000 [00:00<00:00, 1172.60it/s]

Bootstrapping precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1178.21it/s]

Bootstrapping precision:  95%|█████████▌| 950/1000 [00:00<00:00, 1186.47it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1180.55it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1209.33it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1214.12it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1217.18it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1215.95it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1213.13it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1209.48it/s]

Bootstrapping recall:  85%|████████▌ | 853/1000 [00:00<00:00, 1203.05it/s]

Bootstrapping recall:  97%|█████████▋| 974/1000 [00:00<00:00, 1203.22it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1207.00it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1185.11it/s]

Bootstrapping f1:  24%|██▍       | 239/1000 [00:00<00:00, 1191.69it/s]

Bootstrapping f1:  36%|███▌      | 361/1000 [00:00<00:00, 1203.33it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1210.35it/s]

Bootstrapping f1:  61%|██████    | 607/1000 [00:00<00:00, 1213.57it/s]

Bootstrapping f1:  73%|███████▎  | 729/1000 [00:00<00:00, 1214.04it/s]

Bootstrapping f1:  85%|████████▌ | 851/1000 [00:00<00:00, 1208.98it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1211.81it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1208.18it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3537.81it/s]

Bootstrapping accuracy:  71%|███████   | 711/1000 [00:00<00:00, 3555.13it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3560.76it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB — 19 nodes, 52 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 139/1000 [00:00<00:00, 1380.10it/s]

Bootstrapping average_precision:  28%|██▊       | 278/1000 [00:00<00:00, 1373.04it/s]

Bootstrapping average_precision:  42%|████▏     | 416/1000 [00:00<00:00, 1356.41it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1348.16it/s]

Bootstrapping average_precision:  69%|██████▊   | 687/1000 [00:00<00:00, 1344.28it/s]

Bootstrapping average_precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1352.15it/s]

Bootstrapping average_precision:  96%|█████████▌| 962/1000 [00:00<00:00, 1359.20it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1355.45it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 847.47it/s]

Bootstrapping roc_auc:  17%|█▋        | 171/1000 [00:00<00:00, 853.74it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 864.78it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 870.00it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 872.85it/s]

Bootstrapping roc_auc:  52%|█████▏    | 523/1000 [00:00<00:00, 865.70it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 858.18it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 854.19it/s]

Bootstrapping roc_auc:  78%|███████▊  | 782/1000 [00:00<00:00, 853.19it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 854.06it/s]

Bootstrapping roc_auc:  96%|█████████▌| 955/1000 [00:01<00:00, 858.85it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.09it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 117/1000 [00:00<00:00, 1167.08it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1178.42it/s]

Bootstrapping precision:  35%|███▌      | 354/1000 [00:00<00:00, 1174.09it/s]

Bootstrapping precision:  47%|████▋     | 472/1000 [00:00<00:00, 1169.93it/s]

Bootstrapping precision:  59%|█████▉    | 593/1000 [00:00<00:00, 1180.89it/s]

Bootstrapping precision:  71%|███████   | 712/1000 [00:00<00:00, 1176.82it/s]

Bootstrapping precision:  83%|████████▎ | 830/1000 [00:00<00:00, 1167.48it/s]

Bootstrapping precision:  95%|█████████▍| 947/1000 [00:00<00:00, 1156.72it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1166.56it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1190.69it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1166.94it/s]

Bootstrapping recall:  36%|███▌      | 357/1000 [00:00<00:00, 1154.36it/s]

Bootstrapping recall:  48%|████▊     | 476/1000 [00:00<00:00, 1167.62it/s]

Bootstrapping recall:  60%|█████▉    | 596/1000 [00:00<00:00, 1177.25it/s]

Bootstrapping recall:  72%|███████▏  | 717/1000 [00:00<00:00, 1185.63it/s]

Bootstrapping recall:  84%|████████▍ | 838/1000 [00:00<00:00, 1192.71it/s]

Bootstrapping recall:  96%|█████████▌| 958/1000 [00:00<00:00, 1186.07it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1175.97it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 114/1000 [00:00<00:00, 1139.16it/s]

Bootstrapping f1:  23%|██▎       | 231/1000 [00:00<00:00, 1153.77it/s]

Bootstrapping f1:  35%|███▍      | 349/1000 [00:00<00:00, 1161.59it/s]

Bootstrapping f1:  47%|████▋     | 470/1000 [00:00<00:00, 1179.95it/s]

Bootstrapping f1:  59%|█████▉    | 592/1000 [00:00<00:00, 1191.58it/s]

Bootstrapping f1:  71%|███████   | 712/1000 [00:00<00:00, 1162.71it/s]

Bootstrapping f1:  83%|████████▎ | 829/1000 [00:00<00:00, 1154.28it/s]

Bootstrapping f1:  94%|█████████▍| 945/1000 [00:00<00:00, 1143.65it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1154.72it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 342/1000 [00:00<00:00, 3412.83it/s]

Bootstrapping accuracy:  69%|██████▉   | 689/1000 [00:00<00:00, 3442.91it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3429.32it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 130/1000 [00:00<00:00, 1295.60it/s]

Bootstrapping average_precision:  26%|██▌       | 260/1000 [00:00<00:00, 1252.58it/s]

Bootstrapping average_precision:  39%|███▉      | 394/1000 [00:00<00:00, 1289.10it/s]

Bootstrapping average_precision:  53%|█████▎    | 529/1000 [00:00<00:00, 1309.85it/s]

Bootstrapping average_precision:  66%|██████▋   | 665/1000 [00:00<00:00, 1325.11it/s]

Bootstrapping average_precision:  80%|████████  | 801/1000 [00:00<00:00, 1335.43it/s]

Bootstrapping average_precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1343.63it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1324.06it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 859.33it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 860.60it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 851.41it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 849.57it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 853.43it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 855.93it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 858.68it/s]

Bootstrapping roc_auc:  69%|██████▉   | 694/1000 [00:00<00:00, 860.46it/s]

Bootstrapping roc_auc:  78%|███████▊  | 781/1000 [00:00<00:00, 862.11it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 864.24it/s]

Bootstrapping roc_auc:  96%|█████████▌| 955/1000 [00:01<00:00, 864.39it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 859.31it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1209.12it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1212.22it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1214.47it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1214.23it/s]

Bootstrapping precision:  61%|██████    | 609/1000 [00:00<00:00, 1214.50it/s]

Bootstrapping precision:  73%|███████▎  | 731/1000 [00:00<00:00, 1198.88it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1196.01it/s]

Bootstrapping precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1202.09it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1204.59it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1213.95it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1185.80it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1189.64it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1196.93it/s]

Bootstrapping recall:  61%|██████    | 607/1000 [00:00<00:00, 1201.91it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1204.48it/s]

Bootstrapping recall:  85%|████████▌ | 851/1000 [00:00<00:00, 1209.39it/s]

Bootstrapping recall:  97%|█████████▋| 974/1000 [00:00<00:00, 1212.87it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1204.64it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1216.58it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1217.50it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1216.68it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1215.32it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1215.15it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1215.78it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1217.67it/s]

Bootstrapping f1:  98%|█████████▊| 978/1000 [00:00<00:00, 1219.20it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1216.34it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3558.62it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3550.18it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3557.42it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem — 23 nodes, 34 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 139/1000 [00:00<00:00, 1389.22it/s]

Bootstrapping average_precision:  28%|██▊       | 280/1000 [00:00<00:00, 1396.28it/s]

Bootstrapping average_precision:  42%|████▏     | 420/1000 [00:00<00:00, 1390.52it/s]

Bootstrapping average_precision:  56%|█████▌    | 560/1000 [00:00<00:00, 1389.80it/s]

Bootstrapping average_precision:  70%|███████   | 700/1000 [00:00<00:00, 1390.77it/s]

Bootstrapping average_precision:  84%|████████▍ | 840/1000 [00:00<00:00, 1379.12it/s]

Bootstrapping average_precision:  98%|█████████▊| 978/1000 [00:00<00:00, 1375.13it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1380.59it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 844.93it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 855.11it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 860.63it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 840.51it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 850.82it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 852.70it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 855.64it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 858.14it/s]

Bootstrapping roc_auc:  78%|███████▊  | 781/1000 [00:00<00:00, 864.61it/s]

Bootstrapping roc_auc:  87%|████████▋ | 869/1000 [00:01<00:00, 868.38it/s]

Bootstrapping roc_auc:  96%|█████████▌| 957/1000 [00:01<00:00, 871.90it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 861.40it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1209.23it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1214.13it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1209.15it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1205.65it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1198.02it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1201.80it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1200.62it/s]

Bootstrapping precision:  97%|█████████▋| 970/1000 [00:00<00:00, 1200.40it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1201.77it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1188.69it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1181.34it/s]

Bootstrapping recall:  36%|███▌      | 357/1000 [00:00<00:00, 1185.16it/s]

Bootstrapping recall:  48%|████▊     | 476/1000 [00:00<00:00, 1185.40it/s]

Bootstrapping recall:  60%|█████▉    | 595/1000 [00:00<00:00, 1184.93it/s]

Bootstrapping recall:  72%|███████▏  | 716/1000 [00:00<00:00, 1191.13it/s]

Bootstrapping recall:  84%|████████▎ | 836/1000 [00:00<00:00, 1193.38it/s]

Bootstrapping recall:  96%|█████████▌| 957/1000 [00:00<00:00, 1198.64it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1192.15it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1205.88it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1199.74it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1190.07it/s]

Bootstrapping f1:  48%|████▊     | 482/1000 [00:00<00:00, 1186.25it/s]

Bootstrapping f1:  60%|██████    | 601/1000 [00:00<00:00, 1186.67it/s]

Bootstrapping f1:  72%|███████▏  | 721/1000 [00:00<00:00, 1189.33it/s]

Bootstrapping f1:  84%|████████▍ | 842/1000 [00:00<00:00, 1194.52it/s]

Bootstrapping f1:  96%|█████████▋| 963/1000 [00:00<00:00, 1197.23it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1193.51it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 358/1000 [00:00<00:00, 3575.38it/s]

Bootstrapping accuracy:  72%|███████▏  | 716/1000 [00:00<00:00, 3574.55it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3571.59it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1344.14it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1338.45it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 1344.46it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1351.26it/s]

Bootstrapping average_precision:  68%|██████▊   | 680/1000 [00:00<00:00, 1357.65it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1359.75it/s]

Bootstrapping average_precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1356.96it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1352.94it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 859.60it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 854.24it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 859.80it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 862.38it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 854.65it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 846.04it/s]

Bootstrapping roc_auc:  60%|██████    | 604/1000 [00:00<00:00, 847.06it/s]

Bootstrapping roc_auc:  69%|██████▉   | 689/1000 [00:00<00:00, 847.17it/s]

Bootstrapping roc_auc:  77%|███████▋  | 774/1000 [00:00<00:00, 843.75it/s]

Bootstrapping roc_auc:  86%|████████▌ | 859/1000 [00:01<00:00, 844.48it/s]

Bootstrapping roc_auc:  94%|█████████▍| 944/1000 [00:01<00:00, 843.64it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 846.94it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1174.04it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1172.79it/s]

Bootstrapping precision:  36%|███▌      | 358/1000 [00:00<00:00, 1191.16it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1202.90it/s]

Bootstrapping precision:  60%|██████    | 603/1000 [00:00<00:00, 1208.93it/s]

Bootstrapping precision:  73%|███████▎  | 726/1000 [00:00<00:00, 1212.91it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1195.03it/s]

Bootstrapping precision:  97%|█████████▋| 968/1000 [00:00<00:00, 1185.49it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1190.08it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1172.70it/s]

Bootstrapping recall:  24%|██▎       | 237/1000 [00:00<00:00, 1181.32it/s]

Bootstrapping recall:  36%|███▌      | 356/1000 [00:00<00:00, 1168.11it/s]

Bootstrapping recall:  47%|████▋     | 473/1000 [00:00<00:00, 1140.87it/s]

Bootstrapping recall:  59%|█████▉    | 590/1000 [00:00<00:00, 1147.81it/s]

Bootstrapping recall:  71%|███████   | 708/1000 [00:00<00:00, 1157.32it/s]

Bootstrapping recall:  82%|████████▎ | 825/1000 [00:00<00:00, 1159.78it/s]

Bootstrapping recall:  94%|█████████▍| 944/1000 [00:00<00:00, 1167.84it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1161.57it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1169.73it/s]

Bootstrapping f1:  24%|██▎       | 235/1000 [00:00<00:00, 1148.87it/s]

Bootstrapping f1:  35%|███▌      | 350/1000 [00:00<00:00, 1136.20it/s]

Bootstrapping f1:  46%|████▋     | 464/1000 [00:00<00:00, 1121.61it/s]

Bootstrapping f1:  58%|█████▊    | 580/1000 [00:00<00:00, 1132.31it/s]

Bootstrapping f1:  70%|██████▉   | 696/1000 [00:00<00:00, 1141.51it/s]

Bootstrapping f1:  82%|████████▏ | 816/1000 [00:00<00:00, 1159.49it/s]

Bootstrapping f1:  93%|█████████▎| 932/1000 [00:00<00:00, 1156.76it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1148.19it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 339/1000 [00:00<00:00, 3388.37it/s]

Bootstrapping accuracy:  68%|██████▊   | 683/1000 [00:00<00:00, 3414.54it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3413.28it/s]

Processing Clinician Consensus $\cup$ PCMB — 215 nodes, 430 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1283.60it/s]

Bootstrapping average_precision:  26%|██▌       | 261/1000 [00:00<00:00, 1304.87it/s]

Bootstrapping average_precision:  40%|███▉      | 395/1000 [00:00<00:00, 1318.22it/s]

Bootstrapping average_precision:  53%|█████▎    | 527/1000 [00:00<00:00, 1315.15it/s]

Bootstrapping average_precision:  66%|██████▌   | 662/1000 [00:00<00:00, 1325.29it/s]

Bootstrapping average_precision:  80%|███████▉  | 795/1000 [00:00<00:00, 1324.86it/s]

Bootstrapping average_precision:  93%|█████████▎| 928/1000 [00:00<00:00, 1322.55it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1318.92it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 833.88it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:01, 830.20it/s]

Bootstrapping roc_auc:  25%|██▌       | 252/1000 [00:00<00:00, 829.79it/s]

Bootstrapping roc_auc:  34%|███▎      | 337/1000 [00:00<00:00, 835.29it/s]

Bootstrapping roc_auc:  42%|████▎     | 425/1000 [00:00<00:00, 847.76it/s]

Bootstrapping roc_auc:  51%|█████▏    | 513/1000 [00:00<00:00, 856.25it/s]

Bootstrapping roc_auc:  60%|█████▉    | 599/1000 [00:00<00:00, 831.21it/s]

Bootstrapping roc_auc:  68%|██████▊   | 683/1000 [00:00<00:00, 832.03it/s]

Bootstrapping roc_auc:  77%|███████▋  | 767/1000 [00:00<00:00, 823.92it/s]

Bootstrapping roc_auc:  85%|████████▌ | 850/1000 [00:01<00:00, 817.71it/s]

Bootstrapping roc_auc:  93%|█████████▎| 932/1000 [00:01<00:00, 811.60it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 824.49it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 112/1000 [00:00<00:00, 1115.42it/s]

Bootstrapping precision:  22%|██▏       | 224/1000 [00:00<00:00, 1115.30it/s]

Bootstrapping precision:  34%|███▍      | 339/1000 [00:00<00:00, 1129.10it/s]

Bootstrapping precision:  46%|████▌     | 460/1000 [00:00<00:00, 1160.25it/s]

Bootstrapping precision:  58%|█████▊    | 580/1000 [00:00<00:00, 1173.31it/s]

Bootstrapping precision:  70%|███████   | 701/1000 [00:00<00:00, 1182.55it/s]

Bootstrapping precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1178.55it/s]

Bootstrapping precision:  94%|█████████▍| 940/1000 [00:00<00:00, 1184.82it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1170.24it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1180.94it/s]

Bootstrapping recall:  24%|██▍       | 239/1000 [00:00<00:00, 1187.87it/s]

Bootstrapping recall:  36%|███▌      | 359/1000 [00:00<00:00, 1191.62it/s]

Bootstrapping recall:  48%|████▊     | 479/1000 [00:00<00:00, 1190.68it/s]

Bootstrapping recall:  60%|█████▉    | 599/1000 [00:00<00:00, 1190.77it/s]

Bootstrapping recall:  72%|███████▏  | 719/1000 [00:00<00:00, 1189.71it/s]

Bootstrapping recall:  84%|████████▍ | 838/1000 [00:00<00:00, 1185.97it/s]

Bootstrapping recall:  96%|█████████▌| 958/1000 [00:00<00:00, 1188.83it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1187.31it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1187.07it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1195.02it/s]

Bootstrapping f1:  36%|███▌      | 361/1000 [00:00<00:00, 1200.42it/s]

Bootstrapping f1:  48%|████▊     | 482/1000 [00:00<00:00, 1196.01it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1192.15it/s]

Bootstrapping f1:  72%|███████▏  | 722/1000 [00:00<00:00, 1186.17it/s]

Bootstrapping f1:  84%|████████▍ | 843/1000 [00:00<00:00, 1191.60it/s]

Bootstrapping f1:  96%|█████████▋| 963/1000 [00:00<00:00, 1188.49it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1189.49it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3525.45it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3497.33it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3500.85it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1333.75it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1348.16it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1339.26it/s]

Bootstrapping average_precision:  54%|█████▍    | 539/1000 [00:00<00:00, 1318.15it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1324.76it/s]

Bootstrapping average_precision:  81%|████████  | 809/1000 [00:00<00:00, 1334.85it/s]

Bootstrapping average_precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1343.68it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1335.70it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 853.48it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 857.91it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 853.89it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 857.31it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 860.30it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 862.57it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 863.05it/s]

Bootstrapping roc_auc:  69%|██████▉   | 694/1000 [00:00<00:00, 862.38it/s]

Bootstrapping roc_auc:  78%|███████▊  | 781/1000 [00:00<00:00, 862.79it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 863.42it/s]

Bootstrapping roc_auc:  96%|█████████▌| 955/1000 [00:01<00:00, 861.89it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.74it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1185.78it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1187.41it/s]

Bootstrapping precision:  36%|███▌      | 357/1000 [00:00<00:00, 1185.12it/s]

Bootstrapping precision:  48%|████▊     | 477/1000 [00:00<00:00, 1190.18it/s]

Bootstrapping precision:  60%|█████▉    | 598/1000 [00:00<00:00, 1195.32it/s]

Bootstrapping precision:  72%|███████▏  | 720/1000 [00:00<00:00, 1200.35it/s]

Bootstrapping precision:  84%|████████▍ | 841/1000 [00:00<00:00, 1194.78it/s]

Bootstrapping precision:  96%|█████████▌| 962/1000 [00:00<00:00, 1198.20it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1194.46it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1202.84it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1208.59it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1201.54it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1205.44it/s]

Bootstrapping recall:  61%|██████    | 608/1000 [00:00<00:00, 1206.22it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1205.28it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1200.12it/s]

Bootstrapping recall:  97%|█████████▋| 971/1000 [00:00<00:00, 1203.12it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1203.27it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1196.66it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1199.00it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1203.32it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1207.24it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1201.84it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1196.89it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1195.22it/s]

Bootstrapping f1:  97%|█████████▋| 967/1000 [00:00<00:00, 1196.97it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1198.64it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 352/1000 [00:00<00:00, 3517.53it/s]

Bootstrapping accuracy:  70%|███████   | 704/1000 [00:00<00:00, 3511.82it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3519.79it/s]

Processing Simplified Golem $\cup$ Simplified PCMB — 24 nodes, 64 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1373.56it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1370.78it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1371.16it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1374.29it/s]

Bootstrapping average_precision:  69%|██████▉   | 690/1000 [00:00<00:00, 1375.30it/s]

Bootstrapping average_precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1377.24it/s]

Bootstrapping average_precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1376.90it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1372.70it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 863.69it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 858.71it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 861.08it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 863.24it/s]

Bootstrapping roc_auc:  44%|████▎     | 436/1000 [00:00<00:00, 867.52it/s]

Bootstrapping roc_auc:  52%|█████▏    | 523/1000 [00:00<00:00, 866.34it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 863.69it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 861.88it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 863.45it/s]

Bootstrapping roc_auc:  87%|████████▋ | 872/1000 [00:01<00:00, 867.38it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 870.42it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.10it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1177.55it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1176.34it/s]

Bootstrapping precision:  36%|███▌      | 356/1000 [00:00<00:00, 1184.40it/s]

Bootstrapping precision:  48%|████▊     | 476/1000 [00:00<00:00, 1186.74it/s]

Bootstrapping precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1192.76it/s]

Bootstrapping precision:  72%|███████▏  | 718/1000 [00:00<00:00, 1198.43it/s]

Bootstrapping precision:  84%|████████▍ | 839/1000 [00:00<00:00, 1201.15it/s]

Bootstrapping precision:  96%|█████████▌| 960/1000 [00:00<00:00, 1202.42it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1193.23it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1195.80it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1197.42it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1198.38it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1195.42it/s]

Bootstrapping recall:  60%|██████    | 600/1000 [00:00<00:00, 1194.16it/s]

Bootstrapping recall:  72%|███████▏  | 720/1000 [00:00<00:00, 1195.59it/s]

Bootstrapping recall:  84%|████████▍ | 840/1000 [00:00<00:00, 1192.83it/s]

Bootstrapping recall:  96%|█████████▌| 960/1000 [00:00<00:00, 1192.67it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1193.91it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1197.55it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1196.96it/s]

Bootstrapping f1:  36%|███▌      | 360/1000 [00:00<00:00, 1198.19it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1192.72it/s]

Bootstrapping f1:  60%|██████    | 600/1000 [00:00<00:00, 1194.45it/s]

Bootstrapping f1:  72%|███████▏  | 721/1000 [00:00<00:00, 1197.96it/s]

Bootstrapping f1:  84%|████████▍ | 841/1000 [00:00<00:00, 1198.17it/s]

Bootstrapping f1:  96%|█████████▌| 961/1000 [00:00<00:00, 1194.45it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1194.93it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3494.82it/s]

Bootstrapping accuracy:  70%|███████   | 702/1000 [00:00<00:00, 3508.24it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3514.17it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1351.90it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1352.23it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1342.89it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1345.44it/s]

Bootstrapping average_precision:  68%|██████▊   | 678/1000 [00:00<00:00, 1346.45it/s]

Bootstrapping average_precision:  81%|████████▏ | 814/1000 [00:00<00:00, 1347.89it/s]

Bootstrapping average_precision:  95%|█████████▍| 949/1000 [00:00<00:00, 1330.09it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1338.84it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 856.95it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 855.37it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 858.91it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 855.30it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 857.32it/s]

Bootstrapping roc_auc:  52%|█████▏    | 518/1000 [00:00<00:00, 857.66it/s]

Bootstrapping roc_auc:  60%|██████    | 604/1000 [00:00<00:00, 856.99it/s]

Bootstrapping roc_auc:  69%|██████▉   | 691/1000 [00:00<00:00, 858.77it/s]

Bootstrapping roc_auc:  78%|███████▊  | 778/1000 [00:00<00:00, 859.40it/s]

Bootstrapping roc_auc:  86%|████████▋ | 865/1000 [00:01<00:00, 861.33it/s]

Bootstrapping roc_auc:  95%|█████████▌| 952/1000 [00:01<00:00, 859.70it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 858.70it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1185.55it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1198.19it/s]

Bootstrapping precision:  36%|███▌      | 362/1000 [00:00<00:00, 1206.46it/s]

Bootstrapping precision:  48%|████▊     | 484/1000 [00:00<00:00, 1211.42it/s]

Bootstrapping precision:  61%|██████    | 606/1000 [00:00<00:00, 1205.66it/s]

Bootstrapping precision:  73%|███████▎  | 727/1000 [00:00<00:00, 1192.62it/s]

Bootstrapping precision:  85%|████████▍ | 847/1000 [00:00<00:00, 1177.98it/s]

Bootstrapping precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1183.01it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1190.76it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1196.20it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1206.45it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1209.59it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1211.01it/s]

Bootstrapping recall:  61%|██████    | 608/1000 [00:00<00:00, 1209.44it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1204.81it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1205.28it/s]

Bootstrapping recall:  97%|█████████▋| 971/1000 [00:00<00:00, 1204.96it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1205.03it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1198.98it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1199.58it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1201.60it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1201.97it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1202.10it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1204.72it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1204.56it/s]

Bootstrapping f1:  97%|█████████▋| 967/1000 [00:00<00:00, 1204.94it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1201.71it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3492.35it/s]

Bootstrapping accuracy:  70%|███████   | 704/1000 [00:00<00:00, 3515.99it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3522.96it/s]

Processing Clinician Consensus — 204 nodes, 372 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1374.43it/s]

Bootstrapping average_precision:  28%|██▊       | 277/1000 [00:00<00:00, 1379.79it/s]

Bootstrapping average_precision:  42%|████▏     | 416/1000 [00:00<00:00, 1383.50it/s]

Bootstrapping average_precision:  56%|█████▌    | 555/1000 [00:00<00:00, 1385.94it/s]

Bootstrapping average_precision:  69%|██████▉   | 694/1000 [00:00<00:00, 1384.52it/s]

Bootstrapping average_precision:  83%|████████▎ | 833/1000 [00:00<00:00, 1385.13it/s]

Bootstrapping average_precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1386.86it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1383.79it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 859.23it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 863.62it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 855.67it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 856.60it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 861.12it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 865.86it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 869.93it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 871.30it/s]

Bootstrapping roc_auc:  78%|███████▊  | 785/1000 [00:00<00:00, 872.97it/s]

Bootstrapping roc_auc:  87%|████████▋ | 873/1000 [00:01<00:00, 873.04it/s]

Bootstrapping roc_auc:  96%|█████████▌| 961/1000 [00:01<00:00, 872.97it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 868.50it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1212.78it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1208.50it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1203.99it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1205.03it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1205.54it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1208.67it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1207.34it/s]

Bootstrapping precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1206.59it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1206.04it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1197.68it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1204.73it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1201.69it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1165.58it/s]

Bootstrapping recall:  60%|██████    | 600/1000 [00:00<00:00, 1157.52it/s]

Bootstrapping recall:  72%|███████▏  | 716/1000 [00:00<00:00, 1155.19it/s]

Bootstrapping recall:  83%|████████▎ | 832/1000 [00:00<00:00, 1154.75it/s]

Bootstrapping recall:  95%|█████████▍| 948/1000 [00:00<00:00, 1156.36it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1166.08it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1169.31it/s]

Bootstrapping f1:  24%|██▎       | 235/1000 [00:00<00:00, 1172.67it/s]

Bootstrapping f1:  36%|███▌      | 355/1000 [00:00<00:00, 1183.30it/s]

Bootstrapping f1:  48%|████▊     | 475/1000 [00:00<00:00, 1186.47it/s]

Bootstrapping f1:  60%|█████▉    | 596/1000 [00:00<00:00, 1191.31it/s]

Bootstrapping f1:  72%|███████▏  | 717/1000 [00:00<00:00, 1197.08it/s]

Bootstrapping f1:  84%|████████▍ | 839/1000 [00:00<00:00, 1201.49it/s]

Bootstrapping f1:  96%|█████████▌| 960/1000 [00:00<00:00, 1201.07it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1193.37it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3529.22it/s]

Bootstrapping accuracy:  71%|███████   | 709/1000 [00:00<00:00, 3543.20it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3542.48it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1348.17it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1353.57it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1354.37it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1352.02it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1345.65it/s]

Bootstrapping average_precision:  81%|████████▏ | 814/1000 [00:00<00:00, 1344.04it/s]

Bootstrapping average_precision:  95%|█████████▍| 949/1000 [00:00<00:00, 1334.65it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1338.12it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 843.43it/s]

Bootstrapping roc_auc:  17%|█▋        | 171/1000 [00:00<00:00, 847.81it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 855.69it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 858.69it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 852.27it/s]

Bootstrapping roc_auc:  52%|█████▏    | 517/1000 [00:00<00:00, 846.98it/s]

Bootstrapping roc_auc:  60%|██████    | 604/1000 [00:00<00:00, 852.87it/s]

Bootstrapping roc_auc:  69%|██████▉   | 691/1000 [00:00<00:00, 855.55it/s]

Bootstrapping roc_auc:  78%|███████▊  | 778/1000 [00:00<00:00, 859.54it/s]

Bootstrapping roc_auc:  86%|████████▋ | 864/1000 [00:01<00:00, 858.30it/s]

Bootstrapping roc_auc:  95%|█████████▌| 950/1000 [00:01<00:00, 858.75it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 855.04it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1198.21it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1207.53it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1195.87it/s]

Bootstrapping precision:  48%|████▊     | 483/1000 [00:00<00:00, 1181.69it/s]

Bootstrapping precision:  60%|██████    | 603/1000 [00:00<00:00, 1187.01it/s]

Bootstrapping precision:  72%|███████▏  | 723/1000 [00:00<00:00, 1189.86it/s]

Bootstrapping precision:  84%|████████▍ | 845/1000 [00:00<00:00, 1197.98it/s]

Bootstrapping precision:  96%|█████████▋| 965/1000 [00:00<00:00, 1198.20it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1194.19it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1182.57it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1186.76it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1199.62it/s]

Bootstrapping recall:  48%|████▊     | 482/1000 [00:00<00:00, 1207.36it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1209.40it/s]

Bootstrapping recall:  72%|███████▎  | 725/1000 [00:00<00:00, 1208.57it/s]

Bootstrapping recall:  85%|████████▍ | 846/1000 [00:00<00:00, 1205.46it/s]

Bootstrapping recall:  97%|█████████▋| 967/1000 [00:00<00:00, 1202.97it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1201.96it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1212.92it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1216.49it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1211.83it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1208.15it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1212.15it/s]

Bootstrapping f1:  73%|███████▎  | 733/1000 [00:00<00:00, 1215.48it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1216.62it/s]

Bootstrapping f1:  98%|█████████▊| 977/1000 [00:00<00:00, 1212.11it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1211.51it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3550.87it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3553.27it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3555.81it/s]

Processing Simplified Clinician Consensus — 16 nodes, 16 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1374.58it/s]

Bootstrapping average_precision:  28%|██▊       | 277/1000 [00:00<00:00, 1378.58it/s]

Bootstrapping average_precision:  42%|████▏     | 415/1000 [00:00<00:00, 1370.64it/s]

Bootstrapping average_precision:  55%|█████▌    | 553/1000 [00:00<00:00, 1373.78it/s]

Bootstrapping average_precision:  69%|██████▉   | 693/1000 [00:00<00:00, 1380.03it/s]

Bootstrapping average_precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1374.49it/s]

Bootstrapping average_precision:  97%|█████████▋| 970/1000 [00:00<00:00, 1372.10it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1373.38it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 875.22it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 873.32it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 870.95it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 873.02it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 847.81it/s]

Bootstrapping roc_auc:  52%|█████▎    | 525/1000 [00:00<00:00, 847.92it/s]

Bootstrapping roc_auc:  61%|██████    | 611/1000 [00:00<00:00, 851.37it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 853.26it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 858.27it/s]

Bootstrapping roc_auc:  87%|████████▋ | 871/1000 [00:01<00:00, 860.28it/s]

Bootstrapping roc_auc:  96%|█████████▌| 959/1000 [00:01<00:00, 864.20it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.57it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1187.71it/s]

Bootstrapping precision:  24%|██▍       | 239/1000 [00:00<00:00, 1191.80it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1165.58it/s]

Bootstrapping precision:  48%|████▊     | 476/1000 [00:00<00:00, 1137.49it/s]

Bootstrapping precision:  60%|█████▉    | 596/1000 [00:00<00:00, 1158.39it/s]

Bootstrapping precision:  71%|███████   | 712/1000 [00:00<00:00, 1139.70it/s]

Bootstrapping precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1124.02it/s]

Bootstrapping precision:  94%|█████████▍| 940/1000 [00:00<00:00, 1121.68it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1138.07it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1187.17it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1182.10it/s]

Bootstrapping recall:  36%|███▌      | 358/1000 [00:00<00:00, 1188.77it/s]

Bootstrapping recall:  48%|████▊     | 477/1000 [00:00<00:00, 1184.44it/s]

Bootstrapping recall:  60%|█████▉    | 596/1000 [00:00<00:00, 1123.43it/s]

Bootstrapping recall:  71%|███████   | 709/1000 [00:00<00:00, 1119.60it/s]

Bootstrapping recall:  82%|████████▏ | 822/1000 [00:00<00:00, 1110.55it/s]

Bootstrapping recall:  93%|█████████▎| 934/1000 [00:00<00:00, 1104.98it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1128.20it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 110/1000 [00:00<00:00, 1092.81it/s]

Bootstrapping f1:  22%|██▏       | 220/1000 [00:00<00:00, 1095.51it/s]

Bootstrapping f1:  34%|███▎      | 337/1000 [00:00<00:00, 1126.02it/s]

Bootstrapping f1:  46%|████▌     | 455/1000 [00:00<00:00, 1142.61it/s]

Bootstrapping f1:  57%|█████▋    | 570/1000 [00:00<00:00, 1109.32it/s]

Bootstrapping f1:  68%|██████▊   | 682/1000 [00:00<00:00, 1096.97it/s]

Bootstrapping f1:  80%|████████  | 801/1000 [00:00<00:00, 1124.97it/s]

Bootstrapping f1:  91%|█████████▏| 914/1000 [00:00<00:00, 1125.20it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1123.33it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  26%|██▌       | 261/1000 [00:00<00:00, 2606.98it/s]

Bootstrapping accuracy:  58%|█████▊    | 576/1000 [00:00<00:00, 2925.08it/s]

Bootstrapping accuracy:  90%|████████▉ | 896/1000 [00:00<00:00, 3046.85it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 2996.72it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1347.09it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1329.54it/s]

Bootstrapping average_precision:  40%|████      | 403/1000 [00:00<00:00, 1315.63it/s]

Bootstrapping average_precision:  54%|█████▎    | 535/1000 [00:00<00:00, 1312.05it/s]

Bootstrapping average_precision:  67%|██████▋   | 669/1000 [00:00<00:00, 1321.38it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1310.95it/s]

Bootstrapping average_precision:  93%|█████████▎| 934/1000 [00:00<00:00, 1312.29it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1317.17it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 859.96it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 859.50it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 857.11it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 854.75it/s]

Bootstrapping roc_auc:  43%|████▎     | 430/1000 [00:00<00:00, 853.57it/s]

Bootstrapping roc_auc:  52%|█████▏    | 516/1000 [00:00<00:00, 853.64it/s]

Bootstrapping roc_auc:  60%|██████    | 602/1000 [00:00<00:00, 842.08it/s]

Bootstrapping roc_auc:  69%|██████▊   | 687/1000 [00:00<00:00, 814.62it/s]

Bootstrapping roc_auc:  77%|███████▋  | 769/1000 [00:00<00:00, 814.11it/s]

Bootstrapping roc_auc:  85%|████████▌ | 851/1000 [00:01<00:00, 811.84it/s]

Bootstrapping roc_auc:  93%|█████████▎| 933/1000 [00:01<00:00, 809.72it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 827.19it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1146.58it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1113.95it/s]

Bootstrapping precision:  35%|███▌      | 350/1000 [00:00<00:00, 1151.19it/s]

Bootstrapping precision:  47%|████▋     | 472/1000 [00:00<00:00, 1176.72it/s]

Bootstrapping precision:  59%|█████▉    | 594/1000 [00:00<00:00, 1191.60it/s]

Bootstrapping precision:  72%|███████▏  | 716/1000 [00:00<00:00, 1200.05it/s]

Bootstrapping precision:  84%|████████▎ | 837/1000 [00:00<00:00, 1202.66it/s]

Bootstrapping precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1200.01it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1184.55it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1182.49it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1193.43it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1191.46it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1187.50it/s]

Bootstrapping recall:  60%|█████▉    | 599/1000 [00:00<00:00, 1164.42it/s]

Bootstrapping recall:  72%|███████▏  | 716/1000 [00:00<00:00, 1161.27it/s]

Bootstrapping recall:  83%|████████▎ | 834/1000 [00:00<00:00, 1164.08it/s]

Bootstrapping recall:  96%|█████████▌| 955/1000 [00:00<00:00, 1175.28it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1175.72it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1204.01it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1195.65it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1193.75it/s]

Bootstrapping f1:  48%|████▊     | 482/1000 [00:00<00:00, 1190.84it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1193.14it/s]

Bootstrapping f1:  72%|███████▏  | 723/1000 [00:00<00:00, 1197.43it/s]

Bootstrapping f1:  84%|████████▍ | 844/1000 [00:00<00:00, 1198.95it/s]

Bootstrapping f1:  96%|█████████▋| 964/1000 [00:00<00:00, 1197.13it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1195.33it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3549.08it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3560.05it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3555.00it/s]

Processing Clinician Consensus $\cap$ PCMB — 21 nodes, 20 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1341.51it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1338.61it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1354.05it/s]

Bootstrapping average_precision:  55%|█████▍    | 546/1000 [00:00<00:00, 1362.17it/s]

Bootstrapping average_precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1364.63it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1365.59it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1366.08it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1360.73it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 862.67it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 861.36it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 860.24it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 857.77it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 856.94it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 860.70it/s]

Bootstrapping roc_auc:  61%|██████    | 608/1000 [00:00<00:00, 863.57it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 865.82it/s]

Bootstrapping roc_auc:  78%|███████▊  | 783/1000 [00:00<00:00, 865.77it/s]

Bootstrapping roc_auc:  87%|████████▋ | 870/1000 [00:01<00:00, 866.10it/s]

Bootstrapping roc_auc:  96%|█████████▌| 957/1000 [00:01<00:00, 866.01it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 862.98it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1217.63it/s]

Bootstrapping precision:  25%|██▍       | 246/1000 [00:00<00:00, 1225.28it/s]

Bootstrapping precision:  37%|███▋      | 369/1000 [00:00<00:00, 1208.94it/s]

Bootstrapping precision:  49%|████▉     | 490/1000 [00:00<00:00, 1207.12it/s]

Bootstrapping precision:  61%|██████    | 611/1000 [00:00<00:00, 1201.98it/s]

Bootstrapping precision:  73%|███████▎  | 732/1000 [00:00<00:00, 1199.44it/s]

Bootstrapping precision:  85%|████████▌ | 853/1000 [00:00<00:00, 1200.31it/s]

Bootstrapping precision:  98%|█████████▊| 976/1000 [00:00<00:00, 1208.07it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1205.93it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1192.14it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1133.32it/s]

Bootstrapping recall:  35%|███▌      | 354/1000 [00:00<00:00, 1135.59it/s]

Bootstrapping recall:  47%|████▋     | 468/1000 [00:00<00:00, 1132.08it/s]

Bootstrapping recall:  58%|█████▊    | 584/1000 [00:00<00:00, 1141.48it/s]

Bootstrapping recall:  70%|██████▉   | 699/1000 [00:00<00:00, 1133.52it/s]

Bootstrapping recall:  82%|████████▏ | 816/1000 [00:00<00:00, 1143.53it/s]

Bootstrapping recall:  94%|█████████▎| 935/1000 [00:00<00:00, 1156.32it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1148.59it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1185.83it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1172.40it/s]

Bootstrapping f1:  36%|███▌      | 356/1000 [00:00<00:00, 1164.89it/s]

Bootstrapping f1:  47%|████▋     | 474/1000 [00:00<00:00, 1168.14it/s]

Bootstrapping f1:  59%|█████▉    | 591/1000 [00:00<00:00, 1162.73it/s]

Bootstrapping f1:  71%|███████   | 708/1000 [00:00<00:00, 1156.72it/s]

Bootstrapping f1:  83%|████████▎ | 828/1000 [00:00<00:00, 1168.34it/s]

Bootstrapping f1:  95%|█████████▌| 950/1000 [00:00<00:00, 1183.15it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1174.62it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 358/1000 [00:00<00:00, 3571.89it/s]

Bootstrapping accuracy:  72%|███████▏  | 716/1000 [00:00<00:00, 3562.04it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3562.11it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1288.97it/s]

Bootstrapping average_precision:  26%|██▌       | 260/1000 [00:00<00:00, 1297.16it/s]

Bootstrapping average_precision:  40%|███▉      | 395/1000 [00:00<00:00, 1319.97it/s]

Bootstrapping average_precision:  53%|█████▎    | 531/1000 [00:00<00:00, 1335.36it/s]

Bootstrapping average_precision:  67%|██████▋   | 667/1000 [00:00<00:00, 1343.97it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1337.03it/s]

Bootstrapping average_precision:  94%|█████████▎| 936/1000 [00:00<00:00, 1312.17it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1318.64it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 850.59it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 852.30it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 851.85it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 845.23it/s]

Bootstrapping roc_auc:  43%|████▎     | 429/1000 [00:00<00:00, 840.13it/s]

Bootstrapping roc_auc:  52%|█████▏    | 515/1000 [00:00<00:00, 846.70it/s]

Bootstrapping roc_auc:  60%|██████    | 603/1000 [00:00<00:00, 854.54it/s]

Bootstrapping roc_auc:  69%|██████▉   | 689/1000 [00:00<00:00, 852.99it/s]

Bootstrapping roc_auc:  78%|███████▊  | 775/1000 [00:00<00:00, 854.73it/s]

Bootstrapping roc_auc:  86%|████████▌ | 862/1000 [00:01<00:00, 858.62it/s]

Bootstrapping roc_auc:  95%|█████████▍| 949/1000 [00:01<00:00, 861.91it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 854.06it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 117/1000 [00:00<00:00, 1163.80it/s]

Bootstrapping precision:  23%|██▎       | 234/1000 [00:00<00:00, 1167.41it/s]

Bootstrapping precision:  35%|███▌      | 352/1000 [00:00<00:00, 1169.62it/s]

Bootstrapping precision:  47%|████▋     | 472/1000 [00:00<00:00, 1178.67it/s]

Bootstrapping precision:  59%|█████▉    | 593/1000 [00:00<00:00, 1186.87it/s]

Bootstrapping precision:  72%|███████▏  | 715/1000 [00:00<00:00, 1196.05it/s]

Bootstrapping precision:  84%|████████▎ | 835/1000 [00:00<00:00, 1188.44it/s]

Bootstrapping precision:  95%|█████████▌| 954/1000 [00:00<00:00, 1186.94it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1183.52it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1212.40it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1199.57it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1200.27it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1196.53it/s]

Bootstrapping recall:  61%|██████    | 607/1000 [00:00<00:00, 1197.88it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1202.88it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1191.89it/s]

Bootstrapping recall:  97%|█████████▋| 970/1000 [00:00<00:00, 1190.38it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1194.89it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1202.09it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1206.95it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1204.38it/s]

Bootstrapping f1:  48%|████▊     | 485/1000 [00:00<00:00, 1194.41it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1194.75it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1195.00it/s]

Bootstrapping f1:  84%|████████▍ | 845/1000 [00:00<00:00, 1196.52it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1200.07it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1198.51it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3537.17it/s]

Bootstrapping accuracy:  71%|███████   | 711/1000 [00:00<00:00, 3554.51it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3543.95it/s]

Processing Golem — 17 nodes, 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1364.77it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1354.45it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1350.15it/s]

Bootstrapping average_precision:  55%|█████▍    | 546/1000 [00:00<00:00, 1341.15it/s]

Bootstrapping average_precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1329.54it/s]

Bootstrapping average_precision:  81%|████████▏ | 814/1000 [00:00<00:00, 1328.65it/s]

Bootstrapping average_precision:  95%|█████████▌| 950/1000 [00:00<00:00, 1338.20it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1339.89it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 867.68it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 852.43it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 855.22it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 857.05it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 857.22it/s]

Bootstrapping roc_auc:  52%|█████▏    | 518/1000 [00:00<00:00, 851.87it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 854.58it/s]

Bootstrapping roc_auc:  69%|██████▉   | 692/1000 [00:00<00:00, 858.12it/s]

Bootstrapping roc_auc:  78%|███████▊  | 779/1000 [00:00<00:00, 860.65it/s]

Bootstrapping roc_auc:  87%|████████▋ | 866/1000 [00:01<00:00, 863.21it/s]

Bootstrapping roc_auc:  95%|█████████▌| 953/1000 [00:01<00:00, 844.67it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 852.74it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1182.84it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1183.96it/s]

Bootstrapping precision:  36%|███▌      | 357/1000 [00:00<00:00, 1172.95it/s]

Bootstrapping precision:  48%|████▊     | 475/1000 [00:00<00:00, 1154.97it/s]

Bootstrapping precision:  59%|█████▉    | 592/1000 [00:00<00:00, 1159.25it/s]

Bootstrapping precision:  71%|███████   | 711/1000 [00:00<00:00, 1167.16it/s]

Bootstrapping precision:  83%|████████▎ | 831/1000 [00:00<00:00, 1177.61it/s]

Bootstrapping precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1185.57it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1175.96it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1199.69it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1201.55it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1186.44it/s]

Bootstrapping recall:  48%|████▊     | 482/1000 [00:00<00:00, 1189.48it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1189.50it/s]

Bootstrapping recall:  72%|███████▏  | 720/1000 [00:00<00:00, 1188.97it/s]

Bootstrapping recall:  84%|████████▍ | 839/1000 [00:00<00:00, 1130.39it/s]

Bootstrapping recall:  96%|█████████▌| 955/1000 [00:00<00:00, 1138.49it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1162.32it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1197.57it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1200.54it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1200.22it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1202.29it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1206.28it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1203.61it/s]

Bootstrapping f1:  85%|████████▍ | 847/1000 [00:00<00:00, 1190.50it/s]

Bootstrapping f1:  97%|█████████▋| 967/1000 [00:00<00:00, 1184.65it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1192.80it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3492.66it/s]

Bootstrapping accuracy:  70%|███████   | 701/1000 [00:00<00:00, 3501.83it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3498.85it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1345.87it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1349.97it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1350.49it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1353.53it/s]

Bootstrapping average_precision:  68%|██████▊   | 680/1000 [00:00<00:00, 1356.11it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1351.65it/s]

Bootstrapping average_precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1352.64it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1351.85it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 857.41it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 861.87it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 864.14it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 865.56it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 859.13it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 857.14it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 859.35it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 859.29it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 861.53it/s]

Bootstrapping roc_auc:  87%|████████▋ | 867/1000 [00:01<00:00, 863.60it/s]

Bootstrapping roc_auc:  96%|█████████▌| 955/1000 [00:01<00:00, 866.25it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 862.73it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1209.01it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1211.16it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1213.06it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1209.93it/s]

Bootstrapping precision:  61%|██████    | 609/1000 [00:00<00:00, 1210.69it/s]

Bootstrapping precision:  73%|███████▎  | 731/1000 [00:00<00:00, 1181.94it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1184.74it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1191.85it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1196.39it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1209.76it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1212.52it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1215.33it/s]

Bootstrapping recall:  49%|████▊     | 487/1000 [00:00<00:00, 1202.94it/s]

Bootstrapping recall:  61%|██████    | 608/1000 [00:00<00:00, 1198.31it/s]

Bootstrapping recall:  73%|███████▎  | 728/1000 [00:00<00:00, 1196.88it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1202.33it/s]

Bootstrapping recall:  97%|█████████▋| 971/1000 [00:00<00:00, 1188.49it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1197.33it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1196.83it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1204.25it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1204.73it/s]

Bootstrapping f1:  48%|████▊     | 485/1000 [00:00<00:00, 1208.84it/s]

Bootstrapping f1:  61%|██████    | 606/1000 [00:00<00:00, 1207.98it/s]

Bootstrapping f1:  73%|███████▎  | 728/1000 [00:00<00:00, 1211.13it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1206.04it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1210.51it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1207.40it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3558.36it/s]

Bootstrapping accuracy:  72%|███████▏  | 715/1000 [00:00<00:00, 3571.91it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3564.08it/s]

Processing PCMB — 32 nodes, 78 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1328.25it/s]

Bootstrapping average_precision:  27%|██▋       | 269/1000 [00:00<00:00, 1345.18it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 1356.17it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1364.77it/s]

Bootstrapping average_precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1362.15it/s]

Bootstrapping average_precision:  82%|████████▏ | 818/1000 [00:00<00:00, 1358.11it/s]

Bootstrapping average_precision:  95%|█████████▌| 954/1000 [00:00<00:00, 1355.76it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1351.70it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 851.56it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 861.18it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 866.46it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 854.17it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 852.53it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 850.36it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 851.11it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 857.03it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 860.46it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 865.24it/s]

Bootstrapping roc_auc:  96%|█████████▌| 956/1000 [00:01<00:00, 867.12it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.03it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1181.62it/s]

Bootstrapping precision:  24%|██▍       | 239/1000 [00:00<00:00, 1187.34it/s]

Bootstrapping precision:  36%|███▌      | 358/1000 [00:00<00:00, 1183.87it/s]

Bootstrapping precision:  48%|████▊     | 477/1000 [00:00<00:00, 1178.55it/s]

Bootstrapping precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1186.10it/s]

Bootstrapping precision:  72%|███████▏  | 716/1000 [00:00<00:00, 1182.78it/s]

Bootstrapping precision:  84%|████████▎ | 837/1000 [00:00<00:00, 1190.96it/s]

Bootstrapping precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1186.82it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1185.00it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1205.03it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1189.15it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1181.68it/s]

Bootstrapping recall:  48%|████▊     | 481/1000 [00:00<00:00, 1188.13it/s]

Bootstrapping recall:  60%|██████    | 600/1000 [00:00<00:00, 1151.72it/s]

Bootstrapping recall:  72%|███████▏  | 719/1000 [00:00<00:00, 1162.19it/s]

Bootstrapping recall:  84%|████████▎ | 836/1000 [00:00<00:00, 1157.10it/s]

Bootstrapping recall:  95%|█████████▌| 953/1000 [00:00<00:00, 1158.20it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1165.28it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1120.88it/s]

Bootstrapping f1:  23%|██▎       | 229/1000 [00:00<00:00, 1143.04it/s]

Bootstrapping f1:  35%|███▍      | 346/1000 [00:00<00:00, 1153.74it/s]

Bootstrapping f1:  46%|████▌     | 462/1000 [00:00<00:00, 1150.68it/s]

Bootstrapping f1:  58%|█████▊    | 579/1000 [00:00<00:00, 1154.50it/s]

Bootstrapping f1:  70%|██████▉   | 697/1000 [00:00<00:00, 1161.20it/s]

Bootstrapping f1:  82%|████████▏ | 818/1000 [00:00<00:00, 1176.03it/s]

Bootstrapping f1:  94%|█████████▎| 936/1000 [00:00<00:00, 1176.13it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1164.17it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 348/1000 [00:00<00:00, 3475.73it/s]

Bootstrapping accuracy:  70%|███████   | 702/1000 [00:00<00:00, 3508.24it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3503.22it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1346.19it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1355.62it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1343.32it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1331.44it/s]

Bootstrapping average_precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1331.24it/s]

Bootstrapping average_precision:  81%|████████  | 811/1000 [00:00<00:00, 1331.74it/s]

Bootstrapping average_precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1335.42it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1336.42it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 842.84it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 840.62it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 842.64it/s]

Bootstrapping roc_auc:  34%|███▍      | 341/1000 [00:00<00:00, 847.68it/s]

Bootstrapping roc_auc:  43%|████▎     | 427/1000 [00:00<00:00, 851.53it/s]

Bootstrapping roc_auc:  51%|█████▏    | 513/1000 [00:00<00:00, 852.42it/s]

Bootstrapping roc_auc:  60%|██████    | 600/1000 [00:00<00:00, 854.99it/s]

Bootstrapping roc_auc:  69%|██████▊   | 686/1000 [00:00<00:00, 841.07it/s]

Bootstrapping roc_auc:  77%|███████▋  | 772/1000 [00:00<00:00, 845.50it/s]

Bootstrapping roc_auc:  86%|████████▌ | 859/1000 [00:01<00:00, 850.67it/s]

Bootstrapping roc_auc:  94%|█████████▍| 945/1000 [00:01<00:00, 836.15it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 838.32it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 107/1000 [00:00<00:00, 1069.26it/s]

Bootstrapping precision:  22%|██▏       | 220/1000 [00:00<00:00, 1099.54it/s]

Bootstrapping precision:  33%|███▎      | 332/1000 [00:00<00:00, 1104.97it/s]

Bootstrapping precision:  45%|████▍     | 446/1000 [00:00<00:00, 1117.85it/s]

Bootstrapping precision:  56%|█████▌    | 561/1000 [00:00<00:00, 1128.78it/s]

Bootstrapping precision:  68%|██████▊   | 675/1000 [00:00<00:00, 1129.73it/s]

Bootstrapping precision:  79%|███████▉  | 792/1000 [00:00<00:00, 1141.43it/s]

Bootstrapping precision:  91%|█████████ | 911/1000 [00:00<00:00, 1156.48it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1138.86it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1200.15it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1183.69it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1182.97it/s]

Bootstrapping recall:  48%|████▊     | 481/1000 [00:00<00:00, 1189.48it/s]

Bootstrapping recall:  60%|██████    | 600/1000 [00:00<00:00, 1184.98it/s]

Bootstrapping recall:  72%|███████▏  | 719/1000 [00:00<00:00, 1160.62it/s]

Bootstrapping recall:  84%|████████▎ | 836/1000 [00:00<00:00, 1158.28it/s]

Bootstrapping recall:  95%|█████████▌| 952/1000 [00:00<00:00, 1154.21it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1164.45it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1157.02it/s]

Bootstrapping f1:  24%|██▎       | 235/1000 [00:00<00:00, 1176.02it/s]

Bootstrapping f1:  35%|███▌      | 353/1000 [00:00<00:00, 1167.96it/s]

Bootstrapping f1:  47%|████▋     | 470/1000 [00:00<00:00, 1161.43it/s]

Bootstrapping f1:  59%|█████▊    | 587/1000 [00:00<00:00, 1147.89it/s]

Bootstrapping f1:  70%|███████   | 702/1000 [00:00<00:00, 1145.11it/s]

Bootstrapping f1:  82%|████████▏ | 817/1000 [00:00<00:00, 1130.48it/s]

Bootstrapping f1:  93%|█████████▎| 933/1000 [00:00<00:00, 1137.52it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1147.62it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 337/1000 [00:00<00:00, 3369.06it/s]

Bootstrapping accuracy:  68%|██████▊   | 679/1000 [00:00<00:00, 3396.75it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3373.33it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB — 15 nodes, 14 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1337.61it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1360.61it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1371.15it/s]

Bootstrapping average_precision:  55%|█████▍    | 549/1000 [00:00<00:00, 1350.38it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1343.36it/s]

Bootstrapping average_precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1351.96it/s]

Bootstrapping average_precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1352.91it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1350.68it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 838.51it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 846.90it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 841.04it/s]

Bootstrapping roc_auc:  34%|███▍      | 341/1000 [00:00<00:00, 847.26it/s]

Bootstrapping roc_auc:  43%|████▎     | 427/1000 [00:00<00:00, 848.42it/s]

Bootstrapping roc_auc:  51%|█████     | 512/1000 [00:00<00:00, 847.80it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 827.65it/s]

Bootstrapping roc_auc:  68%|██████▊   | 683/1000 [00:00<00:00, 835.79it/s]

Bootstrapping roc_auc:  77%|███████▋  | 769/1000 [00:00<00:00, 842.31it/s]

Bootstrapping roc_auc:  85%|████████▌ | 854/1000 [00:01<00:00, 844.02it/s]

Bootstrapping roc_auc:  94%|█████████▍| 939/1000 [00:01<00:00, 844.88it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 842.00it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1179.54it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1198.98it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1200.28it/s]

Bootstrapping precision:  48%|████▊     | 482/1000 [00:00<00:00, 1192.00it/s]

Bootstrapping precision:  60%|██████    | 602/1000 [00:00<00:00, 1186.49it/s]

Bootstrapping precision:  72%|███████▏  | 721/1000 [00:00<00:00, 1186.50it/s]

Bootstrapping precision:  84%|████████▍ | 840/1000 [00:00<00:00, 1175.20it/s]

Bootstrapping precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1177.97it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1182.72it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1187.63it/s]

Bootstrapping recall:  24%|██▍       | 239/1000 [00:00<00:00, 1192.82it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1197.52it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1193.45it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1197.26it/s]

Bootstrapping recall:  72%|███████▏  | 721/1000 [00:00<00:00, 1187.76it/s]

Bootstrapping recall:  84%|████████▍ | 841/1000 [00:00<00:00, 1188.86it/s]

Bootstrapping recall:  96%|█████████▌| 962/1000 [00:00<00:00, 1195.26it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1193.18it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1181.34it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1103.19it/s]

Bootstrapping f1:  35%|███▌      | 354/1000 [00:00<00:00, 1124.77it/s]

Bootstrapping f1:  47%|████▋     | 474/1000 [00:00<00:00, 1150.80it/s]

Bootstrapping f1:  60%|█████▉    | 595/1000 [00:00<00:00, 1169.08it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1182.58it/s]

Bootstrapping f1:  84%|████████▎ | 837/1000 [00:00<00:00, 1188.38it/s]

Bootstrapping f1:  96%|█████████▌| 957/1000 [00:00<00:00, 1190.64it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1172.13it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 352/1000 [00:00<00:00, 3511.40it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3526.92it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3531.69it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1351.56it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1334.12it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 1330.87it/s]

Bootstrapping average_precision:  54%|█████▍    | 540/1000 [00:00<00:00, 1327.21it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1326.32it/s]

Bootstrapping average_precision:  81%|████████  | 806/1000 [00:00<00:00, 1323.94it/s]

Bootstrapping average_precision:  94%|█████████▍| 939/1000 [00:00<00:00, 1305.86it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1318.36it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 851.68it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 855.16it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 856.54it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 856.95it/s]

Bootstrapping roc_auc:  43%|████▎     | 430/1000 [00:00<00:00, 855.74it/s]

Bootstrapping roc_auc:  52%|█████▏    | 516/1000 [00:00<00:00, 846.92it/s]

Bootstrapping roc_auc:  60%|██████    | 601/1000 [00:00<00:00, 847.03it/s]

Bootstrapping roc_auc:  69%|██████▉   | 688/1000 [00:00<00:00, 851.41it/s]

Bootstrapping roc_auc:  77%|███████▋  | 774/1000 [00:00<00:00, 846.97it/s]

Bootstrapping roc_auc:  86%|████████▌ | 861/1000 [00:01<00:00, 851.43it/s]

Bootstrapping roc_auc:  95%|█████████▍| 948/1000 [00:01<00:00, 854.38it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 852.76it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1170.76it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1172.73it/s]

Bootstrapping precision:  35%|███▌      | 354/1000 [00:00<00:00, 1171.52it/s]

Bootstrapping precision:  47%|████▋     | 472/1000 [00:00<00:00, 1166.21it/s]

Bootstrapping precision:  59%|█████▉    | 589/1000 [00:00<00:00, 1155.06it/s]

Bootstrapping precision:  71%|███████   | 707/1000 [00:00<00:00, 1162.83it/s]

Bootstrapping precision:  82%|████████▎ | 825/1000 [00:00<00:00, 1166.71it/s]

Bootstrapping precision:  94%|█████████▍| 942/1000 [00:00<00:00, 1166.18it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1166.12it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 114/1000 [00:00<00:00, 1134.96it/s]

Bootstrapping recall:  23%|██▎       | 228/1000 [00:00<00:00, 1130.25it/s]

Bootstrapping recall:  34%|███▍      | 342/1000 [00:00<00:00, 1126.44it/s]

Bootstrapping recall:  46%|████▌     | 455/1000 [00:00<00:00, 1116.68it/s]

Bootstrapping recall:  57%|█████▋    | 572/1000 [00:00<00:00, 1133.31it/s]

Bootstrapping recall:  69%|██████▉   | 689/1000 [00:00<00:00, 1142.89it/s]

Bootstrapping recall:  81%|████████  | 807/1000 [00:00<00:00, 1152.20it/s]

Bootstrapping recall:  93%|█████████▎| 929/1000 [00:00<00:00, 1172.90it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1153.98it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1209.71it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1205.40it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1204.30it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1205.64it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1196.40it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1195.75it/s]

Bootstrapping f1:  84%|████████▍ | 845/1000 [00:00<00:00, 1194.03it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1196.20it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1198.40it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3553.39it/s]

Bootstrapping accuracy:  72%|███████▏  | 715/1000 [00:00<00:00, 3569.93it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3558.78it/s]

Processing Simplified PCMB — 18 nodes, 50 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1346.82it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1352.27it/s]

Bootstrapping average_precision:  41%|████      | 409/1000 [00:00<00:00, 1364.39it/s]

Bootstrapping average_precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1370.22it/s]

Bootstrapping average_precision:  69%|██████▊   | 686/1000 [00:00<00:00, 1374.34it/s]

Bootstrapping average_precision:  82%|████████▎ | 825/1000 [00:00<00:00, 1376.95it/s]

Bootstrapping average_precision:  96%|█████████▋| 963/1000 [00:00<00:00, 1375.30it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1359.39it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 82/1000 [00:00<00:01, 815.07it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:00, 836.00it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 843.24it/s]

Bootstrapping roc_auc:  34%|███▍      | 339/1000 [00:00<00:00, 839.70it/s]

Bootstrapping roc_auc:  42%|████▏     | 424/1000 [00:00<00:00, 843.13it/s]

Bootstrapping roc_auc:  51%|█████     | 510/1000 [00:00<00:00, 847.23it/s]

Bootstrapping roc_auc:  60%|█████▉    | 595/1000 [00:00<00:00, 844.92it/s]

Bootstrapping roc_auc:  68%|██████▊   | 682/1000 [00:00<00:00, 851.73it/s]

Bootstrapping roc_auc:  77%|███████▋  | 770/1000 [00:00<00:00, 859.27it/s]

Bootstrapping roc_auc:  86%|████████▌ | 857/1000 [00:01<00:00, 860.83it/s]

Bootstrapping roc_auc:  94%|█████████▍| 945/1000 [00:01<00:00, 864.50it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 853.28it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1185.74it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1179.06it/s]

Bootstrapping precision:  36%|███▌      | 356/1000 [00:00<00:00, 1163.57it/s]

Bootstrapping precision:  48%|████▊     | 475/1000 [00:00<00:00, 1172.52it/s]

Bootstrapping precision:  60%|█████▉    | 595/1000 [00:00<00:00, 1182.07it/s]

Bootstrapping precision:  71%|███████▏  | 714/1000 [00:00<00:00, 1177.05it/s]

Bootstrapping precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1147.48it/s]

Bootstrapping precision:  95%|█████████▍| 947/1000 [00:00<00:00, 1141.64it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1158.30it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1151.06it/s]

Bootstrapping recall:  23%|██▎       | 233/1000 [00:00<00:00, 1157.60it/s]

Bootstrapping recall:  35%|███▍      | 349/1000 [00:00<00:00, 1155.83it/s]

Bootstrapping recall:  46%|████▋     | 465/1000 [00:00<00:00, 1142.54it/s]

Bootstrapping recall:  58%|█████▊    | 580/1000 [00:00<00:00, 1139.48it/s]

Bootstrapping recall:  70%|██████▉   | 698/1000 [00:00<00:00, 1150.41it/s]

Bootstrapping recall:  82%|████████▏ | 815/1000 [00:00<00:00, 1155.08it/s]

Bootstrapping recall:  93%|█████████▎| 931/1000 [00:00<00:00, 1155.85it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1148.60it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 114/1000 [00:00<00:00, 1134.23it/s]

Bootstrapping f1:  23%|██▎       | 229/1000 [00:00<00:00, 1140.11it/s]

Bootstrapping f1:  35%|███▍      | 348/1000 [00:00<00:00, 1159.16it/s]

Bootstrapping f1:  46%|████▋     | 464/1000 [00:00<00:00, 1154.48it/s]

Bootstrapping f1:  58%|█████▊    | 580/1000 [00:00<00:00, 1143.29it/s]

Bootstrapping f1:  70%|██████▉   | 698/1000 [00:00<00:00, 1154.78it/s]

Bootstrapping f1:  82%|████████▏ | 819/1000 [00:00<00:00, 1170.20it/s]

Bootstrapping f1:  94%|█████████▍| 939/1000 [00:00<00:00, 1178.16it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1161.94it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 347/1000 [00:00<00:00, 3466.61it/s]

Bootstrapping accuracy:  70%|██████▉   | 695/1000 [00:00<00:00, 3470.71it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3465.80it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 131/1000 [00:00<00:00, 1309.42it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1339.32it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1350.82it/s]

Bootstrapping average_precision:  54%|█████▍    | 542/1000 [00:00<00:00, 1355.94it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1357.59it/s]

Bootstrapping average_precision:  82%|████████▏ | 815/1000 [00:00<00:00, 1342.76it/s]

Bootstrapping average_precision:  95%|█████████▌| 950/1000 [00:00<00:00, 1336.38it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1341.28it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 856.44it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 859.32it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 856.44it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 850.46it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 856.42it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 860.32it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 852.50it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 856.73it/s]

Bootstrapping roc_auc:  78%|███████▊  | 781/1000 [00:00<00:00, 861.06it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 862.63it/s]

Bootstrapping roc_auc:  96%|█████████▌| 955/1000 [00:01<00:00, 854.50it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 855.83it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1192.25it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1167.78it/s]

Bootstrapping precision:  36%|███▌      | 357/1000 [00:00<00:00, 1161.36it/s]

Bootstrapping precision:  47%|████▋     | 474/1000 [00:00<00:00, 1149.28it/s]

Bootstrapping precision:  59%|█████▉    | 593/1000 [00:00<00:00, 1162.50it/s]

Bootstrapping precision:  71%|███████   | 710/1000 [00:00<00:00, 1159.60it/s]

Bootstrapping precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1160.04it/s]

Bootstrapping precision:  94%|█████████▍| 944/1000 [00:00<00:00, 1162.12it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1158.71it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 114/1000 [00:00<00:00, 1134.51it/s]

Bootstrapping recall:  23%|██▎       | 228/1000 [00:00<00:00, 1136.04it/s]

Bootstrapping recall:  35%|███▍      | 348/1000 [00:00<00:00, 1163.67it/s]

Bootstrapping recall:  46%|████▋     | 465/1000 [00:00<00:00, 1162.28it/s]

Bootstrapping recall:  58%|█████▊    | 584/1000 [00:00<00:00, 1171.30it/s]

Bootstrapping recall:  70%|███████   | 705/1000 [00:00<00:00, 1183.49it/s]

Bootstrapping recall:  83%|████████▎ | 826/1000 [00:00<00:00, 1189.08it/s]

Bootstrapping recall:  95%|█████████▍| 947/1000 [00:00<00:00, 1192.23it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1177.47it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1174.01it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1147.36it/s]

Bootstrapping f1:  35%|███▌      | 351/1000 [00:00<00:00, 1114.39it/s]

Bootstrapping f1:  46%|████▋     | 463/1000 [00:00<00:00, 1103.08it/s]

Bootstrapping f1:  57%|█████▋    | 574/1000 [00:00<00:00, 1098.47it/s]

Bootstrapping f1:  69%|██████▊   | 686/1000 [00:00<00:00, 1104.19it/s]

Bootstrapping f1:  80%|████████  | 800/1000 [00:00<00:00, 1113.98it/s]

Bootstrapping f1:  91%|█████████ | 912/1000 [00:00<00:00, 1106.08it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1115.88it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 345/1000 [00:00<00:00, 3446.52it/s]

Bootstrapping accuracy:  69%|██████▉   | 690/1000 [00:00<00:00, 3421.51it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3427.00it/s]

Processing Clinician Consensus $\cap$ Golem — 8 nodes, 7 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 127/1000 [00:00<00:00, 1262.07it/s]

Bootstrapping average_precision:  26%|██▌       | 258/1000 [00:00<00:00, 1288.32it/s]

Bootstrapping average_precision:  39%|███▉      | 388/1000 [00:00<00:00, 1289.76it/s]

Bootstrapping average_precision:  52%|█████▏    | 520/1000 [00:00<00:00, 1299.39it/s]

Bootstrapping average_precision:  65%|██████▌   | 653/1000 [00:00<00:00, 1308.72it/s]

Bootstrapping average_precision:  79%|███████▊  | 787/1000 [00:00<00:00, 1316.65it/s]

Bootstrapping average_precision:  92%|█████████▏| 919/1000 [00:00<00:00, 1313.96it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1303.66it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 824.75it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 823.49it/s]

Bootstrapping roc_auc:  25%|██▌       | 251/1000 [00:00<00:00, 831.60it/s]

Bootstrapping roc_auc:  34%|███▎      | 335/1000 [00:00<00:00, 804.59it/s]

Bootstrapping roc_auc:  42%|████▏     | 421/1000 [00:00<00:00, 822.09it/s]

Bootstrapping roc_auc:  51%|█████     | 506/1000 [00:00<00:00, 830.74it/s]

Bootstrapping roc_auc:  59%|█████▉    | 591/1000 [00:00<00:00, 835.40it/s]

Bootstrapping roc_auc:  68%|██████▊   | 678/1000 [00:00<00:00, 843.88it/s]

Bootstrapping roc_auc:  76%|███████▋  | 765/1000 [00:00<00:00, 848.69it/s]

Bootstrapping roc_auc:  85%|████████▌ | 850/1000 [00:01<00:00, 844.61it/s]

Bootstrapping roc_auc:  94%|█████████▎| 936/1000 [00:01<00:00, 848.96it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 838.58it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1208.65it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1198.74it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1207.02it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1210.99it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1206.64it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1203.45it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1206.28it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1197.64it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1201.55it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1186.70it/s]

Bootstrapping recall:  24%|██▍       | 239/1000 [00:00<00:00, 1189.04it/s]

Bootstrapping recall:  36%|███▌      | 359/1000 [00:00<00:00, 1192.70it/s]

Bootstrapping recall:  48%|████▊     | 479/1000 [00:00<00:00, 1193.47it/s]

Bootstrapping recall:  60%|█████▉    | 599/1000 [00:00<00:00, 1192.85it/s]

Bootstrapping recall:  72%|███████▏  | 719/1000 [00:00<00:00, 1193.60it/s]

Bootstrapping recall:  84%|████████▍ | 839/1000 [00:00<00:00, 1193.16it/s]

Bootstrapping recall:  96%|█████████▌| 959/1000 [00:00<00:00, 1194.46it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1193.03it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1202.52it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1208.74it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1198.17it/s]

Bootstrapping f1:  48%|████▊     | 485/1000 [00:00<00:00, 1201.65it/s]

Bootstrapping f1:  61%|██████    | 606/1000 [00:00<00:00, 1195.27it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1168.61it/s]

Bootstrapping f1:  84%|████████▍ | 843/1000 [00:00<00:00, 1164.08it/s]

Bootstrapping f1:  96%|█████████▌| 960/1000 [00:00<00:00, 1162.36it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1177.03it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 345/1000 [00:00<00:00, 3441.85it/s]

Bootstrapping accuracy:  69%|██████▉   | 693/1000 [00:00<00:00, 3459.94it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3467.07it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1365.19it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1363.13it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1356.28it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1359.52it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1363.10it/s]

Bootstrapping average_precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1362.41it/s]

Bootstrapping average_precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1359.99it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1359.81it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 834.78it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 848.32it/s]

Bootstrapping roc_auc:  26%|██▌       | 257/1000 [00:00<00:00, 856.83it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 861.00it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 861.72it/s]

Bootstrapping roc_auc:  52%|█████▏    | 518/1000 [00:00<00:00, 861.61it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 862.91it/s]

Bootstrapping roc_auc:  69%|██████▉   | 692/1000 [00:00<00:00, 864.10it/s]

Bootstrapping roc_auc:  78%|███████▊  | 779/1000 [00:00<00:00, 861.05it/s]

Bootstrapping roc_auc:  87%|████████▋ | 866/1000 [00:01<00:00, 861.41it/s]

Bootstrapping roc_auc:  95%|█████████▌| 953/1000 [00:01<00:00, 861.69it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.41it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1201.86it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1205.55it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1207.49it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1212.96it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1210.97it/s]

Bootstrapping precision:  73%|███████▎  | 730/1000 [00:00<00:00, 1199.39it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1198.95it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1203.11it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1203.94it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1208.20it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1211.92it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1214.77it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1219.40it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1219.50it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1216.83it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1201.58it/s]

Bootstrapping recall:  98%|█████████▊| 975/1000 [00:00<00:00, 1181.99it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1200.51it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1199.40it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1194.26it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1200.99it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1196.24it/s]

Bootstrapping f1:  60%|██████    | 603/1000 [00:00<00:00, 1181.68it/s]

Bootstrapping f1:  72%|███████▏  | 722/1000 [00:00<00:00, 1167.95it/s]

Bootstrapping f1:  84%|████████▍ | 839/1000 [00:00<00:00, 1158.33it/s]

Bootstrapping f1:  96%|█████████▌| 955/1000 [00:00<00:00, 1154.34it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1170.05it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3526.96it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3458.56it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3443.25it/s]

Processing Simplified Golem — 12 nodes, 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1358.96it/s]

Bootstrapping average_precision:  28%|██▊       | 275/1000 [00:00<00:00, 1374.02it/s]

Bootstrapping average_precision:  42%|████▏     | 415/1000 [00:00<00:00, 1381.88it/s]

Bootstrapping average_precision:  55%|█████▌    | 554/1000 [00:00<00:00, 1376.03it/s]

Bootstrapping average_precision:  69%|██████▉   | 692/1000 [00:00<00:00, 1376.29it/s]

Bootstrapping average_precision:  83%|████████▎ | 830/1000 [00:00<00:00, 1377.07it/s]

Bootstrapping average_precision:  97%|█████████▋| 968/1000 [00:00<00:00, 1376.32it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1375.02it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 848.93it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 861.18it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 870.09it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 868.52it/s]

Bootstrapping roc_auc:  44%|████▎     | 436/1000 [00:00<00:00, 867.41it/s]

Bootstrapping roc_auc:  52%|█████▏    | 524/1000 [00:00<00:00, 870.26it/s]

Bootstrapping roc_auc:  61%|██████    | 612/1000 [00:00<00:00, 871.94it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 871.19it/s]

Bootstrapping roc_auc:  79%|███████▉  | 788/1000 [00:00<00:00, 871.77it/s]

Bootstrapping roc_auc:  88%|████████▊ | 876/1000 [00:01<00:00, 871.30it/s]

Bootstrapping roc_auc:  96%|█████████▋| 964/1000 [00:01<00:00, 871.83it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 869.69it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1204.93it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1195.21it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1201.85it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1206.44it/s]

Bootstrapping precision:  61%|██████    | 606/1000 [00:00<00:00, 1204.85it/s]

Bootstrapping precision:  73%|███████▎  | 727/1000 [00:00<00:00, 1199.73it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1199.67it/s]

Bootstrapping precision:  97%|█████████▋| 969/1000 [00:00<00:00, 1200.01it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1199.80it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1181.28it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1192.92it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1199.79it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1204.53it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1201.18it/s]

Bootstrapping recall:  72%|███████▎  | 725/1000 [00:00<00:00, 1201.25it/s]

Bootstrapping recall:  85%|████████▍ | 846/1000 [00:00<00:00, 1202.71it/s]

Bootstrapping recall:  97%|█████████▋| 967/1000 [00:00<00:00, 1199.83it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1198.65it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1207.69it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1206.87it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1204.19it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1191.78it/s]

Bootstrapping f1:  61%|██████    | 606/1000 [00:00<00:00, 1199.04it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1197.73it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1171.14it/s]

Bootstrapping f1:  96%|█████████▋| 964/1000 [00:00<00:00, 1169.80it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1183.63it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3528.62it/s]

Bootstrapping accuracy:  71%|███████   | 709/1000 [00:00<00:00, 3540.83it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3414.91it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 127/1000 [00:00<00:00, 1267.62it/s]

Bootstrapping average_precision:  26%|██▌       | 258/1000 [00:00<00:00, 1288.73it/s]

Bootstrapping average_precision:  39%|███▉      | 388/1000 [00:00<00:00, 1290.10it/s]

Bootstrapping average_precision:  52%|█████▏    | 518/1000 [00:00<00:00, 1285.36it/s]

Bootstrapping average_precision:  65%|██████▍   | 647/1000 [00:00<00:00, 1282.30it/s]

Bootstrapping average_precision:  78%|███████▊  | 778/1000 [00:00<00:00, 1287.63it/s]

Bootstrapping average_precision:  91%|█████████ | 910/1000 [00:00<00:00, 1296.20it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1290.73it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 828.88it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 822.76it/s]

Bootstrapping roc_auc:  25%|██▍       | 249/1000 [00:00<00:00, 824.25it/s]

Bootstrapping roc_auc:  33%|███▎      | 333/1000 [00:00<00:00, 827.21it/s]

Bootstrapping roc_auc:  42%|████▏     | 417/1000 [00:00<00:00, 827.62it/s]

Bootstrapping roc_auc:  50%|█████     | 500/1000 [00:00<00:00, 828.09it/s]

Bootstrapping roc_auc:  58%|█████▊    | 585/1000 [00:00<00:00, 834.28it/s]

Bootstrapping roc_auc:  67%|██████▋   | 671/1000 [00:00<00:00, 840.75it/s]

Bootstrapping roc_auc:  76%|███████▌  | 758/1000 [00:00<00:00, 848.27it/s]

Bootstrapping roc_auc:  84%|████████▍ | 845/1000 [00:01<00:00, 854.67it/s]

Bootstrapping roc_auc:  93%|█████████▎| 932/1000 [00:01<00:00, 857.50it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 840.45it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1139.83it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1148.53it/s]

Bootstrapping precision:  35%|███▌      | 350/1000 [00:00<00:00, 1170.04it/s]

Bootstrapping precision:  47%|████▋     | 470/1000 [00:00<00:00, 1180.84it/s]

Bootstrapping precision:  59%|█████▉    | 591/1000 [00:00<00:00, 1190.52it/s]

Bootstrapping precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1199.87it/s]

Bootstrapping precision:  84%|████████▎ | 835/1000 [00:00<00:00, 1205.11it/s]

Bootstrapping precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1202.31it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1190.42it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1217.75it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1210.73it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1212.03it/s]

Bootstrapping recall:  49%|████▉     | 489/1000 [00:00<00:00, 1215.38it/s]

Bootstrapping recall:  61%|██████    | 611/1000 [00:00<00:00, 1216.79it/s]

Bootstrapping recall:  73%|███████▎  | 733/1000 [00:00<00:00, 1216.26it/s]

Bootstrapping recall:  86%|████████▌ | 856/1000 [00:00<00:00, 1219.07it/s]

Bootstrapping recall:  98%|█████████▊| 978/1000 [00:00<00:00, 1218.29it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1215.93it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1215.65it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1212.35it/s]

Bootstrapping f1:  37%|███▋      | 367/1000 [00:00<00:00, 1217.88it/s]

Bootstrapping f1:  49%|████▉     | 489/1000 [00:00<00:00, 1217.90it/s]

Bootstrapping f1:  61%|██████    | 611/1000 [00:00<00:00, 1215.15it/s]

Bootstrapping f1:  73%|███████▎  | 733/1000 [00:00<00:00, 1212.36it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1212.08it/s]

Bootstrapping f1:  98%|█████████▊| 977/1000 [00:00<00:00, 1213.39it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1213.25it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3536.75it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3534.34it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3540.48it/s]

Processing Golem $\cup$ PCMB — 48 nodes, 100 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1337.30it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1336.92it/s]

Bootstrapping average_precision:  40%|████      | 403/1000 [00:00<00:00, 1341.20it/s]

Bootstrapping average_precision:  54%|█████▍    | 540/1000 [00:00<00:00, 1350.09it/s]

Bootstrapping average_precision:  68%|██████▊   | 678/1000 [00:00<00:00, 1358.56it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1364.98it/s]

Bootstrapping average_precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1361.50it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1355.60it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 867.39it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 869.23it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 869.53it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 871.09it/s]

Bootstrapping roc_auc:  44%|████▍     | 439/1000 [00:00<00:00, 872.02it/s]

Bootstrapping roc_auc:  53%|█████▎    | 527/1000 [00:00<00:00, 870.98it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 872.42it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 874.13it/s]

Bootstrapping roc_auc:  79%|███████▉  | 791/1000 [00:00<00:00, 873.94it/s]

Bootstrapping roc_auc:  88%|████████▊ | 879/1000 [00:01<00:00, 874.94it/s]

Bootstrapping roc_auc:  97%|█████████▋| 967/1000 [00:01<00:00, 875.49it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 872.92it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1200.65it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1202.10it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1205.88it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1208.30it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1209.65it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1206.12it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1204.79it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1206.89it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1205.86it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1206.15it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1204.34it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1204.73it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1204.84it/s]

Bootstrapping recall:  60%|██████    | 605/1000 [00:00<00:00, 1205.45it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1204.53it/s]

Bootstrapping recall:  85%|████████▍ | 847/1000 [00:00<00:00, 1206.19it/s]

Bootstrapping recall:  97%|█████████▋| 968/1000 [00:00<00:00, 1205.17it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1204.36it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1204.60it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1209.11it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1210.77it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1210.95it/s]

Bootstrapping f1:  61%|██████    | 609/1000 [00:00<00:00, 1209.33it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1208.29it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1209.45it/s]

Bootstrapping f1:  97%|█████████▋| 974/1000 [00:00<00:00, 1210.77it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1209.16it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 358/1000 [00:00<00:00, 3571.75it/s]

Bootstrapping accuracy:  72%|███████▏  | 716/1000 [00:00<00:00, 3566.18it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3562.86it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1348.99it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1348.48it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1348.83it/s]

Bootstrapping average_precision:  54%|█████▍    | 540/1000 [00:00<00:00, 1349.29it/s]

Bootstrapping average_precision:  68%|██████▊   | 676/1000 [00:00<00:00, 1352.68it/s]

Bootstrapping average_precision:  81%|████████  | 812/1000 [00:00<00:00, 1352.76it/s]

Bootstrapping average_precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1347.86it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1347.16it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 859.12it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 862.07it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 864.33it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 861.21it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 861.93it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 862.73it/s]

Bootstrapping roc_auc:  61%|██████    | 608/1000 [00:00<00:00, 864.32it/s]

Bootstrapping roc_auc:  70%|██████▉   | 695/1000 [00:00<00:00, 865.45it/s]

Bootstrapping roc_auc:  78%|███████▊  | 782/1000 [00:00<00:00, 862.31it/s]

Bootstrapping roc_auc:  87%|████████▋ | 869/1000 [00:01<00:00, 864.00it/s]

Bootstrapping roc_auc:  96%|█████████▌| 956/1000 [00:01<00:00, 864.50it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 863.44it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1205.06it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1204.54it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1208.92it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1207.31it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1208.75it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1210.05it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1211.38it/s]

Bootstrapping precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1213.15it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1209.92it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1215.50it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1214.60it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1213.96it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1214.04it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1213.46it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1214.83it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1215.58it/s]

Bootstrapping recall:  98%|█████████▊| 976/1000 [00:00<00:00, 1216.47it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1214.16it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1207.19it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1210.98it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1213.14it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1213.91it/s]

Bootstrapping f1:  61%|██████    | 609/1000 [00:00<00:00, 1213.10it/s]

Bootstrapping f1:  73%|███████▎  | 731/1000 [00:00<00:00, 1215.09it/s]

Bootstrapping f1:  85%|████████▌ | 853/1000 [00:00<00:00, 1214.93it/s]

Bootstrapping f1:  98%|█████████▊| 975/1000 [00:00<00:00, 1212.27it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1212.02it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3551.51it/s]

Bootstrapping accuracy:  71%|███████▏  | 713/1000 [00:00<00:00, 3562.17it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3560.56it/s]

Processing Simplified Golem $\cap$ Simplified PCMB — 6 nodes, 5 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1343.22it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1346.78it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1355.27it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1360.61it/s]

Bootstrapping average_precision:  68%|██████▊   | 682/1000 [00:00<00:00, 1364.50it/s]

Bootstrapping average_precision:  82%|████████▏ | 819/1000 [00:00<00:00, 1364.94it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1368.96it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1362.77it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 871.46it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 869.05it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 872.29it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 874.02it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 872.68it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 870.74it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 869.67it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 858.25it/s]

Bootstrapping roc_auc:  79%|███████▉  | 789/1000 [00:00<00:00, 855.73it/s]

Bootstrapping roc_auc:  88%|████████▊ | 875/1000 [00:01<00:00, 850.66it/s]

Bootstrapping roc_auc:  96%|█████████▌| 961/1000 [00:01<00:00, 851.10it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.65it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1204.09it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1181.76it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1173.16it/s]

Bootstrapping precision:  48%|████▊     | 479/1000 [00:00<00:00, 1174.17it/s]

Bootstrapping precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1162.87it/s]

Bootstrapping precision:  72%|███████▏  | 715/1000 [00:00<00:00, 1168.47it/s]

Bootstrapping precision:  84%|████████▎ | 835/1000 [00:00<00:00, 1177.61it/s]

Bootstrapping precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1184.87it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1175.89it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1193.14it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1197.96it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1203.68it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1206.08it/s]

Bootstrapping recall:  60%|██████    | 605/1000 [00:00<00:00, 1204.71it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1198.36it/s]

Bootstrapping recall:  85%|████████▍ | 846/1000 [00:00<00:00, 1192.71it/s]

Bootstrapping recall:  97%|█████████▋| 968/1000 [00:00<00:00, 1200.13it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1199.28it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1205.24it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1207.61it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1206.96it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1207.45it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1206.47it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1206.85it/s]

Bootstrapping f1:  85%|████████▍ | 848/1000 [00:00<00:00, 1208.01it/s]

Bootstrapping f1:  97%|█████████▋| 969/1000 [00:00<00:00, 1207.58it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1206.44it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3534.66it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3554.63it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3546.19it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1355.03it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1354.75it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1357.10it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1357.75it/s]

Bootstrapping average_precision:  68%|██████▊   | 680/1000 [00:00<00:00, 1355.43it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1356.33it/s]

Bootstrapping average_precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1357.57it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1355.88it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 854.99it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 851.46it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 847.15it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 848.79it/s]

Bootstrapping roc_auc:  43%|████▎     | 430/1000 [00:00<00:00, 850.27it/s]

Bootstrapping roc_auc:  52%|█████▏    | 516/1000 [00:00<00:00, 852.52it/s]

Bootstrapping roc_auc:  60%|██████    | 602/1000 [00:00<00:00, 853.14it/s]

Bootstrapping roc_auc:  69%|██████▉   | 689/1000 [00:00<00:00, 856.38it/s]

Bootstrapping roc_auc:  78%|███████▊  | 776/1000 [00:00<00:00, 859.41it/s]

Bootstrapping roc_auc:  86%|████████▋ | 863/1000 [00:01<00:00, 860.86it/s]

Bootstrapping roc_auc:  95%|█████████▌| 950/1000 [00:01<00:00, 861.48it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 856.42it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1205.80it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1208.67it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1206.91it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1210.40it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1204.10it/s]

Bootstrapping precision:  73%|███████▎  | 730/1000 [00:00<00:00, 1206.76it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1201.51it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1196.31it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1200.27it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1177.69it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1185.42it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1199.71it/s]

Bootstrapping recall:  48%|████▊     | 482/1000 [00:00<00:00, 1206.31it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1208.92it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1212.07it/s]

Bootstrapping recall:  85%|████████▍ | 848/1000 [00:00<00:00, 1211.18it/s]

Bootstrapping recall:  97%|█████████▋| 970/1000 [00:00<00:00, 1193.05it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1196.73it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1170.63it/s]

Bootstrapping f1:  24%|██▍       | 239/1000 [00:00<00:00, 1192.16it/s]

Bootstrapping f1:  36%|███▌      | 361/1000 [00:00<00:00, 1200.76it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1205.10it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1207.29it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1200.62it/s]

Bootstrapping f1:  85%|████████▍ | 847/1000 [00:00<00:00, 1197.83it/s]

Bootstrapping f1:  97%|█████████▋| 968/1000 [00:00<00:00, 1201.23it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1199.75it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3542.38it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3554.92it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3556.28it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem — 5 nodes, 4 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1367.69it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1366.82it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1367.92it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1367.68it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1367.93it/s]

Bootstrapping average_precision:  82%|████████▏ | 823/1000 [00:00<00:00, 1369.32it/s]

Bootstrapping average_precision:  96%|█████████▌| 960/1000 [00:00<00:00, 1366.55it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1366.21it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 842.91it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 844.02it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 847.82it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 858.27it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 863.59it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 867.95it/s]

Bootstrapping roc_auc:  61%|██████    | 608/1000 [00:00<00:00, 870.45it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 872.23it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 873.51it/s]

Bootstrapping roc_auc:  87%|████████▋ | 872/1000 [00:01<00:00, 873.41it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 872.72it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.86it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1185.05it/s]

Bootstrapping precision:  24%|██▍       | 239/1000 [00:00<00:00, 1191.57it/s]

Bootstrapping precision:  36%|███▌      | 360/1000 [00:00<00:00, 1199.72it/s]

Bootstrapping precision:  48%|████▊     | 480/1000 [00:00<00:00, 1195.72it/s]

Bootstrapping precision:  60%|██████    | 600/1000 [00:00<00:00, 1167.80it/s]

Bootstrapping precision:  72%|███████▏  | 719/1000 [00:00<00:00, 1172.29it/s]

Bootstrapping precision:  84%|████████▎ | 837/1000 [00:00<00:00, 1171.59it/s]

Bootstrapping precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1167.08it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1175.51it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1192.33it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1197.20it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1203.20it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1205.27it/s]

Bootstrapping recall:  60%|██████    | 605/1000 [00:00<00:00, 1204.08it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1204.97it/s]

Bootstrapping recall:  85%|████████▍ | 847/1000 [00:00<00:00, 1205.43it/s]

Bootstrapping recall:  97%|█████████▋| 968/1000 [00:00<00:00, 1204.87it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1202.75it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1192.15it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1199.30it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1200.45it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1199.49it/s]

Bootstrapping f1:  60%|██████    | 603/1000 [00:00<00:00, 1196.00it/s]

Bootstrapping f1:  72%|███████▏  | 723/1000 [00:00<00:00, 1194.24it/s]

Bootstrapping f1:  84%|████████▍ | 843/1000 [00:00<00:00, 1186.87it/s]

Bootstrapping f1:  96%|█████████▋| 963/1000 [00:00<00:00, 1189.43it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1192.32it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3534.05it/s]

Bootstrapping accuracy:  71%|███████   | 709/1000 [00:00<00:00, 3540.93it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3535.76it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 130/1000 [00:00<00:00, 1299.06it/s]

Bootstrapping average_precision:  26%|██▌       | 260/1000 [00:00<00:00, 1287.01it/s]

Bootstrapping average_precision:  39%|███▉      | 392/1000 [00:00<00:00, 1298.98it/s]

Bootstrapping average_precision:  52%|█████▎    | 525/1000 [00:00<00:00, 1308.30it/s]

Bootstrapping average_precision:  66%|██████▌   | 661/1000 [00:00<00:00, 1323.45it/s]

Bootstrapping average_precision:  80%|███████▉  | 797/1000 [00:00<00:00, 1335.70it/s]

Bootstrapping average_precision:  93%|█████████▎| 933/1000 [00:00<00:00, 1343.20it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1327.37it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 854.17it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 853.61it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 858.50it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 851.12it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 853.70it/s]

Bootstrapping roc_auc:  52%|█████▏    | 518/1000 [00:00<00:00, 856.63it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 861.03it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 863.30it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 865.09it/s]

Bootstrapping roc_auc:  87%|████████▋ | 867/1000 [00:01<00:00, 864.73it/s]

Bootstrapping roc_auc:  95%|█████████▌| 954/1000 [00:01<00:00, 865.50it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.99it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1213.11it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1215.07it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1215.93it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1215.20it/s]

Bootstrapping precision:  61%|██████    | 610/1000 [00:00<00:00, 1210.36it/s]

Bootstrapping precision:  73%|███████▎  | 732/1000 [00:00<00:00, 1212.62it/s]

Bootstrapping precision:  85%|████████▌ | 854/1000 [00:00<00:00, 1212.75it/s]

Bootstrapping precision:  98%|█████████▊| 976/1000 [00:00<00:00, 1209.67it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1211.25it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1183.70it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1179.93it/s]

Bootstrapping recall:  36%|███▌      | 359/1000 [00:00<00:00, 1190.09it/s]

Bootstrapping recall:  48%|████▊     | 481/1000 [00:00<00:00, 1199.91it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1194.60it/s]

Bootstrapping recall:  72%|███████▏  | 721/1000 [00:00<00:00, 1185.00it/s]

Bootstrapping recall:  84%|████████▍ | 841/1000 [00:00<00:00, 1189.13it/s]

Bootstrapping recall:  96%|█████████▌| 962/1000 [00:00<00:00, 1192.97it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1189.65it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1195.31it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1203.30it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1208.60it/s]

Bootstrapping f1:  48%|████▊     | 485/1000 [00:00<00:00, 1211.90it/s]

Bootstrapping f1:  61%|██████    | 607/1000 [00:00<00:00, 1213.31it/s]

Bootstrapping f1:  73%|███████▎  | 729/1000 [00:00<00:00, 1211.91it/s]

Bootstrapping f1:  85%|████████▌ | 851/1000 [00:00<00:00, 1213.51it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1214.70it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1210.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3555.41it/s]

Bootstrapping accuracy:  71%|███████▏  | 714/1000 [00:00<00:00, 3565.90it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3560.71it/s]

In [11]:
df2 = pd.DataFrame(results2)
df2.to_csv('Generative LGBN - No Drugs.csv', index=False)
df2

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,Generative LGBN,Control,"0.48 (0.44, 0.53)","0.84 (0.82, 0.86)","0.76 (0.74, 0.78)","0.78 (0.76, 0.80)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.121,624,34
1,XGB,Control,"0.80 (0.77, 0.83)","0.92 (0.91, 0.94)","0.92 (0.90, 0.94)","0.80 (0.78, 0.82)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.090,624,34
2,Generative LGBN,Correlation,"0.54 (0.49, 0.59)","0.81 (0.78, 0.83)","0.82 (0.80, 0.85)","0.74 (0.72, 0.77)","0.77 (0.75, 0.79)","0.92 (0.91, 0.93)",0.080,70,26
3,XGB,Correlation,"0.75 (0.71, 0.79)","0.89 (0.87, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.82 (0.80, 0.85)","0.94 (0.93, 0.95)",0.111,70,26
4,Generative LGBN,Clinician Consensus $\cup$ Golem,"0.54 (0.49, 0.58)","0.84 (0.82, 0.87)","0.77 (0.75, 0.80)","0.77 (0.75, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.108,134,15
5,XGB,Clinician Consensus $\cup$ Golem,"0.77 (0.73, 0.80)","0.90 (0.88, 0.92)","0.91 (0.89, 0.93)","0.80 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.100,134,15
6,Generative LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.52 (0.47, 0.56)","0.85 (0.83, 0.87)","0.77 (0.75, 0.79)","0.77 (0.74, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.110,198,11
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.77 (0.74, 0.81)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.81)","0.84 (0.81, 0.86)","0.94 (0.94, 0.95)",0.100,198,11
8,Generative LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.50 (0.46, 0.56)","0.85 (0.82, 0.87)","0.76 (0.74, 0.79)","0.77 (0.75, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.114,271,15
9,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.77 (0.74, 0.81)","0.91 (0.89, 0.93)","0.91 (0.89, 0.92)","0.80 (0.78, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.099,271,15
10,Generative LGBN,Clinician Consensus $\cup$ PCMB,"0.52 (0.48, 0.57)","0.84 (0.82, 0.87)","0.77 (0.74, 0.79)","0.76 (0.74, 0.79)","0.77 (0.74, 0.79)","0.91 (0.90, 0.92)",0.110,130,12
11,XGB,Clinician Consensus $\cup$ PCMB,"0.76 (0.73, 0.80)","0.90 (0.88, 0.92)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.099,130,12
12,Generative LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.49 (0.44, 0.53)","0.84 (0.82, 0.87)","0.75 (0.73, 0.78)","0.76 (0.74, 0.78)","0.76 (0.74, 0.78)","0.90 (0.89, 0.91)",0.115,271,15
13,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.096,271,15
14,Generative LGBN,Clinician Consensus,"0.53 (0.49, 0.58)","0.84 (0.82, 0.86)","0.77 (0.75, 0.79)","0.77 (0.74, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.109,126,9
15,XGB,Clinician Consensus,"0.76 (0.73, 0.80)","0.90 (0.88, 0.92)","0.89 (0.87, 0.91)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.101,126,9
16,Generative LGBN,Simplified Clinician Consensus,"0.53 (0.48, 0.57)","0.84 (0.82, 0.87)","0.77 (0.75, 0.79)","0.77 (0.74, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.111,160,9
17,XGB,Simplified Clinician Consensus,"0.75 (0.72, 0.79)","0.90 (0.88, 0.92)","0.91 (0.90, 0.93)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.100,160,9
18,Generative LGBN,Clinician Consensus $\cap$ PCMB,"0.57 (0.52, 0.61)","0.80 (0.77, 0.83)","0.77 (0.75, 0.80)","0.74 (0.71, 0.76)","0.75 (0.73, 0.77)","0.91 (0.90, 0.92)",0.098,14,8
19,XGB,Clinician Consensus $\cap$ PCMB,"0.66 (0.62, 0.70)","0.84 (0.82, 0.86)","0.87 (0.84, 0.89)","0.74 (0.72, 0.77)","0.79 (0.77, 0.81)","0.93 (0.92, 0.94)",0.123,14,8
20,Generative LGBN,Golem,"0.26 (0.22, 0.30)","0.70 (0.68, 0.73)","0.63 (0.59, 0.66)","0.56 (0.54, 0.58)","0.57 (0.55, 0.60)","0.88 (0.87, 0.89)",0.051,15,10
21,XGB,Golem,"0.54 (0.50, 0.59)","0.84 (0.82, 0.86)","0.77 (0.74, 0.80)","0.68 (0.66, 0.70)","0.71 (0.69, 0.73)","0.91 (0.90, 0.91)",0.115,15,10
22,Generative LGBN,PCMB,"0.56 (0.51, 0.61)","0.81 (0.79, 0.84)","0.75 (0.72, 0.77)","0.74 (0.71, 0.76)","0.74 (0.72, 0.76)","0.90 (0.89, 0.91)",0.109,18,11
23,XGB,PCMB,"0.69 (0.65, 0.73)","0.87 (0.85, 0.89)","0.87 (0.84, 0.89)","0.75 (0.73, 0.77)","0.79 (0.77, 0.82)","0.93 (0.92, 0.94)",0.120,18,11
24,Generative LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.52 (0.48, 0.57)","0.84 (0.82, 0.87)","0.77 (0.75, 0.79)","0.77 (0.75, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.111,141,8
25,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.91 (0.89, 0.93)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.100,141,8
26,Generative LGBN,Simplified PCMB,"0.51 (0.47, 0.56)","0.85 (0.83, 0.87)","0.76 (0.74, 0.79)","0.76 (0.74, 0.79)","0.76 (0.74, 0.78)","0.91 (0.90, 0.92)",0.110,179,10
27,XGB,Simplified PCMB,"0.78 (0.75, 0.81)","0.91 (0.89, 0.93)","0.92 (0.90, 0.93)","0.80 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.101,179,10
28,Generative LGBN,Clinician Consensus $\cap$ Golem,"0.18 (0.15, 0.21)","0.55 (0.52, 0.58)","0.63 (0.59, 0.67)","0.54 (0.52, 0.55)","0.55 (0.52, 0.57)","0.88 (0.87, 0.89)",0.189,7,4
29,XGB,Clinician Consensus $\cap$ Golem,"0.25 (0.21, 0.29)","0.65 (0.62, 0.68)","0.70 (0.65, 0.74)","0.56 (0.54, 0.57)","0.57 (0.55, 0.59)","0.89 (0.88, 0.90)",0.124,7,4
30,Generative LGBN,Simplified Golem,"0.52 (0.48, 0.57)","0.85 (0.83, 0.87)","0.76 (0.74, 0.78)","0.77 (0.75, 0.80)","0.77 (0.75, 0.79)","0.90 (0.90, 0.91)",0.119,180,10
31,XGB,Simplified Golem,"0.78 (0.75, 0.81)","0.92 (0.90, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.098,180,10
32,Generative LGBN,Golem $\cup$ PCMB,"0.55 (0.51, 0.60)","0.84 (0.81, 0.86)","0.76 (0.74, 0.79)","0.75 (0.73, 0.77)","0.76 (0.74, 0.78)","0.91 (0.90, 0.91)",0.106,33,16
33,XGB,Golem $\cup$ PCMB,"0.73 (0.69, 0.77)","0.90 (0.88, 0.91)","0.88 (0.86, 0.90)","0.77 (0.75, 0.80)","0.82 (0.79, 0.84)","0.94 (0.93, 0.95)",0.109,33,16
34,Generative LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.55 (0.51, 0.60)","0.85 (0.82, 0.87)","0.78 (0.76, 0.80)","0.76 (0.74, 0.78)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.101,88,5
35,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.76 (0.73, 0.80)","0.90 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,88,5
36,Generative LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.57 (0.52, 0.61)","0.85 (0.82, 0.87)","0.78 (0.76, 0.81)","0.76 (0.74, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.102,69,4
37,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.76, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.106,69,4

In [12]:
aurocs2, auprcs2 = [], []
for dag_name, preds in model_preds2.items():
    (z, p_delong), perm = compare_models(y_test.Outcome, preds['Generative LGBN'], preds['XGB'])
    aurocs2.append({'DAG': dag_name, 'Z-score': f"{z:.4f}", 'P-value': f"{p_delong:.3e}"})
    auprcs2.append({'DAG': dag_name,
                    'Avg Precision LGBN': f"{perm[0]:.4f}",
                    'Avg Precision XGB':  f"{perm[1]:.4f}",
                    'P-value': f"{perm[2]:.3e}"})

pd.DataFrame(aurocs2).to_csv('Generative LGBN - delong_no_drugs_auroc.csv', index=False)
pd.DataFrame(auprcs2).to_csv('Generative LGBN - delong_no_drugs_auprc.csv', index=False)
pd.DataFrame(aurocs2)

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 729.45it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 727.35it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 728.00it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 724.82it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 718.21it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 720.18it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 512/1000 [00:00<00:00, 723.65it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 586/1000 [00:00<00:00, 726.09it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 659/1000 [00:00<00:00, 725.52it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 732/1000 [00:01<00:00, 726.33it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 806/1000 [00:01<00:00, 728.15it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 879/1000 [00:01<00:00, 728.18it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 952/1000 [00:01<00:00, 727.08it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 725.80it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 726.94it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 727.16it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 727.37it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 727.39it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 728.08it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 727.93it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 512/1000 [00:00<00:00, 728.91it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 585/1000 [00:00<00:00, 729.03it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 659/1000 [00:00<00:00, 730.11it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 733/1000 [00:01<00:00, 729.36it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 806/1000 [00:01<00:00, 725.42it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 879/1000 [00:01<00:00, 721.08it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 952/1000 [00:01<00:00, 723.56it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 726.01it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 726.71it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 727.54it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 220/1000 [00:00<00:01, 729.86it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 294/1000 [00:00<00:00, 730.46it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 368/1000 [00:00<00:00, 730.06it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 442/1000 [00:00<00:00, 730.53it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 516/1000 [00:00<00:00, 730.60it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 590/1000 [00:00<00:00, 731.26it/s]

Computing average_precision Permutation Test p-value:  66%|██████▋   | 664/1000 [00:00<00:00, 727.57it/s]

Computing average_precision Permutation Test p-value:  74%|███████▍  | 738/1000 [00:01<00:00, 728.50it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 811/1000 [00:01<00:00, 728.76it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 885/1000 [00:01<00:00, 729.46it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 959/1000 [00:01<00:00, 730.54it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 729.54it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 731.10it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 728.68it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 221/1000 [00:00<00:01, 727.56it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 294/1000 [00:00<00:00, 728.30it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 367/1000 [00:00<00:00, 728.20it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 728.15it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 728.18it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 586/1000 [00:00<00:00, 728.59it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 659/1000 [00:00<00:00, 727.91it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 733/1000 [00:01<00:00, 729.13it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 806/1000 [00:01<00:00, 728.82it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 880/1000 [00:01<00:00, 729.85it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 953/1000 [00:01<00:00, 729.41it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 728.77it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 736.30it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 735.44it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 734.20it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 731.61it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 370/1000 [00:00<00:00, 730.21it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 444/1000 [00:00<00:00, 730.92it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 518/1000 [00:00<00:00, 731.56it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 592/1000 [00:00<00:00, 731.87it/s]

Computing average_precision Permutation Test p-value:  67%|██████▋   | 666/1000 [00:00<00:00, 733.11it/s]

Computing average_precision Permutation Test p-value:  74%|███████▍  | 740/1000 [00:01<00:00, 733.78it/s]

Computing average_precision Permutation Test p-value:  81%|████████▏ | 814/1000 [00:01<00:00, 732.77it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 888/1000 [00:01<00:00, 733.60it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 962/1000 [00:01<00:00, 732.62it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 732.54it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 708.17it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 719.40it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 725.45it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 728.49it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 366/1000 [00:00<00:00, 729.77it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 729.96it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 728.39it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 586/1000 [00:00<00:00, 727.54it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 659/1000 [00:00<00:00, 727.02it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 733/1000 [00:01<00:00, 728.13it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 806/1000 [00:01<00:00, 727.82it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 880/1000 [00:01<00:00, 728.48it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 954/1000 [00:01<00:00, 728.99it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 727.63it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 729.61it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 147/1000 [00:00<00:01, 729.61it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 220/1000 [00:00<00:01, 729.58it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 293/1000 [00:00<00:00, 728.89it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 366/1000 [00:00<00:00, 725.67it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 439/1000 [00:00<00:00, 725.41it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 727.09it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 587/1000 [00:00<00:00, 727.83it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 661/1000 [00:00<00:00, 729.22it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 735/1000 [00:01<00:00, 730.27it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 809/1000 [00:01<00:00, 729.96it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 883/1000 [00:01<00:00, 730.76it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 957/1000 [00:01<00:00, 731.23it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 729.15it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 731.12it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 728.57it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 221/1000 [00:00<00:01, 728.93it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 294/1000 [00:00<00:00, 729.34it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 367/1000 [00:00<00:00, 729.02it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 441/1000 [00:00<00:00, 729.46it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 515/1000 [00:00<00:00, 730.97it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 589/1000 [00:00<00:00, 731.68it/s]

Computing average_precision Permutation Test p-value:  66%|██████▋   | 663/1000 [00:00<00:00, 731.66it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 737/1000 [00:01<00:00, 730.96it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 811/1000 [00:01<00:00, 731.31it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 885/1000 [00:01<00:00, 730.41it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 959/1000 [00:01<00:00, 730.64it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 730.27it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 729.13it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 147/1000 [00:00<00:01, 729.49it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 220/1000 [00:00<00:01, 729.00it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 293/1000 [00:00<00:00, 728.22it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 366/1000 [00:00<00:00, 728.32it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 729.05it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 514/1000 [00:00<00:00, 729.43it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 588/1000 [00:00<00:00, 731.34it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 662/1000 [00:00<00:00, 731.39it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 736/1000 [00:01<00:00, 730.60it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 810/1000 [00:01<00:00, 731.14it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 884/1000 [00:01<00:00, 730.74it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 958/1000 [00:01<00:00, 722.35it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 727.03it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 713.83it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 712.94it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 713.38it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 289/1000 [00:00<00:00, 716.95it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 362/1000 [00:00<00:00, 720.98it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 435/1000 [00:00<00:00, 721.60it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 508/1000 [00:00<00:00, 720.45it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 581/1000 [00:00<00:00, 721.51it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 654/1000 [00:00<00:00, 720.83it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 727/1000 [00:01<00:00, 715.07it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 799/1000 [00:01<00:00, 716.04it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 872/1000 [00:01<00:00, 718.27it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 945/1000 [00:01<00:00, 721.05it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 719.23it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 725.08it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 725.34it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 725.49it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 726.02it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 725.04it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 722.74it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 511/1000 [00:00<00:00, 722.84it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 584/1000 [00:00<00:00, 723.67it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 657/1000 [00:00<00:00, 724.06it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 730/1000 [00:01<00:00, 725.80it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 803/1000 [00:01<00:00, 725.68it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 876/1000 [00:01<00:00, 725.76it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 949/1000 [00:01<00:00, 726.19it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 724.99it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 730.98it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 727.71it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 221/1000 [00:00<00:01, 728.14it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 294/1000 [00:00<00:00, 727.27it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 367/1000 [00:00<00:00, 727.97it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 728.17it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 727.37it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 586/1000 [00:00<00:00, 723.13it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 659/1000 [00:00<00:00, 721.17it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 732/1000 [00:01<00:00, 723.26it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 805/1000 [00:01<00:00, 724.07it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 878/1000 [00:01<00:00, 725.45it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 951/1000 [00:01<00:00, 724.33it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 724.87it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 730.13it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 727.88it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 221/1000 [00:00<00:01, 728.32it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 294/1000 [00:00<00:00, 727.93it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 367/1000 [00:00<00:00, 728.28it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 441/1000 [00:00<00:00, 729.18it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 514/1000 [00:00<00:00, 729.20it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 588/1000 [00:00<00:00, 731.44it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 662/1000 [00:00<00:00, 732.05it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 736/1000 [00:01<00:00, 730.62it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 810/1000 [00:01<00:00, 730.22it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 884/1000 [00:01<00:00, 728.39it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 957/1000 [00:01<00:00, 727.89it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 728.90it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 724.64it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 724.29it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 723.40it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 722.87it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 724.30it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 722.63it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 512/1000 [00:00<00:00, 725.42it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 585/1000 [00:00<00:00, 726.61it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 658/1000 [00:00<00:00, 727.19it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 731/1000 [00:01<00:00, 727.24it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 805/1000 [00:01<00:00, 728.21it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 878/1000 [00:01<00:00, 723.61it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 951/1000 [00:01<00:00, 724.24it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 724.67it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 724.31it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 719.89it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 719.49it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 290/1000 [00:00<00:00, 719.33it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 363/1000 [00:00<00:00, 719.77it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 436/1000 [00:00<00:00, 721.29it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 509/1000 [00:00<00:00, 723.50it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 582/1000 [00:00<00:00, 723.67it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 655/1000 [00:00<00:00, 724.70it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 728/1000 [00:01<00:00, 724.21it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 801/1000 [00:01<00:00, 723.96it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 874/1000 [00:01<00:00, 722.38it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 947/1000 [00:01<00:00, 722.15it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 722.28it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 727.87it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 728.49it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 725.28it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 722.49it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 719.47it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 721.57it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 511/1000 [00:00<00:00, 724.21it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 585/1000 [00:00<00:00, 726.27it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 658/1000 [00:00<00:00, 727.13it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 731/1000 [00:01<00:00, 727.92it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 804/1000 [00:01<00:00, 728.33it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 878/1000 [00:01<00:00, 729.45it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 952/1000 [00:01<00:00, 729.46it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 726.78it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 729.99it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 724.77it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 723.41it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 723.27it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 724.78it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 724.10it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 511/1000 [00:00<00:00, 724.88it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 584/1000 [00:00<00:00, 726.10it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 657/1000 [00:00<00:00, 726.54it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 731/1000 [00:01<00:00, 727.73it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 805/1000 [00:01<00:00, 729.44it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 879/1000 [00:01<00:00, 729.84it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 952/1000 [00:01<00:00, 728.62it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 726.53it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 731.63it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 729.98it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 221/1000 [00:00<00:01, 728.80it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 295/1000 [00:00<00:00, 730.20it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 369/1000 [00:00<00:00, 728.60it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 442/1000 [00:00<00:00, 728.61it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 515/1000 [00:00<00:00, 727.73it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 588/1000 [00:00<00:00, 727.13it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 661/1000 [00:00<00:00, 727.57it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 735/1000 [00:01<00:00, 728.79it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 808/1000 [00:01<00:00, 728.54it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 882/1000 [00:01<00:00, 729.98it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 956/1000 [00:01<00:00, 730.55it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 729.37it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 732.21it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 731.63it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 731.08it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 729.95it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 369/1000 [00:00<00:00, 728.99it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 443/1000 [00:00<00:00, 729.27it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 516/1000 [00:00<00:00, 729.44it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 589/1000 [00:00<00:00, 729.36it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 662/1000 [00:00<00:00, 728.37it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 735/1000 [00:01<00:00, 728.41it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 808/1000 [00:01<00:00, 728.74it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 881/1000 [00:01<00:00, 727.69it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 954/1000 [00:01<00:00, 728.20it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 728.85it/s]

                                                  DAG Z-score    P-value
0                                             Control  7.9325  2.149e-15
1                                         Correlation  6.7043  2.023e-11
2                    Clinician Consensus $\cup$ Golem  5.6721  1.410e-08
3   Simplified Clinician Consensus $\cup$ Simplifi...  5.7669  8.074e-09
4   Simplified Clinician Consensus $\cup$ Simplifi...  6.0204  1.740e-09
5                     Clinician Consensus $\cup$ PCMB  5.5715  2.526e-08
6             Simplified Golem $\cup$ Simplified PCMB  6.3830  1.737e-10
7                                 Clinician Consensus  5.6888  1.280e-08
8                      Simplified Clinician Consensus  5.0814  3.747e-07
9                     Clinician Consensus $\cap$ PCMB  3.5034  4.593e-04
10                                              Golem  8.8807  6.646e-19
11                                               PCMB  5.1015  3.370e-07
12  Simplified Clinician Consensus $\cap$ Simplifi...  6.1316  8.702e-10
13                                    Simplified PCMB  6.3266  2.506e-10
14                   Clinician Consensus $\cap$ Golem  5.0653  4.077e-07
15                                   Simplified Golem  6.3973  1.581e-10
16                                  Golem $\cup$ PCMB  5.9383  2.880e-09
17            Simplified Golem $\cap$ Simplified PCMB  5.5593  2.709e-08
18  Simplified Clinician Consensus $\cap$ Simplifi...  3.7647  1.667e-04

## Experiment 3: No drugs or interventions

In [13]:
results3, calibrations3, model_preds3 = train_models(remove_drugs=True, remove_interventions=True)

Processing Control — 46 nodes, 45 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1366.55it/s]

Bootstrapping average_precision:  28%|██▊       | 275/1000 [00:00<00:00, 1373.45it/s]

Bootstrapping average_precision:  42%|████▏     | 415/1000 [00:00<00:00, 1381.32it/s]

Bootstrapping average_precision:  55%|█████▌    | 554/1000 [00:00<00:00, 1381.26it/s]

Bootstrapping average_precision:  69%|██████▉   | 693/1000 [00:00<00:00, 1384.26it/s]

Bootstrapping average_precision:  83%|████████▎ | 833/1000 [00:00<00:00, 1386.27it/s]

Bootstrapping average_precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1371.12it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1374.79it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 837.12it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:01, 830.54it/s]

Bootstrapping roc_auc:  25%|██▌       | 252/1000 [00:00<00:00, 822.08it/s]

Bootstrapping roc_auc:  34%|███▍      | 338/1000 [00:00<00:00, 835.75it/s]

Bootstrapping roc_auc:  43%|████▎     | 426/1000 [00:00<00:00, 850.23it/s]

Bootstrapping roc_auc:  51%|█████▏    | 514/1000 [00:00<00:00, 857.32it/s]

Bootstrapping roc_auc:  60%|██████    | 601/1000 [00:00<00:00, 859.08it/s]

Bootstrapping roc_auc:  69%|██████▉   | 689/1000 [00:00<00:00, 863.91it/s]

Bootstrapping roc_auc:  78%|███████▊  | 777/1000 [00:00<00:00, 868.15it/s]

Bootstrapping roc_auc:  86%|████████▋ | 864/1000 [00:01<00:00, 868.48it/s]

Bootstrapping roc_auc:  95%|█████████▌| 952/1000 [00:01<00:00, 870.78it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 858.27it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 117/1000 [00:00<00:00, 1169.74it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1175.74it/s]

Bootstrapping precision:  36%|███▌      | 355/1000 [00:00<00:00, 1177.32it/s]

Bootstrapping precision:  48%|████▊     | 476/1000 [00:00<00:00, 1186.87it/s]

Bootstrapping precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1194.31it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1196.19it/s]

Bootstrapping precision:  84%|████████▎ | 837/1000 [00:00<00:00, 1197.34it/s]

Bootstrapping precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1199.90it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1192.08it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1208.87it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1184.48it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1193.68it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1198.00it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1197.96it/s]

Bootstrapping recall:  72%|███████▏  | 724/1000 [00:00<00:00, 1196.27it/s]

Bootstrapping recall:  84%|████████▍ | 844/1000 [00:00<00:00, 1189.64it/s]

Bootstrapping recall:  96%|█████████▋| 965/1000 [00:00<00:00, 1194.62it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1194.56it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1184.88it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1174.96it/s]

Bootstrapping f1:  36%|███▌      | 358/1000 [00:00<00:00, 1184.04it/s]

Bootstrapping f1:  48%|████▊     | 479/1000 [00:00<00:00, 1190.92it/s]

Bootstrapping f1:  60%|█████▉    | 599/1000 [00:00<00:00, 1180.36it/s]

Bootstrapping f1:  72%|███████▏  | 718/1000 [00:00<00:00, 1171.92it/s]

Bootstrapping f1:  84%|████████▎ | 837/1000 [00:00<00:00, 1177.43it/s]

Bootstrapping f1:  96%|█████████▌| 955/1000 [00:00<00:00, 1177.07it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1178.71it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 349/1000 [00:00<00:00, 3480.85it/s]

Bootstrapping accuracy:  70%|███████   | 700/1000 [00:00<00:00, 3497.65it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3510.08it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1316.10it/s]

Bootstrapping average_precision:  26%|██▋       | 265/1000 [00:00<00:00, 1320.60it/s]

Bootstrapping average_precision:  40%|███▉      | 398/1000 [00:00<00:00, 1315.69it/s]

Bootstrapping average_precision:  53%|█████▎    | 532/1000 [00:00<00:00, 1321.87it/s]

Bootstrapping average_precision:  67%|██████▋   | 667/1000 [00:00<00:00, 1330.20it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 1339.78it/s]

Bootstrapping average_precision:  94%|█████████▍| 939/1000 [00:00<00:00, 1344.75it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1335.03it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 858.97it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 859.91it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 845.49it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 833.75it/s]

Bootstrapping roc_auc:  43%|████▎     | 428/1000 [00:00<00:00, 833.75it/s]

Bootstrapping roc_auc:  51%|█████▏    | 513/1000 [00:00<00:00, 838.37it/s]

Bootstrapping roc_auc:  60%|██████    | 600/1000 [00:00<00:00, 846.58it/s]

Bootstrapping roc_auc:  69%|██████▊   | 687/1000 [00:00<00:00, 852.84it/s]

Bootstrapping roc_auc:  77%|███████▋  | 774/1000 [00:00<00:00, 856.47it/s]

Bootstrapping roc_auc:  86%|████████▌ | 860/1000 [00:01<00:00, 856.55it/s]

Bootstrapping roc_auc:  95%|█████████▍| 946/1000 [00:01<00:00, 855.79it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 850.19it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1209.42it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1215.20it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1213.77it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1210.28it/s]

Bootstrapping precision:  61%|██████    | 609/1000 [00:00<00:00, 1197.28it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1196.56it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1188.75it/s]

Bootstrapping precision:  97%|█████████▋| 970/1000 [00:00<00:00, 1194.68it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1198.95it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1217.32it/s]

Bootstrapping recall:  24%|██▍       | 245/1000 [00:00<00:00, 1219.11it/s]

Bootstrapping recall:  37%|███▋      | 368/1000 [00:00<00:00, 1220.46it/s]

Bootstrapping recall:  49%|████▉     | 491/1000 [00:00<00:00, 1219.21it/s]

Bootstrapping recall:  61%|██████▏   | 613/1000 [00:00<00:00, 1209.64it/s]

Bootstrapping recall:  73%|███████▎  | 734/1000 [00:00<00:00, 1201.27it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1199.46it/s]

Bootstrapping recall:  98%|█████████▊| 975/1000 [00:00<00:00, 1199.55it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1206.13it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1206.96it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1212.18it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1215.68it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1220.58it/s]

Bootstrapping f1:  61%|██████    | 611/1000 [00:00<00:00, 1205.81it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1206.56it/s]

Bootstrapping f1:  85%|████████▌ | 853/1000 [00:00<00:00, 1197.76it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1196.48it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1202.41it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 343/1000 [00:00<00:00, 3427.57it/s]

Bootstrapping accuracy:  70%|██████▉   | 695/1000 [00:00<00:00, 3476.30it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3485.23it/s]

Processing Correlation — 38 nodes, 37 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 139/1000 [00:00<00:00, 1383.87it/s]

Bootstrapping average_precision:  28%|██▊       | 278/1000 [00:00<00:00, 1371.02it/s]

Bootstrapping average_precision:  42%|████▏     | 416/1000 [00:00<00:00, 1366.81it/s]

Bootstrapping average_precision:  55%|█████▌    | 553/1000 [00:00<00:00, 1365.13it/s]

Bootstrapping average_precision:  69%|██████▉   | 690/1000 [00:00<00:00, 1355.18it/s]

Bootstrapping average_precision:  83%|████████▎ | 826/1000 [00:00<00:00, 1354.16it/s]

Bootstrapping average_precision:  96%|█████████▋| 963/1000 [00:00<00:00, 1357.65it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1358.90it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 869.27it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 869.45it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 868.56it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 864.87it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 858.77it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 858.61it/s]

Bootstrapping roc_auc:  61%|██████    | 608/1000 [00:00<00:00, 861.47it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 865.17it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 868.62it/s]

Bootstrapping roc_auc:  87%|████████▋ | 872/1000 [00:01<00:00, 871.71it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 872.01it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 867.23it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1211.81it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1210.01it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1213.87it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1210.95it/s]

Bootstrapping precision:  61%|██████    | 610/1000 [00:00<00:00, 1210.21it/s]

Bootstrapping precision:  73%|███████▎  | 733/1000 [00:00<00:00, 1213.56it/s]

Bootstrapping precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1213.03it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1214.05it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1211.90it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1212.32it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1207.55it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1208.95it/s]

Bootstrapping recall:  49%|████▊     | 487/1000 [00:00<00:00, 1208.28it/s]

Bootstrapping recall:  61%|██████    | 608/1000 [00:00<00:00, 1208.64it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1203.09it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1204.27it/s]

Bootstrapping recall:  97%|█████████▋| 971/1000 [00:00<00:00, 1204.68it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1204.95it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1192.05it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1203.17it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1207.86it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1211.61it/s]

Bootstrapping f1:  61%|██████    | 608/1000 [00:00<00:00, 1212.81it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1208.47it/s]

Bootstrapping f1:  85%|████████▌ | 851/1000 [00:00<00:00, 1206.78it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1207.69it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1206.78it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3548.68it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3558.21it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3548.67it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1288.08it/s]

Bootstrapping average_precision:  26%|██▌       | 262/1000 [00:00<00:00, 1310.32it/s]

Bootstrapping average_precision:  40%|███▉      | 397/1000 [00:00<00:00, 1327.54it/s]

Bootstrapping average_precision:  53%|█████▎    | 532/1000 [00:00<00:00, 1335.64it/s]

Bootstrapping average_precision:  67%|██████▋   | 668/1000 [00:00<00:00, 1343.99it/s]

Bootstrapping average_precision:  80%|████████  | 804/1000 [00:00<00:00, 1348.27it/s]

Bootstrapping average_precision:  94%|█████████▍| 941/1000 [00:00<00:00, 1355.11it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1342.47it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 848.49it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 841.93it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 849.67it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 858.07it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 863.46it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 864.43it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 864.51it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 858.25it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 860.19it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 863.90it/s]

Bootstrapping roc_auc:  96%|█████████▌| 956/1000 [00:01<00:00, 866.09it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 861.66it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1214.96it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1195.85it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1200.95it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1209.16it/s]

Bootstrapping precision:  61%|██████    | 611/1000 [00:00<00:00, 1213.17it/s]

Bootstrapping precision:  73%|███████▎  | 733/1000 [00:00<00:00, 1215.46it/s]

Bootstrapping precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1216.48it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1209.24it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1209.51it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1219.95it/s]

Bootstrapping recall:  24%|██▍       | 245/1000 [00:00<00:00, 1222.67it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1227.25it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1211.83it/s]

Bootstrapping recall:  61%|██████▏   | 614/1000 [00:00<00:00, 1205.37it/s]

Bootstrapping recall:  74%|███████▎  | 735/1000 [00:00<00:00, 1200.54it/s]

Bootstrapping recall:  86%|████████▌ | 856/1000 [00:00<00:00, 1187.48it/s]

Bootstrapping recall:  98%|█████████▊| 975/1000 [00:00<00:00, 1183.21it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1196.73it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1146.63it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1145.74it/s]

Bootstrapping f1:  35%|███▍      | 349/1000 [00:00<00:00, 1164.12it/s]

Bootstrapping f1:  47%|████▋     | 467/1000 [00:00<00:00, 1167.96it/s]

Bootstrapping f1:  58%|█████▊    | 585/1000 [00:00<00:00, 1171.15it/s]

Bootstrapping f1:  70%|███████   | 703/1000 [00:00<00:00, 1157.87it/s]

Bootstrapping f1:  82%|████████▏ | 820/1000 [00:00<00:00, 1161.27it/s]

Bootstrapping f1:  94%|█████████▍| 941/1000 [00:00<00:00, 1176.24it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1169.45it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 344/1000 [00:00<00:00, 3436.36it/s]

Bootstrapping accuracy:  69%|██████▉   | 688/1000 [00:00<00:00, 3437.08it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3471.38it/s]

Processing Clinician Consensus $\cup$ Golem — 213 nodes, 387 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1346.17it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1362.53it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1342.53it/s]

Bootstrapping average_precision:  55%|█████▍    | 545/1000 [00:00<00:00, 1333.20it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1306.73it/s]

Bootstrapping average_precision:  81%|████████▏ | 814/1000 [00:00<00:00, 1320.43it/s]

Bootstrapping average_precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1338.11it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1334.57it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 872.25it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 841.61it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 836.07it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 837.79it/s]

Bootstrapping roc_auc:  43%|████▎     | 430/1000 [00:00<00:00, 834.30it/s]

Bootstrapping roc_auc:  51%|█████▏    | 514/1000 [00:00<00:00, 835.31it/s]

Bootstrapping roc_auc:  60%|█████▉    | 598/1000 [00:00<00:00, 830.77it/s]

Bootstrapping roc_auc:  68%|██████▊   | 682/1000 [00:00<00:00, 832.71it/s]

Bootstrapping roc_auc:  77%|███████▋  | 766/1000 [00:00<00:00, 833.46it/s]

Bootstrapping roc_auc:  85%|████████▌ | 852/1000 [00:01<00:00, 840.27it/s]

Bootstrapping roc_auc:  94%|█████████▍| 940/1000 [00:01<00:00, 850.82it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 842.90it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1203.11it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1203.74it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1208.10it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1210.68it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1204.82it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1203.44it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1206.35it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1198.11it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1200.52it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1202.82it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1204.79it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1210.14it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1207.38it/s]

Bootstrapping recall:  61%|██████    | 607/1000 [00:00<00:00, 1206.29it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1208.07it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1208.03it/s]

Bootstrapping recall:  97%|█████████▋| 972/1000 [00:00<00:00, 1208.76it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1207.14it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1206.92it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1207.95it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1191.35it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1155.40it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1165.26it/s]

Bootstrapping f1:  72%|███████▏  | 723/1000 [00:00<00:00, 1177.84it/s]

Bootstrapping f1:  84%|████████▍ | 844/1000 [00:00<00:00, 1187.55it/s]

Bootstrapping f1:  96%|█████████▋| 965/1000 [00:00<00:00, 1192.79it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1185.78it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3560.85it/s]

Bootstrapping accuracy:  71%|███████▏  | 714/1000 [00:00<00:00, 3566.05it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3561.84it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1355.53it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1357.25it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1353.71it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1344.49it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1338.76it/s]

Bootstrapping average_precision:  82%|████████▏ | 815/1000 [00:00<00:00, 1343.23it/s]

Bootstrapping average_precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1346.38it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1343.68it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 77/1000 [00:00<00:01, 768.68it/s]

Bootstrapping roc_auc:  16%|█▌        | 159/1000 [00:00<00:01, 792.81it/s]

Bootstrapping roc_auc:  24%|██▍       | 241/1000 [00:00<00:00, 804.07it/s]

Bootstrapping roc_auc:  33%|███▎      | 327/1000 [00:00<00:00, 825.22it/s]

Bootstrapping roc_auc:  41%|████▏     | 414/1000 [00:00<00:00, 840.12it/s]

Bootstrapping roc_auc:  50%|█████     | 501/1000 [00:00<00:00, 847.08it/s]

Bootstrapping roc_auc:  59%|█████▉    | 588/1000 [00:00<00:00, 853.88it/s]

Bootstrapping roc_auc:  68%|██████▊   | 675/1000 [00:00<00:00, 858.61it/s]

Bootstrapping roc_auc:  76%|███████▌  | 761/1000 [00:00<00:00, 856.73it/s]

Bootstrapping roc_auc:  85%|████████▍ | 847/1000 [00:01<00:00, 853.21it/s]

Bootstrapping roc_auc:  93%|█████████▎| 933/1000 [00:01<00:00, 844.04it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 839.48it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1153.35it/s]

Bootstrapping precision:  23%|██▎       | 234/1000 [00:00<00:00, 1163.21it/s]

Bootstrapping precision:  36%|███▌      | 357/1000 [00:00<00:00, 1189.05it/s]

Bootstrapping precision:  48%|████▊     | 477/1000 [00:00<00:00, 1188.68it/s]

Bootstrapping precision:  60%|█████▉    | 596/1000 [00:00<00:00, 1178.78it/s]

Bootstrapping precision:  71%|███████▏  | 714/1000 [00:00<00:00, 1168.66it/s]

Bootstrapping precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1171.93it/s]

Bootstrapping precision:  95%|█████████▌| 950/1000 [00:00<00:00, 1171.77it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1170.85it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1170.76it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1171.43it/s]

Bootstrapping recall:  36%|███▌      | 355/1000 [00:00<00:00, 1179.25it/s]

Bootstrapping recall:  48%|████▊     | 475/1000 [00:00<00:00, 1185.26it/s]

Bootstrapping recall:  59%|█████▉    | 594/1000 [00:00<00:00, 1177.02it/s]

Bootstrapping recall:  71%|███████   | 712/1000 [00:00<00:00, 1167.84it/s]

Bootstrapping recall:  83%|████████▎ | 829/1000 [00:00<00:00, 1164.67it/s]

Bootstrapping recall:  95%|█████████▍| 946/1000 [00:00<00:00, 1159.78it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1165.82it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1141.48it/s]

Bootstrapping f1:  23%|██▎       | 231/1000 [00:00<00:00, 1151.42it/s]

Bootstrapping f1:  35%|███▍      | 348/1000 [00:00<00:00, 1155.68it/s]

Bootstrapping f1:  47%|████▋     | 470/1000 [00:00<00:00, 1178.85it/s]

Bootstrapping f1:  59%|█████▉    | 593/1000 [00:00<00:00, 1194.24it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1203.91it/s]

Bootstrapping f1:  84%|████████▎ | 837/1000 [00:00<00:00, 1131.90it/s]

Bootstrapping f1:  95%|█████████▌| 951/1000 [00:00<00:00, 1124.81it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1148.34it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 338/1000 [00:00<00:00, 3371.74it/s]

Bootstrapping accuracy:  68%|██████▊   | 679/1000 [00:00<00:00, 3392.55it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3372.20it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB — 19 nodes, 52 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1346.09it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1325.22it/s]

Bootstrapping average_precision:  40%|████      | 403/1000 [00:00<00:00, 1322.47it/s]

Bootstrapping average_precision:  54%|█████▍    | 539/1000 [00:00<00:00, 1336.13it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1334.57it/s]

Bootstrapping average_precision:  81%|████████  | 810/1000 [00:00<00:00, 1343.06it/s]

Bootstrapping average_precision:  95%|█████████▍| 947/1000 [00:00<00:00, 1351.43it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1342.95it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 868.87it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 872.09it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 866.24it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 865.07it/s]

Bootstrapping roc_auc:  44%|████▎     | 437/1000 [00:00<00:00, 865.67it/s]

Bootstrapping roc_auc:  52%|█████▎    | 525/1000 [00:00<00:00, 867.26it/s]

Bootstrapping roc_auc:  61%|██████    | 612/1000 [00:00<00:00, 859.27it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 864.23it/s]

Bootstrapping roc_auc:  79%|███████▉  | 788/1000 [00:00<00:00, 868.66it/s]

Bootstrapping roc_auc:  88%|████████▊ | 875/1000 [00:01<00:00, 865.69it/s]

Bootstrapping roc_auc:  96%|█████████▌| 962/1000 [00:01<00:00, 860.45it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 864.23it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1194.05it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1192.28it/s]

Bootstrapping precision:  36%|███▌      | 360/1000 [00:00<00:00, 1190.52it/s]

Bootstrapping precision:  48%|████▊     | 480/1000 [00:00<00:00, 1184.84it/s]

Bootstrapping precision:  60%|█████▉    | 599/1000 [00:00<00:00, 1176.05it/s]

Bootstrapping precision:  72%|███████▏  | 719/1000 [00:00<00:00, 1183.42it/s]

Bootstrapping precision:  84%|████████▍ | 840/1000 [00:00<00:00, 1190.81it/s]

Bootstrapping precision:  96%|█████████▌| 961/1000 [00:00<00:00, 1194.88it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1189.47it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1190.07it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1191.06it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1169.22it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1177.97it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1185.79it/s]

Bootstrapping recall:  72%|███████▏  | 720/1000 [00:00<00:00, 1173.81it/s]

Bootstrapping recall:  84%|████████▍ | 839/1000 [00:00<00:00, 1178.26it/s]

Bootstrapping recall:  96%|█████████▌| 957/1000 [00:00<00:00, 1170.84it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1175.23it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 114/1000 [00:00<00:00, 1138.92it/s]

Bootstrapping f1:  23%|██▎       | 228/1000 [00:00<00:00, 1139.26it/s]

Bootstrapping f1:  35%|███▍      | 347/1000 [00:00<00:00, 1159.48it/s]

Bootstrapping f1:  47%|████▋     | 468/1000 [00:00<00:00, 1177.28it/s]

Bootstrapping f1:  59%|█████▊    | 586/1000 [00:00<00:00, 1172.61it/s]

Bootstrapping f1:  70%|███████   | 704/1000 [00:00<00:00, 1171.12it/s]

Bootstrapping f1:  82%|████████▏ | 822/1000 [00:00<00:00, 1147.02it/s]

Bootstrapping f1:  94%|█████████▎| 937/1000 [00:00<00:00, 1144.99it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1151.51it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 351/1000 [00:00<00:00, 3500.90it/s]

Bootstrapping accuracy:  70%|███████   | 702/1000 [00:00<00:00, 3489.52it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3504.45it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1335.73it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1332.29it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1346.64it/s]

Bootstrapping average_precision:  54%|█████▍    | 541/1000 [00:00<00:00, 1348.58it/s]

Bootstrapping average_precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1350.54it/s]

Bootstrapping average_precision:  81%|████████▏ | 813/1000 [00:00<00:00, 1352.26it/s]

Bootstrapping average_precision:  95%|█████████▍| 949/1000 [00:00<00:00, 1354.55it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1349.23it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 868.20it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 864.05it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 862.30it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 863.64it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 864.59it/s]

Bootstrapping roc_auc:  52%|█████▏    | 523/1000 [00:00<00:00, 866.69it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 867.15it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 866.54it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 867.35it/s]

Bootstrapping roc_auc:  87%|████████▋ | 872/1000 [00:01<00:00, 868.30it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 868.77it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.56it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1185.73it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1161.24it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1182.52it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1196.11it/s]

Bootstrapping precision:  60%|██████    | 603/1000 [00:00<00:00, 1203.97it/s]

Bootstrapping precision:  72%|███████▎  | 725/1000 [00:00<00:00, 1209.07it/s]

Bootstrapping precision:  85%|████████▍ | 847/1000 [00:00<00:00, 1209.72it/s]

Bootstrapping precision:  97%|█████████▋| 968/1000 [00:00<00:00, 1209.04it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1199.51it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1168.38it/s]

Bootstrapping recall:  24%|██▍       | 239/1000 [00:00<00:00, 1196.96it/s]

Bootstrapping recall:  36%|███▌      | 359/1000 [00:00<00:00, 1197.69it/s]

Bootstrapping recall:  48%|████▊     | 479/1000 [00:00<00:00, 1181.12it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1194.69it/s]

Bootstrapping recall:  72%|███████▏  | 721/1000 [00:00<00:00, 1194.34it/s]

Bootstrapping recall:  84%|████████▍ | 841/1000 [00:00<00:00, 1192.39it/s]

Bootstrapping recall:  96%|█████████▌| 961/1000 [00:00<00:00, 1179.94it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1186.40it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1213.49it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1215.49it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1216.04it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1216.99it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1213.65it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1213.11it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1212.73it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1214.25it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1212.08it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3558.40it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3556.58it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3553.67it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem — 23 nodes, 34 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1368.29it/s]

Bootstrapping average_precision:  28%|██▊       | 275/1000 [00:00<00:00, 1373.00it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1377.71it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1368.32it/s]

Bootstrapping average_precision:  69%|██████▉   | 689/1000 [00:00<00:00, 1362.29it/s]

Bootstrapping average_precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1366.24it/s]

Bootstrapping average_precision:  97%|█████████▋| 966/1000 [00:00<00:00, 1373.66it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1369.97it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 863.97it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 859.45it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 865.20it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 863.10it/s]

Bootstrapping roc_auc:  44%|████▎     | 436/1000 [00:00<00:00, 864.63it/s]

Bootstrapping roc_auc:  52%|█████▏    | 524/1000 [00:00<00:00, 866.70it/s]

Bootstrapping roc_auc:  61%|██████    | 612/1000 [00:00<00:00, 868.65it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 870.90it/s]

Bootstrapping roc_auc:  79%|███████▉  | 788/1000 [00:00<00:00, 872.09it/s]

Bootstrapping roc_auc:  88%|████████▊ | 876/1000 [00:01<00:00, 864.19it/s]

Bootstrapping roc_auc:  96%|█████████▋| 963/1000 [00:01<00:00, 859.86it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 863.75it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1154.94it/s]

Bootstrapping precision:  23%|██▎       | 234/1000 [00:00<00:00, 1164.10it/s]

Bootstrapping precision:  35%|███▌      | 351/1000 [00:00<00:00, 1161.95it/s]

Bootstrapping precision:  47%|████▋     | 470/1000 [00:00<00:00, 1172.66it/s]

Bootstrapping precision:  59%|█████▉    | 588/1000 [00:00<00:00, 1171.70it/s]

Bootstrapping precision:  71%|███████   | 708/1000 [00:00<00:00, 1180.98it/s]

Bootstrapping precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1188.13it/s]

Bootstrapping precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1174.94it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1173.35it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1184.49it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1180.62it/s]

Bootstrapping recall:  36%|███▌      | 357/1000 [00:00<00:00, 1181.36it/s]

Bootstrapping recall:  48%|████▊     | 476/1000 [00:00<00:00, 1181.27it/s]

Bootstrapping recall:  60%|█████▉    | 595/1000 [00:00<00:00, 1179.04it/s]

Bootstrapping recall:  71%|███████▏  | 714/1000 [00:00<00:00, 1181.20it/s]

Bootstrapping recall:  83%|████████▎ | 833/1000 [00:00<00:00, 1181.58it/s]

Bootstrapping recall:  95%|█████████▌| 952/1000 [00:00<00:00, 1183.84it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1179.63it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1195.04it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1182.08it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1175.23it/s]

Bootstrapping f1:  48%|████▊     | 478/1000 [00:00<00:00, 1178.04it/s]

Bootstrapping f1:  60%|█████▉    | 596/1000 [00:00<00:00, 1177.03it/s]

Bootstrapping f1:  71%|███████▏  | 714/1000 [00:00<00:00, 1175.68it/s]

Bootstrapping f1:  83%|████████▎ | 832/1000 [00:00<00:00, 1172.79it/s]

Bootstrapping f1:  95%|█████████▌| 950/1000 [00:00<00:00, 1171.95it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1175.28it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3525.56it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3538.45it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3536.03it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1339.33it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1349.53it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1357.66it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1359.06it/s]

Bootstrapping average_precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1359.38it/s]

Bootstrapping average_precision:  82%|████████▏ | 818/1000 [00:00<00:00, 1360.88it/s]

Bootstrapping average_precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1360.18it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1358.05it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 864.08it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 862.66it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 864.68it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 865.20it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 865.46it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 866.62it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 865.79it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 865.83it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 867.77it/s]

Bootstrapping roc_auc:  87%|████████▋ | 871/1000 [00:01<00:00, 867.69it/s]

Bootstrapping roc_auc:  96%|█████████▌| 958/1000 [00:01<00:00, 867.90it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.00it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1211.02it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1209.13it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1211.80it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1214.88it/s]

Bootstrapping precision:  61%|██████    | 610/1000 [00:00<00:00, 1214.28it/s]

Bootstrapping precision:  73%|███████▎  | 732/1000 [00:00<00:00, 1212.54it/s]

Bootstrapping precision:  85%|████████▌ | 854/1000 [00:00<00:00, 1212.43it/s]

Bootstrapping precision:  98%|█████████▊| 976/1000 [00:00<00:00, 1211.36it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1211.59it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1229.73it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1223.46it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1218.54it/s]

Bootstrapping recall:  49%|████▉     | 491/1000 [00:00<00:00, 1214.58it/s]

Bootstrapping recall:  61%|██████▏   | 614/1000 [00:00<00:00, 1217.43it/s]

Bootstrapping recall:  74%|███████▎  | 737/1000 [00:00<00:00, 1220.17it/s]

Bootstrapping recall:  86%|████████▌ | 860/1000 [00:00<00:00, 1221.89it/s]

Bootstrapping recall:  98%|█████████▊| 983/1000 [00:00<00:00, 1219.04it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1218.39it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1209.20it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1206.50it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1207.47it/s]

Bootstrapping f1:  48%|████▊     | 485/1000 [00:00<00:00, 1208.92it/s]

Bootstrapping f1:  61%|██████    | 607/1000 [00:00<00:00, 1209.31it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1212.84it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1215.17it/s]

Bootstrapping f1:  98%|█████████▊| 975/1000 [00:00<00:00, 1217.94it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1213.00it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3537.73it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3535.12it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3540.08it/s]

Processing Clinician Consensus $\cup$ PCMB — 215 nodes, 430 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1360.94it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1374.79it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1371.44it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1371.48it/s]

Bootstrapping average_precision:  69%|██████▉   | 690/1000 [00:00<00:00, 1372.88it/s]

Bootstrapping average_precision:  83%|████████▎ | 828/1000 [00:00<00:00, 1374.85it/s]

Bootstrapping average_precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1376.34it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1373.30it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 868.03it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 871.27it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 873.06it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 873.74it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 876.38it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 876.65it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 876.81it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 876.69it/s]

Bootstrapping roc_auc:  79%|███████▉  | 792/1000 [00:00<00:00, 873.80it/s]

Bootstrapping roc_auc:  88%|████████▊ | 880/1000 [00:01<00:00, 874.56it/s]

Bootstrapping roc_auc:  97%|█████████▋| 968/1000 [00:01<00:00, 874.45it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 874.19it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1187.65it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1186.20it/s]

Bootstrapping precision:  36%|███▌      | 358/1000 [00:00<00:00, 1190.32it/s]

Bootstrapping precision:  48%|████▊     | 478/1000 [00:00<00:00, 1193.06it/s]

Bootstrapping precision:  60%|█████▉    | 599/1000 [00:00<00:00, 1196.98it/s]

Bootstrapping precision:  72%|███████▏  | 720/1000 [00:00<00:00, 1199.69it/s]

Bootstrapping precision:  84%|████████▍ | 840/1000 [00:00<00:00, 1198.91it/s]

Bootstrapping precision:  96%|█████████▌| 961/1000 [00:00<00:00, 1199.67it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1196.11it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1198.06it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1202.27it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1206.28it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1201.32it/s]

Bootstrapping recall:  60%|██████    | 605/1000 [00:00<00:00, 1170.83it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1158.80it/s]

Bootstrapping recall:  84%|████████▍ | 839/1000 [00:00<00:00, 1149.11it/s]

Bootstrapping recall:  95%|█████████▌| 954/1000 [00:00<00:00, 1145.10it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1160.93it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1120.61it/s]

Bootstrapping f1:  23%|██▎       | 226/1000 [00:00<00:00, 1117.32it/s]

Bootstrapping f1:  34%|███▍      | 341/1000 [00:00<00:00, 1129.91it/s]

Bootstrapping f1:  46%|████▌     | 460/1000 [00:00<00:00, 1152.75it/s]

Bootstrapping f1:  58%|█████▊    | 579/1000 [00:00<00:00, 1163.70it/s]

Bootstrapping f1:  70%|██████▉   | 698/1000 [00:00<00:00, 1172.45it/s]

Bootstrapping f1:  82%|████████▏ | 817/1000 [00:00<00:00, 1177.25it/s]

Bootstrapping f1:  94%|█████████▎| 935/1000 [00:00<00:00, 1173.31it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1161.50it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3498.19it/s]

Bootstrapping accuracy:  70%|███████   | 703/1000 [00:00<00:00, 3516.57it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3512.13it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1284.38it/s]

Bootstrapping average_precision:  26%|██▌       | 258/1000 [00:00<00:00, 1276.07it/s]

Bootstrapping average_precision:  39%|███▉      | 388/1000 [00:00<00:00, 1281.42it/s]

Bootstrapping average_precision:  52%|█████▏    | 522/1000 [00:00<00:00, 1301.45it/s]

Bootstrapping average_precision:  66%|██████▌   | 659/1000 [00:00<00:00, 1323.63it/s]

Bootstrapping average_precision:  80%|███████▉  | 796/1000 [00:00<00:00, 1337.41it/s]

Bootstrapping average_precision:  93%|█████████▎| 933/1000 [00:00<00:00, 1345.39it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1324.63it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 853.36it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 836.54it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 835.50it/s]

Bootstrapping roc_auc:  34%|███▍      | 340/1000 [00:00<00:00, 830.83it/s]

Bootstrapping roc_auc:  42%|████▏     | 424/1000 [00:00<00:00, 816.16it/s]

Bootstrapping roc_auc:  51%|█████     | 506/1000 [00:00<00:00, 802.97it/s]

Bootstrapping roc_auc:  59%|█████▉    | 590/1000 [00:00<00:00, 813.75it/s]

Bootstrapping roc_auc:  68%|██████▊   | 675/1000 [00:00<00:00, 822.63it/s]

Bootstrapping roc_auc:  76%|███████▌  | 760/1000 [00:00<00:00, 830.34it/s]

Bootstrapping roc_auc:  85%|████████▍ | 846/1000 [00:01<00:00, 839.07it/s]

Bootstrapping roc_auc:  93%|█████████▎| 932/1000 [00:01<00:00, 844.74it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 832.56it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1216.15it/s]

Bootstrapping precision:  24%|██▍       | 245/1000 [00:00<00:00, 1217.89it/s]

Bootstrapping precision:  37%|███▋      | 367/1000 [00:00<00:00, 1217.03it/s]

Bootstrapping precision:  49%|████▉     | 489/1000 [00:00<00:00, 1218.13it/s]

Bootstrapping precision:  61%|██████    | 611/1000 [00:00<00:00, 1212.95it/s]

Bootstrapping precision:  73%|███████▎  | 733/1000 [00:00<00:00, 1207.93it/s]

Bootstrapping precision:  86%|████████▌ | 856/1000 [00:00<00:00, 1212.57it/s]

Bootstrapping precision:  98%|█████████▊| 979/1000 [00:00<00:00, 1216.46it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1214.46it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1211.64it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1216.46it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1216.38it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1217.56it/s]

Bootstrapping recall:  61%|██████    | 611/1000 [00:00<00:00, 1218.48it/s]

Bootstrapping recall:  73%|███████▎  | 733/1000 [00:00<00:00, 1214.06it/s]

Bootstrapping recall:  86%|████████▌ | 856/1000 [00:00<00:00, 1216.09it/s]

Bootstrapping recall:  98%|█████████▊| 978/1000 [00:00<00:00, 1216.74it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1215.84it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1218.29it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1216.81it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1211.53it/s]

Bootstrapping f1:  49%|████▉     | 489/1000 [00:00<00:00, 1217.40it/s]

Bootstrapping f1:  61%|██████    | 611/1000 [00:00<00:00, 1218.18it/s]

Bootstrapping f1:  73%|███████▎  | 734/1000 [00:00<00:00, 1218.82it/s]

Bootstrapping f1:  86%|████████▌ | 856/1000 [00:00<00:00, 1218.64it/s]

Bootstrapping f1:  98%|█████████▊| 978/1000 [00:00<00:00, 1217.12it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1216.36it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 359/1000 [00:00<00:00, 3585.81it/s]

Bootstrapping accuracy:  72%|███████▏  | 718/1000 [00:00<00:00, 3580.35it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3574.19it/s]

Processing Simplified Golem $\cup$ Simplified PCMB — 24 nodes, 64 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 139/1000 [00:00<00:00, 1387.73it/s]

Bootstrapping average_precision:  28%|██▊       | 280/1000 [00:00<00:00, 1395.05it/s]

Bootstrapping average_precision:  42%|████▏     | 421/1000 [00:00<00:00, 1397.44it/s]

Bootstrapping average_precision:  56%|█████▌    | 561/1000 [00:00<00:00, 1397.42it/s]

Bootstrapping average_precision:  70%|███████   | 702/1000 [00:00<00:00, 1398.62it/s]

Bootstrapping average_precision:  84%|████████▍ | 842/1000 [00:00<00:00, 1396.01it/s]

Bootstrapping average_precision:  98%|█████████▊| 983/1000 [00:00<00:00, 1397.16it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1395.46it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 871.19it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 875.36it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 858.83it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 865.33it/s]

Bootstrapping roc_auc:  44%|████▍     | 441/1000 [00:00<00:00, 870.82it/s]

Bootstrapping roc_auc:  53%|█████▎    | 529/1000 [00:00<00:00, 872.66it/s]

Bootstrapping roc_auc:  62%|██████▏   | 617/1000 [00:00<00:00, 873.79it/s]

Bootstrapping roc_auc:  70%|███████   | 705/1000 [00:00<00:00, 875.19it/s]

Bootstrapping roc_auc:  79%|███████▉  | 793/1000 [00:00<00:00, 869.09it/s]

Bootstrapping roc_auc:  88%|████████▊ | 880/1000 [00:01<00:00, 866.59it/s]

Bootstrapping roc_auc:  97%|█████████▋| 967/1000 [00:01<00:00, 863.80it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 867.58it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1209.13it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1210.40it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1195.36it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1182.72it/s]

Bootstrapping precision:  60%|██████    | 604/1000 [00:00<00:00, 1179.70it/s]

Bootstrapping precision:  72%|███████▏  | 722/1000 [00:00<00:00, 1165.75it/s]

Bootstrapping precision:  84%|████████▍ | 839/1000 [00:00<00:00, 1165.08it/s]

Bootstrapping precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1166.45it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1173.37it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1168.63it/s]

Bootstrapping recall:  24%|██▍       | 239/1000 [00:00<00:00, 1193.95it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1203.68it/s]

Bootstrapping recall:  48%|████▊     | 482/1000 [00:00<00:00, 1180.05it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1168.10it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1167.11it/s]

Bootstrapping recall:  84%|████████▍ | 838/1000 [00:00<00:00, 1175.54it/s]

Bootstrapping recall:  96%|█████████▌| 956/1000 [00:00<00:00, 1163.69it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1172.91it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1207.34it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1177.50it/s]

Bootstrapping f1:  36%|███▌      | 361/1000 [00:00<00:00, 1180.66it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1172.93it/s]

Bootstrapping f1:  60%|█████▉    | 599/1000 [00:00<00:00, 1175.95it/s]

Bootstrapping f1:  72%|███████▏  | 720/1000 [00:00<00:00, 1185.62it/s]

Bootstrapping f1:  84%|████████▍ | 839/1000 [00:00<00:00, 1168.99it/s]

Bootstrapping f1:  96%|█████████▌| 956/1000 [00:00<00:00, 1157.49it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1168.28it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 346/1000 [00:00<00:00, 3459.42it/s]

Bootstrapping accuracy:  70%|██████▉   | 697/1000 [00:00<00:00, 3485.09it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3470.28it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 130/1000 [00:00<00:00, 1291.45it/s]

Bootstrapping average_precision:  26%|██▋       | 265/1000 [00:00<00:00, 1323.22it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1335.19it/s]

Bootstrapping average_precision:  54%|█████▎    | 536/1000 [00:00<00:00, 1344.09it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1350.91it/s]

Bootstrapping average_precision:  81%|████████  | 810/1000 [00:00<00:00, 1354.91it/s]

Bootstrapping average_precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1355.27it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1346.52it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 850.89it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 856.70it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 860.64it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 861.54it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 862.79it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 864.11it/s]

Bootstrapping roc_auc:  61%|██████    | 608/1000 [00:00<00:00, 865.83it/s]

Bootstrapping roc_auc:  70%|██████▉   | 695/1000 [00:00<00:00, 866.28it/s]

Bootstrapping roc_auc:  78%|███████▊  | 782/1000 [00:00<00:00, 866.64it/s]

Bootstrapping roc_auc:  87%|████████▋ | 870/1000 [00:01<00:00, 867.77it/s]

Bootstrapping roc_auc:  96%|█████████▌| 957/1000 [00:01<00:00, 867.69it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 864.39it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1211.56it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1212.50it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1211.57it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1211.90it/s]

Bootstrapping precision:  61%|██████    | 611/1000 [00:00<00:00, 1215.24it/s]

Bootstrapping precision:  73%|███████▎  | 734/1000 [00:00<00:00, 1217.21it/s]

Bootstrapping precision:  86%|████████▌ | 856/1000 [00:00<00:00, 1217.85it/s]

Bootstrapping precision:  98%|█████████▊| 978/1000 [00:00<00:00, 1217.01it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1214.79it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1211.75it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1210.35it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1210.38it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1207.95it/s]

Bootstrapping recall:  61%|██████    | 609/1000 [00:00<00:00, 1206.98it/s]

Bootstrapping recall:  73%|███████▎  | 730/1000 [00:00<00:00, 1207.80it/s]

Bootstrapping recall:  85%|████████▌ | 853/1000 [00:00<00:00, 1212.74it/s]

Bootstrapping recall:  98%|█████████▊| 975/1000 [00:00<00:00, 1206.76it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1205.70it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1171.47it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1175.43it/s]

Bootstrapping f1:  36%|███▌      | 355/1000 [00:00<00:00, 1178.40it/s]

Bootstrapping f1:  47%|████▋     | 473/1000 [00:00<00:00, 1178.03it/s]

Bootstrapping f1:  59%|█████▉    | 594/1000 [00:00<00:00, 1187.97it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1196.04it/s]

Bootstrapping f1:  84%|████████▎ | 836/1000 [00:00<00:00, 1195.17it/s]

Bootstrapping f1:  96%|█████████▌| 957/1000 [00:00<00:00, 1197.59it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1190.61it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3528.66it/s]

Bootstrapping accuracy:  71%|███████   | 710/1000 [00:00<00:00, 3550.17it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3548.83it/s]

Processing Clinician Consensus — 204 nodes, 372 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1367.55it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1367.39it/s]

Bootstrapping average_precision:  41%|████      | 412/1000 [00:00<00:00, 1370.79it/s]

Bootstrapping average_precision:  55%|█████▌    | 551/1000 [00:00<00:00, 1376.01it/s]

Bootstrapping average_precision:  69%|██████▉   | 691/1000 [00:00<00:00, 1381.47it/s]

Bootstrapping average_precision:  83%|████████▎ | 830/1000 [00:00<00:00, 1366.46it/s]

Bootstrapping average_precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1366.68it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1368.88it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 875.79it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 876.11it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 874.31it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 873.32it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 872.15it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 874.43it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 876.08it/s]

Bootstrapping roc_auc:  70%|███████   | 705/1000 [00:00<00:00, 877.20it/s]

Bootstrapping roc_auc:  79%|███████▉  | 793/1000 [00:00<00:00, 877.69it/s]

Bootstrapping roc_auc:  88%|████████▊ | 882/1000 [00:01<00:00, 878.86it/s]

Bootstrapping roc_auc:  97%|█████████▋| 970/1000 [00:01<00:00, 877.80it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 875.97it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1201.12it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1205.09it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1205.22it/s]

Bootstrapping precision:  48%|████▊     | 484/1000 [00:00<00:00, 1201.19it/s]

Bootstrapping precision:  60%|██████    | 605/1000 [00:00<00:00, 1201.11it/s]

Bootstrapping precision:  73%|███████▎  | 727/1000 [00:00<00:00, 1205.81it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1207.66it/s]

Bootstrapping precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1210.22it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1205.25it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1212.90it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1216.30it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1210.13it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1209.71it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1209.98it/s]

Bootstrapping recall:  73%|███████▎  | 731/1000 [00:00<00:00, 1205.43it/s]

Bootstrapping recall:  85%|████████▌ | 853/1000 [00:00<00:00, 1207.20it/s]

Bootstrapping recall:  98%|█████████▊| 975/1000 [00:00<00:00, 1208.77it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1208.10it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1208.46it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1207.68it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1207.76it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1207.87it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1207.50it/s]

Bootstrapping f1:  73%|███████▎  | 727/1000 [00:00<00:00, 1208.63it/s]

Bootstrapping f1:  85%|████████▍ | 848/1000 [00:00<00:00, 1204.40it/s]

Bootstrapping f1:  97%|█████████▋| 969/1000 [00:00<00:00, 1191.58it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1199.09it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 342/1000 [00:00<00:00, 3411.03it/s]

Bootstrapping accuracy:  70%|██████▉   | 697/1000 [00:00<00:00, 3489.28it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3496.79it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1337.79it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1336.89it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 1335.26it/s]

Bootstrapping average_precision:  54%|█████▍    | 538/1000 [00:00<00:00, 1344.11it/s]

Bootstrapping average_precision:  68%|██████▊   | 675/1000 [00:00<00:00, 1351.06it/s]

Bootstrapping average_precision:  81%|████████  | 811/1000 [00:00<00:00, 1351.57it/s]

Bootstrapping average_precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1354.53it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1347.78it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 857.81it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 848.31it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 852.79it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 856.17it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 859.37it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 861.28it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 863.62it/s]

Bootstrapping roc_auc:  69%|██████▉   | 694/1000 [00:00<00:00, 866.36it/s]

Bootstrapping roc_auc:  78%|███████▊  | 781/1000 [00:00<00:00, 860.78it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 862.32it/s]

Bootstrapping roc_auc:  96%|█████████▌| 955/1000 [00:01<00:00, 863.51it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.76it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1205.20it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1211.37it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1215.83it/s]

Bootstrapping precision:  49%|████▉     | 489/1000 [00:00<00:00, 1218.85it/s]

Bootstrapping precision:  61%|██████    | 612/1000 [00:00<00:00, 1219.45it/s]

Bootstrapping precision:  73%|███████▎  | 734/1000 [00:00<00:00, 1217.50it/s]

Bootstrapping precision:  86%|████████▌ | 856/1000 [00:00<00:00, 1217.04it/s]

Bootstrapping precision:  98%|█████████▊| 978/1000 [00:00<00:00, 1215.04it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1215.05it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1220.45it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1215.97it/s]

Bootstrapping recall:  37%|███▋      | 368/1000 [00:00<00:00, 1217.24it/s]

Bootstrapping recall:  49%|████▉     | 490/1000 [00:00<00:00, 1215.91it/s]

Bootstrapping recall:  61%|██████    | 612/1000 [00:00<00:00, 1214.17it/s]

Bootstrapping recall:  73%|███████▎  | 734/1000 [00:00<00:00, 1208.83it/s]

Bootstrapping recall:  86%|████████▌ | 856/1000 [00:00<00:00, 1210.04it/s]

Bootstrapping recall:  98%|█████████▊| 978/1000 [00:00<00:00, 1212.69it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1212.50it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1207.59it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1192.92it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1202.30it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1206.55it/s]

Bootstrapping f1:  61%|██████    | 608/1000 [00:00<00:00, 1209.86it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1210.48it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1194.21it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1196.67it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1197.98it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3541.89it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3555.11it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3552.22it/s]

Processing Simplified Clinician Consensus — 16 nodes, 16 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1364.35it/s]

Bootstrapping average_precision:  28%|██▊       | 275/1000 [00:00<00:00, 1368.75it/s]

Bootstrapping average_precision:  41%|████      | 412/1000 [00:00<00:00, 1365.66it/s]

Bootstrapping average_precision:  55%|█████▍    | 549/1000 [00:00<00:00, 1356.65it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1354.41it/s]

Bootstrapping average_precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1358.75it/s]

Bootstrapping average_precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1357.68it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1358.38it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 863.58it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 871.37it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 873.34it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 866.63it/s]

Bootstrapping roc_auc:  44%|████▍     | 439/1000 [00:00<00:00, 868.25it/s]

Bootstrapping roc_auc:  53%|█████▎    | 527/1000 [00:00<00:00, 869.66it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 870.56it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 862.15it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 864.36it/s]

Bootstrapping roc_auc:  88%|████████▊ | 878/1000 [00:01<00:00, 867.56it/s]

Bootstrapping roc_auc:  97%|█████████▋| 966/1000 [00:01<00:00, 869.32it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 868.02it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1195.35it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1185.98it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1192.78it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1194.89it/s]

Bootstrapping precision:  60%|██████    | 601/1000 [00:00<00:00, 1191.43it/s]

Bootstrapping precision:  72%|███████▏  | 722/1000 [00:00<00:00, 1197.20it/s]

Bootstrapping precision:  84%|████████▍ | 843/1000 [00:00<00:00, 1200.93it/s]

Bootstrapping precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1193.13it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1194.19it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1201.65it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1204.83it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1204.66it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1179.48it/s]

Bootstrapping recall:  60%|██████    | 603/1000 [00:00<00:00, 1178.71it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1185.59it/s]

Bootstrapping recall:  84%|████████▍ | 843/1000 [00:00<00:00, 1187.44it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1193.21it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1190.97it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1203.92it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1196.98it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1194.07it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1196.35it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1200.61it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1203.72it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1203.80it/s]

Bootstrapping f1:  97%|█████████▋| 967/1000 [00:00<00:00, 1203.82it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1201.10it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3532.34it/s]

Bootstrapping accuracy:  71%|███████   | 711/1000 [00:00<00:00, 3550.80it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3549.84it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1343.71it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1342.26it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 1346.30it/s]

Bootstrapping average_precision:  54%|█████▍    | 542/1000 [00:00<00:00, 1347.95it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1353.95it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1358.15it/s]

Bootstrapping average_precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1333.47it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1337.54it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 80/1000 [00:00<00:01, 794.32it/s]

Bootstrapping roc_auc:  16%|█▌        | 161/1000 [00:00<00:01, 800.32it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 805.86it/s]

Bootstrapping roc_auc:  32%|███▎      | 325/1000 [00:00<00:00, 809.94it/s]

Bootstrapping roc_auc:  41%|████      | 408/1000 [00:00<00:00, 812.97it/s]

Bootstrapping roc_auc:  49%|████▉     | 491/1000 [00:00<00:00, 818.11it/s]

Bootstrapping roc_auc:  58%|█████▊    | 578/1000 [00:00<00:00, 833.56it/s]

Bootstrapping roc_auc:  66%|██████▋   | 664/1000 [00:00<00:00, 839.56it/s]

Bootstrapping roc_auc:  75%|███████▍  | 748/1000 [00:00<00:00, 836.03it/s]

Bootstrapping roc_auc:  83%|████████▎ | 833/1000 [00:01<00:00, 838.24it/s]

Bootstrapping roc_auc:  92%|█████████▏| 917/1000 [00:01<00:00, 835.12it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 828.79it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1188.29it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1183.60it/s]

Bootstrapping precision:  36%|███▌      | 357/1000 [00:00<00:00, 1180.43it/s]

Bootstrapping precision:  48%|████▊     | 476/1000 [00:00<00:00, 1176.39it/s]

Bootstrapping precision:  60%|█████▉    | 595/1000 [00:00<00:00, 1180.00it/s]

Bootstrapping precision:  71%|███████▏  | 714/1000 [00:00<00:00, 1173.10it/s]

Bootstrapping precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1155.09it/s]

Bootstrapping precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1143.95it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1159.80it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 113/1000 [00:00<00:00, 1121.24it/s]

Bootstrapping recall:  23%|██▎       | 228/1000 [00:00<00:00, 1133.67it/s]

Bootstrapping recall:  34%|███▍      | 342/1000 [00:00<00:00, 1135.43it/s]

Bootstrapping recall:  46%|████▌     | 460/1000 [00:00<00:00, 1150.67it/s]

Bootstrapping recall:  58%|█████▊    | 582/1000 [00:00<00:00, 1173.95it/s]

Bootstrapping recall:  70%|███████   | 705/1000 [00:00<00:00, 1189.66it/s]

Bootstrapping recall:  83%|████████▎ | 828/1000 [00:00<00:00, 1200.48it/s]

Bootstrapping recall:  95%|█████████▌| 950/1000 [00:00<00:00, 1204.92it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1181.92it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1168.74it/s]

Bootstrapping f1:  23%|██▎       | 234/1000 [00:00<00:00, 1159.38it/s]

Bootstrapping f1:  35%|███▌      | 353/1000 [00:00<00:00, 1171.39it/s]

Bootstrapping f1:  47%|████▋     | 471/1000 [00:00<00:00, 1170.49it/s]

Bootstrapping f1:  59%|█████▉    | 592/1000 [00:00<00:00, 1182.01it/s]

Bootstrapping f1:  71%|███████▏  | 713/1000 [00:00<00:00, 1189.25it/s]

Bootstrapping f1:  84%|████████▎ | 835/1000 [00:00<00:00, 1198.39it/s]

Bootstrapping f1:  96%|█████████▌| 956/1000 [00:00<00:00, 1201.75it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1189.70it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3539.64it/s]

Bootstrapping accuracy:  71%|███████   | 709/1000 [00:00<00:00, 3543.43it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3549.02it/s]

Processing Clinician Consensus $\cap$ PCMB — 21 nodes, 20 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1367.22it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1375.74it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1376.73it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1376.14it/s]

Bootstrapping average_precision:  69%|██████▉   | 691/1000 [00:00<00:00, 1380.38it/s]

Bootstrapping average_precision:  83%|████████▎ | 830/1000 [00:00<00:00, 1382.49it/s]

Bootstrapping average_precision:  97%|█████████▋| 969/1000 [00:00<00:00, 1383.63it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1379.63it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 867.49it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 869.03it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 870.23it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 857.22it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 859.50it/s]

Bootstrapping roc_auc:  52%|█████▎    | 525/1000 [00:00<00:00, 862.02it/s]

Bootstrapping roc_auc:  61%|██████    | 612/1000 [00:00<00:00, 863.98it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 867.78it/s]

Bootstrapping roc_auc:  79%|███████▉  | 788/1000 [00:00<00:00, 868.68it/s]

Bootstrapping roc_auc:  88%|████████▊ | 875/1000 [00:01<00:00, 865.61it/s]

Bootstrapping roc_auc:  96%|█████████▌| 962/1000 [00:01<00:00, 863.85it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 863.42it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1203.84it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1204.21it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1202.36it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1205.76it/s]

Bootstrapping precision:  61%|██████    | 606/1000 [00:00<00:00, 1202.84it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1207.32it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1210.78it/s]

Bootstrapping precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1215.05it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1209.27it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1217.94it/s]

Bootstrapping recall:  24%|██▍       | 245/1000 [00:00<00:00, 1222.68it/s]

Bootstrapping recall:  37%|███▋      | 368/1000 [00:00<00:00, 1224.14it/s]

Bootstrapping recall:  49%|████▉     | 491/1000 [00:00<00:00, 1219.37it/s]

Bootstrapping recall:  61%|██████▏   | 613/1000 [00:00<00:00, 1219.08it/s]

Bootstrapping recall:  74%|███████▎  | 736/1000 [00:00<00:00, 1220.06it/s]

Bootstrapping recall:  86%|████████▌ | 859/1000 [00:00<00:00, 1216.41it/s]

Bootstrapping recall:  98%|█████████▊| 981/1000 [00:00<00:00, 1204.86it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1211.73it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1206.20it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1214.15it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1216.59it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1218.18it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1215.20it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1212.88it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1215.13it/s]

Bootstrapping f1:  98%|█████████▊| 977/1000 [00:00<00:00, 1218.13it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1215.12it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3566.82it/s]

Bootstrapping accuracy:  72%|███████▏  | 717/1000 [00:00<00:00, 3581.25it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3580.73it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1347.79it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1340.68it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1338.31it/s]

Bootstrapping average_precision:  54%|█████▍    | 542/1000 [00:00<00:00, 1347.54it/s]

Bootstrapping average_precision:  68%|██████▊   | 678/1000 [00:00<00:00, 1350.23it/s]

Bootstrapping average_precision:  82%|████████▏ | 815/1000 [00:00<00:00, 1356.35it/s]

Bootstrapping average_precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1360.42it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1353.69it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 856.84it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 861.07it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 865.43it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 867.32it/s]

Bootstrapping roc_auc:  44%|████▎     | 436/1000 [00:00<00:00, 867.95it/s]

Bootstrapping roc_auc:  52%|█████▏    | 524/1000 [00:00<00:00, 869.10it/s]

Bootstrapping roc_auc:  61%|██████    | 611/1000 [00:00<00:00, 868.23it/s]

Bootstrapping roc_auc:  70%|██████▉   | 698/1000 [00:00<00:00, 866.85it/s]

Bootstrapping roc_auc:  78%|███████▊  | 785/1000 [00:00<00:00, 864.32it/s]

Bootstrapping roc_auc:  87%|████████▋ | 872/1000 [00:01<00:00, 864.95it/s]

Bootstrapping roc_auc:  96%|█████████▌| 959/1000 [00:01<00:00, 866.39it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 866.03it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1149.88it/s]

Bootstrapping precision:  23%|██▎       | 231/1000 [00:00<00:00, 1141.88it/s]

Bootstrapping precision:  35%|███▍      | 349/1000 [00:00<00:00, 1156.00it/s]

Bootstrapping precision:  47%|████▋     | 468/1000 [00:00<00:00, 1165.55it/s]

Bootstrapping precision:  59%|█████▊    | 587/1000 [00:00<00:00, 1170.79it/s]

Bootstrapping precision:  70%|███████   | 705/1000 [00:00<00:00, 1167.12it/s]

Bootstrapping precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1172.86it/s]

Bootstrapping precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1187.12it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1174.85it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1223.77it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1220.76it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1221.66it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1223.09it/s]

Bootstrapping recall:  62%|██████▏   | 615/1000 [00:00<00:00, 1222.83it/s]

Bootstrapping recall:  74%|███████▍  | 738/1000 [00:00<00:00, 1207.26it/s]

Bootstrapping recall:  86%|████████▌ | 859/1000 [00:00<00:00, 1176.25it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1164.76it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1191.55it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1192.34it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1200.28it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1202.29it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1202.58it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1182.94it/s]

Bootstrapping f1:  72%|███████▏  | 723/1000 [00:00<00:00, 1166.55it/s]

Bootstrapping f1:  84%|████████▍ | 840/1000 [00:00<00:00, 1158.84it/s]

Bootstrapping f1:  96%|█████████▌| 959/1000 [00:00<00:00, 1166.44it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1177.03it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3565.51it/s]

Bootstrapping accuracy:  72%|███████▏  | 717/1000 [00:00<00:00, 3583.37it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3577.58it/s]

Processing Golem — 17 nodes, 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1330.53it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1297.15it/s]

Bootstrapping average_precision:  40%|███▉      | 399/1000 [00:00<00:00, 1302.88it/s]

Bootstrapping average_precision:  53%|█████▎    | 531/1000 [00:00<00:00, 1305.89it/s]

Bootstrapping average_precision:  66%|██████▋   | 665/1000 [00:00<00:00, 1316.00it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1330.99it/s]

Bootstrapping average_precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1339.91it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1326.51it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 857.02it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 864.28it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 861.34it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 865.54it/s]

Bootstrapping roc_auc:  44%|████▎     | 437/1000 [00:00<00:00, 871.73it/s]

Bootstrapping roc_auc:  52%|█████▎    | 525/1000 [00:00<00:00, 834.47it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 835.30it/s]

Bootstrapping roc_auc:  69%|██████▉   | 694/1000 [00:00<00:00, 839.77it/s]

Bootstrapping roc_auc:  78%|███████▊  | 781/1000 [00:00<00:00, 847.60it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 854.08it/s]

Bootstrapping roc_auc:  96%|█████████▌| 955/1000 [00:01<00:00, 856.62it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 853.40it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1212.44it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1206.17it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1206.93it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1209.06it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1209.27it/s]

Bootstrapping precision:  73%|███████▎  | 730/1000 [00:00<00:00, 1212.33it/s]

Bootstrapping precision:  85%|████████▌ | 852/1000 [00:00<00:00, 1212.27it/s]

Bootstrapping precision:  97%|█████████▋| 974/1000 [00:00<00:00, 1213.07it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1210.57it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1211.55it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1199.06it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1202.51it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1184.05it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1186.81it/s]

Bootstrapping recall:  73%|███████▎  | 728/1000 [00:00<00:00, 1195.39it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1202.01it/s]

Bootstrapping recall:  97%|█████████▋| 972/1000 [00:00<00:00, 1206.20it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1199.38it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1203.48it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1209.94it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1210.61it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1213.68it/s]

Bootstrapping f1:  61%|██████    | 609/1000 [00:00<00:00, 1213.53it/s]

Bootstrapping f1:  73%|███████▎  | 731/1000 [00:00<00:00, 1211.36it/s]

Bootstrapping f1:  85%|████████▌ | 853/1000 [00:00<00:00, 1209.77it/s]

Bootstrapping f1:  98%|█████████▊| 975/1000 [00:00<00:00, 1211.16it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1210.30it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3535.12it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3558.14it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3549.69it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1368.99it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1357.84it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1360.79it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1356.93it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1358.75it/s]

Bootstrapping average_precision:  82%|████████▏ | 823/1000 [00:00<00:00, 1362.55it/s]

Bootstrapping average_precision:  96%|█████████▌| 960/1000 [00:00<00:00, 1364.76it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1361.60it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 875.56it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 871.46it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 871.51it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 871.36it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 870.15it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 870.06it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 868.81it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 868.06it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 868.17it/s]

Bootstrapping roc_auc:  88%|████████▊ | 878/1000 [00:01<00:00, 870.24it/s]

Bootstrapping roc_auc:  97%|█████████▋| 966/1000 [00:01<00:00, 869.67it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 869.83it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 123/1000 [00:00<00:00, 1221.39it/s]

Bootstrapping precision:  25%|██▍       | 246/1000 [00:00<00:00, 1223.75it/s]

Bootstrapping precision:  37%|███▋      | 369/1000 [00:00<00:00, 1220.08it/s]

Bootstrapping precision:  49%|████▉     | 492/1000 [00:00<00:00, 1208.18it/s]

Bootstrapping precision:  61%|██████▏   | 613/1000 [00:00<00:00, 1198.03it/s]

Bootstrapping precision:  73%|███████▎  | 733/1000 [00:00<00:00, 1193.47it/s]

Bootstrapping precision:  85%|████████▌ | 854/1000 [00:00<00:00, 1197.15it/s]

Bootstrapping precision:  98%|█████████▊| 975/1000 [00:00<00:00, 1199.67it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1201.58it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1222.54it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1221.28it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1222.75it/s]

Bootstrapping recall:  49%|████▉     | 493/1000 [00:00<00:00, 1225.72it/s]

Bootstrapping recall:  62%|██████▏   | 617/1000 [00:00<00:00, 1227.97it/s]

Bootstrapping recall:  74%|███████▍  | 741/1000 [00:00<00:00, 1228.56it/s]

Bootstrapping recall:  86%|████████▋ | 864/1000 [00:00<00:00, 1227.96it/s]

Bootstrapping recall:  99%|█████████▊| 987/1000 [00:00<00:00, 1225.39it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1224.85it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1215.41it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1215.74it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1217.05it/s]

Bootstrapping f1:  49%|████▉     | 490/1000 [00:00<00:00, 1222.41it/s]

Bootstrapping f1:  61%|██████▏   | 613/1000 [00:00<00:00, 1223.48it/s]

Bootstrapping f1:  74%|███████▎  | 736/1000 [00:00<00:00, 1221.37it/s]

Bootstrapping f1:  86%|████████▌ | 859/1000 [00:00<00:00, 1223.81it/s]

Bootstrapping f1:  98%|█████████▊| 982/1000 [00:00<00:00, 1225.15it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1221.82it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3559.40it/s]

Bootstrapping accuracy:  72%|███████▏  | 715/1000 [00:00<00:00, 3575.27it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3573.04it/s]

Processing PCMB — 32 nodes, 78 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1355.19it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1365.93it/s]

Bootstrapping average_precision:  41%|████      | 412/1000 [00:00<00:00, 1371.73it/s]

Bootstrapping average_precision:  55%|█████▌    | 550/1000 [00:00<00:00, 1374.37it/s]

Bootstrapping average_precision:  69%|██████▉   | 688/1000 [00:00<00:00, 1374.19it/s]

Bootstrapping average_precision:  83%|████████▎ | 826/1000 [00:00<00:00, 1373.61it/s]

Bootstrapping average_precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1373.86it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1371.13it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 858.41it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 864.88it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 870.26it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 872.69it/s]

Bootstrapping roc_auc:  44%|████▎     | 437/1000 [00:00<00:00, 874.49it/s]

Bootstrapping roc_auc:  52%|█████▎    | 525/1000 [00:00<00:00, 875.04it/s]

Bootstrapping roc_auc:  61%|██████▏   | 614/1000 [00:00<00:00, 877.74it/s]

Bootstrapping roc_auc:  70%|███████   | 702/1000 [00:00<00:00, 875.57it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 873.86it/s]

Bootstrapping roc_auc:  88%|████████▊ | 878/1000 [00:01<00:00, 874.93it/s]

Bootstrapping roc_auc:  97%|█████████▋| 966/1000 [00:01<00:00, 874.62it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 872.78it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1199.58it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1207.58it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1214.68it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1217.96it/s]

Bootstrapping precision:  61%|██████    | 610/1000 [00:00<00:00, 1216.49it/s]

Bootstrapping precision:  73%|███████▎  | 733/1000 [00:00<00:00, 1217.84it/s]

Bootstrapping precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1218.36it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1218.17it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1215.37it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1210.35it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1211.25it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1214.45it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1216.47it/s]

Bootstrapping recall:  61%|██████    | 611/1000 [00:00<00:00, 1218.67it/s]

Bootstrapping recall:  73%|███████▎  | 733/1000 [00:00<00:00, 1217.32it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1216.73it/s]

Bootstrapping recall:  98%|█████████▊| 978/1000 [00:00<00:00, 1218.17it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1214.44it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1186.94it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1183.79it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1194.90it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1199.68it/s]

Bootstrapping f1:  60%|██████    | 601/1000 [00:00<00:00, 1200.22it/s]

Bootstrapping f1:  72%|███████▏  | 723/1000 [00:00<00:00, 1205.40it/s]

Bootstrapping f1:  84%|████████▍ | 844/1000 [00:00<00:00, 1205.60it/s]

Bootstrapping f1:  96%|█████████▋| 965/1000 [00:00<00:00, 1199.54it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1197.01it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 346/1000 [00:00<00:00, 3456.53it/s]

Bootstrapping accuracy:  70%|██████▉   | 696/1000 [00:00<00:00, 3480.64it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3482.97it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1355.12it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1354.49it/s]

Bootstrapping average_precision:  41%|████      | 409/1000 [00:00<00:00, 1358.99it/s]

Bootstrapping average_precision:  55%|█████▍    | 546/1000 [00:00<00:00, 1362.38it/s]

Bootstrapping average_precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1364.79it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1364.10it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1363.10it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1361.28it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 865.26it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 842.21it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 850.48it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 854.29it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 856.97it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 859.11it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 860.62it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 861.85it/s]

Bootstrapping roc_auc:  78%|███████▊  | 783/1000 [00:00<00:00, 863.15it/s]

Bootstrapping roc_auc:  87%|████████▋ | 870/1000 [00:01<00:00, 863.12it/s]

Bootstrapping roc_auc:  96%|█████████▌| 957/1000 [00:01<00:00, 862.41it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 859.65it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1203.39it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1205.16it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1210.00it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1211.22it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1211.43it/s]

Bootstrapping precision:  73%|███████▎  | 730/1000 [00:00<00:00, 1209.65it/s]

Bootstrapping precision:  85%|████████▌ | 852/1000 [00:00<00:00, 1212.74it/s]

Bootstrapping precision:  97%|█████████▋| 974/1000 [00:00<00:00, 1213.97it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1210.88it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1216.47it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1214.27it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1214.41it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1210.80it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1207.89it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1210.34it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1210.12it/s]

Bootstrapping recall:  98%|█████████▊| 976/1000 [00:00<00:00, 1209.91it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1209.58it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1211.22it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1205.33it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1207.38it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1207.06it/s]

Bootstrapping f1:  61%|██████    | 608/1000 [00:00<00:00, 1210.24it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1213.10it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1202.68it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1198.97it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1203.70it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 351/1000 [00:00<00:00, 3509.47it/s]

Bootstrapping accuracy:  71%|███████   | 710/1000 [00:00<00:00, 3552.78it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3550.52it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB — 15 nodes, 14 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1368.40it/s]

Bootstrapping average_precision:  28%|██▊       | 275/1000 [00:00<00:00, 1369.86it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1374.74it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1375.48it/s]

Bootstrapping average_precision:  69%|██████▉   | 690/1000 [00:00<00:00, 1376.52it/s]

Bootstrapping average_precision:  83%|████████▎ | 828/1000 [00:00<00:00, 1368.22it/s]

Bootstrapping average_precision:  96%|█████████▋| 965/1000 [00:00<00:00, 1362.14it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1364.89it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 865.83it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 869.05it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 868.52it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 872.02it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 870.03it/s]

Bootstrapping roc_auc:  53%|█████▎    | 526/1000 [00:00<00:00, 871.96it/s]

Bootstrapping roc_auc:  61%|██████▏   | 614/1000 [00:00<00:00, 874.06it/s]

Bootstrapping roc_auc:  70%|███████   | 702/1000 [00:00<00:00, 875.49it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 874.74it/s]

Bootstrapping roc_auc:  88%|████████▊ | 878/1000 [00:01<00:00, 875.15it/s]

Bootstrapping roc_auc:  97%|█████████▋| 966/1000 [00:01<00:00, 875.56it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 872.10it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1179.77it/s]

Bootstrapping precision:  24%|██▎       | 237/1000 [00:00<00:00, 1185.20it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1199.39it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1203.84it/s]

Bootstrapping precision:  60%|██████    | 604/1000 [00:00<00:00, 1211.52it/s]

Bootstrapping precision:  73%|███████▎  | 726/1000 [00:00<00:00, 1212.93it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1214.62it/s]

Bootstrapping precision:  97%|█████████▋| 970/1000 [00:00<00:00, 1213.18it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1207.47it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1217.84it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1214.35it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1213.02it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1212.34it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1208.14it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1209.82it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1211.33it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1215.87it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1212.44it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1212.33it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1210.55it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1211.92it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1214.23it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1213.83it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1213.09it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1204.43it/s]

Bootstrapping f1:  98%|█████████▊| 975/1000 [00:00<00:00, 1197.04it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1204.38it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3552.25it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3545.35it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3545.27it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1352.79it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1346.45it/s]

Bootstrapping average_precision:  41%|████      | 409/1000 [00:00<00:00, 1353.25it/s]

Bootstrapping average_precision:  55%|█████▍    | 545/1000 [00:00<00:00, 1355.79it/s]

Bootstrapping average_precision:  68%|██████▊   | 682/1000 [00:00<00:00, 1358.43it/s]

Bootstrapping average_precision:  82%|████████▏ | 818/1000 [00:00<00:00, 1358.57it/s]

Bootstrapping average_precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1361.14it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1355.59it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 862.80it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 846.87it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 844.00it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 846.95it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 854.15it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 857.34it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 856.96it/s]

Bootstrapping roc_auc:  69%|██████▉   | 692/1000 [00:00<00:00, 860.56it/s]

Bootstrapping roc_auc:  78%|███████▊  | 779/1000 [00:00<00:00, 861.90it/s]

Bootstrapping roc_auc:  87%|████████▋ | 866/1000 [00:01<00:00, 854.44it/s]

Bootstrapping roc_auc:  95%|█████████▌| 953/1000 [00:01<00:00, 856.37it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 855.57it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1209.68it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1211.75it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1211.62it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1215.01it/s]

Bootstrapping precision:  61%|██████    | 611/1000 [00:00<00:00, 1220.01it/s]

Bootstrapping precision:  73%|███████▎  | 734/1000 [00:00<00:00, 1216.30it/s]

Bootstrapping precision:  86%|████████▌ | 856/1000 [00:00<00:00, 1215.72it/s]

Bootstrapping precision:  98%|█████████▊| 979/1000 [00:00<00:00, 1218.05it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1215.66it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1211.98it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1198.33it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1200.37it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1203.56it/s]

Bootstrapping recall:  61%|██████    | 608/1000 [00:00<00:00, 1207.18it/s]

Bootstrapping recall:  73%|███████▎  | 730/1000 [00:00<00:00, 1209.78it/s]

Bootstrapping recall:  85%|████████▌ | 852/1000 [00:00<00:00, 1211.12it/s]

Bootstrapping recall:  97%|█████████▋| 974/1000 [00:00<00:00, 1213.07it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1208.41it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1208.29it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1217.62it/s]

Bootstrapping f1:  37%|███▋      | 367/1000 [00:00<00:00, 1219.81it/s]

Bootstrapping f1:  49%|████▉     | 489/1000 [00:00<00:00, 1215.93it/s]

Bootstrapping f1:  61%|██████    | 611/1000 [00:00<00:00, 1216.21it/s]

Bootstrapping f1:  73%|███████▎  | 733/1000 [00:00<00:00, 1213.31it/s]

Bootstrapping f1:  86%|████████▌ | 856/1000 [00:00<00:00, 1215.65it/s]

Bootstrapping f1:  98%|█████████▊| 978/1000 [00:00<00:00, 1216.40it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1215.16it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 348/1000 [00:00<00:00, 3478.23it/s]

Bootstrapping accuracy:  70%|██████▉   | 696/1000 [00:00<00:00, 3462.63it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3459.35it/s]

Processing Simplified PCMB — 18 nodes, 50 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1371.03it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1373.41it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1374.02it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1374.79it/s]

Bootstrapping average_precision:  69%|██████▉   | 691/1000 [00:00<00:00, 1377.56it/s]

Bootstrapping average_precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1378.19it/s]

Bootstrapping average_precision:  97%|█████████▋| 968/1000 [00:00<00:00, 1380.13it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1377.21it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 871.95it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 876.35it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 874.68it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 873.23it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 873.14it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 872.09it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 871.06it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 873.32it/s]

Bootstrapping roc_auc:  79%|███████▉  | 792/1000 [00:00<00:00, 862.34it/s]

Bootstrapping roc_auc:  88%|████████▊ | 879/1000 [00:01<00:00, 851.98it/s]

Bootstrapping roc_auc:  96%|█████████▋| 965/1000 [00:01<00:00, 842.28it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 859.45it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 112/1000 [00:00<00:00, 1115.51it/s]

Bootstrapping precision:  23%|██▎       | 229/1000 [00:00<00:00, 1141.78it/s]

Bootstrapping precision:  35%|███▌      | 350/1000 [00:00<00:00, 1169.55it/s]

Bootstrapping precision:  47%|████▋     | 470/1000 [00:00<00:00, 1179.29it/s]

Bootstrapping precision:  59%|█████▉    | 590/1000 [00:00<00:00, 1184.59it/s]

Bootstrapping precision:  71%|███████   | 709/1000 [00:00<00:00, 1185.84it/s]

Bootstrapping precision:  83%|████████▎ | 830/1000 [00:00<00:00, 1190.52it/s]

Bootstrapping precision:  95%|█████████▌| 950/1000 [00:00<00:00, 1183.82it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1175.46it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 113/1000 [00:00<00:00, 1129.65it/s]

Bootstrapping recall:  23%|██▎       | 228/1000 [00:00<00:00, 1136.90it/s]

Bootstrapping recall:  34%|███▍      | 344/1000 [00:00<00:00, 1143.28it/s]

Bootstrapping recall:  46%|████▋     | 463/1000 [00:00<00:00, 1161.35it/s]

Bootstrapping recall:  58%|█████▊    | 580/1000 [00:00<00:00, 1152.73it/s]

Bootstrapping recall:  70%|██████▉   | 697/1000 [00:00<00:00, 1158.52it/s]

Bootstrapping recall:  82%|████████▏ | 816/1000 [00:00<00:00, 1166.35it/s]

Bootstrapping recall:  93%|█████████▎| 933/1000 [00:00<00:00, 1154.41it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1152.55it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1157.57it/s]

Bootstrapping f1:  23%|██▎       | 232/1000 [00:00<00:00, 1156.13it/s]

Bootstrapping f1:  35%|███▌      | 353/1000 [00:00<00:00, 1177.26it/s]

Bootstrapping f1:  47%|████▋     | 471/1000 [00:00<00:00, 1177.97it/s]

Bootstrapping f1:  59%|█████▉    | 589/1000 [00:00<00:00, 1163.46it/s]

Bootstrapping f1:  71%|███████   | 706/1000 [00:00<00:00, 1164.65it/s]

Bootstrapping f1:  83%|████████▎ | 826/1000 [00:00<00:00, 1173.34it/s]

Bootstrapping f1:  95%|█████████▍| 946/1000 [00:00<00:00, 1179.95it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1173.61it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3554.49it/s]

Bootstrapping accuracy:  71%|███████▏  | 714/1000 [00:00<00:00, 3568.27it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3570.23it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1348.86it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1361.73it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1363.10it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1366.13it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1362.52it/s]

Bootstrapping average_precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1363.14it/s]

Bootstrapping average_precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1365.09it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1362.59it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 869.06it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 869.55it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 857.11it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 857.19it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 862.14it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 863.75it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 864.53it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 865.46it/s]

Bootstrapping roc_auc:  78%|███████▊  | 783/1000 [00:00<00:00, 865.93it/s]

Bootstrapping roc_auc:  87%|████████▋ | 870/1000 [00:01<00:00, 865.31it/s]

Bootstrapping roc_auc:  96%|█████████▌| 957/1000 [00:01<00:00, 861.95it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 862.87it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1197.61it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1199.75it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1197.79it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1185.00it/s]

Bootstrapping precision:  60%|██████    | 600/1000 [00:00<00:00, 1168.33it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1164.39it/s]

Bootstrapping precision:  83%|████████▎ | 834/1000 [00:00<00:00, 1157.54it/s]

Bootstrapping precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1160.33it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1168.45it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1177.95it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1177.30it/s]

Bootstrapping recall:  36%|███▌      | 358/1000 [00:00<00:00, 1193.68it/s]

Bootstrapping recall:  48%|████▊     | 478/1000 [00:00<00:00, 1176.76it/s]

Bootstrapping recall:  60%|█████▉    | 596/1000 [00:00<00:00, 1162.07it/s]

Bootstrapping recall:  71%|███████▏  | 713/1000 [00:00<00:00, 1156.31it/s]

Bootstrapping recall:  83%|████████▎ | 833/1000 [00:00<00:00, 1169.89it/s]

Bootstrapping recall:  96%|█████████▌| 955/1000 [00:00<00:00, 1182.80it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1176.75it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1208.64it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1213.29it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1211.33it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1212.05it/s]

Bootstrapping f1:  61%|██████    | 609/1000 [00:00<00:00, 1203.86it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1191.85it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1199.90it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1210.05it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1205.61it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3549.61it/s]

Bootstrapping accuracy:  72%|███████▏  | 715/1000 [00:00<00:00, 3574.03it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3576.47it/s]

Processing Clinician Consensus $\cap$ Golem — 8 nodes, 7 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1362.39it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1365.23it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1365.11it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1366.75it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1348.53it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1348.52it/s]

Bootstrapping average_precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1337.37it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1346.09it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 866.89it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 868.19it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 869.56it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 872.07it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 869.86it/s]

Bootstrapping roc_auc:  52%|█████▎    | 525/1000 [00:00<00:00, 868.00it/s]

Bootstrapping roc_auc:  61%|██████    | 612/1000 [00:00<00:00, 860.27it/s]

Bootstrapping roc_auc:  70%|██████▉   | 699/1000 [00:00<00:00, 858.37it/s]

Bootstrapping roc_auc:  79%|███████▊  | 786/1000 [00:00<00:00, 860.82it/s]

Bootstrapping roc_auc:  87%|████████▋ | 873/1000 [00:01<00:00, 861.29it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 863.87it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 864.39it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1215.45it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1212.82it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1215.00it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1215.84it/s]

Bootstrapping precision:  61%|██████    | 610/1000 [00:00<00:00, 1199.24it/s]

Bootstrapping precision:  73%|███████▎  | 732/1000 [00:00<00:00, 1204.08it/s]

Bootstrapping precision:  85%|████████▌ | 853/1000 [00:00<00:00, 1178.06it/s]

Bootstrapping precision:  97%|█████████▋| 974/1000 [00:00<00:00, 1186.01it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1195.41it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1216.36it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1224.44it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1222.32it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1219.99it/s]

Bootstrapping recall:  62%|██████▏   | 615/1000 [00:00<00:00, 1221.21it/s]

Bootstrapping recall:  74%|███████▍  | 738/1000 [00:00<00:00, 1210.14it/s]

Bootstrapping recall:  86%|████████▌ | 860/1000 [00:00<00:00, 1194.63it/s]

Bootstrapping recall:  98%|█████████▊| 980/1000 [00:00<00:00, 1177.09it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1197.06it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1178.02it/s]

Bootstrapping f1:  24%|██▍       | 239/1000 [00:00<00:00, 1192.10it/s]

Bootstrapping f1:  36%|███▌      | 361/1000 [00:00<00:00, 1204.53it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1210.00it/s]

Bootstrapping f1:  61%|██████    | 606/1000 [00:00<00:00, 1214.57it/s]

Bootstrapping f1:  73%|███████▎  | 728/1000 [00:00<00:00, 1215.26it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1214.59it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1218.54it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1211.62it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 358/1000 [00:00<00:00, 3575.82it/s]

Bootstrapping accuracy:  72%|███████▏  | 717/1000 [00:00<00:00, 3583.97it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3576.22it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1344.20it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1346.64it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 1349.61it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1356.13it/s]

Bootstrapping average_precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1362.22it/s]

Bootstrapping average_precision:  82%|████████▏ | 819/1000 [00:00<00:00, 1367.93it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1371.04it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1363.08it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 861.24it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 863.70it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 867.22it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 867.48it/s]

Bootstrapping roc_auc:  44%|████▎     | 436/1000 [00:00<00:00, 867.81it/s]

Bootstrapping roc_auc:  52%|█████▏    | 523/1000 [00:00<00:00, 866.75it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 864.70it/s]

Bootstrapping roc_auc:  70%|██████▉   | 698/1000 [00:00<00:00, 866.45it/s]

Bootstrapping roc_auc:  79%|███████▊  | 786/1000 [00:00<00:00, 869.47it/s]

Bootstrapping roc_auc:  87%|████████▋ | 873/1000 [00:01<00:00, 868.99it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 868.93it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 867.20it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 123/1000 [00:00<00:00, 1224.99it/s]

Bootstrapping precision:  25%|██▍       | 246/1000 [00:00<00:00, 1219.14it/s]

Bootstrapping precision:  37%|███▋      | 368/1000 [00:00<00:00, 1216.97it/s]

Bootstrapping precision:  49%|████▉     | 490/1000 [00:00<00:00, 1215.12it/s]

Bootstrapping precision:  61%|██████▏   | 613/1000 [00:00<00:00, 1217.36it/s]

Bootstrapping precision:  74%|███████▎  | 735/1000 [00:00<00:00, 1203.27it/s]

Bootstrapping precision:  86%|████████▌ | 856/1000 [00:00<00:00, 1204.25it/s]

Bootstrapping precision:  98%|█████████▊| 978/1000 [00:00<00:00, 1208.02it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1210.31it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1208.74it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1206.49it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1202.77it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1202.24it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1207.27it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 1205.63it/s]

Bootstrapping recall:  85%|████████▍ | 848/1000 [00:00<00:00, 1194.15it/s]

Bootstrapping recall:  97%|█████████▋| 969/1000 [00:00<00:00, 1197.95it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1197.74it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1191.24it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1203.67it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1205.67it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1193.15it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1184.21it/s]

Bootstrapping f1:  72%|███████▏  | 723/1000 [00:00<00:00, 1174.75it/s]

Bootstrapping f1:  84%|████████▍ | 845/1000 [00:00<00:00, 1186.61it/s]

Bootstrapping f1:  97%|█████████▋| 968/1000 [00:00<00:00, 1197.92it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1192.30it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3545.25it/s]

Bootstrapping accuracy:  71%|███████▏  | 713/1000 [00:00<00:00, 3560.74it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3527.81it/s]

Processing Simplified Golem — 12 nodes, 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1378.66it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1373.21it/s]

Bootstrapping average_precision:  42%|████▏     | 415/1000 [00:00<00:00, 1378.76it/s]

Bootstrapping average_precision:  55%|█████▌    | 554/1000 [00:00<00:00, 1381.73it/s]

Bootstrapping average_precision:  69%|██████▉   | 693/1000 [00:00<00:00, 1381.28it/s]

Bootstrapping average_precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1382.20it/s]

Bootstrapping average_precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1380.54it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1379.42it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 874.15it/s]

Bootstrapping roc_auc:  18%|█▊        | 177/1000 [00:00<00:00, 879.02it/s]

Bootstrapping roc_auc:  27%|██▋       | 266/1000 [00:00<00:00, 879.87it/s]

Bootstrapping roc_auc:  35%|███▌      | 354/1000 [00:00<00:00, 878.78it/s]

Bootstrapping roc_auc:  44%|████▍     | 443/1000 [00:00<00:00, 880.09it/s]

Bootstrapping roc_auc:  53%|█████▎    | 532/1000 [00:00<00:00, 879.91it/s]

Bootstrapping roc_auc:  62%|██████▏   | 620/1000 [00:00<00:00, 879.63it/s]

Bootstrapping roc_auc:  71%|███████   | 709/1000 [00:00<00:00, 879.89it/s]

Bootstrapping roc_auc:  80%|███████▉  | 797/1000 [00:00<00:00, 879.43it/s]

Bootstrapping roc_auc:  88%|████████▊ | 885/1000 [00:01<00:00, 877.21it/s]

Bootstrapping roc_auc:  97%|█████████▋| 973/1000 [00:01<00:00, 877.39it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 878.25it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1197.75it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1202.11it/s]

Bootstrapping precision:  36%|███▌      | 362/1000 [00:00<00:00, 1202.07it/s]

Bootstrapping precision:  48%|████▊     | 484/1000 [00:00<00:00, 1206.03it/s]

Bootstrapping precision:  61%|██████    | 606/1000 [00:00<00:00, 1208.33it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1210.91it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1202.55it/s]

Bootstrapping precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1197.06it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1200.62it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1181.19it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1182.29it/s]

Bootstrapping recall:  36%|███▌      | 358/1000 [00:00<00:00, 1187.06it/s]

Bootstrapping recall:  48%|████▊     | 478/1000 [00:00<00:00, 1187.94it/s]

Bootstrapping recall:  60%|█████▉    | 597/1000 [00:00<00:00, 1187.54it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1192.64it/s]

Bootstrapping recall:  84%|████████▍ | 838/1000 [00:00<00:00, 1193.04it/s]

Bootstrapping recall:  96%|█████████▌| 959/1000 [00:00<00:00, 1195.85it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1189.99it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1190.43it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1193.95it/s]

Bootstrapping f1:  36%|███▌      | 360/1000 [00:00<00:00, 1187.35it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1189.00it/s]

Bootstrapping f1:  60%|█████▉    | 599/1000 [00:00<00:00, 1186.89it/s]

Bootstrapping f1:  72%|███████▏  | 719/1000 [00:00<00:00, 1190.47it/s]

Bootstrapping f1:  84%|████████▍ | 839/1000 [00:00<00:00, 1190.53it/s]

Bootstrapping f1:  96%|█████████▌| 959/1000 [00:00<00:00, 1187.56it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1188.49it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3536.61it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3531.15it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3540.30it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1335.89it/s]

Bootstrapping average_precision:  27%|██▋       | 269/1000 [00:00<00:00, 1343.70it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1349.82it/s]

Bootstrapping average_precision:  54%|█████▍    | 540/1000 [00:00<00:00, 1347.92it/s]

Bootstrapping average_precision:  68%|██████▊   | 676/1000 [00:00<00:00, 1349.85it/s]

Bootstrapping average_precision:  81%|████████  | 811/1000 [00:00<00:00, 1348.59it/s]

Bootstrapping average_precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1352.90it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1350.10it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 862.23it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 868.07it/s]

Bootstrapping roc_auc:  26%|██▌       | 262/1000 [00:00<00:00, 867.49it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 868.51it/s]

Bootstrapping roc_auc:  44%|████▎     | 437/1000 [00:00<00:00, 867.76it/s]

Bootstrapping roc_auc:  52%|█████▏    | 524/1000 [00:00<00:00, 867.53it/s]

Bootstrapping roc_auc:  61%|██████    | 611/1000 [00:00<00:00, 865.94it/s]

Bootstrapping roc_auc:  70%|██████▉   | 699/1000 [00:00<00:00, 868.63it/s]

Bootstrapping roc_auc:  79%|███████▊  | 786/1000 [00:00<00:00, 868.52it/s]

Bootstrapping roc_auc:  87%|████████▋ | 873/1000 [00:01<00:00, 867.49it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 866.12it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 865.15it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1156.47it/s]

Bootstrapping precision:  23%|██▎       | 233/1000 [00:00<00:00, 1160.83it/s]

Bootstrapping precision:  35%|███▌      | 350/1000 [00:00<00:00, 1162.92it/s]

Bootstrapping precision:  47%|████▋     | 467/1000 [00:00<00:00, 1165.48it/s]

Bootstrapping precision:  59%|█████▊    | 586/1000 [00:00<00:00, 1172.01it/s]

Bootstrapping precision:  71%|███████   | 706/1000 [00:00<00:00, 1179.62it/s]

Bootstrapping precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1188.47it/s]

Bootstrapping precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1194.11it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1181.99it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1211.60it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1212.45it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1197.55it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1193.63it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1179.80it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 1188.96it/s]

Bootstrapping recall:  85%|████████▍ | 848/1000 [00:00<00:00, 1193.41it/s]

Bootstrapping recall:  97%|█████████▋| 969/1000 [00:00<00:00, 1196.62it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1194.14it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 123/1000 [00:00<00:00, 1221.29it/s]

Bootstrapping f1:  25%|██▍       | 246/1000 [00:00<00:00, 1214.37it/s]

Bootstrapping f1:  37%|███▋      | 368/1000 [00:00<00:00, 1211.87it/s]

Bootstrapping f1:  49%|████▉     | 490/1000 [00:00<00:00, 1205.97it/s]

Bootstrapping f1:  61%|██████    | 611/1000 [00:00<00:00, 1206.94it/s]

Bootstrapping f1:  73%|███████▎  | 733/1000 [00:00<00:00, 1209.81it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1201.19it/s]

Bootstrapping f1:  98%|█████████▊| 975/1000 [00:00<00:00, 1191.05it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1200.27it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3552.43it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3502.96it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3508.51it/s]

Processing Golem $\cup$ PCMB — 48 nodes, 100 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1361.97it/s]

Bootstrapping average_precision:  28%|██▊       | 275/1000 [00:00<00:00, 1371.88it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1376.33it/s]

Bootstrapping average_precision:  55%|█████▌    | 552/1000 [00:00<00:00, 1369.29it/s]

Bootstrapping average_precision:  69%|██████▉   | 689/1000 [00:00<00:00, 1363.41it/s]

Bootstrapping average_precision:  83%|████████▎ | 826/1000 [00:00<00:00, 1359.84it/s]

Bootstrapping average_precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1363.69it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1364.48it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 870.33it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 872.51it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 867.35it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 868.47it/s]

Bootstrapping roc_auc:  44%|████▍     | 439/1000 [00:00<00:00, 868.37it/s]

Bootstrapping roc_auc:  53%|█████▎    | 526/1000 [00:00<00:00, 863.56it/s]

Bootstrapping roc_auc:  61%|██████▏   | 613/1000 [00:00<00:00, 860.39it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 856.16it/s]

Bootstrapping roc_auc:  79%|███████▊  | 786/1000 [00:00<00:00, 855.43it/s]

Bootstrapping roc_auc:  87%|████████▋ | 873/1000 [00:01<00:00, 857.94it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 860.42it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 861.83it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1177.92it/s]

Bootstrapping precision:  24%|██▎       | 237/1000 [00:00<00:00, 1182.34it/s]

Bootstrapping precision:  36%|███▌      | 358/1000 [00:00<00:00, 1194.54it/s]

Bootstrapping precision:  48%|████▊     | 479/1000 [00:00<00:00, 1200.26it/s]

Bootstrapping precision:  60%|██████    | 600/1000 [00:00<00:00, 1203.68it/s]

Bootstrapping precision:  72%|███████▏  | 721/1000 [00:00<00:00, 1204.00it/s]

Bootstrapping precision:  84%|████████▍ | 842/1000 [00:00<00:00, 1198.31it/s]

Bootstrapping precision:  96%|█████████▌| 962/1000 [00:00<00:00, 1195.95it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1195.23it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1192.45it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1191.80it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1202.19it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1200.47it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1188.41it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1179.72it/s]

Bootstrapping recall:  84%|████████▍ | 844/1000 [00:00<00:00, 1187.58it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1189.04it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1190.30it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1202.69it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1184.83it/s]

Bootstrapping f1:  36%|███▌      | 361/1000 [00:00<00:00, 1180.71it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1178.48it/s]

Bootstrapping f1:  60%|█████▉    | 599/1000 [00:00<00:00, 1181.47it/s]

Bootstrapping f1:  72%|███████▏  | 718/1000 [00:00<00:00, 1183.55it/s]

Bootstrapping f1:  84%|████████▎ | 837/1000 [00:00<00:00, 1179.66it/s]

Bootstrapping f1:  96%|█████████▌| 955/1000 [00:00<00:00, 1174.95it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1176.97it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 352/1000 [00:00<00:00, 3510.35it/s]

Bootstrapping accuracy:  70%|███████   | 704/1000 [00:00<00:00, 3513.17it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3531.21it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1344.62it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1350.72it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1357.48it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1357.90it/s]

Bootstrapping average_precision:  68%|██████▊   | 680/1000 [00:00<00:00, 1355.88it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1358.29it/s]

Bootstrapping average_precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1365.05it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1360.21it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 856.67it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 849.92it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 858.60it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 858.78it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 855.80it/s]

Bootstrapping roc_auc:  52%|█████▏    | 517/1000 [00:00<00:00, 853.61it/s]

Bootstrapping roc_auc:  60%|██████    | 603/1000 [00:00<00:00, 852.54it/s]

Bootstrapping roc_auc:  69%|██████▉   | 689/1000 [00:00<00:00, 849.64it/s]

Bootstrapping roc_auc:  78%|███████▊  | 775/1000 [00:00<00:00, 851.20it/s]

Bootstrapping roc_auc:  86%|████████▌ | 862/1000 [00:01<00:00, 855.61it/s]

Bootstrapping roc_auc:  95%|█████████▍| 949/1000 [00:01<00:00, 859.80it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 855.24it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1207.27it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1205.42it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1191.45it/s]

Bootstrapping precision:  48%|████▊     | 483/1000 [00:00<00:00, 1177.77it/s]

Bootstrapping precision:  60%|██████    | 601/1000 [00:00<00:00, 1177.34it/s]

Bootstrapping precision:  72%|███████▏  | 721/1000 [00:00<00:00, 1182.48it/s]

Bootstrapping precision:  84%|████████▍ | 840/1000 [00:00<00:00, 1180.91it/s]

Bootstrapping precision:  96%|█████████▌| 960/1000 [00:00<00:00, 1186.90it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1185.99it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1200.72it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1197.85it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1199.26it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1202.12it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1205.08it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 1204.62it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1211.54it/s]

Bootstrapping recall:  97%|█████████▋| 972/1000 [00:00<00:00, 1209.13it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1205.30it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1218.67it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1212.59it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1213.51it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1214.25it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1212.35it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1211.24it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1215.15it/s]

Bootstrapping f1:  98%|█████████▊| 978/1000 [00:00<00:00, 1217.19it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1214.34it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3541.37it/s]

Bootstrapping accuracy:  72%|███████▏  | 716/1000 [00:00<00:00, 3579.53it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3563.88it/s]

Processing Simplified Golem $\cap$ Simplified PCMB — 6 nodes, 5 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1363.50it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1376.88it/s]

Bootstrapping average_precision:  41%|████▏     | 414/1000 [00:00<00:00, 1373.78it/s]

Bootstrapping average_precision:  55%|█████▌    | 553/1000 [00:00<00:00, 1376.41it/s]

Bootstrapping average_precision:  69%|██████▉   | 691/1000 [00:00<00:00, 1372.28it/s]

Bootstrapping average_precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1373.00it/s]

Bootstrapping average_precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1371.32it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1370.40it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 869.70it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 875.49it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 873.43it/s]

Bootstrapping roc_auc:  35%|███▌      | 353/1000 [00:00<00:00, 876.42it/s]

Bootstrapping roc_auc:  44%|████▍     | 441/1000 [00:00<00:00, 875.34it/s]

Bootstrapping roc_auc:  53%|█████▎    | 529/1000 [00:00<00:00, 875.40it/s]

Bootstrapping roc_auc:  62%|██████▏   | 617/1000 [00:00<00:00, 874.90it/s]

Bootstrapping roc_auc:  70%|███████   | 705/1000 [00:00<00:00, 872.50it/s]

Bootstrapping roc_auc:  79%|███████▉  | 793/1000 [00:00<00:00, 869.70it/s]

Bootstrapping roc_auc:  88%|████████▊ | 880/1000 [00:01<00:00, 866.47it/s]

Bootstrapping roc_auc:  97%|█████████▋| 967/1000 [00:01<00:00, 866.67it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 870.77it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1189.25it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1153.75it/s]

Bootstrapping precision:  35%|███▌      | 354/1000 [00:00<00:00, 1142.64it/s]

Bootstrapping precision:  47%|████▋     | 472/1000 [00:00<00:00, 1153.41it/s]

Bootstrapping precision:  59%|█████▉    | 588/1000 [00:00<00:00, 1155.56it/s]

Bootstrapping precision:  70%|███████   | 704/1000 [00:00<00:00, 1155.60it/s]

Bootstrapping precision:  82%|████████▎ | 825/1000 [00:00<00:00, 1171.01it/s]

Bootstrapping precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1181.85it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1168.91it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1169.88it/s]

Bootstrapping recall:  24%|██▎       | 237/1000 [00:00<00:00, 1183.98it/s]

Bootstrapping recall:  36%|███▌      | 359/1000 [00:00<00:00, 1196.65it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1200.77it/s]

Bootstrapping recall:  60%|██████    | 602/1000 [00:00<00:00, 1204.54it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1195.74it/s]

Bootstrapping recall:  84%|████████▍ | 844/1000 [00:00<00:00, 1198.11it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1197.89it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1195.94it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1211.49it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1205.59it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1205.54it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1209.75it/s]

Bootstrapping f1:  61%|██████    | 608/1000 [00:00<00:00, 1202.02it/s]

Bootstrapping f1:  73%|███████▎  | 729/1000 [00:00<00:00, 1201.61it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1200.30it/s]

Bootstrapping f1:  97%|█████████▋| 971/1000 [00:00<00:00, 1199.22it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1201.53it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3534.10it/s]

Bootstrapping accuracy:  71%|███████   | 710/1000 [00:00<00:00, 3545.61it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3530.52it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1327.06it/s]

Bootstrapping average_precision:  27%|██▋       | 269/1000 [00:00<00:00, 1344.02it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1347.89it/s]

Bootstrapping average_precision:  54%|█████▍    | 540/1000 [00:00<00:00, 1346.83it/s]

Bootstrapping average_precision:  68%|██████▊   | 675/1000 [00:00<00:00, 1346.58it/s]

Bootstrapping average_precision:  81%|████████  | 812/1000 [00:00<00:00, 1351.30it/s]

Bootstrapping average_precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1349.67it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1345.59it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 823.24it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:00, 837.02it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 850.61it/s]

Bootstrapping roc_auc:  34%|███▍      | 342/1000 [00:00<00:00, 856.06it/s]

Bootstrapping roc_auc:  43%|████▎     | 429/1000 [00:00<00:00, 860.17it/s]

Bootstrapping roc_auc:  52%|█████▏    | 516/1000 [00:00<00:00, 862.08it/s]

Bootstrapping roc_auc:  60%|██████    | 603/1000 [00:00<00:00, 864.22it/s]

Bootstrapping roc_auc:  69%|██████▉   | 690/1000 [00:00<00:00, 865.40it/s]

Bootstrapping roc_auc:  78%|███████▊  | 777/1000 [00:00<00:00, 866.29it/s]

Bootstrapping roc_auc:  86%|████████▋ | 864/1000 [00:01<00:00, 866.74it/s]

Bootstrapping roc_auc:  95%|█████████▌| 951/1000 [00:01<00:00, 865.30it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 861.03it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1206.39it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1211.07it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1207.31it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1206.87it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1174.04it/s]

Bootstrapping precision:  73%|███████▎  | 727/1000 [00:00<00:00, 1179.98it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1189.57it/s]

Bootstrapping precision:  97%|█████████▋| 970/1000 [00:00<00:00, 1198.42it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1195.34it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1215.31it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1215.85it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1195.07it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1178.11it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1170.92it/s]

Bootstrapping recall:  72%|███████▎  | 725/1000 [00:00<00:00, 1180.79it/s]

Bootstrapping recall:  84%|████████▍ | 844/1000 [00:00<00:00, 1183.65it/s]

Bootstrapping recall:  96%|█████████▋| 965/1000 [00:00<00:00, 1191.03it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1187.40it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1185.46it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1197.28it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1206.33it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1204.97it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1200.76it/s]

Bootstrapping f1:  73%|███████▎  | 727/1000 [00:00<00:00, 1208.18it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1213.90it/s]

Bootstrapping f1:  97%|█████████▋| 972/1000 [00:00<00:00, 1207.65it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1204.66it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 347/1000 [00:00<00:00, 3465.12it/s]

Bootstrapping accuracy:  70%|███████   | 703/1000 [00:00<00:00, 3516.87it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3517.08it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem — 5 nodes, 4 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1368.33it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1360.08it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1358.98it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1362.58it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1363.23it/s]

Bootstrapping average_precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1364.52it/s]

Bootstrapping average_precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1364.28it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1362.48it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 872.00it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 874.46it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 874.35it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 874.85it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 872.55it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 871.47it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 867.87it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 869.09it/s]

Bootstrapping roc_auc:  79%|███████▉  | 791/1000 [00:00<00:00, 869.01it/s]

Bootstrapping roc_auc:  88%|████████▊ | 879/1000 [00:01<00:00, 870.94it/s]

Bootstrapping roc_auc:  97%|█████████▋| 967/1000 [00:01<00:00, 868.34it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 870.01it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1187.55it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1197.96it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1202.72it/s]

Bootstrapping precision:  48%|████▊     | 484/1000 [00:00<00:00, 1209.85it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1213.27it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1214.90it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1213.96it/s]

Bootstrapping precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1212.02it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1208.60it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1202.33it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1204.15it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1202.95it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1206.76it/s]

Bootstrapping recall:  61%|██████    | 607/1000 [00:00<00:00, 1209.88it/s]

Bootstrapping recall:  73%|███████▎  | 728/1000 [00:00<00:00, 1206.43it/s]

Bootstrapping recall:  85%|████████▍ | 849/1000 [00:00<00:00, 1204.15it/s]

Bootstrapping recall:  97%|█████████▋| 970/1000 [00:00<00:00, 1204.61it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1204.13it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1211.09it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1214.29it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1215.41it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1213.11it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1209.84it/s]

Bootstrapping f1:  73%|███████▎  | 732/1000 [00:00<00:00, 1210.85it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1210.70it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1212.30it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1211.92it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 359/1000 [00:00<00:00, 3581.36it/s]

Bootstrapping accuracy:  72%|███████▏  | 718/1000 [00:00<00:00, 3572.10it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3559.28it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1356.56it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1361.43it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1359.70it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1364.19it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1363.17it/s]

Bootstrapping average_precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1360.96it/s]

Bootstrapping average_precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1356.52it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1357.79it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 852.48it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 853.73it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 856.22it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 856.74it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 857.97it/s]

Bootstrapping roc_auc:  52%|█████▏    | 519/1000 [00:00<00:00, 863.86it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 867.58it/s]

Bootstrapping roc_auc:  70%|██████▉   | 695/1000 [00:00<00:00, 869.89it/s]

Bootstrapping roc_auc:  78%|███████▊  | 783/1000 [00:00<00:00, 870.00it/s]

Bootstrapping roc_auc:  87%|████████▋ | 870/1000 [00:01<00:00, 867.29it/s]

Bootstrapping roc_auc:  96%|█████████▌| 959/1000 [00:01<00:00, 871.23it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 865.50it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1215.66it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1215.62it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1209.65it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1187.10it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1189.06it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1194.74it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1197.32it/s]

Bootstrapping precision:  97%|█████████▋| 969/1000 [00:00<00:00, 1190.77it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1194.49it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1222.26it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1219.51it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1222.15it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1222.17it/s]

Bootstrapping recall:  62%|██████▏   | 615/1000 [00:00<00:00, 1221.54it/s]

Bootstrapping recall:  74%|███████▍  | 738/1000 [00:00<00:00, 1220.72it/s]

Bootstrapping recall:  86%|████████▌ | 861/1000 [00:00<00:00, 1220.33it/s]

Bootstrapping recall:  98%|█████████▊| 984/1000 [00:00<00:00, 1219.86it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1219.97it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1206.94it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1210.29it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1208.49it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1209.03it/s]

Bootstrapping f1:  61%|██████    | 609/1000 [00:00<00:00, 1212.78it/s]

Bootstrapping f1:  73%|███████▎  | 731/1000 [00:00<00:00, 1208.75it/s]

Bootstrapping f1:  85%|████████▌ | 853/1000 [00:00<00:00, 1209.28it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1214.97it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1211.10it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3534.63it/s]

Bootstrapping accuracy:  72%|███████▏  | 715/1000 [00:00<00:00, 3578.06it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3561.14it/s]

In [14]:
df3 = pd.DataFrame(results3)
df3.to_csv('Generative LGBN - No Drugs or Interventions.csv', index=False)
df3

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,Generative LGBN,Control,"0.47 (0.43, 0.51)","0.84 (0.81, 0.86)","0.76 (0.73, 0.78)","0.78 (0.75, 0.80)","0.77 (0.74, 0.79)","0.90 (0.89, 0.91)",0.121,521,28
1,XGB,Control,"0.78 (0.75, 0.82)","0.92 (0.90, 0.93)","0.90 (0.88, 0.92)","0.80 (0.78, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.093,521,28
2,Generative LGBN,Correlation,"0.55 (0.50, 0.60)","0.81 (0.78, 0.83)","0.82 (0.80, 0.85)","0.74 (0.71, 0.76)","0.77 (0.75, 0.79)","0.92 (0.91, 0.93)",0.078,53,20
3,XGB,Correlation,"0.75 (0.71, 0.78)","0.89 (0.87, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.83 (0.80, 0.85)","0.94 (0.93, 0.95)",0.114,53,20
4,Generative LGBN,Clinician Consensus $\cup$ Golem,"0.54 (0.49, 0.58)","0.84 (0.82, 0.87)","0.77 (0.75, 0.80)","0.77 (0.75, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.108,134,15
5,XGB,Clinician Consensus $\cup$ Golem,"0.77 (0.73, 0.80)","0.90 (0.88, 0.92)","0.91 (0.89, 0.93)","0.80 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.100,134,15
6,Generative LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.47 (0.42, 0.51)","0.83 (0.80, 0.85)","0.73 (0.71, 0.76)","0.74 (0.72, 0.77)","0.74 (0.72, 0.76)","0.89 (0.88, 0.90)",0.116,131,7
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.89 (0.87, 0.91)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.104,131,7
8,Generative LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.48 (0.43, 0.53)","0.83 (0.81, 0.86)","0.73 (0.71, 0.75)","0.76 (0.73, 0.78)","0.74 (0.72, 0.76)","0.89 (0.88, 0.90)",0.126,204,11
9,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.77 (0.74, 0.81)","0.91 (0.90, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.101,204,11
10,Generative LGBN,Clinician Consensus $\cup$ PCMB,"0.52 (0.48, 0.57)","0.84 (0.82, 0.87)","0.77 (0.74, 0.79)","0.76 (0.74, 0.79)","0.77 (0.74, 0.79)","0.91 (0.90, 0.92)",0.110,130,12
11,XGB,Clinician Consensus $\cup$ PCMB,"0.76 (0.73, 0.80)","0.90 (0.88, 0.92)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.099,130,12
12,Generative LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.45 (0.41, 0.50)","0.83 (0.80, 0.85)","0.73 (0.71, 0.75)","0.75 (0.73, 0.77)","0.74 (0.72, 0.76)","0.89 (0.88, 0.90)",0.123,223,12
13,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.77 (0.73, 0.80)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.098,223,12
14,Generative LGBN,Clinician Consensus,"0.53 (0.49, 0.58)","0.84 (0.82, 0.86)","0.77 (0.75, 0.79)","0.77 (0.74, 0.79)","0.77 (0.75, 0.79)","0.91 (0.90, 0.92)",0.109,126,9
15,XGB,Clinician Consensus,"0.76 (0.73, 0.80)","0.90 (0.88, 0.92)","0.89 (0.87, 0.91)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.101,126,9
16,Generative LGBN,Simplified Clinician Consensus,"0.49 (0.45, 0.54)","0.81 (0.79, 0.84)","0.74 (0.72, 0.77)","0.75 (0.73, 0.77)","0.75 (0.73, 0.77)","0.90 (0.89, 0.91)",0.115,93,5
17,XGB,Simplified Clinician Consensus,"0.73 (0.69, 0.76)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.75, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.108,93,5
18,Generative LGBN,Clinician Consensus $\cap$ PCMB,"0.57 (0.52, 0.61)","0.80 (0.77, 0.83)","0.77 (0.75, 0.80)","0.74 (0.71, 0.76)","0.75 (0.73, 0.77)","0.91 (0.90, 0.92)",0.098,14,8
19,XGB,Clinician Consensus $\cap$ PCMB,"0.66 (0.62, 0.70)","0.84 (0.82, 0.86)","0.87 (0.84, 0.89)","0.74 (0.72, 0.77)","0.79 (0.77, 0.81)","0.93 (0.92, 0.94)",0.123,14,8
20,Generative LGBN,Golem,"0.26 (0.22, 0.30)","0.70 (0.68, 0.73)","0.63 (0.59, 0.66)","0.56 (0.54, 0.58)","0.57 (0.55, 0.60)","0.88 (0.87, 0.89)",0.051,15,10
21,XGB,Golem,"0.54 (0.50, 0.59)","0.84 (0.82, 0.86)","0.77 (0.74, 0.80)","0.68 (0.66, 0.70)","0.71 (0.69, 0.73)","0.91 (0.90, 0.91)",0.115,15,10
22,Generative LGBN,PCMB,"0.56 (0.51, 0.61)","0.81 (0.79, 0.84)","0.75 (0.72, 0.77)","0.74 (0.71, 0.76)","0.74 (0.72, 0.76)","0.90 (0.89, 0.91)",0.109,18,11
23,XGB,PCMB,"0.69 (0.65, 0.73)","0.87 (0.85, 0.89)","0.87 (0.84, 0.89)","0.75 (0.73, 0.77)","0.79 (0.77, 0.82)","0.93 (0.92, 0.94)",0.120,18,11
24,Generative LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.49 (0.45, 0.54)","0.81 (0.79, 0.84)","0.74 (0.72, 0.77)","0.75 (0.73, 0.77)","0.75 (0.73, 0.77)","0.90 (0.89, 0.91)",0.115,93,5
25,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.73 (0.69, 0.76)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.75, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.108,93,5
26,Generative LGBN,Simplified PCMB,"0.47 (0.42, 0.51)","0.83 (0.80, 0.85)","0.73 (0.71, 0.76)","0.74 (0.72, 0.77)","0.74 (0.72, 0.76)","0.89 (0.88, 0.90)",0.116,131,7
27,XGB,Simplified PCMB,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.89 (0.87, 0.91)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.104,131,7
28,Generative LGBN,Clinician Consensus $\cap$ Golem,"0.18 (0.15, 0.21)","0.55 (0.52, 0.58)","0.63 (0.59, 0.67)","0.54 (0.52, 0.55)","0.55 (0.52, 0.57)","0.88 (0.87, 0.89)",0.189,7,4
29,XGB,Clinician Consensus $\cap$ Golem,"0.25 (0.21, 0.29)","0.65 (0.62, 0.68)","0.70 (0.65, 0.74)","0.56 (0.54, 0.57)","0.57 (0.55, 0.59)","0.89 (0.88, 0.90)",0.124,7,4
30,Generative LGBN,Simplified Golem,"0.48 (0.44, 0.53)","0.84 (0.81, 0.86)","0.73 (0.71, 0.75)","0.75 (0.73, 0.78)","0.74 (0.72, 0.76)","0.89 (0.88, 0.90)",0.125,149,8
31,XGB,Simplified Golem,"0.76 (0.72, 0.79)","0.91 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,149,8
32,Generative LGBN,Golem $\cup$ PCMB,"0.55 (0.51, 0.60)","0.84 (0.81, 0.86)","0.76 (0.74, 0.79)","0.75 (0.73, 0.77)","0.76 (0.74, 0.78)","0.91 (0.90, 0.91)",0.106,33,16
33,XGB,Golem $\cup$ PCMB,"0.73 (0.69, 0.77)","0.90 (0.88, 0.91)","0.88 (0.86, 0.90)","0.77 (0.75, 0.80)","0.82 (0.79, 0.84)","0.94 (0.93, 0.95)",0.109,33,16
34,Generative LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.47 (0.42, 0.52)","0.81 (0.79, 0.84)","0.73 (0.71, 0.76)","0.71 (0.69, 0.74)","0.72 (0.70, 0.75)","0.90 (0.89, 0.91)",0.101,57,3
35,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.71 (0.68, 0.75)","0.89 (0.87, 0.91)","0.86 (0.84, 0.89)","0.77 (0.75, 0.80)","0.81 (0.79, 0.83)","0.93 (0.93, 0.94)",0.113,57,3
36,Generative LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.43 (0.39, 0.49)","0.80 (0.77, 0.82)","0.70 (0.68, 0.73)","0.70 (0.68, 0.73)","0.70 (0.68, 0.73)","0.88 (0.87, 0.89)",0.111,38,2
37,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.66 (0.62, 0.70)","0.86 (0.84, 0.88)","0.85 (0.82, 0.87)","0.74 (0.72, 0.76)","0.78 (0.76, 0.80)","0.93 (0.92, 0.93)",0.116,38,2

In [15]:
aurocs3, auprcs3 = [], []
for dag_name, preds in model_preds3.items():
    (z, p_delong), perm = compare_models(y_test.Outcome, preds['Generative LGBN'], preds['XGB'])
    aurocs3.append({'DAG': dag_name, 'Z-score': f"{z:.4f}", 'P-value': f"{p_delong:.3e}"})
    auprcs3.append({'DAG': dag_name,
                    'Avg Precision LGBN': f"{perm[0]:.4f}",
                    'Avg Precision XGB':  f"{perm[1]:.4f}",
                    'P-value': f"{perm[2]:.3e}"})

pd.DataFrame(aurocs3).to_csv('Generative LGBN - delong_only_vitals_labs_auroc.csv', index=False)
pd.DataFrame(auprcs3).to_csv('Generative LGBN - delong_only_vitals_labs_auprc.csv', index=False)
pd.DataFrame(aurocs3)

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 730.95it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 733.65it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 727.23it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 295/1000 [00:00<00:00, 724.86it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 368/1000 [00:00<00:00, 720.34it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 441/1000 [00:00<00:00, 713.39it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 710.64it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 585/1000 [00:00<00:00, 710.29it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 657/1000 [00:00<00:00, 711.25it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 729/1000 [00:01<00:00, 712.03it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 801/1000 [00:01<00:00, 707.69it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 873/1000 [00:01<00:00, 709.08it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 944/1000 [00:01<00:00, 708.67it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 714.02it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 705.04it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 713.80it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 714.12it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:00, 718.52it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 362/1000 [00:00<00:00, 723.29it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 435/1000 [00:00<00:00, 725.48it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 508/1000 [00:00<00:00, 724.38it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 581/1000 [00:00<00:00, 722.19it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 654/1000 [00:00<00:00, 717.12it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 726/1000 [00:01<00:00, 712.59it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 798/1000 [00:01<00:00, 706.48it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 869/1000 [00:01<00:00, 703.54it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 941/1000 [00:01<00:00, 705.80it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 713.09it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 700.41it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 701.87it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 704.15it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 285/1000 [00:00<00:01, 709.63it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 357/1000 [00:00<00:00, 712.53it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 429/1000 [00:00<00:00, 712.44it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 501/1000 [00:00<00:00, 714.47it/s]

Computing average_precision Permutation Test p-value:  57%|█████▊    | 575/1000 [00:00<00:00, 721.52it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 648/1000 [00:00<00:00, 723.11it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 722/1000 [00:01<00:00, 725.78it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 796/1000 [00:01<00:00, 727.21it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 869/1000 [00:01<00:00, 724.79it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 942/1000 [00:01<00:00, 718.55it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 717.13it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 714.58it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 712.08it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 714.06it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:00, 716.19it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 360/1000 [00:00<00:00, 713.09it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 715.02it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 504/1000 [00:00<00:00, 715.80it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 577/1000 [00:00<00:00, 718.90it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 649/1000 [00:00<00:00, 718.20it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 721/1000 [00:01<00:00, 717.16it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 794/1000 [00:01<00:00, 718.70it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 867/1000 [00:01<00:00, 721.58it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 940/1000 [00:01<00:00, 720.86it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 717.42it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 712.99it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 711.37it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 710.14it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 289/1000 [00:00<00:00, 714.15it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 361/1000 [00:00<00:00, 714.21it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 433/1000 [00:00<00:00, 714.90it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 505/1000 [00:00<00:00, 714.35it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 578/1000 [00:00<00:00, 716.43it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 651/1000 [00:00<00:00, 717.69it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 724/1000 [00:01<00:00, 719.55it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 797/1000 [00:01<00:00, 720.56it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 870/1000 [00:01<00:00, 721.83it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 944/1000 [00:01<00:00, 724.29it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 718.10it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 710.16it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 714.68it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 714.17it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 289/1000 [00:00<00:00, 717.09it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 361/1000 [00:00<00:00, 714.20it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 434/1000 [00:00<00:00, 718.96it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 506/1000 [00:00<00:00, 718.39it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 578/1000 [00:00<00:00, 716.80it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 651/1000 [00:00<00:00, 718.39it/s]

Computing average_precision Permutation Test p-value:  72%|███████▎  | 725/1000 [00:01<00:00, 723.39it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 799/1000 [00:01<00:00, 727.11it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 872/1000 [00:01<00:00, 727.18it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 945/1000 [00:01<00:00, 727.66it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 722.01it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 730.51it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 734.84it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 734.10it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 733.41it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 370/1000 [00:00<00:00, 734.63it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 444/1000 [00:00<00:00, 734.80it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 518/1000 [00:00<00:00, 736.08it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 592/1000 [00:00<00:00, 736.27it/s]

Computing average_precision Permutation Test p-value:  67%|██████▋   | 666/1000 [00:00<00:00, 736.14it/s]

Computing average_precision Permutation Test p-value:  74%|███████▍  | 740/1000 [00:01<00:00, 734.60it/s]

Computing average_precision Permutation Test p-value:  81%|████████▏ | 814/1000 [00:01<00:00, 733.97it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 888/1000 [00:01<00:00, 732.95it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 962/1000 [00:01<00:00, 731.67it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 733.63it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 733.02it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 734.12it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 733.94it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 734.04it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 370/1000 [00:00<00:00, 735.95it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 445/1000 [00:00<00:00, 737.74it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 519/1000 [00:00<00:00, 735.84it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 593/1000 [00:00<00:00, 734.50it/s]

Computing average_precision Permutation Test p-value:  67%|██████▋   | 667/1000 [00:00<00:00, 734.91it/s]

Computing average_precision Permutation Test p-value:  74%|███████▍  | 741/1000 [00:01<00:00, 734.36it/s]

Computing average_precision Permutation Test p-value:  82%|████████▏ | 816/1000 [00:01<00:00, 737.12it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 890/1000 [00:01<00:00, 736.78it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▋| 964/1000 [00:01<00:00, 737.75it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 735.78it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 731.91it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 731.39it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 222/1000 [00:00<00:01, 720.64it/s]

Computing average_precision Permutation Test p-value:  30%|██▉       | 296/1000 [00:00<00:00, 725.80it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 370/1000 [00:00<00:00, 727.73it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 444/1000 [00:00<00:00, 729.11it/s]

Computing average_precision Permutation Test p-value:  52%|█████▏    | 517/1000 [00:00<00:00, 729.30it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 591/1000 [00:00<00:00, 731.42it/s]

Computing average_precision Permutation Test p-value:  66%|██████▋   | 665/1000 [00:00<00:00, 730.96it/s]

Computing average_precision Permutation Test p-value:  74%|███████▍  | 739/1000 [00:01<00:00, 730.97it/s]

Computing average_precision Permutation Test p-value:  81%|████████▏ | 813/1000 [00:01<00:00, 730.60it/s]

Computing average_precision Permutation Test p-value:  89%|████████▊ | 887/1000 [00:01<00:00, 732.43it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 961/1000 [00:01<00:00, 734.29it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 730.51it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 726.22it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 726.91it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 728.29it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 293/1000 [00:00<00:00, 730.60it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 367/1000 [00:00<00:00, 729.40it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 729.14it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 726.82it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 586/1000 [00:00<00:00, 726.68it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 659/1000 [00:00<00:00, 727.35it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 732/1000 [00:01<00:00, 723.90it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 805/1000 [00:01<00:00, 719.55it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 877/1000 [00:01<00:00, 712.80it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 949/1000 [00:01<00:00, 710.12it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 720.83it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 706.90it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 714.10it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 701.36it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 701.84it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 359/1000 [00:00<00:00, 708.95it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 712.73it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 505/1000 [00:00<00:00, 717.76it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 578/1000 [00:00<00:00, 718.70it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 651/1000 [00:00<00:00, 719.92it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 724/1000 [00:01<00:00, 720.69it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 797/1000 [00:01<00:00, 721.45it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 870/1000 [00:01<00:00, 721.97it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 943/1000 [00:01<00:00, 721.95it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 715.89it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 698.67it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 713.41it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 217/1000 [00:00<00:01, 721.16it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 290/1000 [00:00<00:00, 722.96it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 364/1000 [00:00<00:00, 726.35it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 437/1000 [00:00<00:00, 725.81it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 510/1000 [00:00<00:00, 723.10it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 583/1000 [00:00<00:00, 723.00it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 656/1000 [00:00<00:00, 721.83it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 730/1000 [00:01<00:00, 724.68it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 803/1000 [00:01<00:00, 725.80it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 877/1000 [00:01<00:00, 729.00it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 950/1000 [00:01<00:00, 729.16it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 724.46it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 717.02it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 716.80it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 723.92it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 726.30it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 366/1000 [00:00<00:00, 729.66it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 730.67it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 514/1000 [00:00<00:00, 733.15it/s]

Computing average_precision Permutation Test p-value:  59%|█████▉    | 588/1000 [00:00<00:00, 733.56it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 662/1000 [00:00<00:00, 734.96it/s]

Computing average_precision Permutation Test p-value:  74%|███████▎  | 736/1000 [00:01<00:00, 735.28it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 810/1000 [00:01<00:00, 734.79it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 884/1000 [00:01<00:00, 733.57it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 958/1000 [00:01<00:00, 733.03it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 731.01it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 727.53it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 728.14it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 728.67it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 293/1000 [00:00<00:00, 729.98it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 366/1000 [00:00<00:00, 725.67it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 439/1000 [00:00<00:00, 724.01it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 512/1000 [00:00<00:00, 719.48it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 586/1000 [00:00<00:00, 724.27it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 659/1000 [00:00<00:00, 725.24it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 732/1000 [00:01<00:00, 711.98it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 804/1000 [00:01<00:00, 708.55it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 876/1000 [00:01<00:00, 711.50it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 950/1000 [00:01<00:00, 719.31it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 720.99it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 696.10it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 710.70it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 714.78it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 287/1000 [00:00<00:00, 716.40it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 359/1000 [00:00<00:00, 713.61it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 431/1000 [00:00<00:00, 702.81it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 502/1000 [00:00<00:00, 695.24it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 573/1000 [00:00<00:00, 696.60it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 643/1000 [00:00<00:00, 696.60it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 716/1000 [00:01<00:00, 705.10it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 790/1000 [00:01<00:00, 713.12it/s]

Computing average_precision Permutation Test p-value:  86%|████████▋ | 863/1000 [00:01<00:00, 716.29it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▎| 937/1000 [00:01<00:00, 720.94it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 711.11it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 713.04it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 698.47it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 697.82it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 704.78it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 359/1000 [00:00<00:00, 713.29it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 433/1000 [00:00<00:00, 721.05it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 507/1000 [00:00<00:00, 725.89it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 581/1000 [00:00<00:00, 728.64it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 654/1000 [00:00<00:00, 728.20it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 727/1000 [00:01<00:00, 725.03it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 800/1000 [00:01<00:00, 723.19it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 873/1000 [00:01<00:00, 724.86it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 946/1000 [00:01<00:00, 725.23it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 720.92it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 721.51it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 716.35it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 220/1000 [00:00<00:01, 723.44it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 294/1000 [00:00<00:00, 727.31it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 367/1000 [00:00<00:00, 727.43it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 720.59it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 721.70it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 587/1000 [00:00<00:00, 725.05it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 660/1000 [00:00<00:00, 726.26it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 733/1000 [00:01<00:00, 726.34it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 806/1000 [00:01<00:00, 726.93it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 879/1000 [00:01<00:00, 724.07it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 952/1000 [00:01<00:00, 716.23it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 720.87it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 706.90it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 715.85it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 217/1000 [00:00<00:01, 721.47it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 291/1000 [00:00<00:00, 725.31it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 364/1000 [00:00<00:00, 721.13it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 437/1000 [00:00<00:00, 715.40it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 509/1000 [00:00<00:00, 706.70it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 580/1000 [00:00<00:00, 703.64it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 651/1000 [00:00<00:00, 699.53it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 721/1000 [00:01<00:00, 688.50it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 791/1000 [00:01<00:00, 690.23it/s]

Computing average_precision Permutation Test p-value:  86%|████████▋ | 864/1000 [00:01<00:00, 700.75it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 938/1000 [00:01<00:00, 709.52it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 708.37it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 724.31it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 727.38it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 724.19it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 720.91it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 721.75it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 722.67it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 511/1000 [00:00<00:00, 717.79it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 583/1000 [00:00<00:00, 717.64it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 656/1000 [00:00<00:00, 720.69it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 729/1000 [00:01<00:00, 722.85it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 802/1000 [00:01<00:00, 723.42it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 876/1000 [00:01<00:00, 725.79it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 949/1000 [00:01<00:00, 726.33it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 723.42it/s]

                                                  DAG Z-score    P-value
0                                             Control  8.1156  4.836e-16
1                                         Correlation  7.1856  6.690e-13
2                    Clinician Consensus $\cup$ Golem  5.6721  1.410e-08
3   Simplified Clinician Consensus $\cup$ Simplifi...  7.7323  1.056e-14
4   Simplified Clinician Consensus $\cup$ Simplifi...  7.4417  9.942e-14
5                     Clinician Consensus $\cup$ PCMB  5.5715  2.526e-08
6             Simplified Golem $\cup$ Simplified PCMB  7.9977  1.268e-15
7                                 Clinician Consensus  5.6888  1.280e-08
8                      Simplified Clinician Consensus  6.7090  1.959e-11
9                     Clinician Consensus $\cap$ PCMB  3.5034  4.593e-04
10                                              Golem  8.8807  6.646e-19
11                                               PCMB  5.1015  3.370e-07
12  Simplified Clinician Consensus $\cap$ Simplifi...  6.7090  1.959e-11
13                                    Simplified PCMB  7.7323  1.056e-14
14                   Clinician Consensus $\cap$ Golem  5.0653  4.077e-07
15                                   Simplified Golem  6.7127  1.910e-11
16                                  Golem $\cup$ PCMB  5.9383  2.880e-09
17            Simplified Golem $\cap$ Simplified PCMB  6.9614  3.368e-12
18  Simplified Clinician Consensus $\cap$ Simplifi...  5.6334  1.766e-08

## Summary: Generative LGBN vs XGBoost across all experiments

In [16]:
def extract_mean(s):
    """Extract the point estimate from a string like '0.76 (0.72, 0.80)'."""
    return float(str(s).split(' ')[0])


summary_rows = []
for experiment, df in [
    ('All Features',              pd.DataFrame(results1)),
    ('No Drugs',                  pd.DataFrame(results2)),
    ('No Drugs or Interventions', pd.DataFrame(results3)),
]:
    for model_name in ['Generative LGBN', 'XGB']:
        sub = df[df['Model'] == model_name].copy()
        sub['_ap'] = sub['Average Precision'].apply(extract_mean)
        best = sub.loc[sub['_ap'].idxmax()]
        summary_rows.append({
            'Experiment':         experiment,
            'Model':              model_name,
            'Best DAG':           best['DAG'],
            'Average Precision':  best['Average Precision'],
            'AUROC':              best['AUROC'],
            'ECE':                best['ECE'],
            '# Features':        best['# Features'],
        })

summary_df = pd.DataFrame(summary_rows)
summary_df.to_csv('Generative LGBN - Summary.csv', index=False)
summary_df

,Experiment,Model,Best DAG,Average Precision,AUROC,ECE,# Features
0,All Features,Generative LGBN,Clinician Consensus $\cap$ PCMB,"0.59 (0.55, 0.64)","0.82 (0.79, 0.84)",0.078,20
1,All Features,XGB,Control,"0.81 (0.78, 0.84)","0.93 (0.91, 0.95)",0.089,811
2,No Drugs,Generative LGBN,Clinician Consensus $\cap$ PCMB,"0.57 (0.52, 0.61)","0.80 (0.77, 0.83)",0.098,14
3,No Drugs,XGB,Control,"0.80 (0.77, 0.83)","0.92 (0.91, 0.94)",0.090,624
4,No Drugs or Interventions,Generative LGBN,Clinician Consensus $\cap$ PCMB,"0.57 (0.52, 0.61)","0.80 (0.77, 0.83)",0.098,14
5,No Drugs or Interventions,XGB,Control,"0.78 (0.75, 0.82)","0.92 (0.90, 0.93)",0.093,521