# DAG Parameterization – Year Sensitivity Analysis
Evaluates whether model performance is stable across the three cohort years in the test set (2020, 2021, 2022).
The test set covers patients admitted on or after 2020; temporal stability suggests the model generalises without year-specific drift.

In [1]:
# Data manipulation and plotting
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import re
import glob

# Metrics
from sklearn.metrics import roc_auc_score, average_precision_score, brier_score_loss, balanced_accuracy_score
from sklearn.calibration import calibration_curve
from pycalib.metrics import ECE

import xgboost

## Data preparation

In [2]:
# Load training data
X_train = pd.read_csv('../../Data Pre-processing/X_train_c12_w48_imp.csv', index_col=0)
X_test  = pd.read_csv('../../Data Pre-processing/X_test_c12_w48_imp.csv',  index_col=0)

print(X_train.shape, X_test.shape)

# Remove features with near-zero variance
X_train = X_train.loc[:, X_train.var() >= 0.01]
X_test  = X_test.filter(items=X_train.columns)
print(X_train.shape, X_test.shape)

# MICE-imputed training set (used for DAG feature selection)
X_train_imp = pd.read_csv('../../Data Pre-processing/X_train_c12_w48_mice.csv', index_col=0)

y_train = pd.read_csv('../../Data Pre-processing/y_train_c12_w48_imp.csv', index_col=[0,1]).groupby('uid').max()
y_test  = pd.read_csv('../../Data Pre-processing/y_test_c12_w48_imp.csv',  index_col=[0,1]).groupby('uid').max()

# Correlation-based feature selection (threshold used in original experiments)
correlation_threshold = 0.3
X_train_corr = X_train_imp.loc[:, X_train_imp.corrwith(y_train['Outcome']).abs() >= correlation_threshold]
print('Correlation-filtered features:', X_train_corr.shape)

(13054, 990) (3895, 990)
(13054, 811) (3895, 811)

Correlation-filtered features: (13054, 113)

## Year-split test sets
Join admission year from `patients.parquet` to the test UIDs and partition into 2020 / 2021 / 2022 subsets.

In [3]:
# Load admission-year metadata
patients = pd.read_parquet('../../Data Pre-processing/Preprocessing/data/real_cohort/patients.parquet')
uid_year = patients.set_index('uid')['arrive_yr']

# Map years onto test UIDs — UIDs absent from patients.parquet get NaN
test_years = uid_year.reindex(X_test.index)

n_missing = int(test_years.isna().sum())
print(f'Test UIDs without year info: {n_missing} (included in "All" evaluation only)')

# Create per-year subsets
TEST_YEARS = [2020, 2021, 2022]
X_test_by_year = {yr: X_test[test_years == yr] for yr in TEST_YEARS}
y_test_by_year = {yr: y_test[test_years == yr] for yr in TEST_YEARS}

print('\nTest set year distribution:')
for yr in TEST_YEARS:
    n     = len(X_test_by_year[yr])
    n_pos = int(y_test_by_year[yr]['Outcome'].sum())
    print(f'  {yr}: {n:5d} patients, {n_pos:3d} positive outcomes ({n_pos/n*100:.1f}%)')
n_all = len(X_test)
n_pos_all = int(y_test.Outcome.sum())
print(f'  All : {n_all:5d} patients, {n_pos_all:3d} positive outcomes ({n_pos_all/n_all*100:.1f}%)')

Test UIDs without year info: 154 (included in "All" evaluation only)

Test set year distribution:
  2020:  1060 patients, 148 positive outcomes (14.0%)
  2021:  1332 patients, 139 positive outcomes (10.4%)
  2022:  1349 patients, 122 positive outcomes (9.0%)
  All :  3895 patients, 431 positive outcomes (11.1%)

## Loading DAGs

In [4]:
# Load all adjacency files
adjacency_files = glob.glob("../DAGs/*_adjacency.csv")

dags = {}
dags['Control']     = nx.from_edgelist([(col, 'Outcome') for col in X_train_imp.columns.str.replace(r'(_.+)?$', '', regex=True).unique().tolist() if col != 'Outcome'], create_using=nx.DiGraph())
dags['Correlation'] = nx.from_edgelist([(col, 'Outcome') for col in X_train_corr.columns.str.replace(r'(_.+)?$', '', regex=True).unique().tolist() if col != 'Outcome'], create_using=nx.DiGraph())
for file in adjacency_files:
    dag_name = re.search(r'../DAGs/(.*)_adjacency.csv', file).group(1)
    dag_name = dag_name.replace('x', '$\\cap$')
    dag_name = dag_name.replace(' + ', ' $\\cup$ ')
    dags[dag_name] = nx.DiGraph(pd.read_csv(file, index_col=0))

dags.pop('Golem $\\cap$ PCMB')  # Remove problematic DAG (0 nodes associated with Outcome)
print('DAGs loaded:', list(dags.keys()))

DAGs loaded: ['Control', 'Correlation', 'Clinician Consensus $\\cup$ Golem', 'Simplified Clinician Consensus $\\cup$ Simplified PCMB', 'Simplified Clinician Consensus $\\cup$ Simplified Golem', 'Clinician Consensus $\\cup$ PCMB', 'Simplified Golem $\\cup$ Simplified PCMB', 'Clinician Consensus', 'Simplified Clinician Consensus', 'Clinician Consensus $\\cap$ PCMB', 'Golem', 'PCMB', 'Simplified Clinician Consensus $\\cap$ Simplified PCMB', 'Simplified PCMB', 'Clinician Consensus $\\cap$ Golem', 'Simplified Golem', 'Golem $\\cup$ PCMB', 'Simplified Golem $\\cap$ Simplified PCMB', 'Simplified Clinician Consensus $\\cap$ Simplified Golem']

## Helper functions

In [5]:
from MLstatkit import Bootstrapping

def performance_report(X, y, model):
    y_prob = model.predict_proba(X)[:, 1]

    n_bootstraps = 1000
    ap,        ap_lower,        ap_upper        = Bootstrapping(y.values, y_prob, metric_str='average_precision', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    auroc,     auroc_lower,     auroc_upper     = Bootstrapping(y.values, y_prob, metric_str='roc_auc',           n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    precision, precision_lower, precision_upper = Bootstrapping(y.values, y_prob, metric_str='precision',         n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    recall,    recall_lower,    recall_upper    = Bootstrapping(y.values, y_prob, metric_str='recall',            n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    f1,        f1_lower,        f1_upper        = Bootstrapping(y.values, y_prob, metric_str='f1',                n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    accuracy,  accuracy_lower,  accuracy_upper  = Bootstrapping(y.values, y_prob, metric_str='accuracy',          n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    ece = ECE(y.values, y_prob.reshape(-1, 1), bins=50)

    return {
        'Average Precision': f"{ap:.2f} ({ap_lower:.2f}, {ap_upper:.2f})",
        'AUROC':             f"{auroc:.2f} ({auroc_lower:.2f}, {auroc_upper:.2f})",
        'Precision':         f"{precision:.2f} ({precision_lower:.2f}, {precision_upper:.2f})",
        'Recall':            f"{recall:.2f} ({recall_lower:.2f}, {recall_upper:.2f})",
        'F1 Score':          f"{f1:.2f} ({f1_lower:.2f}, {f1_upper:.2f})",
        'Accuracy':          f"{accuracy:.2f} ({accuracy_lower:.2f}, {accuracy_upper:.2f})",
        'ECE':               f"{ece:.3f}",
    }

## Training function with year-stratified evaluation
Trains models on the full training set (identical to Experiment 1 in the main notebook) and then evaluates each trained model on:
- The full test set (`Year = 'All'`)
- Each year-split subset (`Year = 2020 / 2021 / 2022`)

In [6]:
def train_models_year_sensitivity(remove_drugs=False, remove_interventions=False):
    results = []
    preds_by_dag = {}  # {dag_name: {year_label: (y_true, y_prob)}}

    drugs = [
        'Midazolam', 'Fentanyl', 'Olanzapine', 'Haloperidol',
        'Dexmedetomidine', 'Lorazepam', 'Morphine', 'Hydromorphone',
        'Dopamine', 'Cisatracurium', 'Epinephrine', 'Norepinephrine',
        'Milrinone', 'Dobutamine',
    ]
    intervention_nodes = [
        'CRRT Therapy Type', 'ECMO Type', 'Ventilated',
        'Pupillary Reaction', 'Peds Coma Score', 'Endotracheal tube',
    ]

    for dag_name, dag in dags.items():
        if 'Simplified' not in dag_name and dag_name not in ['Control', 'Correlation']:
            continue

        print(f"Processing {dag_name} ({dag.number_of_nodes()} nodes, {dag.number_of_edges()} edges)")

        nodes_in_dag = list(dag.nodes())

        if 'Simplified' in dag_name or dag_name in ['Control', 'Correlation']:
            if remove_drugs:
                nodes_in_dag = [n for n in nodes_in_dag if n not in drugs]
            if remove_interventions:
                nodes_in_dag = [n for n in nodes_in_dag if n not in intervention_nodes]

            if dag_name == 'Correlation':
                features_in_dag = [col for col in X_train_corr.columns
                                   if any(re.search(rf'^{node}(_.+)?$', col) for node in nodes_in_dag)]
            else:
                features_in_dag = [col for col in X_train_imp.columns
                                   if any(re.search(rf'^{node}(_.+)?$', col) for node in nodes_in_dag)]

            n_biomarkers = len(nodes_in_dag) - 1

        else:
            if remove_drugs:
                nodes_in_dag = [n for n in nodes_in_dag if not any(d in n for d in drugs)]
            if remove_interventions:
                nodes_in_dag = [n for n in nodes_in_dag if not any(iv in n for iv in intervention_nodes)]

            features_in_dag = X_train_imp.filter(items=nodes_in_dag).columns.tolist()
            n_biomarkers = (X_train_imp.filter(items=nodes_in_dag)
                            .columns.str.replace(r'(_.+)?$', '', regex=True).nunique() - 1)

        # Train XGBoost
        xgb = xgboost.XGBClassifier(objective='binary:logistic', random_state=42, eval_metric='aucpr')
        xgb.fit(X_train.filter(features_in_dag), y_train.Outcome)

        # Evaluate on full test set and each year subset; store raw predictions for permutation tests
        eval_sets = [('All', X_test.filter(features_in_dag), y_test.Outcome)]
        for yr in TEST_YEARS:
            eval_sets.append((yr, X_test_by_year[yr].filter(features_in_dag), y_test_by_year[yr].Outcome))

        preds_by_dag[dag_name] = {}
        for year_label, X_eval, y_eval in eval_sets:
            y_prob = xgb.predict_proba(X_eval)[:, 1]
            preds_by_dag[dag_name][year_label] = (y_eval.values, y_prob)

            row = {'Model': 'XGB', 'DAG': dag_name, 'Year': year_label,
                   '# Features': len(features_in_dag), '# Biomarkers': n_biomarkers}
            row.update(performance_report(X_eval, y_eval, xgb))
            results.append(row)

    return pd.DataFrame(results), preds_by_dag

## Run year sensitivity experiment
Mirrors Experiment 1 from the main notebook (no drugs or interventions removed) with year-stratified evaluation.

In [7]:
results_df, preds_by_dag = train_models_year_sensitivity(remove_drugs=False, remove_interventions=False)

Processing Control (46 nodes, 45 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1283.82it/s]

Bootstrapping average_precision:  26%|██▌       | 258/1000 [00:00<00:00, 1285.58it/s]

Bootstrapping average_precision:  39%|███▊      | 387/1000 [00:00<00:00, 1277.86it/s]

Bootstrapping average_precision:  52%|█████▏    | 515/1000 [00:00<00:00, 1243.61it/s]

Bootstrapping average_precision:  64%|██████▍   | 643/1000 [00:00<00:00, 1255.49it/s]

Bootstrapping average_precision:  78%|███████▊  | 775/1000 [00:00<00:00, 1274.30it/s]

Bootstrapping average_precision:  91%|█████████ | 907/1000 [00:00<00:00, 1286.86it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1228.98it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 77/1000 [00:00<00:01, 769.36it/s]

Bootstrapping roc_auc:  16%|█▌        | 160/1000 [00:00<00:01, 801.12it/s]

Bootstrapping roc_auc:  24%|██▍       | 242/1000 [00:00<00:00, 807.31it/s]

Bootstrapping roc_auc:  33%|███▎      | 327/1000 [00:00<00:00, 820.65it/s]

Bootstrapping roc_auc:  41%|████      | 410/1000 [00:00<00:00, 808.24it/s]

Bootstrapping roc_auc:  49%|████▉     | 491/1000 [00:00<00:00, 752.23it/s]

Bootstrapping roc_auc:  57%|█████▋    | 567/1000 [00:00<00:00, 745.34it/s]

Bootstrapping roc_auc:  65%|██████▍   | 647/1000 [00:00<00:00, 761.88it/s]

Bootstrapping roc_auc:  73%|███████▎  | 727/1000 [00:00<00:00, 771.18it/s]

Bootstrapping roc_auc:  81%|████████  | 808/1000 [00:01<00:00, 782.22it/s]

Bootstrapping roc_auc:  89%|████████▊ | 887/1000 [00:01<00:00, 784.31it/s]

Bootstrapping roc_auc:  97%|█████████▋| 968/1000 [00:01<00:00, 790.36it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 783.71it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 113/1000 [00:00<00:00, 1123.28it/s]

Bootstrapping precision:  23%|██▎       | 228/1000 [00:00<00:00, 1133.67it/s]

Bootstrapping precision:  35%|███▍      | 346/1000 [00:00<00:00, 1149.72it/s]

Bootstrapping precision:  46%|████▌     | 461/1000 [00:00<00:00, 1138.95it/s]

Bootstrapping precision:  58%|█████▊    | 576/1000 [00:00<00:00, 1141.58it/s]

Bootstrapping precision:  69%|██████▉   | 691/1000 [00:00<00:00, 1140.52it/s]

Bootstrapping precision:  81%|████████  | 806/1000 [00:00<00:00, 1140.61it/s]

Bootstrapping precision:  92%|█████████▏| 922/1000 [00:00<00:00, 1144.98it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1143.80it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1159.57it/s]

Bootstrapping recall:  23%|██▎       | 232/1000 [00:00<00:00, 1153.55it/s]

Bootstrapping recall:  35%|███▌      | 350/1000 [00:00<00:00, 1163.67it/s]

Bootstrapping recall:  47%|████▋     | 467/1000 [00:00<00:00, 1155.03it/s]

Bootstrapping recall:  58%|█████▊    | 583/1000 [00:00<00:00, 1131.83it/s]

Bootstrapping recall:  70%|██████▉   | 697/1000 [00:00<00:00, 1127.48it/s]

Bootstrapping recall:  82%|████████▏ | 816/1000 [00:00<00:00, 1144.50it/s]

Bootstrapping recall:  93%|█████████▎| 932/1000 [00:00<00:00, 1147.75it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1142.55it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 111/1000 [00:00<00:00, 1108.26it/s]

Bootstrapping f1:  22%|██▏       | 223/1000 [00:00<00:00, 1112.41it/s]

Bootstrapping f1:  34%|███▎      | 336/1000 [00:00<00:00, 1119.49it/s]

Bootstrapping f1:  45%|████▌     | 452/1000 [00:00<00:00, 1132.95it/s]

Bootstrapping f1:  57%|█████▋    | 566/1000 [00:00<00:00, 1130.96it/s]

Bootstrapping f1:  68%|██████▊   | 680/1000 [00:00<00:00, 1124.40it/s]

Bootstrapping f1:  79%|███████▉  | 793/1000 [00:00<00:00, 1119.74it/s]

Bootstrapping f1:  90%|█████████ | 905/1000 [00:00<00:00, 1118.79it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1121.16it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 327/1000 [00:00<00:00, 3267.88it/s]

Bootstrapping accuracy:  65%|██████▌   | 654/1000 [00:00<00:00, 3243.75it/s]

Bootstrapping accuracy:  98%|█████████▊| 983/1000 [00:00<00:00, 3257.73it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3244.31it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  19%|█▉        | 194/1000 [00:00<00:00, 1936.63it/s]

Bootstrapping average_precision:  39%|███▉      | 389/1000 [00:00<00:00, 1941.74it/s]

Bootstrapping average_precision:  59%|█████▉    | 589/1000 [00:00<00:00, 1965.28it/s]

Bootstrapping average_precision:  80%|███████▉  | 795/1000 [00:00<00:00, 2001.26it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2000.95it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 124/1000 [00:00<00:00, 1237.50it/s]

Bootstrapping roc_auc:  25%|██▍       | 248/1000 [00:00<00:00, 1197.84it/s]

Bootstrapping roc_auc:  37%|███▋      | 368/1000 [00:00<00:00, 1180.03it/s]

Bootstrapping roc_auc:  49%|████▊     | 487/1000 [00:00<00:00, 1171.19it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 1176.49it/s]

Bootstrapping roc_auc:  72%|███████▎  | 725/1000 [00:00<00:00, 1178.14it/s]

Bootstrapping roc_auc:  85%|████████▍ | 848/1000 [00:00<00:00, 1194.06it/s]

Bootstrapping roc_auc:  97%|█████████▋| 971/1000 [00:00<00:00, 1203.89it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1192.06it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 138/1000 [00:00<00:00, 1377.48it/s]

Bootstrapping precision:  28%|██▊       | 276/1000 [00:00<00:00, 1312.01it/s]

Bootstrapping precision:  41%|████      | 410/1000 [00:00<00:00, 1320.68it/s]

Bootstrapping precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1318.45it/s]

Bootstrapping precision:  68%|██████▊   | 675/1000 [00:00<00:00, 1309.09it/s]

Bootstrapping precision:  81%|████████  | 806/1000 [00:00<00:00, 1300.95it/s]

Bootstrapping precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1305.86it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1313.42it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 140/1000 [00:00<00:00, 1399.08it/s]

Bootstrapping recall:  28%|██▊       | 281/1000 [00:00<00:00, 1402.59it/s]

Bootstrapping recall:  42%|████▏     | 422/1000 [00:00<00:00, 1395.22it/s]

Bootstrapping recall:  56%|█████▌    | 562/1000 [00:00<00:00, 1393.21it/s]

Bootstrapping recall:  70%|███████   | 702/1000 [00:00<00:00, 1378.34it/s]

Bootstrapping recall:  84%|████████▍ | 841/1000 [00:00<00:00, 1381.72it/s]

Bootstrapping recall:  98%|█████████▊| 980/1000 [00:00<00:00, 1365.07it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1375.33it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▎        | 137/1000 [00:00<00:00, 1363.33it/s]

Bootstrapping f1:  27%|██▋       | 274/1000 [00:00<00:00, 1329.52it/s]

Bootstrapping f1:  41%|████      | 408/1000 [00:00<00:00, 1298.31it/s]

Bootstrapping f1:  54%|█████▍    | 538/1000 [00:00<00:00, 1283.79it/s]

Bootstrapping f1:  67%|██████▋   | 667/1000 [00:00<00:00, 1280.34it/s]

Bootstrapping f1:  80%|████████  | 802/1000 [00:00<00:00, 1301.66it/s]

Bootstrapping f1:  94%|█████████▍| 940/1000 [00:00<00:00, 1325.87it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1307.09it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  38%|███▊      | 382/1000 [00:00<00:00, 3814.01it/s]

Bootstrapping accuracy:  77%|███████▋  | 770/1000 [00:00<00:00, 3850.31it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3815.70it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 195/1000 [00:00<00:00, 1947.78it/s]

Bootstrapping average_precision:  39%|███▉      | 390/1000 [00:00<00:00, 1919.42it/s]

Bootstrapping average_precision:  58%|█████▊    | 582/1000 [00:00<00:00, 1909.69it/s]

Bootstrapping average_precision:  77%|███████▋  | 773/1000 [00:00<00:00, 1905.97it/s]

Bootstrapping average_precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1889.54it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1900.97it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 119/1000 [00:00<00:00, 1183.10it/s]

Bootstrapping roc_auc:  24%|██▍       | 238/1000 [00:00<00:00, 1136.01it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 1126.56it/s]

Bootstrapping roc_auc:  46%|████▋     | 465/1000 [00:00<00:00, 1124.45it/s]

Bootstrapping roc_auc:  58%|█████▊    | 578/1000 [00:00<00:00, 1124.87it/s]

Bootstrapping roc_auc:  69%|██████▉   | 691/1000 [00:00<00:00, 1119.15it/s]

Bootstrapping roc_auc:  81%|████████  | 806/1000 [00:00<00:00, 1128.18it/s]

Bootstrapping roc_auc:  92%|█████████▎| 925/1000 [00:00<00:00, 1147.11it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1138.39it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▎        | 135/1000 [00:00<00:00, 1347.36it/s]

Bootstrapping precision:  27%|██▋       | 270/1000 [00:00<00:00, 1311.97it/s]

Bootstrapping precision:  40%|████      | 402/1000 [00:00<00:00, 1298.79it/s]

Bootstrapping precision:  53%|█████▎    | 532/1000 [00:00<00:00, 1292.21it/s]

Bootstrapping precision:  67%|██████▋   | 666/1000 [00:00<00:00, 1308.24it/s]

Bootstrapping precision:  80%|████████  | 803/1000 [00:00<00:00, 1328.77it/s]

Bootstrapping precision:  94%|█████████▍| 940/1000 [00:00<00:00, 1341.59it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1326.08it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 134/1000 [00:00<00:00, 1338.81it/s]

Bootstrapping recall:  27%|██▋       | 270/1000 [00:00<00:00, 1350.02it/s]

Bootstrapping recall:  41%|████      | 408/1000 [00:00<00:00, 1361.59it/s]

Bootstrapping recall:  55%|█████▍    | 545/1000 [00:00<00:00, 1364.28it/s]

Bootstrapping recall:  68%|██████▊   | 683/1000 [00:00<00:00, 1369.10it/s]

Bootstrapping recall:  82%|████████▏ | 820/1000 [00:00<00:00, 1366.92it/s]

Bootstrapping recall:  96%|█████████▌| 957/1000 [00:00<00:00, 1364.29it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1361.69it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▎        | 136/1000 [00:00<00:00, 1357.05it/s]

Bootstrapping f1:  27%|██▋       | 272/1000 [00:00<00:00, 1350.00it/s]

Bootstrapping f1:  41%|████      | 409/1000 [00:00<00:00, 1358.20it/s]

Bootstrapping f1:  55%|█████▍    | 545/1000 [00:00<00:00, 1356.88it/s]

Bootstrapping f1:  68%|██████▊   | 684/1000 [00:00<00:00, 1367.88it/s]

Bootstrapping f1:  82%|████████▏ | 823/1000 [00:00<00:00, 1373.14it/s]

Bootstrapping f1:  96%|█████████▌| 962/1000 [00:00<00:00, 1376.55it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1366.61it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 409/1000 [00:00<00:00, 4081.82it/s]

Bootstrapping accuracy:  82%|████████▏ | 818/1000 [00:00<00:00, 4077.60it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4082.19it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 200/1000 [00:00<00:00, 1989.42it/s]

Bootstrapping average_precision:  40%|███▉      | 399/1000 [00:00<00:00, 1961.49it/s]

Bootstrapping average_precision:  60%|█████▉    | 599/1000 [00:00<00:00, 1974.85it/s]

Bootstrapping average_precision:  80%|███████▉  | 797/1000 [00:00<00:00, 1969.82it/s]

Bootstrapping average_precision:  99%|█████████▉| 994/1000 [00:00<00:00, 1959.01it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1961.25it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 120/1000 [00:00<00:00, 1198.49it/s]

Bootstrapping roc_auc:  24%|██▍       | 240/1000 [00:00<00:00, 1193.89it/s]

Bootstrapping roc_auc:  36%|███▌      | 360/1000 [00:00<00:00, 1181.21it/s]

Bootstrapping roc_auc:  48%|████▊     | 479/1000 [00:00<00:00, 1179.75it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 1175.31it/s]

Bootstrapping roc_auc:  72%|███████▏  | 717/1000 [00:00<00:00, 1182.14it/s]

Bootstrapping roc_auc:  84%|████████▍ | 838/1000 [00:00<00:00, 1188.77it/s]

Bootstrapping roc_auc:  96%|█████████▌| 959/1000 [00:00<00:00, 1194.87it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1187.69it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 139/1000 [00:00<00:00, 1385.75it/s]

Bootstrapping precision:  28%|██▊       | 278/1000 [00:00<00:00, 1386.30it/s]

Bootstrapping precision:  42%|████▏     | 417/1000 [00:00<00:00, 1377.70it/s]

Bootstrapping precision:  56%|█████▌    | 557/1000 [00:00<00:00, 1386.19it/s]

Bootstrapping precision:  70%|██████▉   | 697/1000 [00:00<00:00, 1391.11it/s]

Bootstrapping precision:  84%|████████▎ | 837/1000 [00:00<00:00, 1377.87it/s]

Bootstrapping precision:  98%|█████████▊| 975/1000 [00:00<00:00, 1365.75it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1373.46it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 138/1000 [00:00<00:00, 1373.89it/s]

Bootstrapping recall:  28%|██▊       | 276/1000 [00:00<00:00, 1367.12it/s]

Bootstrapping recall:  41%|████▏     | 413/1000 [00:00<00:00, 1361.78it/s]

Bootstrapping recall:  55%|█████▌    | 550/1000 [00:00<00:00, 1362.13it/s]

Bootstrapping recall:  69%|██████▊   | 687/1000 [00:00<00:00, 1361.56it/s]

Bootstrapping recall:  83%|████████▎ | 828/1000 [00:00<00:00, 1375.34it/s]

Bootstrapping recall:  97%|█████████▋| 970/1000 [00:00<00:00, 1389.05it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1375.88it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 141/1000 [00:00<00:00, 1400.79it/s]

Bootstrapping f1:  28%|██▊       | 282/1000 [00:00<00:00, 1390.32it/s]

Bootstrapping f1:  42%|████▏     | 422/1000 [00:00<00:00, 1390.10it/s]

Bootstrapping f1:  56%|█████▌    | 562/1000 [00:00<00:00, 1393.71it/s]

Bootstrapping f1:  70%|███████   | 703/1000 [00:00<00:00, 1396.81it/s]

Bootstrapping f1:  84%|████████▍ | 843/1000 [00:00<00:00, 1391.50it/s]

Bootstrapping f1:  98%|█████████▊| 983/1000 [00:00<00:00, 1392.12it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1390.88it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 411/1000 [00:00<00:00, 4103.26it/s]

Bootstrapping accuracy:  82%|████████▏ | 822/1000 [00:00<00:00, 4098.45it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4082.05it/s]

Processing Correlation (38 nodes, 37 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1324.35it/s]

Bootstrapping average_precision:  27%|██▋       | 267/1000 [00:00<00:00, 1332.43it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 1322.13it/s]

Bootstrapping average_precision:  54%|█████▎    | 535/1000 [00:00<00:00, 1327.60it/s]

Bootstrapping average_precision:  67%|██████▋   | 669/1000 [00:00<00:00, 1329.51it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1307.83it/s]

Bootstrapping average_precision:  93%|█████████▎| 933/1000 [00:00<00:00, 1293.11it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1307.37it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 82/1000 [00:00<00:01, 817.38it/s]

Bootstrapping roc_auc:  16%|█▋        | 165/1000 [00:00<00:01, 821.82it/s]

Bootstrapping roc_auc:  25%|██▍       | 248/1000 [00:00<00:00, 817.20it/s]

Bootstrapping roc_auc:  33%|███▎      | 330/1000 [00:00<00:00, 807.86it/s]

Bootstrapping roc_auc:  41%|████      | 411/1000 [00:00<00:00, 803.73it/s]

Bootstrapping roc_auc:  49%|████▉     | 494/1000 [00:00<00:00, 809.99it/s]

Bootstrapping roc_auc:  58%|█████▊    | 577/1000 [00:00<00:00, 813.28it/s]

Bootstrapping roc_auc:  66%|██████▌   | 661/1000 [00:00<00:00, 819.22it/s]

Bootstrapping roc_auc:  74%|███████▍  | 744/1000 [00:00<00:00, 819.03it/s]

Bootstrapping roc_auc:  83%|████████▎ | 827/1000 [00:01<00:00, 821.91it/s]

Bootstrapping roc_auc:  91%|█████████ | 910/1000 [00:01<00:00, 822.29it/s]

Bootstrapping roc_auc:  99%|█████████▉| 993/1000 [00:01<00:00, 817.31it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 815.37it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1153.89it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1139.28it/s]

Bootstrapping precision:  35%|███▍      | 348/1000 [00:00<00:00, 1146.64it/s]

Bootstrapping precision:  47%|████▋     | 466/1000 [00:00<00:00, 1156.13it/s]

Bootstrapping precision:  58%|█████▊    | 584/1000 [00:00<00:00, 1162.75it/s]

Bootstrapping precision:  70%|███████   | 702/1000 [00:00<00:00, 1165.56it/s]

Bootstrapping precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1176.06it/s]

Bootstrapping precision:  94%|█████████▍| 941/1000 [00:00<00:00, 1179.95it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1167.30it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1197.44it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1204.35it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1193.18it/s]

Bootstrapping recall:  48%|████▊     | 482/1000 [00:00<00:00, 1193.59it/s]

Bootstrapping recall:  60%|██████    | 602/1000 [00:00<00:00, 1185.25it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1192.05it/s]

Bootstrapping recall:  84%|████████▍ | 843/1000 [00:00<00:00, 1194.05it/s]

Bootstrapping recall:  96%|█████████▋| 965/1000 [00:00<00:00, 1200.48it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1195.53it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1195.53it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1186.63it/s]

Bootstrapping f1:  36%|███▌      | 360/1000 [00:00<00:00, 1190.85it/s]

Bootstrapping f1:  48%|████▊     | 481/1000 [00:00<00:00, 1195.20it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1197.48it/s]

Bootstrapping f1:  72%|███████▏  | 723/1000 [00:00<00:00, 1200.20it/s]

Bootstrapping f1:  84%|████████▍ | 844/1000 [00:00<00:00, 1195.25it/s]

Bootstrapping f1:  96%|█████████▋| 964/1000 [00:00<00:00, 1194.87it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1193.82it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 352/1000 [00:00<00:00, 3511.15it/s]

Bootstrapping accuracy:  70%|███████   | 704/1000 [00:00<00:00, 3505.77it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3498.18it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 198/1000 [00:00<00:00, 1971.44it/s]

Bootstrapping average_precision:  40%|███▉      | 396/1000 [00:00<00:00, 1960.82it/s]

Bootstrapping average_precision:  60%|██████    | 600/1000 [00:00<00:00, 1994.97it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 2005.71it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2002.91it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 117/1000 [00:00<00:00, 1161.30it/s]

Bootstrapping roc_auc:  24%|██▍       | 238/1000 [00:00<00:00, 1186.44it/s]

Bootstrapping roc_auc:  36%|███▌      | 360/1000 [00:00<00:00, 1198.41it/s]

Bootstrapping roc_auc:  48%|████▊     | 483/1000 [00:00<00:00, 1208.55it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 1219.52it/s]

Bootstrapping roc_auc:  73%|███████▎  | 730/1000 [00:00<00:00, 1222.53it/s]

Bootstrapping roc_auc:  85%|████████▌ | 854/1000 [00:00<00:00, 1228.17it/s]

Bootstrapping roc_auc:  98%|█████████▊| 980/1000 [00:00<00:00, 1235.67it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1218.74it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 142/1000 [00:00<00:00, 1417.57it/s]

Bootstrapping precision:  28%|██▊       | 284/1000 [00:00<00:00, 1384.40it/s]

Bootstrapping precision:  42%|████▏     | 423/1000 [00:00<00:00, 1377.60it/s]

Bootstrapping precision:  56%|█████▋    | 564/1000 [00:00<00:00, 1386.69it/s]

Bootstrapping precision:  71%|███████   | 706/1000 [00:00<00:00, 1395.35it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1402.19it/s]

Bootstrapping precision:  99%|█████████▉| 989/1000 [00:00<00:00, 1399.02it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1392.73it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1411.60it/s]

Bootstrapping recall:  28%|██▊       | 284/1000 [00:00<00:00, 1400.50it/s]

Bootstrapping recall:  42%|████▎     | 425/1000 [00:00<00:00, 1362.16it/s]

Bootstrapping recall:  56%|█████▌    | 562/1000 [00:00<00:00, 1340.96it/s]

Bootstrapping recall:  70%|██████▉   | 697/1000 [00:00<00:00, 1335.58it/s]

Bootstrapping recall:  83%|████████▎ | 831/1000 [00:00<00:00, 1305.49it/s]

Bootstrapping recall:  97%|█████████▋| 968/1000 [00:00<00:00, 1323.10it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1329.38it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 127/1000 [00:00<00:00, 1268.45it/s]

Bootstrapping f1:  26%|██▌       | 258/1000 [00:00<00:00, 1288.88it/s]

Bootstrapping f1:  39%|███▉      | 390/1000 [00:00<00:00, 1302.27it/s]

Bootstrapping f1:  52%|█████▏    | 521/1000 [00:00<00:00, 1161.63it/s]

Bootstrapping f1:  65%|██████▌   | 652/1000 [00:00<00:00, 1209.05it/s]

Bootstrapping f1:  79%|███████▉  | 788/1000 [00:00<00:00, 1255.40it/s]

Bootstrapping f1:  93%|█████████▎| 927/1000 [00:00<00:00, 1296.21it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1271.08it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|████      | 402/1000 [00:00<00:00, 4011.73it/s]

Bootstrapping accuracy:  80%|████████  | 804/1000 [00:00<00:00, 3917.99it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3920.26it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  19%|█▉        | 189/1000 [00:00<00:00, 1887.06it/s]

Bootstrapping average_precision:  38%|███▊      | 379/1000 [00:00<00:00, 1894.48it/s]

Bootstrapping average_precision:  57%|█████▋    | 573/1000 [00:00<00:00, 1914.23it/s]

Bootstrapping average_precision:  77%|███████▋  | 769/1000 [00:00<00:00, 1931.71it/s]

Bootstrapping average_precision:  96%|█████████▋| 965/1000 [00:00<00:00, 1938.80it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1925.40it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  11%|█▏        | 113/1000 [00:00<00:00, 1126.53it/s]

Bootstrapping roc_auc:  23%|██▎       | 230/1000 [00:00<00:00, 1146.59it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 1163.24it/s]

Bootstrapping roc_auc:  47%|████▋     | 468/1000 [00:00<00:00, 1170.97it/s]

Bootstrapping roc_auc:  59%|█████▊    | 587/1000 [00:00<00:00, 1176.25it/s]

Bootstrapping roc_auc:  70%|███████   | 705/1000 [00:00<00:00, 1173.14it/s]

Bootstrapping roc_auc:  82%|████████▏ | 823/1000 [00:00<00:00, 1175.10it/s]

Bootstrapping roc_auc:  94%|█████████▍| 941/1000 [00:00<00:00, 1154.30it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1155.43it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  13%|█▎        | 130/1000 [00:00<00:00, 1290.94it/s]

Bootstrapping precision:  26%|██▌       | 260/1000 [00:00<00:00, 1289.81it/s]

Bootstrapping precision:  39%|███▉      | 389/1000 [00:00<00:00, 1285.46it/s]

Bootstrapping precision:  52%|█████▏    | 518/1000 [00:00<00:00, 1282.69it/s]

Bootstrapping precision:  65%|██████▍   | 647/1000 [00:00<00:00, 1284.75it/s]

Bootstrapping precision:  78%|███████▊  | 777/1000 [00:00<00:00, 1287.89it/s]

Bootstrapping precision:  91%|█████████ | 907/1000 [00:00<00:00, 1291.35it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1289.62it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 139/1000 [00:00<00:00, 1384.51it/s]

Bootstrapping recall:  28%|██▊       | 278/1000 [00:00<00:00, 1382.00it/s]

Bootstrapping recall:  42%|████▏     | 417/1000 [00:00<00:00, 1359.48it/s]

Bootstrapping recall:  56%|█████▌    | 555/1000 [00:00<00:00, 1367.44it/s]

Bootstrapping recall:  69%|██████▉   | 693/1000 [00:00<00:00, 1370.96it/s]

Bootstrapping recall:  83%|████████▎ | 831/1000 [00:00<00:00, 1362.46it/s]

Bootstrapping recall:  97%|█████████▋| 968/1000 [00:00<00:00, 1339.63it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1353.38it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 133/1000 [00:00<00:00, 1321.67it/s]

Bootstrapping f1:  27%|██▋       | 267/1000 [00:00<00:00, 1332.33it/s]

Bootstrapping f1:  41%|████      | 406/1000 [00:00<00:00, 1358.01it/s]

Bootstrapping f1:  55%|█████▍    | 547/1000 [00:00<00:00, 1376.38it/s]

Bootstrapping f1:  69%|██████▉   | 688/1000 [00:00<00:00, 1386.36it/s]

Bootstrapping f1:  83%|████████▎ | 827/1000 [00:00<00:00, 1370.16it/s]

Bootstrapping f1:  96%|█████████▋| 965/1000 [00:00<00:00, 1370.17it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1365.06it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 411/1000 [00:00<00:00, 4105.52it/s]

Bootstrapping accuracy:  82%|████████▏ | 822/1000 [00:00<00:00, 4042.72it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4029.74it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  19%|█▉        | 192/1000 [00:00<00:00, 1915.38it/s]

Bootstrapping average_precision:  38%|███▊      | 384/1000 [00:00<00:00, 1855.60it/s]

Bootstrapping average_precision:  58%|█████▊    | 580/1000 [00:00<00:00, 1898.94it/s]

Bootstrapping average_precision:  78%|███████▊  | 780/1000 [00:00<00:00, 1935.75it/s]

Bootstrapping average_precision:  98%|█████████▊| 980/1000 [00:00<00:00, 1958.60it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1932.21it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 120/1000 [00:00<00:00, 1192.38it/s]

Bootstrapping roc_auc:  24%|██▍       | 240/1000 [00:00<00:00, 1185.28it/s]

Bootstrapping roc_auc:  36%|███▌      | 359/1000 [00:00<00:00, 1181.22it/s]

Bootstrapping roc_auc:  48%|████▊     | 478/1000 [00:00<00:00, 1182.24it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 1181.60it/s]

Bootstrapping roc_auc:  72%|███████▏  | 716/1000 [00:00<00:00, 1182.66it/s]

Bootstrapping roc_auc:  84%|████████▎ | 835/1000 [00:00<00:00, 1184.83it/s]

Bootstrapping roc_auc:  95%|█████████▌| 954/1000 [00:00<00:00, 1176.65it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1178.92it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▎        | 137/1000 [00:00<00:00, 1368.59it/s]

Bootstrapping precision:  28%|██▊       | 277/1000 [00:00<00:00, 1386.22it/s]

Bootstrapping precision:  42%|████▏     | 417/1000 [00:00<00:00, 1387.62it/s]

Bootstrapping precision:  56%|█████▌    | 556/1000 [00:00<00:00, 1379.73it/s]

Bootstrapping precision:  69%|██████▉   | 694/1000 [00:00<00:00, 1373.55it/s]

Bootstrapping precision:  83%|████████▎ | 833/1000 [00:00<00:00, 1375.64it/s]

Bootstrapping precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1375.68it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1373.04it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 138/1000 [00:00<00:00, 1376.94it/s]

Bootstrapping recall:  28%|██▊       | 276/1000 [00:00<00:00, 1333.02it/s]

Bootstrapping recall:  41%|████      | 410/1000 [00:00<00:00, 1327.71it/s]

Bootstrapping recall:  55%|█████▍    | 547/1000 [00:00<00:00, 1341.51it/s]

Bootstrapping recall:  68%|██████▊   | 682/1000 [00:00<00:00, 1336.71it/s]

Bootstrapping recall:  82%|████████▏ | 817/1000 [00:00<00:00, 1340.72it/s]

Bootstrapping recall:  96%|█████████▌| 957/1000 [00:00<00:00, 1357.87it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1346.84it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▎        | 137/1000 [00:00<00:00, 1365.19it/s]

Bootstrapping f1:  28%|██▊       | 278/1000 [00:00<00:00, 1390.38it/s]

Bootstrapping f1:  42%|████▏     | 419/1000 [00:00<00:00, 1397.55it/s]

Bootstrapping f1:  56%|█████▌    | 559/1000 [00:00<00:00, 1391.61it/s]

Bootstrapping f1:  70%|███████   | 700/1000 [00:00<00:00, 1394.54it/s]

Bootstrapping f1:  84%|████████▍ | 840/1000 [00:00<00:00, 1393.27it/s]

Bootstrapping f1:  98%|█████████▊| 982/1000 [00:00<00:00, 1400.61it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1392.35it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|████      | 400/1000 [00:00<00:00, 3999.96it/s]

Bootstrapping accuracy:  81%|████████  | 807/1000 [00:00<00:00, 4040.97it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4040.60it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB (20 nodes, 53 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1332.78it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1332.59it/s]

Bootstrapping average_precision:  40%|████      | 403/1000 [00:00<00:00, 1337.64it/s]

Bootstrapping average_precision:  54%|█████▍    | 540/1000 [00:00<00:00, 1346.74it/s]

Bootstrapping average_precision:  68%|██████▊   | 675/1000 [00:00<00:00, 1340.35it/s]

Bootstrapping average_precision:  81%|████████  | 811/1000 [00:00<00:00, 1344.00it/s]

Bootstrapping average_precision:  95%|█████████▍| 947/1000 [00:00<00:00, 1347.41it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1343.95it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 852.67it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 849.61it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 850.46it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 837.15it/s]

Bootstrapping roc_auc:  43%|████▎     | 428/1000 [00:00<00:00, 825.66it/s]

Bootstrapping roc_auc:  51%|█████     | 511/1000 [00:00<00:00, 821.29it/s]

Bootstrapping roc_auc:  59%|█████▉    | 594/1000 [00:00<00:00, 810.92it/s]

Bootstrapping roc_auc:  68%|██████▊   | 676/1000 [00:00<00:00, 803.04it/s]

Bootstrapping roc_auc:  76%|███████▌  | 759/1000 [00:00<00:00, 809.15it/s]

Bootstrapping roc_auc:  84%|████████▍ | 840/1000 [00:01<00:00, 807.90it/s]

Bootstrapping roc_auc:  92%|█████████▏| 921/1000 [00:01<00:00, 802.19it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 816.03it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1144.21it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1113.79it/s]

Bootstrapping precision:  35%|███▍      | 349/1000 [00:00<00:00, 1144.75it/s]

Bootstrapping precision:  46%|████▋     | 465/1000 [00:00<00:00, 1148.70it/s]

Bootstrapping precision:  58%|█████▊    | 581/1000 [00:00<00:00, 1152.27it/s]

Bootstrapping precision:  70%|██████▉   | 697/1000 [00:00<00:00, 1153.06it/s]

Bootstrapping precision:  81%|████████▏ | 813/1000 [00:00<00:00, 1147.53it/s]

Bootstrapping precision:  93%|█████████▎| 928/1000 [00:00<00:00, 1145.06it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1146.14it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1152.95it/s]

Bootstrapping recall:  23%|██▎       | 232/1000 [00:00<00:00, 1133.72it/s]

Bootstrapping recall:  35%|███▍      | 346/1000 [00:00<00:00, 1113.67it/s]

Bootstrapping recall:  46%|████▌     | 459/1000 [00:00<00:00, 1117.33it/s]

Bootstrapping recall:  58%|█████▊    | 576/1000 [00:00<00:00, 1134.04it/s]

Bootstrapping recall:  69%|██████▉   | 691/1000 [00:00<00:00, 1137.45it/s]

Bootstrapping recall:  80%|████████  | 805/1000 [00:00<00:00, 1128.58it/s]

Bootstrapping recall:  92%|█████████▏| 920/1000 [00:00<00:00, 1134.13it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1132.09it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1149.67it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1134.16it/s]

Bootstrapping f1:  34%|███▍      | 345/1000 [00:00<00:00, 1139.01it/s]

Bootstrapping f1:  46%|████▌     | 459/1000 [00:00<00:00, 1123.23it/s]

Bootstrapping f1:  57%|█████▊    | 575/1000 [00:00<00:00, 1135.03it/s]

Bootstrapping f1:  69%|██████▉   | 694/1000 [00:00<00:00, 1151.36it/s]

Bootstrapping f1:  81%|████████  | 811/1000 [00:00<00:00, 1157.20it/s]

Bootstrapping f1:  93%|█████████▎| 930/1000 [00:00<00:00, 1164.18it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1151.51it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 347/1000 [00:00<00:00, 3469.27it/s]

Bootstrapping accuracy:  70%|██████▉   | 695/1000 [00:00<00:00, 3474.97it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3480.96it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 199/1000 [00:00<00:00, 1983.41it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 2004.09it/s]

Bootstrapping average_precision:  60%|██████    | 602/1000 [00:00<00:00, 1950.61it/s]

Bootstrapping average_precision:  80%|███████▉  | 798/1000 [00:00<00:00, 1938.76it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1964.53it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1962.25it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1225.17it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1184.10it/s]

Bootstrapping roc_auc:  37%|███▋      | 367/1000 [00:00<00:00, 1195.66it/s]

Bootstrapping roc_auc:  49%|████▉     | 492/1000 [00:00<00:00, 1214.31it/s]

Bootstrapping roc_auc:  61%|██████▏   | 614/1000 [00:00<00:00, 1213.96it/s]

Bootstrapping roc_auc:  74%|███████▎  | 736/1000 [00:00<00:00, 1197.91it/s]

Bootstrapping roc_auc:  86%|████████▌ | 856/1000 [00:00<00:00, 1185.42it/s]

Bootstrapping roc_auc:  98%|█████████▊| 977/1000 [00:00<00:00, 1191.46it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1196.36it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1409.93it/s]

Bootstrapping precision:  28%|██▊       | 282/1000 [00:00<00:00, 1386.92it/s]

Bootstrapping precision:  42%|████▏     | 423/1000 [00:00<00:00, 1396.72it/s]

Bootstrapping precision:  56%|█████▋    | 564/1000 [00:00<00:00, 1399.21it/s]

Bootstrapping precision:  70%|███████   | 704/1000 [00:00<00:00, 1376.03it/s]

Bootstrapping precision:  84%|████████▍ | 844/1000 [00:00<00:00, 1381.48it/s]

Bootstrapping precision:  98%|█████████▊| 984/1000 [00:00<00:00, 1385.02it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1385.34it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 141/1000 [00:00<00:00, 1402.34it/s]

Bootstrapping recall:  28%|██▊       | 283/1000 [00:00<00:00, 1406.94it/s]

Bootstrapping recall:  42%|████▏     | 424/1000 [00:00<00:00, 1375.41it/s]

Bootstrapping recall:  56%|█████▌    | 562/1000 [00:00<00:00, 1375.11it/s]

Bootstrapping recall:  70%|███████   | 702/1000 [00:00<00:00, 1382.56it/s]

Bootstrapping recall:  84%|████████▍ | 845/1000 [00:00<00:00, 1395.35it/s]

Bootstrapping recall:  98%|█████████▊| 985/1000 [00:00<00:00, 1393.39it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1387.91it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 141/1000 [00:00<00:00, 1404.59it/s]

Bootstrapping f1:  28%|██▊       | 283/1000 [00:00<00:00, 1408.12it/s]

Bootstrapping f1:  42%|████▏     | 424/1000 [00:00<00:00, 1397.95it/s]

Bootstrapping f1:  56%|█████▋    | 564/1000 [00:00<00:00, 1396.81it/s]

Bootstrapping f1:  70%|███████   | 704/1000 [00:00<00:00, 1395.85it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1402.12it/s]

Bootstrapping f1:  99%|█████████▊| 987/1000 [00:00<00:00, 1401.73it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1397.71it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 415/1000 [00:00<00:00, 4145.02it/s]

Bootstrapping accuracy:  83%|████████▎ | 831/1000 [00:00<00:00, 4150.05it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4125.49it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  19%|█▉        | 193/1000 [00:00<00:00, 1927.13it/s]

Bootstrapping average_precision:  39%|███▉      | 388/1000 [00:00<00:00, 1936.52it/s]

Bootstrapping average_precision:  59%|█████▊    | 586/1000 [00:00<00:00, 1953.77it/s]

Bootstrapping average_precision:  78%|███████▊  | 784/1000 [00:00<00:00, 1962.96it/s]

Bootstrapping average_precision:  98%|█████████▊| 981/1000 [00:00<00:00, 1947.31it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1944.02it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 115/1000 [00:00<00:00, 1148.92it/s]

Bootstrapping roc_auc:  23%|██▎       | 230/1000 [00:00<00:00, 1149.12it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 1163.50it/s]

Bootstrapping roc_auc:  47%|████▋     | 468/1000 [00:00<00:00, 1173.53it/s]

Bootstrapping roc_auc:  59%|█████▉    | 589/1000 [00:00<00:00, 1185.18it/s]

Bootstrapping roc_auc:  71%|███████   | 708/1000 [00:00<00:00, 1178.44it/s]

Bootstrapping roc_auc:  83%|████████▎ | 827/1000 [00:00<00:00, 1181.42it/s]

Bootstrapping roc_auc:  95%|█████████▍| 946/1000 [00:00<00:00, 1181.30it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1176.71it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 139/1000 [00:00<00:00, 1386.39it/s]

Bootstrapping precision:  28%|██▊       | 278/1000 [00:00<00:00, 1387.61it/s]

Bootstrapping precision:  42%|████▏     | 418/1000 [00:00<00:00, 1389.12it/s]

Bootstrapping precision:  56%|█████▌    | 557/1000 [00:00<00:00, 1383.30it/s]

Bootstrapping precision:  70%|██████▉   | 697/1000 [00:00<00:00, 1386.23it/s]

Bootstrapping precision:  84%|████████▎ | 837/1000 [00:00<00:00, 1388.19it/s]

Bootstrapping precision:  98%|█████████▊| 976/1000 [00:00<00:00, 1377.68it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1377.56it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▎        | 137/1000 [00:00<00:00, 1369.11it/s]

Bootstrapping recall:  27%|██▋       | 274/1000 [00:00<00:00, 1294.09it/s]

Bootstrapping recall:  40%|████      | 404/1000 [00:00<00:00, 1074.04it/s]

Bootstrapping recall:  54%|█████▎    | 537/1000 [00:00<00:00, 1160.68it/s]

Bootstrapping recall:  68%|██████▊   | 675/1000 [00:00<00:00, 1230.89it/s]

Bootstrapping recall:  81%|████████▏ | 813/1000 [00:00<00:00, 1277.65it/s]

Bootstrapping recall:  94%|█████████▍| 945/1000 [00:00<00:00, 1290.43it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1251.73it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 139/1000 [00:00<00:00, 1383.32it/s]

Bootstrapping f1:  28%|██▊       | 278/1000 [00:00<00:00, 1370.49it/s]

Bootstrapping f1:  42%|████▏     | 416/1000 [00:00<00:00, 1373.21it/s]

Bootstrapping f1:  55%|█████▌    | 554/1000 [00:00<00:00, 1368.16it/s]

Bootstrapping f1:  69%|██████▉   | 691/1000 [00:00<00:00, 1365.43it/s]

Bootstrapping f1:  83%|████████▎ | 829/1000 [00:00<00:00, 1368.42it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1366.05it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1367.61it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|███▉      | 396/1000 [00:00<00:00, 3959.92it/s]

Bootstrapping accuracy:  79%|███████▉  | 793/1000 [00:00<00:00, 3964.52it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3992.62it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 197/1000 [00:00<00:00, 1964.40it/s]

Bootstrapping average_precision:  39%|███▉      | 394/1000 [00:00<00:00, 1954.80it/s]

Bootstrapping average_precision:  59%|█████▉    | 591/1000 [00:00<00:00, 1961.11it/s]

Bootstrapping average_precision:  79%|███████▉  | 789/1000 [00:00<00:00, 1966.00it/s]

Bootstrapping average_precision:  99%|█████████▊| 986/1000 [00:00<00:00, 1966.49it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1961.18it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 116/1000 [00:00<00:00, 1157.19it/s]

Bootstrapping roc_auc:  24%|██▎       | 235/1000 [00:00<00:00, 1171.61it/s]

Bootstrapping roc_auc:  35%|███▌      | 353/1000 [00:00<00:00, 1174.55it/s]

Bootstrapping roc_auc:  47%|████▋     | 473/1000 [00:00<00:00, 1182.87it/s]

Bootstrapping roc_auc:  59%|█████▉    | 594/1000 [00:00<00:00, 1189.19it/s]

Bootstrapping roc_auc:  72%|███████▏  | 715/1000 [00:00<00:00, 1193.66it/s]

Bootstrapping roc_auc:  84%|████████▎ | 836/1000 [00:00<00:00, 1198.82it/s]

Bootstrapping roc_auc:  96%|█████████▌| 956/1000 [00:00<00:00, 1192.26it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1184.42it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 140/1000 [00:00<00:00, 1399.69it/s]

Bootstrapping precision:  28%|██▊       | 280/1000 [00:00<00:00, 1394.36it/s]

Bootstrapping precision:  42%|████▏     | 420/1000 [00:00<00:00, 1391.96it/s]

Bootstrapping precision:  56%|█████▌    | 560/1000 [00:00<00:00, 1386.13it/s]

Bootstrapping precision:  70%|██████▉   | 699/1000 [00:00<00:00, 1376.55it/s]

Bootstrapping precision:  84%|████████▍ | 838/1000 [00:00<00:00, 1380.15it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1381.04it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1382.24it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 138/1000 [00:00<00:00, 1377.84it/s]

Bootstrapping recall:  28%|██▊       | 276/1000 [00:00<00:00, 1361.95it/s]

Bootstrapping recall:  42%|████▏     | 415/1000 [00:00<00:00, 1370.40it/s]

Bootstrapping recall:  56%|█████▌    | 556/1000 [00:00<00:00, 1383.18it/s]

Bootstrapping recall:  70%|██████▉   | 696/1000 [00:00<00:00, 1386.96it/s]

Bootstrapping recall:  84%|████████▎ | 836/1000 [00:00<00:00, 1390.72it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1396.54it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1385.79it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 138/1000 [00:00<00:00, 1376.48it/s]

Bootstrapping f1:  28%|██▊       | 280/1000 [00:00<00:00, 1398.03it/s]

Bootstrapping f1:  42%|████▏     | 420/1000 [00:00<00:00, 1392.14it/s]

Bootstrapping f1:  56%|█████▌    | 561/1000 [00:00<00:00, 1399.00it/s]

Bootstrapping f1:  70%|███████   | 701/1000 [00:00<00:00, 1379.06it/s]

Bootstrapping f1:  84%|████████▍ | 842/1000 [00:00<00:00, 1386.98it/s]

Bootstrapping f1:  98%|█████████▊| 981/1000 [00:00<00:00, 1366.89it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1375.25it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  39%|███▉      | 390/1000 [00:00<00:00, 3895.20it/s]

Bootstrapping accuracy:  78%|███████▊  | 780/1000 [00:00<00:00, 3841.43it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3831.89it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem (24 nodes, 35 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1280.84it/s]

Bootstrapping average_precision:  26%|██▋       | 263/1000 [00:00<00:00, 1310.05it/s]

Bootstrapping average_precision:  40%|███▉      | 397/1000 [00:00<00:00, 1320.20it/s]

Bootstrapping average_precision:  53%|█████▎    | 531/1000 [00:00<00:00, 1323.25it/s]

Bootstrapping average_precision:  66%|██████▋   | 664/1000 [00:00<00:00, 1280.25it/s]

Bootstrapping average_precision:  79%|███████▉  | 793/1000 [00:00<00:00, 1273.32it/s]

Bootstrapping average_precision:  92%|█████████▏| 921/1000 [00:00<00:00, 1273.20it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1286.21it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 80/1000 [00:00<00:01, 799.97it/s]

Bootstrapping roc_auc:  16%|█▌        | 160/1000 [00:00<00:01, 724.01it/s]

Bootstrapping roc_auc:  24%|██▍       | 239/1000 [00:00<00:01, 752.02it/s]

Bootstrapping roc_auc:  32%|███▏      | 318/1000 [00:00<00:00, 764.51it/s]

Bootstrapping roc_auc:  40%|███▉      | 398/1000 [00:00<00:00, 776.04it/s]

Bootstrapping roc_auc:  48%|████▊     | 479/1000 [00:00<00:00, 786.69it/s]

Bootstrapping roc_auc:  56%|█████▌    | 558/1000 [00:00<00:00, 785.68it/s]

Bootstrapping roc_auc:  64%|██████▍   | 639/1000 [00:00<00:00, 792.12it/s]

Bootstrapping roc_auc:  72%|███████▏  | 722/1000 [00:00<00:00, 803.42it/s]

Bootstrapping roc_auc:  80%|████████  | 805/1000 [00:01<00:00, 809.21it/s]

Bootstrapping roc_auc:  89%|████████▊ | 886/1000 [00:01<00:00, 806.97it/s]

Bootstrapping roc_auc:  97%|█████████▋| 969/1000 [00:01<00:00, 812.54it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 792.24it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 107/1000 [00:00<00:00, 1069.58it/s]

Bootstrapping precision:  22%|██▏       | 224/1000 [00:00<00:00, 1125.11it/s]

Bootstrapping precision:  34%|███▍      | 343/1000 [00:00<00:00, 1152.03it/s]

Bootstrapping precision:  46%|████▋     | 464/1000 [00:00<00:00, 1173.83it/s]

Bootstrapping precision:  58%|█████▊    | 582/1000 [00:00<00:00, 1155.58it/s]

Bootstrapping precision:  70%|██████▉   | 699/1000 [00:00<00:00, 1158.72it/s]

Bootstrapping precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1164.94it/s]

Bootstrapping precision:  93%|█████████▎| 934/1000 [00:00<00:00, 1151.65it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1148.36it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1161.62it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1175.17it/s]

Bootstrapping recall:  36%|███▌      | 357/1000 [00:00<00:00, 1189.88it/s]

Bootstrapping recall:  48%|████▊     | 476/1000 [00:00<00:00, 1185.70it/s]

Bootstrapping recall:  60%|█████▉    | 595/1000 [00:00<00:00, 1156.97it/s]

Bootstrapping recall:  71%|███████▏  | 713/1000 [00:00<00:00, 1162.73it/s]

Bootstrapping recall:  83%|████████▎ | 830/1000 [00:00<00:00, 1152.20it/s]

Bootstrapping recall:  95%|█████████▍| 946/1000 [00:00<00:00, 1143.76it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1157.99it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1174.21it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1134.19it/s]

Bootstrapping f1:  35%|███▌      | 350/1000 [00:00<00:00, 1131.93it/s]

Bootstrapping f1:  46%|████▋     | 464/1000 [00:00<00:00, 1120.88it/s]

Bootstrapping f1:  58%|█████▊    | 578/1000 [00:00<00:00, 1127.49it/s]

Bootstrapping f1:  69%|██████▉   | 693/1000 [00:00<00:00, 1131.85it/s]

Bootstrapping f1:  81%|████████  | 807/1000 [00:00<00:00, 1130.52it/s]

Bootstrapping f1:  92%|█████████▏| 923/1000 [00:00<00:00, 1138.97it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1132.97it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 331/1000 [00:00<00:00, 3305.67it/s]

Bootstrapping accuracy:  67%|██████▋   | 671/1000 [00:00<00:00, 3355.42it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3370.91it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 199/1000 [00:00<00:00, 1980.99it/s]

Bootstrapping average_precision:  40%|███▉      | 398/1000 [00:00<00:00, 1975.22it/s]

Bootstrapping average_precision:  60%|█████▉    | 596/1000 [00:00<00:00, 1969.20it/s]

Bootstrapping average_precision:  80%|███████▉  | 795/1000 [00:00<00:00, 1977.32it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1999.48it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 122/1000 [00:00<00:00, 1215.48it/s]

Bootstrapping roc_auc:  24%|██▍       | 244/1000 [00:00<00:00, 1184.77it/s]

Bootstrapping roc_auc:  36%|███▋      | 363/1000 [00:00<00:00, 1176.50it/s]

Bootstrapping roc_auc:  48%|████▊     | 481/1000 [00:00<00:00, 1159.18it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 1154.80it/s]

Bootstrapping roc_auc:  72%|███████▏  | 715/1000 [00:00<00:00, 1160.61it/s]

Bootstrapping roc_auc:  83%|████████▎ | 834/1000 [00:00<00:00, 1167.53it/s]

Bootstrapping roc_auc:  96%|█████████▌| 958/1000 [00:00<00:00, 1189.81it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1178.06it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1409.72it/s]

Bootstrapping precision:  28%|██▊       | 282/1000 [00:00<00:00, 1365.91it/s]

Bootstrapping precision:  42%|████▏     | 419/1000 [00:00<00:00, 1363.32it/s]

Bootstrapping precision:  56%|█████▌    | 557/1000 [00:00<00:00, 1369.13it/s]

Bootstrapping precision:  70%|██████▉   | 699/1000 [00:00<00:00, 1387.11it/s]

Bootstrapping precision:  84%|████████▍ | 840/1000 [00:00<00:00, 1392.82it/s]

Bootstrapping precision:  98%|█████████▊| 981/1000 [00:00<00:00, 1397.79it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1386.39it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 141/1000 [00:00<00:00, 1402.04it/s]

Bootstrapping recall:  28%|██▊       | 283/1000 [00:00<00:00, 1412.03it/s]

Bootstrapping recall:  43%|████▎     | 426/1000 [00:00<00:00, 1418.69it/s]

Bootstrapping recall:  57%|█████▋    | 568/1000 [00:00<00:00, 1410.35it/s]

Bootstrapping recall:  71%|███████   | 711/1000 [00:00<00:00, 1413.82it/s]

Bootstrapping recall:  86%|████████▌ | 856/1000 [00:00<00:00, 1423.16it/s]

Bootstrapping recall: 100%|█████████▉| 999/1000 [00:00<00:00, 1406.50it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1409.34it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 138/1000 [00:00<00:00, 1374.68it/s]

Bootstrapping f1:  28%|██▊       | 277/1000 [00:00<00:00, 1380.07it/s]

Bootstrapping f1:  42%|████▏     | 417/1000 [00:00<00:00, 1387.86it/s]

Bootstrapping f1:  56%|█████▌    | 556/1000 [00:00<00:00, 1374.67it/s]

Bootstrapping f1:  69%|██████▉   | 694/1000 [00:00<00:00, 1372.04it/s]

Bootstrapping f1:  83%|████████▎ | 832/1000 [00:00<00:00, 1374.29it/s]

Bootstrapping f1:  97%|█████████▋| 974/1000 [00:00<00:00, 1386.27it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1380.12it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 419/1000 [00:00<00:00, 4180.38it/s]

Bootstrapping accuracy:  84%|████████▍ | 838/1000 [00:00<00:00, 4146.50it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4145.32it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 198/1000 [00:00<00:00, 1975.71it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 2004.41it/s]

Bootstrapping average_precision:  60%|██████    | 602/1000 [00:00<00:00, 2006.33it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 2002.81it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1999.19it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 120/1000 [00:00<00:00, 1195.79it/s]

Bootstrapping roc_auc:  24%|██▍       | 240/1000 [00:00<00:00, 1187.39it/s]

Bootstrapping roc_auc:  36%|███▌      | 360/1000 [00:00<00:00, 1191.12it/s]

Bootstrapping roc_auc:  48%|████▊     | 480/1000 [00:00<00:00, 1194.33it/s]

Bootstrapping roc_auc:  60%|██████    | 600/1000 [00:00<00:00, 1191.59it/s]

Bootstrapping roc_auc:  72%|███████▏  | 720/1000 [00:00<00:00, 1186.14it/s]

Bootstrapping roc_auc:  84%|████████▍ | 841/1000 [00:00<00:00, 1191.10it/s]

Bootstrapping roc_auc:  96%|█████████▌| 961/1000 [00:00<00:00, 1193.60it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1190.79it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1404.59it/s]

Bootstrapping precision:  28%|██▊       | 282/1000 [00:00<00:00, 1379.70it/s]

Bootstrapping precision:  42%|████▏     | 422/1000 [00:00<00:00, 1386.41it/s]

Bootstrapping precision:  56%|█████▌    | 562/1000 [00:00<00:00, 1390.39it/s]

Bootstrapping precision:  70%|███████   | 702/1000 [00:00<00:00, 1391.69it/s]

Bootstrapping precision:  84%|████████▍ | 843/1000 [00:00<00:00, 1394.90it/s]

Bootstrapping precision:  98%|█████████▊| 984/1000 [00:00<00:00, 1398.60it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1392.08it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 138/1000 [00:00<00:00, 1379.92it/s]

Bootstrapping recall:  28%|██▊       | 279/1000 [00:00<00:00, 1393.47it/s]

Bootstrapping recall:  42%|████▏     | 419/1000 [00:00<00:00, 1372.81it/s]

Bootstrapping recall:  56%|█████▌    | 557/1000 [00:00<00:00, 1346.07it/s]

Bootstrapping recall:  69%|██████▉   | 692/1000 [00:00<00:00, 1343.98it/s]

Bootstrapping recall:  83%|████████▎ | 827/1000 [00:00<00:00, 1341.58it/s]

Bootstrapping recall:  96%|█████████▌| 962/1000 [00:00<00:00, 1334.61it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1345.38it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 131/1000 [00:00<00:00, 1305.48it/s]

Bootstrapping f1:  26%|██▌       | 262/1000 [00:00<00:00, 1302.60it/s]

Bootstrapping f1:  40%|███▉      | 396/1000 [00:00<00:00, 1316.63it/s]

Bootstrapping f1:  53%|█████▎    | 533/1000 [00:00<00:00, 1337.37it/s]

Bootstrapping f1:  67%|██████▋   | 669/1000 [00:00<00:00, 1342.79it/s]

Bootstrapping f1:  81%|████████  | 808/1000 [00:00<00:00, 1356.61it/s]

Bootstrapping f1:  95%|█████████▍| 949/1000 [00:00<00:00, 1372.92it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1349.56it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|████      | 404/1000 [00:00<00:00, 4036.90it/s]

Bootstrapping accuracy:  81%|████████  | 809/1000 [00:00<00:00, 4041.84it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4048.85it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 200/1000 [00:00<00:00, 1997.76it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1978.98it/s]

Bootstrapping average_precision:  60%|██████    | 601/1000 [00:00<00:00, 1991.98it/s]

Bootstrapping average_precision:  80%|████████  | 801/1000 [00:00<00:00, 1983.26it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1953.86it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1966.30it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 118/1000 [00:00<00:00, 1170.93it/s]

Bootstrapping roc_auc:  24%|██▎       | 236/1000 [00:00<00:00, 1168.45it/s]

Bootstrapping roc_auc:  36%|███▌      | 355/1000 [00:00<00:00, 1174.65it/s]

Bootstrapping roc_auc:  47%|████▋     | 474/1000 [00:00<00:00, 1177.30it/s]

Bootstrapping roc_auc:  59%|█████▉    | 594/1000 [00:00<00:00, 1183.67it/s]

Bootstrapping roc_auc:  71%|███████▏  | 713/1000 [00:00<00:00, 1179.47it/s]

Bootstrapping roc_auc:  83%|████████▎ | 831/1000 [00:00<00:00, 1174.31it/s]

Bootstrapping roc_auc:  95%|█████████▍| 949/1000 [00:00<00:00, 1175.41it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1174.85it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▎        | 136/1000 [00:00<00:00, 1351.43it/s]

Bootstrapping precision:  27%|██▋       | 274/1000 [00:00<00:00, 1366.70it/s]

Bootstrapping precision:  41%|████▏     | 414/1000 [00:00<00:00, 1381.75it/s]

Bootstrapping precision:  55%|█████▌    | 553/1000 [00:00<00:00, 1380.27it/s]

Bootstrapping precision:  69%|██████▉   | 693/1000 [00:00<00:00, 1383.91it/s]

Bootstrapping precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1382.48it/s]

Bootstrapping precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1371.38it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1370.14it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 133/1000 [00:00<00:00, 1329.36it/s]

Bootstrapping recall:  27%|██▋       | 266/1000 [00:00<00:00, 1303.99it/s]

Bootstrapping recall:  40%|███▉      | 398/1000 [00:00<00:00, 1308.98it/s]

Bootstrapping recall:  53%|█████▎    | 529/1000 [00:00<00:00, 1291.24it/s]

Bootstrapping recall:  66%|██████▌   | 659/1000 [00:00<00:00, 1274.54it/s]

Bootstrapping recall:  79%|███████▉  | 791/1000 [00:00<00:00, 1287.37it/s]

Bootstrapping recall:  92%|█████████▏| 923/1000 [00:00<00:00, 1295.60it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1291.97it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 133/1000 [00:00<00:00, 1321.89it/s]

Bootstrapping f1:  27%|██▋       | 266/1000 [00:00<00:00, 1326.09it/s]

Bootstrapping f1:  40%|████      | 403/1000 [00:00<00:00, 1342.02it/s]

Bootstrapping f1:  54%|█████▍    | 541/1000 [00:00<00:00, 1355.36it/s]

Bootstrapping f1:  68%|██████▊   | 677/1000 [00:00<00:00, 1338.37it/s]

Bootstrapping f1:  81%|████████  | 811/1000 [00:00<00:00, 1321.51it/s]

Bootstrapping f1:  95%|█████████▍| 946/1000 [00:00<00:00, 1328.27it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1332.79it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|███▉      | 397/1000 [00:00<00:00, 3960.69it/s]

Bootstrapping accuracy:  80%|████████  | 804/1000 [00:00<00:00, 4021.79it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3990.90it/s]

Processing Simplified Golem $\cup$ Simplified PCMB (24 nodes, 64 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1355.47it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1352.63it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1353.38it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1326.87it/s]

Bootstrapping average_precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1316.03it/s]

Bootstrapping average_precision:  81%|████████  | 809/1000 [00:00<00:00, 1299.56it/s]

Bootstrapping average_precision:  94%|█████████▍| 940/1000 [00:00<00:00, 1298.34it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1311.24it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 82/1000 [00:00<00:01, 817.23it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:00, 840.53it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 850.91it/s]

Bootstrapping roc_auc:  34%|███▍      | 341/1000 [00:00<00:00, 851.17it/s]

Bootstrapping roc_auc:  43%|████▎     | 427/1000 [00:00<00:00, 853.58it/s]

Bootstrapping roc_auc:  51%|█████▏    | 513/1000 [00:00<00:00, 850.86it/s]

Bootstrapping roc_auc:  60%|█████▉    | 599/1000 [00:00<00:00, 851.30it/s]

Bootstrapping roc_auc:  68%|██████▊   | 685/1000 [00:00<00:00, 853.41it/s]

Bootstrapping roc_auc:  77%|███████▋  | 771/1000 [00:00<00:00, 853.31it/s]

Bootstrapping roc_auc:  86%|████████▌ | 858/1000 [00:01<00:00, 855.19it/s]

Bootstrapping roc_auc:  94%|█████████▍| 945/1000 [00:01<00:00, 857.21it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 852.59it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1216.34it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1194.96it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1196.43it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1203.85it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1204.61it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1204.55it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1207.78it/s]

Bootstrapping precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1208.10it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1204.61it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1191.33it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1204.77it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1206.11it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1209.74it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1206.49it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 1205.87it/s]

Bootstrapping recall:  85%|████████▍ | 849/1000 [00:00<00:00, 1207.54it/s]

Bootstrapping recall:  97%|█████████▋| 971/1000 [00:00<00:00, 1208.34it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1206.26it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1167.72it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1187.96it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1196.53it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1200.42it/s]

Bootstrapping f1:  60%|██████    | 601/1000 [00:00<00:00, 1201.00it/s]

Bootstrapping f1:  72%|███████▏  | 722/1000 [00:00<00:00, 1197.78it/s]

Bootstrapping f1:  84%|████████▍ | 843/1000 [00:00<00:00, 1198.36it/s]

Bootstrapping f1:  96%|█████████▋| 963/1000 [00:00<00:00, 1193.59it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1194.57it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3525.88it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3516.56it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3525.46it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 210/1000 [00:00<00:00, 2096.83it/s]

Bootstrapping average_precision:  42%|████▏     | 420/1000 [00:00<00:00, 2093.84it/s]

Bootstrapping average_precision:  63%|██████▎   | 630/1000 [00:00<00:00, 2095.72it/s]

Bootstrapping average_precision:  84%|████████▍ | 840/1000 [00:00<00:00, 2077.75it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2083.18it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 124/1000 [00:00<00:00, 1237.54it/s]

Bootstrapping roc_auc:  25%|██▍       | 248/1000 [00:00<00:00, 1234.07it/s]

Bootstrapping roc_auc:  37%|███▋      | 374/1000 [00:00<00:00, 1245.16it/s]

Bootstrapping roc_auc:  50%|█████     | 500/1000 [00:00<00:00, 1249.26it/s]

Bootstrapping roc_auc:  62%|██████▎   | 625/1000 [00:00<00:00, 1248.83it/s]

Bootstrapping roc_auc:  75%|███████▌  | 751/1000 [00:00<00:00, 1250.74it/s]

Bootstrapping roc_auc:  88%|████████▊ | 877/1000 [00:00<00:00, 1252.77it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1246.33it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 138/1000 [00:00<00:00, 1379.85it/s]

Bootstrapping precision:  28%|██▊       | 279/1000 [00:00<00:00, 1396.79it/s]

Bootstrapping precision:  42%|████▏     | 420/1000 [00:00<00:00, 1400.23it/s]

Bootstrapping precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1410.75it/s]

Bootstrapping precision:  70%|███████   | 705/1000 [00:00<00:00, 1407.47it/s]

Bootstrapping precision:  85%|████████▍ | 846/1000 [00:00<00:00, 1404.83it/s]

Bootstrapping precision:  99%|█████████▉| 989/1000 [00:00<00:00, 1409.67it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1404.21it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 141/1000 [00:00<00:00, 1404.86it/s]

Bootstrapping recall:  28%|██▊       | 282/1000 [00:00<00:00, 1403.50it/s]

Bootstrapping recall:  43%|████▎     | 426/1000 [00:00<00:00, 1418.95it/s]

Bootstrapping recall:  57%|█████▋    | 568/1000 [00:00<00:00, 1415.35it/s]

Bootstrapping recall:  71%|███████   | 710/1000 [00:00<00:00, 1412.02it/s]

Bootstrapping recall:  85%|████████▌ | 852/1000 [00:00<00:00, 1412.79it/s]

Bootstrapping recall:  99%|█████████▉| 994/1000 [00:00<00:00, 1408.50it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1408.92it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1423.98it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1412.43it/s]

Bootstrapping f1:  43%|████▎     | 429/1000 [00:00<00:00, 1418.74it/s]

Bootstrapping f1:  57%|█████▋    | 572/1000 [00:00<00:00, 1421.31it/s]

Bootstrapping f1:  72%|███████▏  | 715/1000 [00:00<00:00, 1414.80it/s]

Bootstrapping f1:  86%|████████▌ | 857/1000 [00:00<00:00, 1412.82it/s]

Bootstrapping f1: 100%|█████████▉| 999/1000 [00:00<00:00, 1401.65it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1408.61it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 406/1000 [00:00<00:00, 4058.70it/s]

Bootstrapping accuracy:  82%|████████▏ | 818/1000 [00:00<00:00, 4088.93it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4088.14it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 200/1000 [00:00<00:00, 1993.97it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 1997.86it/s]

Bootstrapping average_precision:  60%|██████    | 601/1000 [00:00<00:00, 1926.60it/s]

Bootstrapping average_precision:  79%|███████▉  | 794/1000 [00:00<00:00, 1913.43it/s]

Bootstrapping average_precision:  99%|█████████▊| 986/1000 [00:00<00:00, 1907.45it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1917.70it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  11%|█         | 111/1000 [00:00<00:00, 1100.95it/s]

Bootstrapping roc_auc:  22%|██▏       | 223/1000 [00:00<00:00, 1106.37it/s]

Bootstrapping roc_auc:  34%|███▎      | 336/1000 [00:00<00:00, 1112.21it/s]

Bootstrapping roc_auc:  45%|████▍     | 448/1000 [00:00<00:00, 1109.88it/s]

Bootstrapping roc_auc:  56%|█████▌    | 561/1000 [00:00<00:00, 1114.93it/s]

Bootstrapping roc_auc:  68%|██████▊   | 675/1000 [00:00<00:00, 1121.91it/s]

Bootstrapping roc_auc:  79%|███████▉  | 793/1000 [00:00<00:00, 1138.10it/s]

Bootstrapping roc_auc:  91%|█████████ | 909/1000 [00:00<00:00, 1144.56it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1133.22it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 139/1000 [00:00<00:00, 1387.75it/s]

Bootstrapping precision:  28%|██▊       | 278/1000 [00:00<00:00, 965.55it/s]

Bootstrapping precision:  40%|███▉      | 398/1000 [00:00<00:00, 1051.07it/s]

Bootstrapping precision:  54%|█████▎    | 535/1000 [00:00<00:00, 1160.66it/s]

Bootstrapping precision:  67%|██████▋   | 670/1000 [00:00<00:00, 1221.37it/s]

Bootstrapping precision:  80%|███████▉  | 797/1000 [00:00<00:00, 1231.61it/s]

Bootstrapping precision:  93%|█████████▎| 928/1000 [00:00<00:00, 1256.10it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1200.23it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 129/1000 [00:00<00:00, 1288.28it/s]

Bootstrapping recall:  26%|██▌       | 261/1000 [00:00<00:00, 1301.67it/s]

Bootstrapping recall:  39%|███▉      | 392/1000 [00:00<00:00, 1300.46it/s]

Bootstrapping recall:  52%|█████▎    | 525/1000 [00:00<00:00, 1308.22it/s]

Bootstrapping recall:  66%|██████▌   | 658/1000 [00:00<00:00, 1315.38it/s]

Bootstrapping recall:  79%|███████▉  | 790/1000 [00:00<00:00, 1315.92it/s]

Bootstrapping recall:  92%|█████████▏| 923/1000 [00:00<00:00, 1319.23it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1312.25it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 133/1000 [00:00<00:00, 1319.17it/s]

Bootstrapping f1:  26%|██▋       | 265/1000 [00:00<00:00, 1312.83it/s]

Bootstrapping f1:  40%|████      | 400/1000 [00:00<00:00, 1325.10it/s]

Bootstrapping f1:  54%|█████▍    | 538/1000 [00:00<00:00, 1344.98it/s]

Bootstrapping f1:  68%|██████▊   | 678/1000 [00:00<00:00, 1361.64it/s]

Bootstrapping f1:  82%|████████▏ | 818/1000 [00:00<00:00, 1373.50it/s]

Bootstrapping f1:  96%|█████████▌| 956/1000 [00:00<00:00, 1359.43it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1350.85it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 409/1000 [00:00<00:00, 4083.56it/s]

Bootstrapping accuracy:  82%|████████▎ | 825/1000 [00:00<00:00, 4120.89it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4099.47it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 195/1000 [00:00<00:00, 1945.49it/s]

Bootstrapping average_precision:  39%|███▉      | 390/1000 [00:00<00:00, 1902.83it/s]

Bootstrapping average_precision:  58%|█████▊    | 581/1000 [00:00<00:00, 1871.15it/s]

Bootstrapping average_precision:  77%|███████▋  | 769/1000 [00:00<00:00, 1848.24it/s]

Bootstrapping average_precision:  95%|█████████▌| 954/1000 [00:00<00:00, 1831.88it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1850.39it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  11%|█▏        | 114/1000 [00:00<00:00, 1134.67it/s]

Bootstrapping roc_auc:  23%|██▎       | 230/1000 [00:00<00:00, 1149.28it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 1164.94it/s]

Bootstrapping roc_auc:  47%|████▋     | 468/1000 [00:00<00:00, 1174.04it/s]

Bootstrapping roc_auc:  59%|█████▊    | 586/1000 [00:00<00:00, 1160.09it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 1139.81it/s]

Bootstrapping roc_auc:  82%|████████▏ | 818/1000 [00:00<00:00, 1134.16it/s]

Bootstrapping roc_auc:  93%|█████████▎| 932/1000 [00:00<00:00, 1133.35it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1139.84it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 139/1000 [00:00<00:00, 1388.43it/s]

Bootstrapping precision:  28%|██▊       | 278/1000 [00:00<00:00, 1368.55it/s]

Bootstrapping precision:  42%|████▏     | 416/1000 [00:00<00:00, 1369.62it/s]

Bootstrapping precision:  55%|█████▌    | 553/1000 [00:00<00:00, 1342.93it/s]

Bootstrapping precision:  69%|██████▉   | 688/1000 [00:00<00:00, 1329.43it/s]

Bootstrapping precision:  82%|████████▏ | 821/1000 [00:00<00:00, 1298.50it/s]

Bootstrapping precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1302.69it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1322.17it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 134/1000 [00:00<00:00, 1336.60it/s]

Bootstrapping recall:  27%|██▋       | 269/1000 [00:00<00:00, 1343.33it/s]

Bootstrapping recall:  41%|████      | 407/1000 [00:00<00:00, 1356.18it/s]

Bootstrapping recall:  54%|█████▍    | 544/1000 [00:00<00:00, 1360.40it/s]

Bootstrapping recall:  68%|██████▊   | 681/1000 [00:00<00:00, 1354.95it/s]

Bootstrapping recall:  82%|████████▏ | 819/1000 [00:00<00:00, 1360.72it/s]

Bootstrapping recall:  96%|█████████▌| 956/1000 [00:00<00:00, 1354.98it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1350.90it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 131/1000 [00:00<00:00, 1305.56it/s]

Bootstrapping f1:  26%|██▋       | 264/1000 [00:00<00:00, 1314.94it/s]

Bootstrapping f1:  40%|███▉      | 396/1000 [00:00<00:00, 1310.85it/s]

Bootstrapping f1:  53%|█████▎    | 528/1000 [00:00<00:00, 1298.96it/s]

Bootstrapping f1:  66%|██████▌   | 659/1000 [00:00<00:00, 1301.05it/s]

Bootstrapping f1:  79%|███████▉  | 794/1000 [00:00<00:00, 1314.47it/s]

Bootstrapping f1:  93%|█████████▎| 928/1000 [00:00<00:00, 1320.12it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1316.88it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|████      | 400/1000 [00:00<00:00, 3997.49it/s]

Bootstrapping accuracy:  80%|████████  | 804/1000 [00:00<00:00, 4017.78it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4017.00it/s]

Processing Simplified Clinician Consensus (17 nodes, 17 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1332.51it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1320.65it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 1324.76it/s]

Bootstrapping average_precision:  54%|█████▎    | 536/1000 [00:00<00:00, 1332.41it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1342.79it/s]

Bootstrapping average_precision:  81%|████████  | 808/1000 [00:00<00:00, 1344.79it/s]

Bootstrapping average_precision:  94%|█████████▍| 944/1000 [00:00<00:00, 1349.30it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1340.60it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 842.18it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 843.88it/s]

Bootstrapping roc_auc:  26%|██▌       | 257/1000 [00:00<00:00, 851.41it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 856.29it/s]

Bootstrapping roc_auc:  43%|████▎     | 430/1000 [00:00<00:00, 857.52it/s]

Bootstrapping roc_auc:  52%|█████▏    | 517/1000 [00:00<00:00, 859.26it/s]

Bootstrapping roc_auc:  60%|██████    | 603/1000 [00:00<00:00, 858.82it/s]

Bootstrapping roc_auc:  69%|██████▉   | 690/1000 [00:00<00:00, 861.40it/s]

Bootstrapping roc_auc:  78%|███████▊  | 777/1000 [00:00<00:00, 861.10it/s]

Bootstrapping roc_auc:  86%|████████▋ | 864/1000 [00:01<00:00, 854.91it/s]

Bootstrapping roc_auc:  95%|█████████▌| 950/1000 [00:01<00:00, 840.49it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 848.20it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1172.13it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1162.50it/s]

Bootstrapping precision:  35%|███▌      | 353/1000 [00:00<00:00, 1149.53it/s]

Bootstrapping precision:  47%|████▋     | 469/1000 [00:00<00:00, 1150.39it/s]

Bootstrapping precision:  58%|█████▊    | 585/1000 [00:00<00:00, 1139.75it/s]

Bootstrapping precision:  70%|██████▉   | 699/1000 [00:00<00:00, 1125.39it/s]

Bootstrapping precision:  81%|████████  | 812/1000 [00:00<00:00, 1116.40it/s]

Bootstrapping precision:  93%|█████████▎| 926/1000 [00:00<00:00, 1122.50it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1133.24it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1149.81it/s]

Bootstrapping recall:  23%|██▎       | 233/1000 [00:00<00:00, 1162.47it/s]

Bootstrapping recall:  35%|███▌      | 354/1000 [00:00<00:00, 1179.57it/s]

Bootstrapping recall:  48%|████▊     | 476/1000 [00:00<00:00, 1195.09it/s]

Bootstrapping recall:  60%|█████▉    | 596/1000 [00:00<00:00, 1172.51it/s]

Bootstrapping recall:  71%|███████▏  | 714/1000 [00:00<00:00, 1170.41it/s]

Bootstrapping recall:  83%|████████▎ | 834/1000 [00:00<00:00, 1179.11it/s]

Bootstrapping recall:  95%|█████████▌| 952/1000 [00:00<00:00, 1177.39it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1174.83it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1164.97it/s]

Bootstrapping f1:  23%|██▎       | 234/1000 [00:00<00:00, 1149.57it/s]

Bootstrapping f1:  35%|███▍      | 349/1000 [00:00<00:00, 1141.28it/s]

Bootstrapping f1:  46%|████▋     | 464/1000 [00:00<00:00, 1131.02it/s]

Bootstrapping f1:  58%|█████▊    | 578/1000 [00:00<00:00, 1134.18it/s]

Bootstrapping f1:  69%|██████▉   | 693/1000 [00:00<00:00, 1138.61it/s]

Bootstrapping f1:  81%|████████  | 807/1000 [00:00<00:00, 1128.17it/s]

Bootstrapping f1:  93%|█████████▎| 929/1000 [00:00<00:00, 1155.30it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1145.75it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 329/1000 [00:00<00:00, 3281.04it/s]

Bootstrapping accuracy:  67%|██████▋   | 667/1000 [00:00<00:00, 3331.99it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3344.69it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 198/1000 [00:00<00:00, 1974.04it/s]

Bootstrapping average_precision:  40%|███▉      | 397/1000 [00:00<00:00, 1982.65it/s]

Bootstrapping average_precision:  60%|█████▉    | 596/1000 [00:00<00:00, 1979.41it/s]

Bootstrapping average_precision:  79%|███████▉  | 794/1000 [00:00<00:00, 1957.40it/s]

Bootstrapping average_precision:  99%|█████████▉| 993/1000 [00:00<00:00, 1969.02it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1966.04it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 122/1000 [00:00<00:00, 1219.18it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1225.44it/s]

Bootstrapping roc_auc:  37%|███▋      | 369/1000 [00:00<00:00, 1209.64it/s]

Bootstrapping roc_auc:  49%|████▉     | 490/1000 [00:00<00:00, 1177.59it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 1179.79it/s]

Bootstrapping roc_auc:  73%|███████▎  | 728/1000 [00:00<00:00, 1178.27it/s]

Bootstrapping roc_auc:  85%|████████▍ | 849/1000 [00:00<00:00, 1184.54it/s]

Bootstrapping roc_auc:  97%|█████████▋| 969/1000 [00:00<00:00, 1186.61it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1188.42it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▎        | 136/1000 [00:00<00:00, 1355.26it/s]

Bootstrapping precision:  27%|██▋       | 272/1000 [00:00<00:00, 1343.62it/s]

Bootstrapping precision:  41%|████      | 407/1000 [00:00<00:00, 1331.77it/s]

Bootstrapping precision:  54%|█████▍    | 542/1000 [00:00<00:00, 1335.61it/s]

Bootstrapping precision:  68%|██████▊   | 676/1000 [00:00<00:00, 1229.60it/s]

Bootstrapping precision:  81%|████████  | 811/1000 [00:00<00:00, 1265.98it/s]

Bootstrapping precision:  94%|█████████▍| 945/1000 [00:00<00:00, 1286.25it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1293.54it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 139/1000 [00:00<00:00, 1382.52it/s]

Bootstrapping recall:  28%|██▊       | 278/1000 [00:00<00:00, 1375.93it/s]

Bootstrapping recall:  42%|████▏     | 416/1000 [00:00<00:00, 1357.53it/s]

Bootstrapping recall:  55%|█████▌    | 552/1000 [00:00<00:00, 1341.87it/s]

Bootstrapping recall:  69%|██████▉   | 689/1000 [00:00<00:00, 1349.77it/s]

Bootstrapping recall:  82%|████████▎ | 825/1000 [00:00<00:00, 1347.47it/s]

Bootstrapping recall:  96%|█████████▌| 961/1000 [00:00<00:00, 1349.69it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1351.03it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▎        | 137/1000 [00:00<00:00, 1361.35it/s]

Bootstrapping f1:  28%|██▊       | 278/1000 [00:00<00:00, 1389.84it/s]

Bootstrapping f1:  42%|████▏     | 420/1000 [00:00<00:00, 1402.83it/s]

Bootstrapping f1:  56%|█████▌    | 562/1000 [00:00<00:00, 1405.78it/s]

Bootstrapping f1:  71%|███████   | 706/1000 [00:00<00:00, 1416.98it/s]

Bootstrapping f1:  85%|████████▍ | 848/1000 [00:00<00:00, 1411.40it/s]

Bootstrapping f1:  99%|█████████▉| 990/1000 [00:00<00:00, 1391.35it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1396.75it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|███▉      | 396/1000 [00:00<00:00, 3952.52it/s]

Bootstrapping accuracy:  80%|███████▉  | 799/1000 [00:00<00:00, 3997.97it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4002.17it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  19%|█▉        | 188/1000 [00:00<00:00, 1875.26it/s]

Bootstrapping average_precision:  38%|███▊      | 379/1000 [00:00<00:00, 1894.08it/s]

Bootstrapping average_precision:  57%|█████▋    | 572/1000 [00:00<00:00, 1909.38it/s]

Bootstrapping average_precision:  76%|███████▋  | 763/1000 [00:00<00:00, 1894.41it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1908.82it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1901.48it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 115/1000 [00:00<00:00, 1146.58it/s]

Bootstrapping roc_auc:  23%|██▎       | 230/1000 [00:00<00:00, 1131.23it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 1122.65it/s]

Bootstrapping roc_auc:  46%|████▌     | 457/1000 [00:00<00:00, 1118.23it/s]

Bootstrapping roc_auc:  57%|█████▋    | 569/1000 [00:00<00:00, 1116.05it/s]

Bootstrapping roc_auc:  68%|██████▊   | 684/1000 [00:00<00:00, 1126.91it/s]

Bootstrapping roc_auc:  80%|████████  | 802/1000 [00:00<00:00, 1143.55it/s]

Bootstrapping roc_auc:  92%|█████████▏| 921/1000 [00:00<00:00, 1157.02it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1144.02it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 140/1000 [00:00<00:00, 1394.61it/s]

Bootstrapping precision:  28%|██▊       | 280/1000 [00:00<00:00, 1376.44it/s]

Bootstrapping precision:  42%|████▏     | 418/1000 [00:00<00:00, 1319.06it/s]

Bootstrapping precision:  55%|█████▌    | 551/1000 [00:00<00:00, 1322.05it/s]

Bootstrapping precision:  68%|██████▊   | 684/1000 [00:00<00:00, 1310.77it/s]

Bootstrapping precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1304.32it/s]

Bootstrapping precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1331.05it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1330.67it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 131/1000 [00:00<00:00, 1307.37it/s]

Bootstrapping recall:  26%|██▌       | 262/1000 [00:00<00:00, 1307.67it/s]

Bootstrapping recall:  39%|███▉      | 393/1000 [00:00<00:00, 1288.38it/s]

Bootstrapping recall:  53%|█████▎    | 526/1000 [00:00<00:00, 1301.38it/s]

Bootstrapping recall:  66%|██████▋   | 664/1000 [00:00<00:00, 1326.59it/s]

Bootstrapping recall:  80%|████████  | 804/1000 [00:00<00:00, 1350.48it/s]

Bootstrapping recall:  94%|█████████▍| 940/1000 [00:00<00:00, 1350.49it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1331.85it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 139/1000 [00:00<00:00, 1388.90it/s]

Bootstrapping f1:  28%|██▊       | 278/1000 [00:00<00:00, 1366.87it/s]

Bootstrapping f1:  42%|████▏     | 416/1000 [00:00<00:00, 1368.02it/s]

Bootstrapping f1:  55%|█████▌    | 554/1000 [00:00<00:00, 1371.18it/s]

Bootstrapping f1:  70%|██████▉   | 695/1000 [00:00<00:00, 1383.26it/s]

Bootstrapping f1:  83%|████████▎ | 834/1000 [00:00<00:00, 1384.43it/s]

Bootstrapping f1:  98%|█████████▊| 975/1000 [00:00<00:00, 1391.29it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1381.79it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 413/1000 [00:00<00:00, 4127.48it/s]

Bootstrapping accuracy:  83%|████████▎ | 826/1000 [00:00<00:00, 4096.22it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4096.23it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 196/1000 [00:00<00:00, 1955.09it/s]

Bootstrapping average_precision:  39%|███▉      | 392/1000 [00:00<00:00, 1955.99it/s]

Bootstrapping average_precision:  59%|█████▉    | 589/1000 [00:00<00:00, 1958.60it/s]

Bootstrapping average_precision:  78%|███████▊  | 785/1000 [00:00<00:00, 1958.06it/s]

Bootstrapping average_precision:  98%|█████████▊| 982/1000 [00:00<00:00, 1961.98it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1957.10it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 118/1000 [00:00<00:00, 1170.44it/s]

Bootstrapping roc_auc:  24%|██▎       | 236/1000 [00:00<00:00, 1161.69it/s]

Bootstrapping roc_auc:  35%|███▌      | 353/1000 [00:00<00:00, 1145.82it/s]

Bootstrapping roc_auc:  47%|████▋     | 473/1000 [00:00<00:00, 1164.84it/s]

Bootstrapping roc_auc:  59%|█████▉    | 590/1000 [00:00<00:00, 1162.39it/s]

Bootstrapping roc_auc:  71%|███████   | 707/1000 [00:00<00:00, 1149.84it/s]

Bootstrapping roc_auc:  82%|████████▏ | 823/1000 [00:00<00:00, 1140.30it/s]

Bootstrapping roc_auc:  94%|█████████▍| 938/1000 [00:00<00:00, 1140.36it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1148.43it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  13%|█▎        | 133/1000 [00:00<00:00, 1328.83it/s]

Bootstrapping precision:  27%|██▋       | 266/1000 [00:00<00:00, 1326.40it/s]

Bootstrapping precision:  40%|████      | 401/1000 [00:00<00:00, 1333.46it/s]

Bootstrapping precision:  54%|█████▎    | 536/1000 [00:00<00:00, 1338.90it/s]

Bootstrapping precision:  67%|██████▋   | 672/1000 [00:00<00:00, 1346.16it/s]

Bootstrapping precision:  81%|████████  | 809/1000 [00:00<00:00, 1351.41it/s]

Bootstrapping precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1363.31it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1351.77it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 140/1000 [00:00<00:00, 1394.83it/s]

Bootstrapping recall:  28%|██▊       | 280/1000 [00:00<00:00, 1397.09it/s]

Bootstrapping recall:  42%|████▏     | 420/1000 [00:00<00:00, 1395.89it/s]

Bootstrapping recall:  56%|█████▌    | 560/1000 [00:00<00:00, 1383.55it/s]

Bootstrapping recall:  70%|███████   | 702/1000 [00:00<00:00, 1393.31it/s]

Bootstrapping recall:  84%|████████▍ | 842/1000 [00:00<00:00, 1381.86it/s]

Bootstrapping recall:  98%|█████████▊| 981/1000 [00:00<00:00, 1382.57it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1385.45it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 138/1000 [00:00<00:00, 1373.89it/s]

Bootstrapping f1:  28%|██▊       | 276/1000 [00:00<00:00, 1335.15it/s]

Bootstrapping f1:  41%|████      | 410/1000 [00:00<00:00, 1334.26it/s]

Bootstrapping f1:  54%|█████▍    | 544/1000 [00:00<00:00, 1327.93it/s]

Bootstrapping f1:  68%|██████▊   | 677/1000 [00:00<00:00, 1317.49it/s]

Bootstrapping f1:  81%|████████  | 810/1000 [00:00<00:00, 1319.73it/s]

Bootstrapping f1:  94%|█████████▍| 942/1000 [00:00<00:00, 1315.72it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1324.18it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  39%|███▉      | 392/1000 [00:00<00:00, 3915.23it/s]

Bootstrapping accuracy:  78%|███████▊  | 784/1000 [00:00<00:00, 3915.09it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3907.56it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB (15 nodes, 14 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1354.96it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1356.05it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1346.27it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1335.99it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1344.27it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1351.23it/s]

Bootstrapping average_precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1355.24it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1348.48it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 854.13it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 853.96it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 856.86it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 860.12it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 859.42it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 862.84it/s]

Bootstrapping roc_auc:  61%|██████    | 608/1000 [00:00<00:00, 862.91it/s]

Bootstrapping roc_auc:  70%|██████▉   | 695/1000 [00:00<00:00, 863.06it/s]

Bootstrapping roc_auc:  78%|███████▊  | 782/1000 [00:00<00:00, 860.87it/s]

Bootstrapping roc_auc:  87%|████████▋ | 869/1000 [00:01<00:00, 859.96it/s]

Bootstrapping roc_auc:  96%|█████████▌| 955/1000 [00:01<00:00, 859.52it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 859.66it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1203.18it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1207.38it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1206.90it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1193.29it/s]

Bootstrapping precision:  60%|██████    | 605/1000 [00:00<00:00, 1187.53it/s]

Bootstrapping precision:  73%|███████▎  | 726/1000 [00:00<00:00, 1192.56it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1200.79it/s]

Bootstrapping precision:  97%|█████████▋| 970/1000 [00:00<00:00, 1182.92it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1188.82it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1164.13it/s]

Bootstrapping recall:  23%|██▎       | 234/1000 [00:00<00:00, 1132.44it/s]

Bootstrapping recall:  35%|███▍      | 348/1000 [00:00<00:00, 1119.65it/s]

Bootstrapping recall:  46%|████▌     | 461/1000 [00:00<00:00, 1121.77it/s]

Bootstrapping recall:  58%|█████▊    | 576/1000 [00:00<00:00, 1129.75it/s]

Bootstrapping recall:  69%|██████▉   | 692/1000 [00:00<00:00, 1138.29it/s]

Bootstrapping recall:  81%|████████  | 812/1000 [00:00<00:00, 1155.97it/s]

Bootstrapping recall:  93%|█████████▎| 933/1000 [00:00<00:00, 1172.83it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1151.35it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1179.00it/s]

Bootstrapping f1:  24%|██▎       | 237/1000 [00:00<00:00, 1180.81it/s]

Bootstrapping f1:  36%|███▌      | 358/1000 [00:00<00:00, 1191.46it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1200.29it/s]

Bootstrapping f1:  60%|██████    | 601/1000 [00:00<00:00, 1200.16it/s]

Bootstrapping f1:  72%|███████▏  | 722/1000 [00:00<00:00, 1201.04it/s]

Bootstrapping f1:  84%|████████▍ | 844/1000 [00:00<00:00, 1205.17it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1208.77it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1200.74it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3548.75it/s]

Bootstrapping accuracy:  71%|███████   | 711/1000 [00:00<00:00, 3554.32it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3556.91it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 209/1000 [00:00<00:00, 2088.73it/s]

Bootstrapping average_precision:  42%|████▏     | 419/1000 [00:00<00:00, 2093.41it/s]

Bootstrapping average_precision:  63%|██████▎   | 629/1000 [00:00<00:00, 2095.37it/s]

Bootstrapping average_precision:  84%|████████▍ | 839/1000 [00:00<00:00, 2097.07it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2080.88it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 119/1000 [00:00<00:00, 1188.97it/s]

Bootstrapping roc_auc:  24%|██▍       | 238/1000 [00:00<00:00, 1167.00it/s]

Bootstrapping roc_auc:  36%|███▌      | 356/1000 [00:00<00:00, 1170.63it/s]

Bootstrapping roc_auc:  47%|████▋     | 474/1000 [00:00<00:00, 1150.97it/s]

Bootstrapping roc_auc:  59%|█████▉    | 590/1000 [00:00<00:00, 1131.29it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 1131.90it/s]

Bootstrapping roc_auc:  82%|████████▏ | 820/1000 [00:00<00:00, 1138.28it/s]

Bootstrapping roc_auc:  94%|█████████▎| 935/1000 [00:00<00:00, 1140.53it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1143.92it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  13%|█▎        | 129/1000 [00:00<00:00, 1277.52it/s]

Bootstrapping precision:  26%|██▌       | 259/1000 [00:00<00:00, 1289.13it/s]

Bootstrapping precision:  39%|███▉      | 390/1000 [00:00<00:00, 1298.05it/s]

Bootstrapping precision:  52%|█████▏    | 523/1000 [00:00<00:00, 1306.73it/s]

Bootstrapping precision:  66%|██████▌   | 655/1000 [00:00<00:00, 1309.90it/s]

Bootstrapping precision:  79%|███████▉  | 791/1000 [00:00<00:00, 1324.58it/s]

Bootstrapping precision:  93%|█████████▎| 930/1000 [00:00<00:00, 1343.94it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1323.95it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▎        | 137/1000 [00:00<00:00, 1368.03it/s]

Bootstrapping recall:  27%|██▋       | 274/1000 [00:00<00:00, 1226.08it/s]

Bootstrapping recall:  42%|████▏     | 415/1000 [00:00<00:00, 1303.50it/s]

Bootstrapping recall:  55%|█████▌    | 553/1000 [00:00<00:00, 1332.21it/s]

Bootstrapping recall:  70%|██████▉   | 695/1000 [00:00<00:00, 1361.33it/s]

Bootstrapping recall:  84%|████████▍ | 838/1000 [00:00<00:00, 1383.76it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1383.98it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1354.33it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 140/1000 [00:00<00:00, 1391.79it/s]

Bootstrapping f1:  28%|██▊       | 281/1000 [00:00<00:00, 1400.48it/s]

Bootstrapping f1:  42%|████▏     | 423/1000 [00:00<00:00, 1407.57it/s]

Bootstrapping f1:  57%|█████▋    | 566/1000 [00:00<00:00, 1415.53it/s]

Bootstrapping f1:  71%|███████   | 708/1000 [00:00<00:00, 1414.76it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1402.12it/s]

Bootstrapping f1:  99%|█████████▉| 991/1000 [00:00<00:00, 1403.63it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1403.48it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 415/1000 [00:00<00:00, 4145.85it/s]

Bootstrapping accuracy:  84%|████████▎ | 836/1000 [00:00<00:00, 4179.84it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4160.17it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 202/1000 [00:00<00:00, 2010.23it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 1957.52it/s]

Bootstrapping average_precision:  60%|██████    | 605/1000 [00:00<00:00, 1978.55it/s]

Bootstrapping average_precision:  81%|████████  | 807/1000 [00:00<00:00, 1993.65it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1992.34it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 119/1000 [00:00<00:00, 1181.73it/s]

Bootstrapping roc_auc:  24%|██▍       | 238/1000 [00:00<00:00, 1179.74it/s]

Bootstrapping roc_auc:  36%|███▌      | 357/1000 [00:00<00:00, 1182.02it/s]

Bootstrapping roc_auc:  48%|████▊     | 477/1000 [00:00<00:00, 1188.49it/s]

Bootstrapping roc_auc:  60%|█████▉    | 598/1000 [00:00<00:00, 1193.80it/s]

Bootstrapping roc_auc:  72%|███████▏  | 719/1000 [00:00<00:00, 1196.22it/s]

Bootstrapping roc_auc:  84%|████████▍ | 839/1000 [00:00<00:00, 1187.85it/s]

Bootstrapping roc_auc:  96%|█████████▌| 959/1000 [00:00<00:00, 1190.04it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1188.18it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 140/1000 [00:00<00:00, 1399.49it/s]

Bootstrapping precision:  28%|██▊       | 281/1000 [00:00<00:00, 1400.77it/s]

Bootstrapping precision:  42%|████▏     | 422/1000 [00:00<00:00, 1391.72it/s]

Bootstrapping precision:  56%|█████▌    | 562/1000 [00:00<00:00, 1388.38it/s]

Bootstrapping precision:  70%|███████   | 701/1000 [00:00<00:00, 1386.80it/s]

Bootstrapping precision:  84%|████████▍ | 843/1000 [00:00<00:00, 1394.91it/s]

Bootstrapping precision:  98%|█████████▊| 983/1000 [00:00<00:00, 1384.77it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1387.66it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 139/1000 [00:00<00:00, 1382.81it/s]

Bootstrapping recall:  28%|██▊       | 278/1000 [00:00<00:00, 1375.44it/s]

Bootstrapping recall:  42%|████▏     | 416/1000 [00:00<00:00, 1370.71it/s]

Bootstrapping recall:  55%|█████▌    | 554/1000 [00:00<00:00, 1366.70it/s]

Bootstrapping recall:  69%|██████▉   | 693/1000 [00:00<00:00, 1371.11it/s]

Bootstrapping recall:  83%|████████▎ | 831/1000 [00:00<00:00, 1371.97it/s]

Bootstrapping recall:  97%|█████████▋| 969/1000 [00:00<00:00, 1366.72it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1361.30it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 130/1000 [00:00<00:00, 1293.45it/s]

Bootstrapping f1:  26%|██▋       | 263/1000 [00:00<00:00, 1313.29it/s]

Bootstrapping f1:  40%|███▉      | 398/1000 [00:00<00:00, 1328.42it/s]

Bootstrapping f1:  54%|█████▎    | 536/1000 [00:00<00:00, 1345.84it/s]

Bootstrapping f1:  67%|██████▋   | 672/1000 [00:00<00:00, 1350.11it/s]

Bootstrapping f1:  81%|████████  | 808/1000 [00:00<00:00, 1343.29it/s]

Bootstrapping f1:  95%|█████████▍| 946/1000 [00:00<00:00, 1353.83it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1344.90it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 409/1000 [00:00<00:00, 4086.49it/s]

Bootstrapping accuracy:  82%|████████▏ | 818/1000 [00:00<00:00, 4002.83it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3973.27it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 198/1000 [00:00<00:00, 1972.06it/s]

Bootstrapping average_precision:  40%|███▉      | 396/1000 [00:00<00:00, 1932.07it/s]

Bootstrapping average_precision:  59%|█████▉    | 590/1000 [00:00<00:00, 1920.72it/s]

Bootstrapping average_precision:  79%|███████▊  | 787/1000 [00:00<00:00, 1938.83it/s]

Bootstrapping average_precision:  98%|█████████▊| 983/1000 [00:00<00:00, 1944.07it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1938.48it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 115/1000 [00:00<00:00, 1149.27it/s]

Bootstrapping roc_auc:  23%|██▎       | 231/1000 [00:00<00:00, 1148.34it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 1134.62it/s]

Bootstrapping roc_auc:  46%|████▌     | 460/1000 [00:00<00:00, 1134.69it/s]

Bootstrapping roc_auc:  58%|█████▊    | 581/1000 [00:00<00:00, 1159.09it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 1152.60it/s]

Bootstrapping roc_auc:  81%|████████▏ | 813/1000 [00:00<00:00, 1150.75it/s]

Bootstrapping roc_auc:  93%|█████████▎| 932/1000 [00:00<00:00, 1162.44it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1156.05it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 138/1000 [00:00<00:00, 1378.31it/s]

Bootstrapping precision:  28%|██▊       | 279/1000 [00:00<00:00, 1392.49it/s]

Bootstrapping precision:  42%|████▏     | 422/1000 [00:00<00:00, 1407.64it/s]

Bootstrapping precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1401.48it/s]

Bootstrapping precision:  70%|███████   | 705/1000 [00:00<00:00, 1405.83it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1412.75it/s]

Bootstrapping precision:  99%|█████████▉| 990/1000 [00:00<00:00, 1391.70it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1394.98it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 131/1000 [00:00<00:00, 1305.65it/s]

Bootstrapping recall:  26%|██▋       | 264/1000 [00:00<00:00, 1319.91it/s]

Bootstrapping recall:  40%|████      | 400/1000 [00:00<00:00, 1335.84it/s]

Bootstrapping recall:  54%|█████▎    | 536/1000 [00:00<00:00, 1344.77it/s]

Bootstrapping recall:  67%|██████▋   | 671/1000 [00:00<00:00, 1344.81it/s]

Bootstrapping recall:  81%|████████  | 807/1000 [00:00<00:00, 1348.74it/s]

Bootstrapping recall:  94%|█████████▍| 942/1000 [00:00<00:00, 1347.11it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1342.17it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 129/1000 [00:00<00:00, 1286.92it/s]

Bootstrapping f1:  26%|██▌       | 262/1000 [00:00<00:00, 1311.55it/s]

Bootstrapping f1:  40%|████      | 402/1000 [00:00<00:00, 1351.34it/s]

Bootstrapping f1:  54%|█████▍    | 542/1000 [00:00<00:00, 1367.35it/s]

Bootstrapping f1:  68%|██████▊   | 679/1000 [00:00<00:00, 1355.83it/s]

Bootstrapping f1:  82%|████████▏ | 815/1000 [00:00<00:00, 1349.48it/s]

Bootstrapping f1:  95%|█████████▌| 951/1000 [00:00<00:00, 1351.69it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1347.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 413/1000 [00:00<00:00, 4126.62it/s]

Bootstrapping accuracy:  83%|████████▎ | 826/1000 [00:00<00:00, 4111.29it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4080.95it/s]

Processing Simplified PCMB (18 nodes, 50 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1323.90it/s]

Bootstrapping average_precision:  27%|██▋       | 267/1000 [00:00<00:00, 1327.97it/s]

Bootstrapping average_precision:  40%|████      | 403/1000 [00:00<00:00, 1340.60it/s]

Bootstrapping average_precision:  54%|█████▍    | 539/1000 [00:00<00:00, 1347.04it/s]

Bootstrapping average_precision:  68%|██████▊   | 676/1000 [00:00<00:00, 1352.99it/s]

Bootstrapping average_precision:  81%|████████▏ | 813/1000 [00:00<00:00, 1357.00it/s]

Bootstrapping average_precision:  95%|█████████▍| 949/1000 [00:00<00:00, 1352.75it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1347.60it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 860.23it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 861.79it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 863.45it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 859.52it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 860.76it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 861.31it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 861.70it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 861.72it/s]

Bootstrapping roc_auc:  78%|███████▊  | 783/1000 [00:00<00:00, 856.68it/s]

Bootstrapping roc_auc:  87%|████████▋ | 869/1000 [00:01<00:00, 857.43it/s]

Bootstrapping roc_auc:  96%|█████████▌| 956/1000 [00:01<00:00, 859.20it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 859.80it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 117/1000 [00:00<00:00, 1165.79it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1188.29it/s]

Bootstrapping precision:  36%|███▌      | 358/1000 [00:00<00:00, 1192.43it/s]

Bootstrapping precision:  48%|████▊     | 479/1000 [00:00<00:00, 1199.22it/s]

Bootstrapping precision:  60%|██████    | 601/1000 [00:00<00:00, 1205.25it/s]

Bootstrapping precision:  72%|███████▏  | 722/1000 [00:00<00:00, 1204.80it/s]

Bootstrapping precision:  84%|████████▍ | 843/1000 [00:00<00:00, 1203.33it/s]

Bootstrapping precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1199.24it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.35it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1209.80it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1216.10it/s]

Bootstrapping recall:  37%|███▋      | 367/1000 [00:00<00:00, 1218.05it/s]

Bootstrapping recall:  49%|████▉     | 489/1000 [00:00<00:00, 1213.91it/s]

Bootstrapping recall:  61%|██████    | 611/1000 [00:00<00:00, 1214.33it/s]

Bootstrapping recall:  73%|███████▎  | 733/1000 [00:00<00:00, 1215.04it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1216.62it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1216.19it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1214.71it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1190.38it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1196.38it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1202.20it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1203.98it/s]

Bootstrapping f1:  61%|██████    | 606/1000 [00:00<00:00, 1207.57it/s]

Bootstrapping f1:  73%|███████▎  | 727/1000 [00:00<00:00, 1200.83it/s]

Bootstrapping f1:  85%|████████▍ | 848/1000 [00:00<00:00, 1201.35it/s]

Bootstrapping f1:  97%|█████████▋| 971/1000 [00:00<00:00, 1207.35it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1203.43it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3554.67it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3538.50it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3535.48it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 212/1000 [00:00<00:00, 2119.39it/s]

Bootstrapping average_precision:  42%|████▏     | 424/1000 [00:00<00:00, 2109.86it/s]

Bootstrapping average_precision:  64%|██████▎   | 636/1000 [00:00<00:00, 2114.28it/s]

Bootstrapping average_precision:  85%|████████▍ | 848/1000 [00:00<00:00, 2099.28it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2102.78it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▎        | 125/1000 [00:00<00:00, 1243.01it/s]

Bootstrapping roc_auc:  25%|██▌       | 253/1000 [00:00<00:00, 1259.12it/s]

Bootstrapping roc_auc:  38%|███▊      | 381/1000 [00:00<00:00, 1265.04it/s]

Bootstrapping roc_auc:  51%|█████     | 508/1000 [00:00<00:00, 1260.52it/s]

Bootstrapping roc_auc:  64%|██████▎   | 635/1000 [00:00<00:00, 1260.18it/s]

Bootstrapping roc_auc:  76%|███████▌  | 762/1000 [00:00<00:00, 1262.11it/s]

Bootstrapping roc_auc:  89%|████████▉ | 890/1000 [00:00<00:00, 1265.10it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1263.20it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 142/1000 [00:00<00:00, 1417.10it/s]

Bootstrapping precision:  28%|██▊       | 284/1000 [00:00<00:00, 1414.32it/s]

Bootstrapping precision:  43%|████▎     | 428/1000 [00:00<00:00, 1422.73it/s]

Bootstrapping precision:  57%|█████▋    | 573/1000 [00:00<00:00, 1430.46it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1432.08it/s]

Bootstrapping precision:  86%|████████▌ | 861/1000 [00:00<00:00, 1432.03it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1423.83it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 139/1000 [00:00<00:00, 1386.86it/s]

Bootstrapping recall:  28%|██▊       | 279/1000 [00:00<00:00, 1392.03it/s]

Bootstrapping recall:  42%|████▏     | 421/1000 [00:00<00:00, 1402.21it/s]

Bootstrapping recall:  56%|█████▌    | 562/1000 [00:00<00:00, 1403.96it/s]

Bootstrapping recall:  70%|███████   | 705/1000 [00:00<00:00, 1410.84it/s]

Bootstrapping recall:  85%|████████▍ | 848/1000 [00:00<00:00, 1414.84it/s]

Bootstrapping recall:  99%|█████████▉| 992/1000 [00:00<00:00, 1422.54it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1411.37it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1424.61it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1415.49it/s]

Bootstrapping f1:  43%|████▎     | 429/1000 [00:00<00:00, 1421.14it/s]

Bootstrapping f1:  57%|█████▋    | 572/1000 [00:00<00:00, 1410.10it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1417.76it/s]

Bootstrapping f1:  86%|████████▌ | 860/1000 [00:00<00:00, 1423.46it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1418.50it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 411/1000 [00:00<00:00, 4109.01it/s]

Bootstrapping accuracy:  83%|████████▎ | 830/1000 [00:00<00:00, 4154.98it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4151.81it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 200/1000 [00:00<00:00, 1994.16it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1993.28it/s]

Bootstrapping average_precision:  60%|██████    | 601/1000 [00:00<00:00, 2000.08it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 2006.55it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2009.90it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1204.52it/s]

Bootstrapping roc_auc:  24%|██▍       | 242/1000 [00:00<00:00, 1186.43it/s]

Bootstrapping roc_auc:  36%|███▌      | 362/1000 [00:00<00:00, 1188.22it/s]

Bootstrapping roc_auc:  48%|████▊     | 483/1000 [00:00<00:00, 1196.55it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 1203.75it/s]

Bootstrapping roc_auc:  73%|███████▎  | 727/1000 [00:00<00:00, 1207.65it/s]

Bootstrapping roc_auc:  85%|████████▍ | 848/1000 [00:00<00:00, 1206.83it/s]

Bootstrapping roc_auc:  97%|█████████▋| 969/1000 [00:00<00:00, 1205.27it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1201.28it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 142/1000 [00:00<00:00, 1412.81it/s]

Bootstrapping precision:  28%|██▊       | 284/1000 [00:00<00:00, 1391.80it/s]

Bootstrapping precision:  42%|████▏     | 424/1000 [00:00<00:00, 1384.05it/s]

Bootstrapping precision:  56%|█████▋    | 564/1000 [00:00<00:00, 1387.65it/s]

Bootstrapping precision:  70%|███████   | 704/1000 [00:00<00:00, 1389.99it/s]

Bootstrapping precision:  84%|████████▍ | 844/1000 [00:00<00:00, 1389.65it/s]

Bootstrapping precision:  98%|█████████▊| 983/1000 [00:00<00:00, 1379.03it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1383.14it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▎        | 136/1000 [00:00<00:00, 1355.80it/s]

Bootstrapping recall:  27%|██▋       | 272/1000 [00:00<00:00, 1352.02it/s]

Bootstrapping recall:  41%|████      | 408/1000 [00:00<00:00, 1353.51it/s]

Bootstrapping recall:  54%|█████▍    | 544/1000 [00:00<00:00, 1354.92it/s]

Bootstrapping recall:  68%|██████▊   | 680/1000 [00:00<00:00, 1355.47it/s]

Bootstrapping recall:  82%|████████▏ | 820/1000 [00:00<00:00, 1368.95it/s]

Bootstrapping recall:  96%|█████████▌| 958/1000 [00:00<00:00, 1372.47it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1365.03it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 141/1000 [00:00<00:00, 1400.95it/s]

Bootstrapping f1:  28%|██▊       | 282/1000 [00:00<00:00, 1404.55it/s]

Bootstrapping f1:  42%|████▏     | 424/1000 [00:00<00:00, 1408.65it/s]

Bootstrapping f1:  56%|█████▋    | 565/1000 [00:00<00:00, 1391.57it/s]

Bootstrapping f1:  70%|███████   | 705/1000 [00:00<00:00, 1389.61it/s]

Bootstrapping f1:  84%|████████▍ | 844/1000 [00:00<00:00, 1377.90it/s]

Bootstrapping f1:  98%|█████████▊| 982/1000 [00:00<00:00, 1363.28it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1377.97it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|███▉      | 395/1000 [00:00<00:00, 3947.36it/s]

Bootstrapping accuracy:  80%|███████▉  | 799/1000 [00:00<00:00, 3996.18it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3971.75it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  19%|█▉        | 189/1000 [00:00<00:00, 1887.34it/s]

Bootstrapping average_precision:  38%|███▊      | 378/1000 [00:00<00:00, 1873.82it/s]

Bootstrapping average_precision:  57%|█████▋    | 566/1000 [00:00<00:00, 1864.93it/s]

Bootstrapping average_precision:  75%|███████▌  | 754/1000 [00:00<00:00, 1867.62it/s]

Bootstrapping average_precision:  94%|█████████▍| 941/1000 [00:00<00:00, 1848.11it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1849.70it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  11%|█         | 111/1000 [00:00<00:00, 1101.77it/s]

Bootstrapping roc_auc:  22%|██▏       | 223/1000 [00:00<00:00, 1112.12it/s]

Bootstrapping roc_auc:  34%|███▎      | 335/1000 [00:00<00:00, 1107.93it/s]

Bootstrapping roc_auc:  45%|████▍     | 447/1000 [00:00<00:00, 1110.87it/s]

Bootstrapping roc_auc:  56%|█████▌    | 560/1000 [00:00<00:00, 1117.53it/s]

Bootstrapping roc_auc:  67%|██████▋   | 673/1000 [00:00<00:00, 1119.89it/s]

Bootstrapping roc_auc:  79%|███████▊  | 786/1000 [00:00<00:00, 1120.90it/s]

Bootstrapping roc_auc:  90%|████████▉ | 899/1000 [00:00<00:00, 1117.19it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1116.26it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  13%|█▎        | 132/1000 [00:00<00:00, 1313.45it/s]

Bootstrapping precision:  27%|██▋       | 270/1000 [00:00<00:00, 1347.25it/s]

Bootstrapping precision:  40%|████      | 405/1000 [00:00<00:00, 1269.52it/s]

Bootstrapping precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1324.46it/s]

Bootstrapping precision:  69%|██████▉   | 689/1000 [00:00<00:00, 1357.63it/s]

Bootstrapping precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1368.83it/s]

Bootstrapping precision:  97%|█████████▋| 968/1000 [00:00<00:00, 1375.23it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1351.48it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 140/1000 [00:00<00:00, 1392.53it/s]

Bootstrapping recall:  28%|██▊       | 280/1000 [00:00<00:00, 1384.31it/s]

Bootstrapping recall:  42%|████▏     | 421/1000 [00:00<00:00, 1395.06it/s]

Bootstrapping recall:  56%|█████▌    | 561/1000 [00:00<00:00, 1391.68it/s]

Bootstrapping recall:  70%|███████   | 702/1000 [00:00<00:00, 1396.38it/s]

Bootstrapping recall:  84%|████████▍ | 845/1000 [00:00<00:00, 1407.18it/s]

Bootstrapping recall:  99%|█████████▊| 987/1000 [00:00<00:00, 1411.17it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1401.40it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 139/1000 [00:00<00:00, 1385.43it/s]

Bootstrapping f1:  28%|██▊       | 279/1000 [00:00<00:00, 1392.86it/s]

Bootstrapping f1:  42%|████▏     | 421/1000 [00:00<00:00, 1404.80it/s]

Bootstrapping f1:  56%|█████▌    | 562/1000 [00:00<00:00, 1396.50it/s]

Bootstrapping f1:  70%|███████   | 702/1000 [00:00<00:00, 1390.75it/s]

Bootstrapping f1:  84%|████████▍ | 842/1000 [00:00<00:00, 1370.33it/s]

Bootstrapping f1:  98%|█████████▊| 980/1000 [00:00<00:00, 1359.01it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1371.32it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|███▉      | 396/1000 [00:00<00:00, 3955.92it/s]

Bootstrapping accuracy:  79%|███████▉  | 792/1000 [00:00<00:00, 3936.13it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3936.90it/s]

Processing Simplified Golem (12 nodes, 22 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 131/1000 [00:00<00:00, 1304.63it/s]

Bootstrapping average_precision:  26%|██▌       | 262/1000 [00:00<00:00, 1301.01it/s]

Bootstrapping average_precision:  40%|███▉      | 395/1000 [00:00<00:00, 1314.00it/s]

Bootstrapping average_precision:  53%|█████▎    | 531/1000 [00:00<00:00, 1330.81it/s]

Bootstrapping average_precision:  67%|██████▋   | 666/1000 [00:00<00:00, 1335.57it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1341.07it/s]

Bootstrapping average_precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1347.16it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1335.04it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 80/1000 [00:00<00:01, 799.91it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 809.38it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 805.47it/s]

Bootstrapping roc_auc:  32%|███▎      | 325/1000 [00:00<00:00, 807.91it/s]

Bootstrapping roc_auc:  41%|████      | 408/1000 [00:00<00:00, 814.35it/s]

Bootstrapping roc_auc:  49%|████▉     | 491/1000 [00:00<00:00, 817.78it/s]

Bootstrapping roc_auc:  57%|█████▋    | 573/1000 [00:00<00:00, 813.92it/s]

Bootstrapping roc_auc:  66%|██████▌   | 656/1000 [00:00<00:00, 816.13it/s]

Bootstrapping roc_auc:  74%|███████▍  | 738/1000 [00:00<00:00, 812.81it/s]

Bootstrapping roc_auc:  82%|████████▏ | 820/1000 [00:01<00:00, 811.44it/s]

Bootstrapping roc_auc:  90%|█████████ | 902/1000 [00:01<00:00, 808.59it/s]

Bootstrapping roc_auc:  98%|█████████▊| 985/1000 [00:01<00:00, 812.59it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 811.50it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1171.11it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1175.45it/s]

Bootstrapping precision:  35%|███▌      | 354/1000 [00:00<00:00, 1171.14it/s]

Bootstrapping precision:  48%|████▊     | 476/1000 [00:00<00:00, 1188.24it/s]

Bootstrapping precision:  60%|█████▉    | 595/1000 [00:00<00:00, 1185.23it/s]

Bootstrapping precision:  71%|███████▏  | 714/1000 [00:00<00:00, 1183.37it/s]

Bootstrapping precision:  83%|████████▎ | 833/1000 [00:00<00:00, 1171.76it/s]

Bootstrapping precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1167.10it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1174.81it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1159.97it/s]

Bootstrapping recall:  23%|██▎       | 232/1000 [00:00<00:00, 1145.75it/s]

Bootstrapping recall:  35%|███▍      | 349/1000 [00:00<00:00, 1156.23it/s]

Bootstrapping recall:  47%|████▋     | 469/1000 [00:00<00:00, 1173.09it/s]

Bootstrapping recall:  59%|█████▉    | 591/1000 [00:00<00:00, 1189.48it/s]

Bootstrapping recall:  71%|███████   | 711/1000 [00:00<00:00, 1191.74it/s]

Bootstrapping recall:  83%|████████▎ | 832/1000 [00:00<00:00, 1194.16it/s]

Bootstrapping recall:  95%|█████████▌| 953/1000 [00:00<00:00, 1198.30it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1186.25it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1207.18it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1213.13it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1205.98it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1207.38it/s]

Bootstrapping f1:  61%|██████    | 608/1000 [00:00<00:00, 1209.68it/s]

Bootstrapping f1:  73%|███████▎  | 729/1000 [00:00<00:00, 1194.52it/s]

Bootstrapping f1:  85%|████████▍ | 849/1000 [00:00<00:00, 1190.85it/s]

Bootstrapping f1:  97%|█████████▋| 969/1000 [00:00<00:00, 1183.61it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1190.89it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  32%|███▎      | 325/1000 [00:00<00:00, 3249.86it/s]

Bootstrapping accuracy:  66%|██████▌   | 662/1000 [00:00<00:00, 3317.82it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3363.42it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 195/1000 [00:00<00:00, 1941.98it/s]

Bootstrapping average_precision:  39%|███▉      | 390/1000 [00:00<00:00, 1946.06it/s]

Bootstrapping average_precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1999.92it/s]

Bootstrapping average_precision:  80%|███████▉  | 799/1000 [00:00<00:00, 2007.73it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1990.41it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1985.18it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 116/1000 [00:00<00:00, 1157.35it/s]

Bootstrapping roc_auc:  23%|██▎       | 233/1000 [00:00<00:00, 1158.89it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 1172.48it/s]

Bootstrapping roc_auc:  47%|████▋     | 470/1000 [00:00<00:00, 1173.88it/s]

Bootstrapping roc_auc:  59%|█████▉    | 590/1000 [00:00<00:00, 1181.25it/s]

Bootstrapping roc_auc:  71%|███████▏  | 713/1000 [00:00<00:00, 1195.99it/s]

Bootstrapping roc_auc:  84%|████████▍ | 838/1000 [00:00<00:00, 1211.53it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:00<00:00, 1198.92it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1188.22it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 140/1000 [00:00<00:00, 1399.76it/s]

Bootstrapping precision:  28%|██▊       | 282/1000 [00:00<00:00, 1405.76it/s]

Bootstrapping precision:  42%|████▎     | 425/1000 [00:00<00:00, 1413.42it/s]

Bootstrapping precision:  57%|█████▋    | 567/1000 [00:00<00:00, 1410.34it/s]

Bootstrapping precision:  71%|███████   | 709/1000 [00:00<00:00, 1392.72it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1385.34it/s]

Bootstrapping precision:  99%|█████████▉| 989/1000 [00:00<00:00, 1389.67it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1393.75it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1423.56it/s]

Bootstrapping recall:  29%|██▊       | 286/1000 [00:00<00:00, 1426.95it/s]

Bootstrapping recall:  43%|████▎     | 429/1000 [00:00<00:00, 1416.52it/s]

Bootstrapping recall:  57%|█████▋    | 573/1000 [00:00<00:00, 1422.19it/s]

Bootstrapping recall:  72%|███████▏  | 716/1000 [00:00<00:00, 1423.59it/s]

Bootstrapping recall:  86%|████████▌ | 859/1000 [00:00<00:00, 1423.92it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1419.22it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 142/1000 [00:00<00:00, 1410.23it/s]

Bootstrapping f1:  28%|██▊       | 285/1000 [00:00<00:00, 1417.13it/s]

Bootstrapping f1:  43%|████▎     | 427/1000 [00:00<00:00, 1411.03it/s]

Bootstrapping f1:  57%|█████▋    | 569/1000 [00:00<00:00, 1411.72it/s]

Bootstrapping f1:  71%|███████   | 711/1000 [00:00<00:00, 1404.88it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1403.91it/s]

Bootstrapping f1: 100%|█████████▉| 995/1000 [00:00<00:00, 1409.30it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1407.25it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 411/1000 [00:00<00:00, 4108.30it/s]

Bootstrapping accuracy:  83%|████████▎ | 830/1000 [00:00<00:00, 4150.42it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4136.50it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 198/1000 [00:00<00:00, 1973.77it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1998.34it/s]

Bootstrapping average_precision:  60%|██████    | 600/1000 [00:00<00:00, 1983.69it/s]

Bootstrapping average_precision:  80%|████████  | 801/1000 [00:00<00:00, 1992.19it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1985.75it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1209.85it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 1212.34it/s]

Bootstrapping roc_auc:  36%|███▋      | 365/1000 [00:00<00:00, 1205.27it/s]

Bootstrapping roc_auc:  49%|████▊     | 486/1000 [00:00<00:00, 1198.32it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 1185.91it/s]

Bootstrapping roc_auc:  72%|███████▎  | 725/1000 [00:00<00:00, 1181.59it/s]

Bootstrapping roc_auc:  84%|████████▍ | 844/1000 [00:00<00:00, 1176.94it/s]

Bootstrapping roc_auc:  96%|█████████▌| 962/1000 [00:00<00:00, 1167.57it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1180.37it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▎        | 135/1000 [00:00<00:00, 1342.70it/s]

Bootstrapping precision:  27%|██▋       | 272/1000 [00:00<00:00, 1354.38it/s]

Bootstrapping precision:  41%|████▏     | 414/1000 [00:00<00:00, 1383.21it/s]

Bootstrapping precision:  56%|█████▌    | 556/1000 [00:00<00:00, 1396.36it/s]

Bootstrapping precision:  70%|██████▉   | 696/1000 [00:00<00:00, 1384.22it/s]

Bootstrapping precision:  84%|████████▎ | 835/1000 [00:00<00:00, 1382.33it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1393.77it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1382.96it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 134/1000 [00:00<00:00, 1336.60it/s]

Bootstrapping recall:  27%|██▋       | 274/1000 [00:00<00:00, 1368.60it/s]

Bootstrapping recall:  41%|████      | 411/1000 [00:00<00:00, 1366.45it/s]

Bootstrapping recall:  55%|█████▍    | 548/1000 [00:00<00:00, 1340.65it/s]

Bootstrapping recall:  68%|██████▊   | 683/1000 [00:00<00:00, 1340.15it/s]

Bootstrapping recall:  82%|████████▏ | 820/1000 [00:00<00:00, 1347.26it/s]

Bootstrapping recall:  96%|█████████▌| 955/1000 [00:00<00:00, 1335.67it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1339.20it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 129/1000 [00:00<00:00, 1282.89it/s]

Bootstrapping f1:  27%|██▋       | 268/1000 [00:00<00:00, 1344.74it/s]

Bootstrapping f1:  41%|████      | 409/1000 [00:00<00:00, 1371.97it/s]

Bootstrapping f1:  55%|█████▌    | 550/1000 [00:00<00:00, 1386.66it/s]

Bootstrapping f1:  69%|██████▉   | 689/1000 [00:00<00:00, 1373.33it/s]

Bootstrapping f1:  83%|████████▎ | 827/1000 [00:00<00:00, 1361.72it/s]

Bootstrapping f1:  96%|█████████▋| 964/1000 [00:00<00:00, 1334.69it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1348.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 408/1000 [00:00<00:00, 4072.55it/s]

Bootstrapping accuracy:  82%|████████▎ | 825/1000 [00:00<00:00, 4128.86it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4115.04it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 197/1000 [00:00<00:00, 1964.01it/s]

Bootstrapping average_precision:  40%|███▉      | 398/1000 [00:00<00:00, 1986.95it/s]

Bootstrapping average_precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1987.87it/s]

Bootstrapping average_precision:  80%|███████▉  | 796/1000 [00:00<00:00, 1958.17it/s]

Bootstrapping average_precision:  99%|█████████▉| 992/1000 [00:00<00:00, 1944.58it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1953.09it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  11%|█         | 112/1000 [00:00<00:00, 1119.05it/s]

Bootstrapping roc_auc:  23%|██▎       | 230/1000 [00:00<00:00, 1153.56it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 1175.48it/s]

Bootstrapping roc_auc:  47%|████▋     | 471/1000 [00:00<00:00, 1182.04it/s]

Bootstrapping roc_auc:  59%|█████▉    | 590/1000 [00:00<00:00, 1184.04it/s]

Bootstrapping roc_auc:  71%|███████   | 710/1000 [00:00<00:00, 1189.27it/s]

Bootstrapping roc_auc:  83%|████████▎ | 830/1000 [00:00<00:00, 1191.17it/s]

Bootstrapping roc_auc:  95%|█████████▌| 950/1000 [00:00<00:00, 1180.43it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1179.25it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 138/1000 [00:00<00:00, 1379.52it/s]

Bootstrapping precision:  28%|██▊       | 278/1000 [00:00<00:00, 1385.90it/s]

Bootstrapping precision:  42%|████▏     | 418/1000 [00:00<00:00, 1391.31it/s]

Bootstrapping precision:  56%|█████▌    | 559/1000 [00:00<00:00, 1397.70it/s]

Bootstrapping precision:  70%|███████   | 701/1000 [00:00<00:00, 1403.42it/s]

Bootstrapping precision:  84%|████████▍ | 842/1000 [00:00<00:00, 1399.74it/s]

Bootstrapping precision:  98%|█████████▊| 982/1000 [00:00<00:00, 1396.81it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1394.56it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1410.25it/s]

Bootstrapping recall:  28%|██▊       | 284/1000 [00:00<00:00, 1414.53it/s]

Bootstrapping recall:  43%|████▎     | 426/1000 [00:00<00:00, 1416.11it/s]

Bootstrapping recall:  57%|█████▋    | 568/1000 [00:00<00:00, 1408.25it/s]

Bootstrapping recall:  71%|███████   | 709/1000 [00:00<00:00, 1406.22it/s]

Bootstrapping recall:  85%|████████▌ | 851/1000 [00:00<00:00, 1408.51it/s]

Bootstrapping recall:  99%|█████████▉| 994/1000 [00:00<00:00, 1413.98it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1410.31it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1426.83it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1419.74it/s]

Bootstrapping f1:  43%|████▎     | 428/1000 [00:00<00:00, 1411.10it/s]

Bootstrapping f1:  57%|█████▋    | 570/1000 [00:00<00:00, 1413.00it/s]

Bootstrapping f1:  71%|███████   | 712/1000 [00:00<00:00, 1415.36it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1419.15it/s]

Bootstrapping f1: 100%|█████████▉| 997/1000 [00:00<00:00, 1407.89it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1410.98it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 413/1000 [00:00<00:00, 4125.50it/s]

Bootstrapping accuracy:  83%|████████▎ | 830/1000 [00:00<00:00, 4150.93it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4146.36it/s]

Processing Simplified Golem $\cap$ Simplified PCMB (6 nodes, 5 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1326.40it/s]

Bootstrapping average_precision:  27%|██▋       | 267/1000 [00:00<00:00, 1332.39it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 1332.89it/s]

Bootstrapping average_precision:  54%|█████▎    | 536/1000 [00:00<00:00, 1339.10it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1346.78it/s]

Bootstrapping average_precision:  81%|████████  | 809/1000 [00:00<00:00, 1350.02it/s]

Bootstrapping average_precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1353.62it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1343.85it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 81/1000 [00:00<00:01, 806.78it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 805.53it/s]

Bootstrapping roc_auc:  24%|██▍       | 245/1000 [00:00<00:00, 815.57it/s]

Bootstrapping roc_auc:  33%|███▎      | 329/1000 [00:00<00:00, 824.97it/s]

Bootstrapping roc_auc:  42%|████▏     | 416/1000 [00:00<00:00, 838.03it/s]

Bootstrapping roc_auc:  50%|█████     | 501/1000 [00:00<00:00, 840.12it/s]

Bootstrapping roc_auc:  59%|█████▊    | 586/1000 [00:00<00:00, 842.26it/s]

Bootstrapping roc_auc:  67%|██████▋   | 673/1000 [00:00<00:00, 849.78it/s]

Bootstrapping roc_auc:  76%|███████▌  | 759/1000 [00:00<00:00, 852.95it/s]

Bootstrapping roc_auc:  85%|████████▍ | 846/1000 [00:01<00:00, 855.84it/s]

Bootstrapping roc_auc:  93%|█████████▎| 932/1000 [00:01<00:00, 854.36it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 843.54it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1204.82it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1208.46it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1210.98it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1211.20it/s]

Bootstrapping precision:  61%|██████    | 609/1000 [00:00<00:00, 1208.06it/s]

Bootstrapping precision:  73%|███████▎  | 731/1000 [00:00<00:00, 1210.39it/s]

Bootstrapping precision:  85%|████████▌ | 853/1000 [00:00<00:00, 1193.86it/s]

Bootstrapping precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1187.80it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.47it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1173.60it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1170.35it/s]

Bootstrapping recall:  36%|███▌      | 358/1000 [00:00<00:00, 1190.14it/s]

Bootstrapping recall:  48%|████▊     | 481/1000 [00:00<00:00, 1202.18it/s]

Bootstrapping recall:  60%|██████    | 602/1000 [00:00<00:00, 1203.59it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1202.64it/s]

Bootstrapping recall:  84%|████████▍ | 845/1000 [00:00<00:00, 1206.98it/s]

Bootstrapping recall:  97%|█████████▋| 967/1000 [00:00<00:00, 1210.05it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1201.80it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1218.46it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1200.75it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1165.63it/s]

Bootstrapping f1:  48%|████▊     | 482/1000 [00:00<00:00, 1166.56it/s]

Bootstrapping f1:  60%|██████    | 603/1000 [00:00<00:00, 1179.18it/s]

Bootstrapping f1:  72%|███████▏  | 724/1000 [00:00<00:00, 1187.32it/s]

Bootstrapping f1:  84%|████████▍ | 843/1000 [00:00<00:00, 1163.57it/s]

Bootstrapping f1:  96%|█████████▌| 960/1000 [00:00<00:00, 1154.31it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1167.35it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 331/1000 [00:00<00:00, 3304.68it/s]

Bootstrapping accuracy:  67%|██████▋   | 668/1000 [00:00<00:00, 3341.01it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3341.47it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 206/1000 [00:00<00:00, 2050.47it/s]

Bootstrapping average_precision:  41%|████▏     | 413/1000 [00:00<00:00, 2056.02it/s]

Bootstrapping average_precision:  62%|██████▏   | 621/1000 [00:00<00:00, 2063.91it/s]

Bootstrapping average_precision:  83%|████████▎ | 829/1000 [00:00<00:00, 2068.15it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2060.47it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 120/1000 [00:00<00:00, 1196.77it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 1212.97it/s]

Bootstrapping roc_auc:  37%|███▋      | 367/1000 [00:00<00:00, 1223.17it/s]

Bootstrapping roc_auc:  49%|████▉     | 492/1000 [00:00<00:00, 1230.75it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 1212.16it/s]

Bootstrapping roc_auc:  74%|███████▍  | 741/1000 [00:00<00:00, 1224.34it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:00<00:00, 1237.61it/s]

Bootstrapping roc_auc: 100%|█████████▉| 995/1000 [00:00<00:00, 1247.19it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1231.38it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1426.34it/s]

Bootstrapping precision:  29%|██▊       | 286/1000 [00:00<00:00, 1421.32it/s]

Bootstrapping precision:  43%|████▎     | 429/1000 [00:00<00:00, 1408.38it/s]

Bootstrapping precision:  57%|█████▋    | 572/1000 [00:00<00:00, 1413.43it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1423.12it/s]

Bootstrapping precision:  86%|████████▌ | 861/1000 [00:00<00:00, 1428.54it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1421.18it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1417.93it/s]

Bootstrapping recall:  29%|██▊       | 287/1000 [00:00<00:00, 1431.74it/s]

Bootstrapping recall:  43%|████▎     | 431/1000 [00:00<00:00, 1433.71it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1431.48it/s]

Bootstrapping recall:  72%|███████▏  | 719/1000 [00:00<00:00, 1425.11it/s]

Bootstrapping recall:  86%|████████▌ | 862/1000 [00:00<00:00, 1422.52it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1427.30it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 144/1000 [00:00<00:00, 1430.28it/s]

Bootstrapping f1:  29%|██▉       | 289/1000 [00:00<00:00, 1436.10it/s]

Bootstrapping f1:  43%|████▎     | 433/1000 [00:00<00:00, 1428.02it/s]

Bootstrapping f1:  58%|█████▊    | 577/1000 [00:00<00:00, 1429.56it/s]

Bootstrapping f1:  72%|███████▏  | 721/1000 [00:00<00:00, 1430.20it/s]

Bootstrapping f1:  86%|████████▋ | 865/1000 [00:00<00:00, 1433.06it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1432.96it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 416/1000 [00:00<00:00, 4151.24it/s]

Bootstrapping accuracy:  83%|████████▎ | 832/1000 [00:00<00:00, 4041.29it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4035.99it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  19%|█▉        | 191/1000 [00:00<00:00, 1908.29it/s]

Bootstrapping average_precision:  38%|███▊      | 382/1000 [00:00<00:00, 1902.20it/s]

Bootstrapping average_precision:  57%|█████▋    | 573/1000 [00:00<00:00, 1901.10it/s]

Bootstrapping average_precision:  76%|███████▋  | 764/1000 [00:00<00:00, 1893.29it/s]

Bootstrapping average_precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1901.15it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1901.06it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  11%|█▏        | 114/1000 [00:00<00:00, 1131.11it/s]

Bootstrapping roc_auc:  23%|██▎       | 232/1000 [00:00<00:00, 1154.85it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 1154.69it/s]

Bootstrapping roc_auc:  47%|████▋     | 468/1000 [00:00<00:00, 1171.96it/s]

Bootstrapping roc_auc:  59%|█████▉    | 588/1000 [00:00<00:00, 1181.54it/s]

Bootstrapping roc_auc:  71%|███████   | 707/1000 [00:00<00:00, 1181.92it/s]

Bootstrapping roc_auc:  83%|████████▎ | 826/1000 [00:00<00:00, 1167.99it/s]

Bootstrapping roc_auc:  94%|█████████▍| 943/1000 [00:00<00:00, 1166.67it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1165.99it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 138/1000 [00:00<00:00, 1371.88it/s]

Bootstrapping precision:  28%|██▊       | 276/1000 [00:00<00:00, 1359.47it/s]

Bootstrapping precision:  41%|████      | 412/1000 [00:00<00:00, 1341.18it/s]

Bootstrapping precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1332.74it/s]

Bootstrapping precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1328.34it/s]

Bootstrapping precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1333.99it/s]

Bootstrapping precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1336.82it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1334.55it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 133/1000 [00:00<00:00, 1316.45it/s]

Bootstrapping recall:  27%|██▋       | 266/1000 [00:00<00:00, 1321.48it/s]

Bootstrapping recall:  40%|████      | 401/1000 [00:00<00:00, 1333.20it/s]

Bootstrapping recall:  54%|█████▎    | 535/1000 [00:00<00:00, 1334.32it/s]

Bootstrapping recall:  67%|██████▋   | 674/1000 [00:00<00:00, 1351.87it/s]

Bootstrapping recall:  82%|████████▏ | 815/1000 [00:00<00:00, 1369.73it/s]

Bootstrapping recall:  95%|█████████▌| 953/1000 [00:00<00:00, 1372.14it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1354.11it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 134/1000 [00:00<00:00, 1336.50it/s]

Bootstrapping f1:  27%|██▋       | 268/1000 [00:00<00:00, 1310.84it/s]

Bootstrapping f1:  40%|████      | 400/1000 [00:00<00:00, 1312.91it/s]

Bootstrapping f1:  53%|█████▎    | 532/1000 [00:00<00:00, 1311.37it/s]

Bootstrapping f1:  67%|██████▋   | 672/1000 [00:00<00:00, 1340.65it/s]

Bootstrapping f1:  81%|████████▏ | 813/1000 [00:00<00:00, 1360.86it/s]

Bootstrapping f1:  95%|█████████▌| 954/1000 [00:00<00:00, 1376.52it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1350.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|███▉      | 399/1000 [00:00<00:00, 3989.68it/s]

Bootstrapping accuracy:  80%|████████  | 800/1000 [00:00<00:00, 4000.71it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4013.55it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 200/1000 [00:00<00:00, 1993.68it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 2005.50it/s]

Bootstrapping average_precision:  60%|██████    | 603/1000 [00:00<00:00, 2006.90it/s]

Bootstrapping average_precision:  80%|████████  | 804/1000 [00:00<00:00, 1963.43it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1952.51it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  11%|█         | 111/1000 [00:00<00:00, 1102.21it/s]

Bootstrapping roc_auc:  22%|██▏       | 222/1000 [00:00<00:00, 1097.77it/s]

Bootstrapping roc_auc:  33%|███▎      | 334/1000 [00:00<00:00, 1105.92it/s]

Bootstrapping roc_auc:  45%|████▍     | 449/1000 [00:00<00:00, 1119.86it/s]

Bootstrapping roc_auc:  57%|█████▋    | 569/1000 [00:00<00:00, 1147.56it/s]

Bootstrapping roc_auc:  68%|██████▊   | 684/1000 [00:00<00:00, 1098.16it/s]

Bootstrapping roc_auc:  80%|████████  | 802/1000 [00:00<00:00, 1122.28it/s]

Bootstrapping roc_auc:  92%|█████████▏| 915/1000 [00:00<00:00, 1109.23it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1115.35it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▎        | 137/1000 [00:00<00:00, 1363.62it/s]

Bootstrapping precision:  27%|██▋       | 274/1000 [00:00<00:00, 1336.55it/s]

Bootstrapping precision:  41%|████      | 409/1000 [00:00<00:00, 1338.41it/s]

Bootstrapping precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1352.60it/s]

Bootstrapping precision:  69%|██████▊   | 686/1000 [00:00<00:00, 1364.42it/s]

Bootstrapping precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1378.45it/s]

Bootstrapping precision:  96%|█████████▋| 965/1000 [00:00<00:00, 1354.65it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1353.17it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  13%|█▎        | 131/1000 [00:00<00:00, 1308.61it/s]

Bootstrapping recall:  27%|██▋       | 269/1000 [00:00<00:00, 1348.36it/s]

Bootstrapping recall:  41%|████      | 411/1000 [00:00<00:00, 1379.97it/s]

Bootstrapping recall:  55%|█████▍    | 549/1000 [00:00<00:00, 1365.51it/s]

Bootstrapping recall:  69%|██████▊   | 686/1000 [00:00<00:00, 1348.78it/s]

Bootstrapping recall:  82%|████████▏ | 823/1000 [00:00<00:00, 1355.17it/s]

Bootstrapping recall:  96%|█████████▌| 959/1000 [00:00<00:00, 1344.62it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1348.40it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 134/1000 [00:00<00:00, 1331.30it/s]

Bootstrapping f1:  27%|██▋       | 270/1000 [00:00<00:00, 1346.53it/s]

Bootstrapping f1:  40%|████      | 405/1000 [00:00<00:00, 1332.14it/s]

Bootstrapping f1:  54%|█████▍    | 540/1000 [00:00<00:00, 1335.94it/s]

Bootstrapping f1:  68%|██████▊   | 682/1000 [00:00<00:00, 1362.85it/s]

Bootstrapping f1:  82%|████████▏ | 819/1000 [00:00<00:00, 1361.12it/s]

Bootstrapping f1:  96%|█████████▌| 956/1000 [00:00<00:00, 1341.43it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1343.67it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 412/1000 [00:00<00:00, 4118.85it/s]

Bootstrapping accuracy:  83%|████████▎ | 827/1000 [00:00<00:00, 4134.57it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4115.69it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem (5 nodes, 4 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1285.82it/s]

Bootstrapping average_precision:  26%|██▌       | 259/1000 [00:00<00:00, 1293.61it/s]

Bootstrapping average_precision:  39%|███▉      | 391/1000 [00:00<00:00, 1302.04it/s]

Bootstrapping average_precision:  52%|█████▏    | 522/1000 [00:00<00:00, 1302.78it/s]

Bootstrapping average_precision:  65%|██████▌   | 653/1000 [00:00<00:00, 1299.13it/s]

Bootstrapping average_precision:  78%|███████▊  | 783/1000 [00:00<00:00, 1298.80it/s]

Bootstrapping average_precision:  91%|█████████▏| 914/1000 [00:00<00:00, 1300.44it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1299.30it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 832.09it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:01, 812.19it/s]

Bootstrapping roc_auc:  25%|██▌       | 250/1000 [00:00<00:00, 801.82it/s]

Bootstrapping roc_auc:  33%|███▎      | 332/1000 [00:00<00:00, 805.66it/s]

Bootstrapping roc_auc:  42%|████▏     | 416/1000 [00:00<00:00, 817.74it/s]

Bootstrapping roc_auc:  50%|█████     | 503/1000 [00:00<00:00, 832.18it/s]

Bootstrapping roc_auc:  59%|█████▉    | 590/1000 [00:00<00:00, 844.20it/s]

Bootstrapping roc_auc:  68%|██████▊   | 677/1000 [00:00<00:00, 850.02it/s]

Bootstrapping roc_auc:  76%|███████▋  | 763/1000 [00:00<00:00, 850.11it/s]

Bootstrapping roc_auc:  85%|████████▌ | 850/1000 [00:01<00:00, 855.12it/s]

Bootstrapping roc_auc:  94%|█████████▍| 938/1000 [00:01<00:00, 859.85it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 842.35it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1203.90it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1203.23it/s]

Bootstrapping precision:  36%|███▋      | 364/1000 [00:00<00:00, 1207.62it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1213.90it/s]

Bootstrapping precision:  61%|██████    | 609/1000 [00:00<00:00, 1212.27it/s]

Bootstrapping precision:  73%|███████▎  | 732/1000 [00:00<00:00, 1214.97it/s]

Bootstrapping precision:  85%|████████▌ | 854/1000 [00:00<00:00, 1214.47it/s]

Bootstrapping precision:  98%|█████████▊| 976/1000 [00:00<00:00, 1213.56it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1211.60it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1213.29it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1215.14it/s]

Bootstrapping recall:  37%|███▋      | 367/1000 [00:00<00:00, 1221.71it/s]

Bootstrapping recall:  49%|████▉     | 490/1000 [00:00<00:00, 1210.30it/s]

Bootstrapping recall:  61%|██████    | 612/1000 [00:00<00:00, 1205.78it/s]

Bootstrapping recall:  73%|███████▎  | 734/1000 [00:00<00:00, 1208.88it/s]

Bootstrapping recall:  86%|████████▌ | 857/1000 [00:00<00:00, 1214.39it/s]

Bootstrapping recall:  98%|█████████▊| 979/1000 [00:00<00:00, 1215.16it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1212.59it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1198.73it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1205.93it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1169.39it/s]

Bootstrapping f1:  48%|████▊     | 481/1000 [00:00<00:00, 1162.89it/s]

Bootstrapping f1:  60%|█████▉    | 598/1000 [00:00<00:00, 1162.20it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1167.28it/s]

Bootstrapping f1:  83%|████████▎ | 834/1000 [00:00<00:00, 1171.36it/s]

Bootstrapping f1:  95%|█████████▌| 952/1000 [00:00<00:00, 1168.86it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1170.07it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 349/1000 [00:00<00:00, 3485.86it/s]

Bootstrapping accuracy:  70%|██████▉   | 698/1000 [00:00<00:00, 3477.50it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3487.77it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 210/1000 [00:00<00:00, 2092.07it/s]

Bootstrapping average_precision:  42%|████▏     | 420/1000 [00:00<00:00, 2096.00it/s]

Bootstrapping average_precision:  63%|██████▎   | 633/1000 [00:00<00:00, 2107.69it/s]

Bootstrapping average_precision:  84%|████████▍ | 844/1000 [00:00<00:00, 2083.88it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2092.19it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 126/1000 [00:00<00:00, 1258.69it/s]

Bootstrapping roc_auc:  25%|██▌       | 252/1000 [00:00<00:00, 1230.11it/s]

Bootstrapping roc_auc:  38%|███▊      | 376/1000 [00:00<00:00, 1225.27it/s]

Bootstrapping roc_auc:  50%|█████     | 502/1000 [00:00<00:00, 1235.95it/s]

Bootstrapping roc_auc:  63%|██████▎   | 629/1000 [00:00<00:00, 1245.01it/s]

Bootstrapping roc_auc:  76%|███████▌  | 755/1000 [00:00<00:00, 1249.84it/s]

Bootstrapping roc_auc:  88%|████████▊ | 881/1000 [00:00<00:00, 1231.30it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1227.38it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 140/1000 [00:00<00:00, 1399.58it/s]

Bootstrapping precision:  28%|██▊       | 283/1000 [00:00<00:00, 1415.84it/s]

Bootstrapping precision:  43%|████▎     | 426/1000 [00:00<00:00, 1420.19it/s]

Bootstrapping precision:  57%|█████▋    | 570/1000 [00:00<00:00, 1424.47it/s]

Bootstrapping precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1419.10it/s]

Bootstrapping precision:  86%|████████▌ | 857/1000 [00:00<00:00, 1423.68it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1424.04it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1428.76it/s]

Bootstrapping recall:  29%|██▊       | 287/1000 [00:00<00:00, 1434.90it/s]

Bootstrapping recall:  43%|████▎     | 431/1000 [00:00<00:00, 1436.92it/s]

Bootstrapping recall:  58%|█████▊    | 576/1000 [00:00<00:00, 1439.70it/s]

Bootstrapping recall:  72%|███████▏  | 721/1000 [00:00<00:00, 1442.91it/s]

Bootstrapping recall:  87%|████████▋ | 866/1000 [00:00<00:00, 1434.66it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1428.53it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 132/1000 [00:00<00:00, 1317.76it/s]

Bootstrapping f1:  26%|██▋       | 264/1000 [00:00<00:00, 1313.45it/s]

Bootstrapping f1:  40%|████      | 401/1000 [00:00<00:00, 1338.50it/s]

Bootstrapping f1:  54%|█████▍    | 539/1000 [00:00<00:00, 1353.49it/s]

Bootstrapping f1:  68%|██████▊   | 675/1000 [00:00<00:00, 1348.06it/s]

Bootstrapping f1:  82%|████████▏ | 817/1000 [00:00<00:00, 1370.63it/s]

Bootstrapping f1:  96%|█████████▌| 959/1000 [00:00<00:00, 1385.94it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1363.17it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 415/1000 [00:00<00:00, 4149.33it/s]

Bootstrapping accuracy:  83%|████████▎ | 831/1000 [00:00<00:00, 4151.13it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4144.95it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 198/1000 [00:00<00:00, 1974.10it/s]

Bootstrapping average_precision:  40%|███▉      | 399/1000 [00:00<00:00, 1991.38it/s]

Bootstrapping average_precision:  60%|██████    | 601/1000 [00:00<00:00, 2003.80it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 2004.65it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2001.11it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1208.15it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 1209.75it/s]

Bootstrapping roc_auc:  36%|███▋      | 365/1000 [00:00<00:00, 1211.05it/s]

Bootstrapping roc_auc:  49%|████▊     | 487/1000 [00:00<00:00, 1203.29it/s]

Bootstrapping roc_auc:  61%|██████    | 608/1000 [00:00<00:00, 1203.47it/s]

Bootstrapping roc_auc:  73%|███████▎  | 730/1000 [00:00<00:00, 1207.79it/s]

Bootstrapping roc_auc:  85%|████████▌ | 852/1000 [00:00<00:00, 1208.21it/s]

Bootstrapping roc_auc:  97%|█████████▋| 974/1000 [00:00<00:00, 1211.66it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1207.72it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 139/1000 [00:00<00:00, 1388.33it/s]

Bootstrapping precision:  28%|██▊       | 280/1000 [00:00<00:00, 1397.59it/s]

Bootstrapping precision:  42%|████▏     | 422/1000 [00:00<00:00, 1407.43it/s]

Bootstrapping precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1399.34it/s]

Bootstrapping precision:  70%|███████   | 703/1000 [00:00<00:00, 1395.55it/s]

Bootstrapping precision:  84%|████████▍ | 843/1000 [00:00<00:00, 1392.49it/s]

Bootstrapping precision:  98%|█████████▊| 983/1000 [00:00<00:00, 1385.75it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1390.89it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 139/1000 [00:00<00:00, 1380.66it/s]

Bootstrapping recall:  28%|██▊       | 278/1000 [00:00<00:00, 1379.46it/s]

Bootstrapping recall:  42%|████▏     | 418/1000 [00:00<00:00, 1386.73it/s]

Bootstrapping recall:  56%|█████▌    | 558/1000 [00:00<00:00, 1391.89it/s]

Bootstrapping recall:  70%|██████▉   | 698/1000 [00:00<00:00, 1388.25it/s]

Bootstrapping recall:  84%|████████▎ | 837/1000 [00:00<00:00, 1354.10it/s]

Bootstrapping recall:  98%|█████████▊| 976/1000 [00:00<00:00, 1363.74it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1370.94it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 133/1000 [00:00<00:00, 1321.69it/s]

Bootstrapping f1:  27%|██▋       | 269/1000 [00:00<00:00, 1343.21it/s]

Bootstrapping f1:  41%|████      | 410/1000 [00:00<00:00, 1370.87it/s]

Bootstrapping f1:  55%|█████▍    | 549/1000 [00:00<00:00, 1378.22it/s]

Bootstrapping f1:  69%|██████▉   | 688/1000 [00:00<00:00, 1380.30it/s]

Bootstrapping f1:  83%|████████▎ | 827/1000 [00:00<00:00, 1372.17it/s]

Bootstrapping f1:  97%|█████████▋| 967/1000 [00:00<00:00, 1378.38it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1371.71it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 414/1000 [00:00<00:00, 4138.67it/s]

Bootstrapping accuracy:  83%|████████▎ | 828/1000 [00:00<00:00, 4016.18it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3995.33it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 196/1000 [00:00<00:00, 1952.68it/s]

Bootstrapping average_precision:  40%|███▉      | 397/1000 [00:00<00:00, 1982.27it/s]

Bootstrapping average_precision:  60%|█████▉    | 596/1000 [00:00<00:00, 1974.84it/s]

Bootstrapping average_precision:  79%|███████▉  | 794/1000 [00:00<00:00, 1940.57it/s]

Bootstrapping average_precision:  99%|█████████▉| 989/1000 [00:00<00:00, 1895.59it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1919.10it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  11%|█         | 108/1000 [00:00<00:00, 1078.37it/s]

Bootstrapping roc_auc:  22%|██▏       | 219/1000 [00:00<00:00, 1092.35it/s]

Bootstrapping roc_auc:  34%|███▍      | 338/1000 [00:00<00:00, 1133.34it/s]

Bootstrapping roc_auc:  45%|████▌     | 452/1000 [00:00<00:00, 1064.11it/s]

Bootstrapping roc_auc:  56%|█████▋    | 563/1000 [00:00<00:00, 1079.63it/s]

Bootstrapping roc_auc:  68%|██████▊   | 678/1000 [00:00<00:00, 1100.36it/s]

Bootstrapping roc_auc:  80%|███████▉  | 798/1000 [00:00<00:00, 1129.35it/s]

Bootstrapping roc_auc:  92%|█████████▏| 920/1000 [00:00<00:00, 1154.82it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1126.34it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1401.73it/s]

Bootstrapping precision:  28%|██▊       | 283/1000 [00:00<00:00, 1411.17it/s]

Bootstrapping precision:  42%|████▎     | 425/1000 [00:00<00:00, 1408.15it/s]

Bootstrapping precision:  57%|█████▋    | 567/1000 [00:00<00:00, 1412.65it/s]

Bootstrapping precision:  71%|███████   | 710/1000 [00:00<00:00, 1416.96it/s]

Bootstrapping precision:  85%|████████▌ | 853/1000 [00:00<00:00, 1418.51it/s]

Bootstrapping precision: 100%|█████████▉| 996/1000 [00:00<00:00, 1420.65it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1414.98it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 140/1000 [00:00<00:00, 1396.47it/s]

Bootstrapping recall:  28%|██▊       | 281/1000 [00:00<00:00, 1400.88it/s]

Bootstrapping recall:  42%|████▏     | 423/1000 [00:00<00:00, 1406.68it/s]

Bootstrapping recall:  57%|█████▋    | 566/1000 [00:00<00:00, 1412.97it/s]

Bootstrapping recall:  71%|███████   | 709/1000 [00:00<00:00, 1416.32it/s]

Bootstrapping recall:  85%|████████▌ | 851/1000 [00:00<00:00, 1406.30it/s]

Bootstrapping recall:  99%|█████████▉| 993/1000 [00:00<00:00, 1409.29it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1407.45it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 142/1000 [00:00<00:00, 1412.18it/s]

Bootstrapping f1:  28%|██▊       | 285/1000 [00:00<00:00, 1421.61it/s]

Bootstrapping f1:  43%|████▎     | 428/1000 [00:00<00:00, 1413.30it/s]

Bootstrapping f1:  57%|█████▋    | 570/1000 [00:00<00:00, 1411.52it/s]

Bootstrapping f1:  71%|███████   | 712/1000 [00:00<00:00, 1410.24it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1410.29it/s]

Bootstrapping f1: 100%|█████████▉| 996/1000 [00:00<00:00, 1410.90it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1410.34it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 415/1000 [00:00<00:00, 4143.48it/s]

Bootstrapping accuracy:  83%|████████▎ | 830/1000 [00:00<00:00, 4138.71it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4134.77it/s]

In [8]:
results_df.to_csv('biomarker_counts_fixed/Year Sensitivity.csv', index=False)
results_df

,Model,DAG,Year,# Features,# Biomarkers,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE
0,XGB,Control,All,811,45,"0.81 (0.78, 0.84)","0.93 (0.91, 0.95)","0.94 (0.92, 0.95)","0.80 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.089
1,XGB,Control,2020,811,45,"0.81 (0.76, 0.86)","0.93 (0.90, 0.95)","0.93 (0.90, 0.96)","0.82 (0.78, 0.85)","0.86 (0.83, 0.89)","0.94 (0.93, 0.96)",0.110
2,XGB,Control,2021,811,45,"0.82 (0.77, 0.88)","0.95 (0.93, 0.97)","0.95 (0.93, 0.98)","0.79 (0.74, 0.83)","0.85 (0.81, 0.88)","0.95 (0.94, 0.96)",0.079
3,XGB,Control,2022,811,45,"0.84 (0.78, 0.89)","0.93 (0.90, 0.96)","0.94 (0.91, 0.97)","0.84 (0.80, 0.88)","0.88 (0.85, 0.91)","0.97 (0.96, 0.97)",0.083
4,XGB,Correlation,All,113,37,"0.75 (0.71, 0.78)","0.90 (0.88, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.108
5,XGB,Correlation,2020,113,37,"0.75 (0.69, 0.81)","0.89 (0.86, 0.92)","0.90 (0.86, 0.93)","0.77 (0.73, 0.81)","0.82 (0.78, 0.85)","0.93 (0.91, 0.94)",0.125
6,XGB,Correlation,2021,113,37,"0.77 (0.70, 0.82)","0.91 (0.89, 0.94)","0.90 (0.86, 0.94)","0.80 (0.76, 0.83)","0.84 (0.80, 0.87)","0.95 (0.94, 0.96)",0.104
7,XGB,Correlation,2022,113,37,"0.77 (0.70, 0.83)","0.89 (0.85, 0.93)","0.90 (0.87, 0.94)","0.81 (0.77, 0.85)","0.85 (0.82, 0.88)","0.96 (0.95, 0.97)",0.099
8,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,All,334,19,"0.77 (0.74, 0.81)","0.91 (0.89, 0.93)","0.92 (0.91, 0.94)","0.79 (0.77, 0.82)","0.84 (0.82, 0.87)","0.95 (0.94, 0.96)",0.092
9,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2020,334,19,"0.77 (0.71, 0.82)","0.90 (0.87, 0.93)","0.92 (0.89, 0.95)","0.78 (0.74, 0.82)","0.83 (0.79, 0.86)","0.93 (0.92, 0.95)",0.112
10,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2021,334,19,"0.81 (0.75, 0.86)","0.93 (0.90, 0.95)","0.94 (0.92, 0.97)","0.80 (0.76, 0.84)","0.85 (0.82, 0.89)","0.95 (0.94, 0.96)",0.084
11,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2022,334,19,"0.80 (0.74, 0.86)","0.91 (0.87, 0.94)","0.92 (0.88, 0.95)","0.83 (0.79, 0.88)","0.87 (0.83, 0.91)","0.96 (0.95, 0.97)",0.085
12,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,All,408,23,"0.79 (0.76, 0.82)","0.91 (0.89, 0.93)","0.93 (0.91, 0.95)","0.80 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.094
13,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2020,408,23,"0.81 (0.75, 0.86)","0.92 (0.88, 0.94)","0.92 (0.88, 0.95)","0.80 (0.76, 0.83)","0.84 (0.81, 0.87)","0.93 (0.92, 0.95)",0.116
14,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2021,408,23,"0.79 (0.73, 0.85)","0.91 (0.88, 0.94)","0.95 (0.92, 0.97)","0.80 (0.76, 0.84)","0.85 (0.82, 0.89)","0.95 (0.94, 0.96)",0.085
15,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2022,408,23,"0.82 (0.76, 0.88)","0.92 (0.88, 0.95)","0.94 (0.91, 0.97)","0.85 (0.82, 0.89)","0.89 (0.86, 0.92)","0.97 (0.96, 0.98)",0.086
16,XGB,Simplified Golem $\cup$ Simplified PCMB,All,407,23,"0.78 (0.75, 0.81)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.94 (0.94, 0.95)",0.093
17,XGB,Simplified Golem $\cup$ Simplified PCMB,2020,407,23,"0.80 (0.74, 0.85)","0.92 (0.89, 0.94)","0.91 (0.88, 0.94)","0.79 (0.76, 0.83)","0.84 (0.80, 0.87)","0.93 (0.92, 0.95)",0.115
18,XGB,Simplified Golem $\cup$ Simplified PCMB,2021,407,23,"0.79 (0.73, 0.84)","0.91 (0.88, 0.94)","0.92 (0.89, 0.95)","0.79 (0.76, 0.84)","0.84 (0.81, 0.88)","0.95 (0.94, 0.96)",0.085
19,XGB,Simplified Golem $\cup$ Simplified PCMB,2022,407,23,"0.81 (0.74, 0.86)","0.92 (0.88, 0.96)","0.90 (0.86, 0.94)","0.82 (0.78, 0.86)","0.85 (0.82, 0.89)","0.96 (0.95, 0.97)",0.085
20,XGB,Simplified Clinician Consensus,All,278,16,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.94 (0.92, 0.95)","0.80 (0.77, 0.82)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.094
21,XGB,Simplified Clinician Consensus,2020,278,16,"0.80 (0.75, 0.85)","0.91 (0.88, 0.94)","0.93 (0.90, 0.95)","0.79 (0.75, 0.83)","0.84 (0.81, 0.87)","0.94 (0.92, 0.95)",0.114
22,XGB,Simplified Clinician Consensus,2021,278,16,"0.78 (0.72, 0.84)","0.92 (0.89, 0.95)","0.94 (0.91, 0.97)","0.79 (0.75, 0.83)","0.85 (0.81, 0.88)","0.95 (0.94, 0.96)",0.087
23,XGB,Simplified Clinician Consensus,2022,278,16,"0.81 (0.75, 0.87)","0.91 (0.87, 0.95)","0.95 (0.92, 0.97)","0.83 (0.79, 0.87)","0.88 (0.85, 0.91)","0.97 (0.96, 0.97)",0.084
24,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,All,240,14,"0.79 (0.75, 0.82)","0.91 (0.89, 0.93)","0.93 (0.91, 0.94)","0.80 (0.77, 0.82)","0.85 (0.82, 0.86)","0.95 (0.94, 0.96)",0.095
25,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2020,240,14,"0.80 (0.75, 0.86)","0.91 (0.88, 0.94)","0.92 (0.89, 0.95)","0.79 (0.75, 0.83)","0.84 (0.80, 0.87)","0.93 (0.92, 0.95)",0.117
26,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2021,240,14,"0.79 (0.73, 0.84)","0.92 (0.90, 0.95)","0.95 (0.92, 0.97)","0.79 (0.76, 0.83)","0.85 (0.82, 0.88)","0.95 (0.94, 0.96)",0.086
27,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2022,240,14,"0.81 (0.75, 0.87)","0.92 (0.87, 0.95)","0.93 (0.90, 0.96)","0.83 (0.79, 0.87)","0.87 (0.84, 0.90)","0.96 (0.95, 0.97)",0.087
28,XGB,Simplified PCMB,All,296,17,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.92 (0.91, 0.94)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.092
29,XGB,Simplified PCMB,2020,296,17,"0.79 (0.73, 0.84)","0.91 (0.88, 0.94)","0.92 (0.89, 0.95)","0.79 (0.75, 0.83)","0.84 (0.80, 0.87)","0.93 (0.92, 0.95)",0.110
30,XGB,Simplified PCMB,2021,296,17,"0.79 (0.74, 0.85)","0.91 (0.88, 0.94)","0.92 (0.89, 0.95)","0.78 (0.74, 0.82)","0.83 (0.80, 0.87)","0.95 (0.93, 0.96)",0.087
31,XGB,Simplified PCMB,2022,296,17,"0.82 (0.75, 0.87)","0.92 (0.88, 0.95)","0.95 (0.93, 0.98)","0.83 (0.79, 0.87)","0.88 (0.84, 0.91)","0.97 (0.96, 0.97)",0.084
32,XGB,Simplified Golem,All,199,11,"0.77 (0.74, 0.80)","0.91 (0.89, 0.93)","0.91 (0.90, 0.93)","0.79 (0.76, 0.81)","0.83 (0.82, 0.86)","0.94 (0.94, 0.95)",0.095
33,XGB,Simplified Golem,2020,199,11,"0.78 (0.72, 0.83)","0.91 (0.88, 0.94)","0.91 (0.88, 0.94)","0.78 (0.74, 0.81)","0.83 (0.79, 0.86)","0.93 (0.91, 0.94)",0.113
34,XGB,Simplified Golem,2021,199,11,"0.79 (0.73, 0.84)","0.93 (0.90, 0.95)","0.93 (0.90, 0.96)","0.79 (0.75, 0.83)","0.84 (0.80, 0.87)","0.95 (0.94, 0.96)",0.086
35,XGB,Simplified Golem,2022,199,11,"0.80 (0.73, 0.86)","0.92 (0.87, 0.95)","0.91 (0.87, 0.94)","0.82 (0.78, 0.86)","0.86 (0.82, 0.89)","0.96 (0.95, 0.97)",0.089
36,XGB,Simplified Golem $\cap$ Simplified PCMB,All,88,5,"0.76 (0.73, 0.80)","0.90 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102
37,XGB,Simplified Golem $\cap$ Simplified PCMB,2020,88,5,"0.78 (0.73, 0.84)","0.91 (0.88, 0.94)","0.90 (0.86, 0.93)","0.79 (0.74, 0.83)","0.83 (0.79, 0.86)","0.93 (0.91, 0.94)",0.120
38,XGB,Simplified Golem $\cap$ Simplified PCMB,2021,88,5,"0.77 (0.71, 0.83)","0.91 (0.88, 0.94)","0.93 (0.90, 0.96)","0.78 (0.74, 0.82)","0.84 (0.80, 0.87)","0.95 (0.94, 0.96)",0.093
39,XGB,Simplified Golem $\cap$ Simplified PCMB,2022,88,5,"0.78 (0.71, 0.84)","0.91 (0.87, 0.94)","0.90 (0.87, 0.94)","0.82 (0.78, 0.86)","0.86 (0.82, 0.89)","0.96 (0.95, 0.97)",0.094
40,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,All,69,4,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.76, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.106
41,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2020,69,4,"0.78 (0.73, 0.84)","0.90 (0.86, 0.93)","0.92 (0.88, 0.95)","0.79 (0.75, 0.83)","0.84 (0.80, 0.87)","0.93 (0.92, 0.95)",0.125
42,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2021,69,4,"0.73 (0.66, 0.79)","0.89 (0.86, 0.92)","0.90 (0.86, 0.93)","0.77 (0.73, 0.81)","0.82 (0.78, 0.85)","0.94 (0.93, 0.95)",0.098
43,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2022,69,4,"0.74 (0.67, 0.81)","0.88 (0.84, 0.92)","0.89 (0.85, 0.93)","0.81 (0.77, 0.85)","0.84 (0.81, 0.88)","0.95 (0.94, 0.96)",0.097

## Summary: AUROC, AUPRC, and Normalized AUPRC by Year
AUPRC depends on class prevalence (π), which differs across years (2020: 14%, 2021: 10%, 2022: 9%).
The **skill score** `(AUPRC − π) / (1 − π)` re-anchors to [0 = random, 1 = perfect] and makes years comparable.
CI bounds transform linearly since π is fixed per year.

In [9]:
def extract_point_ci(s):
    """Parse 'value (lower, upper)' string into three floats."""
    try:
        s = str(s).replace('(', '').replace(')', '').replace(',', '')
        parts = s.split()
        return float(parts[0]), float(parts[1]), float(parts[2])
    except Exception:
        v = float(s)
        return v, v, v

def extract_point(s):
    return extract_point_ci(s)[0]

def normalize_auprc(auprc_str, pi):
    """Apply skill-score normalization to an AUPRC string with CI."""
    pt, lo, hi = extract_point_ci(auprc_str)
    norm    = (pt - pi) / (1 - pi)
    norm_lo = (lo - pi) / (1 - pi)
    norm_hi = (hi - pi) / (1 - pi)
    return f"{norm:.2f} ({norm_lo:.2f}, {norm_hi:.2f})"

# Per-year prevalence (π) used for normalization
prevalence = {yr: float(y_test_by_year[yr]['Outcome'].mean()) for yr in TEST_YEARS}
prevalence['All'] = float(y_test['Outcome'].mean())
print('Prevalence by year:', {k: f"{v:.3f}" for k, v in prevalence.items()})

# Add normalized AUPRC column
summary = results_df.copy()
summary['Normalized AUPRC'] = summary.apply(
    lambda row: normalize_auprc(row['Average Precision'], prevalence[row['Year']]),
    axis=1
)

# Numeric point estimates for plotting / delta tables
for col in ['Average Precision', 'AUROC', 'Normalized AUPRC']:
    summary[col + '_pt'] = summary[col].apply(extract_point)

# Pivot: rows = DAG, columns = Year
for metric_col, label in [
    ('Average Precision_pt', 'Average Precision (raw)'),
    ('Normalized AUPRC_pt',  'Normalized AUPRC (skill score)'),
    ('AUROC_pt',             'AUROC'),
]:
    pivot = summary.pivot_table(index='DAG', columns='Year', values=metric_col)
    pivot.columns = [str(c) for c in pivot.columns]
    col_order = ['All'] + [str(yr) for yr in TEST_YEARS]
    pivot = pivot[[c for c in col_order if c in pivot.columns]]
    print(f'\n=== {label} ===')
    display(pivot.round(3))

Prevalence by year: {2020: '0.140', 2021: '0.104', 2022: '0.090', 'All': '0.111'}

=== Average Precision (raw) ===

                                                     All  2020  2021  2022
DAG
Control                                             0.81  0.81  0.82  0.84
Correlation                                         0.75  0.75  0.77  0.77
Simplified Clinician Consensus                      0.78  0.80  0.78  0.81
Simplified Clinician Consensus $\cap$ Simplifie...  0.74  0.78  0.73  0.74
Simplified Clinician Consensus $\cap$ Simplifie...  0.79  0.80  0.79  0.81
Simplified Clinician Consensus $\cup$ Simplifie...  0.79  0.81  0.79  0.82
Simplified Clinician Consensus $\cup$ Simplifie...  0.77  0.77  0.81  0.80
Simplified Golem                                    0.77  0.78  0.79  0.80
Simplified Golem $\cap$ Simplified PCMB             0.76  0.78  0.77  0.78
Simplified Golem $\cup$ Simplified PCMB             0.78  0.80  0.79  0.81
Simplified PCMB                                     0.78  0.79  0.79  0.82

=== Normalized AUPRC (skill score) ===

                                                     All  2020  2021  2022
DAG
Control                                             0.79  0.78  0.80  0.82
Correlation                                         0.72  0.71  0.74  0.75
Simplified Clinician Consensus                      0.75  0.77  0.75  0.79
Simplified Clinician Consensus $\cap$ Simplifie...  0.71  0.74  0.70  0.71
Simplified Clinician Consensus $\cap$ Simplifie...  0.76  0.77  0.77  0.79
Simplified Clinician Consensus $\cup$ Simplifie...  0.76  0.78  0.77  0.80
Simplified Clinician Consensus $\cup$ Simplifie...  0.74  0.73  0.79  0.78
Simplified Golem                                    0.74  0.74  0.77  0.78
Simplified Golem $\cap$ Simplified PCMB             0.73  0.74  0.74  0.76
Simplified Golem $\cup$ Simplified PCMB             0.75  0.77  0.77  0.79
Simplified PCMB                                     0.75  0.76  0.77  0.80

=== AUROC ===

                                                     All  2020  2021  2022
DAG
Control                                             0.93  0.93  0.95  0.93
Correlation                                         0.90  0.89  0.91  0.89
Simplified Clinician Consensus                      0.91  0.91  0.92  0.91
Simplified Clinician Consensus $\cap$ Simplifie...  0.89  0.90  0.89  0.88
Simplified Clinician Consensus $\cap$ Simplifie...  0.91  0.91  0.92  0.92
Simplified Clinician Consensus $\cup$ Simplifie...  0.91  0.92  0.91  0.92
Simplified Clinician Consensus $\cup$ Simplifie...  0.91  0.90  0.93  0.91
Simplified Golem                                    0.91  0.91  0.93  0.92
Simplified Golem $\cap$ Simplified PCMB             0.90  0.91  0.91  0.91
Simplified Golem $\cup$ Simplified PCMB             0.91  0.92  0.91  0.92
Simplified PCMB                                     0.91  0.91  0.91  0.92

In [10]:
cols_to_save = ['DAG', 'Year', 'Average Precision', 'Normalized AUPRC', 'AUROC',
                'Precision', 'Recall', 'F1 Score', 'Accuracy', 'ECE',
                '# Features', '# Biomarkers']
summary[cols_to_save].to_csv('biomarker_counts_fixed/Year Sensitivity - Normalized.csv', index=False)

## Plot: AUROC and AUPRC by Year
Line plot across years for each DAG and model type, making any temporal drift immediately visible.

In [11]:
plt.rcParams.update({
    'figure.figsize': (14, 5),
    'figure.dpi': 150,
    'font.size': 11,
    'lines.linewidth': 1.5,
    'figure.constrained_layout.use': True,
    'pdf.fonttype': 42,
})

year_only = summary[summary['Year'].isin(TEST_YEARS)].copy()
year_only['Year'] = year_only['Year'].astype(int)

metrics_to_plot = [
    ('AUROC_pt',             'AUROC'),
    ('Average Precision_pt', 'Average Precision (raw)'),
    ('Normalized AUPRC_pt',  'Normalized AUPRC (skill score)'),
]

fig, axes = plt.subplots(1, 3)
fig.suptitle('XGB – Performance by Test-Set Year')

for ax, (metric, ylabel) in zip(axes, metrics_to_plot):
    for dag_name, grp in year_only.groupby('DAG'):
        grp_sorted = grp.sort_values('Year')
        ax.plot(grp_sorted['Year'], grp_sorted[metric], marker='o', label=dag_name, alpha=0.7)
    ax.set_xlabel('Year')
    ax.set_ylabel(ylabel)
    ax.set_xticks(TEST_YEARS)
    ax.grid(True, alpha=0.3)

handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, loc='lower center', ncol=4,
           bbox_to_anchor=(0.5, -0.3), fontsize=8, frameon=False)

plt.savefig('biomarker_counts_fixed/Year Sensitivity - XGB.pdf', bbox_inches='tight', dpi=300)
plt.show()
plt.rcParams.update(plt.rcParamsDefault)

/var/folders/17/ccxjtf7x73b7_wzzqdvhv3h80000gq/T/ipykernel_58532/3808486603.py:36: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Year-over-year delta table
Shows how much AUROC and Average Precision shift from 2020 → 2021 and 2021 → 2022 for each DAG × Model.

In [12]:
for metric_col, label in [
    ('AUROC_pt',             'AUROC'),
    ('Average Precision_pt', 'Average Precision (raw)'),
    ('Normalized AUPRC_pt',  'Normalized AUPRC (skill score)'),
]:
    pivot = summary.pivot_table(index='DAG', columns='Year', values=metric_col)
    pivot.columns = [str(c) for c in pivot.columns]
    delta = pd.DataFrame(index=pivot.index)
    delta['2020→2021'] = pivot['2021'] - pivot['2020']
    delta['2021→2022'] = pivot['2022'] - pivot['2021']
    delta['2020→2022'] = pivot['2022'] - pivot['2020']
    print(f'\n=== {label} – year-over-year delta ===')
    display(delta.round(3))

=== AUROC – year-over-year delta ===

,2020→2021,2021→2022,2020→2022
DAG,,,
Control,0.02,-0.02,0.00
Correlation,0.02,-0.02,0.00
Simplified Clinician Consensus,0.01,-0.01,0.00
Simplified Clinician Consensus $\cap$ Simplified Golem,-0.01,-0.01,-0.02
Simplified Clinician Consensus $\cap$ Simplified PCMB,0.01,0.00,0.01
Simplified Clinician Consensus $\cup$ Simplified Golem,-0.01,0.01,0.00
Simplified Clinician Consensus $\cup$ Simplified PCMB,0.03,-0.02,0.01
Simplified Golem,0.02,-0.01,0.01
Simplified Golem $\cap$ Simplified PCMB,0.00,0.00,0.00
Simplified Golem $\cup$ Simplified PCMB,-0.01,0.01,0.00
Simplified PCMB,0.00,0.01,0.01

=== Average Precision (raw) – year-over-year delta ===

,2020→2021,2021→2022,2020→2022
DAG,,,
Control,0.01,0.02,0.03
Correlation,0.02,0.00,0.02
Simplified Clinician Consensus,-0.02,0.03,0.01
Simplified Clinician Consensus $\cap$ Simplified Golem,-0.05,0.01,-0.04
Simplified Clinician Consensus $\cap$ Simplified PCMB,-0.01,0.02,0.01
Simplified Clinician Consensus $\cup$ Simplified Golem,-0.02,0.03,0.01
Simplified Clinician Consensus $\cup$ Simplified PCMB,0.04,-0.01,0.03
Simplified Golem,0.01,0.01,0.02
Simplified Golem $\cap$ Simplified PCMB,-0.01,0.01,0.00
Simplified Golem $\cup$ Simplified PCMB,-0.01,0.02,0.01
Simplified PCMB,0.00,0.03,0.03

=== Normalized AUPRC (skill score) – year-over-year delta ===

,2020→2021,2021→2022,2020→2022
DAG,,,
Control,0.02,0.02,0.04
Correlation,0.03,0.01,0.04
Simplified Clinician Consensus,-0.02,0.04,0.02
Simplified Clinician Consensus $\cap$ Simplified Golem,-0.04,0.01,-0.03
Simplified Clinician Consensus $\cap$ Simplified PCMB,0.00,0.02,0.02
Simplified Clinician Consensus $\cup$ Simplified Golem,-0.01,0.03,0.02
Simplified Clinician Consensus $\cup$ Simplified PCMB,0.06,-0.01,0.05
Simplified Golem,0.03,0.01,0.04
Simplified Golem $\cap$ Simplified PCMB,0.00,0.02,0.02
Simplified Golem $\cup$ Simplified PCMB,0.00,0.02,0.02
Simplified PCMB,0.01,0.03,0.04

## Permutation test: pairwise year comparisons
Tests whether the same model performs significantly differently across years.

**Design:** pool predictions from years A and B, randomly shuffle year labels (preserving group sizes), recompute the metric difference, repeat 1000 times. The p-value is the fraction of permuted differences with |Δ| ≥ |observed Δ| (two-tailed).

Note: raw AUPRC and AUROC are used inside the permutation loop (not normalized AUPRC), because permuting year labels changes the within-permutation prevalence, making normalization ill-defined. Normalized AUPRC values from the table above provide the prevalence-adjusted magnitudes.

In [13]:
from sklearn.metrics import average_precision_score, roc_auc_score
from itertools import combinations

def permutation_test_across_years(y_true_A, y_prob_A, y_true_B, y_prob_B,
                                   metric_str='average_precision',
                                   n_permutations=1000, random_state=42):
    """
    Two-tailed permutation test comparing the same model on two year subsets.

    H0: the metric does not differ between year A and year B.
    Permutes year labels (pooling A+B) to build the null distribution of |Δ metric|.
    """
    metric_fn = {'average_precision': average_precision_score,
                 'roc_auc': roc_auc_score}[metric_str]

    obs_A = metric_fn(y_true_A, y_prob_A)
    obs_B = metric_fn(y_true_B, y_prob_B)
    obs_diff = abs(obs_A - obs_B)

    y_true_pool = np.concatenate([y_true_A, y_true_B])
    y_prob_pool = np.concatenate([y_prob_A, y_prob_B])
    n_A = len(y_true_A)

    rng = np.random.default_rng(random_state)
    null_diffs = []
    for _ in range(n_permutations):
        idx = rng.permutation(len(y_true_pool))
        try:
            diff = abs(
                metric_fn(y_true_pool[idx[:n_A]], y_prob_pool[idx[:n_A]])
                - metric_fn(y_true_pool[idx[n_A:]], y_prob_pool[idx[n_A:]])
            )
        except Exception:
            diff = 0.0
        null_diffs.append(diff)

    p_value = float(np.mean(np.array(null_diffs) >= obs_diff))
    return obs_A, obs_B, obs_diff, p_value


# Run pairwise tests for each DAG and metric
year_pairs = list(combinations(TEST_YEARS, 2))
perm_rows = []

for dag_name, year_preds in preds_by_dag.items():
    for yr_A, yr_B in year_pairs:
        y_true_A, y_prob_A = year_preds[yr_A]
        y_true_B, y_prob_B = year_preds[yr_B]

        for metric_str, metric_label in [('average_precision', 'AUPRC'),
                                          ('roc_auc',           'AUROC')]:
            obs_A, obs_B, obs_diff, p_value = permutation_test_across_years(
                y_true_A, y_prob_A, y_true_B, y_prob_B,
                metric_str=metric_str, n_permutations=1000, random_state=42,
            )
            perm_rows.append({
                'DAG':        dag_name,
                'Metric':     metric_label,
                'Year A':     yr_A,
                'Year B':     yr_B,
                f'{metric_label} (A)': round(obs_A, 3),
                f'{metric_label} (B)': round(obs_B, 3),
                '|Δ|':        round(obs_diff, 3),
                'p-value':    round(p_value, 3),
                'Significant (p<0.05)': p_value < 0.05,
            })

perm_df = pd.DataFrame(perm_rows)
perm_df.to_csv('biomarker_counts_fixed/Year Sensitivity - Permutation Tests.csv', index=False)
perm_df

,DAG,Metric,Year A,Year B,AUPRC (A),AUPRC (B),|Δ|,p-value,Significant (p<0.05),AUROC (A),AUROC (B)
0,Control,AUPRC,2020,2021,0.814,0.822,0.008,0.827,False,NaN,NaN
1,Control,AUROC,2020,2021,NaN,NaN,0.021,0.224,False,0.926,0.947
2,Control,AUPRC,2020,2022,0.814,0.835,0.021,0.592,False,NaN,NaN
3,Control,AUROC,2020,2022,NaN,NaN,0.007,0.721,False,0.926,0.932
4,Control,AUPRC,2021,2022,0.822,0.835,0.013,0.721,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
61,Simplified Clinician Consensus $\cap$ Simplifi...,AUROC,2020,2021,NaN,NaN,0.004,0.855,False,0.896,0.892
62,Simplified Clinician Consensus $\cap$ Simplifi...,AUPRC,2020,2022,0.783,0.743,0.041,0.370,False,NaN,NaN
63,Simplified Clinician Consensus $\cap$ Simplifi...,AUROC,2020,2022,NaN,NaN,0.012,0.659,False,0.896,0.884
64,Simplified Clinician Consensus $\cap$ Simplifi...,AUPRC,2021,2022,0.726,0.743,0.017,0.718,False,NaN,NaN
65,Simplified Clinician Consensus $\cap$ Simplifi...,AUROC,2021,2022,NaN,NaN,0.008,0.765,False,0.892,0.884

In [14]:
# Summary: which year pairs show significant differences, and for which DAGs?
print("=== Significant year differences (p < 0.05) ===\n")
for metric_label in ['AUPRC', 'AUROC']:
    sub = perm_df[perm_df['Metric'] == metric_label]
    sig = sub[sub['Significant (p<0.05)']]
    print(f"{metric_label}: {len(sig)} / {len(sub)} comparisons significant")
    if len(sig):
        display(sig[['DAG', 'Year A', 'Year B', '|Δ|', 'p-value']].reset_index(drop=True))
    print()

=== Significant year differences (p < 0.05) ===

AUPRC: 0 / 33 comparisons significant

AUROC: 0 / 33 comparisons significant

## Permutation test on AUCNPR (prevalence-normalized)
Repeats the pairwise year comparison on **AUCNPR** instead of raw AUPRC. Unlike the raw test, each year subset is normalized by its **own** prevalence anchor ($\pi$) before the difference is taken, so this is a genuinely distinct test rather than a monotone relabelling — the observed $|\Delta|$ and the permutation null both differ from the raw-AUPRC version.

This addresses the concern that the apparent year-over-year rise in raw AUPRC is largely a prevalence artifact (prevalence falls 14.0% → 10.4% → 9.0% across 2020–2022). Saved to `Year Sensitivity - Permutation AUCNPR.csv`.

In [15]:
# AUCNPR (prevalence-normalized AUPRC) permutation test.
# Each year subset keeps its OWN prevalence anchor throughout the permutation, so the
# null asks whether prevalence-adjusted discrimination differs between years.
#   AUCNPR   = (AUPRC - AUPR_min) / (1 - AUPR_min)
#   AUPR_min = 1 + (1 - pi) * ln(1 - pi) / pi          (Boyd, Eng & Page, ECML PKDD 2012)

def aucpr_min(pi):
    """Worst-case (minimum achievable) AUPRC at prevalence pi (Boyd et al. 2012)."""
    return 1 + (1 - pi) * np.log(1 - pi) / pi


def permutation_test_aucnpr_across_years(y_true_A, y_prob_A, pi_A,
                                         y_true_B, y_prob_B, pi_B,
                                         n_permutations=1000, random_state=42):
    """
    Two-tailed permutation test on AUCNPR comparing the same model on two year subsets.

    H0: prevalence-adjusted discrimination (AUCNPR) does not differ between year A and B.
    Each side is normalized by its original-year prevalence (pi_A, pi_B); year labels are
    then pooled and shuffled to build the null distribution of |Delta AUCNPR|.
    """
    min_A, min_B = aucpr_min(pi_A), aucpr_min(pi_B)
    npr_A = lambda yt, yp: (average_precision_score(yt, yp) - min_A) / (1 - min_A)
    npr_B = lambda yt, yp: (average_precision_score(yt, yp) - min_B) / (1 - min_B)

    obs_A, obs_B = npr_A(y_true_A, y_prob_A), npr_B(y_true_B, y_prob_B)
    obs_diff = abs(obs_A - obs_B)

    y_true_pool = np.concatenate([y_true_A, y_true_B])
    y_prob_pool = np.concatenate([y_prob_A, y_prob_B])
    n_A = len(y_true_A)

    rng = np.random.default_rng(random_state)
    null_diffs = []
    for _ in range(n_permutations):
        idx = rng.permutation(len(y_true_pool))
        try:
            diff = abs(
                npr_A(y_true_pool[idx[:n_A]], y_prob_pool[idx[:n_A]])
                - npr_B(y_true_pool[idx[n_A:]], y_prob_pool[idx[n_A:]])
            )
        except Exception:
            diff = 0.0
        null_diffs.append(diff)

    p_value = float(np.mean(np.array(null_diffs) >= obs_diff))
    return obs_A, obs_B, obs_diff, p_value


# Run AUCNPR pairwise tests for each DAG (reuses year_pairs from the raw-AUPRC test above)
perm_npr_rows = []
for dag_name, year_preds in preds_by_dag.items():
    for yr_A, yr_B in year_pairs:
        y_true_A, y_prob_A = year_preds[yr_A]
        y_true_B, y_prob_B = year_preds[yr_B]

        obs_A, obs_B, obs_diff, p_value = permutation_test_aucnpr_across_years(
            y_true_A, y_prob_A, prevalence[yr_A],
            y_true_B, y_prob_B, prevalence[yr_B],
            n_permutations=1000, random_state=42,
        )
        perm_npr_rows.append({
            'DAG':        dag_name,
            'Metric':     'AUCNPR',
            'Year A':     yr_A,
            'Year B':     yr_B,
            'AUCNPR (A)': round(obs_A, 3),
            'AUCNPR (B)': round(obs_B, 3),
            '|Δ|':        round(obs_diff, 3),
            'p-value':    round(p_value, 3),
            'Significant (p<0.05)': p_value < 0.05,
        })

perm_npr_df = pd.DataFrame(perm_npr_rows)
perm_npr_df.to_csv('biomarker_counts_fixed/Year Sensitivity - Permutation AUCNPR.csv', index=False)

n_sig = int(perm_npr_df['Significant (p<0.05)'].sum())
print(f"AUCNPR: {n_sig} / {len(perm_npr_df)} comparisons significant (p < 0.05)")
perm_npr_df

AUCNPR: 0 / 33 comparisons significant (p < 0.05)

,DAG,Metric,Year A,Year B,AUCNPR (A),AUCNPR (B),|Δ|,p-value,Significant (p<0.05)
0,Control,AUCNPR,2020,2021,0.800,0.812,0.013,0.756,False
1,Control,AUCNPR,2020,2022,0.800,0.827,0.028,0.501,False
2,Control,AUCNPR,2021,2022,0.812,0.827,0.015,0.697,False
3,Correlation,AUCNPR,2020,2021,0.733,0.753,0.020,0.675,False
4,Correlation,AUCNPR,2020,2022,0.733,0.754,0.021,0.684,False
5,Correlation,AUCNPR,2021,2022,0.753,0.754,0.001,0.985,False
6,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2020,2021,0.751,0.795,0.045,0.334,False
7,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2020,2022,0.751,0.789,0.038,0.433,False
8,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2021,2022,0.795,0.789,0.006,0.861,False
9,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2020,2021,0.795,0.778,0.017,0.688,False
10,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2020,2022,0.795,0.813,0.018,0.670,False
11,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2021,2022,0.778,0.813,0.035,0.428,False
12,Simplified Golem $\cup$ Simplified PCMB,AUCNPR,2020,2021,0.783,0.775,0.008,0.868,False
13,Simplified Golem $\cup$ Simplified PCMB,AUCNPR,2020,2022,0.783,0.798,0.015,0.735,False
14,Simplified Golem $\cup$ Simplified PCMB,AUCNPR,2021,2022,0.775,0.798,0.023,0.610,False
15,Simplified Clinician Consensus,AUCNPR,2020,2021,0.784,0.768,0.016,0.742,False
16,Simplified Clinician Consensus,AUCNPR,2020,2022,0.784,0.804,0.020,0.658,False
17,Simplified Clinician Consensus,AUCNPR,2021,2022,0.768,0.804,0.036,0.434,False
18,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2020,2021,0.789,0.775,0.014,0.756,False
19,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2020,2022,0.789,0.806,0.017,0.685,False
20,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2021,2022,0.775,0.806,0.031,0.476,False
21,Simplified PCMB,AUCNPR,2020,2021,0.774,0.780,0.006,0.911,False
22,Simplified PCMB,AUCNPR,2020,2022,0.774,0.810,0.036,0.412,False
23,Simplified PCMB,AUCNPR,2021,2022,0.780,0.810,0.030,0.471,False
24,Simplified Golem,AUCNPR,2020,2021,0.762,0.775,0.013,0.765,False
25,Simplified Golem,AUCNPR,2020,2022,0.762,0.792,0.030,0.532,False
26,Simplified Golem,AUCNPR,2021,2022,0.775,0.792,0.017,0.697,False
27,Simplified Golem $\cap$ Simplified PCMB,AUCNPR,2020,2021,0.767,0.756,0.011,0.803,False
28,Simplified Golem $\cap$ Simplified PCMB,AUCNPR,2020,2022,0.767,0.768,0.001,0.983,False
29,Simplified Golem $\cap$ Simplified PCMB,AUCNPR,2021,2022,0.756,0.768,0.012,0.779,False
30,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2020,2021,0.766,0.710,0.056,0.241,False
31,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2020,2022,0.766,0.730,0.036,0.449,False
32,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2021,2022,0.710,0.730,0.020,0.683,False

# Experiment 2: Vitals & Labs Only (No Drugs or Interventions)
Re-runs the full year-sensitivity pipeline after removing all drug and intervention features, leaving only vitals and laboratory biomarkers (mirrors *Experiment 3: No Drugs or Interventions* in the main notebook). All helper functions, prevalence anchors ($\pi$), and year pairs defined above are reused.

**Note:** once drugs and interventions are removed, some simplified DAGs reduce to identical feature sets (e.g. SCC $\cup$ SPCMB $\equiv$ SPCMB at 131 features; SCC $\equiv$ SCC $\cap$ SPCMB at 93 features), so those rows carry identical metrics.

In [16]:
# Vitals & labs only: drop drug and intervention features
results_df_vl, preds_by_dag_vl = train_models_year_sensitivity(remove_drugs=True, remove_interventions=True)
results_df_vl.to_csv('biomarker_counts_fixed/Year Sensitivity - Vitals Labs.csv', index=False)
results_df_vl

Processing Control (46 nodes, 45 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1328.99it/s]

Bootstrapping average_precision:  27%|██▋       | 266/1000 [00:00<00:00, 1321.26it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1328.65it/s]

Bootstrapping average_precision:  53%|█████▎    | 533/1000 [00:00<00:00, 1324.44it/s]

Bootstrapping average_precision:  67%|██████▋   | 667/1000 [00:00<00:00, 1329.14it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 1339.13it/s]

Bootstrapping average_precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1339.69it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1332.54it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 850.55it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 843.55it/s]

Bootstrapping roc_auc:  26%|██▌       | 257/1000 [00:00<00:00, 842.00it/s]

Bootstrapping roc_auc:  34%|███▍      | 342/1000 [00:00<00:00, 834.10it/s]

Bootstrapping roc_auc:  43%|████▎     | 426/1000 [00:00<00:00, 831.08it/s]

Bootstrapping roc_auc:  51%|█████     | 510/1000 [00:00<00:00, 831.12it/s]

Bootstrapping roc_auc:  60%|█████▉    | 596/1000 [00:00<00:00, 837.76it/s]

Bootstrapping roc_auc:  68%|██████▊   | 681/1000 [00:00<00:00, 839.47it/s]

Bootstrapping roc_auc:  76%|███████▋  | 765/1000 [00:00<00:00, 835.85it/s]

Bootstrapping roc_auc:  85%|████████▍ | 849/1000 [00:01<00:00, 836.72it/s]

Bootstrapping roc_auc:  94%|█████████▎| 935/1000 [00:01<00:00, 842.48it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 839.59it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1200.88it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1189.39it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1187.85it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1192.43it/s]

Bootstrapping precision:  60%|██████    | 601/1000 [00:00<00:00, 1179.56it/s]

Bootstrapping precision:  72%|███████▏  | 719/1000 [00:00<00:00, 1163.39it/s]

Bootstrapping precision:  84%|████████▎ | 836/1000 [00:00<00:00, 1163.18it/s]

Bootstrapping precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1162.16it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1170.65it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1198.24it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1193.32it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1193.97it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1188.96it/s]

Bootstrapping recall:  60%|██████    | 602/1000 [00:00<00:00, 1196.85it/s]

Bootstrapping recall:  72%|███████▏  | 722/1000 [00:00<00:00, 1190.45it/s]

Bootstrapping recall:  84%|████████▍ | 842/1000 [00:00<00:00, 1192.30it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1198.40it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1194.46it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1176.25it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1178.01it/s]

Bootstrapping f1:  36%|███▌      | 357/1000 [00:00<00:00, 1189.04it/s]

Bootstrapping f1:  48%|████▊     | 477/1000 [00:00<00:00, 1191.94it/s]

Bootstrapping f1:  60%|█████▉    | 597/1000 [00:00<00:00, 1191.59it/s]

Bootstrapping f1:  72%|███████▏  | 719/1000 [00:00<00:00, 1199.45it/s]

Bootstrapping f1:  84%|████████▍ | 840/1000 [00:00<00:00, 1200.99it/s]

Bootstrapping f1:  96%|█████████▌| 962/1000 [00:00<00:00, 1204.17it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1196.16it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3552.61it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3540.66it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3534.48it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 210/1000 [00:00<00:00, 2098.17it/s]

Bootstrapping average_precision:  42%|████▏     | 421/1000 [00:00<00:00, 2104.33it/s]

Bootstrapping average_precision:  63%|██████▎   | 633/1000 [00:00<00:00, 2109.06it/s]

Bootstrapping average_precision:  84%|████████▍ | 844/1000 [00:00<00:00, 2107.33it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2105.08it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 126/1000 [00:00<00:00, 1256.18it/s]

Bootstrapping roc_auc:  25%|██▌       | 252/1000 [00:00<00:00, 1253.42it/s]

Bootstrapping roc_auc:  38%|███▊      | 378/1000 [00:00<00:00, 1246.78it/s]

Bootstrapping roc_auc:  50%|█████     | 504/1000 [00:00<00:00, 1248.21it/s]

Bootstrapping roc_auc:  63%|██████▎   | 631/1000 [00:00<00:00, 1253.91it/s]

Bootstrapping roc_auc:  76%|███████▌  | 757/1000 [00:00<00:00, 1255.65it/s]

Bootstrapping roc_auc:  88%|████████▊ | 884/1000 [00:00<00:00, 1258.37it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1256.42it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 144/1000 [00:00<00:00, 1434.89it/s]

Bootstrapping precision:  29%|██▉       | 288/1000 [00:00<00:00, 1437.14it/s]

Bootstrapping precision:  43%|████▎     | 432/1000 [00:00<00:00, 1436.20it/s]

Bootstrapping precision:  58%|█████▊    | 576/1000 [00:00<00:00, 1431.05it/s]

Bootstrapping precision:  72%|███████▏  | 720/1000 [00:00<00:00, 1423.21it/s]

Bootstrapping precision:  86%|████████▋ | 865/1000 [00:00<00:00, 1430.49it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1432.42it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1425.82it/s]

Bootstrapping recall:  29%|██▊       | 286/1000 [00:00<00:00, 1424.99it/s]

Bootstrapping recall:  43%|████▎     | 431/1000 [00:00<00:00, 1433.79it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1427.97it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1425.62it/s]

Bootstrapping recall:  86%|████████▌ | 861/1000 [00:00<00:00, 1426.74it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1426.88it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1424.26it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1423.85it/s]

Bootstrapping f1:  43%|████▎     | 430/1000 [00:00<00:00, 1428.05it/s]

Bootstrapping f1:  57%|█████▋    | 573/1000 [00:00<00:00, 1422.07it/s]

Bootstrapping f1:  72%|███████▏  | 717/1000 [00:00<00:00, 1424.07it/s]

Bootstrapping f1:  86%|████████▌ | 862/1000 [00:00<00:00, 1431.45it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1426.42it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 417/1000 [00:00<00:00, 4161.88it/s]

Bootstrapping accuracy:  84%|████████▍ | 838/1000 [00:00<00:00, 4183.84it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4160.65it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 199/1000 [00:00<00:00, 1987.73it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 2025.96it/s]

Bootstrapping average_precision:  61%|██████    | 608/1000 [00:00<00:00, 2021.10it/s]

Bootstrapping average_precision:  81%|████████  | 811/1000 [00:00<00:00, 2012.22it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2005.04it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1202.13it/s]

Bootstrapping roc_auc:  24%|██▍       | 242/1000 [00:00<00:00, 1203.96it/s]

Bootstrapping roc_auc:  36%|███▋      | 363/1000 [00:00<00:00, 1195.95it/s]

Bootstrapping roc_auc:  48%|████▊     | 484/1000 [00:00<00:00, 1197.46it/s]

Bootstrapping roc_auc:  60%|██████    | 604/1000 [00:00<00:00, 1193.59it/s]

Bootstrapping roc_auc:  72%|███████▏  | 724/1000 [00:00<00:00, 1188.11it/s]

Bootstrapping roc_auc:  84%|████████▍ | 844/1000 [00:00<00:00, 1191.48it/s]

Bootstrapping roc_auc:  96%|█████████▋| 964/1000 [00:00<00:00, 1193.65it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1194.69it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 140/1000 [00:00<00:00, 1395.49it/s]

Bootstrapping precision:  28%|██▊       | 281/1000 [00:00<00:00, 1401.42it/s]

Bootstrapping precision:  42%|████▏     | 422/1000 [00:00<00:00, 1403.42it/s]

Bootstrapping precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1404.94it/s]

Bootstrapping precision:  70%|███████   | 705/1000 [00:00<00:00, 1408.01it/s]

Bootstrapping precision:  85%|████████▍ | 846/1000 [00:00<00:00, 1401.07it/s]

Bootstrapping precision:  99%|█████████▉| 988/1000 [00:00<00:00, 1404.88it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1402.32it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 141/1000 [00:00<00:00, 1403.59it/s]

Bootstrapping recall:  28%|██▊       | 282/1000 [00:00<00:00, 1397.73it/s]

Bootstrapping recall:  42%|████▏     | 424/1000 [00:00<00:00, 1404.83it/s]

Bootstrapping recall:  56%|█████▋    | 565/1000 [00:00<00:00, 1405.83it/s]

Bootstrapping recall:  71%|███████   | 707/1000 [00:00<00:00, 1408.66it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1413.14it/s]

Bootstrapping recall:  99%|█████████▉| 992/1000 [00:00<00:00, 1407.71it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1405.53it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 144/1000 [00:00<00:00, 1431.58it/s]

Bootstrapping f1:  29%|██▉       | 288/1000 [00:00<00:00, 1396.28it/s]

Bootstrapping f1:  43%|████▎     | 429/1000 [00:00<00:00, 1398.69it/s]

Bootstrapping f1:  57%|█████▋    | 570/1000 [00:00<00:00, 1401.51it/s]

Bootstrapping f1:  71%|███████   | 711/1000 [00:00<00:00, 1402.71it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1399.70it/s]

Bootstrapping f1:  99%|█████████▉| 992/1000 [00:00<00:00, 1394.15it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1396.75it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 413/1000 [00:00<00:00, 4124.76it/s]

Bootstrapping accuracy:  83%|████████▎ | 826/1000 [00:00<00:00, 4124.28it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4111.82it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 200/1000 [00:00<00:00, 1995.43it/s]

Bootstrapping average_precision:  40%|████      | 403/1000 [00:00<00:00, 2014.29it/s]

Bootstrapping average_precision:  60%|██████    | 605/1000 [00:00<00:00, 2005.79it/s]

Bootstrapping average_precision:  81%|████████  | 806/1000 [00:00<00:00, 2002.89it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2007.31it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 122/1000 [00:00<00:00, 1219.43it/s]

Bootstrapping roc_auc:  24%|██▍       | 244/1000 [00:00<00:00, 1214.06it/s]

Bootstrapping roc_auc:  37%|███▋      | 366/1000 [00:00<00:00, 1206.17it/s]

Bootstrapping roc_auc:  49%|████▊     | 487/1000 [00:00<00:00, 1195.10it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 1190.84it/s]

Bootstrapping roc_auc:  73%|███████▎  | 727/1000 [00:00<00:00, 1192.61it/s]

Bootstrapping roc_auc:  85%|████████▍ | 847/1000 [00:00<00:00, 1193.07it/s]

Bootstrapping roc_auc:  97%|█████████▋| 967/1000 [00:00<00:00, 1190.98it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1194.21it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▎        | 137/1000 [00:00<00:00, 1367.37it/s]

Bootstrapping precision:  28%|██▊       | 278/1000 [00:00<00:00, 1391.64it/s]

Bootstrapping precision:  42%|████▏     | 419/1000 [00:00<00:00, 1397.37it/s]

Bootstrapping precision:  56%|█████▌    | 562/1000 [00:00<00:00, 1408.12it/s]

Bootstrapping precision:  71%|███████   | 706/1000 [00:00<00:00, 1417.40it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1410.95it/s]

Bootstrapping precision:  99%|█████████▉| 990/1000 [00:00<00:00, 1404.52it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1402.64it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 140/1000 [00:00<00:00, 1390.65it/s]

Bootstrapping recall:  28%|██▊       | 281/1000 [00:00<00:00, 1399.72it/s]

Bootstrapping recall:  42%|████▏     | 423/1000 [00:00<00:00, 1408.20it/s]

Bootstrapping recall:  56%|█████▋    | 564/1000 [00:00<00:00, 1405.82it/s]

Bootstrapping recall:  70%|███████   | 705/1000 [00:00<00:00, 1406.95it/s]

Bootstrapping recall:  85%|████████▍ | 847/1000 [00:00<00:00, 1408.62it/s]

Bootstrapping recall:  99%|█████████▉| 990/1000 [00:00<00:00, 1413.61it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1407.34it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 141/1000 [00:00<00:00, 1406.39it/s]

Bootstrapping f1:  28%|██▊       | 282/1000 [00:00<00:00, 1405.22it/s]

Bootstrapping f1:  42%|████▏     | 424/1000 [00:00<00:00, 1408.64it/s]

Bootstrapping f1:  57%|█████▋    | 566/1000 [00:00<00:00, 1412.07it/s]

Bootstrapping f1:  71%|███████   | 708/1000 [00:00<00:00, 1412.79it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1409.04it/s]

Bootstrapping f1:  99%|█████████▉| 991/1000 [00:00<00:00, 1407.56it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1407.61it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 412/1000 [00:00<00:00, 4113.01it/s]

Bootstrapping accuracy:  83%|████████▎ | 826/1000 [00:00<00:00, 4126.16it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4124.36it/s]

Processing Correlation (38 nodes, 37 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1353.84it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1361.05it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1364.02it/s]

Bootstrapping average_precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1357.38it/s]

Bootstrapping average_precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1339.40it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1336.66it/s]

Bootstrapping average_precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1334.08it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1342.26it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 866.60it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 860.55it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 853.66it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 857.82it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 857.13it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 857.50it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 859.62it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 859.66it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 860.14it/s]

Bootstrapping roc_auc:  87%|████████▋ | 867/1000 [00:01<00:00, 860.93it/s]

Bootstrapping roc_auc:  95%|█████████▌| 954/1000 [00:01<00:00, 859.32it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 859.12it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1213.77it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1205.75it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1207.81it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1199.25it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1202.23it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1201.45it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1204.55it/s]

Bootstrapping precision:  97%|█████████▋| 974/1000 [00:00<00:00, 1209.14it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1205.16it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1221.31it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1219.28it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1219.87it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1222.53it/s]

Bootstrapping recall:  62%|██████▏   | 615/1000 [00:00<00:00, 1219.90it/s]

Bootstrapping recall:  74%|███████▎  | 737/1000 [00:00<00:00, 1215.95it/s]

Bootstrapping recall:  86%|████████▌ | 859/1000 [00:00<00:00, 1210.20it/s]

Bootstrapping recall:  98%|█████████▊| 981/1000 [00:00<00:00, 1207.42it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1212.85it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1213.93it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1198.35it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1180.32it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1171.35it/s]

Bootstrapping f1:  60%|██████    | 601/1000 [00:00<00:00, 1170.56it/s]

Bootstrapping f1:  72%|███████▏  | 719/1000 [00:00<00:00, 1172.13it/s]

Bootstrapping f1:  84%|████████▍ | 838/1000 [00:00<00:00, 1177.30it/s]

Bootstrapping f1:  96%|█████████▌| 959/1000 [00:00<00:00, 1186.37it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1180.82it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 360/1000 [00:00<00:00, 3590.81it/s]

Bootstrapping accuracy:  72%|███████▏  | 720/1000 [00:00<00:00, 3573.51it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3564.17it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 205/1000 [00:00<00:00, 2043.59it/s]

Bootstrapping average_precision:  42%|████▏     | 418/1000 [00:00<00:00, 2090.67it/s]

Bootstrapping average_precision:  63%|██████▎   | 629/1000 [00:00<00:00, 2096.57it/s]

Bootstrapping average_precision:  84%|████████▍ | 840/1000 [00:00<00:00, 2098.35it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2094.21it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 127/1000 [00:00<00:00, 1267.62it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 1257.93it/s]

Bootstrapping roc_auc:  38%|███▊      | 381/1000 [00:00<00:00, 1261.25it/s]

Bootstrapping roc_auc:  51%|█████     | 509/1000 [00:00<00:00, 1267.21it/s]

Bootstrapping roc_auc:  64%|██████▎   | 636/1000 [00:00<00:00, 1265.57it/s]

Bootstrapping roc_auc:  76%|███████▋  | 763/1000 [00:00<00:00, 1266.67it/s]

Bootstrapping roc_auc:  89%|████████▉ | 890/1000 [00:00<00:00, 1265.21it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1266.01it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1421.75it/s]

Bootstrapping precision:  29%|██▊       | 287/1000 [00:00<00:00, 1427.84it/s]

Bootstrapping precision:  43%|████▎     | 432/1000 [00:00<00:00, 1437.80it/s]

Bootstrapping precision:  58%|█████▊    | 577/1000 [00:00<00:00, 1440.20it/s]

Bootstrapping precision:  72%|███████▏  | 722/1000 [00:00<00:00, 1440.14it/s]

Bootstrapping precision:  87%|████████▋ | 867/1000 [00:00<00:00, 1438.98it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1438.26it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 141/1000 [00:00<00:00, 1407.26it/s]

Bootstrapping recall:  28%|██▊       | 284/1000 [00:00<00:00, 1417.14it/s]

Bootstrapping recall:  43%|████▎     | 430/1000 [00:00<00:00, 1434.60it/s]

Bootstrapping recall:  57%|█████▋    | 574/1000 [00:00<00:00, 1433.59it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1434.11it/s]

Bootstrapping recall:  86%|████████▋ | 863/1000 [00:00<00:00, 1437.52it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1430.97it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 144/1000 [00:00<00:00, 1437.76it/s]

Bootstrapping f1:  29%|██▉       | 288/1000 [00:00<00:00, 1430.31it/s]

Bootstrapping f1:  43%|████▎     | 432/1000 [00:00<00:00, 1429.66it/s]

Bootstrapping f1:  58%|█████▊    | 576/1000 [00:00<00:00, 1429.33it/s]

Bootstrapping f1:  72%|███████▏  | 719/1000 [00:00<00:00, 1429.18it/s]

Bootstrapping f1:  86%|████████▋ | 863/1000 [00:00<00:00, 1432.40it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1432.68it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 419/1000 [00:00<00:00, 4181.76it/s]

Bootstrapping accuracy:  84%|████████▍ | 838/1000 [00:00<00:00, 4161.82it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4168.63it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 201/1000 [00:00<00:00, 2007.77it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 2016.70it/s]

Bootstrapping average_precision:  61%|██████    | 607/1000 [00:00<00:00, 2021.46it/s]

Bootstrapping average_precision:  81%|████████  | 811/1000 [00:00<00:00, 2027.90it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2011.34it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1222.93it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1204.91it/s]

Bootstrapping roc_auc:  37%|███▋      | 368/1000 [00:00<00:00, 1211.67it/s]

Bootstrapping roc_auc:  49%|████▉     | 490/1000 [00:00<00:00, 1206.77it/s]

Bootstrapping roc_auc:  61%|██████    | 611/1000 [00:00<00:00, 1206.19it/s]

Bootstrapping roc_auc:  73%|███████▎  | 733/1000 [00:00<00:00, 1207.98it/s]

Bootstrapping roc_auc:  85%|████████▌ | 854/1000 [00:00<00:00, 1207.58it/s]

Bootstrapping roc_auc:  98%|█████████▊| 976/1000 [00:00<00:00, 1211.50it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1208.74it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 142/1000 [00:00<00:00, 1411.64it/s]

Bootstrapping precision:  28%|██▊       | 284/1000 [00:00<00:00, 1367.86it/s]

Bootstrapping precision:  42%|████▏     | 424/1000 [00:00<00:00, 1382.17it/s]

Bootstrapping precision:  57%|█████▋    | 567/1000 [00:00<00:00, 1398.08it/s]

Bootstrapping precision:  71%|███████   | 709/1000 [00:00<00:00, 1404.97it/s]

Bootstrapping precision:  85%|████████▌ | 850/1000 [00:00<00:00, 1406.48it/s]

Bootstrapping precision:  99%|█████████▉| 992/1000 [00:00<00:00, 1408.74it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1399.67it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1419.43it/s]

Bootstrapping recall:  28%|██▊       | 285/1000 [00:00<00:00, 1421.10it/s]

Bootstrapping recall:  43%|████▎     | 429/1000 [00:00<00:00, 1427.16it/s]

Bootstrapping recall:  57%|█████▋    | 572/1000 [00:00<00:00, 1424.53it/s]

Bootstrapping recall:  72%|███████▏  | 715/1000 [00:00<00:00, 1413.30it/s]

Bootstrapping recall:  86%|████████▌ | 858/1000 [00:00<00:00, 1416.33it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1419.53it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 142/1000 [00:00<00:00, 1412.29it/s]

Bootstrapping f1:  28%|██▊       | 285/1000 [00:00<00:00, 1419.63it/s]

Bootstrapping f1:  43%|████▎     | 429/1000 [00:00<00:00, 1426.11it/s]

Bootstrapping f1:  57%|█████▋    | 572/1000 [00:00<00:00, 1425.32it/s]

Bootstrapping f1:  72%|███████▏  | 715/1000 [00:00<00:00, 1422.88it/s]

Bootstrapping f1:  86%|████████▌ | 858/1000 [00:00<00:00, 1419.90it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1421.64it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 417/1000 [00:00<00:00, 4166.22it/s]

Bootstrapping accuracy:  84%|████████▎ | 837/1000 [00:00<00:00, 4180.03it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4158.21it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 203/1000 [00:00<00:00, 2022.84it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 2027.05it/s]

Bootstrapping average_precision:  61%|██████    | 610/1000 [00:00<00:00, 2027.71it/s]

Bootstrapping average_precision:  81%|████████▏ | 813/1000 [00:00<00:00, 2026.76it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2025.69it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1222.09it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1214.43it/s]

Bootstrapping roc_auc:  37%|███▋      | 368/1000 [00:00<00:00, 1214.99it/s]

Bootstrapping roc_auc:  49%|████▉     | 490/1000 [00:00<00:00, 1213.31it/s]

Bootstrapping roc_auc:  61%|██████▏   | 613/1000 [00:00<00:00, 1216.43it/s]

Bootstrapping roc_auc:  74%|███████▎  | 736/1000 [00:00<00:00, 1218.99it/s]

Bootstrapping roc_auc:  86%|████████▌ | 859/1000 [00:00<00:00, 1220.82it/s]

Bootstrapping roc_auc:  98%|█████████▊| 982/1000 [00:00<00:00, 1218.73it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1216.64it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1423.81it/s]

Bootstrapping precision:  29%|██▊       | 287/1000 [00:00<00:00, 1427.10it/s]

Bootstrapping precision:  43%|████▎     | 431/1000 [00:00<00:00, 1429.72it/s]

Bootstrapping precision:  57%|█████▊    | 575/1000 [00:00<00:00, 1432.07it/s]

Bootstrapping precision:  72%|███████▏  | 719/1000 [00:00<00:00, 1420.22it/s]

Bootstrapping precision:  86%|████████▌ | 862/1000 [00:00<00:00, 1423.39it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1424.89it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1421.61it/s]

Bootstrapping recall:  29%|██▊       | 286/1000 [00:00<00:00, 1417.47it/s]

Bootstrapping recall:  43%|████▎     | 429/1000 [00:00<00:00, 1418.51it/s]

Bootstrapping recall:  57%|█████▋    | 571/1000 [00:00<00:00, 1409.03it/s]

Bootstrapping recall:  71%|███████▏  | 713/1000 [00:00<00:00, 1411.52it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1405.07it/s]

Bootstrapping recall: 100%|█████████▉| 997/1000 [00:00<00:00, 1408.57it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1409.15it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1422.93it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1421.73it/s]

Bootstrapping f1:  43%|████▎     | 429/1000 [00:00<00:00, 1423.86it/s]

Bootstrapping f1:  57%|█████▋    | 573/1000 [00:00<00:00, 1429.63it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1426.84it/s]

Bootstrapping f1:  86%|████████▌ | 859/1000 [00:00<00:00, 1405.60it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1397.16it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1409.67it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 413/1000 [00:00<00:00, 4123.28it/s]

Bootstrapping accuracy:  83%|████████▎ | 827/1000 [00:00<00:00, 4129.40it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4124.09it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB (20 nodes, 53 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1362.44it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1357.10it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1353.18it/s]

Bootstrapping average_precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1356.01it/s]

Bootstrapping average_precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1354.48it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1357.31it/s]

Bootstrapping average_precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1356.06it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1355.30it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 854.37it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 858.42it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 858.95it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 856.48it/s]

Bootstrapping roc_auc:  43%|████▎     | 432/1000 [00:00<00:00, 853.74it/s]

Bootstrapping roc_auc:  52%|█████▏    | 518/1000 [00:00<00:00, 848.73it/s]

Bootstrapping roc_auc:  60%|██████    | 603/1000 [00:00<00:00, 845.53it/s]

Bootstrapping roc_auc:  69%|██████▉   | 688/1000 [00:00<00:00, 843.41it/s]

Bootstrapping roc_auc:  77%|███████▋  | 773/1000 [00:00<00:00, 842.07it/s]

Bootstrapping roc_auc:  86%|████████▌ | 858/1000 [00:01<00:00, 841.67it/s]

Bootstrapping roc_auc:  94%|█████████▍| 943/1000 [00:01<00:00, 841.54it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 845.17it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1149.83it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1135.55it/s]

Bootstrapping precision:  35%|███▍      | 346/1000 [00:00<00:00, 1144.91it/s]

Bootstrapping precision:  47%|████▋     | 466/1000 [00:00<00:00, 1165.74it/s]

Bootstrapping precision:  58%|█████▊    | 585/1000 [00:00<00:00, 1172.58it/s]

Bootstrapping precision:  71%|███████   | 706/1000 [00:00<00:00, 1182.61it/s]

Bootstrapping precision:  82%|████████▎ | 825/1000 [00:00<00:00, 1181.43it/s]

Bootstrapping precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1187.68it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1174.82it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1198.17it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1190.17it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1191.63it/s]

Bootstrapping recall:  48%|████▊     | 481/1000 [00:00<00:00, 1198.73it/s]

Bootstrapping recall:  60%|██████    | 602/1000 [00:00<00:00, 1199.77it/s]

Bootstrapping recall:  72%|███████▎  | 725/1000 [00:00<00:00, 1206.90it/s]

Bootstrapping recall:  85%|████████▍ | 846/1000 [00:00<00:00, 1206.99it/s]

Bootstrapping recall:  97%|█████████▋| 967/1000 [00:00<00:00, 1205.09it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1201.51it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1211.63it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1208.17it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1212.80it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1212.66it/s]

Bootstrapping f1:  61%|██████    | 610/1000 [00:00<00:00, 1208.78it/s]

Bootstrapping f1:  73%|███████▎  | 731/1000 [00:00<00:00, 1206.02it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1206.10it/s]

Bootstrapping f1:  97%|█████████▋| 974/1000 [00:00<00:00, 1209.58it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1208.11it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3537.50it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3535.25it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3526.02it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 209/1000 [00:00<00:00, 2083.56it/s]

Bootstrapping average_precision:  42%|████▏     | 419/1000 [00:00<00:00, 2090.59it/s]

Bootstrapping average_precision:  63%|██████▎   | 631/1000 [00:00<00:00, 2100.77it/s]

Bootstrapping average_precision:  84%|████████▍ | 843/1000 [00:00<00:00, 2108.27it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2099.64it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 127/1000 [00:00<00:00, 1268.04it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 1261.86it/s]

Bootstrapping roc_auc:  38%|███▊      | 381/1000 [00:00<00:00, 1256.54it/s]

Bootstrapping roc_auc:  51%|█████     | 507/1000 [00:00<00:00, 1254.05it/s]

Bootstrapping roc_auc:  63%|██████▎   | 634/1000 [00:00<00:00, 1259.07it/s]

Bootstrapping roc_auc:  76%|███████▌  | 761/1000 [00:00<00:00, 1261.99it/s]

Bootstrapping roc_auc:  89%|████████▉ | 888/1000 [00:00<00:00, 1257.21it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1256.46it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 144/1000 [00:00<00:00, 1435.61it/s]

Bootstrapping precision:  29%|██▉       | 288/1000 [00:00<00:00, 1433.61it/s]

Bootstrapping precision:  43%|████▎     | 433/1000 [00:00<00:00, 1438.63it/s]

Bootstrapping precision:  58%|█████▊    | 578/1000 [00:00<00:00, 1441.06it/s]

Bootstrapping precision:  72%|███████▏  | 723/1000 [00:00<00:00, 1439.77it/s]

Bootstrapping precision:  87%|████████▋ | 868/1000 [00:00<00:00, 1440.16it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1438.86it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1417.51it/s]

Bootstrapping recall:  29%|██▊       | 286/1000 [00:00<00:00, 1429.64it/s]

Bootstrapping recall:  43%|████▎     | 429/1000 [00:00<00:00, 1418.56it/s]

Bootstrapping recall:  57%|█████▋    | 574/1000 [00:00<00:00, 1427.11it/s]

Bootstrapping recall:  72%|███████▏  | 717/1000 [00:00<00:00, 1428.07it/s]

Bootstrapping recall:  86%|████████▌ | 860/1000 [00:00<00:00, 1428.56it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1428.44it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 145/1000 [00:00<00:00, 1444.56it/s]

Bootstrapping f1:  29%|██▉       | 290/1000 [00:00<00:00, 1432.31it/s]

Bootstrapping f1:  43%|████▎     | 434/1000 [00:00<00:00, 1433.45it/s]

Bootstrapping f1:  58%|█████▊    | 578/1000 [00:00<00:00, 1424.16it/s]

Bootstrapping f1:  72%|███████▏  | 721/1000 [00:00<00:00, 1424.80it/s]

Bootstrapping f1:  86%|████████▋ | 865/1000 [00:00<00:00, 1429.45it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1429.12it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 418/1000 [00:00<00:00, 4175.44it/s]

Bootstrapping accuracy:  84%|████████▎ | 836/1000 [00:00<00:00, 4171.69it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4166.49it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 200/1000 [00:00<00:00, 1997.68it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 2003.09it/s]

Bootstrapping average_precision:  60%|██████    | 604/1000 [00:00<00:00, 2013.39it/s]

Bootstrapping average_precision:  81%|████████  | 806/1000 [00:00<00:00, 2010.04it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2010.42it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1221.16it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1217.70it/s]

Bootstrapping roc_auc:  37%|███▋      | 368/1000 [00:00<00:00, 1212.48it/s]

Bootstrapping roc_auc:  49%|████▉     | 490/1000 [00:00<00:00, 1215.16it/s]

Bootstrapping roc_auc:  61%|██████▏   | 614/1000 [00:00<00:00, 1221.86it/s]

Bootstrapping roc_auc:  74%|███████▎  | 737/1000 [00:00<00:00, 1215.81it/s]

Bootstrapping roc_auc:  86%|████████▌ | 859/1000 [00:00<00:00, 1216.13it/s]

Bootstrapping roc_auc:  98%|█████████▊| 981/1000 [00:00<00:00, 1215.62it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1215.12it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1403.40it/s]

Bootstrapping precision:  28%|██▊       | 283/1000 [00:00<00:00, 1409.29it/s]

Bootstrapping precision:  43%|████▎     | 426/1000 [00:00<00:00, 1418.66it/s]

Bootstrapping precision:  57%|█████▋    | 569/1000 [00:00<00:00, 1419.94it/s]

Bootstrapping precision:  71%|███████   | 711/1000 [00:00<00:00, 1411.58it/s]

Bootstrapping precision:  85%|████████▌ | 853/1000 [00:00<00:00, 1413.15it/s]

Bootstrapping precision: 100%|█████████▉| 996/1000 [00:00<00:00, 1416.79it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1413.21it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1411.17it/s]

Bootstrapping recall:  28%|██▊       | 284/1000 [00:00<00:00, 1412.06it/s]

Bootstrapping recall:  43%|████▎     | 426/1000 [00:00<00:00, 1414.85it/s]

Bootstrapping recall:  57%|█████▋    | 568/1000 [00:00<00:00, 1413.98it/s]

Bootstrapping recall:  71%|███████   | 711/1000 [00:00<00:00, 1417.21it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1420.17it/s]

Bootstrapping recall: 100%|█████████▉| 997/1000 [00:00<00:00, 1416.92it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1414.57it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1420.47it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1410.27it/s]

Bootstrapping f1:  43%|████▎     | 428/1000 [00:00<00:00, 1410.30it/s]

Bootstrapping f1:  57%|█████▋    | 570/1000 [00:00<00:00, 1414.06it/s]

Bootstrapping f1:  71%|███████   | 712/1000 [00:00<00:00, 1412.28it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1414.72it/s]

Bootstrapping f1: 100%|█████████▉| 997/1000 [00:00<00:00, 1412.73it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1411.47it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 415/1000 [00:00<00:00, 4147.07it/s]

Bootstrapping accuracy:  83%|████████▎ | 832/1000 [00:00<00:00, 4160.32it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4144.68it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 202/1000 [00:00<00:00, 2013.78it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 2016.38it/s]

Bootstrapping average_precision:  61%|██████    | 607/1000 [00:00<00:00, 2019.17it/s]

Bootstrapping average_precision:  81%|████████  | 809/1000 [00:00<00:00, 2006.90it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2011.16it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1204.55it/s]

Bootstrapping roc_auc:  24%|██▍       | 242/1000 [00:00<00:00, 1179.33it/s]

Bootstrapping roc_auc:  36%|███▌      | 362/1000 [00:00<00:00, 1186.15it/s]

Bootstrapping roc_auc:  48%|████▊     | 483/1000 [00:00<00:00, 1193.87it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 1202.25it/s]

Bootstrapping roc_auc:  73%|███████▎  | 726/1000 [00:00<00:00, 1203.46it/s]

Bootstrapping roc_auc:  85%|████████▍ | 848/1000 [00:00<00:00, 1207.42it/s]

Bootstrapping roc_auc:  97%|█████████▋| 969/1000 [00:00<00:00, 1198.01it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1197.45it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 139/1000 [00:00<00:00, 1381.17it/s]

Bootstrapping precision:  28%|██▊       | 281/1000 [00:00<00:00, 1401.50it/s]

Bootstrapping precision:  42%|████▏     | 422/1000 [00:00<00:00, 1388.10it/s]

Bootstrapping precision:  56%|█████▋    | 565/1000 [00:00<00:00, 1402.98it/s]

Bootstrapping precision:  71%|███████   | 706/1000 [00:00<00:00, 1405.16it/s]

Bootstrapping precision:  85%|████████▍ | 847/1000 [00:00<00:00, 1392.98it/s]

Bootstrapping precision:  99%|█████████▉| 988/1000 [00:00<00:00, 1395.70it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1394.64it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 141/1000 [00:00<00:00, 1406.05it/s]

Bootstrapping recall:  28%|██▊       | 282/1000 [00:00<00:00, 1374.90it/s]

Bootstrapping recall:  42%|████▏     | 423/1000 [00:00<00:00, 1388.31it/s]

Bootstrapping recall:  56%|█████▌    | 562/1000 [00:00<00:00, 1373.17it/s]

Bootstrapping recall:  70%|███████   | 701/1000 [00:00<00:00, 1378.61it/s]

Bootstrapping recall:  84%|████████▍ | 840/1000 [00:00<00:00, 1381.89it/s]

Bootstrapping recall:  98%|█████████▊| 979/1000 [00:00<00:00, 1381.17it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1377.14it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 141/1000 [00:00<00:00, 1400.41it/s]

Bootstrapping f1:  28%|██▊       | 282/1000 [00:00<00:00, 1400.33it/s]

Bootstrapping f1:  42%|████▏     | 423/1000 [00:00<00:00, 1397.03it/s]

Bootstrapping f1:  56%|█████▋    | 563/1000 [00:00<00:00, 1398.00it/s]

Bootstrapping f1:  70%|███████   | 703/1000 [00:00<00:00, 1367.77it/s]

Bootstrapping f1:  84%|████████▍ | 840/1000 [00:00<00:00, 1365.19it/s]

Bootstrapping f1:  98%|█████████▊| 979/1000 [00:00<00:00, 1371.01it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1377.20it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|████      | 405/1000 [00:00<00:00, 4042.03it/s]

Bootstrapping accuracy:  81%|████████  | 810/1000 [00:00<00:00, 4026.10it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4026.14it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem (24 nodes, 35 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1349.10it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1354.24it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1356.80it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1353.40it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1349.85it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1352.80it/s]

Bootstrapping average_precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1352.72it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1352.31it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 838.28it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 849.47it/s]

Bootstrapping roc_auc:  26%|██▌       | 257/1000 [00:00<00:00, 854.36it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 857.24it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 859.36it/s]

Bootstrapping roc_auc:  52%|█████▏    | 517/1000 [00:00<00:00, 854.90it/s]

Bootstrapping roc_auc:  60%|██████    | 604/1000 [00:00<00:00, 858.81it/s]

Bootstrapping roc_auc:  69%|██████▉   | 691/1000 [00:00<00:00, 860.57it/s]

Bootstrapping roc_auc:  78%|███████▊  | 778/1000 [00:00<00:00, 857.72it/s]

Bootstrapping roc_auc:  86%|████████▋ | 864/1000 [00:01<00:00, 858.05it/s]

Bootstrapping roc_auc:  95%|█████████▌| 950/1000 [00:01<00:00, 858.62it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 857.35it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1199.15it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1202.92it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1207.23it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1210.52it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1205.11it/s]

Bootstrapping precision:  73%|███████▎  | 728/1000 [00:00<00:00, 1202.14it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1208.58it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1205.68it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1204.49it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1220.34it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1212.47it/s]

Bootstrapping recall:  37%|███▋      | 368/1000 [00:00<00:00, 1201.62it/s]

Bootstrapping recall:  49%|████▉     | 489/1000 [00:00<00:00, 1199.85it/s]

Bootstrapping recall:  61%|██████    | 611/1000 [00:00<00:00, 1205.87it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1200.92it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1207.05it/s]

Bootstrapping recall:  98%|█████████▊| 976/1000 [00:00<00:00, 1203.49it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1203.60it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1199.95it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1199.40it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1205.80it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1193.38it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1200.79it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1203.27it/s]

Bootstrapping f1:  85%|████████▍ | 847/1000 [00:00<00:00, 1201.65it/s]

Bootstrapping f1:  97%|█████████▋| 968/1000 [00:00<00:00, 1201.84it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1200.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3528.59it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3521.70it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3515.17it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 211/1000 [00:00<00:00, 2104.32it/s]

Bootstrapping average_precision:  42%|████▏     | 422/1000 [00:00<00:00, 2093.63it/s]

Bootstrapping average_precision:  63%|██████▎   | 632/1000 [00:00<00:00, 2085.93it/s]

Bootstrapping average_precision:  84%|████████▍ | 843/1000 [00:00<00:00, 2091.51it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2091.74it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 127/1000 [00:00<00:00, 1262.70it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 1258.57it/s]

Bootstrapping roc_auc:  38%|███▊      | 380/1000 [00:00<00:00, 1248.24it/s]

Bootstrapping roc_auc:  50%|█████     | 505/1000 [00:00<00:00, 1245.81it/s]

Bootstrapping roc_auc:  63%|██████▎   | 630/1000 [00:00<00:00, 1242.75it/s]

Bootstrapping roc_auc:  76%|███████▌  | 755/1000 [00:00<00:00, 1243.76it/s]

Bootstrapping roc_auc:  88%|████████▊ | 880/1000 [00:00<00:00, 1240.26it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1244.57it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1424.61it/s]

Bootstrapping precision:  29%|██▊       | 286/1000 [00:00<00:00, 1420.06it/s]

Bootstrapping precision:  43%|████▎     | 429/1000 [00:00<00:00, 1403.44it/s]

Bootstrapping precision:  57%|█████▋    | 570/1000 [00:00<00:00, 1403.83it/s]

Bootstrapping precision:  71%|███████   | 712/1000 [00:00<00:00, 1406.74it/s]

Bootstrapping precision:  85%|████████▌ | 854/1000 [00:00<00:00, 1410.94it/s]

Bootstrapping precision: 100%|█████████▉| 997/1000 [00:00<00:00, 1414.38it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1409.99it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 145/1000 [00:00<00:00, 1442.17it/s]

Bootstrapping recall:  29%|██▉       | 290/1000 [00:00<00:00, 1422.04it/s]

Bootstrapping recall:  43%|████▎     | 433/1000 [00:00<00:00, 1412.93it/s]

Bootstrapping recall:  58%|█████▊    | 576/1000 [00:00<00:00, 1418.66it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1407.06it/s]

Bootstrapping recall:  86%|████████▌ | 862/1000 [00:00<00:00, 1417.44it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1417.76it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1423.29it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1426.45it/s]

Bootstrapping f1:  43%|████▎     | 430/1000 [00:00<00:00, 1428.15it/s]

Bootstrapping f1:  57%|█████▋    | 573/1000 [00:00<00:00, 1409.62it/s]

Bootstrapping f1:  71%|███████▏  | 714/1000 [00:00<00:00, 1403.32it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1400.70it/s]

Bootstrapping f1: 100%|█████████▉| 996/1000 [00:00<00:00, 1401.26it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1405.81it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|███▉      | 398/1000 [00:00<00:00, 3975.15it/s]

Bootstrapping accuracy:  81%|████████  | 806/1000 [00:00<00:00, 4031.75it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4022.30it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 201/1000 [00:00<00:00, 2008.85it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 2003.07it/s]

Bootstrapping average_precision:  61%|██████    | 606/1000 [00:00<00:00, 2017.24it/s]

Bootstrapping average_precision:  81%|████████  | 808/1000 [00:00<00:00, 2017.96it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2017.50it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 120/1000 [00:00<00:00, 1196.69it/s]

Bootstrapping roc_auc:  24%|██▍       | 242/1000 [00:00<00:00, 1206.41it/s]

Bootstrapping roc_auc:  36%|███▋      | 363/1000 [00:00<00:00, 1203.25it/s]

Bootstrapping roc_auc:  48%|████▊     | 484/1000 [00:00<00:00, 1204.16it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 1207.48it/s]

Bootstrapping roc_auc:  73%|███████▎  | 728/1000 [00:00<00:00, 1209.43it/s]

Bootstrapping roc_auc:  85%|████████▌ | 850/1000 [00:00<00:00, 1210.28it/s]

Bootstrapping roc_auc:  97%|█████████▋| 973/1000 [00:00<00:00, 1214.83it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1208.91it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1401.60it/s]

Bootstrapping precision:  28%|██▊       | 283/1000 [00:00<00:00, 1408.88it/s]

Bootstrapping precision:  42%|████▏     | 424/1000 [00:00<00:00, 1399.65it/s]

Bootstrapping precision:  56%|█████▋    | 564/1000 [00:00<00:00, 1398.95it/s]

Bootstrapping precision:  70%|███████   | 704/1000 [00:00<00:00, 1392.15it/s]

Bootstrapping precision:  84%|████████▍ | 844/1000 [00:00<00:00, 1392.23it/s]

Bootstrapping precision:  98%|█████████▊| 985/1000 [00:00<00:00, 1396.60it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1395.82it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1414.41it/s]

Bootstrapping recall:  28%|██▊       | 285/1000 [00:00<00:00, 1422.52it/s]

Bootstrapping recall:  43%|████▎     | 428/1000 [00:00<00:00, 1417.54it/s]

Bootstrapping recall:  57%|█████▋    | 570/1000 [00:00<00:00, 1414.93it/s]

Bootstrapping recall:  71%|███████   | 712/1000 [00:00<00:00, 1415.56it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1415.42it/s]

Bootstrapping recall: 100%|█████████▉| 997/1000 [00:00<00:00, 1418.94it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1415.81it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 141/1000 [00:00<00:00, 1403.25it/s]

Bootstrapping f1:  28%|██▊       | 283/1000 [00:00<00:00, 1410.83it/s]

Bootstrapping f1:  42%|████▎     | 425/1000 [00:00<00:00, 1400.85it/s]

Bootstrapping f1:  57%|█████▋    | 566/1000 [00:00<00:00, 1400.65it/s]

Bootstrapping f1:  71%|███████   | 708/1000 [00:00<00:00, 1406.27it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1408.83it/s]

Bootstrapping f1:  99%|█████████▉| 992/1000 [00:00<00:00, 1412.35it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1406.21it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 411/1000 [00:00<00:00, 4102.08it/s]

Bootstrapping accuracy:  82%|████████▎ | 825/1000 [00:00<00:00, 4119.89it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4127.85it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 202/1000 [00:00<00:00, 2014.62it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 2013.17it/s]

Bootstrapping average_precision:  61%|██████    | 606/1000 [00:00<00:00, 2012.53it/s]

Bootstrapping average_precision:  81%|████████  | 808/1000 [00:00<00:00, 2010.97it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2016.38it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 122/1000 [00:00<00:00, 1215.79it/s]

Bootstrapping roc_auc:  24%|██▍       | 244/1000 [00:00<00:00, 1207.56it/s]

Bootstrapping roc_auc:  37%|███▋      | 366/1000 [00:00<00:00, 1209.68it/s]

Bootstrapping roc_auc:  49%|████▊     | 487/1000 [00:00<00:00, 1190.52it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 1167.82it/s]

Bootstrapping roc_auc:  73%|███████▎  | 728/1000 [00:00<00:00, 1179.35it/s]

Bootstrapping roc_auc:  85%|████████▍ | 847/1000 [00:00<00:00, 1177.16it/s]

Bootstrapping roc_auc:  96%|█████████▋| 965/1000 [00:00<00:00, 1175.35it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1182.31it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▎        | 136/1000 [00:00<00:00, 1350.87it/s]

Bootstrapping precision:  27%|██▋       | 273/1000 [00:00<00:00, 1359.83it/s]

Bootstrapping precision:  41%|████▏     | 414/1000 [00:00<00:00, 1378.99it/s]

Bootstrapping precision:  56%|█████▌    | 556/1000 [00:00<00:00, 1391.25it/s]

Bootstrapping precision:  70%|██████▉   | 696/1000 [00:00<00:00, 1387.06it/s]

Bootstrapping precision:  84%|████████▍ | 839/1000 [00:00<00:00, 1400.21it/s]

Bootstrapping precision:  98%|█████████▊| 982/1000 [00:00<00:00, 1408.12it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1392.65it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 140/1000 [00:00<00:00, 1398.53it/s]

Bootstrapping recall:  28%|██▊       | 282/1000 [00:00<00:00, 1410.79it/s]

Bootstrapping recall:  42%|████▎     | 425/1000 [00:00<00:00, 1415.72it/s]

Bootstrapping recall:  57%|█████▋    | 567/1000 [00:00<00:00, 1414.19it/s]

Bootstrapping recall:  71%|███████   | 709/1000 [00:00<00:00, 1404.79it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1402.67it/s]

Bootstrapping recall:  99%|█████████▉| 992/1000 [00:00<00:00, 1406.48it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1405.64it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 141/1000 [00:00<00:00, 1407.30it/s]

Bootstrapping f1:  28%|██▊       | 283/1000 [00:00<00:00, 1413.52it/s]

Bootstrapping f1:  42%|████▎     | 425/1000 [00:00<00:00, 1412.45it/s]

Bootstrapping f1:  57%|█████▋    | 567/1000 [00:00<00:00, 1412.71it/s]

Bootstrapping f1:  71%|███████   | 709/1000 [00:00<00:00, 1411.46it/s]

Bootstrapping f1:  85%|████████▌ | 851/1000 [00:00<00:00, 1409.97it/s]

Bootstrapping f1:  99%|█████████▉| 993/1000 [00:00<00:00, 1411.27it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1409.74it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 421/1000 [00:00<00:00, 4209.82it/s]

Bootstrapping accuracy:  84%|████████▍ | 842/1000 [00:00<00:00, 4197.97it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4184.04it/s]

Processing Simplified Golem $\cup$ Simplified PCMB (24 nodes, 64 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1357.14it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1360.39it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1359.51it/s]

Bootstrapping average_precision:  55%|█████▍    | 546/1000 [00:00<00:00, 1359.05it/s]

Bootstrapping average_precision:  68%|██████▊   | 682/1000 [00:00<00:00, 1353.29it/s]

Bootstrapping average_precision:  82%|████████▏ | 818/1000 [00:00<00:00, 1351.71it/s]

Bootstrapping average_precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1355.67it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1353.62it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 858.34it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 864.75it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 859.96it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 861.84it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 859.61it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 857.04it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 857.15it/s]

Bootstrapping roc_auc:  69%|██████▉   | 693/1000 [00:00<00:00, 858.23it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 860.72it/s]

Bootstrapping roc_auc:  87%|████████▋ | 867/1000 [00:01<00:00, 863.51it/s]

Bootstrapping roc_auc:  95%|█████████▌| 954/1000 [00:01<00:00, 862.82it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.57it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1185.07it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1198.40it/s]

Bootstrapping precision:  36%|███▌      | 362/1000 [00:00<00:00, 1205.88it/s]

Bootstrapping precision:  48%|████▊     | 483/1000 [00:00<00:00, 1203.71it/s]

Bootstrapping precision:  60%|██████    | 604/1000 [00:00<00:00, 1202.65it/s]

Bootstrapping precision:  73%|███████▎  | 726/1000 [00:00<00:00, 1205.84it/s]

Bootstrapping precision:  85%|████████▍ | 847/1000 [00:00<00:00, 1198.07it/s]

Bootstrapping precision:  97%|█████████▋| 969/1000 [00:00<00:00, 1202.53it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1201.24it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1204.62it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1204.00it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1203.25it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1208.00it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1207.83it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 1207.33it/s]

Bootstrapping recall:  85%|████████▍ | 848/1000 [00:00<00:00, 1203.62it/s]

Bootstrapping recall:  97%|█████████▋| 969/1000 [00:00<00:00, 1204.34it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1204.51it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1204.88it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1197.68it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1201.28it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1203.52it/s]

Bootstrapping f1:  61%|██████    | 606/1000 [00:00<00:00, 1206.04it/s]

Bootstrapping f1:  73%|███████▎  | 728/1000 [00:00<00:00, 1208.85it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1210.55it/s]

Bootstrapping f1:  97%|█████████▋| 972/1000 [00:00<00:00, 1203.53it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1203.85it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 348/1000 [00:00<00:00, 3475.03it/s]

Bootstrapping accuracy:  70%|███████   | 704/1000 [00:00<00:00, 3521.28it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3517.16it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 211/1000 [00:00<00:00, 2101.65it/s]

Bootstrapping average_precision:  42%|████▏     | 422/1000 [00:00<00:00, 2102.06it/s]

Bootstrapping average_precision:  63%|██████▎   | 634/1000 [00:00<00:00, 2108.72it/s]

Bootstrapping average_precision:  84%|████████▍ | 845/1000 [00:00<00:00, 2107.63it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2108.21it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 126/1000 [00:00<00:00, 1259.92it/s]

Bootstrapping roc_auc:  25%|██▌       | 252/1000 [00:00<00:00, 1258.82it/s]

Bootstrapping roc_auc:  38%|███▊      | 379/1000 [00:00<00:00, 1261.30it/s]

Bootstrapping roc_auc:  51%|█████     | 506/1000 [00:00<00:00, 1248.60it/s]

Bootstrapping roc_auc:  63%|██████▎   | 633/1000 [00:00<00:00, 1254.16it/s]

Bootstrapping roc_auc:  76%|███████▌  | 760/1000 [00:00<00:00, 1256.37it/s]

Bootstrapping roc_auc:  89%|████████▉ | 888/1000 [00:00<00:00, 1262.47it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1258.33it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 144/1000 [00:00<00:00, 1435.86it/s]

Bootstrapping precision:  29%|██▉       | 288/1000 [00:00<00:00, 1432.34it/s]

Bootstrapping precision:  43%|████▎     | 432/1000 [00:00<00:00, 1429.35it/s]

Bootstrapping precision:  58%|█████▊    | 576/1000 [00:00<00:00, 1432.41it/s]

Bootstrapping precision:  72%|███████▏  | 720/1000 [00:00<00:00, 1434.07it/s]

Bootstrapping precision:  86%|████████▋ | 864/1000 [00:00<00:00, 1433.73it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1432.33it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 144/1000 [00:00<00:00, 1433.14it/s]

Bootstrapping recall:  29%|██▉       | 289/1000 [00:00<00:00, 1437.89it/s]

Bootstrapping recall:  43%|████▎     | 433/1000 [00:00<00:00, 1423.86it/s]

Bootstrapping recall:  58%|█████▊    | 578/1000 [00:00<00:00, 1433.40it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1438.97it/s]

Bootstrapping recall:  87%|████████▋ | 867/1000 [00:00<00:00, 1438.10it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1434.62it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 145/1000 [00:00<00:00, 1448.06it/s]

Bootstrapping f1:  29%|██▉       | 290/1000 [00:00<00:00, 1439.77it/s]

Bootstrapping f1:  44%|████▎     | 435/1000 [00:00<00:00, 1441.63it/s]

Bootstrapping f1:  58%|█████▊    | 580/1000 [00:00<00:00, 1440.69it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1434.91it/s]

Bootstrapping f1:  87%|████████▋ | 869/1000 [00:00<00:00, 1434.53it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1437.20it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 417/1000 [00:00<00:00, 4168.21it/s]

Bootstrapping accuracy:  84%|████████▍ | 838/1000 [00:00<00:00, 4187.96it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4172.76it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 200/1000 [00:00<00:00, 1999.16it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1981.38it/s]

Bootstrapping average_precision:  60%|█████▉    | 599/1000 [00:00<00:00, 1973.73it/s]

Bootstrapping average_precision:  80%|████████  | 801/1000 [00:00<00:00, 1988.45it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1989.55it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1225.23it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1221.52it/s]

Bootstrapping roc_auc:  37%|███▋      | 369/1000 [00:00<00:00, 1222.29it/s]

Bootstrapping roc_auc:  49%|████▉     | 492/1000 [00:00<00:00, 1222.70it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 1219.25it/s]

Bootstrapping roc_auc:  74%|███████▎  | 737/1000 [00:00<00:00, 1212.65it/s]

Bootstrapping roc_auc:  86%|████████▌ | 860/1000 [00:00<00:00, 1215.98it/s]

Bootstrapping roc_auc:  98%|█████████▊| 982/1000 [00:00<00:00, 1211.27it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1213.86it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 139/1000 [00:00<00:00, 1387.53it/s]

Bootstrapping precision:  28%|██▊       | 279/1000 [00:00<00:00, 1390.50it/s]

Bootstrapping precision:  42%|████▏     | 419/1000 [00:00<00:00, 1386.51it/s]

Bootstrapping precision:  56%|█████▌    | 558/1000 [00:00<00:00, 1384.83it/s]

Bootstrapping precision:  70%|██████▉   | 697/1000 [00:00<00:00, 1385.86it/s]

Bootstrapping precision:  84%|████████▎ | 836/1000 [00:00<00:00, 1386.50it/s]

Bootstrapping precision:  98%|█████████▊| 975/1000 [00:00<00:00, 1382.55it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1381.94it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 139/1000 [00:00<00:00, 1386.01it/s]

Bootstrapping recall:  28%|██▊       | 278/1000 [00:00<00:00, 1361.93it/s]

Bootstrapping recall:  42%|████▏     | 415/1000 [00:00<00:00, 1360.28it/s]

Bootstrapping recall:  55%|█████▌    | 552/1000 [00:00<00:00, 1346.57it/s]

Bootstrapping recall:  69%|██████▉   | 691/1000 [00:00<00:00, 1359.53it/s]

Bootstrapping recall:  83%|████████▎ | 831/1000 [00:00<00:00, 1370.13it/s]

Bootstrapping recall:  97%|█████████▋| 969/1000 [00:00<00:00, 1367.33it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1363.91it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 139/1000 [00:00<00:00, 1386.75it/s]

Bootstrapping f1:  28%|██▊       | 278/1000 [00:00<00:00, 1380.46it/s]

Bootstrapping f1:  42%|████▏     | 417/1000 [00:00<00:00, 1361.68it/s]

Bootstrapping f1:  56%|█████▌    | 555/1000 [00:00<00:00, 1366.20it/s]

Bootstrapping f1:  70%|██████▉   | 696/1000 [00:00<00:00, 1380.32it/s]

Bootstrapping f1:  84%|████████▎ | 835/1000 [00:00<00:00, 1379.94it/s]

Bootstrapping f1:  98%|█████████▊| 976/1000 [00:00<00:00, 1389.54it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1380.35it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 414/1000 [00:00<00:00, 4135.53it/s]

Bootstrapping accuracy:  83%|████████▎ | 828/1000 [00:00<00:00, 4107.06it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4109.07it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 197/1000 [00:00<00:00, 1968.31it/s]

Bootstrapping average_precision:  40%|███▉      | 399/1000 [00:00<00:00, 1993.78it/s]

Bootstrapping average_precision:  60%|██████    | 601/1000 [00:00<00:00, 2003.43it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 2005.54it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1995.09it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 119/1000 [00:00<00:00, 1185.13it/s]

Bootstrapping roc_auc:  24%|██▍       | 239/1000 [00:00<00:00, 1192.24it/s]

Bootstrapping roc_auc:  36%|███▌      | 361/1000 [00:00<00:00, 1200.45it/s]

Bootstrapping roc_auc:  48%|████▊     | 482/1000 [00:00<00:00, 1191.84it/s]

Bootstrapping roc_auc:  60%|██████    | 604/1000 [00:00<00:00, 1199.64it/s]

Bootstrapping roc_auc:  72%|███████▏  | 724/1000 [00:00<00:00, 1198.74it/s]

Bootstrapping roc_auc:  84%|████████▍ | 845/1000 [00:00<00:00, 1199.36it/s]

Bootstrapping roc_auc:  96%|█████████▋| 965/1000 [00:00<00:00, 1197.85it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1196.51it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1401.62it/s]

Bootstrapping precision:  28%|██▊       | 282/1000 [00:00<00:00, 1396.93it/s]

Bootstrapping precision:  42%|████▏     | 423/1000 [00:00<00:00, 1397.59it/s]

Bootstrapping precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1396.47it/s]

Bootstrapping precision:  70%|███████   | 704/1000 [00:00<00:00, 1399.68it/s]

Bootstrapping precision:  85%|████████▍ | 846/1000 [00:00<00:00, 1405.67it/s]

Bootstrapping precision:  99%|█████████▉| 988/1000 [00:00<00:00, 1408.54it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1401.94it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1418.26it/s]

Bootstrapping recall:  28%|██▊       | 284/1000 [00:00<00:00, 1409.63it/s]

Bootstrapping recall:  43%|████▎     | 426/1000 [00:00<00:00, 1410.15it/s]

Bootstrapping recall:  57%|█████▋    | 568/1000 [00:00<00:00, 1404.67it/s]

Bootstrapping recall:  71%|███████   | 709/1000 [00:00<00:00, 1406.02it/s]

Bootstrapping recall:  85%|████████▌ | 850/1000 [00:00<00:00, 1401.55it/s]

Bootstrapping recall:  99%|█████████▉| 991/1000 [00:00<00:00, 1402.48it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1403.34it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 140/1000 [00:00<00:00, 1394.30it/s]

Bootstrapping f1:  28%|██▊       | 281/1000 [00:00<00:00, 1399.44it/s]

Bootstrapping f1:  42%|████▏     | 421/1000 [00:00<00:00, 1369.67it/s]

Bootstrapping f1:  56%|█████▌    | 562/1000 [00:00<00:00, 1383.96it/s]

Bootstrapping f1:  70%|███████   | 703/1000 [00:00<00:00, 1392.37it/s]

Bootstrapping f1:  84%|████████▍ | 845/1000 [00:00<00:00, 1398.78it/s]

Bootstrapping f1:  98%|█████████▊| 985/1000 [00:00<00:00, 1396.27it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1390.80it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 413/1000 [00:00<00:00, 4124.56it/s]

Bootstrapping accuracy:  83%|████████▎ | 827/1000 [00:00<00:00, 4128.39it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4113.31it/s]

Processing Simplified Clinician Consensus (17 nodes, 17 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1352.41it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1341.71it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1349.55it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1349.91it/s]

Bootstrapping average_precision:  68%|██████▊   | 680/1000 [00:00<00:00, 1351.00it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1352.53it/s]

Bootstrapping average_precision:  95%|█████████▌| 952/1000 [00:00<00:00, 1349.91it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1347.39it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 862.02it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 858.62it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 859.30it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 860.76it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 858.33it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 854.27it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 855.24it/s]

Bootstrapping roc_auc:  69%|██████▉   | 694/1000 [00:00<00:00, 858.73it/s]

Bootstrapping roc_auc:  78%|███████▊  | 780/1000 [00:00<00:00, 857.82it/s]

Bootstrapping roc_auc:  87%|████████▋ | 867/1000 [00:01<00:00, 860.18it/s]

Bootstrapping roc_auc:  95%|█████████▌| 954/1000 [00:01<00:00, 860.51it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 858.87it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1207.19it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1212.01it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1215.35it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1215.83it/s]

Bootstrapping precision:  61%|██████    | 609/1000 [00:00<00:00, 1208.58it/s]

Bootstrapping precision:  73%|███████▎  | 731/1000 [00:00<00:00, 1212.22it/s]

Bootstrapping precision:  85%|████████▌ | 853/1000 [00:00<00:00, 1207.75it/s]

Bootstrapping precision:  98%|█████████▊| 975/1000 [00:00<00:00, 1209.32it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1210.26it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1218.20it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1213.60it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1213.97it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1210.99it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1211.05it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1211.23it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1213.84it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1211.37it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1211.22it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1207.22it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1209.52it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1212.91it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1177.65it/s]

Bootstrapping f1:  61%|██████    | 608/1000 [00:00<00:00, 1187.37it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1197.68it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1202.59it/s]

Bootstrapping f1:  97%|█████████▋| 974/1000 [00:00<00:00, 1205.58it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1199.24it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3538.26it/s]

Bootstrapping accuracy:  71%|███████   | 709/1000 [00:00<00:00, 3538.44it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3549.03it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 209/1000 [00:00<00:00, 2085.26it/s]

Bootstrapping average_precision:  42%|████▏     | 420/1000 [00:00<00:00, 2096.90it/s]

Bootstrapping average_precision:  63%|██████▎   | 631/1000 [00:00<00:00, 2098.43it/s]

Bootstrapping average_precision:  84%|████████▍ | 843/1000 [00:00<00:00, 2106.51it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2101.99it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 127/1000 [00:00<00:00, 1264.59it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 1269.20it/s]

Bootstrapping roc_auc:  38%|███▊      | 382/1000 [00:00<00:00, 1263.57it/s]

Bootstrapping roc_auc:  51%|█████     | 509/1000 [00:00<00:00, 1253.61it/s]

Bootstrapping roc_auc:  64%|██████▎   | 636/1000 [00:00<00:00, 1258.13it/s]

Bootstrapping roc_auc:  76%|███████▋  | 764/1000 [00:00<00:00, 1263.06it/s]

Bootstrapping roc_auc:  89%|████████▉ | 891/1000 [00:00<00:00, 1264.78it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1262.12it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 144/1000 [00:00<00:00, 1430.36it/s]

Bootstrapping precision:  29%|██▉       | 288/1000 [00:00<00:00, 1429.61it/s]

Bootstrapping precision:  43%|████▎     | 431/1000 [00:00<00:00, 1428.88it/s]

Bootstrapping precision:  58%|█████▊    | 576/1000 [00:00<00:00, 1436.21it/s]

Bootstrapping precision:  72%|███████▏  | 720/1000 [00:00<00:00, 1422.69it/s]

Bootstrapping precision:  86%|████████▋ | 865/1000 [00:00<00:00, 1429.59it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1427.28it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  15%|█▍        | 146/1000 [00:00<00:00, 1455.27it/s]

Bootstrapping recall:  29%|██▉       | 292/1000 [00:00<00:00, 1441.96it/s]

Bootstrapping recall:  44%|████▎     | 437/1000 [00:00<00:00, 1436.70it/s]

Bootstrapping recall:  58%|█████▊    | 581/1000 [00:00<00:00, 1436.87it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1440.86it/s]

Bootstrapping recall:  87%|████████▋ | 871/1000 [00:00<00:00, 1438.69it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1441.36it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 144/1000 [00:00<00:00, 1430.72it/s]

Bootstrapping f1:  29%|██▉       | 288/1000 [00:00<00:00, 1435.24it/s]

Bootstrapping f1:  43%|████▎     | 433/1000 [00:00<00:00, 1439.50it/s]

Bootstrapping f1:  58%|█████▊    | 578/1000 [00:00<00:00, 1439.95it/s]

Bootstrapping f1:  72%|███████▏  | 722/1000 [00:00<00:00, 1437.67it/s]

Bootstrapping f1:  87%|████████▋ | 867/1000 [00:00<00:00, 1441.71it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1438.97it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 419/1000 [00:00<00:00, 4189.20it/s]

Bootstrapping accuracy:  84%|████████▍ | 839/1000 [00:00<00:00, 4193.06it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4180.55it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|█▉        | 199/1000 [00:00<00:00, 1987.59it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 2007.11it/s]

Bootstrapping average_precision:  60%|██████    | 605/1000 [00:00<00:00, 2013.83it/s]

Bootstrapping average_precision:  81%|████████  | 808/1000 [00:00<00:00, 2018.23it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2018.05it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1203.57it/s]

Bootstrapping roc_auc:  24%|██▍       | 242/1000 [00:00<00:00, 1206.83it/s]

Bootstrapping roc_auc:  36%|███▋      | 363/1000 [00:00<00:00, 1208.09it/s]

Bootstrapping roc_auc:  48%|████▊     | 484/1000 [00:00<00:00, 1204.58it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 1206.37it/s]

Bootstrapping roc_auc:  73%|███████▎  | 726/1000 [00:00<00:00, 1184.13it/s]

Bootstrapping roc_auc:  84%|████████▍ | 845/1000 [00:00<00:00, 1184.08it/s]

Bootstrapping roc_auc:  96%|█████████▋| 964/1000 [00:00<00:00, 1181.00it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1189.30it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 142/1000 [00:00<00:00, 1414.51it/s]

Bootstrapping precision:  28%|██▊       | 284/1000 [00:00<00:00, 1406.04it/s]

Bootstrapping precision:  42%|████▎     | 425/1000 [00:00<00:00, 1395.51it/s]

Bootstrapping precision:  57%|█████▋    | 566/1000 [00:00<00:00, 1400.66it/s]

Bootstrapping precision:  71%|███████   | 707/1000 [00:00<00:00, 1399.67it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1402.75it/s]

Bootstrapping precision:  99%|█████████▉| 989/1000 [00:00<00:00, 1403.79it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1401.09it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 141/1000 [00:00<00:00, 1400.92it/s]

Bootstrapping recall:  28%|██▊       | 283/1000 [00:00<00:00, 1408.45it/s]

Bootstrapping recall:  42%|████▎     | 425/1000 [00:00<00:00, 1412.73it/s]

Bootstrapping recall:  57%|█████▋    | 567/1000 [00:00<00:00, 1409.72it/s]

Bootstrapping recall:  71%|███████   | 709/1000 [00:00<00:00, 1412.25it/s]

Bootstrapping recall:  85%|████████▌ | 851/1000 [00:00<00:00, 1414.06it/s]

Bootstrapping recall:  99%|█████████▉| 993/1000 [00:00<00:00, 1414.35it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1410.60it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 142/1000 [00:00<00:00, 1412.37it/s]

Bootstrapping f1:  28%|██▊       | 284/1000 [00:00<00:00, 1412.68it/s]

Bootstrapping f1:  43%|████▎     | 427/1000 [00:00<00:00, 1417.15it/s]

Bootstrapping f1:  57%|█████▋    | 569/1000 [00:00<00:00, 1412.87it/s]

Bootstrapping f1:  71%|███████   | 712/1000 [00:00<00:00, 1414.95it/s]

Bootstrapping f1:  85%|████████▌ | 854/1000 [00:00<00:00, 1413.85it/s]

Bootstrapping f1: 100%|█████████▉| 997/1000 [00:00<00:00, 1416.55it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1413.74it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████      | 412/1000 [00:00<00:00, 4119.75it/s]

Bootstrapping accuracy:  83%|████████▎ | 828/1000 [00:00<00:00, 4142.06it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4143.77it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 202/1000 [00:00<00:00, 2018.64it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 2013.57it/s]

Bootstrapping average_precision:  61%|██████    | 607/1000 [00:00<00:00, 2020.11it/s]

Bootstrapping average_precision:  81%|████████  | 810/1000 [00:00<00:00, 2004.81it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2006.53it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 117/1000 [00:00<00:00, 1162.31it/s]

Bootstrapping roc_auc:  24%|██▍       | 238/1000 [00:00<00:00, 1184.90it/s]

Bootstrapping roc_auc:  36%|███▌      | 357/1000 [00:00<00:00, 1178.07it/s]

Bootstrapping roc_auc:  48%|████▊     | 478/1000 [00:00<00:00, 1189.21it/s]

Bootstrapping roc_auc:  60%|█████▉    | 599/1000 [00:00<00:00, 1193.52it/s]

Bootstrapping roc_auc:  72%|███████▏  | 721/1000 [00:00<00:00, 1202.29it/s]

Bootstrapping roc_auc:  84%|████████▍ | 842/1000 [00:00<00:00, 1201.69it/s]

Bootstrapping roc_auc:  96%|█████████▋| 964/1000 [00:00<00:00, 1206.28it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1196.68it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1401.19it/s]

Bootstrapping precision:  28%|██▊       | 282/1000 [00:00<00:00, 1395.62it/s]

Bootstrapping precision:  42%|████▏     | 424/1000 [00:00<00:00, 1401.19it/s]

Bootstrapping precision:  56%|█████▋    | 565/1000 [00:00<00:00, 1400.26it/s]

Bootstrapping precision:  71%|███████   | 706/1000 [00:00<00:00, 1391.82it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1401.32it/s]

Bootstrapping precision:  99%|█████████▉| 991/1000 [00:00<00:00, 1405.80it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1399.64it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1412.92it/s]

Bootstrapping recall:  28%|██▊       | 284/1000 [00:00<00:00, 1414.82it/s]

Bootstrapping recall:  43%|████▎     | 426/1000 [00:00<00:00, 1413.76it/s]

Bootstrapping recall:  57%|█████▋    | 568/1000 [00:00<00:00, 1415.72it/s]

Bootstrapping recall:  71%|███████   | 710/1000 [00:00<00:00, 1414.21it/s]

Bootstrapping recall:  85%|████████▌ | 852/1000 [00:00<00:00, 1414.33it/s]

Bootstrapping recall:  99%|█████████▉| 994/1000 [00:00<00:00, 1409.70it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1410.55it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 138/1000 [00:00<00:00, 1371.62it/s]

Bootstrapping f1:  28%|██▊       | 279/1000 [00:00<00:00, 1388.51it/s]

Bootstrapping f1:  42%|████▏     | 419/1000 [00:00<00:00, 1391.24it/s]

Bootstrapping f1:  56%|█████▌    | 559/1000 [00:00<00:00, 1392.93it/s]

Bootstrapping f1:  70%|██████▉   | 699/1000 [00:00<00:00, 1394.12it/s]

Bootstrapping f1:  84%|████████▍ | 840/1000 [00:00<00:00, 1396.40it/s]

Bootstrapping f1:  98%|█████████▊| 982/1000 [00:00<00:00, 1402.74it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1394.45it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|████      | 400/1000 [00:00<00:00, 3995.52it/s]

Bootstrapping accuracy:  81%|████████▏ | 813/1000 [00:00<00:00, 4074.49it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4054.79it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB (15 nodes, 14 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1282.75it/s]

Bootstrapping average_precision:  26%|██▌       | 259/1000 [00:00<00:00, 1291.95it/s]

Bootstrapping average_precision:  39%|███▉      | 393/1000 [00:00<00:00, 1312.88it/s]

Bootstrapping average_precision:  53%|█████▎    | 529/1000 [00:00<00:00, 1329.79it/s]

Bootstrapping average_precision:  66%|██████▋   | 664/1000 [00:00<00:00, 1336.31it/s]

Bootstrapping average_precision:  80%|████████  | 800/1000 [00:00<00:00, 1341.83it/s]

Bootstrapping average_precision:  94%|█████████▎| 936/1000 [00:00<00:00, 1345.06it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1333.69it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 860.59it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 860.16it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 859.87it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 862.97it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 860.02it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 860.96it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 861.03it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 858.89it/s]

Bootstrapping roc_auc:  78%|███████▊  | 782/1000 [00:00<00:00, 857.95it/s]

Bootstrapping roc_auc:  87%|████████▋ | 869/1000 [00:01<00:00, 859.50it/s]

Bootstrapping roc_auc:  96%|█████████▌| 956/1000 [00:01<00:00, 860.30it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.37it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1197.48it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1203.39it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1210.72it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1211.62it/s]

Bootstrapping precision:  61%|██████    | 607/1000 [00:00<00:00, 1212.48it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1214.40it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1213.12it/s]

Bootstrapping precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1209.60it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1209.44it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1206.97it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1206.40it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1208.88it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1211.07it/s]

Bootstrapping recall:  61%|██████    | 608/1000 [00:00<00:00, 1206.86it/s]

Bootstrapping recall:  73%|███████▎  | 730/1000 [00:00<00:00, 1210.94it/s]

Bootstrapping recall:  85%|████████▌ | 852/1000 [00:00<00:00, 1212.99it/s]

Bootstrapping recall:  97%|█████████▋| 974/1000 [00:00<00:00, 1215.03it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1211.01it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1205.83it/s]

Bootstrapping f1:  24%|██▍       | 243/1000 [00:00<00:00, 1209.71it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1198.31it/s]

Bootstrapping f1:  48%|████▊     | 485/1000 [00:00<00:00, 1201.47it/s]

Bootstrapping f1:  61%|██████    | 607/1000 [00:00<00:00, 1205.91it/s]

Bootstrapping f1:  73%|███████▎  | 728/1000 [00:00<00:00, 1205.63it/s]

Bootstrapping f1:  85%|████████▌ | 850/1000 [00:00<00:00, 1208.32it/s]

Bootstrapping f1:  97%|█████████▋| 971/1000 [00:00<00:00, 1207.58it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1204.36it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 352/1000 [00:00<00:00, 3512.06it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3524.62it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3523.94it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 204/1000 [00:00<00:00, 2034.43it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 2019.60it/s]

Bootstrapping average_precision:  61%|██████▏   | 614/1000 [00:00<00:00, 2033.94it/s]

Bootstrapping average_precision:  82%|████████▏ | 822/1000 [00:00<00:00, 2048.82it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2050.41it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 127/1000 [00:00<00:00, 1268.19it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 1248.23it/s]

Bootstrapping roc_auc:  38%|███▊      | 379/1000 [00:00<00:00, 1240.74it/s]

Bootstrapping roc_auc:  50%|█████     | 504/1000 [00:00<00:00, 1243.73it/s]

Bootstrapping roc_auc:  63%|██████▎   | 630/1000 [00:00<00:00, 1248.59it/s]

Bootstrapping roc_auc:  76%|███████▌  | 755/1000 [00:00<00:00, 1246.26it/s]

Bootstrapping roc_auc:  88%|████████▊ | 883/1000 [00:00<00:00, 1254.18it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1249.23it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1406.31it/s]

Bootstrapping precision:  28%|██▊       | 285/1000 [00:00<00:00, 1424.43it/s]

Bootstrapping precision:  43%|████▎     | 430/1000 [00:00<00:00, 1436.09it/s]

Bootstrapping precision:  57%|█████▋    | 574/1000 [00:00<00:00, 1429.83it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1424.26it/s]

Bootstrapping precision:  86%|████████▌ | 860/1000 [00:00<00:00, 1422.38it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1423.42it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1428.70it/s]

Bootstrapping recall:  29%|██▉       | 288/1000 [00:00<00:00, 1438.16it/s]

Bootstrapping recall:  43%|████▎     | 432/1000 [00:00<00:00, 1429.05it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1429.21it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1426.30it/s]

Bootstrapping recall:  86%|████████▌ | 861/1000 [00:00<00:00, 1423.12it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1425.15it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 138/1000 [00:00<00:00, 1379.32it/s]

Bootstrapping f1:  28%|██▊       | 277/1000 [00:00<00:00, 1383.30it/s]

Bootstrapping f1:  42%|████▏     | 416/1000 [00:00<00:00, 1386.13it/s]

Bootstrapping f1:  56%|█████▌    | 556/1000 [00:00<00:00, 1388.82it/s]

Bootstrapping f1:  70%|██████▉   | 698/1000 [00:00<00:00, 1396.63it/s]

Bootstrapping f1:  84%|████████▍ | 839/1000 [00:00<00:00, 1400.27it/s]

Bootstrapping f1:  98%|█████████▊| 980/1000 [00:00<00:00, 1365.70it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1377.16it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  40%|████      | 400/1000 [00:00<00:00, 3997.19it/s]

Bootstrapping accuracy:  81%|████████  | 807/1000 [00:00<00:00, 4039.66it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4036.77it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 202/1000 [00:00<00:00, 2016.41it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 2012.98it/s]

Bootstrapping average_precision:  61%|██████    | 606/1000 [00:00<00:00, 2008.75it/s]

Bootstrapping average_precision:  81%|████████  | 809/1000 [00:00<00:00, 2012.88it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2011.02it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1204.02it/s]

Bootstrapping roc_auc:  24%|██▍       | 242/1000 [00:00<00:00, 1206.64it/s]

Bootstrapping roc_auc:  36%|███▋      | 363/1000 [00:00<00:00, 1206.89it/s]

Bootstrapping roc_auc:  48%|████▊     | 485/1000 [00:00<00:00, 1208.14it/s]

Bootstrapping roc_auc:  61%|██████    | 607/1000 [00:00<00:00, 1210.88it/s]

Bootstrapping roc_auc:  73%|███████▎  | 730/1000 [00:00<00:00, 1216.59it/s]

Bootstrapping roc_auc:  85%|████████▌ | 852/1000 [00:00<00:00, 1215.48it/s]

Bootstrapping roc_auc:  97%|█████████▋| 974/1000 [00:00<00:00, 1212.82it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1210.46it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 141/1000 [00:00<00:00, 1405.11it/s]

Bootstrapping precision:  28%|██▊       | 282/1000 [00:00<00:00, 1405.03it/s]

Bootstrapping precision:  42%|████▎     | 425/1000 [00:00<00:00, 1412.03it/s]

Bootstrapping precision:  57%|█████▋    | 568/1000 [00:00<00:00, 1417.24it/s]

Bootstrapping precision:  71%|███████   | 711/1000 [00:00<00:00, 1418.48it/s]

Bootstrapping precision:  85%|████████▌ | 853/1000 [00:00<00:00, 1411.48it/s]

Bootstrapping precision: 100%|█████████▉| 995/1000 [00:00<00:00, 1410.33it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1410.06it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 140/1000 [00:00<00:00, 1394.03it/s]

Bootstrapping recall:  28%|██▊       | 281/1000 [00:00<00:00, 1399.83it/s]

Bootstrapping recall:  42%|████▏     | 423/1000 [00:00<00:00, 1409.01it/s]

Bootstrapping recall:  57%|█████▋    | 566/1000 [00:00<00:00, 1413.41it/s]

Bootstrapping recall:  71%|███████   | 709/1000 [00:00<00:00, 1418.15it/s]

Bootstrapping recall:  85%|████████▌ | 853/1000 [00:00<00:00, 1423.10it/s]

Bootstrapping recall: 100%|█████████▉| 996/1000 [00:00<00:00, 1424.50it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1416.21it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1424.79it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1414.91it/s]

Bootstrapping f1:  43%|████▎     | 430/1000 [00:00<00:00, 1423.50it/s]

Bootstrapping f1:  57%|█████▋    | 573/1000 [00:00<00:00, 1424.44it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1423.93it/s]

Bootstrapping f1:  86%|████████▌ | 859/1000 [00:00<00:00, 1425.27it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1423.26it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 414/1000 [00:00<00:00, 4135.32it/s]

Bootstrapping accuracy:  84%|████████▎ | 835/1000 [00:00<00:00, 4174.36it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4159.91it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 202/1000 [00:00<00:00, 2015.22it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 2026.59it/s]

Bootstrapping average_precision:  61%|██████    | 610/1000 [00:00<00:00, 2029.46it/s]

Bootstrapping average_precision:  81%|████████▏ | 813/1000 [00:00<00:00, 2026.97it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2027.31it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 122/1000 [00:00<00:00, 1217.33it/s]

Bootstrapping roc_auc:  24%|██▍       | 245/1000 [00:00<00:00, 1218.93it/s]

Bootstrapping roc_auc:  37%|███▋      | 367/1000 [00:00<00:00, 1207.42it/s]

Bootstrapping roc_auc:  49%|████▉     | 488/1000 [00:00<00:00, 1206.32it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 1210.84it/s]

Bootstrapping roc_auc:  73%|███████▎  | 733/1000 [00:00<00:00, 1214.94it/s]

Bootstrapping roc_auc:  86%|████████▌ | 855/1000 [00:00<00:00, 1215.40it/s]

Bootstrapping roc_auc:  98%|█████████▊| 978/1000 [00:00<00:00, 1218.44it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1213.87it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 142/1000 [00:00<00:00, 1417.44it/s]

Bootstrapping precision:  28%|██▊       | 285/1000 [00:00<00:00, 1421.93it/s]

Bootstrapping precision:  43%|████▎     | 429/1000 [00:00<00:00, 1428.76it/s]

Bootstrapping precision:  57%|█████▋    | 572/1000 [00:00<00:00, 1427.62it/s]

Bootstrapping precision:  72%|███████▏  | 716/1000 [00:00<00:00, 1429.74it/s]

Bootstrapping precision:  86%|████████▌ | 860/1000 [00:00<00:00, 1431.73it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1429.34it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1413.61it/s]

Bootstrapping recall:  28%|██▊       | 284/1000 [00:00<00:00, 1416.80it/s]

Bootstrapping recall:  43%|████▎     | 427/1000 [00:00<00:00, 1422.52it/s]

Bootstrapping recall:  57%|█████▋    | 570/1000 [00:00<00:00, 1424.67it/s]

Bootstrapping recall:  71%|███████▏  | 713/1000 [00:00<00:00, 1423.50it/s]

Bootstrapping recall:  86%|████████▌ | 856/1000 [00:00<00:00, 1422.64it/s]

Bootstrapping recall: 100%|█████████▉| 999/1000 [00:00<00:00, 1423.75it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1421.48it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 142/1000 [00:00<00:00, 1413.75it/s]

Bootstrapping f1:  28%|██▊       | 285/1000 [00:00<00:00, 1420.15it/s]

Bootstrapping f1:  43%|████▎     | 428/1000 [00:00<00:00, 1422.93it/s]

Bootstrapping f1:  57%|█████▋    | 571/1000 [00:00<00:00, 1424.23it/s]

Bootstrapping f1:  71%|███████▏  | 714/1000 [00:00<00:00, 1423.81it/s]

Bootstrapping f1:  86%|████████▌ | 857/1000 [00:00<00:00, 1424.22it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1420.84it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1421.11it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  41%|████▏     | 414/1000 [00:00<00:00, 4130.46it/s]

Bootstrapping accuracy:  83%|████████▎ | 833/1000 [00:00<00:00, 4162.44it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4153.74it/s]

Processing Simplified PCMB (18 nodes, 50 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1339.74it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1351.22it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1356.00it/s]

Bootstrapping average_precision:  54%|█████▍    | 544/1000 [00:00<00:00, 1358.59it/s]

Bootstrapping average_precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1361.37it/s]

Bootstrapping average_precision:  82%|████████▏ | 818/1000 [00:00<00:00, 1363.06it/s]

Bootstrapping average_precision:  96%|█████████▌| 955/1000 [00:00<00:00, 1359.28it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1357.56it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 863.46it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 865.95it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 865.05it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 866.50it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 861.46it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 863.01it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 866.12it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 867.32it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 866.28it/s]

Bootstrapping roc_auc:  87%|████████▋ | 871/1000 [00:01<00:00, 865.56it/s]

Bootstrapping roc_auc:  96%|█████████▌| 958/1000 [00:01<00:00, 866.36it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 865.01it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1219.87it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1219.67it/s]

Bootstrapping precision:  37%|███▋      | 368/1000 [00:00<00:00, 1225.65it/s]

Bootstrapping precision:  49%|████▉     | 491/1000 [00:00<00:00, 1224.45it/s]

Bootstrapping precision:  61%|██████▏   | 614/1000 [00:00<00:00, 1224.71it/s]

Bootstrapping precision:  74%|███████▎  | 737/1000 [00:00<00:00, 1225.01it/s]

Bootstrapping precision:  86%|████████▌ | 860/1000 [00:00<00:00, 1224.21it/s]

Bootstrapping precision:  98%|█████████▊| 983/1000 [00:00<00:00, 1209.39it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1217.34it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1222.47it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1215.55it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1219.71it/s]

Bootstrapping recall:  49%|████▉     | 493/1000 [00:00<00:00, 1224.02it/s]

Bootstrapping recall:  62%|██████▏   | 616/1000 [00:00<00:00, 1221.89it/s]

Bootstrapping recall:  74%|███████▍  | 739/1000 [00:00<00:00, 1219.39it/s]

Bootstrapping recall:  86%|████████▌ | 861/1000 [00:00<00:00, 1195.79it/s]

Bootstrapping recall:  98%|█████████▊| 983/1000 [00:00<00:00, 1201.74it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1209.13it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1219.57it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1217.44it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1216.54it/s]

Bootstrapping f1:  49%|████▉     | 489/1000 [00:00<00:00, 1218.80it/s]

Bootstrapping f1:  61%|██████    | 611/1000 [00:00<00:00, 1218.43it/s]

Bootstrapping f1:  73%|███████▎  | 733/1000 [00:00<00:00, 1217.57it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1212.96it/s]

Bootstrapping f1:  98%|█████████▊| 977/1000 [00:00<00:00, 1198.89it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1208.84it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3554.10it/s]

Bootstrapping accuracy:  71%|███████▏  | 714/1000 [00:00<00:00, 3564.52it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3556.16it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 212/1000 [00:00<00:00, 2112.77it/s]

Bootstrapping average_precision:  42%|████▎     | 425/1000 [00:00<00:00, 2118.50it/s]

Bootstrapping average_precision:  64%|██████▍   | 638/1000 [00:00<00:00, 2122.40it/s]

Bootstrapping average_precision:  85%|████████▌ | 851/1000 [00:00<00:00, 2108.61it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2102.35it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 122/1000 [00:00<00:00, 1213.06it/s]

Bootstrapping roc_auc:  24%|██▍       | 245/1000 [00:00<00:00, 1222.16it/s]

Bootstrapping roc_auc:  37%|███▋      | 368/1000 [00:00<00:00, 1220.62it/s]

Bootstrapping roc_auc:  49%|████▉     | 494/1000 [00:00<00:00, 1235.87it/s]

Bootstrapping roc_auc:  62%|██████▏   | 618/1000 [00:00<00:00, 1234.02it/s]

Bootstrapping roc_auc:  74%|███████▍  | 743/1000 [00:00<00:00, 1237.36it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:00<00:00, 1240.41it/s]

Bootstrapping roc_auc:  99%|█████████▉| 994/1000 [00:00<00:00, 1246.41it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1235.97it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 144/1000 [00:00<00:00, 1437.07it/s]

Bootstrapping precision:  29%|██▉       | 289/1000 [00:00<00:00, 1440.84it/s]

Bootstrapping precision:  43%|████▎     | 434/1000 [00:00<00:00, 1423.43it/s]

Bootstrapping precision:  58%|█████▊    | 577/1000 [00:00<00:00, 1424.02it/s]

Bootstrapping precision:  72%|███████▏  | 722/1000 [00:00<00:00, 1431.00it/s]

Bootstrapping precision:  87%|████████▋ | 867/1000 [00:00<00:00, 1435.90it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1433.41it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1429.64it/s]

Bootstrapping recall:  29%|██▉       | 289/1000 [00:00<00:00, 1442.10it/s]

Bootstrapping recall:  43%|████▎     | 434/1000 [00:00<00:00, 1441.99it/s]

Bootstrapping recall:  58%|█████▊    | 580/1000 [00:00<00:00, 1446.49it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1450.96it/s]

Bootstrapping recall:  87%|████████▋ | 873/1000 [00:00<00:00, 1454.16it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1445.83it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  13%|█▎        | 133/1000 [00:00<00:00, 1322.59it/s]

Bootstrapping f1:  27%|██▋       | 266/1000 [00:00<00:00, 1311.62it/s]

Bootstrapping f1:  40%|███▉      | 398/1000 [00:00<00:00, 1313.29it/s]

Bootstrapping f1:  53%|█████▎    | 531/1000 [00:00<00:00, 1318.44it/s]

Bootstrapping f1:  67%|██████▋   | 672/1000 [00:00<00:00, 1349.71it/s]

Bootstrapping f1:  81%|████████▏ | 814/1000 [00:00<00:00, 1372.60it/s]

Bootstrapping f1:  96%|█████████▌| 957/1000 [00:00<00:00, 1390.04it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1360.67it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 419/1000 [00:00<00:00, 4189.75it/s]

Bootstrapping accuracy:  84%|████████▍ | 839/1000 [00:00<00:00, 4194.50it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4193.88it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 204/1000 [00:00<00:00, 2031.11it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 2031.85it/s]

Bootstrapping average_precision:  61%|██████    | 612/1000 [00:00<00:00, 2034.45it/s]

Bootstrapping average_precision:  82%|████████▏ | 818/1000 [00:00<00:00, 2041.26it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2040.15it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 122/1000 [00:00<00:00, 1219.22it/s]

Bootstrapping roc_auc:  24%|██▍       | 244/1000 [00:00<00:00, 1218.97it/s]

Bootstrapping roc_auc:  37%|███▋      | 368/1000 [00:00<00:00, 1224.23it/s]

Bootstrapping roc_auc:  49%|████▉     | 492/1000 [00:00<00:00, 1227.05it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 1223.90it/s]

Bootstrapping roc_auc:  74%|███████▍  | 738/1000 [00:00<00:00, 1224.93it/s]

Bootstrapping roc_auc:  86%|████████▌ | 861/1000 [00:00<00:00, 1225.52it/s]

Bootstrapping roc_auc:  98%|█████████▊| 984/1000 [00:00<00:00, 1222.43it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1222.28it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1426.32it/s]

Bootstrapping precision:  29%|██▊       | 286/1000 [00:00<00:00, 1410.63it/s]

Bootstrapping precision:  43%|████▎     | 428/1000 [00:00<00:00, 1409.03it/s]

Bootstrapping precision:  57%|█████▋    | 571/1000 [00:00<00:00, 1416.11it/s]

Bootstrapping precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1413.93it/s]

Bootstrapping precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1415.36it/s]

Bootstrapping precision: 100%|█████████▉| 998/1000 [00:00<00:00, 1418.93it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1414.77it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 145/1000 [00:00<00:00, 1441.21it/s]

Bootstrapping recall:  29%|██▉       | 290/1000 [00:00<00:00, 1442.52it/s]

Bootstrapping recall:  44%|████▎     | 435/1000 [00:00<00:00, 1427.17it/s]

Bootstrapping recall:  58%|█████▊    | 578/1000 [00:00<00:00, 1426.71it/s]

Bootstrapping recall:  72%|███████▏  | 721/1000 [00:00<00:00, 1426.31it/s]

Bootstrapping recall:  86%|████████▋ | 864/1000 [00:00<00:00, 1426.49it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1429.91it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 144/1000 [00:00<00:00, 1431.67it/s]

Bootstrapping f1:  29%|██▉       | 288/1000 [00:00<00:00, 1429.67it/s]

Bootstrapping f1:  43%|████▎     | 431/1000 [00:00<00:00, 1425.24it/s]

Bootstrapping f1:  57%|█████▋    | 574/1000 [00:00<00:00, 1403.92it/s]

Bootstrapping f1:  72%|███████▏  | 715/1000 [00:00<00:00, 1396.17it/s]

Bootstrapping f1:  86%|████████▌ | 855/1000 [00:00<00:00, 1380.75it/s]

Bootstrapping f1: 100%|█████████▉| 996/1000 [00:00<00:00, 1389.51it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1397.26it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 420/1000 [00:00<00:00, 4196.52it/s]

Bootstrapping accuracy:  84%|████████▍ | 840/1000 [00:00<00:00, 4188.86it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4184.75it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 202/1000 [00:00<00:00, 2013.88it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 2017.73it/s]

Bootstrapping average_precision:  61%|██████    | 609/1000 [00:00<00:00, 2023.74it/s]

Bootstrapping average_precision:  81%|████████  | 812/1000 [00:00<00:00, 2024.84it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2025.08it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1202.83it/s]

Bootstrapping roc_auc:  24%|██▍       | 244/1000 [00:00<00:00, 1217.35it/s]

Bootstrapping roc_auc:  37%|███▋      | 366/1000 [00:00<00:00, 1215.39it/s]

Bootstrapping roc_auc:  49%|████▉     | 489/1000 [00:00<00:00, 1218.71it/s]

Bootstrapping roc_auc:  61%|██████    | 611/1000 [00:00<00:00, 1218.64it/s]

Bootstrapping roc_auc:  73%|███████▎  | 733/1000 [00:00<00:00, 1217.96it/s]

Bootstrapping roc_auc:  86%|████████▌ | 855/1000 [00:00<00:00, 1215.44it/s]

Bootstrapping roc_auc:  98%|█████████▊| 978/1000 [00:00<00:00, 1218.47it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1216.08it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 142/1000 [00:00<00:00, 1413.75it/s]

Bootstrapping precision:  28%|██▊       | 285/1000 [00:00<00:00, 1421.55it/s]

Bootstrapping precision:  43%|████▎     | 429/1000 [00:00<00:00, 1426.51it/s]

Bootstrapping precision:  57%|█████▋    | 573/1000 [00:00<00:00, 1430.08it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1424.20it/s]

Bootstrapping precision:  86%|████████▌ | 860/1000 [00:00<00:00, 1423.30it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1424.55it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1425.45it/s]

Bootstrapping recall:  29%|██▊       | 286/1000 [00:00<00:00, 1426.44it/s]

Bootstrapping recall:  43%|████▎     | 429/1000 [00:00<00:00, 1427.87it/s]

Bootstrapping recall:  57%|█████▋    | 572/1000 [00:00<00:00, 1426.39it/s]

Bootstrapping recall:  72%|███████▏  | 716/1000 [00:00<00:00, 1429.83it/s]

Bootstrapping recall:  86%|████████▌ | 860/1000 [00:00<00:00, 1431.41it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1430.60it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1422.69it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1418.71it/s]

Bootstrapping f1:  43%|████▎     | 430/1000 [00:00<00:00, 1423.92it/s]

Bootstrapping f1:  57%|█████▋    | 573/1000 [00:00<00:00, 1423.72it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1424.83it/s]

Bootstrapping f1:  86%|████████▌ | 859/1000 [00:00<00:00, 1426.02it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1425.22it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 416/1000 [00:00<00:00, 4153.40it/s]

Bootstrapping accuracy:  84%|████████▎ | 837/1000 [00:00<00:00, 4183.55it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4174.28it/s]

Processing Simplified Golem (12 nodes, 22 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1362.25it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1361.67it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1365.28it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1366.03it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1352.41it/s]

Bootstrapping average_precision:  82%|████████▏ | 821/1000 [00:00<00:00, 1343.12it/s]

Bootstrapping average_precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1344.23it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1350.37it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 865.54it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 867.28it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 866.78it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 864.85it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 861.10it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 862.57it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 863.77it/s]

Bootstrapping roc_auc:  70%|██████▉   | 697/1000 [00:00<00:00, 867.39it/s]

Bootstrapping roc_auc:  78%|███████▊  | 784/1000 [00:00<00:00, 867.85it/s]

Bootstrapping roc_auc:  87%|████████▋ | 871/1000 [00:01<00:00, 867.59it/s]

Bootstrapping roc_auc:  96%|█████████▌| 958/1000 [00:01<00:00, 861.24it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 862.56it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1176.26it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1177.10it/s]

Bootstrapping precision:  36%|███▌      | 355/1000 [00:00<00:00, 1180.84it/s]

Bootstrapping precision:  47%|████▋     | 474/1000 [00:00<00:00, 1172.98it/s]

Bootstrapping precision:  59%|█████▉    | 592/1000 [00:00<00:00, 1175.30it/s]

Bootstrapping precision:  71%|███████   | 712/1000 [00:00<00:00, 1180.45it/s]

Bootstrapping precision:  83%|████████▎ | 834/1000 [00:00<00:00, 1190.91it/s]

Bootstrapping precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1199.46it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1188.09it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1225.72it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1227.44it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1226.49it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1223.04it/s]

Bootstrapping recall:  62%|██████▏   | 615/1000 [00:00<00:00, 1223.69it/s]

Bootstrapping recall:  74%|███████▍  | 739/1000 [00:00<00:00, 1227.51it/s]

Bootstrapping recall:  86%|████████▌ | 862/1000 [00:00<00:00, 1226.97it/s]

Bootstrapping recall:  99%|█████████▊| 986/1000 [00:00<00:00, 1228.34it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1225.97it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1216.73it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1214.65it/s]

Bootstrapping f1:  37%|███▋      | 368/1000 [00:00<00:00, 1221.77it/s]

Bootstrapping f1:  49%|████▉     | 491/1000 [00:00<00:00, 1223.20it/s]

Bootstrapping f1:  61%|██████▏   | 614/1000 [00:00<00:00, 1223.85it/s]

Bootstrapping f1:  74%|███████▎  | 737/1000 [00:00<00:00, 1222.53it/s]

Bootstrapping f1:  86%|████████▌ | 860/1000 [00:00<00:00, 1224.32it/s]

Bootstrapping f1:  98%|█████████▊| 983/1000 [00:00<00:00, 1223.22it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1221.23it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 358/1000 [00:00<00:00, 3578.32it/s]

Bootstrapping accuracy:  72%|███████▏  | 716/1000 [00:00<00:00, 3575.42it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3580.28it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 212/1000 [00:00<00:00, 2112.52it/s]

Bootstrapping average_precision:  42%|████▏     | 424/1000 [00:00<00:00, 2116.30it/s]

Bootstrapping average_precision:  64%|██████▎   | 637/1000 [00:00<00:00, 2118.78it/s]

Bootstrapping average_precision:  85%|████████▍ | 849/1000 [00:00<00:00, 2118.22it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2116.97it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 127/1000 [00:00<00:00, 1268.08it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 1269.67it/s]

Bootstrapping roc_auc:  38%|███▊      | 382/1000 [00:00<00:00, 1239.79it/s]

Bootstrapping roc_auc:  51%|█████     | 507/1000 [00:00<00:00, 1242.39it/s]

Bootstrapping roc_auc:  63%|██████▎   | 632/1000 [00:00<00:00, 1244.59it/s]

Bootstrapping roc_auc:  76%|███████▌  | 758/1000 [00:00<00:00, 1247.99it/s]

Bootstrapping roc_auc:  89%|████████▊ | 886/1000 [00:00<00:00, 1255.77it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1252.53it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1429.61it/s]

Bootstrapping precision:  29%|██▊       | 287/1000 [00:00<00:00, 1435.27it/s]

Bootstrapping precision:  43%|████▎     | 432/1000 [00:00<00:00, 1438.98it/s]

Bootstrapping precision:  58%|█████▊    | 576/1000 [00:00<00:00, 1437.79it/s]

Bootstrapping precision:  72%|███████▏  | 722/1000 [00:00<00:00, 1443.11it/s]

Bootstrapping precision:  87%|████████▋ | 868/1000 [00:00<00:00, 1447.91it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1443.96it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 145/1000 [00:00<00:00, 1442.27it/s]

Bootstrapping recall:  29%|██▉       | 290/1000 [00:00<00:00, 1445.10it/s]

Bootstrapping recall:  44%|████▎     | 435/1000 [00:00<00:00, 1446.30it/s]

Bootstrapping recall:  58%|█████▊    | 581/1000 [00:00<00:00, 1448.32it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1447.33it/s]

Bootstrapping recall:  87%|████████▋ | 872/1000 [00:00<00:00, 1450.15it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1448.49it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  15%|█▍        | 146/1000 [00:00<00:00, 1451.40it/s]

Bootstrapping f1:  29%|██▉       | 292/1000 [00:00<00:00, 1451.85it/s]

Bootstrapping f1:  44%|████▍     | 438/1000 [00:00<00:00, 1453.59it/s]

Bootstrapping f1:  58%|█████▊    | 584/1000 [00:00<00:00, 1450.72it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1449.96it/s]

Bootstrapping f1:  88%|████████▊ | 875/1000 [00:00<00:00, 1448.48it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1450.72it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 421/1000 [00:00<00:00, 4207.10it/s]

Bootstrapping accuracy:  84%|████████▍ | 842/1000 [00:00<00:00, 4122.71it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4136.54it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 203/1000 [00:00<00:00, 2026.61it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 2029.91it/s]

Bootstrapping average_precision:  61%|██████    | 612/1000 [00:00<00:00, 2037.06it/s]

Bootstrapping average_precision:  82%|████████▏ | 816/1000 [00:00<00:00, 2033.67it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2030.66it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 121/1000 [00:00<00:00, 1209.92it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 1213.91it/s]

Bootstrapping roc_auc:  36%|███▋      | 365/1000 [00:00<00:00, 1210.09it/s]

Bootstrapping roc_auc:  49%|████▉     | 488/1000 [00:00<00:00, 1213.56it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 1212.61it/s]

Bootstrapping roc_auc:  73%|███████▎  | 733/1000 [00:00<00:00, 1215.71it/s]

Bootstrapping roc_auc:  86%|████████▌ | 857/1000 [00:00<00:00, 1222.69it/s]

Bootstrapping roc_auc:  98%|█████████▊| 980/1000 [00:00<00:00, 1223.33it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1217.07it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1420.80it/s]

Bootstrapping precision:  29%|██▊       | 286/1000 [00:00<00:00, 1409.85it/s]

Bootstrapping precision:  43%|████▎     | 427/1000 [00:00<00:00, 1402.08it/s]

Bootstrapping precision:  57%|█████▋    | 570/1000 [00:00<00:00, 1409.09it/s]

Bootstrapping precision:  71%|███████   | 712/1000 [00:00<00:00, 1411.24it/s]

Bootstrapping precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1416.75it/s]

Bootstrapping precision: 100%|█████████▉| 999/1000 [00:00<00:00, 1422.18it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1414.43it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1429.29it/s]

Bootstrapping recall:  29%|██▊       | 287/1000 [00:00<00:00, 1433.72it/s]

Bootstrapping recall:  43%|████▎     | 431/1000 [00:00<00:00, 1431.22it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1430.31it/s]

Bootstrapping recall:  72%|███████▏  | 719/1000 [00:00<00:00, 1429.52it/s]

Bootstrapping recall:  86%|████████▌ | 862/1000 [00:00<00:00, 1428.63it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1429.51it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1425.97it/s]

Bootstrapping f1:  29%|██▊       | 287/1000 [00:00<00:00, 1431.55it/s]

Bootstrapping f1:  43%|████▎     | 431/1000 [00:00<00:00, 1427.08it/s]

Bootstrapping f1:  57%|█████▋    | 574/1000 [00:00<00:00, 1427.81it/s]

Bootstrapping f1:  72%|███████▏  | 718/1000 [00:00<00:00, 1432.07it/s]

Bootstrapping f1:  86%|████████▌ | 862/1000 [00:00<00:00, 1431.44it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1430.22it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 419/1000 [00:00<00:00, 4182.85it/s]

Bootstrapping accuracy:  84%|████████▍ | 840/1000 [00:00<00:00, 4194.25it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4187.94it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 204/1000 [00:00<00:00, 2031.55it/s]

Bootstrapping average_precision:  41%|████      | 409/1000 [00:00<00:00, 2036.69it/s]

Bootstrapping average_precision:  62%|██████▏   | 615/1000 [00:00<00:00, 2044.01it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 2042.59it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2040.16it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 122/1000 [00:00<00:00, 1211.06it/s]

Bootstrapping roc_auc:  24%|██▍       | 244/1000 [00:00<00:00, 1201.29it/s]

Bootstrapping roc_auc:  37%|███▋      | 367/1000 [00:00<00:00, 1213.46it/s]

Bootstrapping roc_auc:  49%|████▉     | 491/1000 [00:00<00:00, 1220.66it/s]

Bootstrapping roc_auc:  61%|██████▏   | 614/1000 [00:00<00:00, 1220.31it/s]

Bootstrapping roc_auc:  74%|███████▎  | 737/1000 [00:00<00:00, 1221.49it/s]

Bootstrapping roc_auc:  86%|████████▌ | 860/1000 [00:00<00:00, 1222.46it/s]

Bootstrapping roc_auc:  98%|█████████▊| 984/1000 [00:00<00:00, 1224.84it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1219.77it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1425.58it/s]

Bootstrapping precision:  29%|██▊       | 287/1000 [00:00<00:00, 1433.22it/s]

Bootstrapping precision:  43%|████▎     | 431/1000 [00:00<00:00, 1435.68it/s]

Bootstrapping precision:  57%|█████▊    | 575/1000 [00:00<00:00, 1433.67it/s]

Bootstrapping precision:  72%|███████▏  | 719/1000 [00:00<00:00, 1434.11it/s]

Bootstrapping precision:  86%|████████▋ | 864/1000 [00:00<00:00, 1436.17it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1433.90it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1427.40it/s]

Bootstrapping recall:  29%|██▊       | 287/1000 [00:00<00:00, 1429.73it/s]

Bootstrapping recall:  43%|████▎     | 431/1000 [00:00<00:00, 1430.40it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1428.98it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1429.33it/s]

Bootstrapping recall:  86%|████████▌ | 862/1000 [00:00<00:00, 1430.79it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1428.02it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1425.60it/s]

Bootstrapping f1:  29%|██▊       | 286/1000 [00:00<00:00, 1418.56it/s]

Bootstrapping f1:  43%|████▎     | 428/1000 [00:00<00:00, 1400.98it/s]

Bootstrapping f1:  57%|█████▋    | 572/1000 [00:00<00:00, 1413.82it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1422.62it/s]

Bootstrapping f1:  86%|████████▌ | 860/1000 [00:00<00:00, 1425.64it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1422.21it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 417/1000 [00:00<00:00, 4165.91it/s]

Bootstrapping accuracy:  84%|████████▎ | 836/1000 [00:00<00:00, 4174.09it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4169.34it/s]

Processing Simplified Golem $\cap$ Simplified PCMB (6 nodes, 5 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1354.93it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1363.13it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1364.57it/s]

Bootstrapping average_precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1366.39it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1368.75it/s]

Bootstrapping average_precision:  82%|████████▏ | 823/1000 [00:00<00:00, 1369.13it/s]

Bootstrapping average_precision:  96%|█████████▌| 961/1000 [00:00<00:00, 1370.03it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1366.85it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 872.82it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 870.64it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 872.26it/s]

Bootstrapping roc_auc:  35%|███▌      | 352/1000 [00:00<00:00, 873.74it/s]

Bootstrapping roc_auc:  44%|████▍     | 440/1000 [00:00<00:00, 874.59it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 868.36it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 865.98it/s]

Bootstrapping roc_auc:  70%|███████   | 702/1000 [00:00<00:00, 866.02it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 867.66it/s]

Bootstrapping roc_auc:  88%|████████▊ | 877/1000 [00:01<00:00, 868.32it/s]

Bootstrapping roc_auc:  96%|█████████▋| 965/1000 [00:01<00:00, 869.95it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 869.16it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1218.75it/s]

Bootstrapping precision:  24%|██▍       | 245/1000 [00:00<00:00, 1222.41it/s]

Bootstrapping precision:  37%|███▋      | 369/1000 [00:00<00:00, 1227.51it/s]

Bootstrapping precision:  49%|████▉     | 492/1000 [00:00<00:00, 1227.68it/s]

Bootstrapping precision:  62%|██████▏   | 615/1000 [00:00<00:00, 1226.78it/s]

Bootstrapping precision:  74%|███████▍  | 739/1000 [00:00<00:00, 1230.27it/s]

Bootstrapping precision:  86%|████████▋ | 863/1000 [00:00<00:00, 1227.44it/s]

Bootstrapping precision:  99%|█████████▊| 986/1000 [00:00<00:00, 1227.22it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1225.70it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1224.02it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1225.17it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1212.44it/s]

Bootstrapping recall:  49%|████▉     | 492/1000 [00:00<00:00, 1216.95it/s]

Bootstrapping recall:  62%|██████▏   | 615/1000 [00:00<00:00, 1221.55it/s]

Bootstrapping recall:  74%|███████▍  | 738/1000 [00:00<00:00, 1219.92it/s]

Bootstrapping recall:  86%|████████▌ | 862/1000 [00:00<00:00, 1223.99it/s]

Bootstrapping recall:  98%|█████████▊| 985/1000 [00:00<00:00, 1219.02it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1218.82it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1219.89it/s]

Bootstrapping f1:  24%|██▍       | 245/1000 [00:00<00:00, 1222.73it/s]

Bootstrapping f1:  37%|███▋      | 369/1000 [00:00<00:00, 1226.13it/s]

Bootstrapping f1:  49%|████▉     | 492/1000 [00:00<00:00, 1218.40it/s]

Bootstrapping f1:  61%|██████▏   | 614/1000 [00:00<00:00, 1217.20it/s]

Bootstrapping f1:  74%|███████▎  | 736/1000 [00:00<00:00, 1214.32it/s]

Bootstrapping f1:  86%|████████▌ | 858/1000 [00:00<00:00, 1215.63it/s]

Bootstrapping f1:  98%|█████████▊| 981/1000 [00:00<00:00, 1217.39it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1216.19it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 348/1000 [00:00<00:00, 3470.93it/s]

Bootstrapping accuracy:  70%|██████▉   | 699/1000 [00:00<00:00, 3489.85it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3495.96it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 211/1000 [00:00<00:00, 2105.25it/s]

Bootstrapping average_precision:  42%|████▏     | 422/1000 [00:00<00:00, 2102.70it/s]

Bootstrapping average_precision:  63%|██████▎   | 633/1000 [00:00<00:00, 2099.32it/s]

Bootstrapping average_precision:  84%|████████▍ | 845/1000 [00:00<00:00, 2104.95it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2103.53it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 128/1000 [00:00<00:00, 1272.41it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 1272.47it/s]

Bootstrapping roc_auc:  38%|███▊      | 384/1000 [00:00<00:00, 1274.68it/s]

Bootstrapping roc_auc:  51%|█████     | 512/1000 [00:00<00:00, 1271.69it/s]

Bootstrapping roc_auc:  64%|██████▍   | 640/1000 [00:00<00:00, 1272.08it/s]

Bootstrapping roc_auc:  77%|███████▋  | 768/1000 [00:00<00:00, 1269.02it/s]

Bootstrapping roc_auc:  90%|████████▉ | 896/1000 [00:00<00:00, 1271.92it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1272.03it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 138/1000 [00:00<00:00, 1371.81it/s]

Bootstrapping precision:  28%|██▊       | 277/1000 [00:00<00:00, 1380.52it/s]

Bootstrapping precision:  42%|████▏     | 418/1000 [00:00<00:00, 1390.19it/s]

Bootstrapping precision:  56%|█████▌    | 558/1000 [00:00<00:00, 1392.66it/s]

Bootstrapping precision:  70%|███████   | 700/1000 [00:00<00:00, 1399.54it/s]

Bootstrapping precision:  84%|████████▍ | 845/1000 [00:00<00:00, 1414.67it/s]

Bootstrapping precision:  99%|█████████▉| 991/1000 [00:00<00:00, 1427.37it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1408.35it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 145/1000 [00:00<00:00, 1445.62it/s]

Bootstrapping recall:  29%|██▉       | 290/1000 [00:00<00:00, 1445.80it/s]

Bootstrapping recall:  44%|████▎     | 436/1000 [00:00<00:00, 1451.34it/s]

Bootstrapping recall:  58%|█████▊    | 582/1000 [00:00<00:00, 1450.79it/s]

Bootstrapping recall:  73%|███████▎  | 728/1000 [00:00<00:00, 1450.52it/s]

Bootstrapping recall:  87%|████████▋ | 874/1000 [00:00<00:00, 1451.30it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1451.09it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 145/1000 [00:00<00:00, 1448.83it/s]

Bootstrapping f1:  29%|██▉       | 290/1000 [00:00<00:00, 1447.78it/s]

Bootstrapping f1:  44%|████▎     | 435/1000 [00:00<00:00, 1448.19it/s]

Bootstrapping f1:  58%|█████▊    | 581/1000 [00:00<00:00, 1451.96it/s]

Bootstrapping f1:  73%|███████▎  | 727/1000 [00:00<00:00, 1449.71it/s]

Bootstrapping f1:  87%|████████▋ | 873/1000 [00:00<00:00, 1452.17it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1451.17it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▎     | 425/1000 [00:00<00:00, 4244.24it/s]

Bootstrapping accuracy:  85%|████████▌ | 850/1000 [00:00<00:00, 4237.26it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4226.26it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 205/1000 [00:00<00:00, 2040.99it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 2043.97it/s]

Bootstrapping average_precision:  62%|██████▏   | 615/1000 [00:00<00:00, 2045.55it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 2046.35it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2043.99it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1223.51it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1225.67it/s]

Bootstrapping roc_auc:  37%|███▋      | 369/1000 [00:00<00:00, 1227.38it/s]

Bootstrapping roc_auc:  49%|████▉     | 492/1000 [00:00<00:00, 1225.60it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 1228.49it/s]

Bootstrapping roc_auc:  74%|███████▍  | 739/1000 [00:00<00:00, 1228.38it/s]

Bootstrapping roc_auc:  86%|████████▌ | 862/1000 [00:00<00:00, 1228.47it/s]

Bootstrapping roc_auc:  98%|█████████▊| 985/1000 [00:00<00:00, 1226.28it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1225.75it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1429.50it/s]

Bootstrapping precision:  29%|██▊       | 287/1000 [00:00<00:00, 1431.51it/s]

Bootstrapping precision:  43%|████▎     | 431/1000 [00:00<00:00, 1433.53it/s]

Bootstrapping precision:  57%|█████▊    | 575/1000 [00:00<00:00, 1434.44it/s]

Bootstrapping precision:  72%|███████▏  | 719/1000 [00:00<00:00, 1415.00it/s]

Bootstrapping precision:  86%|████████▌ | 861/1000 [00:00<00:00, 1406.36it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1412.08it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 142/1000 [00:00<00:00, 1415.18it/s]

Bootstrapping recall:  28%|██▊       | 285/1000 [00:00<00:00, 1421.82it/s]

Bootstrapping recall:  43%|████▎     | 428/1000 [00:00<00:00, 1424.96it/s]

Bootstrapping recall:  57%|█████▋    | 571/1000 [00:00<00:00, 1426.17it/s]

Bootstrapping recall:  72%|███████▏  | 716/1000 [00:00<00:00, 1432.09it/s]

Bootstrapping recall:  86%|████████▌ | 860/1000 [00:00<00:00, 1433.41it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1430.47it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1426.90it/s]

Bootstrapping f1:  29%|██▊       | 287/1000 [00:00<00:00, 1432.56it/s]

Bootstrapping f1:  43%|████▎     | 431/1000 [00:00<00:00, 1432.17it/s]

Bootstrapping f1:  57%|█████▊    | 575/1000 [00:00<00:00, 1435.14it/s]

Bootstrapping f1:  72%|███████▏  | 720/1000 [00:00<00:00, 1437.54it/s]

Bootstrapping f1:  86%|████████▋ | 865/1000 [00:00<00:00, 1438.37it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1436.08it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 420/1000 [00:00<00:00, 4197.52it/s]

Bootstrapping accuracy:  84%|████████▍ | 840/1000 [00:00<00:00, 4195.75it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4190.62it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 204/1000 [00:00<00:00, 2031.17it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 2031.02it/s]

Bootstrapping average_precision:  61%|██████▏   | 613/1000 [00:00<00:00, 2038.91it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 2033.79it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2035.11it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1223.65it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1221.80it/s]

Bootstrapping roc_auc:  37%|███▋      | 369/1000 [00:00<00:00, 1223.89it/s]

Bootstrapping roc_auc:  49%|████▉     | 492/1000 [00:00<00:00, 1224.24it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 1227.33it/s]

Bootstrapping roc_auc:  74%|███████▍  | 739/1000 [00:00<00:00, 1226.89it/s]

Bootstrapping roc_auc:  86%|████████▌ | 862/1000 [00:00<00:00, 1227.13it/s]

Bootstrapping roc_auc:  98%|█████████▊| 985/1000 [00:00<00:00, 1224.39it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1224.06it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 144/1000 [00:00<00:00, 1433.15it/s]

Bootstrapping precision:  29%|██▉       | 289/1000 [00:00<00:00, 1437.83it/s]

Bootstrapping precision:  43%|████▎     | 434/1000 [00:00<00:00, 1440.63it/s]

Bootstrapping precision:  58%|█████▊    | 579/1000 [00:00<00:00, 1437.33it/s]

Bootstrapping precision:  72%|███████▏  | 724/1000 [00:00<00:00, 1439.10it/s]

Bootstrapping precision:  87%|████████▋ | 868/1000 [00:00<00:00, 1438.66it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1437.23it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1423.75it/s]

Bootstrapping recall:  29%|██▉       | 288/1000 [00:00<00:00, 1436.56it/s]

Bootstrapping recall:  43%|████▎     | 433/1000 [00:00<00:00, 1441.63it/s]

Bootstrapping recall:  58%|█████▊    | 578/1000 [00:00<00:00, 1441.84it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1441.31it/s]

Bootstrapping recall:  87%|████████▋ | 868/1000 [00:00<00:00, 1443.18it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1440.36it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1429.35it/s]

Bootstrapping f1:  29%|██▊       | 287/1000 [00:00<00:00, 1430.90it/s]

Bootstrapping f1:  43%|████▎     | 431/1000 [00:00<00:00, 1433.79it/s]

Bootstrapping f1:  57%|█████▊    | 575/1000 [00:00<00:00, 1434.18it/s]

Bootstrapping f1:  72%|███████▏  | 720/1000 [00:00<00:00, 1436.99it/s]

Bootstrapping f1:  86%|████████▋ | 864/1000 [00:00<00:00, 1437.34it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1437.07it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 419/1000 [00:00<00:00, 4181.35it/s]

Bootstrapping accuracy:  84%|████████▍ | 842/1000 [00:00<00:00, 4207.74it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4199.09it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem (5 nodes, 4 edges)

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1360.10it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1363.04it/s]

Bootstrapping average_precision:  41%|████      | 412/1000 [00:00<00:00, 1368.73it/s]

Bootstrapping average_precision:  55%|█████▌    | 550/1000 [00:00<00:00, 1370.93it/s]

Bootstrapping average_precision:  69%|██████▉   | 688/1000 [00:00<00:00, 1371.01it/s]

Bootstrapping average_precision:  83%|████████▎ | 826/1000 [00:00<00:00, 1373.22it/s]

Bootstrapping average_precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1371.09it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1369.13it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 869.51it/s]

Bootstrapping roc_auc:  18%|█▊        | 175/1000 [00:00<00:00, 870.80it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 869.21it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 870.84it/s]

Bootstrapping roc_auc:  44%|████▍     | 439/1000 [00:00<00:00, 866.51it/s]

Bootstrapping roc_auc:  53%|█████▎    | 526/1000 [00:00<00:00, 867.13it/s]

Bootstrapping roc_auc:  61%|██████▏   | 614/1000 [00:00<00:00, 869.72it/s]

Bootstrapping roc_auc:  70%|███████   | 702/1000 [00:00<00:00, 871.43it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 871.87it/s]

Bootstrapping roc_auc:  88%|████████▊ | 878/1000 [00:01<00:00, 872.51it/s]

Bootstrapping roc_auc:  97%|█████████▋| 966/1000 [00:01<00:00, 873.85it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 871.08it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 123/1000 [00:00<00:00, 1224.25it/s]

Bootstrapping precision:  25%|██▍       | 246/1000 [00:00<00:00, 1222.12it/s]

Bootstrapping precision:  37%|███▋      | 369/1000 [00:00<00:00, 1225.04it/s]

Bootstrapping precision:  49%|████▉     | 492/1000 [00:00<00:00, 1223.81it/s]

Bootstrapping precision:  62%|██████▏   | 615/1000 [00:00<00:00, 1221.93it/s]

Bootstrapping precision:  74%|███████▍  | 738/1000 [00:00<00:00, 1221.77it/s]

Bootstrapping precision:  86%|████████▌ | 861/1000 [00:00<00:00, 1222.25it/s]

Bootstrapping precision:  98%|█████████▊| 984/1000 [00:00<00:00, 1222.86it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1221.82it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1216.91it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1216.39it/s]

Bootstrapping recall:  37%|███▋      | 367/1000 [00:00<00:00, 1220.18it/s]

Bootstrapping recall:  49%|████▉     | 490/1000 [00:00<00:00, 1222.36it/s]

Bootstrapping recall:  61%|██████▏   | 613/1000 [00:00<00:00, 1224.15it/s]

Bootstrapping recall:  74%|███████▎  | 736/1000 [00:00<00:00, 1225.45it/s]

Bootstrapping recall:  86%|████████▌ | 859/1000 [00:00<00:00, 1219.63it/s]

Bootstrapping recall:  98%|█████████▊| 981/1000 [00:00<00:00, 1204.51it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1212.94it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1201.07it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1195.68it/s]

Bootstrapping f1:  36%|███▋      | 365/1000 [00:00<00:00, 1210.71it/s]

Bootstrapping f1:  49%|████▉     | 488/1000 [00:00<00:00, 1214.76it/s]

Bootstrapping f1:  61%|██████    | 611/1000 [00:00<00:00, 1217.12it/s]

Bootstrapping f1:  73%|███████▎  | 733/1000 [00:00<00:00, 1215.14it/s]

Bootstrapping f1:  86%|████████▌ | 856/1000 [00:00<00:00, 1217.31it/s]

Bootstrapping f1:  98%|█████████▊| 978/1000 [00:00<00:00, 1215.80it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1212.25it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 357/1000 [00:00<00:00, 3562.47it/s]

Bootstrapping accuracy:  71%|███████▏  | 714/1000 [00:00<00:00, 3552.59it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3558.30it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  21%|██        | 211/1000 [00:00<00:00, 2105.98it/s]

Bootstrapping average_precision:  42%|████▏     | 424/1000 [00:00<00:00, 2116.26it/s]

Bootstrapping average_precision:  64%|██████▎   | 636/1000 [00:00<00:00, 2116.59it/s]

Bootstrapping average_precision:  85%|████████▍ | 849/1000 [00:00<00:00, 2120.36it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2118.07it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  13%|█▎        | 128/1000 [00:00<00:00, 1272.24it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 1267.65it/s]

Bootstrapping roc_auc:  38%|███▊      | 384/1000 [00:00<00:00, 1268.58it/s]

Bootstrapping roc_auc:  51%|█████     | 512/1000 [00:00<00:00, 1271.60it/s]

Bootstrapping roc_auc:  64%|██████▍   | 640/1000 [00:00<00:00, 1274.08it/s]

Bootstrapping roc_auc:  77%|███████▋  | 768/1000 [00:00<00:00, 1271.64it/s]

Bootstrapping roc_auc:  90%|████████▉ | 896/1000 [00:00<00:00, 1272.31it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1271.37it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 144/1000 [00:00<00:00, 1435.56it/s]

Bootstrapping precision:  29%|██▉       | 290/1000 [00:00<00:00, 1445.07it/s]

Bootstrapping precision:  44%|████▎     | 436/1000 [00:00<00:00, 1450.21it/s]

Bootstrapping precision:  58%|█████▊    | 582/1000 [00:00<00:00, 1450.91it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1454.48it/s]

Bootstrapping precision:  88%|████████▊ | 876/1000 [00:00<00:00, 1458.05it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1452.65it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 145/1000 [00:00<00:00, 1444.78it/s]

Bootstrapping recall:  29%|██▉       | 290/1000 [00:00<00:00, 1432.71it/s]

Bootstrapping recall:  44%|████▎     | 435/1000 [00:00<00:00, 1440.27it/s]

Bootstrapping recall:  58%|█████▊    | 580/1000 [00:00<00:00, 1443.92it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1447.96it/s]

Bootstrapping recall:  87%|████████▋ | 872/1000 [00:00<00:00, 1448.76it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1445.66it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 145/1000 [00:00<00:00, 1449.33it/s]

Bootstrapping f1:  29%|██▉       | 291/1000 [00:00<00:00, 1450.04it/s]

Bootstrapping f1:  44%|████▍     | 438/1000 [00:00<00:00, 1455.58it/s]

Bootstrapping f1:  58%|█████▊    | 584/1000 [00:00<00:00, 1453.87it/s]

Bootstrapping f1:  73%|███████▎  | 730/1000 [00:00<00:00, 1452.47it/s]

Bootstrapping f1:  88%|████████▊ | 876/1000 [00:00<00:00, 1450.30it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1451.40it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 423/1000 [00:00<00:00, 4222.01it/s]

Bootstrapping accuracy:  85%|████████▍ | 846/1000 [00:00<00:00, 4220.48it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4214.16it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 204/1000 [00:00<00:00, 2030.58it/s]

Bootstrapping average_precision:  41%|████      | 409/1000 [00:00<00:00, 2038.19it/s]

Bootstrapping average_precision:  61%|██████▏   | 613/1000 [00:00<00:00, 2034.37it/s]

Bootstrapping average_precision:  82%|████████▏ | 818/1000 [00:00<00:00, 2039.01it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2039.55it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1228.60it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1221.85it/s]

Bootstrapping roc_auc:  37%|███▋      | 369/1000 [00:00<00:00, 1224.21it/s]

Bootstrapping roc_auc:  49%|████▉     | 493/1000 [00:00<00:00, 1226.73it/s]

Bootstrapping roc_auc:  62%|██████▏   | 617/1000 [00:00<00:00, 1228.11it/s]

Bootstrapping roc_auc:  74%|███████▍  | 740/1000 [00:00<00:00, 1228.54it/s]

Bootstrapping roc_auc:  86%|████████▋ | 864/1000 [00:00<00:00, 1229.47it/s]

Bootstrapping roc_auc:  99%|█████████▊| 987/1000 [00:00<00:00, 1229.52it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1226.62it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1429.47it/s]

Bootstrapping precision:  29%|██▊       | 287/1000 [00:00<00:00, 1429.46it/s]

Bootstrapping precision:  43%|████▎     | 432/1000 [00:00<00:00, 1434.85it/s]

Bootstrapping precision:  58%|█████▊    | 576/1000 [00:00<00:00, 1434.65it/s]

Bootstrapping precision:  72%|███████▏  | 720/1000 [00:00<00:00, 1435.48it/s]

Bootstrapping precision:  86%|████████▋ | 864/1000 [00:00<00:00, 1432.68it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1433.51it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 143/1000 [00:00<00:00, 1425.23it/s]

Bootstrapping recall:  29%|██▊       | 287/1000 [00:00<00:00, 1429.06it/s]

Bootstrapping recall:  43%|████▎     | 431/1000 [00:00<00:00, 1430.72it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1426.23it/s]

Bootstrapping recall:  72%|███████▏  | 718/1000 [00:00<00:00, 1425.59it/s]

Bootstrapping recall:  86%|████████▌ | 861/1000 [00:00<00:00, 1425.92it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1426.16it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1425.65it/s]

Bootstrapping f1:  29%|██▊       | 287/1000 [00:00<00:00, 1428.22it/s]

Bootstrapping f1:  43%|████▎     | 431/1000 [00:00<00:00, 1429.19it/s]

Bootstrapping f1:  57%|█████▋    | 574/1000 [00:00<00:00, 1428.59it/s]

Bootstrapping f1:  72%|███████▏  | 717/1000 [00:00<00:00, 1429.04it/s]

Bootstrapping f1:  86%|████████▌ | 860/1000 [00:00<00:00, 1429.27it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1428.70it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 418/1000 [00:00<00:00, 4170.12it/s]

Bootstrapping accuracy:  84%|████████▎ | 836/1000 [00:00<00:00, 4173.05it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4171.33it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  20%|██        | 202/1000 [00:00<00:00, 2016.66it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 2024.97it/s]

Bootstrapping average_precision:  61%|██████    | 611/1000 [00:00<00:00, 2032.07it/s]

Bootstrapping average_precision:  82%|████████▏ | 815/1000 [00:00<00:00, 2033.70it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 2031.56it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:  12%|█▏        | 123/1000 [00:00<00:00, 1223.99it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 1225.25it/s]

Bootstrapping roc_auc:  37%|███▋      | 369/1000 [00:00<00:00, 1224.35it/s]

Bootstrapping roc_auc:  49%|████▉     | 492/1000 [00:00<00:00, 1224.28it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 1226.53it/s]

Bootstrapping roc_auc:  74%|███████▍  | 739/1000 [00:00<00:00, 1227.51it/s]

Bootstrapping roc_auc:  86%|████████▋ | 863/1000 [00:00<00:00, 1229.41it/s]

Bootstrapping roc_auc:  99%|█████████▊| 986/1000 [00:00<00:00, 1228.89it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1226.41it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  14%|█▍        | 143/1000 [00:00<00:00, 1421.74it/s]

Bootstrapping precision:  29%|██▊       | 286/1000 [00:00<00:00, 1425.67it/s]

Bootstrapping precision:  43%|████▎     | 429/1000 [00:00<00:00, 1427.58it/s]

Bootstrapping precision:  57%|█████▋    | 572/1000 [00:00<00:00, 1426.88it/s]

Bootstrapping precision:  72%|███████▏  | 715/1000 [00:00<00:00, 1427.09it/s]

Bootstrapping precision:  86%|████████▌ | 858/1000 [00:00<00:00, 1427.04it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1426.95it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  14%|█▍        | 144/1000 [00:00<00:00, 1430.18it/s]

Bootstrapping recall:  29%|██▉       | 289/1000 [00:00<00:00, 1436.28it/s]

Bootstrapping recall:  43%|████▎     | 434/1000 [00:00<00:00, 1439.70it/s]

Bootstrapping recall:  58%|█████▊    | 578/1000 [00:00<00:00, 1426.77it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1432.05it/s]

Bootstrapping recall:  87%|████████▋ | 868/1000 [00:00<00:00, 1435.87it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1434.33it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  14%|█▍        | 143/1000 [00:00<00:00, 1426.87it/s]

Bootstrapping f1:  29%|██▊       | 287/1000 [00:00<00:00, 1431.34it/s]

Bootstrapping f1:  43%|████▎     | 431/1000 [00:00<00:00, 1431.54it/s]

Bootstrapping f1:  57%|█████▊    | 575/1000 [00:00<00:00, 1430.26it/s]

Bootstrapping f1:  72%|███████▏  | 719/1000 [00:00<00:00, 1429.87it/s]

Bootstrapping f1:  86%|████████▋ | 863/1000 [00:00<00:00, 1430.93it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1430.95it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  42%|████▏     | 420/1000 [00:00<00:00, 4193.84it/s]

Bootstrapping accuracy:  84%|████████▍ | 840/1000 [00:00<00:00, 4195.74it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 4189.00it/s]

,Model,DAG,Year,# Features,# Biomarkers,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE
0,XGB,Control,All,521,28,"0.78 (0.75, 0.82)","0.92 (0.90, 0.93)","0.90 (0.88, 0.92)","0.80 (0.78, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.093
1,XGB,Control,2020,521,28,"0.79 (0.73, 0.85)","0.91 (0.88, 0.94)","0.91 (0.88, 0.94)","0.80 (0.76, 0.84)","0.84 (0.81, 0.87)","0.93 (0.92, 0.95)",0.113
2,XGB,Control,2021,521,28,"0.80 (0.74, 0.85)","0.93 (0.91, 0.96)","0.91 (0.88, 0.95)","0.80 (0.77, 0.84)","0.85 (0.81, 0.88)","0.95 (0.94, 0.96)",0.087
3,XGB,Control,2022,521,28,"0.80 (0.74, 0.86)","0.93 (0.89, 0.96)","0.90 (0.86, 0.94)","0.82 (0.78, 0.86)","0.86 (0.82, 0.89)","0.96 (0.95, 0.97)",0.086
4,XGB,Correlation,All,53,20,"0.75 (0.71, 0.78)","0.89 (0.87, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.83 (0.80, 0.85)","0.94 (0.93, 0.95)",0.114
5,XGB,Correlation,2020,53,20,"0.75 (0.69, 0.81)","0.89 (0.85, 0.92)","0.88 (0.84, 0.91)","0.76 (0.72, 0.80)","0.80 (0.76, 0.84)","0.92 (0.90, 0.93)",0.131
6,XGB,Correlation,2021,53,20,"0.76 (0.69, 0.82)","0.89 (0.86, 0.93)","0.92 (0.89, 0.95)","0.80 (0.76, 0.84)","0.85 (0.81, 0.88)","0.95 (0.94, 0.96)",0.109
7,XGB,Correlation,2022,53,20,"0.78 (0.72, 0.84)","0.91 (0.87, 0.94)","0.93 (0.90, 0.96)","0.82 (0.78, 0.86)","0.87 (0.83, 0.90)","0.96 (0.95, 0.97)",0.106
8,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,All,150,8,"0.76 (0.73, 0.80)","0.91 (0.89, 0.93)","0.90 (0.88, 0.92)","0.79 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.104
9,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2020,150,8,"0.78 (0.72, 0.83)","0.90 (0.87, 0.93)","0.92 (0.89, 0.95)","0.80 (0.75, 0.83)","0.84 (0.80, 0.87)","0.93 (0.92, 0.95)",0.121
10,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2021,150,8,"0.77 (0.71, 0.83)","0.92 (0.89, 0.95)","0.89 (0.85, 0.92)","0.78 (0.74, 0.83)","0.82 (0.79, 0.86)","0.94 (0.93, 0.95)",0.097
11,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2022,150,8,"0.78 (0.71, 0.84)","0.92 (0.88, 0.95)","0.90 (0.87, 0.94)","0.82 (0.78, 0.86)","0.85 (0.82, 0.89)","0.96 (0.95, 0.97)",0.096
12,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,All,223,12,"0.76 (0.73, 0.80)","0.91 (0.89, 0.93)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.100
13,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2020,223,12,"0.76 (0.70, 0.82)","0.90 (0.87, 0.93)","0.90 (0.86, 0.93)","0.78 (0.74, 0.82)","0.82 (0.78, 0.86)","0.93 (0.91, 0.94)",0.116
14,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2021,223,12,"0.79 (0.74, 0.85)","0.92 (0.89, 0.95)","0.91 (0.88, 0.94)","0.81 (0.77, 0.85)","0.85 (0.81, 0.88)","0.95 (0.94, 0.96)",0.096
15,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,2022,223,12,"0.79 (0.73, 0.85)","0.92 (0.89, 0.95)","0.90 (0.87, 0.94)","0.81 (0.76, 0.85)","0.85 (0.81, 0.88)","0.96 (0.94, 0.97)",0.092
16,XGB,Simplified Golem $\cup$ Simplified PCMB,All,223,12,"0.77 (0.73, 0.80)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.098
17,XGB,Simplified Golem $\cup$ Simplified PCMB,2020,223,12,"0.77 (0.71, 0.82)","0.90 (0.87, 0.93)","0.93 (0.91, 0.96)","0.78 (0.74, 0.82)","0.84 (0.80, 0.87)","0.93 (0.92, 0.95)",0.115
18,XGB,Simplified Golem $\cup$ Simplified PCMB,2021,223,12,"0.79 (0.73, 0.84)","0.93 (0.90, 0.95)","0.91 (0.88, 0.95)","0.79 (0.75, 0.84)","0.84 (0.80, 0.88)","0.95 (0.94, 0.96)",0.092
19,XGB,Simplified Golem $\cup$ Simplified PCMB,2022,223,12,"0.79 (0.73, 0.85)","0.93 (0.89, 0.96)","0.90 (0.86, 0.94)","0.81 (0.76, 0.85)","0.84 (0.81, 0.88)","0.95 (0.94, 0.97)",0.092
20,XGB,Simplified Clinician Consensus,All,112,6,"0.73 (0.70, 0.77)","0.90 (0.88, 0.92)","0.90 (0.87, 0.92)","0.76 (0.74, 0.79)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.104
21,XGB,Simplified Clinician Consensus,2020,112,6,"0.75 (0.69, 0.80)","0.89 (0.86, 0.92)","0.88 (0.84, 0.91)","0.77 (0.73, 0.81)","0.81 (0.77, 0.84)","0.92 (0.90, 0.94)",0.125
22,XGB,Simplified Clinician Consensus,2021,112,6,"0.74 (0.67, 0.80)","0.90 (0.86, 0.93)","0.90 (0.86, 0.94)","0.77 (0.73, 0.81)","0.82 (0.78, 0.85)","0.94 (0.93, 0.95)",0.098
23,XGB,Simplified Clinician Consensus,2022,112,6,"0.76 (0.70, 0.83)","0.92 (0.88, 0.95)","0.92 (0.89, 0.95)","0.79 (0.74, 0.83)","0.84 (0.80, 0.87)","0.96 (0.94, 0.97)",0.094
24,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,All,93,5,"0.73 (0.69, 0.76)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.75, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.108
25,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2020,93,5,"0.75 (0.69, 0.81)","0.89 (0.86, 0.92)","0.88 (0.84, 0.91)","0.78 (0.74, 0.82)","0.82 (0.78, 0.85)","0.92 (0.91, 0.94)",0.129
26,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2021,93,5,"0.71 (0.64, 0.77)","0.88 (0.85, 0.91)","0.89 (0.85, 0.93)","0.77 (0.73, 0.82)","0.82 (0.78, 0.86)","0.94 (0.93, 0.95)",0.102
27,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2022,93,5,"0.77 (0.71, 0.83)","0.91 (0.88, 0.94)","0.93 (0.89, 0.96)","0.80 (0.76, 0.84)","0.85 (0.81, 0.88)","0.96 (0.95, 0.97)",0.097
28,XGB,Simplified PCMB,All,131,7,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.89 (0.87, 0.91)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.104
29,XGB,Simplified PCMB,2020,131,7,"0.76 (0.69, 0.81)","0.89 (0.86, 0.92)","0.88 (0.84, 0.92)","0.78 (0.74, 0.82)","0.82 (0.79, 0.85)","0.93 (0.91, 0.94)",0.122
30,XGB,Simplified PCMB,2021,131,7,"0.79 (0.73, 0.84)","0.93 (0.90, 0.95)","0.90 (0.86, 0.93)","0.79 (0.75, 0.83)","0.83 (0.80, 0.87)","0.95 (0.93, 0.96)",0.096
31,XGB,Simplified PCMB,2022,131,7,"0.80 (0.73, 0.85)","0.91 (0.87, 0.95)","0.91 (0.87, 0.95)","0.83 (0.79, 0.87)","0.87 (0.83, 0.90)","0.96 (0.95, 0.97)",0.096
32,XGB,Simplified Golem,All,149,8,"0.76 (0.72, 0.79)","0.91 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102
33,XGB,Simplified Golem,2020,149,8,"0.74 (0.68, 0.80)","0.89 (0.86, 0.92)","0.88 (0.84, 0.92)","0.76 (0.72, 0.80)","0.81 (0.77, 0.84)","0.92 (0.90, 0.94)",0.121
34,XGB,Simplified Golem,2021,149,8,"0.79 (0.73, 0.84)","0.92 (0.89, 0.95)","0.91 (0.88, 0.95)","0.81 (0.77, 0.85)","0.85 (0.82, 0.88)","0.95 (0.94, 0.96)",0.096
35,XGB,Simplified Golem,2022,149,8,"0.81 (0.75, 0.87)","0.94 (0.90, 0.97)","0.90 (0.87, 0.94)","0.82 (0.78, 0.86)","0.86 (0.82, 0.89)","0.96 (0.95, 0.97)",0.095
36,XGB,Simplified Golem $\cap$ Simplified PCMB,All,57,3,"0.71 (0.68, 0.75)","0.89 (0.87, 0.91)","0.86 (0.84, 0.89)","0.77 (0.75, 0.80)","0.81 (0.79, 0.83)","0.93 (0.93, 0.94)",0.113
37,XGB,Simplified Golem $\cap$ Simplified PCMB,2020,57,3,"0.74 (0.67, 0.80)","0.88 (0.84, 0.91)","0.89 (0.85, 0.93)","0.77 (0.73, 0.81)","0.82 (0.78, 0.85)","0.92 (0.91, 0.94)",0.126
38,XGB,Simplified Golem $\cap$ Simplified PCMB,2021,57,3,"0.72 (0.65, 0.79)","0.91 (0.88, 0.94)","0.87 (0.83, 0.91)","0.78 (0.74, 0.82)","0.82 (0.78, 0.85)","0.94 (0.93, 0.95)",0.107
39,XGB,Simplified Golem $\cap$ Simplified PCMB,2022,57,3,"0.73 (0.66, 0.80)","0.90 (0.86, 0.94)","0.85 (0.81, 0.89)","0.80 (0.75, 0.84)","0.82 (0.78, 0.86)","0.95 (0.93, 0.96)",0.108
40,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,All,38,2,"0.66 (0.62, 0.70)","0.86 (0.84, 0.88)","0.85 (0.82, 0.87)","0.74 (0.72, 0.76)","0.78 (0.76, 0.80)","0.93 (0.92, 0.93)",0.116
41,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2020,38,2,"0.70 (0.62, 0.76)","0.87 (0.83, 0.90)","0.87 (0.82, 0.90)","0.74 (0.70, 0.78)","0.79 (0.75, 0.82)","0.91 (0.90, 0.93)",0.129
42,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2021,38,2,"0.66 (0.59, 0.73)","0.86 (0.82, 0.90)","0.84 (0.79, 0.88)","0.73 (0.69, 0.77)","0.77 (0.73, 0.81)","0.93 (0.91, 0.94)",0.111
43,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,2022,38,2,"0.66 (0.59, 0.74)","0.88 (0.84, 0.91)","0.83 (0.78, 0.87)","0.76 (0.72, 0.80)","0.79 (0.75, 0.83)","0.94 (0.93, 0.95)",0.110

In [17]:
# Skill-score and AUCNPR point estimates for the vitals & labs model (reuses helpers above)
summary_vl = results_df_vl.copy()
summary_vl['Normalized AUPRC'] = summary_vl.apply(
    lambda r: normalize_auprc(r['Average Precision'], prevalence[r['Year']]), axis=1)

def aucnpr_point(auprc_str, pi):
    """AUCNPR point estimate from an AUPRC CI string (Boyd et al. 2012)."""
    return (extract_point(auprc_str) - aucpr_min(pi)) / (1 - aucpr_min(pi))

summary_vl['AUCNPR']               = summary_vl.apply(lambda r: aucnpr_point(r['Average Precision'], prevalence[r['Year']]), axis=1)
summary_vl['Average Precision_pt'] = summary_vl['Average Precision'].apply(extract_point)
summary_vl['AUROC_pt']             = summary_vl['AUROC'].apply(extract_point)

cols_to_save = ['DAG', 'Year', 'Average Precision', 'Normalized AUPRC', 'AUROC',
                'Precision', 'Recall', 'F1 Score', 'Accuracy', 'ECE', '# Features', '# Biomarkers']
summary_vl[cols_to_save].to_csv('biomarker_counts_fixed/Year Sensitivity - Vitals Labs - Normalized.csv', index=False)

# Table 1: Raw AUPRC + AUCNPR, wide by year, ordered by AUCNPR on the full test set
raw_piv = summary_vl.pivot_table(index='DAG', columns='Year', values='Average Precision_pt')
npr_piv = summary_vl.pivot_table(index='DAG', columns='Year', values='AUCNPR')
raw_piv.columns = [f'AUPRC_{c}'  for c in raw_piv.columns]
npr_piv.columns = [f'AUCNPR_{c}' for c in npr_piv.columns]
table1_vl = pd.concat([raw_piv, npr_piv], axis=1).sort_values('AUCNPR_All', ascending=False)
table1_vl.to_csv('biomarker_counts_fixed/Year Sensitivity - Vitals Labs - Table1 AUPRC AUCNPR.csv')
table1_vl.round(3)

,AUPRC_2020,AUPRC_2021,AUPRC_2022,AUPRC_All,AUCNPR_2020,AUCNPR_2021,AUCNPR_2022,AUCNPR_All
DAG,,,,,,,,
Control,0.79,0.80,0.80,0.78,0.773,0.789,0.790,0.767
Simplified Golem $\cup$ Simplified PCMB,0.77,0.79,0.79,0.77,0.752,0.778,0.780,0.756
Simplified Clinician Consensus $\cup$ Simplified Golem,0.76,0.79,0.79,0.76,0.741,0.778,0.780,0.745
Simplified Clinician Consensus $\cup$ Simplified PCMB,0.78,0.77,0.78,0.76,0.763,0.757,0.769,0.745
Simplified Golem,0.74,0.79,0.81,0.76,0.719,0.778,0.801,0.745
Simplified PCMB,0.76,0.79,0.80,0.76,0.741,0.778,0.790,0.745
Correlation,0.75,0.76,0.78,0.75,0.730,0.746,0.769,0.735
Simplified Clinician Consensus,0.75,0.74,0.76,0.73,0.730,0.725,0.748,0.714
Simplified Clinician Consensus $\cap$ Simplified PCMB,0.75,0.71,0.77,0.73,0.730,0.693,0.759,0.714
Simplified Golem $\cap$ Simplified PCMB,0.74,0.72,0.73,0.71,0.719,0.704,0.717,0.692
Simplified Clinician Consensus $\cap$ Simplified Golem,0.70,0.66,0.66,0.66,0.676,0.641,0.643,0.639

In [18]:
# Raw AUPRC / AUROC permutation test — vitals & labs model
perm_rows_vl = []
for dag_name, year_preds in preds_by_dag_vl.items():
    for yr_A, yr_B in year_pairs:
        y_true_A, y_prob_A = year_preds[yr_A]
        y_true_B, y_prob_B = year_preds[yr_B]

        for metric_str, metric_label in [('average_precision', 'AUPRC'),
                                          ('roc_auc',           'AUROC')]:
            obs_A, obs_B, obs_diff, p_value = permutation_test_across_years(
                y_true_A, y_prob_A, y_true_B, y_prob_B,
                metric_str=metric_str, n_permutations=1000, random_state=42,
            )
            perm_rows_vl.append({
                'DAG':        dag_name,
                'Metric':     metric_label,
                'Year A':     yr_A,
                'Year B':     yr_B,
                f'{metric_label} (A)': round(obs_A, 3),
                f'{metric_label} (B)': round(obs_B, 3),
                '|Δ|':        round(obs_diff, 3),
                'p-value':    round(p_value, 3),
                'Significant (p<0.05)': p_value < 0.05,
            })

perm_df_vl = pd.DataFrame(perm_rows_vl)
perm_df_vl.to_csv('biomarker_counts_fixed/Year Sensitivity - Vitals Labs - Permutation Tests.csv', index=False)
for metric_label in ['AUPRC', 'AUROC']:
    sub = perm_df_vl[perm_df_vl['Metric'] == metric_label]
    print(f"{metric_label}: {int(sub['Significant (p<0.05)'].sum())} / {len(sub)} comparisons significant (p < 0.05)")
perm_df_vl

AUPRC: 0 / 33 comparisons significant (p < 0.05)
AUROC: 1 / 33 comparisons significant (p < 0.05)

,DAG,Metric,Year A,Year B,AUPRC (A),AUPRC (B),|Δ|,p-value,Significant (p<0.05),AUROC (A),AUROC (B)
0,Control,AUPRC,2020,2021,0.794,0.798,0.004,0.925,False,NaN,NaN
1,Control,AUROC,2020,2021,NaN,NaN,0.026,0.214,False,0.908,0.934
2,Control,AUPRC,2020,2022,0.794,0.801,0.007,0.854,False,NaN,NaN
3,Control,AUROC,2020,2022,NaN,NaN,0.018,0.391,False,0.908,0.927
4,Control,AUPRC,2021,2022,0.798,0.801,0.003,0.941,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
61,Simplified Clinician Consensus $\cap$ Simplifi...,AUROC,2020,2021,NaN,NaN,0.006,0.829,False,0.868,0.862
62,Simplified Clinician Consensus $\cap$ Simplifi...,AUPRC,2020,2022,0.696,0.662,0.034,0.523,False,NaN,NaN
63,Simplified Clinician Consensus $\cap$ Simplifi...,AUROC,2020,2022,NaN,NaN,0.009,0.750,False,0.868,0.877
64,Simplified Clinician Consensus $\cap$ Simplifi...,AUPRC,2021,2022,0.665,0.662,0.003,0.953,False,NaN,NaN
65,Simplified Clinician Consensus $\cap$ Simplifi...,AUROC,2021,2022,NaN,NaN,0.015,0.577,False,0.862,0.877

In [19]:
# AUCNPR (prevalence-normalized) permutation test — vitals & labs model
perm_npr_rows_vl = []
for dag_name, year_preds in preds_by_dag_vl.items():
    for yr_A, yr_B in year_pairs:
        y_true_A, y_prob_A = year_preds[yr_A]
        y_true_B, y_prob_B = year_preds[yr_B]

        obs_A, obs_B, obs_diff, p_value = permutation_test_aucnpr_across_years(
            y_true_A, y_prob_A, prevalence[yr_A],
            y_true_B, y_prob_B, prevalence[yr_B],
            n_permutations=1000, random_state=42,
        )
        perm_npr_rows_vl.append({
            'DAG':        dag_name,
            'Metric':     'AUCNPR',
            'Year A':     yr_A,
            'Year B':     yr_B,
            'AUCNPR (A)': round(obs_A, 3),
            'AUCNPR (B)': round(obs_B, 3),
            '|Δ|':        round(obs_diff, 3),
            'p-value':    round(p_value, 3),
            'Significant (p<0.05)': p_value < 0.05,
        })

perm_npr_df_vl = pd.DataFrame(perm_npr_rows_vl)
perm_npr_df_vl.to_csv('biomarker_counts_fixed/Year Sensitivity - Vitals Labs - Permutation AUCNPR.csv', index=False)

n_sig = int(perm_npr_df_vl['Significant (p<0.05)'].sum())
print(f"AUCNPR: {n_sig} / {len(perm_npr_df_vl)} comparisons significant (p < 0.05)")
perm_npr_df_vl

AUCNPR: 0 / 33 comparisons significant (p < 0.05)

,DAG,Metric,Year A,Year B,AUCNPR (A),AUCNPR (B),|Δ|,p-value,Significant (p<0.05)
0,Control,AUCNPR,2020,2021,0.777,0.786,0.009,0.843,False
1,Control,AUCNPR,2020,2022,0.777,0.791,0.014,0.759,False
2,Control,AUCNPR,2021,2022,0.786,0.791,0.005,0.920,False
3,Correlation,AUCNPR,2020,2021,0.730,0.743,0.013,0.788,False
4,Correlation,AUCNPR,2020,2022,0.730,0.770,0.040,0.399,False
5,Correlation,AUCNPR,2021,2022,0.743,0.770,0.027,0.582,False
6,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2020,2021,0.760,0.762,0.002,0.964,False
7,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2020,2022,0.760,0.770,0.010,0.846,False
8,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2021,2022,0.762,0.770,0.008,0.856,False
9,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2020,2021,0.744,0.781,0.037,0.426,False
10,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2020,2022,0.744,0.781,0.037,0.456,False
11,Simplified Clinician Consensus $\cup$ Simplifi...,AUCNPR,2021,2022,0.781,0.781,0.000,0.992,False
12,Simplified Golem $\cup$ Simplified PCMB,AUCNPR,2020,2021,0.749,0.779,0.030,0.529,False
13,Simplified Golem $\cup$ Simplified PCMB,AUCNPR,2020,2022,0.749,0.784,0.036,0.448,False
14,Simplified Golem $\cup$ Simplified PCMB,AUCNPR,2021,2022,0.779,0.784,0.006,0.901,False
15,Simplified Clinician Consensus,AUCNPR,2020,2021,0.727,0.725,0.002,0.961,False
16,Simplified Clinician Consensus,AUCNPR,2020,2022,0.727,0.751,0.024,0.627,False
17,Simplified Clinician Consensus,AUCNPR,2021,2022,0.725,0.751,0.026,0.589,False
18,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2020,2021,0.732,0.689,0.043,0.398,False
19,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2020,2022,0.732,0.763,0.031,0.516,False
20,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2021,2022,0.689,0.763,0.074,0.145,False
21,Simplified PCMB,AUCNPR,2020,2021,0.736,0.776,0.039,0.406,False
22,Simplified PCMB,AUCNPR,2020,2022,0.736,0.787,0.051,0.300,False
23,Simplified PCMB,AUCNPR,2021,2022,0.776,0.787,0.012,0.784,False
24,Simplified Golem,AUCNPR,2020,2021,0.721,0.773,0.052,0.282,False
25,Simplified Golem,AUCNPR,2020,2022,0.721,0.801,0.080,0.107,False
26,Simplified Golem,AUCNPR,2021,2022,0.773,0.801,0.028,0.539,False
27,Simplified Golem $\cap$ Simplified PCMB,AUCNPR,2020,2021,0.715,0.704,0.011,0.830,False
28,Simplified Golem $\cap$ Simplified PCMB,AUCNPR,2020,2022,0.715,0.718,0.004,0.956,False
29,Simplified Golem $\cap$ Simplified PCMB,AUCNPR,2021,2022,0.704,0.718,0.015,0.768,False
30,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2020,2021,0.672,0.646,0.026,0.660,False
31,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2020,2022,0.672,0.645,0.027,0.662,False
32,Simplified Clinician Consensus $\cap$ Simplifi...,AUCNPR,2021,2022,0.646,0.645,0.001,0.993,False