# DAG Parameterization
The goal of this notebook is to assess which of the graphs (DAGs or PAGs) we generated during our causal structure learning step produces the best predictive model.

In [1]:
# Data manipulation and plotting
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import re
import glob

# Bayesian Networks
from pgmpy.models import LinearGaussianBayesianNetwork

# Metrics
from sklearn.calibration import calibration_curve
from pycalib.metrics import ECE

import xgboost
import shap

/Users/eddie/.pixi-envs/dag-parameterization-2248481784431669736/envs/default/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Data preparation

In [2]:
# Load training data
X_train = pd.read_csv('../../Data Pre-processing/X_train_c12_w48_imp.csv', index_col=0)
X_test = pd.read_csv('../../Data Pre-processing/X_test_c12_w48_imp.csv', index_col=0)

print(X_train.shape, X_test.shape)

#Remove features with 0 variance
X_train = X_train.loc[:, X_train.var() >= 0.01]
X_test = X_test.filter(items=X_train.columns) # Keep only columns in X_train
print(X_train.shape, X_test.shape)

# # Impute missing values using Iterative Imputer (Linear Gaussian BN can't handle missing values)
# imputer = IterativeImputer(random_state=42, max_iter=100)
# X_train_imp = pd.DataFrame(imputer.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
# X_test_imp = pd.DataFrame(imputer.transform(X_test), columns=X_test.columns, index=X_test.index)

X_train_imp = pd.read_csv('../../Data Pre-processing/X_train_c12_w48_mice.csv', index_col=0)
X_test_imp = pd.read_csv('../../Data Pre-processing/X_test_c12_w48_mice.csv', index_col=0)

y_train = pd.read_csv('../../Data Pre-processing/y_train_c12_w48_imp.csv', index_col=[0,1]).groupby('uid').max()
y_test = pd.read_csv('../../Data Pre-processing/y_test_c12_w48_imp.csv', index_col=[0,1]).groupby('uid').max()

# Correlation feature selection
correlation_threshold = 0.3
X_train_corr = X_train_imp.loc[:, X_train_imp.corrwith(y_train['Outcome']).abs() >= correlation_threshold]
print(X_train_corr.shape)

(13054, 990) (3895, 990)
(13054, 811) (3895, 811)

(13054, 113)

# Loading DAGs

In [3]:
#Get all adjacency files
adjacency_files = glob.glob("../DAGs/*_adjacency.csv")

dags = {}
dags['Control'] = nx.from_edgelist([(col, 'Outcome') for col in X_train_imp.columns.str.replace(r'(_.+)?$', '', regex=True).unique().tolist() if col != 'Outcome'], create_using=nx.DiGraph())
dags['Correlation'] = nx.from_edgelist([(col, 'Outcome') for col in X_train_corr.columns.str.replace(r'(_.+)?$', '', regex=True).unique().tolist() if col != 'Outcome'], create_using=nx.DiGraph())
for file in adjacency_files:
    dag_name = re.search(r'../DAGs/(.*)_adjacency.csv', file).group(1)
    dag_name = re.sub(r'(?<![a-zA-Z])x(?![a-zA-Z])', lambda _: '$\\cap$', dag_name)
    dag_name = dag_name.replace(' + ', ' $\\cup$ ')
    dags[dag_name] = nx.DiGraph(pd.read_csv(file, index_col=0))

dags.pop('Golem $\\cap$ PCMB')  # Remove problematic DAG (has 0 nodes associated with Outcome)
list(dags.keys())

['Control',
 'Correlation',
 'Clinician Consensus $\\cup$ Golem',
 'Simplified Clinician Consensus $\\cup$ Simplified PCMB',
 'Simplified Clinician Consensus $\\cup$ Simplified Golem',
 'Clinician Consensus $\\cup$ PCMB',
 'Simplified Golem $\\cup$ Simplified PCMB',
 'Clinician Consensus',
 'Simplified Clinician Consensus',
 'Clinician Consensus $\\cap$ PCMB',
 'Golem',
 'PCMB',
 'Simplified Clinician Consensus $\\cap$ Simplified PCMB',
 'Simplified PCMB',
 'Clinician Consensus $\\cap$ Golem',
 'Simplified Golem',
 'Golem $\\cup$ PCMB',
 'Simplified Golem $\\cap$ Simplified PCMB',
 'Simplified Clinician Consensus $\\cap$ Simplified Golem']

In [4]:
list(dags['Simplified Golem'].nodes())

['Outcome',
 'Weight',
 'SpO2',
 'Creatinine',
 'Peds Coma Score',
 'Blood urea nitrogen',
 'Dopamine',
 'Sodium',
 'PTT',
 'Ventilated',
 'Potassium',
 'DBP']

# Model Training Functions
For each dag we train a Linear Gaussian Bayesian Network, an XGBoost

In [5]:
from MLstatkit import Bootstrapping, Delong_test, Permutation_test
from itertools import combinations

def compare_models(y, y_prob1, y_prob2):
        # DeLong Test for AUROC
        z, p = Delong_test(y.values, y_prob1, y_prob2, return_ci=False, return_auc=False)
        metric_a, metric_b, p_value, benchmark, samples_mean, samples_std = Permutation_test(y.values, y_prob1, y_prob2, metric_str='average_precision')
        return (z, p), (metric_a, metric_b, p_value, benchmark, samples_mean, samples_std)

def performance_report(X, y, model):
    try:
        y_prob = model.predict_proba(X)[:, 1] # Predict on test data
    except AttributeError:
        y_prob = model.predict(X)['Outcome'].to_numpy() # Predict on test data (LGBN fallback: pgmpy 1.x returns DataFrame w/ Outcome conditional mean)
        y_prob = np.where(y_prob > 1, 1, np.where(y_prob < 0, 0, y_prob))

    ## Calculate Performance Metrics with Bootstrapping
    n_bootstraps = 1000
    # Average Precision
    ap, ap_lower, ap_upper = Bootstrapping(y.values, y_prob, metric_str='average_precision', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # AUROC
    auroc, auroc_lower, auroc_upper = Bootstrapping(y.values, y_prob, metric_str='roc_auc', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # Precision 
    precision, precision_lower, precision_upper = Bootstrapping(y.values, y_prob, metric_str='precision', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # Recall
    recall, recall_lower, recall_upper = Bootstrapping(y.values, y_prob, metric_str='recall', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # F1 Score
    f1, f1_lower, f1_upper = Bootstrapping(y.values, y_prob, metric_str='f1', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # Accuracy
    accuracy, accuracy_lower, accuracy_upper = Bootstrapping(y.values, y_prob, metric_str='accuracy', n_bootstraps=n_bootstraps, confidence_level=0.95, random_state=4242)
    # ECE
    ece = ECE(y.values, y_prob.reshape(-1, 1), bins=50)

    return {'Average Precision': f"{ap:.2f} ({ap_lower:.2f}, {ap_upper:.2f})",
     'AUROC': f"{auroc:.2f} ({auroc_lower:.2f}, {auroc_upper:.2f})",
     'Precision': f"{precision:.2f} ({precision_lower:.2f}, {precision_upper:.2f})",
     'Recall': f"{recall:.2f} ({recall_lower:.2f}, {recall_upper:.2f})",
     'F1 Score': f"{f1:.2f} ({f1_lower:.2f}, {f1_upper:.2f})",
     'Accuracy': f"{accuracy:.2f} ({accuracy_lower:.2f}, {accuracy_upper:.2f})",
     'ECE': f"{ece:.3f}"}

def train_models(remove_drugs=False, remove_interventions=False):
        results = []
        shap_values = {}
        calibrations = {}
        model_preds = {}
        drugs = ['Midazolam', 'Fentanyl', 'Olanzapine', 'Haloperidol', 
                'Dexmedetomidine', 'Lorazepam', 'Morphine', 'Hydromorphone', 
                'Dopamine', 'Cisatracurium', 'Epinephrine', 'Norepinephrine', 
                'Milrinone', 'Dobutamine']
        

        for dag_name, dag in dags.items():
        
                # Simplified is not in the dag_name, skip
                if 'Simplified' not in dag_name and dag_name not in ['Control', 'Correlation']:
                        continue


                if dag is not None:
                        print(f"Processing {dag_name} with {dag.number_of_nodes()} nodes and {dag.number_of_edges()} edges")

                nodes_in_dag = list(dag.nodes())

                if 'Simplified' in dag_name or dag_name in ['Control', 'Correlation']:
                        if remove_drugs:
                                for drug in drugs:
                                        if drug in nodes_in_dag:
                                                nodes_in_dag.remove(drug)
                
                        if remove_interventions:
                                intervention_nodes = ['CRRT Therapy Type', 'ECMO Type', 'Ventilated', 'Pupillary Reaction', 'Peds Coma Score', 'Endotracheal tube']
                                for intervention in intervention_nodes:
                                        if intervention in nodes_in_dag:
                                                nodes_in_dag.remove(intervention)

                        if dag_name == 'Correlation':
                                features_in_dag = [col for col in X_train_corr.columns if any(re.search(rf'^{re.escape(node)}(_.+)?$', col) for node in nodes_in_dag)]
                        else:
                                features_in_dag = [col for col in X_train_imp.columns if any(re.search(rf'^{re.escape(node)}(_.+)?$', col) for node in nodes_in_dag)]

                        train_dag = nx.DiGraph()

                        # Map DAG nodes to features
                        for node in nodes_in_dag:
                                ends = list(dag.successors(node))
                                from_features = [col for col in features_in_dag + ['Outcome'] if re.search(rf'^{re.escape(node)}(_.+)?$', col)]
                                to_features = [col for col in features_in_dag + ['Outcome'] if any(re.search(rf'^{re.escape(end)}(_.+)?$', col) for end in ends)]
                                for from_feature in from_features:
                                        for to_feature in to_features:
                                                train_dag.add_edge(from_feature, to_feature)
                        
                        n_biomarkers = len(nodes_in_dag) - 1  # Exclude Outcome
                else:
                        # Use list comprehensions to avoid mutating nodes_in_dag while iterating
                        if remove_drugs:
                                nodes_in_dag = [node for node in nodes_in_dag if not any(drug in node for drug in drugs)]
                        if remove_interventions:
                                intervention_nodes = ['CRRT Therapy Type', 'ECMO Type', 'Ventilated', 'Pupillary Reaction', 'Peds Coma Score', 'Endotracheal tube']
                                nodes_in_dag = [node for node in nodes_in_dag if not any(intervention in node for intervention in intervention_nodes)]
                        
                        features_in_dag = X_train_imp.filter(items=nodes_in_dag).columns.tolist()
                        train_dag = dag.subgraph(features_in_dag + ['Outcome']).copy()
                        n_biomarkers = X_train_imp.filter(items=nodes_in_dag).columns.str.replace(r'(_.+)?$', '', regex=True).nunique() - 1  # Exclude Outcome

                # XGB trains on non-imputed X_train; restrict to columns actually present there
                xgb_features = [f for f in features_in_dag if f in X_train.columns]

                models = {}
                # Instantiate Models
                models['LGBN'] = LinearGaussianBayesianNetwork(train_dag.edges())
                # models['LR'] = LogisticRegression(max_iter=1000, random_state=42)
                models['XGB'] = xgboost.XGBClassifier(objective='binary:logistic', random_state=42, eval_metric='aucpr')
                

                for model_name, model in models.items():
                        metrics = {}
                        metrics['Model'] = model_name
                        metrics['DAG'] = dag_name

                        if model_name == 'LGBN':
                                # Fit the model
                                train = pd.concat([X_train_imp.filter(features_in_dag), y_train.filter(['Outcome']).astype(int)], axis=1)
                                model.fit(train)
                                metrics.update(performance_report(X_test_imp.filter(features_in_dag), y_test.Outcome, model))
                                metrics['# Features'] = len(features_in_dag)
                        elif model_name == 'LR':
                                model.fit(X_train_imp.filter(features_in_dag), y_train.Outcome)
                                model_preds[dag_name] = model.predict_proba(X_test_imp.filter(features_in_dag))[:, 1]
                                metrics.update(performance_report(X_test_imp.filter(features_in_dag), y_test.Outcome, model))
                                metrics['# Features'] = len(features_in_dag)
                        else:
                                X_train_filtered = X_train.filter(xgb_features)
                                X_test_filtered = X_test.filter(xgb_features)
                                model.fit(X_train_filtered, y_train.Outcome)
                                y_prob = model.predict_proba(X_test_filtered)[:, 1]
                                model_preds[dag_name] = y_prob
                                metrics.update(performance_report(X_test_filtered, y_test.Outcome, model))
                                calibrations[dag_name] = calibration_curve(y_test.Outcome, y_prob, n_bins=50)
                                metrics['# Features'] = len(xgb_features)

                        metrics['# Biomarkers'] = n_biomarkers

                        results.append(metrics)


                # SHAP feature importance
                X_test_shap = X_test.filter(xgb_features)
                explainer = shap.TreeExplainer(models['XGB'])
                values = explainer.shap_values(X_test_shap)
                values = pd.DataFrame(values, columns=X_test_shap.columns, index=X_test_shap.index)
                shap_values[dag_name] = values
        

        return results, shap_values, calibrations, model_preds

In [6]:
def shap_values_biomarker_summary(shap_values):
    vals = {} 
    for dag_name in shap_values:
        df = shap_values[dag_name].reset_index().melt(id_vars='uid')
        df.variable = df.variable.str.replace(r'(_.+)?$', '', regex=True)
        df.value = df.value.abs()                                   # abs before summing to prevent sign cancellation
        df = df.groupby(['uid', 'variable']).sum().reset_index()
        df = df.groupby('variable').value.mean().sort_values(ascending=True)
        vals[dag_name] = df
    return vals

# Model Training

## Bootstrapping
We simulate the potential performance of our models on an out of distribution dataset by performing a weighted bootstrap of our Test set. <br>
For context, our test set is already based on prospective samples. The training set comes from patients admitted up to 2019 and the test set is from patient admitted on or after 2020.

## Expriment 1: Comparing Feature Selection Approaches (DAGs)

In [7]:
results, shap_values, calibrations, model_preds = train_models(remove_drugs=False, remove_interventions=False)

Processing Control with 46 nodes and 45 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 130/1000 [00:00<00:00, 1291.92it/s]

Bootstrapping average_precision:  26%|██▋       | 264/1000 [00:00<00:00, 1317.56it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1357.16it/s]

Bootstrapping average_precision:  54%|█████▍    | 541/1000 [00:00<00:00, 1356.18it/s]

Bootstrapping average_precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1348.19it/s]

Bootstrapping average_precision:  81%|████████  | 812/1000 [00:00<00:00, 1321.43it/s]

Bootstrapping average_precision:  95%|█████████▌| 950/1000 [00:00<00:00, 1339.47it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1341.09it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 92/1000 [00:00<00:01, 907.15it/s]

Bootstrapping roc_auc:  18%|█▊        | 183/1000 [00:00<00:00, 893.07it/s]

Bootstrapping roc_auc:  27%|██▋       | 273/1000 [00:00<00:00, 891.56it/s]

Bootstrapping roc_auc:  37%|███▋      | 366/1000 [00:00<00:00, 901.92it/s]

Bootstrapping roc_auc:  46%|████▌     | 457/1000 [00:00<00:00, 900.15it/s]

Bootstrapping roc_auc:  55%|█████▍    | 548/1000 [00:00<00:00, 898.49it/s]

Bootstrapping roc_auc:  64%|██████▍   | 638/1000 [00:00<00:00, 889.55it/s]

Bootstrapping roc_auc:  73%|███████▎  | 727/1000 [00:00<00:00, 876.49it/s]

Bootstrapping roc_auc:  82%|████████▏ | 815/1000 [00:00<00:00, 871.42it/s]

Bootstrapping roc_auc:  90%|█████████ | 903/1000 [00:01<00:00, 869.98it/s]

Bootstrapping roc_auc:  99%|█████████▉| 992/1000 [00:01<00:00, 874.28it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 882.83it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 110/1000 [00:00<00:00, 1099.14it/s]

Bootstrapping precision:  22%|██▏       | 221/1000 [00:00<00:00, 1101.40it/s]

Bootstrapping precision:  34%|███▍      | 338/1000 [00:00<00:00, 1129.77it/s]

Bootstrapping precision:  45%|████▌     | 454/1000 [00:00<00:00, 1140.43it/s]

Bootstrapping precision:  57%|█████▋    | 571/1000 [00:00<00:00, 1147.72it/s]

Bootstrapping precision:  69%|██████▊   | 686/1000 [00:00<00:00, 1138.86it/s]

Bootstrapping precision:  80%|████████  | 805/1000 [00:00<00:00, 1152.85it/s]

Bootstrapping precision:  93%|█████████▎| 929/1000 [00:00<00:00, 1178.32it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1158.12it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1178.05it/s]

Bootstrapping recall:  24%|██▎       | 237/1000 [00:00<00:00, 1179.40it/s]

Bootstrapping recall:  36%|███▌      | 355/1000 [00:00<00:00, 1167.20it/s]

Bootstrapping recall:  47%|████▋     | 472/1000 [00:00<00:00, 1167.80it/s]

Bootstrapping recall:  59%|█████▉    | 591/1000 [00:00<00:00, 1174.96it/s]

Bootstrapping recall:  71%|███████▏  | 713/1000 [00:00<00:00, 1188.20it/s]

Bootstrapping recall:  83%|████████▎ | 832/1000 [00:00<00:00, 1188.59it/s]

Bootstrapping recall:  95%|█████████▌| 951/1000 [00:00<00:00, 1184.45it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1180.82it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 123/1000 [00:00<00:00, 1221.29it/s]

Bootstrapping f1:  25%|██▍       | 246/1000 [00:00<00:00, 1216.67it/s]

Bootstrapping f1:  37%|███▋      | 369/1000 [00:00<00:00, 1217.41it/s]

Bootstrapping f1:  49%|████▉     | 493/1000 [00:00<00:00, 1224.45it/s]

Bootstrapping f1:  62%|██████▏   | 619/1000 [00:00<00:00, 1236.40it/s]

Bootstrapping f1:  74%|███████▍  | 743/1000 [00:00<00:00, 1232.49it/s]

Bootstrapping f1:  87%|████████▋ | 867/1000 [00:00<00:00, 1214.86it/s]

Bootstrapping f1:  99%|█████████▉| 989/1000 [00:00<00:00, 1213.62it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1217.40it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 343/1000 [00:00<00:00, 3424.89it/s]

Bootstrapping accuracy:  69%|██████▊   | 686/1000 [00:00<00:00, 3427.59it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3459.81it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 130/1000 [00:00<00:00, 1292.42it/s]

Bootstrapping average_precision:  26%|██▌       | 260/1000 [00:00<00:00, 1293.51it/s]

Bootstrapping average_precision:  39%|███▉      | 390/1000 [00:00<00:00, 1295.70it/s]

Bootstrapping average_precision:  52%|█████▏    | 520/1000 [00:00<00:00, 1297.31it/s]

Bootstrapping average_precision:  65%|██████▌   | 653/1000 [00:00<00:00, 1307.56it/s]

Bootstrapping average_precision:  78%|███████▊  | 784/1000 [00:00<00:00, 1302.26it/s]

Bootstrapping average_precision:  92%|█████████▏| 915/1000 [00:00<00:00, 1295.15it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1297.52it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 834.36it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:01, 822.88it/s]

Bootstrapping roc_auc:  25%|██▌       | 251/1000 [00:00<00:00, 820.30it/s]

Bootstrapping roc_auc:  33%|███▎      | 334/1000 [00:00<00:00, 822.63it/s]

Bootstrapping roc_auc:  42%|████▏     | 417/1000 [00:00<00:00, 824.36it/s]

Bootstrapping roc_auc:  50%|█████     | 500/1000 [00:00<00:00, 821.50it/s]

Bootstrapping roc_auc:  58%|█████▊    | 584/1000 [00:00<00:00, 827.40it/s]

Bootstrapping roc_auc:  67%|██████▋   | 667/1000 [00:00<00:00, 821.26it/s]

Bootstrapping roc_auc:  75%|███████▌  | 750/1000 [00:00<00:00, 819.34it/s]

Bootstrapping roc_auc:  83%|████████▎ | 832/1000 [00:01<00:00, 815.16it/s]

Bootstrapping roc_auc:  92%|█████████▏| 916/1000 [00:01<00:00, 819.96it/s]

Bootstrapping roc_auc: 100%|█████████▉| 999/1000 [00:01<00:00, 800.81it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 814.95it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1138.60it/s]

Bootstrapping precision:  23%|██▎       | 234/1000 [00:00<00:00, 1170.67it/s]

Bootstrapping precision:  35%|███▌      | 352/1000 [00:00<00:00, 1169.03it/s]

Bootstrapping precision:  47%|████▋     | 469/1000 [00:00<00:00, 1151.11it/s]

Bootstrapping precision:  59%|█████▊    | 587/1000 [00:00<00:00, 1160.66it/s]

Bootstrapping precision:  70%|███████   | 704/1000 [00:00<00:00, 1152.77it/s]

Bootstrapping precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1154.51it/s]

Bootstrapping precision:  94%|█████████▎| 936/1000 [00:00<00:00, 1130.93it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1146.28it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1161.05it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1174.49it/s]

Bootstrapping recall:  35%|███▌      | 354/1000 [00:00<00:00, 1174.73it/s]

Bootstrapping recall:  47%|████▋     | 472/1000 [00:00<00:00, 1157.55it/s]

Bootstrapping recall:  59%|█████▉    | 589/1000 [00:00<00:00, 1161.13it/s]

Bootstrapping recall:  71%|███████   | 708/1000 [00:00<00:00, 1168.33it/s]

Bootstrapping recall:  82%|████████▎ | 825/1000 [00:00<00:00, 1144.62it/s]

Bootstrapping recall:  94%|█████████▍| 940/1000 [00:00<00:00, 1143.06it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1152.59it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 110/1000 [00:00<00:00, 1094.25it/s]

Bootstrapping f1:  23%|██▎       | 227/1000 [00:00<00:00, 1135.79it/s]

Bootstrapping f1:  35%|███▍      | 347/1000 [00:00<00:00, 1164.84it/s]

Bootstrapping f1:  46%|████▋     | 464/1000 [00:00<00:00, 1162.76it/s]

Bootstrapping f1:  58%|█████▊    | 581/1000 [00:00<00:00, 1144.17it/s]

Bootstrapping f1:  70%|██████▉   | 697/1000 [00:00<00:00, 1146.32it/s]

Bootstrapping f1:  82%|████████▏ | 816/1000 [00:00<00:00, 1157.36it/s]

Bootstrapping f1:  94%|█████████▎| 937/1000 [00:00<00:00, 1171.31it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1159.95it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3525.84it/s]

Bootstrapping accuracy:  72%|███████▏  | 715/1000 [00:00<00:00, 3580.44it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3526.33it/s]

Processing Correlation with 38 nodes and 37 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1322.46it/s]

Bootstrapping average_precision:  27%|██▋       | 266/1000 [00:00<00:00, 1322.58it/s]

Bootstrapping average_precision:  40%|███▉      | 399/1000 [00:00<00:00, 1318.88it/s]

Bootstrapping average_precision:  54%|█████▎    | 535/1000 [00:00<00:00, 1329.58it/s]

Bootstrapping average_precision:  67%|██████▋   | 672/1000 [00:00<00:00, 1340.17it/s]

Bootstrapping average_precision:  81%|████████  | 807/1000 [00:00<00:00, 1342.31it/s]

Bootstrapping average_precision:  94%|█████████▍| 942/1000 [00:00<00:00, 1329.58it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1327.85it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 82/1000 [00:00<00:01, 814.75it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 827.88it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 850.27it/s]

Bootstrapping roc_auc:  34%|███▍      | 340/1000 [00:00<00:00, 828.79it/s]

Bootstrapping roc_auc:  42%|████▏     | 423/1000 [00:00<00:00, 826.04it/s]

Bootstrapping roc_auc:  51%|█████     | 506/1000 [00:00<00:00, 823.76it/s]

Bootstrapping roc_auc:  59%|█████▉    | 589/1000 [00:00<00:00, 824.39it/s]

Bootstrapping roc_auc:  67%|██████▋   | 672/1000 [00:00<00:00, 822.21it/s]

Bootstrapping roc_auc:  76%|███████▌  | 755/1000 [00:00<00:00, 824.24it/s]

Bootstrapping roc_auc:  84%|████████▍ | 838/1000 [00:01<00:00, 815.16it/s]

Bootstrapping roc_auc:  92%|█████████▏| 921/1000 [00:01<00:00, 819.52it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 826.85it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 113/1000 [00:00<00:00, 1121.85it/s]

Bootstrapping precision:  23%|██▎       | 231/1000 [00:00<00:00, 1151.05it/s]

Bootstrapping precision:  35%|███▌      | 350/1000 [00:00<00:00, 1168.47it/s]

Bootstrapping precision:  47%|████▋     | 467/1000 [00:00<00:00, 1167.82it/s]

Bootstrapping precision:  59%|█████▉    | 588/1000 [00:00<00:00, 1181.69it/s]

Bootstrapping precision:  71%|███████   | 711/1000 [00:00<00:00, 1197.43it/s]

Bootstrapping precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1201.47it/s]

Bootstrapping precision:  95%|█████████▌| 954/1000 [00:00<00:00, 1205.43it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1185.96it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1189.79it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1172.86it/s]

Bootstrapping recall:  36%|███▌      | 356/1000 [00:00<00:00, 1173.41it/s]

Bootstrapping recall:  48%|████▊     | 475/1000 [00:00<00:00, 1177.80it/s]

Bootstrapping recall:  59%|█████▉    | 593/1000 [00:00<00:00, 1172.95it/s]

Bootstrapping recall:  71%|███████   | 712/1000 [00:00<00:00, 1171.80it/s]

Bootstrapping recall:  83%|████████▎ | 831/1000 [00:00<00:00, 1175.49it/s]

Bootstrapping recall:  95%|█████████▍| 949/1000 [00:00<00:00, 1175.97it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1174.32it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1199.43it/s]

Bootstrapping f1:  24%|██▍       | 241/1000 [00:00<00:00, 1203.93it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1192.74it/s]

Bootstrapping f1:  48%|████▊     | 482/1000 [00:00<00:00, 1169.09it/s]

Bootstrapping f1:  60%|██████    | 600/1000 [00:00<00:00, 1170.56it/s]

Bootstrapping f1:  72%|███████▏  | 718/1000 [00:00<00:00, 1146.60it/s]

Bootstrapping f1:  83%|████████▎ | 833/1000 [00:00<00:00, 1135.96it/s]

Bootstrapping f1:  95%|█████████▌| 950/1000 [00:00<00:00, 1145.49it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1160.40it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 353/1000 [00:00<00:00, 3518.32it/s]

Bootstrapping accuracy:  70%|███████   | 705/1000 [00:00<00:00, 3470.92it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3478.66it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 128/1000 [00:00<00:00, 1276.43it/s]

Bootstrapping average_precision:  26%|██▌       | 257/1000 [00:00<00:00, 1280.04it/s]

Bootstrapping average_precision:  39%|███▉      | 389/1000 [00:00<00:00, 1292.84it/s]

Bootstrapping average_precision:  52%|█████▏    | 519/1000 [00:00<00:00, 1291.01it/s]

Bootstrapping average_precision:  65%|██████▍   | 649/1000 [00:00<00:00, 1293.48it/s]

Bootstrapping average_precision:  78%|███████▊  | 779/1000 [00:00<00:00, 1273.01it/s]

Bootstrapping average_precision:  91%|█████████ | 908/1000 [00:00<00:00, 1276.85it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1284.08it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 858.40it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 863.18it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 853.41it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 836.51it/s]

Bootstrapping roc_auc:  43%|████▎     | 430/1000 [00:00<00:00, 830.98it/s]

Bootstrapping roc_auc:  51%|█████▏    | 514/1000 [00:00<00:00, 830.38it/s]

Bootstrapping roc_auc:  60%|█████▉    | 598/1000 [00:00<00:00, 818.03it/s]

Bootstrapping roc_auc:  68%|██████▊   | 680/1000 [00:00<00:00, 818.46it/s]

Bootstrapping roc_auc:  76%|███████▌  | 762/1000 [00:00<00:00, 814.46it/s]

Bootstrapping roc_auc:  84%|████████▍ | 845/1000 [00:01<00:00, 817.55it/s]

Bootstrapping roc_auc:  93%|█████████▎| 930/1000 [00:01<00:00, 826.85it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 828.87it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1195.69it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1157.43it/s]

Bootstrapping precision:  36%|███▌      | 356/1000 [00:00<00:00, 1153.98it/s]

Bootstrapping precision:  47%|████▋     | 474/1000 [00:00<00:00, 1161.79it/s]

Bootstrapping precision:  59%|█████▉    | 592/1000 [00:00<00:00, 1167.30it/s]

Bootstrapping precision:  71%|███████   | 709/1000 [00:00<00:00, 1148.56it/s]

Bootstrapping precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1142.54it/s]

Bootstrapping precision:  94%|█████████▍| 939/1000 [00:00<00:00, 1136.62it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1148.08it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1197.93it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1211.52it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1209.92it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1188.94it/s]

Bootstrapping recall:  60%|██████    | 605/1000 [00:00<00:00, 1163.85it/s]

Bootstrapping recall:  72%|███████▏  | 722/1000 [00:00<00:00, 1146.59it/s]

Bootstrapping recall:  84%|████████▎ | 837/1000 [00:00<00:00, 1144.68it/s]

Bootstrapping recall:  95%|█████████▌| 952/1000 [00:00<00:00, 1113.30it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1145.80it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1141.27it/s]

Bootstrapping f1:  23%|██▎       | 232/1000 [00:00<00:00, 1153.03it/s]

Bootstrapping f1:  35%|███▍      | 349/1000 [00:00<00:00, 1158.84it/s]

Bootstrapping f1:  47%|████▋     | 470/1000 [00:00<00:00, 1176.98it/s]

Bootstrapping f1:  59%|█████▉    | 588/1000 [00:00<00:00, 1158.53it/s]

Bootstrapping f1:  70%|███████   | 705/1000 [00:00<00:00, 1160.98it/s]

Bootstrapping f1:  82%|████████▏ | 822/1000 [00:00<00:00, 1158.48it/s]

Bootstrapping f1:  94%|█████████▍| 941/1000 [00:00<00:00, 1167.26it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1163.17it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3547.47it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3559.78it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3520.06it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB with 20 nodes and 53 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 145/1000 [00:00<00:00, 1441.74it/s]

Bootstrapping average_precision:  29%|██▉       | 290/1000 [00:00<00:00, 1436.75it/s]

Bootstrapping average_precision:  44%|████▎     | 435/1000 [00:00<00:00, 1440.24it/s]

Bootstrapping average_precision:  58%|█████▊    | 580/1000 [00:00<00:00, 1433.40it/s]

Bootstrapping average_precision:  72%|███████▏  | 724/1000 [00:00<00:00, 1433.18it/s]

Bootstrapping average_precision:  87%|████████▋ | 869/1000 [00:00<00:00, 1435.66it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1433.18it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 89/1000 [00:00<00:01, 888.83it/s]

Bootstrapping roc_auc:  18%|█▊        | 179/1000 [00:00<00:00, 890.45it/s]

Bootstrapping roc_auc:  27%|██▋       | 270/1000 [00:00<00:00, 897.03it/s]

Bootstrapping roc_auc:  36%|███▌      | 360/1000 [00:00<00:00, 891.51it/s]

Bootstrapping roc_auc:  45%|████▌     | 450/1000 [00:00<00:00, 883.53it/s]

Bootstrapping roc_auc:  54%|█████▍    | 539/1000 [00:00<00:00, 885.02it/s]

Bootstrapping roc_auc:  63%|██████▎   | 629/1000 [00:00<00:00, 888.25it/s]

Bootstrapping roc_auc:  72%|███████▏  | 720/1000 [00:00<00:00, 893.96it/s]

Bootstrapping roc_auc:  81%|████████  | 810/1000 [00:00<00:00, 884.57it/s]

Bootstrapping roc_auc:  90%|████████▉ | 899/1000 [00:01<00:00, 869.32it/s]

Bootstrapping roc_auc:  99%|█████████▊| 986/1000 [00:01<00:00, 861.54it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 877.05it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1141.93it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1129.88it/s]

Bootstrapping precision:  35%|███▍      | 346/1000 [00:00<00:00, 1143.36it/s]

Bootstrapping precision:  47%|████▋     | 466/1000 [00:00<00:00, 1165.37it/s]

Bootstrapping precision:  58%|█████▊    | 583/1000 [00:00<00:00, 1152.34it/s]

Bootstrapping precision:  70%|██████▉   | 699/1000 [00:00<00:00, 1150.78it/s]

Bootstrapping precision:  82%|████████▏ | 815/1000 [00:00<00:00, 1152.95it/s]

Bootstrapping precision:  93%|█████████▎| 932/1000 [00:00<00:00, 1158.02it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1150.66it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1148.21it/s]

Bootstrapping recall:  23%|██▎       | 230/1000 [00:00<00:00, 1136.92it/s]

Bootstrapping recall:  35%|███▍      | 347/1000 [00:00<00:00, 1148.12it/s]

Bootstrapping recall:  46%|████▌     | 462/1000 [00:00<00:00, 1147.01it/s]

Bootstrapping recall:  58%|█████▊    | 579/1000 [00:00<00:00, 1152.07it/s]

Bootstrapping recall:  70%|██████▉   | 696/1000 [00:00<00:00, 1155.39it/s]

Bootstrapping recall:  81%|████████▏ | 814/1000 [00:00<00:00, 1161.21it/s]

Bootstrapping recall:  93%|█████████▎| 934/1000 [00:00<00:00, 1172.17it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1157.96it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1202.59it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1203.71it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1196.24it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1183.40it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1189.85it/s]

Bootstrapping f1:  72%|███████▏  | 724/1000 [00:00<00:00, 1182.50it/s]

Bootstrapping f1:  84%|████████▍ | 843/1000 [00:00<00:00, 1172.76it/s]

Bootstrapping f1:  96%|█████████▌| 961/1000 [00:00<00:00, 1163.13it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1175.54it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 341/1000 [00:00<00:00, 3409.63it/s]

Bootstrapping accuracy:  69%|██████▊   | 686/1000 [00:00<00:00, 3424.83it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3399.04it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1354.06it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1307.87it/s]

Bootstrapping average_precision:  40%|████      | 403/1000 [00:00<00:00, 1307.26it/s]

Bootstrapping average_precision:  53%|█████▎    | 534/1000 [00:00<00:00, 1299.81it/s]

Bootstrapping average_precision:  67%|██████▋   | 667/1000 [00:00<00:00, 1307.98it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1321.08it/s]

Bootstrapping average_precision:  94%|█████████▎| 935/1000 [00:00<00:00, 1321.94it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1314.48it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 81/1000 [00:00<00:01, 809.87it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:00, 840.88it/s]

Bootstrapping roc_auc:  25%|██▌       | 253/1000 [00:00<00:00, 834.28it/s]

Bootstrapping roc_auc:  34%|███▍      | 338/1000 [00:00<00:00, 837.17it/s]

Bootstrapping roc_auc:  42%|████▏     | 422/1000 [00:00<00:00, 832.70it/s]

Bootstrapping roc_auc:  51%|█████     | 509/1000 [00:00<00:00, 844.77it/s]

Bootstrapping roc_auc:  60%|█████▉    | 595/1000 [00:00<00:00, 849.13it/s]

Bootstrapping roc_auc:  68%|██████▊   | 683/1000 [00:00<00:00, 855.78it/s]

Bootstrapping roc_auc:  77%|███████▋  | 769/1000 [00:00<00:00, 852.82it/s]

Bootstrapping roc_auc:  86%|████████▌ | 856/1000 [00:01<00:00, 857.45it/s]

Bootstrapping roc_auc:  94%|█████████▍| 942/1000 [00:01<00:00, 842.36it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 844.22it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1147.19it/s]

Bootstrapping precision:  23%|██▎       | 231/1000 [00:00<00:00, 1150.81it/s]

Bootstrapping precision:  35%|███▍      | 347/1000 [00:00<00:00, 1144.57it/s]

Bootstrapping precision:  46%|████▌     | 462/1000 [00:00<00:00, 1140.44it/s]

Bootstrapping precision:  58%|█████▊    | 582/1000 [00:00<00:00, 1160.04it/s]

Bootstrapping precision:  70%|██████▉   | 699/1000 [00:00<00:00, 1150.54it/s]

Bootstrapping precision:  82%|████████▏ | 815/1000 [00:00<00:00, 1141.18it/s]

Bootstrapping precision:  94%|█████████▎| 936/1000 [00:00<00:00, 1162.70it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1157.32it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1204.60it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1211.38it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1210.49it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1217.64it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1183.11it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1182.46it/s]

Bootstrapping recall:  85%|████████▍ | 848/1000 [00:00<00:00, 1163.40it/s]

Bootstrapping recall:  96%|█████████▋| 965/1000 [00:00<00:00, 1160.85it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1177.59it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1149.88it/s]

Bootstrapping f1:  23%|██▎       | 233/1000 [00:00<00:00, 1163.18it/s]

Bootstrapping f1:  35%|███▌      | 350/1000 [00:00<00:00, 1113.25it/s]

Bootstrapping f1:  47%|████▋     | 466/1000 [00:00<00:00, 1129.87it/s]

Bootstrapping f1:  58%|█████▊    | 584/1000 [00:00<00:00, 1146.67it/s]

Bootstrapping f1:  70%|███████   | 702/1000 [00:00<00:00, 1156.71it/s]

Bootstrapping f1:  82%|████████▏ | 819/1000 [00:00<00:00, 1158.54it/s]

Bootstrapping f1:  94%|█████████▎| 936/1000 [00:00<00:00, 1160.42it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1150.77it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 338/1000 [00:00<00:00, 3378.81it/s]

Bootstrapping accuracy:  68%|██████▊   | 681/1000 [00:00<00:00, 3408.81it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3392.96it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem with 24 nodes and 35 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 140/1000 [00:00<00:00, 1396.59it/s]

Bootstrapping average_precision:  28%|██▊       | 280/1000 [00:00<00:00, 1393.64it/s]

Bootstrapping average_precision:  42%|████▏     | 420/1000 [00:00<00:00, 1393.90it/s]

Bootstrapping average_precision:  56%|█████▌    | 561/1000 [00:00<00:00, 1396.35it/s]

Bootstrapping average_precision:  70%|███████   | 703/1000 [00:00<00:00, 1400.61it/s]

Bootstrapping average_precision:  84%|████████▍ | 844/1000 [00:00<00:00, 1394.87it/s]

Bootstrapping average_precision:  98%|█████████▊| 984/1000 [00:00<00:00, 1393.04it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1393.38it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 870.29it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 868.36it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 862.50it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 851.47it/s]

Bootstrapping roc_auc:  44%|████▎     | 436/1000 [00:00<00:00, 846.96it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 832.91it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 832.82it/s]

Bootstrapping roc_auc:  69%|██████▉   | 689/1000 [00:00<00:00, 831.77it/s]

Bootstrapping roc_auc:  77%|███████▋  | 773/1000 [00:00<00:00, 823.39it/s]

Bootstrapping roc_auc:  86%|████████▌ | 860/1000 [00:01<00:00, 834.68it/s]

Bootstrapping roc_auc:  94%|█████████▍| 944/1000 [00:01<00:00, 832.54it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 841.01it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1208.50it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1212.36it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1213.53it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1217.43it/s]

Bootstrapping precision:  61%|██████    | 610/1000 [00:00<00:00, 1215.98it/s]

Bootstrapping precision:  73%|███████▎  | 733/1000 [00:00<00:00, 1217.95it/s]

Bootstrapping precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1186.16it/s]

Bootstrapping precision:  97%|█████████▋| 974/1000 [00:00<00:00, 1181.00it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.47it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1207.23it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1196.16it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1199.89it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1205.18it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1195.63it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1193.71it/s]

Bootstrapping recall:  85%|████████▍ | 846/1000 [00:00<00:00, 1191.58it/s]

Bootstrapping recall:  97%|█████████▋| 966/1000 [00:00<00:00, 1174.02it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1185.35it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 114/1000 [00:00<00:00, 1139.85it/s]

Bootstrapping f1:  23%|██▎       | 228/1000 [00:00<00:00, 1135.25it/s]

Bootstrapping f1:  35%|███▍      | 346/1000 [00:00<00:00, 1152.14it/s]

Bootstrapping f1:  46%|████▌     | 462/1000 [00:00<00:00, 1153.52it/s]

Bootstrapping f1:  58%|█████▊    | 580/1000 [00:00<00:00, 1162.88it/s]

Bootstrapping f1:  70%|██████▉   | 697/1000 [00:00<00:00, 1152.29it/s]

Bootstrapping f1:  81%|████████▏ | 813/1000 [00:00<00:00, 1152.37it/s]

Bootstrapping f1:  93%|█████████▎| 930/1000 [00:00<00:00, 1156.23it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1155.58it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3548.55it/s]

Bootstrapping accuracy:  71%|███████   | 710/1000 [00:00<00:00, 3532.31it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3501.64it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1288.57it/s]

Bootstrapping average_precision:  26%|██▌       | 258/1000 [00:00<00:00, 1267.06it/s]

Bootstrapping average_precision:  39%|███▊      | 386/1000 [00:00<00:00, 1270.46it/s]

Bootstrapping average_precision:  52%|█████▏    | 515/1000 [00:00<00:00, 1275.46it/s]

Bootstrapping average_precision:  65%|██████▍   | 648/1000 [00:00<00:00, 1292.88it/s]

Bootstrapping average_precision:  78%|███████▊  | 778/1000 [00:00<00:00, 1287.56it/s]

Bootstrapping average_precision:  91%|█████████ | 907/1000 [00:00<00:00, 1282.91it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1282.59it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 829.09it/s]

Bootstrapping roc_auc:  17%|█▋        | 167/1000 [00:00<00:00, 835.48it/s]

Bootstrapping roc_auc:  25%|██▌       | 251/1000 [00:00<00:00, 833.19it/s]

Bootstrapping roc_auc:  34%|███▎      | 335/1000 [00:00<00:00, 830.82it/s]

Bootstrapping roc_auc:  42%|████▏     | 419/1000 [00:00<00:00, 826.44it/s]

Bootstrapping roc_auc:  50%|█████     | 504/1000 [00:00<00:00, 834.21it/s]

Bootstrapping roc_auc:  59%|█████▉    | 588/1000 [00:00<00:00, 832.93it/s]

Bootstrapping roc_auc:  67%|██████▋   | 672/1000 [00:00<00:00, 830.56it/s]

Bootstrapping roc_auc:  76%|███████▌  | 758/1000 [00:00<00:00, 836.51it/s]

Bootstrapping roc_auc:  84%|████████▍ | 842/1000 [00:01<00:00, 826.95it/s]

Bootstrapping roc_auc:  92%|█████████▎| 925/1000 [00:01<00:00, 823.38it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 829.25it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 117/1000 [00:00<00:00, 1162.79it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1174.77it/s]

Bootstrapping precision:  35%|███▌      | 354/1000 [00:00<00:00, 1148.23it/s]

Bootstrapping precision:  47%|████▋     | 469/1000 [00:00<00:00, 1124.39it/s]

Bootstrapping precision:  59%|█████▊    | 587/1000 [00:00<00:00, 1142.47it/s]

Bootstrapping precision:  70%|███████   | 702/1000 [00:00<00:00, 1144.87it/s]

Bootstrapping precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1166.09it/s]

Bootstrapping precision:  94%|█████████▍| 945/1000 [00:00<00:00, 1178.47it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1163.32it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1159.03it/s]

Bootstrapping recall:  23%|██▎       | 233/1000 [00:00<00:00, 1135.45it/s]

Bootstrapping recall:  35%|███▍      | 347/1000 [00:00<00:00, 1129.81it/s]

Bootstrapping recall:  46%|████▌     | 461/1000 [00:00<00:00, 1133.02it/s]

Bootstrapping recall:  57%|█████▊    | 575/1000 [00:00<00:00, 1132.70it/s]

Bootstrapping recall:  69%|██████▉   | 690/1000 [00:00<00:00, 1136.20it/s]

Bootstrapping recall:  80%|████████  | 805/1000 [00:00<00:00, 1137.65it/s]

Bootstrapping recall:  92%|█████████▏| 919/1000 [00:00<00:00, 1123.53it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1131.01it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1184.58it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1165.75it/s]

Bootstrapping f1:  36%|███▌      | 355/1000 [00:00<00:00, 1164.95it/s]

Bootstrapping f1:  47%|████▋     | 472/1000 [00:00<00:00, 1159.34it/s]

Bootstrapping f1:  59%|█████▉    | 590/1000 [00:00<00:00, 1165.37it/s]

Bootstrapping f1:  71%|███████   | 707/1000 [00:00<00:00, 1149.90it/s]

Bootstrapping f1:  82%|████████▏ | 823/1000 [00:00<00:00, 1152.57it/s]

Bootstrapping f1:  94%|█████████▍| 941/1000 [00:00<00:00, 1159.45it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1154.31it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 333/1000 [00:00<00:00, 3326.81it/s]

Bootstrapping accuracy:  67%|██████▋   | 666/1000 [00:00<00:00, 3167.82it/s]

Bootstrapping accuracy:  98%|█████████▊| 984/1000 [00:00<00:00, 3129.34it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3139.12it/s]

Processing Simplified Golem $\cup$ Simplified PCMB with 24 nodes and 64 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 128/1000 [00:00<00:00, 1279.22it/s]

Bootstrapping average_precision:  26%|██▌       | 262/1000 [00:00<00:00, 1312.87it/s]

Bootstrapping average_precision:  40%|███▉      | 397/1000 [00:00<00:00, 1327.12it/s]

Bootstrapping average_precision:  53%|█████▎    | 534/1000 [00:00<00:00, 1340.80it/s]

Bootstrapping average_precision:  67%|██████▋   | 669/1000 [00:00<00:00, 1340.44it/s]

Bootstrapping average_precision:  81%|████████  | 808/1000 [00:00<00:00, 1356.18it/s]

Bootstrapping average_precision:  95%|█████████▍| 949/1000 [00:00<00:00, 1371.91it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1347.27it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 76/1000 [00:00<00:01, 757.44it/s]

Bootstrapping roc_auc:  16%|█▌        | 159/1000 [00:00<00:01, 797.26it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 814.20it/s]

Bootstrapping roc_auc:  32%|███▎      | 325/1000 [00:00<00:00, 816.20it/s]

Bootstrapping roc_auc:  41%|████      | 408/1000 [00:00<00:00, 819.25it/s]

Bootstrapping roc_auc:  49%|████▉     | 490/1000 [00:00<00:00, 803.01it/s]

Bootstrapping roc_auc:  58%|█████▊    | 576/1000 [00:00<00:00, 818.78it/s]

Bootstrapping roc_auc:  66%|██████▋   | 664/1000 [00:00<00:00, 837.25it/s]

Bootstrapping roc_auc:  75%|███████▌  | 754/1000 [00:00<00:00, 854.02it/s]

Bootstrapping roc_auc:  84%|████████▍ | 840/1000 [00:01<00:00, 844.65it/s]

Bootstrapping roc_auc:  92%|█████████▎| 925/1000 [00:01<00:00, 845.83it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 829.12it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  10%|█         | 104/1000 [00:00<00:00, 1029.36it/s]

Bootstrapping precision:  22%|██▏       | 222/1000 [00:00<00:00, 1112.36it/s]

Bootstrapping precision:  34%|███▍      | 343/1000 [00:00<00:00, 1156.35it/s]

Bootstrapping precision:  46%|████▋     | 465/1000 [00:00<00:00, 1178.04it/s]

Bootstrapping precision:  59%|█████▊    | 587/1000 [00:00<00:00, 1192.54it/s]

Bootstrapping precision:  71%|███████   | 707/1000 [00:00<00:00, 1190.76it/s]

Bootstrapping precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1182.61it/s]

Bootstrapping precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1175.47it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1168.77it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1159.78it/s]

Bootstrapping recall:  23%|██▎       | 232/1000 [00:00<00:00, 1128.11it/s]

Bootstrapping recall:  34%|███▍      | 345/1000 [00:00<00:00, 1049.53it/s]

Bootstrapping recall:  45%|████▌     | 454/1000 [00:00<00:00, 1061.16it/s]

Bootstrapping recall:  57%|█████▋    | 572/1000 [00:00<00:00, 1101.88it/s]

Bootstrapping recall:  69%|██████▉   | 688/1000 [00:00<00:00, 1120.07it/s]

Bootstrapping recall:  80%|████████  | 802/1000 [00:00<00:00, 1123.81it/s]

Bootstrapping recall:  92%|█████████▏| 916/1000 [00:00<00:00, 1127.84it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1116.44it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1141.11it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1071.16it/s]

Bootstrapping f1:  34%|███▍      | 344/1000 [00:00<00:00, 1099.86it/s]

Bootstrapping f1:  46%|████▌     | 456/1000 [00:00<00:00, 1105.92it/s]

Bootstrapping f1:  57%|█████▋    | 567/1000 [00:00<00:00, 1094.50it/s]

Bootstrapping f1:  68%|██████▊   | 679/1000 [00:00<00:00, 1101.91it/s]

Bootstrapping f1:  79%|███████▉  | 792/1000 [00:00<00:00, 1109.42it/s]

Bootstrapping f1:  91%|█████████ | 907/1000 [00:00<00:00, 1121.99it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1114.91it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 340/1000 [00:00<00:00, 3392.91it/s]

Bootstrapping accuracy:  68%|██████▊   | 680/1000 [00:00<00:00, 3295.09it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3300.45it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  12%|█▏        | 123/1000 [00:00<00:00, 1226.71it/s]

Bootstrapping average_precision:  25%|██▍       | 249/1000 [00:00<00:00, 1239.65it/s]

Bootstrapping average_precision:  38%|███▊      | 375/1000 [00:00<00:00, 1244.13it/s]

Bootstrapping average_precision:  50%|█████     | 501/1000 [00:00<00:00, 1246.70it/s]

Bootstrapping average_precision:  63%|██████▎   | 630/1000 [00:00<00:00, 1260.65it/s]

Bootstrapping average_precision:  76%|███████▌  | 757/1000 [00:00<00:00, 1244.11it/s]

Bootstrapping average_precision:  88%|████████▊ | 882/1000 [00:00<00:00, 1224.05it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1239.56it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 81/1000 [00:00<00:01, 807.91it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 761.16it/s]

Bootstrapping roc_auc:  24%|██▍       | 242/1000 [00:00<00:00, 773.98it/s]

Bootstrapping roc_auc:  32%|███▎      | 325/1000 [00:00<00:00, 795.56it/s]

Bootstrapping roc_auc:  41%|████      | 408/1000 [00:00<00:00, 806.92it/s]

Bootstrapping roc_auc:  49%|████▉     | 493/1000 [00:00<00:00, 820.52it/s]

Bootstrapping roc_auc:  58%|█████▊    | 576/1000 [00:00<00:00, 820.46it/s]

Bootstrapping roc_auc:  66%|██████▌   | 659/1000 [00:00<00:00, 820.85it/s]

Bootstrapping roc_auc:  74%|███████▍  | 742/1000 [00:00<00:00, 794.57it/s]

Bootstrapping roc_auc:  82%|████████▏ | 822/1000 [00:01<00:00, 777.59it/s]

Bootstrapping roc_auc:  90%|█████████ | 901/1000 [00:01<00:00, 778.60it/s]

Bootstrapping roc_auc:  98%|█████████▊| 981/1000 [00:01<00:00, 783.94it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 792.13it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 110/1000 [00:00<00:00, 1095.47it/s]

Bootstrapping precision:  22%|██▏       | 220/1000 [00:00<00:00, 1059.66it/s]

Bootstrapping precision:  33%|███▎      | 329/1000 [00:00<00:00, 1069.92it/s]

Bootstrapping precision:  44%|████▍     | 441/1000 [00:00<00:00, 1088.43it/s]

Bootstrapping precision:  55%|█████▌    | 551/1000 [00:00<00:00, 1091.25it/s]

Bootstrapping precision:  66%|██████▌   | 661/1000 [00:00<00:00, 1093.54it/s]

Bootstrapping precision:  77%|███████▋  | 771/1000 [00:00<00:00, 1060.03it/s]

Bootstrapping precision:  88%|████████▊ | 878/1000 [00:00<00:00, 1052.40it/s]

Bootstrapping precision:  98%|█████████▊| 984/1000 [00:00<00:00, 1035.13it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1047.42it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  10%|█         | 103/1000 [00:00<00:00, 1023.78it/s]

Bootstrapping recall:  21%|██        | 211/1000 [00:00<00:00, 1056.37it/s]

Bootstrapping recall:  32%|███▏      | 317/1000 [00:00<00:00, 1001.81it/s]

Bootstrapping recall:  42%|████▏     | 418/1000 [00:00<00:00, 985.16it/s]

Bootstrapping recall:  52%|█████▏    | 521/1000 [00:00<00:00, 1000.48it/s]

Bootstrapping recall:  62%|██████▎   | 625/1000 [00:00<00:00, 1013.46it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 994.90it/s]

Bootstrapping recall:  83%|████████▎ | 834/1000 [00:00<00:00, 1016.05it/s]

Bootstrapping recall:  94%|█████████▍| 943/1000 [00:00<00:00, 1037.81it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1021.94it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 108/1000 [00:00<00:00, 1077.88it/s]

Bootstrapping f1:  22%|██▏       | 218/1000 [00:00<00:00, 1089.46it/s]

Bootstrapping f1:  33%|███▎      | 327/1000 [00:00<00:00, 1073.41it/s]

Bootstrapping f1:  44%|████▎     | 437/1000 [00:00<00:00, 1080.72it/s]

Bootstrapping f1:  55%|█████▍    | 546/1000 [00:00<00:00, 1026.46it/s]

Bootstrapping f1:  66%|██████▌   | 662/1000 [00:00<00:00, 1068.01it/s]

Bootstrapping f1:  78%|███████▊  | 779/1000 [00:00<00:00, 1099.96it/s]

Bootstrapping f1:  90%|████████▉ | 899/1000 [00:00<00:00, 1130.52it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1097.02it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 346/1000 [00:00<00:00, 3456.91it/s]

Bootstrapping accuracy:  69%|██████▉   | 692/1000 [00:00<00:00, 3399.42it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3424.97it/s]

Processing Simplified Clinician Consensus with 17 nodes and 17 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 142/1000 [00:00<00:00, 1419.36it/s]

Bootstrapping average_precision:  28%|██▊       | 284/1000 [00:00<00:00, 1419.00it/s]

Bootstrapping average_precision:  43%|████▎     | 426/1000 [00:00<00:00, 1414.36it/s]

Bootstrapping average_precision:  57%|█████▋    | 570/1000 [00:00<00:00, 1421.64it/s]

Bootstrapping average_precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1422.04it/s]

Bootstrapping average_precision:  86%|████████▌ | 856/1000 [00:00<00:00, 1392.76it/s]

Bootstrapping average_precision: 100%|█████████▉| 996/1000 [00:00<00:00, 1373.57it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1393.64it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 847.36it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 859.25it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 868.50it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 871.08it/s]

Bootstrapping roc_auc:  44%|████▍     | 439/1000 [00:00<00:00, 878.33it/s]

Bootstrapping roc_auc:  53%|█████▎    | 528/1000 [00:00<00:00, 879.93it/s]

Bootstrapping roc_auc:  62%|██████▏   | 616/1000 [00:00<00:00, 878.01it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 877.19it/s]

Bootstrapping roc_auc:  79%|███████▉  | 794/1000 [00:00<00:00, 880.46it/s]

Bootstrapping roc_auc:  88%|████████▊ | 883/1000 [00:01<00:00, 874.32it/s]

Bootstrapping roc_auc:  97%|█████████▋| 972/1000 [00:01<00:00, 878.80it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 875.06it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1203.23it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1202.66it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1202.71it/s]

Bootstrapping precision:  48%|████▊     | 484/1000 [00:00<00:00, 1201.39it/s]

Bootstrapping precision:  60%|██████    | 605/1000 [00:00<00:00, 1196.09it/s]

Bootstrapping precision:  72%|███████▎  | 725/1000 [00:00<00:00, 1194.19it/s]

Bootstrapping precision:  85%|████████▍ | 846/1000 [00:00<00:00, 1196.76it/s]

Bootstrapping precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1196.00it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1189.76it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 114/1000 [00:00<00:00, 1138.05it/s]

Bootstrapping recall:  24%|██▎       | 235/1000 [00:00<00:00, 1178.55it/s]

Bootstrapping recall:  36%|███▌      | 355/1000 [00:00<00:00, 1184.29it/s]

Bootstrapping recall:  48%|████▊     | 475/1000 [00:00<00:00, 1189.88it/s]

Bootstrapping recall:  60%|█████▉    | 596/1000 [00:00<00:00, 1193.94it/s]

Bootstrapping recall:  72%|███████▏  | 716/1000 [00:00<00:00, 1194.60it/s]

Bootstrapping recall:  84%|████████▍ | 838/1000 [00:00<00:00, 1199.08it/s]

Bootstrapping recall:  96%|█████████▌| 960/1000 [00:00<00:00, 1205.01it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1193.85it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 123/1000 [00:00<00:00, 1224.63it/s]

Bootstrapping f1:  25%|██▍       | 246/1000 [00:00<00:00, 1212.11it/s]

Bootstrapping f1:  37%|███▋      | 368/1000 [00:00<00:00, 1210.93it/s]

Bootstrapping f1:  49%|████▉     | 490/1000 [00:00<00:00, 1210.38it/s]

Bootstrapping f1:  61%|██████    | 612/1000 [00:00<00:00, 1212.41it/s]

Bootstrapping f1:  73%|███████▎  | 734/1000 [00:00<00:00, 1212.92it/s]

Bootstrapping f1:  86%|████████▌ | 856/1000 [00:00<00:00, 1204.86it/s]

Bootstrapping f1:  98%|█████████▊| 977/1000 [00:00<00:00, 1205.95it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1207.99it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3556.16it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3498.43it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3506.42it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1342.51it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1346.26it/s]

Bootstrapping average_precision:  41%|████      | 406/1000 [00:00<00:00, 1350.62it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1355.08it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1352.51it/s]

Bootstrapping average_precision:  82%|████████▏ | 815/1000 [00:00<00:00, 1350.06it/s]

Bootstrapping average_precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1352.12it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1351.44it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 866.84it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 860.27it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 861.85it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 862.58it/s]

Bootstrapping roc_auc:  44%|████▎     | 435/1000 [00:00<00:00, 857.39it/s]

Bootstrapping roc_auc:  52%|█████▏    | 522/1000 [00:00<00:00, 861.42it/s]

Bootstrapping roc_auc:  61%|██████    | 609/1000 [00:00<00:00, 863.80it/s]

Bootstrapping roc_auc:  70%|██████▉   | 696/1000 [00:00<00:00, 862.59it/s]

Bootstrapping roc_auc:  78%|███████▊  | 783/1000 [00:00<00:00, 861.33it/s]

Bootstrapping roc_auc:  87%|████████▋ | 870/1000 [00:01<00:00, 862.17it/s]

Bootstrapping roc_auc:  96%|█████████▌| 957/1000 [00:01<00:00, 862.99it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 862.06it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1213.53it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1212.96it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1212.21it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1211.01it/s]

Bootstrapping precision:  61%|██████    | 610/1000 [00:00<00:00, 1213.40it/s]

Bootstrapping precision:  73%|███████▎  | 733/1000 [00:00<00:00, 1216.94it/s]

Bootstrapping precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1217.53it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1218.17it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1214.85it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1225.50it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1213.89it/s]

Bootstrapping recall:  37%|███▋      | 368/1000 [00:00<00:00, 1209.93it/s]

Bootstrapping recall:  49%|████▉     | 489/1000 [00:00<00:00, 1206.91it/s]

Bootstrapping recall:  61%|██████    | 612/1000 [00:00<00:00, 1213.24it/s]

Bootstrapping recall:  74%|███████▎  | 735/1000 [00:00<00:00, 1215.52it/s]

Bootstrapping recall:  86%|████████▌ | 858/1000 [00:00<00:00, 1216.44it/s]

Bootstrapping recall:  98%|█████████▊| 980/1000 [00:00<00:00, 1214.36it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1211.54it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1152.85it/s]

Bootstrapping f1:  23%|██▎       | 232/1000 [00:00<00:00, 1139.80it/s]

Bootstrapping f1:  35%|███▌      | 350/1000 [00:00<00:00, 1157.47it/s]

Bootstrapping f1:  47%|████▋     | 471/1000 [00:00<00:00, 1175.48it/s]

Bootstrapping f1:  59%|█████▉    | 592/1000 [00:00<00:00, 1185.96it/s]

Bootstrapping f1:  71%|███████▏  | 713/1000 [00:00<00:00, 1193.42it/s]

Bootstrapping f1:  83%|████████▎ | 834/1000 [00:00<00:00, 1197.54it/s]

Bootstrapping f1:  95%|█████████▌| 954/1000 [00:00<00:00, 1194.57it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1184.41it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3536.14it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3537.79it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3537.47it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB with 15 nodes and 14 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 140/1000 [00:00<00:00, 1396.29it/s]

Bootstrapping average_precision:  28%|██▊       | 284/1000 [00:00<00:00, 1420.48it/s]

Bootstrapping average_precision:  43%|████▎     | 427/1000 [00:00<00:00, 1422.44it/s]

Bootstrapping average_precision:  57%|█████▋    | 571/1000 [00:00<00:00, 1426.44it/s]

Bootstrapping average_precision:  71%|███████▏  | 714/1000 [00:00<00:00, 1418.17it/s]

Bootstrapping average_precision:  86%|████████▌ | 856/1000 [00:00<00:00, 1414.86it/s]

Bootstrapping average_precision: 100%|█████████▉| 998/1000 [00:00<00:00, 1410.99it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1413.61it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 90/1000 [00:00<00:01, 895.66it/s]

Bootstrapping roc_auc:  18%|█▊        | 180/1000 [00:00<00:00, 893.86it/s]

Bootstrapping roc_auc:  27%|██▋       | 270/1000 [00:00<00:00, 889.97it/s]

Bootstrapping roc_auc:  36%|███▌      | 359/1000 [00:00<00:00, 887.09it/s]

Bootstrapping roc_auc:  45%|████▍     | 448/1000 [00:00<00:00, 881.51it/s]

Bootstrapping roc_auc:  54%|█████▎    | 537/1000 [00:00<00:00, 875.10it/s]

Bootstrapping roc_auc:  62%|██████▎   | 625/1000 [00:00<00:00, 875.13it/s]

Bootstrapping roc_auc:  71%|███████▏  | 713/1000 [00:00<00:00, 875.69it/s]

Bootstrapping roc_auc:  80%|████████  | 803/1000 [00:00<00:00, 881.03it/s]

Bootstrapping roc_auc:  89%|████████▉ | 893/1000 [00:01<00:00, 883.88it/s]

Bootstrapping roc_auc:  98%|█████████▊| 982/1000 [00:01<00:00, 881.83it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 881.85it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1194.84it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1199.33it/s]

Bootstrapping precision:  36%|███▌      | 362/1000 [00:00<00:00, 1203.05it/s]

Bootstrapping precision:  48%|████▊     | 484/1000 [00:00<00:00, 1208.24it/s]

Bootstrapping precision:  60%|██████    | 605/1000 [00:00<00:00, 1206.33it/s]

Bootstrapping precision:  73%|███████▎  | 727/1000 [00:00<00:00, 1206.98it/s]

Bootstrapping precision:  85%|████████▍ | 848/1000 [00:00<00:00, 1204.73it/s]

Bootstrapping precision:  97%|█████████▋| 969/1000 [00:00<00:00, 1199.97it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1201.92it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1200.48it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1196.60it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1195.44it/s]

Bootstrapping recall:  48%|████▊     | 482/1000 [00:00<00:00, 1196.73it/s]

Bootstrapping recall:  60%|██████    | 603/1000 [00:00<00:00, 1199.16it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1196.77it/s]

Bootstrapping recall:  84%|████████▍ | 844/1000 [00:00<00:00, 1200.95it/s]

Bootstrapping recall:  96%|█████████▋| 965/1000 [00:00<00:00, 1201.03it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1198.68it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1208.25it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1197.99it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1197.40it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1199.63it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1202.30it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1203.81it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1201.74it/s]

Bootstrapping f1:  97%|█████████▋| 967/1000 [00:00<00:00, 1201.84it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1200.33it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 352/1000 [00:00<00:00, 3516.23it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3528.53it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3521.94it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1323.86it/s]

Bootstrapping average_precision:  27%|██▋       | 266/1000 [00:00<00:00, 1306.16it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 1330.42it/s]

Bootstrapping average_precision:  54%|█████▍    | 538/1000 [00:00<00:00, 1341.78it/s]

Bootstrapping average_precision:  67%|██████▋   | 674/1000 [00:00<00:00, 1346.12it/s]

Bootstrapping average_precision:  81%|████████  | 810/1000 [00:00<00:00, 1347.79it/s]

Bootstrapping average_precision:  94%|█████████▍| 945/1000 [00:00<00:00, 1341.69it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1338.42it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 849.08it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 842.52it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 849.98it/s]

Bootstrapping roc_auc:  34%|███▍      | 342/1000 [00:00<00:00, 853.67it/s]

Bootstrapping roc_auc:  43%|████▎     | 428/1000 [00:00<00:00, 848.48it/s]

Bootstrapping roc_auc:  51%|█████▏    | 513/1000 [00:00<00:00, 844.89it/s]

Bootstrapping roc_auc:  60%|█████▉    | 598/1000 [00:00<00:00, 838.31it/s]

Bootstrapping roc_auc:  68%|██████▊   | 682/1000 [00:00<00:00, 831.26it/s]

Bootstrapping roc_auc:  77%|███████▋  | 766/1000 [00:00<00:00, 831.03it/s]

Bootstrapping roc_auc:  85%|████████▌ | 850/1000 [00:01<00:00, 830.45it/s]

Bootstrapping roc_auc:  93%|█████████▎| 934/1000 [00:01<00:00, 829.64it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 839.10it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1204.90it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1209.12it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1212.72it/s]

Bootstrapping precision:  49%|████▊     | 487/1000 [00:00<00:00, 1196.65it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1199.04it/s]

Bootstrapping precision:  73%|███████▎  | 729/1000 [00:00<00:00, 1201.07it/s]

Bootstrapping precision:  85%|████████▌ | 851/1000 [00:00<00:00, 1205.30it/s]

Bootstrapping precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1205.91it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1204.09it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1204.06it/s]

Bootstrapping recall:  24%|██▍       | 243/1000 [00:00<00:00, 1208.75it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1202.02it/s]

Bootstrapping recall:  49%|████▊     | 487/1000 [00:00<00:00, 1211.54it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1216.39it/s]

Bootstrapping recall:  73%|███████▎  | 733/1000 [00:00<00:00, 1217.81it/s]

Bootstrapping recall:  86%|████████▌ | 855/1000 [00:00<00:00, 1212.07it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1163.68it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1191.15it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1143.29it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1110.42it/s]

Bootstrapping f1:  34%|███▍      | 345/1000 [00:00<00:00, 1125.63it/s]

Bootstrapping f1:  46%|████▌     | 458/1000 [00:00<00:00, 1126.22it/s]

Bootstrapping f1:  57%|█████▋    | 573/1000 [00:00<00:00, 1132.70it/s]

Bootstrapping f1:  69%|██████▊   | 687/1000 [00:00<00:00, 1132.47it/s]

Bootstrapping f1:  80%|████████  | 801/1000 [00:00<00:00, 1133.91it/s]

Bootstrapping f1:  92%|█████████▏| 915/1000 [00:00<00:00, 1134.99it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1131.11it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 327/1000 [00:00<00:00, 3259.41it/s]

Bootstrapping accuracy:  66%|██████▋   | 663/1000 [00:00<00:00, 3312.70it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3339.31it/s]

Processing Simplified PCMB with 18 nodes and 50 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1313.56it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1339.61it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 1346.83it/s]

Bootstrapping average_precision:  54%|█████▍    | 541/1000 [00:00<00:00, 1352.27it/s]

Bootstrapping average_precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1353.79it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1366.80it/s]

Bootstrapping average_precision:  95%|█████████▌| 954/1000 [00:00<00:00, 1364.61it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1353.02it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 821.75it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 822.62it/s]

Bootstrapping roc_auc:  25%|██▌       | 252/1000 [00:00<00:00, 836.12it/s]

Bootstrapping roc_auc:  34%|███▎      | 337/1000 [00:00<00:00, 840.75it/s]

Bootstrapping roc_auc:  42%|████▏     | 423/1000 [00:00<00:00, 845.10it/s]

Bootstrapping roc_auc:  51%|█████     | 510/1000 [00:00<00:00, 852.37it/s]

Bootstrapping roc_auc:  60%|█████▉    | 596/1000 [00:00<00:00, 852.55it/s]

Bootstrapping roc_auc:  68%|██████▊   | 682/1000 [00:00<00:00, 838.65it/s]

Bootstrapping roc_auc:  77%|███████▋  | 766/1000 [00:00<00:00, 828.04it/s]

Bootstrapping roc_auc:  85%|████████▍ | 849/1000 [00:01<00:00, 824.53it/s]

Bootstrapping roc_auc:  93%|█████████▎| 933/1000 [00:01<00:00, 828.07it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 835.22it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 113/1000 [00:00<00:00, 1120.80it/s]

Bootstrapping precision:  23%|██▎       | 227/1000 [00:00<00:00, 1128.37it/s]

Bootstrapping precision:  34%|███▍      | 342/1000 [00:00<00:00, 1137.72it/s]

Bootstrapping precision:  46%|████▌     | 457/1000 [00:00<00:00, 1139.94it/s]

Bootstrapping precision:  57%|█████▋    | 571/1000 [00:00<00:00, 1138.26it/s]

Bootstrapping precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1137.81it/s]

Bootstrapping precision:  80%|████████  | 800/1000 [00:00<00:00, 1139.80it/s]

Bootstrapping precision:  91%|█████████▏| 914/1000 [00:00<00:00, 1139.22it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1133.86it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 110/1000 [00:00<00:00, 1093.35it/s]

Bootstrapping recall:  22%|██▏       | 223/1000 [00:00<00:00, 1109.56it/s]

Bootstrapping recall:  34%|███▎      | 337/1000 [00:00<00:00, 1123.29it/s]

Bootstrapping recall:  45%|████▌     | 450/1000 [00:00<00:00, 1122.18it/s]

Bootstrapping recall:  56%|█████▋    | 563/1000 [00:00<00:00, 1124.67it/s]

Bootstrapping recall:  68%|██████▊   | 677/1000 [00:00<00:00, 1127.89it/s]

Bootstrapping recall:  79%|███████▉  | 794/1000 [00:00<00:00, 1138.83it/s]

Bootstrapping recall:  91%|█████████ | 910/1000 [00:00<00:00, 1144.44it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1131.52it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1154.06it/s]

Bootstrapping f1:  23%|██▎       | 232/1000 [00:00<00:00, 1155.98it/s]

Bootstrapping f1:  35%|███▍      | 348/1000 [00:00<00:00, 1155.80it/s]

Bootstrapping f1:  46%|████▋     | 464/1000 [00:00<00:00, 1152.16it/s]

Bootstrapping f1:  58%|█████▊    | 580/1000 [00:00<00:00, 1136.36it/s]

Bootstrapping f1:  70%|██████▉   | 696/1000 [00:00<00:00, 1141.32it/s]

Bootstrapping f1:  81%|████████  | 811/1000 [00:00<00:00, 1139.61it/s]

Bootstrapping f1:  92%|█████████▎| 925/1000 [00:00<00:00, 1127.31it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1138.16it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 344/1000 [00:00<00:00, 3430.78it/s]

Bootstrapping accuracy:  69%|██████▉   | 688/1000 [00:00<00:00, 3426.67it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3436.55it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  12%|█▏        | 124/1000 [00:00<00:00, 1235.27it/s]

Bootstrapping average_precision:  25%|██▌       | 254/1000 [00:00<00:00, 1270.07it/s]

Bootstrapping average_precision:  38%|███▊      | 385/1000 [00:00<00:00, 1287.41it/s]

Bootstrapping average_precision:  52%|█████▏    | 516/1000 [00:00<00:00, 1293.91it/s]

Bootstrapping average_precision:  65%|██████▌   | 652/1000 [00:00<00:00, 1314.27it/s]

Bootstrapping average_precision:  78%|███████▊  | 784/1000 [00:00<00:00, 1315.85it/s]

Bootstrapping average_precision:  92%|█████████▏| 916/1000 [00:00<00:00, 1314.57it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1303.23it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 824.31it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 823.11it/s]

Bootstrapping roc_auc:  25%|██▍       | 249/1000 [00:00<00:00, 816.13it/s]

Bootstrapping roc_auc:  33%|███▎      | 331/1000 [00:00<00:00, 815.61it/s]

Bootstrapping roc_auc:  41%|████▏     | 413/1000 [00:00<00:00, 806.57it/s]

Bootstrapping roc_auc:  50%|████▉     | 496/1000 [00:00<00:00, 812.06it/s]

Bootstrapping roc_auc:  58%|█████▊    | 581/1000 [00:00<00:00, 822.30it/s]

Bootstrapping roc_auc:  66%|██████▋   | 664/1000 [00:00<00:00, 823.75it/s]

Bootstrapping roc_auc:  75%|███████▍  | 747/1000 [00:00<00:00, 818.46it/s]

Bootstrapping roc_auc:  83%|████████▎ | 831/1000 [00:01<00:00, 822.66it/s]

Bootstrapping roc_auc:  91%|█████████▏| 914/1000 [00:01<00:00, 820.70it/s]

Bootstrapping roc_auc: 100%|█████████▉| 997/1000 [00:01<00:00, 811.84it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 815.80it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1136.74it/s]

Bootstrapping precision:  23%|██▎       | 229/1000 [00:00<00:00, 1138.38it/s]

Bootstrapping precision:  34%|███▍      | 343/1000 [00:00<00:00, 1109.69it/s]

Bootstrapping precision:  46%|████▌     | 459/1000 [00:00<00:00, 1126.84it/s]

Bootstrapping precision:  57%|█████▋    | 574/1000 [00:00<00:00, 1133.54it/s]

Bootstrapping precision:  69%|██████▉   | 689/1000 [00:00<00:00, 1136.10it/s]

Bootstrapping precision:  80%|████████  | 803/1000 [00:00<00:00, 1127.67it/s]

Bootstrapping precision:  92%|█████████▏| 916/1000 [00:00<00:00, 1124.89it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1125.65it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 110/1000 [00:00<00:00, 1099.80it/s]

Bootstrapping recall:  22%|██▏       | 224/1000 [00:00<00:00, 1123.02it/s]

Bootstrapping recall:  34%|███▍      | 340/1000 [00:00<00:00, 1139.05it/s]

Bootstrapping recall:  46%|████▌     | 457/1000 [00:00<00:00, 1148.44it/s]

Bootstrapping recall:  57%|█████▋    | 572/1000 [00:00<00:00, 1131.13it/s]

Bootstrapping recall:  69%|██████▊   | 686/1000 [00:00<00:00, 1124.80it/s]

Bootstrapping recall:  80%|████████  | 802/1000 [00:00<00:00, 1132.52it/s]

Bootstrapping recall:  92%|█████████▏| 920/1000 [00:00<00:00, 1146.93it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1138.64it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1175.06it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1168.64it/s]

Bootstrapping f1:  35%|███▌      | 353/1000 [00:00<00:00, 1138.89it/s]

Bootstrapping f1:  47%|████▋     | 467/1000 [00:00<00:00, 1122.33it/s]

Bootstrapping f1:  58%|█████▊    | 580/1000 [00:00<00:00, 1114.32it/s]

Bootstrapping f1:  69%|██████▉   | 694/1000 [00:00<00:00, 1120.46it/s]

Bootstrapping f1:  81%|████████  | 807/1000 [00:00<00:00, 1120.05it/s]

Bootstrapping f1:  92%|█████████▏| 921/1000 [00:00<00:00, 1122.66it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1127.11it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 338/1000 [00:00<00:00, 3370.83it/s]

Bootstrapping accuracy:  68%|██████▊   | 676/1000 [00:00<00:00, 3368.97it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3375.49it/s]

Processing Simplified Golem with 12 nodes and 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1339.83it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1334.22it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1353.53it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1348.53it/s]

Bootstrapping average_precision:  68%|██████▊   | 680/1000 [00:00<00:00, 1352.66it/s]

Bootstrapping average_precision:  82%|████████▏ | 819/1000 [00:00<00:00, 1364.53it/s]

Bootstrapping average_precision:  96%|█████████▌| 961/1000 [00:00<00:00, 1381.03it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1363.74it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 89/1000 [00:00<00:01, 881.67it/s]

Bootstrapping roc_auc:  18%|█▊        | 178/1000 [00:00<00:00, 876.39it/s]

Bootstrapping roc_auc:  27%|██▋       | 266/1000 [00:00<00:00, 844.44it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 844.07it/s]

Bootstrapping roc_auc:  44%|████▎     | 436/1000 [00:00<00:00, 836.83it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 837.49it/s]

Bootstrapping roc_auc:  61%|██████    | 610/1000 [00:00<00:00, 855.25it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 868.05it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 877.02it/s]

Bootstrapping roc_auc:  88%|████████▊ | 879/1000 [00:01<00:00, 878.10it/s]

Bootstrapping roc_auc:  97%|█████████▋| 968/1000 [00:01<00:00, 879.84it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 861.78it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1147.08it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1152.04it/s]

Bootstrapping precision:  35%|███▍      | 348/1000 [00:00<00:00, 1151.68it/s]

Bootstrapping precision:  47%|████▋     | 467/1000 [00:00<00:00, 1165.68it/s]

Bootstrapping precision:  58%|█████▊    | 584/1000 [00:00<00:00, 1167.11it/s]

Bootstrapping precision:  70%|███████   | 701/1000 [00:00<00:00, 1164.72it/s]

Bootstrapping precision:  82%|████████▏ | 818/1000 [00:00<00:00, 1163.81it/s]

Bootstrapping precision:  94%|█████████▎| 935/1000 [00:00<00:00, 1158.89it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1158.58it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 114/1000 [00:00<00:00, 1132.17it/s]

Bootstrapping recall:  23%|██▎       | 229/1000 [00:00<00:00, 1141.43it/s]

Bootstrapping recall:  34%|███▍      | 345/1000 [00:00<00:00, 1146.98it/s]

Bootstrapping recall:  46%|████▌     | 460/1000 [00:00<00:00, 1118.41it/s]

Bootstrapping recall:  57%|█████▋    | 572/1000 [00:00<00:00, 1091.83it/s]

Bootstrapping recall:  68%|██████▊   | 682/1000 [00:00<00:00, 1090.95it/s]

Bootstrapping recall:  80%|███████▉  | 796/1000 [00:00<00:00, 1106.07it/s]

Bootstrapping recall:  91%|█████████ | 911/1000 [00:00<00:00, 1119.77it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1114.22it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1141.21it/s]

Bootstrapping f1:  24%|██▎       | 235/1000 [00:00<00:00, 1171.25it/s]

Bootstrapping f1:  35%|███▌      | 354/1000 [00:00<00:00, 1178.33it/s]

Bootstrapping f1:  47%|████▋     | 472/1000 [00:00<00:00, 1177.14it/s]

Bootstrapping f1:  59%|█████▉    | 592/1000 [00:00<00:00, 1184.93it/s]

Bootstrapping f1:  71%|███████▏  | 713/1000 [00:00<00:00, 1193.36it/s]

Bootstrapping f1:  83%|████████▎ | 834/1000 [00:00<00:00, 1198.05it/s]

Bootstrapping f1:  95%|█████████▌| 954/1000 [00:00<00:00, 1189.22it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1182.06it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 345/1000 [00:00<00:00, 3442.33it/s]

Bootstrapping accuracy:  69%|██████▉   | 690/1000 [00:00<00:00, 3429.18it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3442.88it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1360.54it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1360.43it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1359.63it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1360.54it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1360.81it/s]

Bootstrapping average_precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1363.02it/s]

Bootstrapping average_precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1352.31it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1355.86it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 81/1000 [00:00<00:01, 809.82it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 802.48it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 819.08it/s]

Bootstrapping roc_auc:  33%|███▎      | 330/1000 [00:00<00:00, 824.67it/s]

Bootstrapping roc_auc:  42%|████▏     | 415/1000 [00:00<00:00, 833.23it/s]

Bootstrapping roc_auc:  50%|█████     | 501/1000 [00:00<00:00, 840.20it/s]

Bootstrapping roc_auc:  59%|█████▊    | 586/1000 [00:00<00:00, 841.65it/s]

Bootstrapping roc_auc:  67%|██████▋   | 671/1000 [00:00<00:00, 837.16it/s]

Bootstrapping roc_auc:  76%|███████▌  | 757/1000 [00:00<00:00, 841.88it/s]

Bootstrapping roc_auc:  84%|████████▍ | 843/1000 [00:01<00:00, 845.96it/s]

Bootstrapping roc_auc:  93%|█████████▎| 928/1000 [00:01<00:00, 838.98it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 833.00it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1170.93it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1169.18it/s]

Bootstrapping precision:  36%|███▌      | 355/1000 [00:00<00:00, 1174.74it/s]

Bootstrapping precision:  48%|████▊     | 475/1000 [00:00<00:00, 1181.17it/s]

Bootstrapping precision:  60%|█████▉    | 596/1000 [00:00<00:00, 1190.23it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1195.71it/s]

Bootstrapping precision:  84%|████████▎ | 837/1000 [00:00<00:00, 1195.01it/s]

Bootstrapping precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1200.92it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1191.57it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1198.76it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1198.98it/s]

Bootstrapping recall:  36%|███▌      | 361/1000 [00:00<00:00, 1201.43it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1208.93it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1209.72it/s]

Bootstrapping recall:  73%|███████▎  | 727/1000 [00:00<00:00, 1207.51it/s]

Bootstrapping recall:  85%|████████▍ | 849/1000 [00:00<00:00, 1210.89it/s]

Bootstrapping recall:  97%|█████████▋| 971/1000 [00:00<00:00, 1210.67it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1207.65it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1193.32it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1195.47it/s]

Bootstrapping f1:  36%|███▌      | 361/1000 [00:00<00:00, 1201.02it/s]

Bootstrapping f1:  48%|████▊     | 484/1000 [00:00<00:00, 1208.63it/s]

Bootstrapping f1:  60%|██████    | 605/1000 [00:00<00:00, 1207.22it/s]

Bootstrapping f1:  73%|███████▎  | 726/1000 [00:00<00:00, 1198.54it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1194.84it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1192.80it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1197.51it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3546.22it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3558.15it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3550.54it/s]

Processing Simplified Golem $\cap$ Simplified PCMB with 6 nodes and 5 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 140/1000 [00:00<00:00, 1394.35it/s]

Bootstrapping average_precision:  28%|██▊       | 281/1000 [00:00<00:00, 1397.79it/s]

Bootstrapping average_precision:  42%|████▏     | 421/1000 [00:00<00:00, 1379.18it/s]

Bootstrapping average_precision:  56%|█████▌    | 559/1000 [00:00<00:00, 1344.94it/s]

Bootstrapping average_precision:  69%|██████▉   | 694/1000 [00:00<00:00, 1334.22it/s]

Bootstrapping average_precision:  83%|████████▎ | 828/1000 [00:00<00:00, 1317.55it/s]

Bootstrapping average_precision:  96%|█████████▌| 961/1000 [00:00<00:00, 1320.03it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1335.89it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 845.10it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:01, 828.19it/s]

Bootstrapping roc_auc:  25%|██▌       | 253/1000 [00:00<00:00, 827.31it/s]

Bootstrapping roc_auc:  34%|███▍      | 339/1000 [00:00<00:00, 837.55it/s]

Bootstrapping roc_auc:  42%|████▏     | 423/1000 [00:00<00:00, 833.21it/s]

Bootstrapping roc_auc:  51%|█████     | 512/1000 [00:00<00:00, 849.15it/s]

Bootstrapping roc_auc:  60%|██████    | 601/1000 [00:00<00:00, 859.04it/s]

Bootstrapping roc_auc:  69%|██████▊   | 687/1000 [00:00<00:00, 858.38it/s]

Bootstrapping roc_auc:  77%|███████▋  | 773/1000 [00:00<00:00, 851.41it/s]

Bootstrapping roc_auc:  86%|████████▌ | 859/1000 [00:01<00:00, 844.21it/s]

Bootstrapping roc_auc:  95%|█████████▍| 946/1000 [00:01<00:00, 850.23it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 845.66it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1133.27it/s]

Bootstrapping precision:  23%|██▎       | 228/1000 [00:00<00:00, 1089.10it/s]

Bootstrapping precision:  34%|███▍      | 342/1000 [00:00<00:00, 1110.77it/s]

Bootstrapping precision:  45%|████▌     | 454/1000 [00:00<00:00, 1108.37it/s]

Bootstrapping precision:  57%|█████▋    | 568/1000 [00:00<00:00, 1117.79it/s]

Bootstrapping precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1124.88it/s]

Bootstrapping precision:  80%|████████  | 802/1000 [00:00<00:00, 1143.87it/s]

Bootstrapping precision:  92%|█████████▏| 917/1000 [00:00<00:00, 1139.72it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1129.37it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1146.16it/s]

Bootstrapping recall:  23%|██▎       | 230/1000 [00:00<00:00, 1137.38it/s]

Bootstrapping recall:  34%|███▍      | 344/1000 [00:00<00:00, 1129.93it/s]

Bootstrapping recall:  46%|████▌     | 457/1000 [00:00<00:00, 1117.12it/s]

Bootstrapping recall:  57%|█████▋    | 570/1000 [00:00<00:00, 1120.75it/s]

Bootstrapping recall:  68%|██████▊   | 685/1000 [00:00<00:00, 1127.56it/s]

Bootstrapping recall:  80%|████████  | 802/1000 [00:00<00:00, 1139.80it/s]

Bootstrapping recall:  92%|█████████▏| 918/1000 [00:00<00:00, 1144.69it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1136.53it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1142.92it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1140.94it/s]

Bootstrapping f1:  35%|███▍      | 346/1000 [00:00<00:00, 1147.42it/s]

Bootstrapping f1:  46%|████▌     | 462/1000 [00:00<00:00, 1151.87it/s]

Bootstrapping f1:  58%|█████▊    | 581/1000 [00:00<00:00, 1163.15it/s]

Bootstrapping f1:  70%|██████▉   | 699/1000 [00:00<00:00, 1167.40it/s]

Bootstrapping f1:  82%|████████▏ | 816/1000 [00:00<00:00, 1166.38it/s]

Bootstrapping f1:  93%|█████████▎| 933/1000 [00:00<00:00, 1159.17it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1158.04it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 341/1000 [00:00<00:00, 3408.06it/s]

Bootstrapping accuracy:  69%|██████▉   | 692/1000 [00:00<00:00, 3463.35it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3472.81it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  12%|█▏        | 124/1000 [00:00<00:00, 1232.63it/s]

Bootstrapping average_precision:  25%|██▌       | 251/1000 [00:00<00:00, 1251.04it/s]

Bootstrapping average_precision:  38%|███▊      | 383/1000 [00:00<00:00, 1279.98it/s]

Bootstrapping average_precision:  51%|█████     | 512/1000 [00:00<00:00, 1270.28it/s]

Bootstrapping average_precision:  64%|██████▍   | 643/1000 [00:00<00:00, 1282.96it/s]

Bootstrapping average_precision:  77%|███████▋  | 772/1000 [00:00<00:00, 1278.24it/s]

Bootstrapping average_precision:  91%|█████████ | 906/1000 [00:00<00:00, 1296.91it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1288.08it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 856.01it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 856.89it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 856.57it/s]

Bootstrapping roc_auc:  34%|███▍      | 344/1000 [00:00<00:00, 840.04it/s]

Bootstrapping roc_auc:  43%|████▎     | 429/1000 [00:00<00:00, 841.66it/s]

Bootstrapping roc_auc:  51%|█████▏    | 514/1000 [00:00<00:00, 840.76it/s]

Bootstrapping roc_auc:  60%|█████▉    | 599/1000 [00:00<00:00, 842.40it/s]

Bootstrapping roc_auc:  68%|██████▊   | 685/1000 [00:00<00:00, 847.57it/s]

Bootstrapping roc_auc:  77%|███████▋  | 772/1000 [00:00<00:00, 851.68it/s]

Bootstrapping roc_auc:  86%|████████▌ | 858/1000 [00:01<00:00, 852.47it/s]

Bootstrapping roc_auc:  94%|█████████▍| 944/1000 [00:01<00:00, 853.51it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 849.98it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1199.24it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1199.60it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1194.71it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1175.69it/s]

Bootstrapping precision:  60%|█████▉    | 599/1000 [00:00<00:00, 1176.97it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1177.83it/s]

Bootstrapping precision:  84%|████████▎ | 836/1000 [00:00<00:00, 1180.36it/s]

Bootstrapping precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1184.29it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1183.61it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1208.79it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1199.15it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1197.21it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1201.28it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1177.01it/s]

Bootstrapping recall:  72%|███████▏  | 722/1000 [00:00<00:00, 1176.11it/s]

Bootstrapping recall:  84%|████████▍ | 842/1000 [00:00<00:00, 1181.49it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1191.65it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1187.33it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1201.65it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1194.88it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1183.03it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1190.97it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1194.23it/s]

Bootstrapping f1:  72%|███████▏  | 724/1000 [00:00<00:00, 1194.93it/s]

Bootstrapping f1:  84%|████████▍ | 844/1000 [00:00<00:00, 1189.13it/s]

Bootstrapping f1:  96%|█████████▋| 963/1000 [00:00<00:00, 1186.45it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1187.38it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 351/1000 [00:00<00:00, 3508.77it/s]

Bootstrapping accuracy:  70%|███████   | 702/1000 [00:00<00:00, 3443.97it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3439.94it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem with 5 nodes and 4 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1355.18it/s]

Bootstrapping average_precision:  27%|██▋       | 273/1000 [00:00<00:00, 1363.77it/s]

Bootstrapping average_precision:  41%|████      | 412/1000 [00:00<00:00, 1374.30it/s]

Bootstrapping average_precision:  55%|█████▌    | 551/1000 [00:00<00:00, 1378.79it/s]

Bootstrapping average_precision:  69%|██████▉   | 692/1000 [00:00<00:00, 1387.05it/s]

Bootstrapping average_precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1391.16it/s]

Bootstrapping average_precision:  97%|█████████▋| 973/1000 [00:00<00:00, 1395.12it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1385.04it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 89/1000 [00:00<00:01, 883.17it/s]

Bootstrapping roc_auc:  18%|█▊        | 178/1000 [00:00<00:00, 881.60it/s]

Bootstrapping roc_auc:  27%|██▋       | 267/1000 [00:00<00:00, 882.75it/s]

Bootstrapping roc_auc:  36%|███▌      | 356/1000 [00:00<00:00, 881.47it/s]

Bootstrapping roc_auc:  44%|████▍     | 445/1000 [00:00<00:00, 882.19it/s]

Bootstrapping roc_auc:  53%|█████▎    | 534/1000 [00:00<00:00, 882.55it/s]

Bootstrapping roc_auc:  62%|██████▏   | 623/1000 [00:00<00:00, 881.45it/s]

Bootstrapping roc_auc:  71%|███████▏  | 713/1000 [00:00<00:00, 885.00it/s]

Bootstrapping roc_auc:  80%|████████  | 802/1000 [00:00<00:00, 886.43it/s]

Bootstrapping roc_auc:  89%|████████▉ | 891/1000 [00:01<00:00, 887.06it/s]

Bootstrapping roc_auc:  98%|█████████▊| 980/1000 [00:01<00:00, 883.57it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 883.17it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1209.29it/s]

Bootstrapping precision:  24%|██▍       | 243/1000 [00:00<00:00, 1210.43it/s]

Bootstrapping precision:  36%|███▋      | 365/1000 [00:00<00:00, 1209.99it/s]

Bootstrapping precision:  49%|████▊     | 486/1000 [00:00<00:00, 1198.15it/s]

Bootstrapping precision:  61%|██████    | 606/1000 [00:00<00:00, 1194.70it/s]

Bootstrapping precision:  73%|███████▎  | 726/1000 [00:00<00:00, 1193.10it/s]

Bootstrapping precision:  85%|████████▍ | 846/1000 [00:00<00:00, 1173.51it/s]

Bootstrapping precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1160.15it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1179.61it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1166.31it/s]

Bootstrapping recall:  23%|██▎       | 234/1000 [00:00<00:00, 1137.82it/s]

Bootstrapping recall:  35%|███▍      | 349/1000 [00:00<00:00, 1141.55it/s]

Bootstrapping recall:  46%|████▋     | 464/1000 [00:00<00:00, 1115.04it/s]

Bootstrapping recall:  58%|█████▊    | 578/1000 [00:00<00:00, 1122.76it/s]

Bootstrapping recall:  70%|██████▉   | 698/1000 [00:00<00:00, 1147.49it/s]

Bootstrapping recall:  82%|████████▏ | 818/1000 [00:00<00:00, 1164.41it/s]

Bootstrapping recall:  94%|█████████▎| 937/1000 [00:00<00:00, 1169.60it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1151.75it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1196.26it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1156.90it/s]

Bootstrapping f1:  36%|███▌      | 356/1000 [00:00<00:00, 1151.42it/s]

Bootstrapping f1:  47%|████▋     | 472/1000 [00:00<00:00, 1142.74it/s]

Bootstrapping f1:  59%|█████▉    | 591/1000 [00:00<00:00, 1157.70it/s]

Bootstrapping f1:  71%|███████   | 708/1000 [00:00<00:00, 1159.69it/s]

Bootstrapping f1:  83%|████████▎ | 829/1000 [00:00<00:00, 1173.33it/s]

Bootstrapping f1:  95%|█████████▍| 949/1000 [00:00<00:00, 1180.14it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1168.94it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 345/1000 [00:00<00:00, 3443.80it/s]

Bootstrapping accuracy:  69%|██████▉   | 690/1000 [00:00<00:00, 3434.55it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3437.82it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1327.90it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1337.53it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 1329.08it/s]

Bootstrapping average_precision:  54%|█████▎    | 535/1000 [00:00<00:00, 1325.46it/s]

Bootstrapping average_precision:  67%|██████▋   | 668/1000 [00:00<00:00, 1314.75it/s]

Bootstrapping average_precision:  80%|████████  | 800/1000 [00:00<00:00, 1299.03it/s]

Bootstrapping average_precision:  93%|█████████▎| 930/1000 [00:00<00:00, 1295.66it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1302.16it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 820.87it/s]

Bootstrapping roc_auc:  17%|█▋        | 169/1000 [00:00<00:00, 838.03it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 847.89it/s]

Bootstrapping roc_auc:  34%|███▍      | 342/1000 [00:00<00:00, 852.98it/s]

Bootstrapping roc_auc:  43%|████▎     | 429/1000 [00:00<00:00, 856.34it/s]

Bootstrapping roc_auc:  52%|█████▏    | 515/1000 [00:00<00:00, 846.21it/s]

Bootstrapping roc_auc:  60%|██████    | 600/1000 [00:00<00:00, 844.72it/s]

Bootstrapping roc_auc:  68%|██████▊   | 685/1000 [00:00<00:00, 842.60it/s]

Bootstrapping roc_auc:  77%|███████▋  | 770/1000 [00:00<00:00, 843.62it/s]

Bootstrapping roc_auc:  86%|████████▌ | 855/1000 [00:01<00:00, 839.92it/s]

Bootstrapping roc_auc:  94%|█████████▍| 939/1000 [00:01<00:00, 830.16it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 838.67it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 113/1000 [00:00<00:00, 1122.00it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1160.59it/s]

Bootstrapping precision:  35%|███▍      | 349/1000 [00:00<00:00, 1163.95it/s]

Bootstrapping precision:  47%|████▋     | 468/1000 [00:00<00:00, 1171.10it/s]

Bootstrapping precision:  59%|█████▊    | 586/1000 [00:00<00:00, 1157.20it/s]

Bootstrapping precision:  70%|███████   | 702/1000 [00:00<00:00, 1133.14it/s]

Bootstrapping precision:  82%|████████▏ | 816/1000 [00:00<00:00, 1111.51it/s]

Bootstrapping precision:  93%|█████████▎| 929/1000 [00:00<00:00, 1114.58it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1131.39it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1165.16it/s]

Bootstrapping recall:  24%|██▎       | 235/1000 [00:00<00:00, 1168.56it/s]

Bootstrapping recall:  36%|███▌      | 357/1000 [00:00<00:00, 1191.04it/s]

Bootstrapping recall:  48%|████▊     | 479/1000 [00:00<00:00, 1198.97it/s]

Bootstrapping recall:  60%|██████    | 601/1000 [00:00<00:00, 1203.23it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1206.68it/s]

Bootstrapping recall:  84%|████████▍ | 844/1000 [00:00<00:00, 1194.29it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1193.43it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1192.44it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1179.14it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1148.18it/s]

Bootstrapping f1:  35%|███▌      | 353/1000 [00:00<00:00, 1154.66it/s]

Bootstrapping f1:  47%|████▋     | 469/1000 [00:00<00:00, 1149.67it/s]

Bootstrapping f1:  59%|█████▊    | 586/1000 [00:00<00:00, 1153.30it/s]

Bootstrapping f1:  70%|███████   | 702/1000 [00:00<00:00, 1128.36it/s]

Bootstrapping f1:  82%|████████▏ | 816/1000 [00:00<00:00, 1129.99it/s]

Bootstrapping f1:  93%|█████████▎| 930/1000 [00:00<00:00, 1117.48it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1130.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 335/1000 [00:00<00:00, 3348.13it/s]

Bootstrapping accuracy:  67%|██████▋   | 670/1000 [00:00<00:00, 3311.83it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3338.99it/s]

In [8]:
aurocs = []
auprcs = []
print(len(model_preds))
# Model Comparisons using DeLong Test
for (model1_name, model2_name) in combinations(model_preds.keys(), 2):
        if model1_name != 'Control': continue
        model1 = model_preds[model1_name]
        model2 = model_preds[model2_name]
        comparison_result1, comparison_result2 = compare_models(y_test.Outcome, model1, model2)
        aurocs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Z-score': f"{comparison_result1[0]:.4f}", 'P-value': f"{comparison_result1[1]:.3e}", 'p_numeric': comparison_result1[1]})
        auprcs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Avg Precision Model 1': f"{comparison_result2[0]:.4f}", 'Avg Precision Model 2': f"{comparison_result2[1]:.4f}", 'P-value': f"{comparison_result2[2]:.3e}", 'Benchmark': comparison_result2[3], 'Samples Mean': f"{comparison_result2[4]:.4f}", 'Samples Std': f"{comparison_result2[5]:.4f}"})
aurocs_df = pd.DataFrame(aurocs)
auprcs_df = pd.DataFrame(auprcs)
aurocs_df.to_csv('biomarker_counts_fixed/delong_test_biomarker_selection_auroc.csv', index=False)
auprcs_df.to_csv('biomarker_counts_fixed/delong_test_biomarker_selection_auprc.csv', index=False)
aurocs_df

11

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 703.67it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 688.58it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 211/1000 [00:00<00:01, 687.48it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 683.85it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 688.58it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 419/1000 [00:00<00:00, 688.46it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 488/1000 [00:00<00:00, 687.47it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 557/1000 [00:00<00:00, 687.53it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 626/1000 [00:00<00:00, 682.47it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 696/1000 [00:01<00:00, 687.53it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 765/1000 [00:01<00:00, 686.47it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 834/1000 [00:01<00:00, 684.97it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 903/1000 [00:01<00:00, 682.35it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 972/1000 [00:01<00:00, 678.97it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 684.65it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 685.00it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 679.01it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 208/1000 [00:00<00:01, 688.41it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 277/1000 [00:00<00:01, 687.33it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 346/1000 [00:00<00:00, 687.39it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 415/1000 [00:00<00:00, 681.82it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 484/1000 [00:00<00:00, 676.04it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 552/1000 [00:00<00:00, 672.54it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 622/1000 [00:00<00:00, 679.34it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 692/1000 [00:01<00:00, 684.80it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 762/1000 [00:01<00:00, 688.27it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 832/1000 [00:01<00:00, 689.96it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 902/1000 [00:01<00:00, 685.95it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 971/1000 [00:01<00:00, 671.77it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 681.00it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 671.66it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 687.35it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 208/1000 [00:00<00:01, 689.27it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 277/1000 [00:00<00:01, 687.95it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 346/1000 [00:00<00:00, 688.25it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 416/1000 [00:00<00:00, 690.34it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 486/1000 [00:00<00:00, 689.47it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 556/1000 [00:00<00:00, 690.14it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 626/1000 [00:00<00:00, 690.31it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 696/1000 [00:01<00:00, 683.03it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 765/1000 [00:01<00:00, 676.97it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 833/1000 [00:01<00:00, 674.37it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 903/1000 [00:01<00:00, 681.21it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 976/1000 [00:01<00:00, 693.52it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 687.42it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 685.63it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 684.17it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 207/1000 [00:00<00:01, 684.29it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 279/1000 [00:00<00:01, 694.58it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 696.54it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 420/1000 [00:00<00:00, 696.05it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 490/1000 [00:00<00:00, 696.37it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 560/1000 [00:00<00:00, 689.12it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 629/1000 [00:00<00:00, 672.37it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 697/1000 [00:01<00:00, 670.09it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 767/1000 [00:01<00:00, 676.36it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 836/1000 [00:01<00:00, 680.22it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 905/1000 [00:01<00:00, 677.57it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 977/1000 [00:01<00:00, 687.68it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 685.33it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 724.09it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 719.45it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 723.72it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 718.11it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 719.12it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 437/1000 [00:00<00:00, 711.34it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 509/1000 [00:00<00:00, 695.80it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 579/1000 [00:00<00:00, 692.83it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 649/1000 [00:00<00:00, 686.06it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 718/1000 [00:01<00:00, 678.35it/s]

Computing average_precision Permutation Test p-value:  79%|███████▊  | 787/1000 [00:01<00:00, 680.96it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 856/1000 [00:01<00:00, 681.61it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 926/1000 [00:01<00:00, 685.37it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 997/1000 [00:01<00:00, 690.35it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.66it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 706.87it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 707.37it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 699.97it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 693.15it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 686.04it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 683.55it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 493/1000 [00:00<00:00, 686.42it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 565/1000 [00:00<00:00, 694.80it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 638/1000 [00:00<00:00, 702.83it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 710/1000 [00:01<00:00, 707.87it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 782/1000 [00:01<00:00, 709.40it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 853/1000 [00:01<00:00, 700.20it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 924/1000 [00:01<00:00, 699.47it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 995/1000 [00:01<00:00, 701.85it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 698.35it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 717.64it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 716.03it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 713.82it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:00, 715.26it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 360/1000 [00:00<00:00, 710.69it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 696.96it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 502/1000 [00:00<00:00, 682.60it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 673.55it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 642/1000 [00:00<00:00, 684.37it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 712/1000 [00:01<00:00, 688.81it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 782/1000 [00:01<00:00, 689.55it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 852/1000 [00:01<00:00, 690.63it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 922/1000 [00:01<00:00, 689.89it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 992/1000 [00:01<00:00, 678.36it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 690.69it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 693.51it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 702.91it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 709.04it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 711.24it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 358/1000 [00:00<00:00, 714.02it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 431/1000 [00:00<00:00, 716.89it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 504/1000 [00:00<00:00, 718.19it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 576/1000 [00:00<00:00, 717.56it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 649/1000 [00:00<00:00, 719.98it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 722/1000 [00:01<00:00, 721.44it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 795/1000 [00:01<00:00, 722.63it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 868/1000 [00:01<00:00, 722.79it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 941/1000 [00:01<00:00, 720.68it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 717.72it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 726.95it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 714.33it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 707.36it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 290/1000 [00:00<00:01, 708.71it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 361/1000 [00:00<00:00, 700.11it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 692.99it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 502/1000 [00:00<00:00, 682.98it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 685.13it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 643/1000 [00:00<00:00, 694.16it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 716/1000 [00:01<00:00, 702.48it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 789/1000 [00:01<00:00, 709.32it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 860/1000 [00:01<00:00, 701.25it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 931/1000 [00:01<00:00, 703.83it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 702.03it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 722.71it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 722.82it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 712.97it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 291/1000 [00:00<00:00, 711.76it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 364/1000 [00:00<00:00, 715.58it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 437/1000 [00:00<00:00, 716.64it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 510/1000 [00:00<00:00, 718.66it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 582/1000 [00:00<00:00, 718.97it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 654/1000 [00:00<00:00, 718.08it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 726/1000 [00:01<00:00, 715.07it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 799/1000 [00:01<00:00, 716.44it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 871/1000 [00:01<00:00, 709.94it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 943/1000 [00:01<00:00, 695.75it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 708.83it/s]

,Model 1,Model 2,Z-score,P-value,p_numeric
0,Control,Correlation,-5.0469,4.491e-07,4.491476e-07
1,Control,Simplified Clinician Consensus $\cup$ Simplifi...,-3.9838,6.782e-05,6.782344e-05
2,Control,Simplified Clinician Consensus $\cup$ Simplifi...,-3.9688,7.224e-05,7.224461e-05
3,Control,Simplified Golem $\cup$ Simplified PCMB,-3.4346,5.934e-04,5.933930e-04
4,Control,Simplified Clinician Consensus,-3.5534,3.803e-04,3.803083e-04
5,Control,Simplified Clinician Consensus $\cap$ Simplifi...,-3.5869,3.346e-04,3.345848e-04
6,Control,Simplified PCMB,-3.7981,1.458e-04,1.457824e-04
7,Control,Simplified Golem,-3.1809,1.468e-03,1.468225e-03
8,Control,Simplified Golem $\cap$ Simplified PCMB,-3.7163,2.022e-04,2.021565e-04
9,Control,Simplified Clinician Consensus $\cap$ Simplifi...,-5.5644,2.630e-08,2.630400e-08

In [9]:
pd.DataFrame(results).to_csv('biomarker_counts_fixed/Biomarker Selection.csv', index=False)
pd.DataFrame(results)

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,LGBN,Control,"0.76 (0.72, 0.80)","0.90 (0.88, 0.92)","0.95 (0.93, 0.96)","0.78 (0.76, 0.81)","0.84 (0.82, 0.86)","0.95 (0.94, 0.96)",0.137,811,45
1,XGB,Control,"0.81 (0.78, 0.84)","0.93 (0.91, 0.95)","0.94 (0.92, 0.95)","0.80 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.089,811,45
2,LGBN,Correlation,"0.73 (0.69, 0.76)","0.87 (0.84, 0.89)","0.95 (0.93, 0.96)","0.74 (0.72, 0.77)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.133,113,37
3,XGB,Correlation,"0.75 (0.71, 0.78)","0.90 (0.88, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.108,113,37
4,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.75 (0.71, 0.79)","0.90 (0.88, 0.92)","0.93 (0.92, 0.95)","0.76 (0.74, 0.79)","0.82 (0.80, 0.84)","0.94 (0.94, 0.95)",0.134,334,19
5,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.77 (0.74, 0.81)","0.91 (0.89, 0.93)","0.92 (0.91, 0.94)","0.79 (0.77, 0.82)","0.84 (0.82, 0.87)","0.95 (0.94, 0.96)",0.092,334,19
6,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.74 (0.70, 0.78)","0.90 (0.88, 0.92)","0.93 (0.91, 0.95)","0.77 (0.75, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.140,408,23
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.79 (0.76, 0.82)","0.91 (0.89, 0.93)","0.93 (0.91, 0.95)","0.80 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.094,408,23
8,LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.74 (0.71, 0.78)","0.90 (0.88, 0.92)","0.93 (0.92, 0.95)","0.76 (0.74, 0.79)","0.82 (0.80, 0.84)","0.94 (0.94, 0.95)",0.138,407,23
9,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.78 (0.75, 0.81)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.94 (0.94, 0.95)",0.093,407,23
10,LGBN,Simplified Clinician Consensus,"0.75 (0.72, 0.79)","0.90 (0.88, 0.92)","0.94 (0.92, 0.96)","0.76 (0.74, 0.79)","0.82 (0.80, 0.84)","0.94 (0.94, 0.95)",0.133,278,16
11,XGB,Simplified Clinician Consensus,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.94 (0.92, 0.95)","0.80 (0.77, 0.82)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.094,278,16
12,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.75 (0.72, 0.79)","0.90 (0.88, 0.92)","0.95 (0.93, 0.96)","0.76 (0.74, 0.78)","0.82 (0.80, 0.84)","0.94 (0.94, 0.95)",0.132,240,14
13,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.79 (0.75, 0.82)","0.91 (0.89, 0.93)","0.93 (0.91, 0.94)","0.80 (0.77, 0.82)","0.85 (0.82, 0.86)","0.95 (0.94, 0.96)",0.095,240,14
14,LGBN,Simplified PCMB,"0.75 (0.71, 0.79)","0.90 (0.88, 0.92)","0.94 (0.92, 0.95)","0.76 (0.74, 0.79)","0.82 (0.80, 0.85)","0.94 (0.94, 0.95)",0.133,296,17
15,XGB,Simplified PCMB,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.92 (0.91, 0.94)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.092,296,17
16,LGBN,Simplified Golem,"0.73 (0.70, 0.77)","0.90 (0.88, 0.91)","0.92 (0.90, 0.94)","0.75 (0.73, 0.78)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.138,199,11
17,XGB,Simplified Golem,"0.77 (0.74, 0.80)","0.91 (0.89, 0.93)","0.91 (0.90, 0.93)","0.79 (0.76, 0.81)","0.83 (0.82, 0.86)","0.94 (0.94, 0.95)",0.095,199,11
18,LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.71 (0.67, 0.76)","0.89 (0.87, 0.91)","0.93 (0.91, 0.94)","0.74 (0.71, 0.76)","0.80 (0.77, 0.82)","0.94 (0.93, 0.95)",0.131,88,5
19,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.76 (0.73, 0.80)","0.90 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,88,5
20,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.72 (0.67, 0.75)","0.88 (0.86, 0.90)","0.94 (0.92, 0.95)","0.73 (0.70, 0.75)","0.79 (0.77, 0.81)","0.94 (0.93, 0.94)",0.130,69,4
21,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.76, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.106,69,4

In [10]:
# Plot calibration curves
for dag_name in calibrations:
    plt.figure(dpi=300, layout='constrained', figsize=(8, 5))
    plt.rcParams['font.size'] = 18
    prob_true, prob_pred = calibrations[dag_name]
    plt.plot(prob_pred, prob_true, marker='o', label='Calibration Curve')
    plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Perfect Calibration')
    plt.xlabel('Predicted Probability')
    plt.ylabel('True Probability')
    plt.xticks(np.arange(0, 1.1, 0.1))
    plt.grid()
    plt.savefig(f'biomarker_counts_fixed/Calibration Curves/Biomarker Selection - {dag_name.replace(" ", "_").replace("$\\cap$", "AND").replace("$\\cup$", "OR")}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

In [11]:
vals = shap_values_biomarker_summary(shap_values)
auprc_top10 = pd.DataFrame(results).sort_values(by=['Average Precision'], ascending=False).head(10).DAG.unique().tolist()
plt.rcParams.update({  
'figure.figsize': (8, 10),   # Default figure size (inches)  
'figure.dpi': 300,          # Default DPI for figure creation  
'ytick.labelsize': 16,
'xtick.labelsize': 16,
'font.size': 18,
'lines.linewidth': 2,       # Default line width  
'figure.constrained_layout.use': True,
'pdf.fonttype': 42
}) 
for dag_name in auprc_top10:
    df = vals[dag_name].sort_values(ascending=True)
    plt.barh(df.index, df)
    plt.xlabel('Mean |SHAP value|')
    plt.ylabel('Biomarker')
    plt.savefig(f'biomarker_counts_fixed/Feature Importance/Biomarker Selection - {dag_name}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

## Experiment 2: No Drugs

In [12]:
results, shap_values, calibrations, model_preds = train_models(remove_drugs=True, remove_interventions=False)

Processing Control with 46 nodes and 45 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 139/1000 [00:00<00:00, 1389.68it/s]

Bootstrapping average_precision:  28%|██▊       | 279/1000 [00:00<00:00, 1390.87it/s]

Bootstrapping average_precision:  42%|████▏     | 419/1000 [00:00<00:00, 1375.10it/s]

Bootstrapping average_precision:  56%|█████▌    | 557/1000 [00:00<00:00, 1374.59it/s]

Bootstrapping average_precision:  70%|██████▉   | 696/1000 [00:00<00:00, 1377.59it/s]

Bootstrapping average_precision:  83%|████████▎ | 834/1000 [00:00<00:00, 1368.96it/s]

Bootstrapping average_precision:  97%|█████████▋| 972/1000 [00:00<00:00, 1372.37it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1375.10it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 858.50it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 861.74it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 865.83it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 871.24it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 873.36it/s]

Bootstrapping roc_auc:  53%|█████▎    | 526/1000 [00:00<00:00, 867.62it/s]

Bootstrapping roc_auc:  61%|██████▏   | 613/1000 [00:00<00:00, 866.14it/s]

Bootstrapping roc_auc:  70%|███████   | 700/1000 [00:00<00:00, 863.28it/s]

Bootstrapping roc_auc:  79%|███████▊  | 787/1000 [00:00<00:00, 860.42it/s]

Bootstrapping roc_auc:  87%|████████▋ | 874/1000 [00:01<00:00, 861.67it/s]

Bootstrapping roc_auc:  96%|█████████▋| 963/1000 [00:01<00:00, 867.94it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 865.83it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1189.48it/s]

Bootstrapping precision:  24%|██▍       | 238/1000 [00:00<00:00, 1178.87it/s]

Bootstrapping precision:  36%|███▌      | 356/1000 [00:00<00:00, 1169.29it/s]

Bootstrapping precision:  47%|████▋     | 474/1000 [00:00<00:00, 1170.79it/s]

Bootstrapping precision:  59%|█████▉    | 594/1000 [00:00<00:00, 1179.19it/s]

Bootstrapping precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1182.34it/s]

Bootstrapping precision:  83%|████████▎ | 832/1000 [00:00<00:00, 1181.53it/s]

Bootstrapping precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1166.92it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1174.75it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1184.04it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1185.98it/s]

Bootstrapping recall:  36%|███▌      | 357/1000 [00:00<00:00, 1180.96it/s]

Bootstrapping recall:  48%|████▊     | 476/1000 [00:00<00:00, 1171.10it/s]

Bootstrapping recall:  59%|█████▉    | 594/1000 [00:00<00:00, 1163.70it/s]

Bootstrapping recall:  71%|███████   | 711/1000 [00:00<00:00, 1162.08it/s]

Bootstrapping recall:  83%|████████▎ | 828/1000 [00:00<00:00, 1152.40it/s]

Bootstrapping recall:  94%|█████████▍| 944/1000 [00:00<00:00, 1147.64it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1153.22it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  10%|▉         | 98/1000 [00:00<00:00, 972.95it/s]

Bootstrapping f1:  21%|██        | 207/1000 [00:00<00:00, 1040.02it/s]

Bootstrapping f1:  32%|███▏      | 316/1000 [00:00<00:00, 1058.82it/s]

Bootstrapping f1:  43%|████▎     | 426/1000 [00:00<00:00, 1071.78it/s]

Bootstrapping f1:  54%|█████▎    | 537/1000 [00:00<00:00, 1083.50it/s]

Bootstrapping f1:  65%|██████▍   | 649/1000 [00:00<00:00, 1095.47it/s]

Bootstrapping f1:  76%|███████▌  | 759/1000 [00:00<00:00, 1085.66it/s]

Bootstrapping f1:  87%|████████▋ | 872/1000 [00:00<00:00, 1098.81it/s]

Bootstrapping f1:  99%|█████████▉| 988/1000 [00:00<00:00, 1114.60it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1086.40it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 335/1000 [00:00<00:00, 3342.07it/s]

Bootstrapping accuracy:  68%|██████▊   | 680/1000 [00:00<00:00, 3401.34it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3393.57it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1345.05it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1347.20it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1340.64it/s]

Bootstrapping average_precision:  54%|█████▍    | 540/1000 [00:00<00:00, 1323.22it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1324.39it/s]

Bootstrapping average_precision:  81%|████████  | 806/1000 [00:00<00:00, 1285.14it/s]

Bootstrapping average_precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1294.40it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1310.65it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 860.82it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 858.40it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 859.42it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 850.51it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 818.32it/s]

Bootstrapping roc_auc:  52%|█████▏    | 516/1000 [00:00<00:00, 802.40it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 796.94it/s]

Bootstrapping roc_auc:  68%|██████▊   | 677/1000 [00:00<00:00, 791.06it/s]

Bootstrapping roc_auc:  76%|███████▌  | 757/1000 [00:00<00:00, 792.42it/s]

Bootstrapping roc_auc:  84%|████████▍ | 845/1000 [00:01<00:00, 817.66it/s]

Bootstrapping roc_auc:  93%|█████████▎| 928/1000 [00:01<00:00, 820.39it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 818.50it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1171.90it/s]

Bootstrapping precision:  24%|██▍       | 239/1000 [00:00<00:00, 1193.64it/s]

Bootstrapping precision:  36%|███▌      | 360/1000 [00:00<00:00, 1196.58it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1198.65it/s]

Bootstrapping precision:  60%|██████    | 602/1000 [00:00<00:00, 1200.95it/s]

Bootstrapping precision:  72%|███████▏  | 723/1000 [00:00<00:00, 1188.81it/s]

Bootstrapping precision:  84%|████████▍ | 842/1000 [00:00<00:00, 1152.53it/s]

Bootstrapping precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1126.90it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1155.89it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 111/1000 [00:00<00:00, 1106.51it/s]

Bootstrapping recall:  22%|██▏       | 222/1000 [00:00<00:00, 1090.13it/s]

Bootstrapping recall:  34%|███▎      | 336/1000 [00:00<00:00, 1110.30it/s]

Bootstrapping recall:  45%|████▌     | 452/1000 [00:00<00:00, 1129.18it/s]

Bootstrapping recall:  56%|█████▋    | 565/1000 [00:00<00:00, 1111.45it/s]

Bootstrapping recall:  68%|██████▊   | 677/1000 [00:00<00:00, 1092.60it/s]

Bootstrapping recall:  79%|███████▉  | 791/1000 [00:00<00:00, 1107.12it/s]

Bootstrapping recall:  90%|█████████ | 902/1000 [00:00<00:00, 1105.93it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1095.59it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 112/1000 [00:00<00:00, 1117.21it/s]

Bootstrapping f1:  22%|██▎       | 225/1000 [00:00<00:00, 1122.75it/s]

Bootstrapping f1:  34%|███▍      | 345/1000 [00:00<00:00, 1154.58it/s]

Bootstrapping f1:  47%|████▋     | 467/1000 [00:00<00:00, 1176.36it/s]

Bootstrapping f1:  59%|█████▉    | 588/1000 [00:00<00:00, 1184.61it/s]

Bootstrapping f1:  71%|███████   | 708/1000 [00:00<00:00, 1186.86it/s]

Bootstrapping f1:  83%|████████▎ | 830/1000 [00:00<00:00, 1196.72it/s]

Bootstrapping f1:  95%|█████████▌| 950/1000 [00:00<00:00, 1197.06it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1181.14it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 355/1000 [00:00<00:00, 3549.25it/s]

Bootstrapping accuracy:  71%|███████   | 710/1000 [00:00<00:00, 3472.87it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3500.18it/s]

Processing Correlation with 38 nodes and 37 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1333.41it/s]

Bootstrapping average_precision:  27%|██▋       | 269/1000 [00:00<00:00, 1342.45it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 1319.37it/s]

Bootstrapping average_precision:  54%|█████▎    | 537/1000 [00:00<00:00, 1323.23it/s]

Bootstrapping average_precision:  67%|██████▋   | 672/1000 [00:00<00:00, 1330.28it/s]

Bootstrapping average_precision:  81%|████████  | 808/1000 [00:00<00:00, 1340.07it/s]

Bootstrapping average_precision:  94%|█████████▍| 943/1000 [00:00<00:00, 1327.62it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1329.75it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 848.59it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 862.81it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 863.72it/s]

Bootstrapping roc_auc:  35%|███▍      | 349/1000 [00:00<00:00, 870.38it/s]

Bootstrapping roc_auc:  44%|████▍     | 439/1000 [00:00<00:00, 877.25it/s]

Bootstrapping roc_auc:  53%|█████▎    | 527/1000 [00:00<00:00, 872.19it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 862.87it/s]

Bootstrapping roc_auc:  70%|███████   | 702/1000 [00:00<00:00, 853.05it/s]

Bootstrapping roc_auc:  79%|███████▉  | 788/1000 [00:00<00:00, 852.77it/s]

Bootstrapping roc_auc:  88%|████████▊ | 876/1000 [00:01<00:00, 859.48it/s]

Bootstrapping roc_auc:  96%|█████████▌| 962/1000 [00:01<00:00, 857.78it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 858.66it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 117/1000 [00:00<00:00, 1161.87it/s]

Bootstrapping precision:  23%|██▎       | 234/1000 [00:00<00:00, 1154.49it/s]

Bootstrapping precision:  35%|███▌      | 351/1000 [00:00<00:00, 1160.87it/s]

Bootstrapping precision:  47%|████▋     | 471/1000 [00:00<00:00, 1173.19it/s]

Bootstrapping precision:  59%|█████▉    | 591/1000 [00:00<00:00, 1182.09it/s]

Bootstrapping precision:  71%|███████   | 710/1000 [00:00<00:00, 1181.62it/s]

Bootstrapping precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1171.53it/s]

Bootstrapping precision:  95%|█████████▍| 947/1000 [00:00<00:00, 1160.05it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1164.90it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1152.75it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1178.77it/s]

Bootstrapping recall:  36%|███▌      | 356/1000 [00:00<00:00, 1188.21it/s]

Bootstrapping recall:  48%|████▊     | 476/1000 [00:00<00:00, 1190.79it/s]

Bootstrapping recall:  60%|█████▉    | 596/1000 [00:00<00:00, 1161.49it/s]

Bootstrapping recall:  71%|███████▏  | 713/1000 [00:00<00:00, 1144.66it/s]

Bootstrapping recall:  83%|████████▎ | 828/1000 [00:00<00:00, 1140.85it/s]

Bootstrapping recall:  94%|█████████▍| 943/1000 [00:00<00:00, 1133.17it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1150.87it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1149.55it/s]

Bootstrapping f1:  24%|██▎       | 235/1000 [00:00<00:00, 1168.99it/s]

Bootstrapping f1:  36%|███▌      | 356/1000 [00:00<00:00, 1183.86it/s]

Bootstrapping f1:  48%|████▊     | 475/1000 [00:00<00:00, 1179.82it/s]

Bootstrapping f1:  59%|█████▉    | 593/1000 [00:00<00:00, 1179.23it/s]

Bootstrapping f1:  71%|███████   | 711/1000 [00:00<00:00, 1176.20it/s]

Bootstrapping f1:  83%|████████▎ | 829/1000 [00:00<00:00, 1168.19it/s]

Bootstrapping f1:  95%|█████████▍| 946/1000 [00:00<00:00, 1143.74it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1159.60it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 340/1000 [00:00<00:00, 3396.84it/s]

Bootstrapping accuracy:  69%|██████▉   | 692/1000 [00:00<00:00, 3464.96it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3471.56it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 127/1000 [00:00<00:00, 1266.53it/s]

Bootstrapping average_precision:  26%|██▌       | 256/1000 [00:00<00:00, 1272.92it/s]

Bootstrapping average_precision:  38%|███▊      | 385/1000 [00:00<00:00, 1278.77it/s]

Bootstrapping average_precision:  52%|█████▏    | 517/1000 [00:00<00:00, 1292.92it/s]

Bootstrapping average_precision:  65%|██████▍   | 647/1000 [00:00<00:00, 1295.05it/s]

Bootstrapping average_precision:  78%|███████▊  | 779/1000 [00:00<00:00, 1301.04it/s]

Bootstrapping average_precision:  91%|█████████ | 910/1000 [00:00<00:00, 1303.61it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1294.74it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 80/1000 [00:00<00:01, 795.07it/s]

Bootstrapping roc_auc:  16%|█▌        | 160/1000 [00:00<00:01, 791.42it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 806.45it/s]

Bootstrapping roc_auc:  33%|███▎      | 328/1000 [00:00<00:00, 822.33it/s]

Bootstrapping roc_auc:  41%|████      | 411/1000 [00:00<00:00, 815.03it/s]

Bootstrapping roc_auc:  49%|████▉     | 493/1000 [00:00<00:00, 810.17it/s]

Bootstrapping roc_auc:  58%|█████▊    | 576/1000 [00:00<00:00, 815.63it/s]

Bootstrapping roc_auc:  66%|██████▌   | 661/1000 [00:00<00:00, 825.75it/s]

Bootstrapping roc_auc:  75%|███████▍  | 748/1000 [00:00<00:00, 837.29it/s]

Bootstrapping roc_auc:  83%|████████▎ | 834/1000 [00:01<00:00, 842.38it/s]

Bootstrapping roc_auc:  92%|█████████▏| 919/1000 [00:01<00:00, 819.31it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 817.94it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 112/1000 [00:00<00:00, 1116.33it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1151.50it/s]

Bootstrapping precision:  35%|███▍      | 346/1000 [00:00<00:00, 1129.11it/s]

Bootstrapping precision:  46%|████▌     | 459/1000 [00:00<00:00, 1125.60it/s]

Bootstrapping precision:  57%|█████▋    | 572/1000 [00:00<00:00, 1100.07it/s]

Bootstrapping precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1088.81it/s]

Bootstrapping precision:  79%|███████▉  | 792/1000 [00:00<00:00, 1081.94it/s]

Bootstrapping precision:  90%|█████████ | 902/1000 [00:00<00:00, 1085.49it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1108.16it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1195.02it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1202.38it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1176.37it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1144.85it/s]

Bootstrapping recall:  60%|█████▉    | 595/1000 [00:00<00:00, 1137.00it/s]

Bootstrapping recall:  71%|███████▏  | 713/1000 [00:00<00:00, 1148.74it/s]

Bootstrapping recall:  83%|████████▎ | 828/1000 [00:00<00:00, 1141.20it/s]

Bootstrapping recall:  95%|█████████▍| 946/1000 [00:00<00:00, 1151.65it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1156.98it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1163.63it/s]

Bootstrapping f1:  23%|██▎       | 234/1000 [00:00<00:00, 1142.49it/s]

Bootstrapping f1:  35%|███▍      | 349/1000 [00:00<00:00, 1127.82it/s]

Bootstrapping f1:  46%|████▌     | 462/1000 [00:00<00:00, 1119.40it/s]

Bootstrapping f1:  57%|█████▋    | 574/1000 [00:00<00:00, 1108.55it/s]

Bootstrapping f1:  69%|██████▊   | 686/1000 [00:00<00:00, 1111.20it/s]

Bootstrapping f1:  80%|████████  | 801/1000 [00:00<00:00, 1120.94it/s]

Bootstrapping f1:  92%|█████████▏| 916/1000 [00:00<00:00, 1129.21it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1125.15it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 339/1000 [00:00<00:00, 3389.83it/s]

Bootstrapping accuracy:  68%|██████▊   | 678/1000 [00:00<00:00, 3333.55it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3337.28it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB with 20 nodes and 53 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1314.39it/s]

Bootstrapping average_precision:  26%|██▋       | 265/1000 [00:00<00:00, 1323.10it/s]

Bootstrapping average_precision:  40%|████      | 400/1000 [00:00<00:00, 1333.40it/s]

Bootstrapping average_precision:  54%|█████▍    | 538/1000 [00:00<00:00, 1351.64it/s]

Bootstrapping average_precision:  68%|██████▊   | 679/1000 [00:00<00:00, 1371.66it/s]

Bootstrapping average_precision:  82%|████████▏ | 818/1000 [00:00<00:00, 1377.61it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1380.36it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1364.82it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 872.22it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 861.45it/s]

Bootstrapping roc_auc:  26%|██▋       | 265/1000 [00:00<00:00, 871.37it/s]

Bootstrapping roc_auc:  35%|███▌      | 354/1000 [00:00<00:00, 877.18it/s]

Bootstrapping roc_auc:  44%|████▍     | 442/1000 [00:00<00:00, 872.61it/s]

Bootstrapping roc_auc:  53%|█████▎    | 530/1000 [00:00<00:00, 864.42it/s]

Bootstrapping roc_auc:  62%|██████▏   | 617/1000 [00:00<00:00, 862.82it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 854.16it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 852.44it/s]

Bootstrapping roc_auc:  88%|████████▊ | 876/1000 [00:01<00:00, 848.51it/s]

Bootstrapping roc_auc:  96%|█████████▌| 961/1000 [00:01<00:00, 847.04it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 856.25it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1140.45it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1156.31it/s]

Bootstrapping precision:  35%|███▍      | 348/1000 [00:00<00:00, 1148.91it/s]

Bootstrapping precision:  46%|████▋     | 463/1000 [00:00<00:00, 1135.02it/s]

Bootstrapping precision:  58%|█████▊    | 577/1000 [00:00<00:00, 1136.26it/s]

Bootstrapping precision:  69%|██████▉   | 693/1000 [00:00<00:00, 1140.82it/s]

Bootstrapping precision:  81%|████████  | 811/1000 [00:00<00:00, 1149.90it/s]

Bootstrapping precision:  93%|█████████▎| 927/1000 [00:00<00:00, 1152.97it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1148.23it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1151.93it/s]

Bootstrapping recall:  23%|██▎       | 232/1000 [00:00<00:00, 1141.39it/s]

Bootstrapping recall:  35%|███▍      | 348/1000 [00:00<00:00, 1145.57it/s]

Bootstrapping recall:  46%|████▋     | 463/1000 [00:00<00:00, 1132.37it/s]

Bootstrapping recall:  58%|█████▊    | 579/1000 [00:00<00:00, 1139.96it/s]

Bootstrapping recall:  70%|██████▉   | 697/1000 [00:00<00:00, 1150.39it/s]

Bootstrapping recall:  81%|████████▏ | 814/1000 [00:00<00:00, 1153.56it/s]

Bootstrapping recall:  93%|█████████▎| 931/1000 [00:00<00:00, 1157.00it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1150.03it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1144.38it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1128.94it/s]

Bootstrapping f1:  34%|███▍      | 343/1000 [00:00<00:00, 1125.76it/s]

Bootstrapping f1:  46%|████▌     | 459/1000 [00:00<00:00, 1137.53it/s]

Bootstrapping f1:  58%|█████▊    | 578/1000 [00:00<00:00, 1155.43it/s]

Bootstrapping f1:  70%|██████▉   | 697/1000 [00:00<00:00, 1164.71it/s]

Bootstrapping f1:  82%|████████▏ | 816/1000 [00:00<00:00, 1170.14it/s]

Bootstrapping f1:  93%|█████████▎| 934/1000 [00:00<00:00, 1162.67it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1155.27it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 344/1000 [00:00<00:00, 3428.83it/s]

Bootstrapping accuracy:  69%|██████▉   | 690/1000 [00:00<00:00, 3442.65it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3457.21it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1320.39it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1335.61it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 1335.28it/s]

Bootstrapping average_precision:  54%|█████▎    | 536/1000 [00:00<00:00, 1329.56it/s]

Bootstrapping average_precision:  67%|██████▋   | 669/1000 [00:00<00:00, 1328.57it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1324.62it/s]

Bootstrapping average_precision:  94%|█████████▎| 935/1000 [00:00<00:00, 1321.73it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1316.89it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 81/1000 [00:00<00:01, 804.81it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 804.92it/s]

Bootstrapping roc_auc:  24%|██▍       | 245/1000 [00:00<00:00, 811.83it/s]

Bootstrapping roc_auc:  33%|███▎      | 327/1000 [00:00<00:00, 809.69it/s]

Bootstrapping roc_auc:  41%|████      | 408/1000 [00:00<00:00, 807.56it/s]

Bootstrapping roc_auc:  49%|████▉     | 490/1000 [00:00<00:00, 810.68it/s]

Bootstrapping roc_auc:  57%|█████▋    | 572/1000 [00:00<00:00, 812.28it/s]

Bootstrapping roc_auc:  66%|██████▌   | 655/1000 [00:00<00:00, 816.28it/s]

Bootstrapping roc_auc:  74%|███████▍  | 739/1000 [00:00<00:00, 822.73it/s]

Bootstrapping roc_auc:  82%|████████▏ | 822/1000 [00:01<00:00, 803.46it/s]

Bootstrapping roc_auc:  90%|█████████ | 903/1000 [00:01<00:00, 803.22it/s]

Bootstrapping roc_auc:  98%|█████████▊| 984/1000 [00:01<00:00, 795.10it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 804.13it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 110/1000 [00:00<00:00, 1092.04it/s]

Bootstrapping precision:  22%|██▎       | 225/1000 [00:00<00:00, 1123.87it/s]

Bootstrapping precision:  34%|███▍      | 338/1000 [00:00<00:00, 1117.12it/s]

Bootstrapping precision:  45%|████▌     | 452/1000 [00:00<00:00, 1124.68it/s]

Bootstrapping precision:  57%|█████▋    | 566/1000 [00:00<00:00, 1129.45it/s]

Bootstrapping precision:  68%|██████▊   | 680/1000 [00:00<00:00, 1131.58it/s]

Bootstrapping precision:  79%|███████▉  | 794/1000 [00:00<00:00, 1121.06it/s]

Bootstrapping precision:  91%|█████████ | 907/1000 [00:00<00:00, 1107.99it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1117.45it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1143.51it/s]

Bootstrapping recall:  23%|██▎       | 231/1000 [00:00<00:00, 1151.03it/s]

Bootstrapping recall:  35%|███▌      | 351/1000 [00:00<00:00, 1169.88it/s]

Bootstrapping recall:  47%|████▋     | 470/1000 [00:00<00:00, 1177.42it/s]

Bootstrapping recall:  59%|█████▉    | 588/1000 [00:00<00:00, 1162.73it/s]

Bootstrapping recall:  70%|███████   | 705/1000 [00:00<00:00, 1157.56it/s]

Bootstrapping recall:  82%|████████▏ | 821/1000 [00:00<00:00, 1156.48it/s]

Bootstrapping recall:  94%|█████████▎| 937/1000 [00:00<00:00, 1156.13it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1158.25it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1122.50it/s]

Bootstrapping f1:  23%|██▎       | 226/1000 [00:00<00:00, 1118.82it/s]

Bootstrapping f1:  34%|███▍      | 339/1000 [00:00<00:00, 1119.39it/s]

Bootstrapping f1:  45%|████▌     | 451/1000 [00:00<00:00, 1109.35it/s]

Bootstrapping f1:  56%|█████▌    | 562/1000 [00:00<00:00, 1102.64it/s]

Bootstrapping f1:  68%|██████▊   | 675/1000 [00:00<00:00, 1111.67it/s]

Bootstrapping f1:  79%|███████▉  | 793/1000 [00:00<00:00, 1131.29it/s]

Bootstrapping f1:  91%|█████████ | 907/1000 [00:00<00:00, 1127.90it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1120.28it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  32%|███▏      | 320/1000 [00:00<00:00, 3197.50it/s]

Bootstrapping accuracy:  65%|██████▌   | 654/1000 [00:00<00:00, 3279.02it/s]

Bootstrapping accuracy:  99%|█████████▉| 989/1000 [00:00<00:00, 3309.45it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3286.08it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem with 24 nodes and 35 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  11%|█         | 107/1000 [00:00<00:00, 1044.09it/s]

Bootstrapping average_precision:  23%|██▎       | 229/1000 [00:00<00:00, 1143.22it/s]

Bootstrapping average_precision:  34%|███▍      | 344/1000 [00:00<00:00, 1044.96it/s]

Bootstrapping average_precision:  47%|████▋     | 474/1000 [00:00<00:00, 1139.56it/s]

Bootstrapping average_precision:  61%|██████    | 606/1000 [00:00<00:00, 1201.44it/s]

Bootstrapping average_precision:  74%|███████▍  | 742/1000 [00:00<00:00, 1252.31it/s]

Bootstrapping average_precision:  87%|████████▋ | 873/1000 [00:00<00:00, 1270.74it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1222.77it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 82/1000 [00:00<00:01, 813.75it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 826.24it/s]

Bootstrapping roc_auc:  25%|██▌       | 251/1000 [00:00<00:00, 834.96it/s]

Bootstrapping roc_auc:  34%|███▎      | 336/1000 [00:00<00:00, 837.18it/s]

Bootstrapping roc_auc:  42%|████▏     | 420/1000 [00:00<00:00, 825.85it/s]

Bootstrapping roc_auc:  50%|█████     | 505/1000 [00:00<00:00, 831.51it/s]

Bootstrapping roc_auc:  59%|█████▉    | 592/1000 [00:00<00:00, 840.67it/s]

Bootstrapping roc_auc:  68%|██████▊   | 677/1000 [00:00<00:00, 832.16it/s]

Bootstrapping roc_auc:  76%|███████▌  | 761/1000 [00:00<00:00, 827.93it/s]

Bootstrapping roc_auc:  84%|████████▍ | 844/1000 [00:01<00:00, 827.20it/s]

Bootstrapping roc_auc:  93%|█████████▎| 927/1000 [00:01<00:00, 817.78it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 827.71it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 112/1000 [00:00<00:00, 1112.60it/s]

Bootstrapping precision:  22%|██▏       | 224/1000 [00:00<00:00, 1116.86it/s]

Bootstrapping precision:  34%|███▎      | 336/1000 [00:00<00:00, 1112.75it/s]

Bootstrapping precision:  45%|████▍     | 448/1000 [00:00<00:00, 1103.05it/s]

Bootstrapping precision:  56%|█████▌    | 561/1000 [00:00<00:00, 1111.37it/s]

Bootstrapping precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1020.41it/s]

Bootstrapping precision:  78%|███████▊  | 782/1000 [00:00<00:00, 1039.94it/s]

Bootstrapping precision:  89%|████████▉ | 893/1000 [00:00<00:00, 1061.22it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1079.36it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 110/1000 [00:00<00:00, 1098.03it/s]

Bootstrapping recall:  22%|██▏       | 220/1000 [00:00<00:00, 1050.14it/s]

Bootstrapping recall:  33%|███▎      | 332/1000 [00:00<00:00, 1081.23it/s]

Bootstrapping recall:  45%|████▍     | 446/1000 [00:00<00:00, 1100.23it/s]

Bootstrapping recall:  56%|█████▌    | 560/1000 [00:00<00:00, 1112.03it/s]

Bootstrapping recall:  68%|██████▊   | 675/1000 [00:00<00:00, 1122.04it/s]

Bootstrapping recall:  79%|███████▉  | 792/1000 [00:00<00:00, 1136.07it/s]

Bootstrapping recall:  91%|█████████ | 909/1000 [00:00<00:00, 1146.01it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1127.02it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1153.13it/s]

Bootstrapping f1:  23%|██▎       | 234/1000 [00:00<00:00, 1163.90it/s]

Bootstrapping f1:  35%|███▌      | 352/1000 [00:00<00:00, 1168.21it/s]

Bootstrapping f1:  47%|████▋     | 469/1000 [00:00<00:00, 1167.20it/s]

Bootstrapping f1:  59%|█████▊    | 586/1000 [00:00<00:00, 1166.42it/s]

Bootstrapping f1:  70%|███████   | 703/1000 [00:00<00:00, 1149.17it/s]

Bootstrapping f1:  82%|████████▏ | 818/1000 [00:00<00:00, 1138.43it/s]

Bootstrapping f1:  93%|█████████▎| 932/1000 [00:00<00:00, 1117.97it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1140.06it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 348/1000 [00:00<00:00, 3475.73it/s]

Bootstrapping accuracy:  70%|██████▉   | 696/1000 [00:00<00:00, 3382.76it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3377.08it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1314.49it/s]

Bootstrapping average_precision:  26%|██▋       | 264/1000 [00:00<00:00, 1301.92it/s]

Bootstrapping average_precision:  40%|███▉      | 395/1000 [00:00<00:00, 1303.34it/s]

Bootstrapping average_precision:  53%|█████▎    | 526/1000 [00:00<00:00, 1289.40it/s]

Bootstrapping average_precision:  66%|██████▌   | 655/1000 [00:00<00:00, 1272.95it/s]

Bootstrapping average_precision:  78%|███████▊  | 783/1000 [00:00<00:00, 1273.76it/s]

Bootstrapping average_precision:  91%|█████████ | 911/1000 [00:00<00:00, 1267.49it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1278.06it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 79/1000 [00:00<00:01, 781.74it/s]

Bootstrapping roc_auc:  16%|█▋        | 164/1000 [00:00<00:01, 819.33it/s]

Bootstrapping roc_auc:  25%|██▍       | 249/1000 [00:00<00:00, 831.62it/s]

Bootstrapping roc_auc:  34%|███▎      | 335/1000 [00:00<00:00, 839.18it/s]

Bootstrapping roc_auc:  42%|████▏     | 420/1000 [00:00<00:00, 840.62it/s]

Bootstrapping roc_auc:  50%|█████     | 505/1000 [00:00<00:00, 820.50it/s]

Bootstrapping roc_auc:  59%|█████▉    | 588/1000 [00:00<00:00, 798.69it/s]

Bootstrapping roc_auc:  67%|██████▋   | 669/1000 [00:00<00:00, 793.81it/s]

Bootstrapping roc_auc:  75%|███████▍  | 749/1000 [00:00<00:00, 794.40it/s]

Bootstrapping roc_auc:  83%|████████▎ | 831/1000 [00:01<00:00, 801.09it/s]

Bootstrapping roc_auc:  91%|█████████▏| 914/1000 [00:01<00:00, 808.30it/s]

Bootstrapping roc_auc: 100%|█████████▉| 995/1000 [00:01<00:00, 804.20it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 808.84it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 107/1000 [00:00<00:00, 1065.98it/s]

Bootstrapping precision:  22%|██▏       | 219/1000 [00:00<00:00, 1092.64it/s]

Bootstrapping precision:  33%|███▎      | 334/1000 [00:00<00:00, 1118.39it/s]

Bootstrapping precision:  45%|████▍     | 446/1000 [00:00<00:00, 1116.87it/s]

Bootstrapping precision:  56%|█████▌    | 558/1000 [00:00<00:00, 1102.27it/s]

Bootstrapping precision:  67%|██████▋   | 672/1000 [00:00<00:00, 1112.95it/s]

Bootstrapping precision:  79%|███████▉  | 791/1000 [00:00<00:00, 1135.31it/s]

Bootstrapping precision:  91%|█████████ | 911/1000 [00:00<00:00, 1153.79it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1132.32it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1185.28it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1177.75it/s]

Bootstrapping recall:  36%|███▌      | 356/1000 [00:00<00:00, 1173.78it/s]

Bootstrapping recall:  48%|████▊     | 475/1000 [00:00<00:00, 1176.05it/s]

Bootstrapping recall:  59%|█████▉    | 593/1000 [00:00<00:00, 1168.99it/s]

Bootstrapping recall:  71%|███████   | 710/1000 [00:00<00:00, 1160.11it/s]

Bootstrapping recall:  83%|████████▎ | 831/1000 [00:00<00:00, 1173.01it/s]

Bootstrapping recall:  95%|█████████▍| 949/1000 [00:00<00:00, 1163.73it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1167.61it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1165.92it/s]

Bootstrapping f1:  24%|██▎       | 235/1000 [00:00<00:00, 1168.56it/s]

Bootstrapping f1:  35%|███▌      | 354/1000 [00:00<00:00, 1178.20it/s]

Bootstrapping f1:  47%|████▋     | 472/1000 [00:00<00:00, 1174.47it/s]

Bootstrapping f1:  59%|█████▉    | 591/1000 [00:00<00:00, 1177.93it/s]

Bootstrapping f1:  71%|███████   | 709/1000 [00:00<00:00, 1167.70it/s]

Bootstrapping f1:  83%|████████▎ | 828/1000 [00:00<00:00, 1174.78it/s]

Bootstrapping f1:  95%|█████████▌| 950/1000 [00:00<00:00, 1186.26it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1179.21it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3493.02it/s]

Bootstrapping accuracy:  70%|███████   | 700/1000 [00:00<00:00, 3405.88it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3407.37it/s]

Processing Simplified Golem $\cup$ Simplified PCMB with 24 nodes and 64 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 140/1000 [00:00<00:00, 1395.45it/s]

Bootstrapping average_precision:  28%|██▊       | 281/1000 [00:00<00:00, 1402.22it/s]

Bootstrapping average_precision:  42%|████▏     | 422/1000 [00:00<00:00, 1405.74it/s]

Bootstrapping average_precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1406.80it/s]

Bootstrapping average_precision:  70%|███████   | 704/1000 [00:00<00:00, 1382.65it/s]

Bootstrapping average_precision:  84%|████████▍ | 843/1000 [00:00<00:00, 1383.34it/s]

Bootstrapping average_precision:  98%|█████████▊| 982/1000 [00:00<00:00, 1385.25it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1388.69it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 858.23it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:01, 814.86it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 818.50it/s]

Bootstrapping roc_auc:  34%|███▍      | 341/1000 [00:00<00:00, 832.95it/s]

Bootstrapping roc_auc:  42%|████▎     | 425/1000 [00:00<00:00, 828.58it/s]

Bootstrapping roc_auc:  51%|█████     | 510/1000 [00:00<00:00, 833.20it/s]

Bootstrapping roc_auc:  59%|█████▉    | 594/1000 [00:00<00:00, 834.36it/s]

Bootstrapping roc_auc:  68%|██████▊   | 680/1000 [00:00<00:00, 842.42it/s]

Bootstrapping roc_auc:  76%|███████▋  | 765/1000 [00:00<00:00, 840.94it/s]

Bootstrapping roc_auc:  85%|████████▌ | 850/1000 [00:01<00:00, 823.94it/s]

Bootstrapping roc_auc:  93%|█████████▎| 933/1000 [00:01<00:00, 822.30it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 831.33it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 118/1000 [00:00<00:00, 1172.17it/s]

Bootstrapping precision:  24%|██▎       | 236/1000 [00:00<00:00, 1173.53it/s]

Bootstrapping precision:  36%|███▌      | 355/1000 [00:00<00:00, 1177.97it/s]

Bootstrapping precision:  47%|████▋     | 474/1000 [00:00<00:00, 1181.31it/s]

Bootstrapping precision:  59%|█████▉    | 593/1000 [00:00<00:00, 1177.41it/s]

Bootstrapping precision:  71%|███████   | 712/1000 [00:00<00:00, 1178.61it/s]

Bootstrapping precision:  83%|████████▎ | 830/1000 [00:00<00:00, 1173.00it/s]

Bootstrapping precision:  95%|█████████▍| 948/1000 [00:00<00:00, 1170.88it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1175.45it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1155.70it/s]

Bootstrapping recall:  23%|██▎       | 234/1000 [00:00<00:00, 1166.57it/s]

Bootstrapping recall:  35%|███▌      | 351/1000 [00:00<00:00, 1119.36it/s]

Bootstrapping recall:  47%|████▋     | 468/1000 [00:00<00:00, 1135.89it/s]

Bootstrapping recall:  58%|█████▊    | 582/1000 [00:00<00:00, 1098.58it/s]

Bootstrapping recall:  69%|██████▉   | 693/1000 [00:00<00:00, 1080.32it/s]

Bootstrapping recall:  80%|████████  | 802/1000 [00:00<00:00, 1068.14it/s]

Bootstrapping recall:  91%|█████████ | 909/1000 [00:00<00:00, 1068.49it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1094.25it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 109/1000 [00:00<00:00, 1081.07it/s]

Bootstrapping f1:  22%|██▏       | 220/1000 [00:00<00:00, 1090.12it/s]

Bootstrapping f1:  33%|███▎      | 330/1000 [00:00<00:00, 1072.77it/s]

Bootstrapping f1:  44%|████▍     | 438/1000 [00:00<00:00, 1063.56it/s]

Bootstrapping f1:  55%|█████▍    | 545/1000 [00:00<00:00, 1064.16it/s]

Bootstrapping f1:  66%|██████▌   | 660/1000 [00:00<00:00, 1090.81it/s]

Bootstrapping f1:  78%|███████▊  | 778/1000 [00:00<00:00, 1118.83it/s]

Bootstrapping f1:  90%|████████▉ | 898/1000 [00:00<00:00, 1142.79it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1112.35it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 330/1000 [00:00<00:00, 3298.71it/s]

Bootstrapping accuracy:  67%|██████▋   | 667/1000 [00:00<00:00, 3336.82it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3359.36it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1280.89it/s]

Bootstrapping average_precision:  26%|██▋       | 265/1000 [00:00<00:00, 1325.82it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 1345.13it/s]

Bootstrapping average_precision:  54%|█████▍    | 538/1000 [00:00<00:00, 1349.30it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1331.70it/s]

Bootstrapping average_precision:  81%|████████  | 807/1000 [00:00<00:00, 1326.31it/s]

Bootstrapping average_precision:  94%|█████████▍| 940/1000 [00:00<00:00, 1306.68it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1319.65it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 844.62it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 836.45it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 837.54it/s]

Bootstrapping roc_auc:  34%|███▍      | 340/1000 [00:00<00:00, 842.57it/s]

Bootstrapping roc_auc:  42%|████▎     | 425/1000 [00:00<00:00, 842.24it/s]

Bootstrapping roc_auc:  51%|█████     | 510/1000 [00:00<00:00, 830.27it/s]

Bootstrapping roc_auc:  60%|█████▉    | 596/1000 [00:00<00:00, 837.27it/s]

Bootstrapping roc_auc:  68%|██████▊   | 680/1000 [00:00<00:00, 813.53it/s]

Bootstrapping roc_auc:  76%|███████▌  | 762/1000 [00:00<00:00, 800.50it/s]

Bootstrapping roc_auc:  84%|████████▍ | 843/1000 [00:01<00:00, 796.25it/s]

Bootstrapping roc_auc:  93%|█████████▎| 926/1000 [00:01<00:00, 803.73it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 812.74it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1158.47it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1077.56it/s]

Bootstrapping precision:  34%|███▍      | 341/1000 [00:00<00:00, 1079.99it/s]

Bootstrapping precision:  46%|████▌     | 457/1000 [00:00<00:00, 1107.90it/s]

Bootstrapping precision:  58%|█████▊    | 577/1000 [00:00<00:00, 1139.02it/s]

Bootstrapping precision:  69%|██████▉   | 692/1000 [00:00<00:00, 1136.83it/s]

Bootstrapping precision:  81%|████████  | 806/1000 [00:00<00:00, 1129.72it/s]

Bootstrapping precision:  92%|█████████▏| 920/1000 [00:00<00:00, 1110.74it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1120.97it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 108/1000 [00:00<00:00, 1069.30it/s]

Bootstrapping recall:  22%|██▏       | 215/1000 [00:00<00:00, 1042.86it/s]

Bootstrapping recall:  33%|███▎      | 330/1000 [00:00<00:00, 1088.46it/s]

Bootstrapping recall:  44%|████▍     | 443/1000 [00:00<00:00, 1104.19it/s]

Bootstrapping recall:  55%|█████▌    | 554/1000 [00:00<00:00, 1091.82it/s]

Bootstrapping recall:  66%|██████▋   | 664/1000 [00:00<00:00, 1088.12it/s]

Bootstrapping recall:  78%|███████▊  | 781/1000 [00:00<00:00, 1114.51it/s]

Bootstrapping recall:  90%|█████████ | 900/1000 [00:00<00:00, 1135.53it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1112.26it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 114/1000 [00:00<00:00, 1139.76it/s]

Bootstrapping f1:  23%|██▎       | 232/1000 [00:00<00:00, 1162.34it/s]

Bootstrapping f1:  35%|███▍      | 349/1000 [00:00<00:00, 1160.72it/s]

Bootstrapping f1:  47%|████▋     | 466/1000 [00:00<00:00, 1098.31it/s]

Bootstrapping f1:  58%|█████▊    | 577/1000 [00:00<00:00, 1060.93it/s]

Bootstrapping f1:  69%|██████▊   | 686/1000 [00:00<00:00, 1069.61it/s]

Bootstrapping f1:  80%|████████  | 805/1000 [00:00<00:00, 1107.50it/s]

Bootstrapping f1:  92%|█████████▏| 920/1000 [00:00<00:00, 1118.20it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1113.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 346/1000 [00:00<00:00, 3451.65it/s]

Bootstrapping accuracy:  69%|██████▉   | 692/1000 [00:00<00:00, 3440.96it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3332.91it/s]

Processing Simplified Clinician Consensus with 17 nodes and 17 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1337.07it/s]

Bootstrapping average_precision:  27%|██▋       | 271/1000 [00:00<00:00, 1350.93it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1344.55it/s]

Bootstrapping average_precision:  55%|█████▍    | 545/1000 [00:00<00:00, 1356.04it/s]

Bootstrapping average_precision:  68%|██████▊   | 684/1000 [00:00<00:00, 1368.20it/s]

Bootstrapping average_precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1378.74it/s]

Bootstrapping average_precision:  96%|█████████▋| 963/1000 [00:00<00:00, 1379.29it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1366.23it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 825.82it/s]

Bootstrapping roc_auc:  17%|█▋        | 167/1000 [00:00<00:01, 831.49it/s]

Bootstrapping roc_auc:  25%|██▌       | 251/1000 [00:00<00:00, 833.98it/s]

Bootstrapping roc_auc:  34%|███▎      | 335/1000 [00:00<00:00, 833.35it/s]

Bootstrapping roc_auc:  42%|████▏     | 419/1000 [00:00<00:00, 835.05it/s]

Bootstrapping roc_auc:  50%|█████     | 504/1000 [00:00<00:00, 838.58it/s]

Bootstrapping roc_auc:  59%|█████▉    | 592/1000 [00:00<00:00, 849.35it/s]

Bootstrapping roc_auc:  68%|██████▊   | 681/1000 [00:00<00:00, 858.81it/s]

Bootstrapping roc_auc:  77%|███████▋  | 768/1000 [00:00<00:00, 859.54it/s]

Bootstrapping roc_auc:  86%|████████▌ | 858/1000 [00:01<00:00, 870.56it/s]

Bootstrapping roc_auc:  95%|█████████▍| 947/1000 [00:01<00:00, 874.81it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 856.69it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 119/1000 [00:00<00:00, 1179.65it/s]

Bootstrapping precision:  24%|██▍       | 239/1000 [00:00<00:00, 1186.64it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1191.04it/s]

Bootstrapping precision:  48%|████▊     | 480/1000 [00:00<00:00, 1193.11it/s]

Bootstrapping precision:  60%|██████    | 600/1000 [00:00<00:00, 1193.91it/s]

Bootstrapping precision:  72%|███████▏  | 720/1000 [00:00<00:00, 1183.37it/s]

Bootstrapping precision:  84%|████████▍ | 839/1000 [00:00<00:00, 1184.89it/s]

Bootstrapping precision:  96%|█████████▌| 959/1000 [00:00<00:00, 1189.49it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1188.14it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1192.62it/s]

Bootstrapping recall:  24%|██▍       | 240/1000 [00:00<00:00, 1193.23it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1188.96it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1192.56it/s]

Bootstrapping recall:  60%|██████    | 602/1000 [00:00<00:00, 1200.12it/s]

Bootstrapping recall:  72%|███████▏  | 723/1000 [00:00<00:00, 1193.59it/s]

Bootstrapping recall:  84%|████████▍ | 844/1000 [00:00<00:00, 1196.81it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1194.36it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1194.79it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1180.08it/s]

Bootstrapping f1:  24%|██▍       | 239/1000 [00:00<00:00, 1188.02it/s]

Bootstrapping f1:  36%|███▌      | 360/1000 [00:00<00:00, 1194.73it/s]

Bootstrapping f1:  48%|████▊     | 480/1000 [00:00<00:00, 1195.20it/s]

Bootstrapping f1:  60%|██████    | 601/1000 [00:00<00:00, 1200.26it/s]

Bootstrapping f1:  72%|███████▏  | 722/1000 [00:00<00:00, 1195.59it/s]

Bootstrapping f1:  84%|████████▍ | 842/1000 [00:00<00:00, 1193.57it/s]

Bootstrapping f1:  96%|█████████▌| 962/1000 [00:00<00:00, 1194.86it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1194.03it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 344/1000 [00:00<00:00, 3436.83it/s]

Bootstrapping accuracy:  69%|██████▉   | 688/1000 [00:00<00:00, 3324.08it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3394.37it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1344.03it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1330.41it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 1324.05it/s]

Bootstrapping average_precision:  54%|█████▎    | 537/1000 [00:00<00:00, 1322.03it/s]

Bootstrapping average_precision:  67%|██████▋   | 671/1000 [00:00<00:00, 1326.58it/s]

Bootstrapping average_precision:  80%|████████  | 804/1000 [00:00<00:00, 1325.77it/s]

Bootstrapping average_precision:  94%|█████████▎| 937/1000 [00:00<00:00, 1324.60it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1322.42it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 839.86it/s]

Bootstrapping roc_auc:  17%|█▋        | 169/1000 [00:00<00:00, 832.45it/s]

Bootstrapping roc_auc:  25%|██▌       | 253/1000 [00:00<00:00, 825.36it/s]

Bootstrapping roc_auc:  34%|███▎      | 336/1000 [00:00<00:00, 804.33it/s]

Bootstrapping roc_auc:  42%|████▏     | 417/1000 [00:00<00:00, 796.56it/s]

Bootstrapping roc_auc:  50%|████▉     | 498/1000 [00:00<00:00, 800.01it/s]

Bootstrapping roc_auc:  58%|█████▊    | 582/1000 [00:00<00:00, 810.64it/s]

Bootstrapping roc_auc:  66%|██████▋   | 665/1000 [00:00<00:00, 815.59it/s]

Bootstrapping roc_auc:  75%|███████▍  | 747/1000 [00:00<00:00, 815.88it/s]

Bootstrapping roc_auc:  83%|████████▎ | 830/1000 [00:01<00:00, 819.02it/s]

Bootstrapping roc_auc:  91%|█████████▏| 913/1000 [00:01<00:00, 822.28it/s]

Bootstrapping roc_auc: 100%|█████████▉| 996/1000 [00:01<00:00, 813.20it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 812.94it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1134.08it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1144.14it/s]

Bootstrapping precision:  35%|███▌      | 351/1000 [00:00<00:00, 1171.51it/s]

Bootstrapping precision:  47%|████▋     | 471/1000 [00:00<00:00, 1182.70it/s]

Bootstrapping precision:  59%|█████▉    | 590/1000 [00:00<00:00, 1181.42it/s]

Bootstrapping precision:  71%|███████   | 709/1000 [00:00<00:00, 1178.77it/s]

Bootstrapping precision:  83%|████████▎ | 827/1000 [00:00<00:00, 1174.06it/s]

Bootstrapping precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1178.33it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1175.07it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1212.95it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1198.44it/s]

Bootstrapping recall:  36%|███▋      | 365/1000 [00:00<00:00, 1199.73it/s]

Bootstrapping recall:  49%|████▊     | 486/1000 [00:00<00:00, 1199.75it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1195.69it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1173.07it/s]

Bootstrapping recall:  84%|████████▍ | 844/1000 [00:00<00:00, 1160.99it/s]

Bootstrapping recall:  96%|█████████▋| 963/1000 [00:00<00:00, 1168.86it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1179.82it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1164.72it/s]

Bootstrapping f1:  23%|██▎       | 234/1000 [00:00<00:00, 1131.88it/s]

Bootstrapping f1:  35%|███▌      | 353/1000 [00:00<00:00, 1156.11it/s]

Bootstrapping f1:  47%|████▋     | 473/1000 [00:00<00:00, 1170.20it/s]

Bootstrapping f1:  59%|█████▉    | 594/1000 [00:00<00:00, 1182.09it/s]

Bootstrapping f1:  71%|███████▏  | 714/1000 [00:00<00:00, 1187.68it/s]

Bootstrapping f1:  83%|████████▎ | 834/1000 [00:00<00:00, 1190.18it/s]

Bootstrapping f1:  95%|█████████▌| 954/1000 [00:00<00:00, 1185.58it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1176.53it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 350/1000 [00:00<00:00, 3497.20it/s]

Bootstrapping accuracy:  70%|███████   | 701/1000 [00:00<00:00, 3503.02it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3505.32it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB with 15 nodes and 14 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 139/1000 [00:00<00:00, 1388.79it/s]

Bootstrapping average_precision:  28%|██▊       | 278/1000 [00:00<00:00, 1374.77it/s]

Bootstrapping average_precision:  42%|████▏     | 420/1000 [00:00<00:00, 1391.85it/s]

Bootstrapping average_precision:  56%|█████▌    | 560/1000 [00:00<00:00, 1362.69it/s]

Bootstrapping average_precision:  70%|██████▉   | 697/1000 [00:00<00:00, 1354.63it/s]

Bootstrapping average_precision:  84%|████████▍ | 838/1000 [00:00<00:00, 1371.57it/s]

Bootstrapping average_precision:  98%|█████████▊| 980/1000 [00:00<00:00, 1384.15it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1375.98it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 845.17it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 843.87it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 846.03it/s]

Bootstrapping roc_auc:  34%|███▍      | 341/1000 [00:00<00:00, 847.07it/s]

Bootstrapping roc_auc:  43%|████▎     | 427/1000 [00:00<00:00, 849.31it/s]

Bootstrapping roc_auc:  52%|█████▏    | 517/1000 [00:00<00:00, 862.94it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 871.11it/s]

Bootstrapping roc_auc:  70%|██████▉   | 695/1000 [00:00<00:00, 875.72it/s]

Bootstrapping roc_auc:  78%|███████▊  | 783/1000 [00:00<00:00, 874.04it/s]

Bootstrapping roc_auc:  87%|████████▋ | 871/1000 [00:01<00:00, 869.74it/s]

Bootstrapping roc_auc:  96%|█████████▌| 958/1000 [00:01<00:00, 858.81it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 858.57it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 116/1000 [00:00<00:00, 1158.18it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1138.06it/s]

Bootstrapping precision:  35%|███▍      | 346/1000 [00:00<00:00, 1130.12it/s]

Bootstrapping precision:  46%|████▌     | 460/1000 [00:00<00:00, 1126.15it/s]

Bootstrapping precision:  58%|█████▊    | 576/1000 [00:00<00:00, 1137.73it/s]

Bootstrapping precision:  69%|██████▉   | 690/1000 [00:00<00:00, 1132.25it/s]

Bootstrapping precision:  80%|████████  | 804/1000 [00:00<00:00, 1127.07it/s]

Bootstrapping precision:  92%|█████████▏| 919/1000 [00:00<00:00, 1132.42it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1135.71it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1171.35it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1153.44it/s]

Bootstrapping recall:  36%|███▌      | 355/1000 [00:00<00:00, 1166.05it/s]

Bootstrapping recall:  47%|████▋     | 472/1000 [00:00<00:00, 1165.24it/s]

Bootstrapping recall:  59%|█████▉    | 589/1000 [00:00<00:00, 1154.36it/s]

Bootstrapping recall:  70%|███████   | 705/1000 [00:00<00:00, 1149.54it/s]

Bootstrapping recall:  82%|████████▏ | 821/1000 [00:00<00:00, 1152.34it/s]

Bootstrapping recall:  94%|█████████▎| 937/1000 [00:00<00:00, 1148.76it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1156.40it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1202.87it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1199.86it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1199.30it/s]

Bootstrapping f1:  48%|████▊     | 482/1000 [00:00<00:00, 1192.09it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1193.78it/s]

Bootstrapping f1:  72%|███████▏  | 722/1000 [00:00<00:00, 1182.13it/s]

Bootstrapping f1:  84%|████████▍ | 841/1000 [00:00<00:00, 1181.67it/s]

Bootstrapping f1:  96%|█████████▌| 961/1000 [00:00<00:00, 1184.38it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1188.09it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 351/1000 [00:00<00:00, 3503.03it/s]

Bootstrapping accuracy:  70%|███████   | 702/1000 [00:00<00:00, 3484.23it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3445.40it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  12%|█▏        | 123/1000 [00:00<00:00, 1223.27it/s]

Bootstrapping average_precision:  25%|██▌       | 252/1000 [00:00<00:00, 1256.28it/s]

Bootstrapping average_precision:  38%|███▊      | 382/1000 [00:00<00:00, 1274.83it/s]

Bootstrapping average_precision:  51%|█████     | 510/1000 [00:00<00:00, 1268.06it/s]

Bootstrapping average_precision:  64%|██████▎   | 637/1000 [00:00<00:00, 1262.81it/s]

Bootstrapping average_precision:  76%|███████▋  | 765/1000 [00:00<00:00, 1264.91it/s]

Bootstrapping average_precision:  90%|████████▉ | 898/1000 [00:00<00:00, 1284.69it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1278.75it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 863.74it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 849.67it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 825.38it/s]

Bootstrapping roc_auc:  34%|███▍      | 342/1000 [00:00<00:00, 819.55it/s]

Bootstrapping roc_auc:  43%|████▎     | 428/1000 [00:00<00:00, 831.18it/s]

Bootstrapping roc_auc:  52%|█████▏    | 515/1000 [00:00<00:00, 841.49it/s]

Bootstrapping roc_auc:  60%|██████    | 602/1000 [00:00<00:00, 848.09it/s]

Bootstrapping roc_auc:  69%|██████▊   | 687/1000 [00:00<00:00, 845.92it/s]

Bootstrapping roc_auc:  77%|███████▋  | 774/1000 [00:00<00:00, 850.78it/s]

Bootstrapping roc_auc:  86%|████████▌ | 860/1000 [00:01<00:00, 844.03it/s]

Bootstrapping roc_auc:  94%|█████████▍| 945/1000 [00:01<00:00, 831.73it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 836.18it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1193.05it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1192.26it/s]

Bootstrapping precision:  36%|███▌      | 360/1000 [00:00<00:00, 1184.24it/s]

Bootstrapping precision:  48%|████▊     | 479/1000 [00:00<00:00, 1168.05it/s]

Bootstrapping precision:  60%|█████▉    | 596/1000 [00:00<00:00, 1162.87it/s]

Bootstrapping precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1163.44it/s]

Bootstrapping precision:  83%|████████▎ | 830/1000 [00:00<00:00, 1156.40it/s]

Bootstrapping precision:  95%|█████████▌| 951/1000 [00:00<00:00, 1171.45it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1172.18it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1201.11it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1173.54it/s]

Bootstrapping recall:  36%|███▌      | 360/1000 [00:00<00:00, 1174.75it/s]

Bootstrapping recall:  48%|████▊     | 480/1000 [00:00<00:00, 1180.88it/s]

Bootstrapping recall:  60%|█████▉    | 599/1000 [00:00<00:00, 1182.46it/s]

Bootstrapping recall:  72%|███████▏  | 719/1000 [00:00<00:00, 1188.36it/s]

Bootstrapping recall:  84%|████████▍ | 841/1000 [00:00<00:00, 1197.68it/s]

Bootstrapping recall:  96%|█████████▌| 962/1000 [00:00<00:00, 1199.84it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1190.14it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1195.34it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1185.25it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1173.14it/s]

Bootstrapping f1:  48%|████▊     | 477/1000 [00:00<00:00, 1139.22it/s]

Bootstrapping f1:  59%|█████▉    | 592/1000 [00:00<00:00, 1129.00it/s]

Bootstrapping f1:  71%|███████   | 707/1000 [00:00<00:00, 1133.76it/s]

Bootstrapping f1:  83%|████████▎ | 826/1000 [00:00<00:00, 1150.16it/s]

Bootstrapping f1:  94%|█████████▍| 942/1000 [00:00<00:00, 1152.64it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1153.18it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 343/1000 [00:00<00:00, 3424.72it/s]

Bootstrapping accuracy:  69%|██████▊   | 687/1000 [00:00<00:00, 3427.62it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3446.22it/s]

Processing Simplified PCMB with 18 nodes and 50 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1357.05it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1317.74it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1333.29it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1355.80it/s]

Bootstrapping average_precision:  69%|██████▊   | 687/1000 [00:00<00:00, 1367.71it/s]

Bootstrapping average_precision:  83%|████████▎ | 829/1000 [00:00<00:00, 1383.40it/s]

Bootstrapping average_precision:  97%|█████████▋| 968/1000 [00:00<00:00, 1374.35it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1362.10it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 852.94it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 868.22it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 863.39it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 846.56it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 849.72it/s]

Bootstrapping roc_auc:  52%|█████▏    | 520/1000 [00:00<00:00, 838.28it/s]

Bootstrapping roc_auc:  61%|██████    | 606/1000 [00:00<00:00, 844.75it/s]

Bootstrapping roc_auc:  69%|██████▉   | 692/1000 [00:00<00:00, 847.18it/s]

Bootstrapping roc_auc:  78%|███████▊  | 781/1000 [00:00<00:00, 858.98it/s]

Bootstrapping roc_auc:  87%|████████▋ | 870/1000 [00:01<00:00, 867.22it/s]

Bootstrapping roc_auc:  96%|█████████▌| 957/1000 [00:01<00:00, 866.09it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 857.65it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1198.37it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1199.15it/s]

Bootstrapping precision:  36%|███▌      | 360/1000 [00:00<00:00, 1184.61it/s]

Bootstrapping precision:  48%|████▊     | 479/1000 [00:00<00:00, 1184.13it/s]

Bootstrapping precision:  60%|█████▉    | 598/1000 [00:00<00:00, 1182.92it/s]

Bootstrapping precision:  72%|███████▏  | 718/1000 [00:00<00:00, 1187.15it/s]

Bootstrapping precision:  84%|████████▍ | 838/1000 [00:00<00:00, 1188.74it/s]

Bootstrapping precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1192.18it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1188.32it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 117/1000 [00:00<00:00, 1169.27it/s]

Bootstrapping recall:  23%|██▎       | 234/1000 [00:00<00:00, 1150.83it/s]

Bootstrapping recall:  35%|███▌      | 350/1000 [00:00<00:00, 1149.63it/s]

Bootstrapping recall:  47%|████▋     | 466/1000 [00:00<00:00, 1153.19it/s]

Bootstrapping recall:  58%|█████▊    | 583/1000 [00:00<00:00, 1156.80it/s]

Bootstrapping recall:  70%|██████▉   | 699/1000 [00:00<00:00, 1145.53it/s]

Bootstrapping recall:  81%|████████▏ | 814/1000 [00:00<00:00, 1140.09it/s]

Bootstrapping recall:  93%|█████████▎| 929/1000 [00:00<00:00, 1142.80it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1146.07it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 114/1000 [00:00<00:00, 1135.92it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1149.71it/s]

Bootstrapping f1:  35%|███▍      | 347/1000 [00:00<00:00, 1156.17it/s]

Bootstrapping f1:  46%|████▋     | 463/1000 [00:00<00:00, 1139.35it/s]

Bootstrapping f1:  58%|█████▊    | 581/1000 [00:00<00:00, 1153.24it/s]

Bootstrapping f1:  70%|██████▉   | 697/1000 [00:00<00:00, 1152.49it/s]

Bootstrapping f1:  81%|████████▏ | 813/1000 [00:00<00:00, 1145.67it/s]

Bootstrapping f1:  93%|█████████▎| 928/1000 [00:00<00:00, 1141.38it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1147.49it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 352/1000 [00:00<00:00, 3512.90it/s]

Bootstrapping accuracy:  70%|███████   | 704/1000 [00:00<00:00, 3498.39it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3505.50it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1327.81it/s]

Bootstrapping average_precision:  27%|██▋       | 266/1000 [00:00<00:00, 1288.22it/s]

Bootstrapping average_precision:  40%|███▉      | 395/1000 [00:00<00:00, 1277.25it/s]

Bootstrapping average_precision:  52%|█████▏    | 523/1000 [00:00<00:00, 1276.43it/s]

Bootstrapping average_precision:  65%|██████▌   | 652/1000 [00:00<00:00, 1280.24it/s]

Bootstrapping average_precision:  78%|███████▊  | 782/1000 [00:00<00:00, 1286.46it/s]

Bootstrapping average_precision:  92%|█████████▏| 916/1000 [00:00<00:00, 1301.56it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1295.64it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 835.18it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:01, 804.78it/s]

Bootstrapping roc_auc:  25%|██▍       | 249/1000 [00:00<00:00, 794.71it/s]

Bootstrapping roc_auc:  33%|███▎      | 330/1000 [00:00<00:00, 797.78it/s]

Bootstrapping roc_auc:  42%|████▏     | 415/1000 [00:00<00:00, 813.35it/s]

Bootstrapping roc_auc:  50%|█████     | 500/1000 [00:00<00:00, 824.18it/s]

Bootstrapping roc_auc:  58%|█████▊    | 583/1000 [00:00<00:00, 810.33it/s]

Bootstrapping roc_auc:  66%|██████▋   | 665/1000 [00:00<00:00, 803.24it/s]

Bootstrapping roc_auc:  75%|███████▍  | 746/1000 [00:00<00:00, 798.24it/s]

Bootstrapping roc_auc:  83%|████████▎ | 826/1000 [00:01<00:00, 798.75it/s]

Bootstrapping roc_auc:  91%|█████████ | 906/1000 [00:01<00:00, 795.57it/s]

Bootstrapping roc_auc:  99%|█████████▊| 987/1000 [00:01<00:00, 797.24it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 801.72it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1147.21it/s]

Bootstrapping precision:  23%|██▎       | 231/1000 [00:00<00:00, 1151.14it/s]

Bootstrapping precision:  35%|███▍      | 349/1000 [00:00<00:00, 1163.42it/s]

Bootstrapping precision:  47%|████▋     | 466/1000 [00:00<00:00, 1153.40it/s]

Bootstrapping precision:  58%|█████▊    | 582/1000 [00:00<00:00, 1140.05it/s]

Bootstrapping precision:  70%|██████▉   | 697/1000 [00:00<00:00, 1122.93it/s]

Bootstrapping precision:  81%|████████  | 810/1000 [00:00<00:00, 1118.47it/s]

Bootstrapping precision:  92%|█████████▎| 925/1000 [00:00<00:00, 1125.03it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1133.12it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 109/1000 [00:00<00:00, 1081.15it/s]

Bootstrapping recall:  22%|██▏       | 223/1000 [00:00<00:00, 1112.25it/s]

Bootstrapping recall:  34%|███▍      | 342/1000 [00:00<00:00, 1146.62it/s]

Bootstrapping recall:  46%|████▌     | 458/1000 [00:00<00:00, 1151.01it/s]

Bootstrapping recall:  57%|█████▋    | 574/1000 [00:00<00:00, 1138.98it/s]

Bootstrapping recall:  69%|██████▉   | 688/1000 [00:00<00:00, 1136.34it/s]

Bootstrapping recall:  80%|████████  | 803/1000 [00:00<00:00, 1138.20it/s]

Bootstrapping recall:  92%|█████████▏| 917/1000 [00:00<00:00, 1132.49it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1130.98it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1125.11it/s]

Bootstrapping f1:  23%|██▎       | 226/1000 [00:00<00:00, 1120.18it/s]

Bootstrapping f1:  34%|███▍      | 339/1000 [00:00<00:00, 1110.93it/s]

Bootstrapping f1:  46%|████▌     | 457/1000 [00:00<00:00, 1137.14it/s]

Bootstrapping f1:  58%|█████▊    | 576/1000 [00:00<00:00, 1155.82it/s]

Bootstrapping f1:  69%|██████▉   | 692/1000 [00:00<00:00, 1151.76it/s]

Bootstrapping f1:  81%|████████  | 808/1000 [00:00<00:00, 1154.00it/s]

Bootstrapping f1:  93%|█████████▎| 927/1000 [00:00<00:00, 1163.67it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1147.17it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 348/1000 [00:00<00:00, 3473.82it/s]

Bootstrapping accuracy:  70%|██████▉   | 698/1000 [00:00<00:00, 3484.28it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3434.91it/s]

Processing Simplified Golem with 12 nodes and 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1328.51it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1348.47it/s]

Bootstrapping average_precision:  41%|████      | 407/1000 [00:00<00:00, 1355.66it/s]

Bootstrapping average_precision:  54%|█████▍    | 543/1000 [00:00<00:00, 1332.37it/s]

Bootstrapping average_precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1323.54it/s]

Bootstrapping average_precision:  81%|████████  | 810/1000 [00:00<00:00, 1323.28it/s]

Bootstrapping average_precision:  95%|█████████▍| 946/1000 [00:00<00:00, 1332.32it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1329.60it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 842.90it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 860.74it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 869.05it/s]

Bootstrapping roc_auc:  35%|███▍      | 348/1000 [00:00<00:00, 846.21it/s]

Bootstrapping roc_auc:  43%|████▎     | 433/1000 [00:00<00:00, 834.57it/s]

Bootstrapping roc_auc:  52%|█████▏    | 517/1000 [00:00<00:00, 831.77it/s]

Bootstrapping roc_auc:  60%|██████    | 601/1000 [00:00<00:00, 831.60it/s]

Bootstrapping roc_auc:  68%|██████▊   | 685/1000 [00:00<00:00, 831.30it/s]

Bootstrapping roc_auc:  77%|███████▋  | 769/1000 [00:00<00:00, 828.06it/s]

Bootstrapping roc_auc:  85%|████████▌ | 852/1000 [00:01<00:00, 822.95it/s]

Bootstrapping roc_auc:  94%|█████████▍| 939/1000 [00:01<00:00, 834.26it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 835.51it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 106/1000 [00:00<00:00, 1057.26it/s]

Bootstrapping precision:  22%|██▏       | 216/1000 [00:00<00:00, 1081.75it/s]

Bootstrapping precision:  33%|███▎      | 334/1000 [00:00<00:00, 1124.25it/s]

Bootstrapping precision:  45%|████▍     | 449/1000 [00:00<00:00, 1133.19it/s]

Bootstrapping precision:  56%|█████▋    | 565/1000 [00:00<00:00, 1139.57it/s]

Bootstrapping precision:  68%|██████▊   | 681/1000 [00:00<00:00, 1143.03it/s]

Bootstrapping precision:  80%|███████▉  | 798/1000 [00:00<00:00, 1148.40it/s]

Bootstrapping precision:  92%|█████████▏| 916/1000 [00:00<00:00, 1155.58it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1136.61it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 113/1000 [00:00<00:00, 1121.69it/s]

Bootstrapping recall:  23%|██▎       | 228/1000 [00:00<00:00, 1134.66it/s]

Bootstrapping recall:  35%|███▍      | 346/1000 [00:00<00:00, 1152.46it/s]

Bootstrapping recall:  46%|████▋     | 464/1000 [00:00<00:00, 1161.36it/s]

Bootstrapping recall:  58%|█████▊    | 581/1000 [00:00<00:00, 1162.04it/s]

Bootstrapping recall:  70%|███████   | 700/1000 [00:00<00:00, 1168.48it/s]

Bootstrapping recall:  82%|████████▏ | 818/1000 [00:00<00:00, 1171.04it/s]

Bootstrapping recall:  94%|█████████▎| 936/1000 [00:00<00:00, 1153.26it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1155.89it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 112/1000 [00:00<00:00, 1114.79it/s]

Bootstrapping f1:  23%|██▎       | 229/1000 [00:00<00:00, 1146.60it/s]

Bootstrapping f1:  34%|███▍      | 344/1000 [00:00<00:00, 1147.67it/s]

Bootstrapping f1:  46%|████▌     | 459/1000 [00:00<00:00, 1139.58it/s]

Bootstrapping f1:  57%|█████▋    | 573/1000 [00:00<00:00, 1132.76it/s]

Bootstrapping f1:  69%|██████▊   | 687/1000 [00:00<00:00, 1114.64it/s]

Bootstrapping f1:  80%|████████  | 803/1000 [00:00<00:00, 1126.39it/s]

Bootstrapping f1:  92%|█████████▏| 919/1000 [00:00<00:00, 1136.43it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1135.38it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 341/1000 [00:00<00:00, 3400.31it/s]

Bootstrapping accuracy:  69%|██████▉   | 693/1000 [00:00<00:00, 3467.36it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3413.41it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 128/1000 [00:00<00:00, 1277.93it/s]

Bootstrapping average_precision:  26%|██▌       | 258/1000 [00:00<00:00, 1288.34it/s]

Bootstrapping average_precision:  39%|███▉      | 389/1000 [00:00<00:00, 1295.16it/s]

Bootstrapping average_precision:  52%|█████▏    | 523/1000 [00:00<00:00, 1310.61it/s]

Bootstrapping average_precision:  66%|██████▌   | 658/1000 [00:00<00:00, 1321.42it/s]

Bootstrapping average_precision:  79%|███████▉  | 791/1000 [00:00<00:00, 1314.34it/s]

Bootstrapping average_precision:  92%|█████████▏| 923/1000 [00:00<00:00, 1309.90it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1308.68it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 837.35it/s]

Bootstrapping roc_auc:  17%|█▋        | 169/1000 [00:00<00:00, 841.65it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 845.11it/s]

Bootstrapping roc_auc:  34%|███▍      | 340/1000 [00:00<00:00, 847.31it/s]

Bootstrapping roc_auc:  43%|████▎     | 427/1000 [00:00<00:00, 853.62it/s]

Bootstrapping roc_auc:  51%|█████▏    | 513/1000 [00:00<00:00, 854.38it/s]

Bootstrapping roc_auc:  60%|█████▉    | 599/1000 [00:00<00:00, 848.06it/s]

Bootstrapping roc_auc:  68%|██████▊   | 684/1000 [00:00<00:00, 843.62it/s]

Bootstrapping roc_auc:  77%|███████▋  | 769/1000 [00:00<00:00, 845.41it/s]

Bootstrapping roc_auc:  86%|████████▌ | 855/1000 [00:01<00:00, 848.84it/s]

Bootstrapping roc_auc:  94%|█████████▍| 941/1000 [00:01<00:00, 850.11it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 845.91it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 113/1000 [00:00<00:00, 1121.67it/s]

Bootstrapping precision:  23%|██▎       | 230/1000 [00:00<00:00, 1148.34it/s]

Bootstrapping precision:  34%|███▍      | 345/1000 [00:00<00:00, 1143.06it/s]

Bootstrapping precision:  46%|████▌     | 460/1000 [00:00<00:00, 1141.12it/s]

Bootstrapping precision:  58%|█████▊    | 579/1000 [00:00<00:00, 1156.01it/s]

Bootstrapping precision:  70%|██████▉   | 697/1000 [00:00<00:00, 1160.81it/s]

Bootstrapping precision:  81%|████████▏ | 814/1000 [00:00<00:00, 1156.02it/s]

Bootstrapping precision:  93%|█████████▎| 931/1000 [00:00<00:00, 1158.22it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1153.75it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1175.66it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1172.87it/s]

Bootstrapping recall:  35%|███▌      | 354/1000 [00:00<00:00, 1174.65it/s]

Bootstrapping recall:  47%|████▋     | 472/1000 [00:00<00:00, 1164.95it/s]

Bootstrapping recall:  59%|█████▉    | 589/1000 [00:00<00:00, 1162.90it/s]

Bootstrapping recall:  71%|███████   | 711/1000 [00:00<00:00, 1179.97it/s]

Bootstrapping recall:  83%|████████▎ | 832/1000 [00:00<00:00, 1188.84it/s]

Bootstrapping recall:  95%|█████████▌| 952/1000 [00:00<00:00, 1190.13it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1179.04it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1173.50it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1156.40it/s]

Bootstrapping f1:  35%|███▌      | 352/1000 [00:00<00:00, 1152.30it/s]

Bootstrapping f1:  47%|████▋     | 468/1000 [00:00<00:00, 1148.74it/s]

Bootstrapping f1:  58%|█████▊    | 583/1000 [00:00<00:00, 1148.29it/s]

Bootstrapping f1:  70%|██████▉   | 698/1000 [00:00<00:00, 1126.11it/s]

Bootstrapping f1:  81%|████████  | 811/1000 [00:00<00:00, 1123.31it/s]

Bootstrapping f1:  92%|█████████▏| 924/1000 [00:00<00:00, 1122.35it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1132.65it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 327/1000 [00:00<00:00, 3266.34it/s]

Bootstrapping accuracy:  66%|██████▌   | 657/1000 [00:00<00:00, 3282.49it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3338.20it/s]

Processing Simplified Golem $\cap$ Simplified PCMB with 6 nodes and 5 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1316.12it/s]

Bootstrapping average_precision:  26%|██▋       | 264/1000 [00:00<00:00, 1292.88it/s]

Bootstrapping average_precision:  40%|███▉      | 395/1000 [00:00<00:00, 1298.09it/s]

Bootstrapping average_precision:  52%|█████▎    | 525/1000 [00:00<00:00, 1296.51it/s]

Bootstrapping average_precision:  66%|██████▌   | 662/1000 [00:00<00:00, 1321.89it/s]

Bootstrapping average_precision:  80%|████████  | 802/1000 [00:00<00:00, 1345.91it/s]

Bootstrapping average_precision:  94%|█████████▍| 939/1000 [00:00<00:00, 1353.26it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1331.59it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 832.95it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 843.43it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 842.72it/s]

Bootstrapping roc_auc:  34%|███▍      | 340/1000 [00:00<00:00, 840.95it/s]

Bootstrapping roc_auc:  42%|████▎     | 425/1000 [00:00<00:00, 833.72it/s]

Bootstrapping roc_auc:  51%|█████     | 509/1000 [00:00<00:00, 832.20it/s]

Bootstrapping roc_auc:  60%|█████▉    | 595/1000 [00:00<00:00, 838.06it/s]

Bootstrapping roc_auc:  68%|██████▊   | 680/1000 [00:00<00:00, 838.99it/s]

Bootstrapping roc_auc:  76%|███████▋  | 764/1000 [00:00<00:00, 838.39it/s]

Bootstrapping roc_auc:  85%|████████▍ | 848/1000 [00:01<00:00, 835.99it/s]

Bootstrapping roc_auc:  93%|█████████▎| 933/1000 [00:01<00:00, 839.24it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 839.67it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1193.24it/s]

Bootstrapping precision:  24%|██▍       | 241/1000 [00:00<00:00, 1199.88it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1181.16it/s]

Bootstrapping precision:  48%|████▊     | 480/1000 [00:00<00:00, 1178.45it/s]

Bootstrapping precision:  60%|█████▉    | 599/1000 [00:00<00:00, 1180.88it/s]

Bootstrapping precision:  72%|███████▏  | 718/1000 [00:00<00:00, 1176.40it/s]

Bootstrapping precision:  84%|████████▎ | 836/1000 [00:00<00:00, 1166.94it/s]

Bootstrapping precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1164.60it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1172.07it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1178.66it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1165.07it/s]

Bootstrapping recall:  35%|███▌      | 353/1000 [00:00<00:00, 1147.94it/s]

Bootstrapping recall:  47%|████▋     | 468/1000 [00:00<00:00, 1137.23it/s]

Bootstrapping recall:  58%|█████▊    | 583/1000 [00:00<00:00, 1141.18it/s]

Bootstrapping recall:  70%|██████▉   | 698/1000 [00:00<00:00, 1135.50it/s]

Bootstrapping recall:  81%|████████  | 812/1000 [00:00<00:00, 1127.87it/s]

Bootstrapping recall:  92%|█████████▎| 925/1000 [00:00<00:00, 1128.34it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1136.09it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 115/1000 [00:00<00:00, 1143.86it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1134.72it/s]

Bootstrapping f1:  34%|███▍      | 344/1000 [00:00<00:00, 1123.77it/s]

Bootstrapping f1:  46%|████▌     | 459/1000 [00:00<00:00, 1130.22it/s]

Bootstrapping f1:  57%|█████▊    | 575/1000 [00:00<00:00, 1136.29it/s]

Bootstrapping f1:  69%|██████▉   | 689/1000 [00:00<00:00, 1130.43it/s]

Bootstrapping f1:  80%|████████  | 804/1000 [00:00<00:00, 1135.78it/s]

Bootstrapping f1:  92%|█████████▏| 919/1000 [00:00<00:00, 1137.40it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1136.46it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 346/1000 [00:00<00:00, 3450.82it/s]

Bootstrapping accuracy:  69%|██████▉   | 692/1000 [00:00<00:00, 3348.87it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3355.41it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 129/1000 [00:00<00:00, 1289.91it/s]

Bootstrapping average_precision:  26%|██▌       | 262/1000 [00:00<00:00, 1308.73it/s]

Bootstrapping average_precision:  39%|███▉      | 393/1000 [00:00<00:00, 1298.19it/s]

Bootstrapping average_precision:  52%|█████▏    | 523/1000 [00:00<00:00, 1291.75it/s]

Bootstrapping average_precision:  65%|██████▌   | 653/1000 [00:00<00:00, 1277.07it/s]

Bootstrapping average_precision:  78%|███████▊  | 783/1000 [00:00<00:00, 1281.60it/s]

Bootstrapping average_precision:  91%|█████████▏| 913/1000 [00:00<00:00, 1287.08it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1290.05it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 81/1000 [00:00<00:01, 801.76it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 801.10it/s]

Bootstrapping roc_auc:  24%|██▍       | 243/1000 [00:00<00:00, 803.37it/s]

Bootstrapping roc_auc:  32%|███▏      | 324/1000 [00:00<00:00, 802.47it/s]

Bootstrapping roc_auc:  40%|████      | 405/1000 [00:00<00:00, 790.97it/s]

Bootstrapping roc_auc:  49%|████▊     | 486/1000 [00:00<00:00, 796.72it/s]

Bootstrapping roc_auc:  57%|█████▋    | 568/1000 [00:00<00:00, 801.04it/s]

Bootstrapping roc_auc:  65%|██████▍   | 649/1000 [00:00<00:00, 802.64it/s]

Bootstrapping roc_auc:  73%|███████▎  | 730/1000 [00:00<00:00, 798.94it/s]

Bootstrapping roc_auc:  81%|████████  | 810/1000 [00:01<00:00, 794.15it/s]

Bootstrapping roc_auc:  89%|████████▉ | 891/1000 [00:01<00:00, 797.02it/s]

Bootstrapping roc_auc:  97%|█████████▋| 971/1000 [00:01<00:00, 796.25it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 797.29it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1135.71it/s]

Bootstrapping precision:  23%|██▎       | 228/1000 [00:00<00:00, 1110.63it/s]

Bootstrapping precision:  34%|███▍      | 341/1000 [00:00<00:00, 1119.04it/s]

Bootstrapping precision:  45%|████▌     | 454/1000 [00:00<00:00, 1122.73it/s]

Bootstrapping precision:  57%|█████▋    | 568/1000 [00:00<00:00, 1127.70it/s]

Bootstrapping precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1134.15it/s]

Bootstrapping precision:  80%|███████▉  | 799/1000 [00:00<00:00, 1140.77it/s]

Bootstrapping precision:  91%|█████████▏| 914/1000 [00:00<00:00, 1124.97it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1125.30it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 113/1000 [00:00<00:00, 1117.72it/s]

Bootstrapping recall:  22%|██▎       | 225/1000 [00:00<00:00, 1110.85it/s]

Bootstrapping recall:  34%|███▎      | 337/1000 [00:00<00:00, 1103.14it/s]

Bootstrapping recall:  45%|████▍     | 448/1000 [00:00<00:00, 1083.65it/s]

Bootstrapping recall:  56%|█████▌    | 560/1000 [00:00<00:00, 1094.54it/s]

Bootstrapping recall:  67%|██████▋   | 671/1000 [00:00<00:00, 1098.38it/s]

Bootstrapping recall:  78%|███████▊  | 783/1000 [00:00<00:00, 1105.31it/s]

Bootstrapping recall:  89%|████████▉ | 894/1000 [00:00<00:00, 1099.11it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1099.05it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 111/1000 [00:00<00:00, 1103.77it/s]

Bootstrapping f1:  22%|██▏       | 224/1000 [00:00<00:00, 1118.53it/s]

Bootstrapping f1:  34%|███▎      | 336/1000 [00:00<00:00, 1114.76it/s]

Bootstrapping f1:  45%|████▌     | 450/1000 [00:00<00:00, 1121.10it/s]

Bootstrapping f1:  56%|█████▋    | 563/1000 [00:00<00:00, 1115.56it/s]

Bootstrapping f1:  68%|██████▊   | 678/1000 [00:00<00:00, 1126.03it/s]

Bootstrapping f1:  79%|███████▉  | 794/1000 [00:00<00:00, 1136.91it/s]

Bootstrapping f1:  91%|█████████▏| 914/1000 [00:00<00:00, 1155.84it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1133.17it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 337/1000 [00:00<00:00, 3366.17it/s]

Bootstrapping accuracy:  68%|██████▊   | 676/1000 [00:00<00:00, 3380.16it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3375.08it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem with 5 nodes and 4 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 140/1000 [00:00<00:00, 1392.05it/s]

Bootstrapping average_precision:  28%|██▊       | 280/1000 [00:00<00:00, 1375.83it/s]

Bootstrapping average_precision:  42%|████▏     | 418/1000 [00:00<00:00, 1374.59it/s]

Bootstrapping average_precision:  56%|█████▌    | 556/1000 [00:00<00:00, 1355.88it/s]

Bootstrapping average_precision:  69%|██████▉   | 692/1000 [00:00<00:00, 1356.87it/s]

Bootstrapping average_precision:  83%|████████▎ | 828/1000 [00:00<00:00, 1357.66it/s]

Bootstrapping average_precision:  96%|█████████▋| 964/1000 [00:00<00:00, 1354.91it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1358.69it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 834.28it/s]

Bootstrapping roc_auc:  17%|█▋        | 169/1000 [00:00<00:00, 840.42it/s]

Bootstrapping roc_auc:  25%|██▌       | 254/1000 [00:00<00:00, 841.21it/s]

Bootstrapping roc_auc:  34%|███▍      | 340/1000 [00:00<00:00, 846.67it/s]

Bootstrapping roc_auc:  43%|████▎     | 427/1000 [00:00<00:00, 852.90it/s]

Bootstrapping roc_auc:  52%|█████▏    | 515/1000 [00:00<00:00, 859.01it/s]

Bootstrapping roc_auc:  60%|██████    | 602/1000 [00:00<00:00, 861.93it/s]

Bootstrapping roc_auc:  69%|██████▉   | 690/1000 [00:00<00:00, 865.30it/s]

Bootstrapping roc_auc:  78%|███████▊  | 778/1000 [00:00<00:00, 869.10it/s]

Bootstrapping roc_auc:  87%|████████▋ | 866/1000 [00:01<00:00, 871.17it/s]

Bootstrapping roc_auc:  95%|█████████▌| 954/1000 [00:01<00:00, 871.06it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 861.81it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1192.49it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1176.85it/s]

Bootstrapping precision:  36%|███▌      | 358/1000 [00:00<00:00, 1171.41it/s]

Bootstrapping precision:  48%|████▊     | 478/1000 [00:00<00:00, 1178.25it/s]

Bootstrapping precision:  60%|█████▉    | 598/1000 [00:00<00:00, 1182.97it/s]

Bootstrapping precision:  72%|███████▏  | 717/1000 [00:00<00:00, 1182.07it/s]

Bootstrapping precision:  84%|████████▎ | 837/1000 [00:00<00:00, 1187.59it/s]

Bootstrapping precision:  96%|█████████▌| 958/1000 [00:00<00:00, 1194.41it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1184.47it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 119/1000 [00:00<00:00, 1181.07it/s]

Bootstrapping recall:  24%|██▍       | 238/1000 [00:00<00:00, 1157.82it/s]

Bootstrapping recall:  36%|███▌      | 355/1000 [00:00<00:00, 1162.05it/s]

Bootstrapping recall:  48%|████▊     | 475/1000 [00:00<00:00, 1175.96it/s]

Bootstrapping recall:  59%|█████▉    | 593/1000 [00:00<00:00, 1169.18it/s]

Bootstrapping recall:  71%|███████   | 712/1000 [00:00<00:00, 1173.57it/s]

Bootstrapping recall:  83%|████████▎ | 833/1000 [00:00<00:00, 1182.35it/s]

Bootstrapping recall:  95%|█████████▌| 952/1000 [00:00<00:00, 1171.84it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1168.36it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1128.12it/s]

Bootstrapping f1:  23%|██▎       | 231/1000 [00:00<00:00, 1152.00it/s]

Bootstrapping f1:  35%|███▍      | 347/1000 [00:00<00:00, 1152.73it/s]

Bootstrapping f1:  46%|████▋     | 465/1000 [00:00<00:00, 1162.86it/s]

Bootstrapping f1:  58%|█████▊    | 585/1000 [00:00<00:00, 1175.14it/s]

Bootstrapping f1:  70%|███████   | 703/1000 [00:00<00:00, 1173.81it/s]

Bootstrapping f1:  82%|████████▏ | 821/1000 [00:00<00:00, 1174.31it/s]

Bootstrapping f1:  94%|█████████▍| 939/1000 [00:00<00:00, 1170.32it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1163.90it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 338/1000 [00:00<00:00, 3379.40it/s]

Bootstrapping accuracy:  68%|██████▊   | 676/1000 [00:00<00:00, 3284.55it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3306.60it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  12%|█▎        | 125/1000 [00:00<00:00, 1249.69it/s]

Bootstrapping average_precision:  25%|██▌       | 252/1000 [00:00<00:00, 1256.93it/s]

Bootstrapping average_precision:  38%|███▊      | 384/1000 [00:00<00:00, 1283.77it/s]

Bootstrapping average_precision:  52%|█████▏    | 516/1000 [00:00<00:00, 1294.36it/s]

Bootstrapping average_precision:  65%|██████▍   | 647/1000 [00:00<00:00, 1296.63it/s]

Bootstrapping average_precision:  78%|███████▊  | 777/1000 [00:00<00:00, 1290.29it/s]

Bootstrapping average_precision:  91%|█████████ | 908/1000 [00:00<00:00, 1294.35it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1288.77it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 81/1000 [00:00<00:01, 804.84it/s]

Bootstrapping roc_auc:  16%|█▋        | 164/1000 [00:00<00:01, 814.53it/s]

Bootstrapping roc_auc:  25%|██▍       | 249/1000 [00:00<00:00, 824.80it/s]

Bootstrapping roc_auc:  33%|███▎      | 332/1000 [00:00<00:00, 820.72it/s]

Bootstrapping roc_auc:  42%|████▏     | 415/1000 [00:00<00:00, 809.93it/s]

Bootstrapping roc_auc:  50%|████▉     | 497/1000 [00:00<00:00, 795.70it/s]

Bootstrapping roc_auc:  58%|█████▊    | 578/1000 [00:00<00:00, 799.44it/s]

Bootstrapping roc_auc:  66%|██████▌   | 661/1000 [00:00<00:00, 808.04it/s]

Bootstrapping roc_auc:  74%|███████▍  | 744/1000 [00:00<00:00, 813.72it/s]

Bootstrapping roc_auc:  83%|████████▎ | 826/1000 [00:01<00:00, 815.30it/s]

Bootstrapping roc_auc:  91%|█████████ | 908/1000 [00:01<00:00, 805.81it/s]

Bootstrapping roc_auc:  99%|█████████▉| 991/1000 [00:01<00:00, 811.86it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 809.85it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 111/1000 [00:00<00:00, 1109.05it/s]

Bootstrapping precision:  22%|██▏       | 222/1000 [00:00<00:00, 1108.23it/s]

Bootstrapping precision:  34%|███▎      | 337/1000 [00:00<00:00, 1123.06it/s]

Bootstrapping precision:  45%|████▌     | 450/1000 [00:00<00:00, 1121.39it/s]

Bootstrapping precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1123.37it/s]

Bootstrapping precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1128.67it/s]

Bootstrapping precision:  79%|███████▉  | 790/1000 [00:00<00:00, 1126.25it/s]

Bootstrapping precision:  90%|█████████ | 903/1000 [00:00<00:00, 1123.65it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1123.26it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 114/1000 [00:00<00:00, 1133.29it/s]

Bootstrapping recall:  23%|██▎       | 229/1000 [00:00<00:00, 1140.35it/s]

Bootstrapping recall:  35%|███▍      | 346/1000 [00:00<00:00, 1151.27it/s]

Bootstrapping recall:  46%|████▌     | 462/1000 [00:00<00:00, 1139.19it/s]

Bootstrapping recall:  58%|█████▊    | 576/1000 [00:00<00:00, 1118.53it/s]

Bootstrapping recall:  69%|██████▉   | 688/1000 [00:00<00:00, 1115.39it/s]

Bootstrapping recall:  80%|████████  | 800/1000 [00:00<00:00, 1115.99it/s]

Bootstrapping recall:  92%|█████████▏| 917/1000 [00:00<00:00, 1130.51it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1123.51it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 110/1000 [00:00<00:00, 1092.60it/s]

Bootstrapping f1:  22%|██▏       | 221/1000 [00:00<00:00, 1100.78it/s]

Bootstrapping f1:  33%|███▎      | 332/1000 [00:00<00:00, 1088.36it/s]

Bootstrapping f1:  45%|████▍     | 446/1000 [00:00<00:00, 1105.66it/s]

Bootstrapping f1:  56%|█████▌    | 560/1000 [00:00<00:00, 1116.07it/s]

Bootstrapping f1:  67%|██████▋   | 672/1000 [00:00<00:00, 1107.53it/s]

Bootstrapping f1:  79%|███████▊  | 786/1000 [00:00<00:00, 1115.15it/s]

Bootstrapping f1:  90%|████████▉ | 898/1000 [00:00<00:00, 1109.85it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1105.14it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 332/1000 [00:00<00:00, 3314.17it/s]

Bootstrapping accuracy:  68%|██████▊   | 680/1000 [00:00<00:00, 3409.40it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3415.51it/s]

In [13]:
pd.DataFrame(results).to_csv('biomarker_counts_fixed/No Drugs.csv', index=False)
pd.DataFrame(results)

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,LGBN,Control,"0.75 (0.71, 0.79)","0.90 (0.88, 0.91)","0.95 (0.93, 0.96)","0.77 (0.75, 0.79)","0.83 (0.81, 0.85)","0.95 (0.94, 0.95)",0.135,624,34
1,XGB,Control,"0.80 (0.77, 0.83)","0.92 (0.91, 0.94)","0.92 (0.90, 0.94)","0.80 (0.78, 0.82)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.090,624,34
2,LGBN,Correlation,"0.72 (0.68, 0.76)","0.86 (0.84, 0.89)","0.94 (0.93, 0.96)","0.73 (0.71, 0.75)","0.80 (0.77, 0.82)","0.94 (0.93, 0.95)",0.129,70,26
3,XGB,Correlation,"0.75 (0.71, 0.79)","0.89 (0.87, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.82 (0.80, 0.85)","0.94 (0.93, 0.95)",0.111,70,26
4,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.74 (0.70, 0.78)","0.90 (0.88, 0.92)","0.93 (0.91, 0.95)","0.75 (0.73, 0.77)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.133,217,12
5,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.77 (0.74, 0.81)","0.90 (0.88, 0.92)","0.91 (0.89, 0.93)","0.80 (0.78, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.098,217,12
6,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.74 (0.71, 0.78)","0.90 (0.88, 0.92)","0.92 (0.90, 0.94)","0.76 (0.73, 0.78)","0.81 (0.79, 0.84)","0.94 (0.93, 0.95)",0.138,290,16
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.78 (0.74, 0.81)","0.90 (0.89, 0.92)","0.91 (0.89, 0.93)","0.81 (0.78, 0.83)","0.85 (0.83, 0.87)","0.95 (0.94, 0.96)",0.099,290,16
8,LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.73 (0.69, 0.77)","0.89 (0.87, 0.91)","0.92 (0.90, 0.94)","0.76 (0.73, 0.78)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.137,271,15
9,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.78 (0.75, 0.82)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.096,271,15
10,LGBN,Simplified Clinician Consensus,"0.75 (0.71, 0.79)","0.90 (0.88, 0.91)","0.94 (0.93, 0.95)","0.75 (0.73, 0.77)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.131,179,10
11,XGB,Simplified Clinician Consensus,"0.77 (0.73, 0.80)","0.90 (0.88, 0.92)","0.93 (0.91, 0.94)","0.79 (0.77, 0.81)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.096,179,10
12,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.94 (0.92, 0.95)","0.74 (0.72, 0.77)","0.81 (0.78, 0.83)","0.94 (0.93, 0.95)",0.133,141,8
13,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.91 (0.89, 0.93)","0.78 (0.76, 0.80)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.100,141,8
14,LGBN,Simplified PCMB,"0.73 (0.69, 0.77)","0.89 (0.87, 0.91)","0.93 (0.91, 0.95)","0.74 (0.72, 0.77)","0.80 (0.78, 0.83)","0.94 (0.93, 0.95)",0.133,179,10
15,XGB,Simplified PCMB,"0.78 (0.75, 0.81)","0.91 (0.89, 0.93)","0.92 (0.90, 0.93)","0.80 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.101,179,10
16,LGBN,Simplified Golem,"0.72 (0.68, 0.76)","0.89 (0.87, 0.91)","0.92 (0.90, 0.94)","0.74 (0.72, 0.76)","0.80 (0.78, 0.82)","0.94 (0.93, 0.95)",0.136,180,10
17,XGB,Simplified Golem,"0.78 (0.75, 0.81)","0.92 (0.90, 0.93)","0.91 (0.89, 0.93)","0.79 (0.77, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.098,180,10
18,LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.71 (0.67, 0.76)","0.89 (0.87, 0.91)","0.93 (0.91, 0.94)","0.74 (0.71, 0.76)","0.80 (0.77, 0.82)","0.94 (0.93, 0.95)",0.131,88,5
19,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.76 (0.73, 0.80)","0.90 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,88,5
20,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.72 (0.67, 0.75)","0.88 (0.86, 0.90)","0.94 (0.92, 0.95)","0.73 (0.70, 0.75)","0.79 (0.77, 0.81)","0.94 (0.93, 0.94)",0.130,69,4
21,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.74 (0.70, 0.77)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.76, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.106,69,4

In [14]:
aurocs = []
auprcs = []
print(len(model_preds))
# Model Comparisons using DeLong Test
for (model1_name, model2_name) in combinations(model_preds.keys(), 2):
        model1 = model_preds[model1_name]
        model2 = model_preds[model2_name]
        comparison_result1, comparison_result2 = compare_models(y_test.Outcome, model1, model2)
        aurocs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Z-score': f"{comparison_result1[0]:.4f}", 'P-value': f"{comparison_result1[1]:.3e}", 'p_numeric': comparison_result1[1]})
        auprcs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Avg Precision Model 1': f"{comparison_result2[0]:.4f}", 'Avg Precision Model 2': f"{comparison_result2[1]:.4f}", 'P-value': f"{comparison_result2[2]:.3e}", 'Benchmark': comparison_result2[3], 'Samples Mean': f"{comparison_result2[4]:.4f}", 'Samples Std': f"{comparison_result2[5]:.4f}"})
aurocs_df = pd.DataFrame(aurocs)
auprcs_df = pd.DataFrame(auprcs)
aurocs_df.to_csv('biomarker_counts_fixed/delong_test_no_drugs_auroc.csv', index=False)
auprcs_df.to_csv('biomarker_counts_fixed/delong_test_no_drugs_auprc.csv', index=False)

11

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 67/1000 [00:00<00:01, 667.48it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 678.02it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 204/1000 [00:00<00:01, 653.23it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 271/1000 [00:00<00:01, 659.50it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 338/1000 [00:00<00:00, 662.82it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 407/1000 [00:00<00:00, 670.95it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 477/1000 [00:00<00:00, 679.98it/s]

Computing average_precision Permutation Test p-value:  55%|█████▍    | 546/1000 [00:00<00:00, 680.38it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 615/1000 [00:00<00:00, 677.91it/s]

Computing average_precision Permutation Test p-value:  68%|██████▊   | 684/1000 [00:01<00:00, 680.36it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 755/1000 [00:01<00:00, 688.02it/s]

Computing average_precision Permutation Test p-value:  82%|████████▎ | 825/1000 [00:01<00:00, 688.24it/s]

Computing average_precision Permutation Test p-value:  90%|████████▉ | 895/1000 [00:01<00:00, 689.60it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▋| 965/1000 [00:01<00:00, 691.60it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 680.20it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 691.91it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 686.85it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 684.93it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 278/1000 [00:00<00:01, 680.20it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 347/1000 [00:00<00:00, 681.72it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 416/1000 [00:00<00:00, 683.70it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 486/1000 [00:00<00:00, 686.59it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 555/1000 [00:00<00:00, 677.54it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 623/1000 [00:00<00:00, 665.51it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 691/1000 [00:01<00:00, 667.92it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 758/1000 [00:01<00:00, 659.68it/s]

Computing average_precision Permutation Test p-value:  82%|████████▎ | 825/1000 [00:01<00:00, 656.98it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 893/1000 [00:01<00:00, 662.68it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 962/1000 [00:01<00:00, 668.57it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 672.57it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 67/1000 [00:00<00:01, 665.09it/s]

Computing average_precision Permutation Test p-value:  13%|█▎        | 134/1000 [00:00<00:01, 662.53it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 202/1000 [00:00<00:01, 667.21it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 269/1000 [00:00<00:01, 656.49it/s]

Computing average_precision Permutation Test p-value:  34%|███▎      | 336/1000 [00:00<00:01, 658.35it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 406/1000 [00:00<00:00, 669.20it/s]

Computing average_precision Permutation Test p-value:  47%|████▋     | 474/1000 [00:00<00:00, 671.33it/s]

Computing average_precision Permutation Test p-value:  54%|█████▍    | 544/1000 [00:00<00:00, 679.16it/s]

Computing average_precision Permutation Test p-value:  61%|██████▏   | 614/1000 [00:00<00:00, 685.19it/s]

Computing average_precision Permutation Test p-value:  68%|██████▊   | 683/1000 [00:01<00:00, 677.28it/s]

Computing average_precision Permutation Test p-value:  75%|███████▌  | 751/1000 [00:01<00:00, 674.74it/s]

Computing average_precision Permutation Test p-value:  82%|████████▏ | 821/1000 [00:01<00:00, 681.02it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 890/1000 [00:01<00:00, 682.00it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 959/1000 [00:01<00:00, 679.77it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 674.20it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   6%|▋         | 65/1000 [00:00<00:01, 643.02it/s]

Computing average_precision Permutation Test p-value:  13%|█▎        | 132/1000 [00:00<00:01, 656.54it/s]

Computing average_precision Permutation Test p-value:  20%|█▉        | 198/1000 [00:00<00:01, 652.99it/s]

Computing average_precision Permutation Test p-value:  26%|██▋       | 265/1000 [00:00<00:01, 656.26it/s]

Computing average_precision Permutation Test p-value:  34%|███▎      | 335/1000 [00:00<00:00, 668.81it/s]

Computing average_precision Permutation Test p-value:  40%|████      | 405/1000 [00:00<00:00, 678.86it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 476/1000 [00:00<00:00, 685.88it/s]

Computing average_precision Permutation Test p-value:  55%|█████▍    | 545/1000 [00:00<00:00, 682.35it/s]

Computing average_precision Permutation Test p-value:  61%|██████▏   | 614/1000 [00:00<00:00, 683.07it/s]

Computing average_precision Permutation Test p-value:  68%|██████▊   | 684/1000 [00:01<00:00, 687.04it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 755/1000 [00:01<00:00, 692.93it/s]

Computing average_precision Permutation Test p-value:  82%|████████▎ | 825/1000 [00:01<00:00, 694.91it/s]

Computing average_precision Permutation Test p-value:  90%|████████▉ | 895/1000 [00:01<00:00, 682.53it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▋| 964/1000 [00:01<00:00, 674.78it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 676.43it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 693.96it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 694.72it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 695.99it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 697.23it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 694.38it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 420/1000 [00:00<00:00, 676.61it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 488/1000 [00:00<00:00, 675.27it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 559/1000 [00:00<00:00, 683.95it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 628/1000 [00:00<00:00, 682.97it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 697/1000 [00:01<00:00, 674.38it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 765/1000 [00:01<00:00, 674.62it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 835/1000 [00:01<00:00, 680.58it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 906/1000 [00:01<00:00, 688.17it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 975/1000 [00:01<00:00, 686.61it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 683.48it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 66/1000 [00:00<00:01, 656.06it/s]

Computing average_precision Permutation Test p-value:  13%|█▎        | 132/1000 [00:00<00:01, 649.95it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 201/1000 [00:00<00:01, 665.76it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 272/1000 [00:00<00:01, 682.05it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 341/1000 [00:00<00:00, 680.76it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 411/1000 [00:00<00:00, 686.37it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 480/1000 [00:00<00:00, 685.39it/s]

Computing average_precision Permutation Test p-value:  55%|█████▍    | 549/1000 [00:00<00:00, 682.13it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 620/1000 [00:00<00:00, 689.13it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 689/1000 [00:01<00:00, 688.77it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 760/1000 [00:01<00:00, 693.81it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 830/1000 [00:01<00:00, 689.24it/s]

Computing average_precision Permutation Test p-value:  90%|████████▉ | 899/1000 [00:01<00:00, 682.34it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 968/1000 [00:01<00:00, 679.76it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 681.79it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 681.70it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 682.92it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 211/1000 [00:00<00:01, 699.97it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 705.05it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 702.10it/s]

Computing average_precision Permutation Test p-value:  42%|████▎     | 425/1000 [00:00<00:00, 684.27it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 494/1000 [00:00<00:00, 680.95it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 563/1000 [00:00<00:00, 677.09it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 631/1000 [00:00<00:00, 671.91it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 700/1000 [00:01<00:00, 675.22it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 772/1000 [00:01<00:00, 686.47it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 844/1000 [00:01<00:00, 693.47it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 915/1000 [00:01<00:00, 697.23it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▊| 986/1000 [00:01<00:00, 699.84it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 689.17it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 704.68it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 705.87it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 702.26it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 702.93it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 355/1000 [00:00<00:00, 702.83it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 427/1000 [00:00<00:00, 706.13it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 498/1000 [00:00<00:00, 693.89it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 568/1000 [00:00<00:00, 688.37it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 637/1000 [00:00<00:00, 687.48it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 707/1000 [00:01<00:00, 689.93it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 777/1000 [00:01<00:00, 682.28it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 846/1000 [00:01<00:00, 676.94it/s]

Computing average_precision Permutation Test p-value:  91%|█████████▏| 914/1000 [00:01<00:00, 676.09it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 984/1000 [00:01<00:00, 681.31it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 689.26it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 712.00it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 478.71it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 555.78it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 285/1000 [00:00<00:01, 605.33it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 356/1000 [00:00<00:01, 637.05it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 642.43it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 493/1000 [00:00<00:00, 658.17it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 565/1000 [00:00<00:00, 673.89it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 637/1000 [00:00<00:00, 684.97it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 709/1000 [00:01<00:00, 694.10it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 779/1000 [00:01<00:00, 695.00it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 849/1000 [00:01<00:00, 695.19it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 921/1000 [00:01<00:00, 700.98it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 992/1000 [00:01<00:00, 699.35it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 661.09it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 707.47it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 700.29it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 688.90it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 282/1000 [00:00<00:01, 686.02it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 352/1000 [00:00<00:00, 690.10it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 422/1000 [00:00<00:00, 686.43it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 687.88it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 561/1000 [00:00<00:00, 688.29it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 630/1000 [00:00<00:00, 687.75it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 699/1000 [00:01<00:00, 683.91it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 768/1000 [00:01<00:00, 670.89it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 836/1000 [00:01<00:00, 667.61it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 903/1000 [00:01<00:00, 667.24it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 973/1000 [00:01<00:00, 675.18it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 681.01it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 689.79it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 687.58it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 208/1000 [00:00<00:01, 684.33it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 277/1000 [00:00<00:01, 684.56it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 346/1000 [00:00<00:00, 675.27it/s]

Computing average_precision Permutation Test p-value:  41%|████▏     | 414/1000 [00:00<00:00, 674.70it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 485/1000 [00:00<00:00, 684.00it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 556/1000 [00:00<00:00, 690.48it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 626/1000 [00:00<00:00, 687.47it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 695/1000 [00:01<00:00, 684.79it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 764/1000 [00:01<00:00, 679.97it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 833/1000 [00:01<00:00, 677.49it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 901/1000 [00:01<00:00, 677.84it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 970/1000 [00:01<00:00, 680.45it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 682.21it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 684.46it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 141/1000 [00:00<00:01, 701.03it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 703.87it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 701.89it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 684.83it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 686.40it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 494/1000 [00:00<00:00, 691.24it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 567/1000 [00:00<00:00, 701.27it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 638/1000 [00:00<00:00, 700.38it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 709/1000 [00:01<00:00, 695.85it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 779/1000 [00:01<00:00, 696.21it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 849/1000 [00:01<00:00, 686.08it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 918/1000 [00:01<00:00, 683.83it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 989/1000 [00:01<00:00, 690.20it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 692.56it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 708.97it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 699.86it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 701.44it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 691.72it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 686.20it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 680.82it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 673.82it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 561/1000 [00:00<00:00, 677.28it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 633/1000 [00:00<00:00, 687.85it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 705/1000 [00:01<00:00, 696.03it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 778/1000 [00:01<00:00, 703.69it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 849/1000 [00:01<00:00, 703.81it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 920/1000 [00:01<00:00, 699.51it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 990/1000 [00:01<00:00, 692.76it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 691.67it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 689.53it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 141/1000 [00:00<00:01, 703.60it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 693.79it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 282/1000 [00:00<00:01, 688.58it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 351/1000 [00:00<00:00, 685.38it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 420/1000 [00:00<00:00, 683.30it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 490/1000 [00:00<00:00, 687.08it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 559/1000 [00:00<00:00, 687.99it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 629/1000 [00:00<00:00, 688.98it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 698/1000 [00:01<00:00, 686.06it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 767/1000 [00:01<00:00, 678.54it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 836/1000 [00:01<00:00, 679.13it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 906/1000 [00:01<00:00, 684.12it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 976/1000 [00:01<00:00, 688.30it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 687.06it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 688.77it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 690.87it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 680.41it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 278/1000 [00:00<00:01, 668.13it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 346/1000 [00:00<00:00, 671.18it/s]

Computing average_precision Permutation Test p-value:  41%|████▏     | 414/1000 [00:00<00:00, 665.24it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 482/1000 [00:00<00:00, 668.88it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 550/1000 [00:00<00:00, 670.37it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 618/1000 [00:00<00:00, 670.13it/s]

Computing average_precision Permutation Test p-value:  69%|██████▊   | 686/1000 [00:01<00:00, 671.20it/s]

Computing average_precision Permutation Test p-value:  75%|███████▌  | 754/1000 [00:01<00:00, 667.92it/s]

Computing average_precision Permutation Test p-value:  82%|████████▏ | 822/1000 [00:01<00:00, 671.38it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 892/1000 [00:01<00:00, 678.16it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 961/1000 [00:01<00:00, 680.73it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 675.33it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 692.60it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 687.92it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 682.78it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 279/1000 [00:00<00:01, 686.73it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 348/1000 [00:00<00:00, 685.77it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 417/1000 [00:00<00:00, 687.19it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 486/1000 [00:00<00:00, 683.52it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 556/1000 [00:00<00:00, 686.81it/s]

Computing average_precision Permutation Test p-value:  62%|██████▎   | 625/1000 [00:00<00:00, 683.16it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 694/1000 [00:01<00:00, 681.49it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 764/1000 [00:01<00:00, 685.04it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 833/1000 [00:01<00:00, 680.89it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 902/1000 [00:01<00:00, 682.03it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 973/1000 [00:01<00:00, 689.09it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 685.99it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 698.46it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 707.28it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 712.78it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 705.87it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 358/1000 [00:00<00:00, 709.91it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 431/1000 [00:00<00:00, 714.77it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 503/1000 [00:00<00:00, 710.45it/s]

Computing average_precision Permutation Test p-value:  57%|█████▊    | 575/1000 [00:00<00:00, 708.45it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 647/1000 [00:00<00:00, 710.91it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 720/1000 [00:01<00:00, 714.67it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 792/1000 [00:01<00:00, 709.82it/s]

Computing average_precision Permutation Test p-value:  86%|████████▋ | 863/1000 [00:01<00:00, 708.68it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▎| 935/1000 [00:01<00:00, 708.98it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 708.44it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 700.94it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 701.33it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 703.10it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 704.33it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 355/1000 [00:00<00:00, 703.65it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 426/1000 [00:00<00:00, 701.52it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 497/1000 [00:00<00:00, 690.21it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 568/1000 [00:00<00:00, 695.41it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 639/1000 [00:00<00:00, 698.97it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 711/1000 [00:01<00:00, 703.16it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 782/1000 [00:01<00:00, 697.57it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 852/1000 [00:01<00:00, 697.15it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 922/1000 [00:01<00:00, 688.20it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 991/1000 [00:01<00:00, 688.17it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 694.92it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 692.53it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 682.15it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 673.94it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 277/1000 [00:00<00:01, 672.24it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 345/1000 [00:00<00:00, 674.77it/s]

Computing average_precision Permutation Test p-value:  41%|████▏     | 413/1000 [00:00<00:00, 675.66it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 482/1000 [00:00<00:00, 678.73it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 550/1000 [00:00<00:00, 679.07it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 618/1000 [00:00<00:00, 674.71it/s]

Computing average_precision Permutation Test p-value:  69%|██████▊   | 686/1000 [00:01<00:00, 668.27it/s]

Computing average_precision Permutation Test p-value:  75%|███████▌  | 753/1000 [00:01<00:00, 667.60it/s]

Computing average_precision Permutation Test p-value:  82%|████████▏ | 820/1000 [00:01<00:00, 661.38it/s]

Computing average_precision Permutation Test p-value:  89%|████████▊ | 887/1000 [00:01<00:00, 663.69it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 956/1000 [00:01<00:00, 670.10it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 671.86it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 67/1000 [00:00<00:01, 664.14it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 135/1000 [00:00<00:01, 669.20it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 204/1000 [00:00<00:01, 676.85it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 275/1000 [00:00<00:01, 688.17it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 344/1000 [00:00<00:00, 688.40it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 417/1000 [00:00<00:00, 699.71it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 487/1000 [00:00<00:00, 698.09it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 557/1000 [00:00<00:00, 693.84it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 628/1000 [00:00<00:00, 697.58it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 699/1000 [00:01<00:00, 698.08it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 770/1000 [00:01<00:00, 698.70it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 842/1000 [00:01<00:00, 703.59it/s]

Computing average_precision Permutation Test p-value:  91%|█████████▏| 914/1000 [00:01<00:00, 707.58it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 985/1000 [00:01<00:00, 699.33it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.04it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 694.23it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 141/1000 [00:00<00:01, 699.83it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 700.66it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 285/1000 [00:00<00:01, 708.04it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 356/1000 [00:00<00:00, 703.12it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 428/1000 [00:00<00:00, 705.42it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 499/1000 [00:00<00:00, 702.39it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 706.31it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 642/1000 [00:00<00:00, 703.32it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 713/1000 [00:01<00:00, 703.56it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 784/1000 [00:01<00:00, 699.14it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 854/1000 [00:01<00:00, 694.04it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 924/1000 [00:01<00:00, 686.65it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 993/1000 [00:01<00:00, 681.21it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.32it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 687.21it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 689.40it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 208/1000 [00:00<00:01, 689.48it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 279/1000 [00:00<00:01, 696.16it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 700.45it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 422/1000 [00:00<00:00, 704.07it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 494/1000 [00:00<00:00, 706.91it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 565/1000 [00:00<00:00, 700.50it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 636/1000 [00:00<00:00, 696.66it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 706/1000 [00:01<00:00, 693.37it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 776/1000 [00:01<00:00, 688.14it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 847/1000 [00:01<00:00, 691.87it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 919/1000 [00:01<00:00, 698.78it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 991/1000 [00:01<00:00, 702.11it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 697.56it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 711.93it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 695.57it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 699.54it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 287/1000 [00:00<00:01, 706.95it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 359/1000 [00:00<00:00, 708.51it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 431/1000 [00:00<00:00, 710.14it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 503/1000 [00:00<00:00, 713.11it/s]

Computing average_precision Permutation Test p-value:  57%|█████▊    | 575/1000 [00:00<00:00, 706.31it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 647/1000 [00:00<00:00, 710.52it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 719/1000 [00:01<00:00, 708.31it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 790/1000 [00:01<00:00, 696.40it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 860/1000 [00:01<00:00, 692.74it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 930/1000 [00:01<00:00, 690.77it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 686.94it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 699.36it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 682.54it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 688.73it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 211/1000 [00:00<00:01, 702.52it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 282/1000 [00:00<00:01, 702.03it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 706.69it/s]

Computing average_precision Permutation Test p-value:  42%|████▎     | 425/1000 [00:00<00:00, 696.23it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 495/1000 [00:00<00:00, 693.49it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 566/1000 [00:00<00:00, 697.59it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 638/1000 [00:00<00:00, 704.27it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 710/1000 [00:01<00:00, 707.34it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 782/1000 [00:01<00:00, 708.87it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 854/1000 [00:01<00:00, 710.06it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 927/1000 [00:01<00:00, 713.82it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 999/1000 [00:01<00:00, 708.85it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 703.81it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 684.29it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 686.73it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 207/1000 [00:00<00:01, 685.49it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 276/1000 [00:00<00:01, 685.85it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 345/1000 [00:00<00:00, 686.82it/s]

Computing average_precision Permutation Test p-value:  41%|████▏     | 414/1000 [00:00<00:00, 683.48it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 485/1000 [00:00<00:00, 689.38it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 556/1000 [00:00<00:00, 695.78it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 627/1000 [00:00<00:00, 699.47it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 698/1000 [00:01<00:00, 702.54it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 770/1000 [00:01<00:00, 704.57it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 841/1000 [00:01<00:00, 703.09it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 912/1000 [00:01<00:00, 701.69it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 983/1000 [00:01<00:00, 702.94it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 696.08it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 712.92it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 713.37it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 709.91it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 287/1000 [00:00<00:01, 692.31it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 357/1000 [00:00<00:00, 689.56it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 426/1000 [00:00<00:00, 680.52it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 496/1000 [00:00<00:00, 684.40it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 568/1000 [00:00<00:00, 692.28it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 640/1000 [00:00<00:00, 699.30it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 710/1000 [00:01<00:00, 689.43it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 781/1000 [00:01<00:00, 693.43it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 851/1000 [00:01<00:00, 691.55it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 923/1000 [00:01<00:00, 697.89it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 994/1000 [00:01<00:00, 700.78it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.32it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 717.04it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 679.73it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 672.11it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 281/1000 [00:00<00:01, 665.77it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 349/1000 [00:00<00:00, 669.09it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 416/1000 [00:00<00:00, 667.92it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 485/1000 [00:00<00:00, 674.84it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 554/1000 [00:00<00:00, 678.05it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 623/1000 [00:00<00:00, 679.75it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 691/1000 [00:01<00:00, 674.69it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 760/1000 [00:01<00:00, 678.57it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 830/1000 [00:01<00:00, 682.27it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 900/1000 [00:01<00:00, 686.99it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 971/1000 [00:01<00:00, 693.89it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 681.29it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 703.21it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 707.68it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 708.47it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 708.97it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 358/1000 [00:00<00:00, 710.72it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 430/1000 [00:00<00:00, 707.75it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 501/1000 [00:00<00:00, 700.05it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 572/1000 [00:00<00:00, 695.67it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 642/1000 [00:00<00:00, 695.47it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 713/1000 [00:01<00:00, 699.16it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 784/1000 [00:01<00:00, 701.55it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 855/1000 [00:01<00:00, 699.19it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 927/1000 [00:01<00:00, 704.28it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 998/1000 [00:01<00:00, 705.60it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 702.74it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 703.81it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 702.18it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 710.41it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:00, 716.19it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 360/1000 [00:00<00:00, 715.16it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 715.84it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 504/1000 [00:00<00:00, 716.67it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 577/1000 [00:00<00:00, 719.36it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 649/1000 [00:00<00:00, 718.86it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 722/1000 [00:01<00:00, 719.63it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 794/1000 [00:01<00:00, 719.42it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 866/1000 [00:01<00:00, 717.55it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 938/1000 [00:01<00:00, 711.12it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 713.90it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 678.11it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 684.93it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 207/1000 [00:00<00:01, 687.19it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 278/1000 [00:00<00:01, 695.96it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 703.85it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 421/1000 [00:00<00:00, 704.30it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 697.98it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 562/1000 [00:00<00:00, 692.37it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 633/1000 [00:00<00:00, 695.42it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 703/1000 [00:01<00:00, 681.03it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 772/1000 [00:01<00:00, 679.37it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 841/1000 [00:01<00:00, 682.03it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 912/1000 [00:01<00:00, 688.80it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 984/1000 [00:01<00:00, 697.95it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 691.62it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 706.80it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 706.31it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 689.91it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 678.63it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 352/1000 [00:00<00:00, 682.19it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 421/1000 [00:00<00:00, 680.13it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 490/1000 [00:00<00:00, 677.83it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 562/1000 [00:00<00:00, 689.72it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 631/1000 [00:00<00:00, 682.28it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 700/1000 [00:01<00:00, 682.34it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 769/1000 [00:01<00:00, 669.61it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 837/1000 [00:01<00:00, 664.17it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 906/1000 [00:01<00:00, 669.33it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 974/1000 [00:01<00:00, 671.04it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 677.85it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 674.43it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 656.99it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 202/1000 [00:00<00:01, 632.42it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 268/1000 [00:00<00:01, 642.55it/s]

Computing average_precision Permutation Test p-value:  33%|███▎      | 333/1000 [00:00<00:01, 644.06it/s]

Computing average_precision Permutation Test p-value:  40%|████      | 401/1000 [00:00<00:00, 653.52it/s]

Computing average_precision Permutation Test p-value:  47%|████▋     | 469/1000 [00:00<00:00, 660.69it/s]

Computing average_precision Permutation Test p-value:  54%|█████▍    | 539/1000 [00:00<00:00, 672.14it/s]

Computing average_precision Permutation Test p-value:  61%|██████    | 610/1000 [00:00<00:00, 683.37it/s]

Computing average_precision Permutation Test p-value:  68%|██████▊   | 679/1000 [00:01<00:00, 679.37it/s]

Computing average_precision Permutation Test p-value:  75%|███████▍  | 747/1000 [00:01<00:00, 672.70it/s]

Computing average_precision Permutation Test p-value:  82%|████████▏ | 817/1000 [00:01<00:00, 678.35it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 888/1000 [00:01<00:00, 686.02it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▌| 960/1000 [00:01<00:00, 693.07it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 670.59it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 67/1000 [00:00<00:01, 667.63it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 692.55it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 673.68it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 277/1000 [00:00<00:01, 671.47it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 347/1000 [00:00<00:00, 678.94it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 416/1000 [00:00<00:00, 680.95it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 485/1000 [00:00<00:00, 673.97it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 553/1000 [00:00<00:00, 674.86it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 624/1000 [00:00<00:00, 683.15it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 694/1000 [00:01<00:00, 687.81it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 763/1000 [00:01<00:00, 687.26it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 832/1000 [00:01<00:00, 686.87it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 901/1000 [00:01<00:00, 684.49it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 970/1000 [00:01<00:00, 677.61it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 679.34it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 677.23it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 137/1000 [00:00<00:01, 679.46it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 205/1000 [00:00<00:01, 675.07it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 273/1000 [00:00<00:01, 676.52it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 345/1000 [00:00<00:00, 689.44it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 415/1000 [00:00<00:00, 691.92it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 486/1000 [00:00<00:00, 697.68it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 556/1000 [00:00<00:00, 693.35it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 627/1000 [00:00<00:00, 696.84it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 698/1000 [00:01<00:00, 700.87it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 769/1000 [00:01<00:00, 701.00it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 840/1000 [00:01<00:00, 692.92it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 910/1000 [00:01<00:00, 690.62it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 981/1000 [00:01<00:00, 694.08it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 691.05it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 67/1000 [00:00<00:01, 667.44it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 679.08it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 204/1000 [00:00<00:01, 678.80it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 273/1000 [00:00<00:01, 679.91it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 344/1000 [00:00<00:00, 688.40it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 415/1000 [00:00<00:00, 691.69it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 485/1000 [00:00<00:00, 687.02it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 554/1000 [00:00<00:00, 681.44it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 624/1000 [00:00<00:00, 685.65it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 696/1000 [00:01<00:00, 695.13it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 767/1000 [00:01<00:00, 697.65it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 839/1000 [00:01<00:00, 701.92it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 910/1000 [00:01<00:00, 695.24it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 980/1000 [00:01<00:00, 686.95it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 687.08it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 675.50it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 691.92it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 709.50it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 285/1000 [00:00<00:01, 713.49it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 357/1000 [00:00<00:00, 710.54it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 429/1000 [00:00<00:00, 708.30it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 500/1000 [00:00<00:00, 707.46it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 700.78it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 642/1000 [00:00<00:00, 698.70it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 712/1000 [00:01<00:00, 696.56it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 782/1000 [00:01<00:00, 690.02it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 854/1000 [00:01<00:00, 696.42it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 926/1000 [00:01<00:00, 702.00it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 997/1000 [00:01<00:00, 704.11it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 701.46it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 699.43it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 692.37it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 701.55it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 702.07it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 700.34it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 426/1000 [00:00<00:00, 706.35it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 497/1000 [00:00<00:00, 699.89it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 568/1000 [00:00<00:00, 692.83it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 638/1000 [00:00<00:00, 688.84it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 708/1000 [00:01<00:00, 689.41it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 777/1000 [00:01<00:00, 689.00it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 847/1000 [00:01<00:00, 689.64it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 920/1000 [00:01<00:00, 700.18it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 992/1000 [00:01<00:00, 705.74it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 697.76it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 718.56it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 700.89it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 683.28it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 285/1000 [00:00<00:01, 688.43it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 356/1000 [00:00<00:00, 692.74it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 427/1000 [00:00<00:00, 698.11it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 499/1000 [00:00<00:00, 703.88it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 706.38it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 643/1000 [00:00<00:00, 709.52it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 714/1000 [00:01<00:00, 702.54it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 785/1000 [00:01<00:00, 701.59it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 857/1000 [00:01<00:00, 705.87it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 929/1000 [00:01<00:00, 707.52it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 703.74it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 721.96it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 716.65it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 703.81it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 289/1000 [00:00<00:01, 697.75it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 359/1000 [00:00<00:00, 687.86it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 428/1000 [00:00<00:00, 687.57it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 500/1000 [00:00<00:00, 695.60it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 699.48it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 642/1000 [00:00<00:00, 701.39it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 714/1000 [00:01<00:00, 704.26it/s]

Computing average_precision Permutation Test p-value:  79%|███████▊  | 787/1000 [00:01<00:00, 708.61it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 860/1000 [00:01<00:00, 713.82it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 932/1000 [00:01<00:00, 707.77it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 703.87it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 722.99it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 718.24it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 718.60it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 290/1000 [00:00<00:00, 712.85it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 362/1000 [00:00<00:00, 710.81it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 434/1000 [00:00<00:00, 713.45it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 506/1000 [00:00<00:00, 713.20it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 578/1000 [00:00<00:00, 704.60it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 649/1000 [00:00<00:00, 705.86it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 720/1000 [00:01<00:00, 706.68it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 791/1000 [00:01<00:00, 706.07it/s]

Computing average_precision Permutation Test p-value:  86%|████████▋ | 863/1000 [00:01<00:00, 708.51it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▎| 935/1000 [00:01<00:00, 709.93it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 709.99it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 708.51it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 691.27it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 683.29it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 281/1000 [00:00<00:01, 671.50it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 675.49it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 419/1000 [00:00<00:00, 677.87it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 487/1000 [00:00<00:00, 675.93it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 555/1000 [00:00<00:00, 674.31it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 623/1000 [00:00<00:00, 657.15it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 691/1000 [00:01<00:00, 662.18it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 758/1000 [00:01<00:00, 660.03it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 826/1000 [00:01<00:00, 663.61it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 894/1000 [00:01<00:00, 667.68it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▋| 964/1000 [00:01<00:00, 674.65it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 672.66it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 696.26it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 678.75it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 682.75it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 693.08it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 352/1000 [00:00<00:00, 702.01it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 703.77it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 494/1000 [00:00<00:00, 699.45it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 564/1000 [00:00<00:00, 687.60it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 633/1000 [00:00<00:00, 686.60it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 704/1000 [00:01<00:00, 691.89it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 775/1000 [00:01<00:00, 695.11it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 846/1000 [00:01<00:00, 697.89it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 918/1000 [00:01<00:00, 703.00it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 990/1000 [00:01<00:00, 706.69it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 696.79it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 704.92it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 694.40it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 693.70it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 282/1000 [00:00<00:01, 694.96it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 700.15it/s]

Computing average_precision Permutation Test p-value:  42%|████▎     | 425/1000 [00:00<00:00, 701.09it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 497/1000 [00:00<00:00, 704.70it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 570/1000 [00:00<00:00, 710.92it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 642/1000 [00:00<00:00, 706.81it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 714/1000 [00:01<00:00, 708.29it/s]

Computing average_precision Permutation Test p-value:  79%|███████▊  | 786/1000 [00:01<00:00, 711.73it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 858/1000 [00:01<00:00, 704.63it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 929/1000 [00:01<00:00, 695.52it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 999/1000 [00:01<00:00, 696.16it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 701.03it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 715.83it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 712.55it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 707.77it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 287/1000 [00:00<00:01, 706.22it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 358/1000 [00:00<00:00, 700.67it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 429/1000 [00:00<00:00, 688.13it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 498/1000 [00:00<00:00, 685.60it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 567/1000 [00:00<00:00, 681.47it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 637/1000 [00:00<00:00, 685.79it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 707/1000 [00:01<00:00, 688.50it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 776/1000 [00:01<00:00, 679.67it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 844/1000 [00:01<00:00, 676.39it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 915/1000 [00:01<00:00, 683.88it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▊| 986/1000 [00:01<00:00, 688.43it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 689.98it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 717.70it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 712.25it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 699.59it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 688.11it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 355/1000 [00:00<00:00, 685.80it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 428/1000 [00:00<00:00, 699.42it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 499/1000 [00:00<00:00, 701.22it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 572/1000 [00:00<00:00, 707.24it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 643/1000 [00:00<00:00, 699.96it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 716/1000 [00:01<00:00, 706.50it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 788/1000 [00:01<00:00, 708.66it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 859/1000 [00:01<00:00, 702.02it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 930/1000 [00:01<00:00, 699.67it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 701.29it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 683.65it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 678.05it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 206/1000 [00:00<00:01, 675.72it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 274/1000 [00:00<00:01, 676.20it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 342/1000 [00:00<00:00, 667.32it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 410/1000 [00:00<00:00, 671.51it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 478/1000 [00:00<00:00, 653.47it/s]

Computing average_precision Permutation Test p-value:  55%|█████▍    | 546/1000 [00:00<00:00, 659.15it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 616/1000 [00:00<00:00, 669.95it/s]

Computing average_precision Permutation Test p-value:  69%|██████▊   | 686/1000 [00:01<00:00, 676.97it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 756/1000 [00:01<00:00, 683.17it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 826/1000 [00:01<00:00, 687.04it/s]

Computing average_precision Permutation Test p-value:  90%|████████▉ | 897/1000 [00:01<00:00, 690.82it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 967/1000 [00:01<00:00, 686.50it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 676.93it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 701.25it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 699.15it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 697.13it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 700.09it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 689.29it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 678.26it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 491/1000 [00:00<00:00, 674.54it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 561/1000 [00:00<00:00, 681.38it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 631/1000 [00:00<00:00, 687.11it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 701/1000 [00:01<00:00, 688.56it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 772/1000 [00:01<00:00, 693.23it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 842/1000 [00:01<00:00, 694.29it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 912/1000 [00:01<00:00, 692.04it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 982/1000 [00:01<00:00, 689.14it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 688.89it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 66/1000 [00:00<00:01, 651.88it/s]

Computing average_precision Permutation Test p-value:  13%|█▎        | 132/1000 [00:00<00:01, 649.96it/s]

Computing average_precision Permutation Test p-value:  20%|█▉        | 199/1000 [00:00<00:01, 658.85it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 270/1000 [00:00<00:01, 676.97it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 338/1000 [00:00<00:01, 660.10it/s]

Computing average_precision Permutation Test p-value:  40%|████      | 405/1000 [00:00<00:00, 657.07it/s]

Computing average_precision Permutation Test p-value:  47%|████▋     | 473/1000 [00:00<00:00, 662.12it/s]

Computing average_precision Permutation Test p-value:  54%|█████▍    | 543/1000 [00:00<00:00, 671.78it/s]

Computing average_precision Permutation Test p-value:  61%|██████▏   | 614/1000 [00:00<00:00, 683.03it/s]

Computing average_precision Permutation Test p-value:  68%|██████▊   | 685/1000 [00:01<00:00, 688.28it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 755/1000 [00:01<00:00, 689.14it/s]

Computing average_precision Permutation Test p-value:  82%|████████▎ | 825/1000 [00:01<00:00, 689.39it/s]

Computing average_precision Permutation Test p-value:  89%|████████▉ | 894/1000 [00:01<00:00, 689.20it/s]

Computing average_precision Permutation Test p-value:  96%|█████████▋| 963/1000 [00:01<00:00, 685.43it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 677.63it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 696.00it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 692.61it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 685.72it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 690.48it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 681.87it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 421/1000 [00:00<00:00, 689.67it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 694.27it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 563/1000 [00:00<00:00, 696.42it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 633/1000 [00:00<00:00, 694.27it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 705/1000 [00:01<00:00, 700.85it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 776/1000 [00:01<00:00, 701.68it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 847/1000 [00:01<00:00, 703.58it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 918/1000 [00:01<00:00, 697.01it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 989/1000 [00:01<00:00, 700.76it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.99it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 708.85it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 688.70it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 690.42it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 697.55it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 356/1000 [00:00<00:00, 704.72it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 428/1000 [00:00<00:00, 709.59it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 501/1000 [00:00<00:00, 713.14it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 574/1000 [00:00<00:00, 717.01it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 647/1000 [00:00<00:00, 718.90it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 719/1000 [00:01<00:00, 710.72it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 791/1000 [00:01<00:00, 710.16it/s]

Computing average_precision Permutation Test p-value:  86%|████████▋ | 863/1000 [00:01<00:00, 706.03it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 934/1000 [00:01<00:00, 701.16it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 705.63it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 695.56it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 693.95it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 694.10it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 282/1000 [00:00<00:01, 704.22it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 355/1000 [00:00<00:00, 711.95it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 427/1000 [00:00<00:00, 707.64it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 499/1000 [00:00<00:00, 708.95it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 570/1000 [00:00<00:00, 708.91it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 641/1000 [00:00<00:00, 708.18it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 712/1000 [00:01<00:00, 708.08it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 784/1000 [00:01<00:00, 710.01it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 856/1000 [00:01<00:00, 706.66it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 927/1000 [00:01<00:00, 704.67it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 998/1000 [00:01<00:00, 699.92it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 704.00it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 699.69it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 681.09it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 211/1000 [00:00<00:01, 692.04it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 281/1000 [00:00<00:01, 689.54it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 684.86it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 419/1000 [00:00<00:00, 684.72it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 490/1000 [00:00<00:00, 691.19it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 562/1000 [00:00<00:00, 698.91it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 634/1000 [00:00<00:00, 702.33it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 705/1000 [00:01<00:00, 697.93it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 777/1000 [00:01<00:00, 703.65it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 848/1000 [00:01<00:00, 698.66it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 918/1000 [00:01<00:00, 692.72it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 988/1000 [00:01<00:00, 694.32it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 693.86it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 733.73it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 697.84it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 679.07it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:01, 685.95it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 358/1000 [00:00<00:00, 688.25it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 429/1000 [00:00<00:00, 691.86it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 501/1000 [00:00<00:00, 699.55it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 572/1000 [00:00<00:00, 699.59it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 644/1000 [00:00<00:00, 703.84it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 716/1000 [00:01<00:00, 705.90it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 788/1000 [00:01<00:00, 706.71it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 859/1000 [00:01<00:00, 706.21it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 930/1000 [00:01<00:00, 704.19it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 700.50it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 713.77it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 716.11it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 217/1000 [00:00<00:01, 722.23it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 290/1000 [00:00<00:00, 716.94it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 362/1000 [00:00<00:00, 709.41it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 434/1000 [00:00<00:00, 712.60it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 506/1000 [00:00<00:00, 709.36it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 577/1000 [00:00<00:00, 704.80it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 650/1000 [00:00<00:00, 709.87it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 722/1000 [00:01<00:00, 712.74it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 794/1000 [00:01<00:00, 709.06it/s]

Computing average_precision Permutation Test p-value:  86%|████████▋ | 865/1000 [00:01<00:00, 704.90it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▎| 936/1000 [00:01<00:00, 702.37it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 708.45it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 712.87it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 716.59it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 715.03it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:00, 716.52it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 360/1000 [00:00<00:00, 713.03it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 705.60it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 503/1000 [00:00<00:00, 699.72it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 573/1000 [00:00<00:00, 697.26it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 644/1000 [00:00<00:00, 699.25it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 714/1000 [00:01<00:00, 692.88it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 784/1000 [00:01<00:00, 694.10it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 854/1000 [00:01<00:00, 689.10it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▎| 925/1000 [00:01<00:00, 693.33it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 997/1000 [00:01<00:00, 698.80it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 700.50it/s]

In [15]:
# Plot calibration curves
for dag_name in calibrations:
    plt.figure(dpi=300, layout='constrained', figsize=(8, 5))
    plt.rcParams['font.size'] = 18
    prob_true, prob_pred = calibrations[dag_name]
    plt.plot(prob_pred, prob_true, marker='o', label=f'Calibration Curve')
    plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Perfect Calibration')
    plt.xlabel('Predicted Probability')
    plt.ylabel('True Probability')
    # plt.title(f'No Drugs - {dag_name}')
    plt.xticks(np.arange(0, 1.1, 0.1))
    plt.grid()
    plt.savefig(f'biomarker_counts_fixed/Calibration Curves/No Drugs - {dag_name.replace(" ", "_").replace("$\\cap$", "AND").replace("$\\cup$", "OR")}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

In [16]:
vals = shap_values_biomarker_summary(shap_values)
auprc_top10 = pd.DataFrame(results).sort_values(by=['Average Precision'], ascending=False).head(10).DAG.unique().tolist()

plt.rcParams.update({  
'figure.figsize': (8, 10),   # Default figure size (inches)  
'figure.dpi': 300,          # Default DPI for figure creation  
'ytick.labelsize': 16,
'xtick.labelsize': 16,
'font.size': 18,
'lines.linewidth': 2,       # Default line width  
'figure.constrained_layout.use': True,
'pdf.fonttype': 42
}) 
for dag_name in auprc_top10:
    df = vals[dag_name].sort_values(ascending=True)
    plt.barh(df.index, df)
    plt.xlabel('Mean |SHAP value|')
    plt.ylabel('Biomarker')
    plt.savefig(f'biomarker_counts_fixed/Feature Importance/No Drugs - {dag_name}.pdf', bbox_inches='tight', dpi=300, transparent=False)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

## Experiment 3: No Drugs or Interventions

In [17]:
results, shap_values, calibrations, model_preds = train_models(remove_drugs=True, remove_interventions=True)

Processing Control with 46 nodes and 45 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 130/1000 [00:00<00:00, 1297.80it/s]

Bootstrapping average_precision:  26%|██▋       | 264/1000 [00:00<00:00, 1318.56it/s]

Bootstrapping average_precision:  40%|███▉      | 398/1000 [00:00<00:00, 1324.62it/s]

Bootstrapping average_precision:  53%|█████▎    | 531/1000 [00:00<00:00, 1250.98it/s]

Bootstrapping average_precision:  66%|██████▌   | 657/1000 [00:00<00:00, 1231.08it/s]

Bootstrapping average_precision:  79%|███████▉  | 794/1000 [00:00<00:00, 1275.97it/s]

Bootstrapping average_precision:  93%|█████████▎| 930/1000 [00:00<00:00, 1301.46it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1287.52it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   7%|▋         | 67/1000 [00:00<00:01, 667.72it/s]

Bootstrapping roc_auc:  14%|█▍        | 141/1000 [00:00<00:01, 707.92it/s]

Bootstrapping roc_auc:  22%|██▎       | 225/1000 [00:00<00:01, 765.28it/s]

Bootstrapping roc_auc:  31%|███       | 309/1000 [00:00<00:00, 791.61it/s]

Bootstrapping roc_auc:  40%|███▉      | 396/1000 [00:00<00:00, 818.21it/s]

Bootstrapping roc_auc:  48%|████▊     | 479/1000 [00:00<00:00, 821.98it/s]

Bootstrapping roc_auc:  56%|█████▌    | 562/1000 [00:00<00:00, 789.81it/s]

Bootstrapping roc_auc:  64%|██████▍   | 642/1000 [00:00<00:00, 777.48it/s]

Bootstrapping roc_auc:  72%|███████▏  | 722/1000 [00:00<00:00, 782.15it/s]

Bootstrapping roc_auc:  81%|████████  | 807/1000 [00:01<00:00, 799.58it/s]

Bootstrapping roc_auc:  89%|████████▉ | 894/1000 [00:01<00:00, 818.58it/s]

Bootstrapping roc_auc:  98%|█████████▊| 982/1000 [00:01<00:00, 836.09it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 801.12it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 112/1000 [00:00<00:00, 1114.26it/s]

Bootstrapping precision:  23%|██▎       | 227/1000 [00:00<00:00, 1132.98it/s]

Bootstrapping precision:  34%|███▍      | 341/1000 [00:00<00:00, 1136.04it/s]

Bootstrapping precision:  46%|████▌     | 455/1000 [00:00<00:00, 1128.09it/s]

Bootstrapping precision:  57%|█████▊    | 575/1000 [00:00<00:00, 1151.05it/s]

Bootstrapping precision:  69%|██████▉   | 692/1000 [00:00<00:00, 1155.73it/s]

Bootstrapping precision:  81%|████████  | 810/1000 [00:00<00:00, 1162.07it/s]

Bootstrapping precision:  93%|█████████▎| 927/1000 [00:00<00:00, 1152.00it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1137.71it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  10%|█         | 104/1000 [00:00<00:00, 1032.81it/s]

Bootstrapping recall:  21%|██        | 208/1000 [00:00<00:00, 1001.93it/s]

Bootstrapping recall:  32%|███▏      | 316/1000 [00:00<00:00, 1033.10it/s]

Bootstrapping recall:  43%|████▎     | 427/1000 [00:00<00:00, 1060.93it/s]

Bootstrapping recall:  54%|█████▍    | 541/1000 [00:00<00:00, 1085.77it/s]

Bootstrapping recall:  65%|██████▌   | 650/1000 [00:00<00:00, 1030.40it/s]

Bootstrapping recall:  75%|███████▌  | 754/1000 [00:00<00:00, 969.97it/s]

Bootstrapping recall:  87%|████████▋ | 867/1000 [00:00<00:00, 1017.08it/s]

Bootstrapping recall:  98%|█████████▊| 981/1000 [00:00<00:00, 1052.36it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1037.67it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1129.02it/s]

Bootstrapping f1:  23%|██▎       | 230/1000 [00:00<00:00, 1146.88it/s]

Bootstrapping f1:  35%|███▍      | 348/1000 [00:00<00:00, 1159.81it/s]

Bootstrapping f1:  47%|████▋     | 470/1000 [00:00<00:00, 1181.12it/s]

Bootstrapping f1:  59%|█████▉    | 590/1000 [00:00<00:00, 1185.68it/s]

Bootstrapping f1:  71%|███████   | 711/1000 [00:00<00:00, 1191.62it/s]

Bootstrapping f1:  83%|████████▎ | 831/1000 [00:00<00:00, 1193.54it/s]

Bootstrapping f1:  95%|█████████▌| 952/1000 [00:00<00:00, 1196.21it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1185.06it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 333/1000 [00:00<00:00, 3327.27it/s]

Bootstrapping accuracy:  67%|██████▋   | 666/1000 [00:00<00:00, 3156.71it/s]

Bootstrapping accuracy:  98%|█████████▊| 983/1000 [00:00<00:00, 3157.81it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3167.01it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  12%|█▎        | 125/1000 [00:00<00:00, 1249.15it/s]

Bootstrapping average_precision:  25%|██▌       | 250/1000 [00:00<00:00, 1214.87it/s]

Bootstrapping average_precision:  38%|███▊      | 380/1000 [00:00<00:00, 1250.34it/s]

Bootstrapping average_precision:  51%|█████     | 510/1000 [00:00<00:00, 1269.22it/s]

Bootstrapping average_precision:  64%|██████▍   | 642/1000 [00:00<00:00, 1283.95it/s]

Bootstrapping average_precision:  77%|███████▋  | 772/1000 [00:00<00:00, 1288.98it/s]

Bootstrapping average_precision:  90%|█████████ | 901/1000 [00:00<00:00, 1286.88it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1275.08it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 80/1000 [00:00<00:01, 798.81it/s]

Bootstrapping roc_auc:  16%|█▌        | 161/1000 [00:00<00:01, 800.20it/s]

Bootstrapping roc_auc:  24%|██▍       | 244/1000 [00:00<00:00, 813.04it/s]

Bootstrapping roc_auc:  33%|███▎      | 326/1000 [00:00<00:00, 806.29it/s]

Bootstrapping roc_auc:  41%|████      | 407/1000 [00:00<00:00, 807.54it/s]

Bootstrapping roc_auc:  49%|████▉     | 488/1000 [00:00<00:00, 800.41it/s]

Bootstrapping roc_auc:  57%|█████▋    | 569/1000 [00:00<00:00, 794.99it/s]

Bootstrapping roc_auc:  65%|██████▍   | 649/1000 [00:00<00:00, 794.01it/s]

Bootstrapping roc_auc:  73%|███████▎  | 729/1000 [00:00<00:00, 790.53it/s]

Bootstrapping roc_auc:  81%|████████▏ | 813/1000 [00:01<00:00, 804.55it/s]

Bootstrapping roc_auc:  90%|████████▉ | 898/1000 [00:01<00:00, 817.12it/s]

Bootstrapping roc_auc:  98%|█████████▊| 984/1000 [00:01<00:00, 827.62it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 809.55it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  10%|▉         | 97/1000 [00:00<00:00, 967.02it/s]

Bootstrapping precision:  21%|██        | 206/1000 [00:00<00:00, 1035.87it/s]

Bootstrapping precision:  32%|███▏      | 323/1000 [00:00<00:00, 1095.39it/s]

Bootstrapping precision:  44%|████▍     | 442/1000 [00:00<00:00, 1131.54it/s]

Bootstrapping precision:  56%|█████▌    | 560/1000 [00:00<00:00, 1145.90it/s]

Bootstrapping precision:  68%|██████▊   | 678/1000 [00:00<00:00, 1156.18it/s]

Bootstrapping precision:  80%|███████▉  | 796/1000 [00:00<00:00, 1162.28it/s]

Bootstrapping precision:  91%|█████████▏| 913/1000 [00:00<00:00, 1162.77it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1137.27it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1151.29it/s]

Bootstrapping recall:  23%|██▎       | 232/1000 [00:00<00:00, 1149.15it/s]

Bootstrapping recall:  35%|███▌      | 350/1000 [00:00<00:00, 1161.69it/s]

Bootstrapping recall:  47%|████▋     | 467/1000 [00:00<00:00, 1151.63it/s]

Bootstrapping recall:  58%|█████▊    | 583/1000 [00:00<00:00, 1132.66it/s]

Bootstrapping recall:  70%|██████▉   | 697/1000 [00:00<00:00, 1116.05it/s]

Bootstrapping recall:  81%|████████▏ | 813/1000 [00:00<00:00, 1127.32it/s]

Bootstrapping recall:  93%|█████████▎| 933/1000 [00:00<00:00, 1149.01it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1146.89it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1191.00it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1165.91it/s]

Bootstrapping f1:  36%|███▌      | 357/1000 [00:00<00:00, 1116.04it/s]

Bootstrapping f1:  47%|████▋     | 470/1000 [00:00<00:00, 1118.26it/s]

Bootstrapping f1:  59%|█████▊    | 586/1000 [00:00<00:00, 1131.32it/s]

Bootstrapping f1:  70%|███████   | 705/1000 [00:00<00:00, 1150.41it/s]

Bootstrapping f1:  83%|████████▎ | 826/1000 [00:00<00:00, 1169.16it/s]

Bootstrapping f1:  95%|█████████▍| 947/1000 [00:00<00:00, 1181.59it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1160.81it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3554.88it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3494.72it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3395.80it/s]

Processing Correlation with 38 nodes and 37 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1345.65it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1357.56it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1369.78it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1356.57it/s]

Bootstrapping average_precision:  69%|██████▊   | 686/1000 [00:00<00:00, 1361.74it/s]

Bootstrapping average_precision:  83%|████████▎ | 826/1000 [00:00<00:00, 1374.21it/s]

Bootstrapping average_precision:  96%|█████████▋| 965/1000 [00:00<00:00, 1378.08it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1369.64it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 877.92it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 877.92it/s]

Bootstrapping roc_auc:  26%|██▋       | 264/1000 [00:00<00:00, 878.53it/s]

Bootstrapping roc_auc:  35%|███▌      | 354/1000 [00:00<00:00, 884.60it/s]

Bootstrapping roc_auc:  44%|████▍     | 443/1000 [00:00<00:00, 877.18it/s]

Bootstrapping roc_auc:  53%|█████▎    | 532/1000 [00:00<00:00, 880.07it/s]

Bootstrapping roc_auc:  62%|██████▏   | 621/1000 [00:00<00:00, 881.98it/s]

Bootstrapping roc_auc:  71%|███████   | 710/1000 [00:00<00:00, 882.59it/s]

Bootstrapping roc_auc:  80%|███████▉  | 799/1000 [00:00<00:00, 879.20it/s]

Bootstrapping roc_auc:  89%|████████▊ | 887/1000 [00:01<00:00, 877.05it/s]

Bootstrapping roc_auc:  98%|█████████▊| 977/1000 [00:01<00:00, 880.95it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 878.90it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1128.55it/s]

Bootstrapping precision:  23%|██▎       | 233/1000 [00:00<00:00, 1164.26it/s]

Bootstrapping precision:  36%|███▌      | 355/1000 [00:00<00:00, 1188.69it/s]

Bootstrapping precision:  48%|████▊     | 478/1000 [00:00<00:00, 1202.43it/s]

Bootstrapping precision:  60%|█████▉    | 599/1000 [00:00<00:00, 1185.86it/s]

Bootstrapping precision:  72%|███████▏  | 718/1000 [00:00<00:00, 1167.62it/s]

Bootstrapping precision:  84%|████████▎ | 835/1000 [00:00<00:00, 1164.09it/s]

Bootstrapping precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1167.63it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1170.78it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 113/1000 [00:00<00:00, 1120.06it/s]

Bootstrapping recall:  23%|██▎       | 226/1000 [00:00<00:00, 1124.59it/s]

Bootstrapping recall:  34%|███▍      | 339/1000 [00:00<00:00, 1111.77it/s]

Bootstrapping recall:  45%|████▌     | 451/1000 [00:00<00:00, 1106.91it/s]

Bootstrapping recall:  56%|█████▌    | 562/1000 [00:00<00:00, 1107.88it/s]

Bootstrapping recall:  68%|██████▊   | 678/1000 [00:00<00:00, 1122.56it/s]

Bootstrapping recall:  79%|███████▉  | 792/1000 [00:00<00:00, 1126.87it/s]

Bootstrapping recall:  91%|█████████▏| 913/1000 [00:00<00:00, 1150.47it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1136.39it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1206.90it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1154.81it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1159.98it/s]

Bootstrapping f1:  48%|████▊     | 476/1000 [00:00<00:00, 1153.90it/s]

Bootstrapping f1:  59%|█████▉    | 594/1000 [00:00<00:00, 1162.82it/s]

Bootstrapping f1:  71%|███████   | 711/1000 [00:00<00:00, 1155.94it/s]

Bootstrapping f1:  83%|████████▎ | 827/1000 [00:00<00:00, 1149.67it/s]

Bootstrapping f1:  94%|█████████▍| 942/1000 [00:00<00:00, 1144.10it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1152.63it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 338/1000 [00:00<00:00, 3379.29it/s]

Bootstrapping accuracy:  68%|██████▊   | 676/1000 [00:00<00:00, 3339.25it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3369.99it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1337.64it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1337.28it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 1308.89it/s]

Bootstrapping average_precision:  53%|█████▎    | 533/1000 [00:00<00:00, 1284.96it/s]

Bootstrapping average_precision:  66%|██████▌   | 662/1000 [00:00<00:00, 1262.35it/s]

Bootstrapping average_precision:  79%|███████▉  | 792/1000 [00:00<00:00, 1272.64it/s]

Bootstrapping average_precision:  92%|█████████▎| 925/1000 [00:00<00:00, 1289.86it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1293.98it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 78/1000 [00:00<00:01, 775.72it/s]

Bootstrapping roc_auc:  16%|█▌        | 156/1000 [00:00<00:01, 724.41it/s]

Bootstrapping roc_auc:  23%|██▎       | 229/1000 [00:00<00:01, 723.60it/s]

Bootstrapping roc_auc:  31%|███       | 306/1000 [00:00<00:00, 740.14it/s]

Bootstrapping roc_auc:  38%|███▊      | 381/1000 [00:00<00:00, 742.19it/s]

Bootstrapping roc_auc:  46%|████▌     | 458/1000 [00:00<00:00, 750.66it/s]

Bootstrapping roc_auc:  54%|█████▎    | 537/1000 [00:00<00:00, 762.60it/s]

Bootstrapping roc_auc:  62%|██████▏   | 619/1000 [00:00<00:00, 780.06it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 795.76it/s]

Bootstrapping roc_auc:  79%|███████▊  | 787/1000 [00:01<00:00, 808.30it/s]

Bootstrapping roc_auc:  87%|████████▋ | 873/1000 [00:01<00:00, 822.10it/s]

Bootstrapping roc_auc:  96%|█████████▌| 960/1000 [00:01<00:00, 834.90it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 789.68it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1190.94it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1193.43it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1199.69it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1156.46it/s]

Bootstrapping precision:  60%|█████▉    | 597/1000 [00:00<00:00, 1137.89it/s]

Bootstrapping precision:  71%|███████   | 711/1000 [00:00<00:00, 1128.67it/s]

Bootstrapping precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1123.25it/s]

Bootstrapping precision:  94%|█████████▎| 937/1000 [00:00<00:00, 1119.70it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1140.85it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1179.01it/s]

Bootstrapping recall:  24%|██▎       | 237/1000 [00:00<00:00, 1183.02it/s]

Bootstrapping recall:  36%|███▌      | 356/1000 [00:00<00:00, 1111.96it/s]

Bootstrapping recall:  47%|████▋     | 468/1000 [00:00<00:00, 1108.23it/s]

Bootstrapping recall:  58%|█████▊    | 585/1000 [00:00<00:00, 1129.49it/s]

Bootstrapping recall:  71%|███████   | 706/1000 [00:00<00:00, 1154.09it/s]

Bootstrapping recall:  82%|████████▏ | 822/1000 [00:00<00:00, 1133.43it/s]

Bootstrapping recall:  94%|█████████▍| 940/1000 [00:00<00:00, 1147.50it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1141.18it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 119/1000 [00:00<00:00, 1188.93it/s]

Bootstrapping f1:  24%|██▍       | 239/1000 [00:00<00:00, 1193.83it/s]

Bootstrapping f1:  36%|███▌      | 359/1000 [00:00<00:00, 1161.75it/s]

Bootstrapping f1:  48%|████▊     | 476/1000 [00:00<00:00, 1124.59it/s]

Bootstrapping f1:  59%|█████▉    | 589/1000 [00:00<00:00, 1110.55it/s]

Bootstrapping f1:  70%|███████   | 701/1000 [00:00<00:00, 1106.25it/s]

Bootstrapping f1:  81%|████████  | 812/1000 [00:00<00:00, 1104.73it/s]

Bootstrapping f1:  92%|█████████▏| 924/1000 [00:00<00:00, 1106.94it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1117.55it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  32%|███▏      | 316/1000 [00:00<00:00, 3157.56it/s]

Bootstrapping accuracy:  63%|██████▎   | 632/1000 [00:00<00:00, 3121.73it/s]

Bootstrapping accuracy:  94%|█████████▍| 945/1000 [00:00<00:00, 3114.49it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3115.00it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified PCMB with 20 nodes and 53 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 142/1000 [00:00<00:00, 1417.92it/s]

Bootstrapping average_precision:  28%|██▊       | 284/1000 [00:00<00:00, 1416.37it/s]

Bootstrapping average_precision:  43%|████▎     | 427/1000 [00:00<00:00, 1421.57it/s]

Bootstrapping average_precision:  57%|█████▋    | 570/1000 [00:00<00:00, 1417.01it/s]

Bootstrapping average_precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1417.77it/s]

Bootstrapping average_precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1415.63it/s]

Bootstrapping average_precision: 100%|█████████▉| 998/1000 [00:00<00:00, 1419.91it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1417.12it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 89/1000 [00:00<00:01, 883.76it/s]

Bootstrapping roc_auc:  18%|█▊        | 178/1000 [00:00<00:00, 885.29it/s]

Bootstrapping roc_auc:  27%|██▋       | 269/1000 [00:00<00:00, 893.53it/s]

Bootstrapping roc_auc:  36%|███▌      | 359/1000 [00:00<00:00, 861.55it/s]

Bootstrapping roc_auc:  45%|████▍     | 446/1000 [00:00<00:00, 836.98it/s]

Bootstrapping roc_auc:  53%|█████▎    | 533/1000 [00:00<00:00, 845.25it/s]

Bootstrapping roc_auc:  62%|██████▏   | 618/1000 [00:00<00:00, 846.27it/s]

Bootstrapping roc_auc:  70%|███████   | 703/1000 [00:00<00:00, 845.69it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 850.57it/s]

Bootstrapping roc_auc:  88%|████████▊ | 879/1000 [00:01<00:00, 859.82it/s]

Bootstrapping roc_auc:  97%|█████████▋| 968/1000 [00:01<00:00, 867.73it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 860.01it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 124/1000 [00:00<00:00, 1231.56it/s]

Bootstrapping precision:  25%|██▍       | 248/1000 [00:00<00:00, 1224.65it/s]

Bootstrapping precision:  37%|███▋      | 371/1000 [00:00<00:00, 1220.58it/s]

Bootstrapping precision:  49%|████▉     | 494/1000 [00:00<00:00, 1210.46it/s]

Bootstrapping precision:  62%|██████▏   | 617/1000 [00:00<00:00, 1216.71it/s]

Bootstrapping precision:  74%|███████▍  | 739/1000 [00:00<00:00, 1217.49it/s]

Bootstrapping precision:  86%|████████▌ | 861/1000 [00:00<00:00, 1217.79it/s]

Bootstrapping precision:  98%|█████████▊| 984/1000 [00:00<00:00, 1220.75it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1218.41it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1212.50it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1213.24it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1215.76it/s]

Bootstrapping recall:  49%|████▉     | 489/1000 [00:00<00:00, 1219.76it/s]

Bootstrapping recall:  61%|██████    | 611/1000 [00:00<00:00, 1213.72it/s]

Bootstrapping recall:  73%|███████▎  | 733/1000 [00:00<00:00, 1205.19it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1193.64it/s]

Bootstrapping recall:  98%|█████████▊| 975/1000 [00:00<00:00, 1197.82it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1203.97it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1178.78it/s]

Bootstrapping f1:  24%|██▎       | 237/1000 [00:00<00:00, 1181.08it/s]

Bootstrapping f1:  36%|███▌      | 357/1000 [00:00<00:00, 1186.65it/s]

Bootstrapping f1:  48%|████▊     | 478/1000 [00:00<00:00, 1192.77it/s]

Bootstrapping f1:  60%|█████▉    | 598/1000 [00:00<00:00, 1194.02it/s]

Bootstrapping f1:  72%|███████▏  | 718/1000 [00:00<00:00, 1180.25it/s]

Bootstrapping f1:  84%|████████▎ | 837/1000 [00:00<00:00, 1182.67it/s]

Bootstrapping f1:  96%|█████████▌| 956/1000 [00:00<00:00, 1167.43it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1174.51it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 351/1000 [00:00<00:00, 3508.92it/s]

Bootstrapping accuracy:  70%|███████   | 702/1000 [00:00<00:00, 3432.51it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3441.23it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 132/1000 [00:00<00:00, 1310.51it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1336.29it/s]

Bootstrapping average_precision:  40%|████      | 402/1000 [00:00<00:00, 1334.50it/s]

Bootstrapping average_precision:  54%|█████▎    | 537/1000 [00:00<00:00, 1338.77it/s]

Bootstrapping average_precision:  67%|██████▋   | 673/1000 [00:00<00:00, 1343.81it/s]

Bootstrapping average_precision:  81%|████████  | 809/1000 [00:00<00:00, 1347.18it/s]

Bootstrapping average_precision:  94%|█████████▍| 944/1000 [00:00<00:00, 1345.42it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1340.49it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 855.30it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 841.34it/s]

Bootstrapping roc_auc:  26%|██▌       | 257/1000 [00:00<00:00, 820.22it/s]

Bootstrapping roc_auc:  34%|███▍      | 340/1000 [00:00<00:00, 803.90it/s]

Bootstrapping roc_auc:  42%|████▏     | 422/1000 [00:00<00:00, 807.05it/s]

Bootstrapping roc_auc:  50%|█████     | 503/1000 [00:00<00:00, 802.82it/s]

Bootstrapping roc_auc:  58%|█████▊    | 584/1000 [00:00<00:00, 793.36it/s]

Bootstrapping roc_auc:  66%|██████▋   | 664/1000 [00:00<00:00, 792.11it/s]

Bootstrapping roc_auc:  75%|███████▌  | 750/1000 [00:00<00:00, 810.28it/s]

Bootstrapping roc_auc:  84%|████████▎ | 837/1000 [00:01<00:00, 826.30it/s]

Bootstrapping roc_auc:  92%|█████████▏| 920/1000 [00:01<00:00, 827.04it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 815.83it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 110/1000 [00:00<00:00, 1099.30it/s]

Bootstrapping precision:  22%|██▏       | 222/1000 [00:00<00:00, 1109.10it/s]

Bootstrapping precision:  34%|███▎      | 336/1000 [00:00<00:00, 1120.49it/s]

Bootstrapping precision:  45%|████▍     | 449/1000 [00:00<00:00, 1118.50it/s]

Bootstrapping precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1125.43it/s]

Bootstrapping precision:  68%|██████▊   | 676/1000 [00:00<00:00, 1123.34it/s]

Bootstrapping precision:  79%|███████▉  | 789/1000 [00:00<00:00, 1120.82it/s]

Bootstrapping precision:  90%|█████████ | 902/1000 [00:00<00:00, 1112.10it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1119.49it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 118/1000 [00:00<00:00, 1170.18it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1156.04it/s]

Bootstrapping recall:  35%|███▌      | 352/1000 [00:00<00:00, 1150.84it/s]

Bootstrapping recall:  47%|████▋     | 471/1000 [00:00<00:00, 1162.09it/s]

Bootstrapping recall:  59%|█████▉    | 588/1000 [00:00<00:00, 1154.37it/s]

Bootstrapping recall:  70%|███████   | 704/1000 [00:00<00:00, 1144.46it/s]

Bootstrapping recall:  82%|████████▏ | 821/1000 [00:00<00:00, 1151.17it/s]

Bootstrapping recall:  94%|█████████▎| 937/1000 [00:00<00:00, 1150.11it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1153.28it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1155.96it/s]

Bootstrapping f1:  23%|██▎       | 232/1000 [00:00<00:00, 1157.37it/s]

Bootstrapping f1:  35%|███▌      | 350/1000 [00:00<00:00, 1163.90it/s]

Bootstrapping f1:  47%|████▋     | 467/1000 [00:00<00:00, 1155.86it/s]

Bootstrapping f1:  58%|█████▊    | 583/1000 [00:00<00:00, 1156.58it/s]

Bootstrapping f1:  70%|███████   | 702/1000 [00:00<00:00, 1165.67it/s]

Bootstrapping f1:  82%|████████▏ | 819/1000 [00:00<00:00, 1155.58it/s]

Bootstrapping f1:  94%|█████████▎| 935/1000 [00:00<00:00, 1151.29it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1154.65it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 342/1000 [00:00<00:00, 3415.77it/s]

Bootstrapping accuracy:  69%|██████▉   | 693/1000 [00:00<00:00, 3467.26it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3482.73it/s]

Processing Simplified Clinician Consensus $\cup$ Simplified Golem with 24 nodes and 35 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1328.05it/s]

Bootstrapping average_precision:  27%|██▋       | 269/1000 [00:00<00:00, 1345.18it/s]

Bootstrapping average_precision:  40%|████      | 404/1000 [00:00<00:00, 1346.65it/s]

Bootstrapping average_precision:  55%|█████▍    | 546/1000 [00:00<00:00, 1371.67it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1376.01it/s]

Bootstrapping average_precision:  82%|████████▏ | 824/1000 [00:00<00:00, 1379.81it/s]

Bootstrapping average_precision:  96%|█████████▋| 965/1000 [00:00<00:00, 1389.40it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1373.72it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 875.93it/s]

Bootstrapping roc_auc:  18%|█▊        | 177/1000 [00:00<00:00, 882.88it/s]

Bootstrapping roc_auc:  27%|██▋       | 267/1000 [00:00<00:00, 887.92it/s]

Bootstrapping roc_auc:  36%|███▌      | 356/1000 [00:00<00:00, 888.42it/s]

Bootstrapping roc_auc:  44%|████▍     | 445/1000 [00:00<00:00, 884.70it/s]

Bootstrapping roc_auc:  53%|█████▎    | 534/1000 [00:00<00:00, 885.95it/s]

Bootstrapping roc_auc:  62%|██████▏   | 623/1000 [00:00<00:00, 877.70it/s]

Bootstrapping roc_auc:  71%|███████   | 711/1000 [00:00<00:00, 868.77it/s]

Bootstrapping roc_auc:  80%|███████▉  | 798/1000 [00:00<00:00, 868.60it/s]

Bootstrapping roc_auc:  89%|████████▊ | 887/1000 [00:01<00:00, 874.24it/s]

Bootstrapping roc_auc:  98%|█████████▊| 977/1000 [00:01<00:00, 881.10it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 879.00it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 122/1000 [00:00<00:00, 1211.74it/s]

Bootstrapping precision:  24%|██▍       | 244/1000 [00:00<00:00, 1206.98it/s]

Bootstrapping precision:  37%|███▋      | 366/1000 [00:00<00:00, 1211.89it/s]

Bootstrapping precision:  49%|████▉     | 488/1000 [00:00<00:00, 1196.17it/s]

Bootstrapping precision:  61%|██████    | 609/1000 [00:00<00:00, 1197.58it/s]

Bootstrapping precision:  73%|███████▎  | 731/1000 [00:00<00:00, 1202.69it/s]

Bootstrapping precision:  85%|████████▌ | 852/1000 [00:00<00:00, 1204.34it/s]

Bootstrapping precision:  97%|█████████▋| 974/1000 [00:00<00:00, 1206.58it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1202.01it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1203.42it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1204.11it/s]

Bootstrapping recall:  36%|███▋      | 363/1000 [00:00<00:00, 1203.93it/s]

Bootstrapping recall:  48%|████▊     | 484/1000 [00:00<00:00, 1197.90it/s]

Bootstrapping recall:  60%|██████    | 604/1000 [00:00<00:00, 1196.53it/s]

Bootstrapping recall:  72%|███████▎  | 725/1000 [00:00<00:00, 1198.00it/s]

Bootstrapping recall:  85%|████████▍ | 847/1000 [00:00<00:00, 1205.07it/s]

Bootstrapping recall:  97%|█████████▋| 968/1000 [00:00<00:00, 1206.56it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1202.84it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1202.13it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1201.66it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1196.12it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1196.05it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1200.33it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1198.42it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1200.38it/s]

Bootstrapping f1:  97%|█████████▋| 967/1000 [00:00<00:00, 1202.04it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1198.65it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3538.45it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3509.62it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3512.81it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 134/1000 [00:00<00:00, 1337.28it/s]

Bootstrapping average_precision:  27%|██▋       | 268/1000 [00:00<00:00, 1327.24it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 1318.52it/s]

Bootstrapping average_precision:  54%|█████▎    | 535/1000 [00:00<00:00, 1325.02it/s]

Bootstrapping average_precision:  67%|██████▋   | 672/1000 [00:00<00:00, 1339.84it/s]

Bootstrapping average_precision:  81%|████████  | 808/1000 [00:00<00:00, 1344.15it/s]

Bootstrapping average_precision:  94%|█████████▍| 943/1000 [00:00<00:00, 1341.18it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1335.60it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 857.44it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 834.45it/s]

Bootstrapping roc_auc:  26%|██▌       | 256/1000 [00:00<00:00, 801.40it/s]

Bootstrapping roc_auc:  34%|███▎      | 337/1000 [00:00<00:00, 790.53it/s]

Bootstrapping roc_auc:  42%|████▏     | 417/1000 [00:00<00:00, 778.78it/s]

Bootstrapping roc_auc:  50%|████▉     | 499/1000 [00:00<00:00, 789.29it/s]

Bootstrapping roc_auc:  58%|█████▊    | 583/1000 [00:00<00:00, 804.18it/s]

Bootstrapping roc_auc:  67%|██████▋   | 667/1000 [00:00<00:00, 813.99it/s]

Bootstrapping roc_auc:  75%|███████▌  | 752/1000 [00:00<00:00, 822.77it/s]

Bootstrapping roc_auc:  84%|████████▍ | 839/1000 [00:01<00:00, 835.08it/s]

Bootstrapping roc_auc:  92%|█████████▏| 923/1000 [00:01<00:00, 830.66it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 818.66it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1194.60it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1164.74it/s]

Bootstrapping precision:  36%|███▌      | 357/1000 [00:00<00:00, 1155.56it/s]

Bootstrapping precision:  47%|████▋     | 473/1000 [00:00<00:00, 1143.59it/s]

Bootstrapping precision:  59%|█████▉    | 589/1000 [00:00<00:00, 1146.80it/s]

Bootstrapping precision:  70%|███████   | 704/1000 [00:00<00:00, 1137.67it/s]

Bootstrapping precision:  82%|████████▏ | 822/1000 [00:00<00:00, 1150.92it/s]

Bootstrapping precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1138.55it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1144.42it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 109/1000 [00:00<00:00, 1081.89it/s]

Bootstrapping recall:  22%|██▏       | 218/1000 [00:00<00:00, 1075.37it/s]

Bootstrapping recall:  33%|███▎      | 331/1000 [00:00<00:00, 1097.58it/s]

Bootstrapping recall:  44%|████▍     | 445/1000 [00:00<00:00, 1111.64it/s]

Bootstrapping recall:  56%|█████▋    | 563/1000 [00:00<00:00, 1134.04it/s]

Bootstrapping recall:  68%|██████▊   | 677/1000 [00:00<00:00, 1125.76it/s]

Bootstrapping recall:  80%|███████▉  | 795/1000 [00:00<00:00, 1141.43it/s]

Bootstrapping recall:  91%|█████████ | 912/1000 [00:00<00:00, 1150.39it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1130.68it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1124.54it/s]

Bootstrapping f1:  23%|██▎       | 228/1000 [00:00<00:00, 1134.93it/s]

Bootstrapping f1:  35%|███▍      | 346/1000 [00:00<00:00, 1153.50it/s]

Bootstrapping f1:  46%|████▌     | 462/1000 [00:00<00:00, 1154.38it/s]

Bootstrapping f1:  58%|█████▊    | 582/1000 [00:00<00:00, 1167.70it/s]

Bootstrapping f1:  70%|███████   | 701/1000 [00:00<00:00, 1174.28it/s]

Bootstrapping f1:  82%|████████▏ | 822/1000 [00:00<00:00, 1184.94it/s]

Bootstrapping f1:  94%|█████████▍| 941/1000 [00:00<00:00, 1158.44it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1158.77it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 337/1000 [00:00<00:00, 3360.69it/s]

Bootstrapping accuracy:  67%|██████▋   | 674/1000 [00:00<00:00, 3365.83it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3390.20it/s]

Processing Simplified Golem $\cup$ Simplified PCMB with 24 nodes and 64 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 133/1000 [00:00<00:00, 1327.61it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1347.16it/s]

Bootstrapping average_precision:  41%|████      | 408/1000 [00:00<00:00, 1359.89it/s]

Bootstrapping average_precision:  55%|█████▍    | 546/1000 [00:00<00:00, 1365.45it/s]

Bootstrapping average_precision:  68%|██████▊   | 685/1000 [00:00<00:00, 1372.58it/s]

Bootstrapping average_precision:  82%|████████▏ | 823/1000 [00:00<00:00, 1368.45it/s]

Bootstrapping average_precision:  96%|█████████▌| 960/1000 [00:00<00:00, 1167.73it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1250.50it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   6%|▋         | 65/1000 [00:00<00:01, 643.14it/s]

Bootstrapping roc_auc:  15%|█▍        | 146/1000 [00:00<00:01, 734.48it/s]

Bootstrapping roc_auc:  23%|██▎       | 228/1000 [00:00<00:01, 771.79it/s]

Bootstrapping roc_auc:  31%|███       | 308/1000 [00:00<00:00, 780.52it/s]

Bootstrapping roc_auc:  39%|███▉      | 391/1000 [00:00<00:00, 795.06it/s]

Bootstrapping roc_auc:  48%|████▊     | 475/1000 [00:00<00:00, 808.61it/s]

Bootstrapping roc_auc:  56%|█████▌    | 562/1000 [00:00<00:00, 828.11it/s]

Bootstrapping roc_auc:  65%|██████▌   | 651/1000 [00:00<00:00, 845.03it/s]

Bootstrapping roc_auc:  74%|███████▍  | 740/1000 [00:00<00:00, 858.37it/s]

Bootstrapping roc_auc:  83%|████████▎ | 826/1000 [00:01<00:00, 847.83it/s]

Bootstrapping roc_auc:  91%|█████████ | 911/1000 [00:01<00:00, 844.38it/s]

Bootstrapping roc_auc: 100%|█████████▉| 996/1000 [00:01<00:00, 831.76it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 816.29it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1137.55it/s]

Bootstrapping precision:  23%|██▎       | 232/1000 [00:00<00:00, 1159.44it/s]

Bootstrapping precision:  35%|███▌      | 350/1000 [00:00<00:00, 1168.46it/s]

Bootstrapping precision:  47%|████▋     | 471/1000 [00:00<00:00, 1183.21it/s]

Bootstrapping precision:  59%|█████▉    | 592/1000 [00:00<00:00, 1191.44it/s]

Bootstrapping precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1195.70it/s]

Bootstrapping precision:  83%|████████▎ | 834/1000 [00:00<00:00, 1198.54it/s]

Bootstrapping precision:  95%|█████████▌| 954/1000 [00:00<00:00, 1198.50it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1187.58it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 120/1000 [00:00<00:00, 1191.23it/s]

Bootstrapping recall:  24%|██▍       | 241/1000 [00:00<00:00, 1199.30it/s]

Bootstrapping recall:  36%|███▌      | 362/1000 [00:00<00:00, 1203.37it/s]

Bootstrapping recall:  48%|████▊     | 483/1000 [00:00<00:00, 1167.02it/s]

Bootstrapping recall:  60%|██████    | 600/1000 [00:00<00:00, 1152.07it/s]

Bootstrapping recall:  72%|███████▏  | 716/1000 [00:00<00:00, 1142.11it/s]

Bootstrapping recall:  83%|████████▎ | 831/1000 [00:00<00:00, 1141.89it/s]

Bootstrapping recall:  95%|█████████▍| 946/1000 [00:00<00:00, 1135.53it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1151.73it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 110/1000 [00:00<00:00, 1099.53it/s]

Bootstrapping f1:  22%|██▏       | 221/1000 [00:00<00:00, 1103.34it/s]

Bootstrapping f1:  33%|███▎      | 334/1000 [00:00<00:00, 1113.31it/s]

Bootstrapping f1:  45%|████▍     | 447/1000 [00:00<00:00, 1119.37it/s]

Bootstrapping f1:  56%|█████▌    | 561/1000 [00:00<00:00, 1123.74it/s]

Bootstrapping f1:  67%|██████▋   | 674/1000 [00:00<00:00, 1113.23it/s]

Bootstrapping f1:  79%|███████▉  | 790/1000 [00:00<00:00, 1128.28it/s]

Bootstrapping f1:  91%|█████████ | 910/1000 [00:00<00:00, 1148.91it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1135.48it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▍      | 349/1000 [00:00<00:00, 3483.14it/s]

Bootstrapping accuracy:  70%|███████   | 700/1000 [00:00<00:00, 3495.76it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3485.12it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:   9%|▉         | 94/1000 [00:00<00:00, 936.45it/s]

Bootstrapping average_precision:  22%|██▏       | 222/1000 [00:00<00:00, 1132.90it/s]

Bootstrapping average_precision:  35%|███▍      | 348/1000 [00:00<00:00, 1189.75it/s]

Bootstrapping average_precision:  48%|████▊     | 481/1000 [00:00<00:00, 1243.86it/s]

Bootstrapping average_precision:  62%|██████▏   | 616/1000 [00:00<00:00, 1280.63it/s]

Bootstrapping average_precision:  75%|███████▌  | 752/1000 [00:00<00:00, 1304.93it/s]

Bootstrapping average_precision:  89%|████████▊ | 887/1000 [00:00<00:00, 1318.10it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1268.17it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 852.73it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 861.82it/s]

Bootstrapping roc_auc:  26%|██▌       | 260/1000 [00:00<00:00, 854.47it/s]

Bootstrapping roc_auc:  35%|███▍      | 346/1000 [00:00<00:00, 845.77it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 840.63it/s]

Bootstrapping roc_auc:  52%|█████▏    | 518/1000 [00:00<00:00, 847.50it/s]

Bootstrapping roc_auc:  60%|██████    | 605/1000 [00:00<00:00, 853.01it/s]

Bootstrapping roc_auc:  69%|██████▉   | 691/1000 [00:00<00:00, 852.24it/s]

Bootstrapping roc_auc:  78%|███████▊  | 777/1000 [00:00<00:00, 849.86it/s]

Bootstrapping roc_auc:  86%|████████▋ | 863/1000 [00:01<00:00, 850.69it/s]

Bootstrapping roc_auc:  95%|█████████▍| 949/1000 [00:01<00:00, 852.39it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 849.72it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1200.93it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1194.87it/s]

Bootstrapping precision:  36%|███▌      | 362/1000 [00:00<00:00, 1178.79it/s]

Bootstrapping precision:  48%|████▊     | 483/1000 [00:00<00:00, 1188.60it/s]

Bootstrapping precision:  60%|██████    | 605/1000 [00:00<00:00, 1198.36it/s]

Bootstrapping precision:  73%|███████▎  | 727/1000 [00:00<00:00, 1204.75it/s]

Bootstrapping precision:  85%|████████▍ | 849/1000 [00:00<00:00, 1207.82it/s]

Bootstrapping precision:  97%|█████████▋| 970/1000 [00:00<00:00, 1202.43it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.27it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 123/1000 [00:00<00:00, 1225.39it/s]

Bootstrapping recall:  25%|██▍       | 246/1000 [00:00<00:00, 1220.00it/s]

Bootstrapping recall:  37%|███▋      | 369/1000 [00:00<00:00, 1193.70it/s]

Bootstrapping recall:  49%|████▉     | 489/1000 [00:00<00:00, 1189.82it/s]

Bootstrapping recall:  61%|██████    | 609/1000 [00:00<00:00, 1187.10it/s]

Bootstrapping recall:  73%|███████▎  | 729/1000 [00:00<00:00, 1189.99it/s]

Bootstrapping recall:  85%|████████▌ | 852/1000 [00:00<00:00, 1201.16it/s]

Bootstrapping recall:  97%|█████████▋| 974/1000 [00:00<00:00, 1205.76it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1200.02it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 120/1000 [00:00<00:00, 1192.92it/s]

Bootstrapping f1:  24%|██▍       | 240/1000 [00:00<00:00, 1192.77it/s]

Bootstrapping f1:  36%|███▌      | 361/1000 [00:00<00:00, 1199.40it/s]

Bootstrapping f1:  48%|████▊     | 482/1000 [00:00<00:00, 1202.77it/s]

Bootstrapping f1:  60%|██████    | 604/1000 [00:00<00:00, 1205.64it/s]

Bootstrapping f1:  72%|███████▎  | 725/1000 [00:00<00:00, 1201.32it/s]

Bootstrapping f1:  85%|████████▍ | 846/1000 [00:00<00:00, 1195.20it/s]

Bootstrapping f1:  97%|█████████▋| 966/1000 [00:00<00:00, 1193.53it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1195.48it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3539.72it/s]

Bootstrapping accuracy:  71%|███████   | 709/1000 [00:00<00:00, 3543.57it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3535.98it/s]

Processing Simplified Clinician Consensus with 17 nodes and 17 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 139/1000 [00:00<00:00, 1384.78it/s]

Bootstrapping average_precision:  28%|██▊       | 282/1000 [00:00<00:00, 1407.05it/s]

Bootstrapping average_precision:  42%|████▏     | 423/1000 [00:00<00:00, 1377.92it/s]

Bootstrapping average_precision:  56%|█████▌    | 562/1000 [00:00<00:00, 1379.48it/s]

Bootstrapping average_precision:  70%|███████   | 700/1000 [00:00<00:00, 1372.83it/s]

Bootstrapping average_precision:  84%|████████▍ | 840/1000 [00:00<00:00, 1381.58it/s]

Bootstrapping average_precision:  98%|█████████▊| 981/1000 [00:00<00:00, 1387.99it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1383.68it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 879.07it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 879.10it/s]

Bootstrapping roc_auc:  26%|██▋       | 265/1000 [00:00<00:00, 883.65it/s]

Bootstrapping roc_auc:  35%|███▌      | 354/1000 [00:00<00:00, 884.89it/s]

Bootstrapping roc_auc:  44%|████▍     | 444/1000 [00:00<00:00, 887.01it/s]

Bootstrapping roc_auc:  53%|█████▎    | 533/1000 [00:00<00:00, 882.14it/s]

Bootstrapping roc_auc:  62%|██████▏   | 622/1000 [00:00<00:00, 873.27it/s]

Bootstrapping roc_auc:  71%|███████   | 710/1000 [00:00<00:00, 872.23it/s]

Bootstrapping roc_auc:  80%|███████▉  | 798/1000 [00:00<00:00, 862.06it/s]

Bootstrapping roc_auc:  88%|████████▊ | 885/1000 [00:01<00:00, 849.23it/s]

Bootstrapping roc_auc:  97%|█████████▋| 970/1000 [00:01<00:00, 844.28it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 863.07it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1144.63it/s]

Bootstrapping precision:  24%|██▎       | 235/1000 [00:00<00:00, 1174.05it/s]

Bootstrapping precision:  36%|███▌      | 356/1000 [00:00<00:00, 1187.83it/s]

Bootstrapping precision:  48%|████▊     | 478/1000 [00:00<00:00, 1199.48it/s]

Bootstrapping precision:  60%|█████▉    | 599/1000 [00:00<00:00, 1200.96it/s]

Bootstrapping precision:  72%|███████▏  | 720/1000 [00:00<00:00, 1179.99it/s]

Bootstrapping precision:  84%|████████▍ | 839/1000 [00:00<00:00, 1162.58it/s]

Bootstrapping precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1155.34it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1168.38it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 113/1000 [00:00<00:00, 1124.03it/s]

Bootstrapping recall:  23%|██▎       | 231/1000 [00:00<00:00, 1156.28it/s]

Bootstrapping recall:  35%|███▍      | 349/1000 [00:00<00:00, 1163.21it/s]

Bootstrapping recall:  47%|████▋     | 468/1000 [00:00<00:00, 1170.73it/s]

Bootstrapping recall:  59%|█████▊    | 586/1000 [00:00<00:00, 1160.57it/s]

Bootstrapping recall:  70%|███████   | 703/1000 [00:00<00:00, 1139.84it/s]

Bootstrapping recall:  82%|████████▏ | 818/1000 [00:00<00:00, 1137.24it/s]

Bootstrapping recall:  93%|█████████▎| 932/1000 [00:00<00:00, 1125.41it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1142.43it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 112/1000 [00:00<00:00, 1116.80it/s]

Bootstrapping f1:  22%|██▏       | 224/1000 [00:00<00:00, 1112.62it/s]

Bootstrapping f1:  34%|███▎      | 337/1000 [00:00<00:00, 1115.55it/s]

Bootstrapping f1:  45%|████▌     | 454/1000 [00:00<00:00, 1135.74it/s]

Bootstrapping f1:  57%|█████▊    | 575/1000 [00:00<00:00, 1159.28it/s]

Bootstrapping f1:  69%|██████▉   | 693/1000 [00:00<00:00, 1166.09it/s]

Bootstrapping f1:  81%|████████▏ | 814/1000 [00:00<00:00, 1178.97it/s]

Bootstrapping f1:  93%|█████████▎| 933/1000 [00:00<00:00, 1180.88it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1162.37it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3533.18it/s]

Bootstrapping accuracy:  71%|███████   | 709/1000 [00:00<00:00, 3542.82it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3541.34it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1361.11it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1360.50it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1355.04it/s]

Bootstrapping average_precision:  55%|█████▍    | 547/1000 [00:00<00:00, 1325.82it/s]

Bootstrapping average_precision:  68%|██████▊   | 683/1000 [00:00<00:00, 1335.09it/s]

Bootstrapping average_precision:  82%|████████▏ | 817/1000 [00:00<00:00, 1313.60it/s]

Bootstrapping average_precision:  95%|█████████▍| 949/1000 [00:00<00:00, 1311.09it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1324.36it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 84/1000 [00:00<00:01, 834.05it/s]

Bootstrapping roc_auc:  17%|█▋        | 168/1000 [00:00<00:01, 821.61it/s]

Bootstrapping roc_auc:  25%|██▌       | 251/1000 [00:00<00:00, 797.81it/s]

Bootstrapping roc_auc:  33%|███▎      | 331/1000 [00:00<00:00, 728.70it/s]

Bootstrapping roc_auc:  42%|████▏     | 416/1000 [00:00<00:00, 769.05it/s]

Bootstrapping roc_auc:  50%|█████     | 501/1000 [00:00<00:00, 792.54it/s]

Bootstrapping roc_auc:  58%|█████▊    | 583/1000 [00:00<00:00, 800.40it/s]

Bootstrapping roc_auc:  67%|██████▋   | 666/1000 [00:00<00:00, 806.90it/s]

Bootstrapping roc_auc:  75%|███████▌  | 751/1000 [00:00<00:00, 819.38it/s]

Bootstrapping roc_auc:  84%|████████▎ | 836/1000 [00:01<00:00, 828.47it/s]

Bootstrapping roc_auc:  92%|█████████▏| 920/1000 [00:01<00:00, 825.11it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 794.65it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:   8%|▊         | 76/1000 [00:00<00:01, 735.01it/s]

Bootstrapping precision:  18%|█▊        | 180/1000 [00:00<00:00, 909.71it/s]

Bootstrapping precision:  30%|██▉       | 296/1000 [00:00<00:00, 1021.17it/s]

Bootstrapping precision:  41%|████      | 412/1000 [00:00<00:00, 1074.40it/s]

Bootstrapping precision:  52%|█████▏    | 522/1000 [00:00<00:00, 1082.78it/s]

Bootstrapping precision:  63%|██████▎   | 631/1000 [00:00<00:00, 1065.73it/s]

Bootstrapping precision:  74%|███████▍  | 743/1000 [00:00<00:00, 1083.02it/s]

Bootstrapping precision:  86%|████████▌ | 858/1000 [00:00<00:00, 1103.67it/s]

Bootstrapping precision:  97%|█████████▋| 971/1000 [00:00<00:00, 1110.10it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1066.58it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█         | 108/1000 [00:00<00:00, 1067.15it/s]

Bootstrapping recall:  22%|██▏       | 216/1000 [00:00<00:00, 1071.54it/s]

Bootstrapping recall:  33%|███▎      | 329/1000 [00:00<00:00, 1095.39it/s]

Bootstrapping recall:  44%|████▍     | 444/1000 [00:00<00:00, 1114.52it/s]

Bootstrapping recall:  56%|█████▌    | 560/1000 [00:00<00:00, 1128.88it/s]

Bootstrapping recall:  68%|██████▊   | 678/1000 [00:00<00:00, 1144.77it/s]

Bootstrapping recall:  80%|███████▉  | 796/1000 [00:00<00:00, 1155.78it/s]

Bootstrapping recall:  91%|█████████ | 912/1000 [00:00<00:00, 1130.67it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1110.48it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1121.21it/s]

Bootstrapping f1:  23%|██▎       | 226/1000 [00:00<00:00, 1116.30it/s]

Bootstrapping f1:  34%|███▍      | 341/1000 [00:00<00:00, 1129.13it/s]

Bootstrapping f1:  46%|████▌     | 459/1000 [00:00<00:00, 1148.89it/s]

Bootstrapping f1:  57%|█████▋    | 574/1000 [00:00<00:00, 1138.95it/s]

Bootstrapping f1:  69%|██████▉   | 688/1000 [00:00<00:00, 1123.45it/s]

Bootstrapping f1:  80%|████████  | 801/1000 [00:00<00:00, 1117.62it/s]

Bootstrapping f1:  91%|█████████▏| 914/1000 [00:00<00:00, 1121.46it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1130.50it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 332/1000 [00:00<00:00, 3311.52it/s]

Bootstrapping accuracy:  68%|██████▊   | 684/1000 [00:00<00:00, 3431.81it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3442.03it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified PCMB with 15 nodes and 14 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 136/1000 [00:00<00:00, 1350.63it/s]

Bootstrapping average_precision:  27%|██▋       | 272/1000 [00:00<00:00, 1354.66it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1367.08it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1358.76it/s]

Bootstrapping average_precision:  69%|██████▊   | 686/1000 [00:00<00:00, 1364.41it/s]

Bootstrapping average_precision:  82%|████████▏ | 823/1000 [00:00<00:00, 1364.20it/s]

Bootstrapping average_precision:  96%|█████████▌| 960/1000 [00:00<00:00, 1365.05it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1361.67it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 856.23it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 854.79it/s]

Bootstrapping roc_auc:  26%|██▌       | 258/1000 [00:00<00:00, 849.41it/s]

Bootstrapping roc_auc:  34%|███▍      | 343/1000 [00:00<00:00, 841.90it/s]

Bootstrapping roc_auc:  43%|████▎     | 428/1000 [00:00<00:00, 836.47it/s]

Bootstrapping roc_auc:  51%|█████▏    | 513/1000 [00:00<00:00, 837.78it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 833.00it/s]

Bootstrapping roc_auc:  68%|██████▊   | 681/1000 [00:00<00:00, 830.36it/s]

Bootstrapping roc_auc:  76%|███████▋  | 765/1000 [00:00<00:00, 828.64it/s]

Bootstrapping roc_auc:  85%|████████▍ | 848/1000 [00:01<00:00, 826.75it/s]

Bootstrapping roc_auc:  93%|█████████▎| 931/1000 [00:01<00:00, 827.20it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 834.77it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 115/1000 [00:00<00:00, 1147.69it/s]

Bootstrapping precision:  23%|██▎       | 233/1000 [00:00<00:00, 1162.38it/s]

Bootstrapping precision:  35%|███▌      | 353/1000 [00:00<00:00, 1175.80it/s]

Bootstrapping precision:  47%|████▋     | 473/1000 [00:00<00:00, 1181.85it/s]

Bootstrapping precision:  59%|█████▉    | 593/1000 [00:00<00:00, 1184.92it/s]

Bootstrapping precision:  71%|███████▏  | 713/1000 [00:00<00:00, 1188.69it/s]

Bootstrapping precision:  83%|████████▎ | 834/1000 [00:00<00:00, 1192.79it/s]

Bootstrapping precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1199.40it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1188.06it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1205.19it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1197.90it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1207.34it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1205.49it/s]

Bootstrapping recall:  61%|██████    | 607/1000 [00:00<00:00, 1208.17it/s]

Bootstrapping recall:  73%|███████▎  | 728/1000 [00:00<00:00, 1118.32it/s]

Bootstrapping recall:  85%|████████▍ | 847/1000 [00:00<00:00, 1137.89it/s]

Bootstrapping recall:  97%|█████████▋| 967/1000 [00:00<00:00, 1156.32it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1168.44it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1214.23it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1210.00it/s]

Bootstrapping f1:  37%|███▋      | 366/1000 [00:00<00:00, 1202.65it/s]

Bootstrapping f1:  49%|████▊     | 487/1000 [00:00<00:00, 1200.42it/s]

Bootstrapping f1:  61%|██████    | 609/1000 [00:00<00:00, 1204.80it/s]

Bootstrapping f1:  73%|███████▎  | 731/1000 [00:00<00:00, 1208.76it/s]

Bootstrapping f1:  85%|████████▌ | 852/1000 [00:00<00:00, 1207.60it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1199.72it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1199.74it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 337/1000 [00:00<00:00, 3368.05it/s]

Bootstrapping accuracy:  68%|██████▊   | 682/1000 [00:00<00:00, 3413.38it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3424.04it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 137/1000 [00:00<00:00, 1363.65it/s]

Bootstrapping average_precision:  27%|██▋       | 274/1000 [00:00<00:00, 1340.41it/s]

Bootstrapping average_precision:  41%|████      | 410/1000 [00:00<00:00, 1348.98it/s]

Bootstrapping average_precision:  55%|█████▍    | 545/1000 [00:00<00:00, 1347.38it/s]

Bootstrapping average_precision:  68%|██████▊   | 682/1000 [00:00<00:00, 1353.07it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1358.91it/s]

Bootstrapping average_precision:  96%|█████████▌| 956/1000 [00:00<00:00, 1358.92it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1354.43it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 85/1000 [00:00<00:01, 843.51it/s]

Bootstrapping roc_auc:  17%|█▋        | 170/1000 [00:00<00:00, 839.39it/s]

Bootstrapping roc_auc:  26%|██▌       | 255/1000 [00:00<00:00, 840.14it/s]

Bootstrapping roc_auc:  34%|███▍      | 342/1000 [00:00<00:00, 849.50it/s]

Bootstrapping roc_auc:  43%|████▎     | 428/1000 [00:00<00:00, 853.22it/s]

Bootstrapping roc_auc:  52%|█████▏    | 515/1000 [00:00<00:00, 856.55it/s]

Bootstrapping roc_auc:  60%|██████    | 601/1000 [00:00<00:00, 839.99it/s]

Bootstrapping roc_auc:  69%|██████▊   | 686/1000 [00:00<00:00, 833.59it/s]

Bootstrapping roc_auc:  77%|███████▋  | 772/1000 [00:00<00:00, 840.44it/s]

Bootstrapping roc_auc:  86%|████████▌ | 858/1000 [00:01<00:00, 843.80it/s]

Bootstrapping roc_auc:  94%|█████████▍| 943/1000 [00:01<00:00, 831.59it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 838.34it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 113/1000 [00:00<00:00, 1129.10it/s]

Bootstrapping precision:  23%|██▎       | 226/1000 [00:00<00:00, 1125.01it/s]

Bootstrapping precision:  34%|███▍      | 342/1000 [00:00<00:00, 1139.42it/s]

Bootstrapping precision:  46%|████▋     | 464/1000 [00:00<00:00, 1168.21it/s]

Bootstrapping precision:  59%|█████▊    | 586/1000 [00:00<00:00, 1183.24it/s]

Bootstrapping precision:  70%|███████   | 705/1000 [00:00<00:00, 1175.54it/s]

Bootstrapping precision:  82%|████████▏ | 823/1000 [00:00<00:00, 1157.80it/s]

Bootstrapping precision:  94%|█████████▍| 939/1000 [00:00<00:00, 1154.06it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1155.68it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1143.63it/s]

Bootstrapping recall:  23%|██▎       | 230/1000 [00:00<00:00, 1130.23it/s]

Bootstrapping recall:  34%|███▍      | 344/1000 [00:00<00:00, 1127.72it/s]

Bootstrapping recall:  46%|████▌     | 457/1000 [00:00<00:00, 1091.32it/s]

Bootstrapping recall:  57%|█████▋    | 568/1000 [00:00<00:00, 1096.68it/s]

Bootstrapping recall:  68%|██████▊   | 685/1000 [00:00<00:00, 1118.08it/s]

Bootstrapping recall:  80%|████████  | 802/1000 [00:00<00:00, 1132.18it/s]

Bootstrapping recall:  92%|█████████▏| 923/1000 [00:00<00:00, 1154.38it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1137.34it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█▏        | 113/1000 [00:00<00:00, 1123.07it/s]

Bootstrapping f1:  23%|██▎       | 226/1000 [00:00<00:00, 1123.21it/s]

Bootstrapping f1:  35%|███▍      | 347/1000 [00:00<00:00, 1158.59it/s]

Bootstrapping f1:  47%|████▋     | 469/1000 [00:00<00:00, 1181.67it/s]

Bootstrapping f1:  59%|█████▉    | 590/1000 [00:00<00:00, 1188.73it/s]

Bootstrapping f1:  71%|███████   | 710/1000 [00:00<00:00, 1189.79it/s]

Bootstrapping f1:  83%|████████▎ | 831/1000 [00:00<00:00, 1194.24it/s]

Bootstrapping f1:  95%|█████████▌| 954/1000 [00:00<00:00, 1203.46it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1185.87it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 356/1000 [00:00<00:00, 3558.15it/s]

Bootstrapping accuracy:  71%|███████   | 712/1000 [00:00<00:00, 3551.48it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3547.05it/s]

Processing Simplified PCMB with 18 nodes and 50 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 141/1000 [00:00<00:00, 1405.80it/s]

Bootstrapping average_precision:  28%|██▊       | 282/1000 [00:00<00:00, 1402.42it/s]

Bootstrapping average_precision:  42%|████▏     | 423/1000 [00:00<00:00, 1370.17it/s]

Bootstrapping average_precision:  56%|█████▌    | 561/1000 [00:00<00:00, 1361.22it/s]

Bootstrapping average_precision:  70%|██████▉   | 698/1000 [00:00<00:00, 1318.71it/s]

Bootstrapping average_precision:  83%|████████▎ | 831/1000 [00:00<00:00, 1311.17it/s]

Bootstrapping average_precision:  97%|█████████▋| 967/1000 [00:00<00:00, 1325.65it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1338.04it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 852.30it/s]

Bootstrapping roc_auc:  17%|█▋        | 172/1000 [00:00<00:00, 842.31it/s]

Bootstrapping roc_auc:  26%|██▌       | 257/1000 [00:00<00:00, 832.45it/s]

Bootstrapping roc_auc:  34%|███▍      | 341/1000 [00:00<00:00, 829.33it/s]

Bootstrapping roc_auc:  42%|████▏     | 424/1000 [00:00<00:00, 823.32it/s]

Bootstrapping roc_auc:  51%|█████     | 509/1000 [00:00<00:00, 830.67it/s]

Bootstrapping roc_auc:  60%|█████▉    | 595/1000 [00:00<00:00, 838.67it/s]

Bootstrapping roc_auc:  68%|██████▊   | 679/1000 [00:00<00:00, 838.83it/s]

Bootstrapping roc_auc:  76%|███████▋  | 763/1000 [00:00<00:00, 836.62it/s]

Bootstrapping roc_auc:  85%|████████▍ | 847/1000 [00:01<00:00, 832.86it/s]

Bootstrapping roc_auc:  93%|█████████▎| 931/1000 [00:01<00:00, 833.88it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 832.58it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█         | 111/1000 [00:00<00:00, 1106.98it/s]

Bootstrapping precision:  22%|██▏       | 222/1000 [00:00<00:00, 1104.54it/s]

Bootstrapping precision:  34%|███▎      | 336/1000 [00:00<00:00, 1114.73it/s]

Bootstrapping precision:  45%|████▍     | 448/1000 [00:00<00:00, 1110.12it/s]

Bootstrapping precision:  56%|█████▋    | 563/1000 [00:00<00:00, 1121.55it/s]

Bootstrapping precision:  68%|██████▊   | 677/1000 [00:00<00:00, 1125.99it/s]

Bootstrapping precision:  79%|███████▉  | 793/1000 [00:00<00:00, 1135.37it/s]

Bootstrapping precision:  91%|█████████ | 907/1000 [00:00<00:00, 1136.18it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1125.13it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1159.27it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1179.17it/s]

Bootstrapping recall:  35%|███▌      | 354/1000 [00:00<00:00, 1166.86it/s]

Bootstrapping recall:  47%|████▋     | 471/1000 [00:00<00:00, 1165.27it/s]

Bootstrapping recall:  59%|█████▉    | 588/1000 [00:00<00:00, 1163.49it/s]

Bootstrapping recall:  71%|███████   | 707/1000 [00:00<00:00, 1169.03it/s]

Bootstrapping recall:  82%|████████▏ | 824/1000 [00:00<00:00, 1162.98it/s]

Bootstrapping recall:  94%|█████████▍| 941/1000 [00:00<00:00, 1147.05it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1155.77it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  11%|█         | 110/1000 [00:00<00:00, 1099.90it/s]

Bootstrapping f1:  23%|██▎       | 226/1000 [00:00<00:00, 1133.84it/s]

Bootstrapping f1:  34%|███▍      | 340/1000 [00:00<00:00, 1119.99it/s]

Bootstrapping f1:  46%|████▌     | 455/1000 [00:00<00:00, 1129.98it/s]

Bootstrapping f1:  57%|█████▋    | 571/1000 [00:00<00:00, 1137.76it/s]

Bootstrapping f1:  69%|██████▉   | 688/1000 [00:00<00:00, 1146.77it/s]

Bootstrapping f1:  80%|████████  | 803/1000 [00:00<00:00, 1126.73it/s]

Bootstrapping f1:  92%|█████████▏| 917/1000 [00:00<00:00, 1129.30it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1130.75it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 339/1000 [00:00<00:00, 3381.98it/s]

Bootstrapping accuracy:  68%|██████▊   | 685/1000 [00:00<00:00, 3422.62it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3430.22it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 126/1000 [00:00<00:00, 1257.87it/s]

Bootstrapping average_precision:  25%|██▌       | 254/1000 [00:00<00:00, 1267.75it/s]

Bootstrapping average_precision:  39%|███▉      | 389/1000 [00:00<00:00, 1301.18it/s]

Bootstrapping average_precision:  52%|█████▏    | 524/1000 [00:00<00:00, 1317.71it/s]

Bootstrapping average_precision:  66%|██████▌   | 660/1000 [00:00<00:00, 1331.25it/s]

Bootstrapping average_precision:  79%|███████▉  | 794/1000 [00:00<00:00, 1325.54it/s]

Bootstrapping average_precision:  93%|█████████▎| 927/1000 [00:00<00:00, 1306.13it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1304.04it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 81/1000 [00:00<00:01, 804.02it/s]

Bootstrapping roc_auc:  16%|█▌        | 162/1000 [00:00<00:01, 795.15it/s]

Bootstrapping roc_auc:  25%|██▍       | 246/1000 [00:00<00:00, 814.85it/s]

Bootstrapping roc_auc:  33%|███▎      | 330/1000 [00:00<00:00, 823.19it/s]

Bootstrapping roc_auc:  41%|████▏     | 413/1000 [00:00<00:00, 816.15it/s]

Bootstrapping roc_auc:  50%|████▉     | 496/1000 [00:00<00:00, 818.42it/s]

Bootstrapping roc_auc:  58%|█████▊    | 581/1000 [00:00<00:00, 826.56it/s]

Bootstrapping roc_auc:  66%|██████▋   | 665/1000 [00:00<00:00, 830.35it/s]

Bootstrapping roc_auc:  75%|███████▌  | 751/1000 [00:00<00:00, 837.12it/s]

Bootstrapping roc_auc:  84%|████████▎ | 837/1000 [00:01<00:00, 843.67it/s]

Bootstrapping roc_auc:  92%|█████████▏| 923/1000 [00:01<00:00, 847.23it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 832.33it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1207.80it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1182.70it/s]

Bootstrapping precision:  36%|███▌      | 361/1000 [00:00<00:00, 1173.27it/s]

Bootstrapping precision:  48%|████▊     | 481/1000 [00:00<00:00, 1181.12it/s]

Bootstrapping precision:  60%|██████    | 600/1000 [00:00<00:00, 1170.19it/s]

Bootstrapping precision:  72%|███████▏  | 718/1000 [00:00<00:00, 1158.03it/s]

Bootstrapping precision:  83%|████████▎ | 834/1000 [00:00<00:00, 1155.47it/s]

Bootstrapping precision:  95%|█████████▌| 953/1000 [00:00<00:00, 1164.88it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1167.28it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  11%|█▏        | 113/1000 [00:00<00:00, 1125.67it/s]

Bootstrapping recall:  23%|██▎       | 228/1000 [00:00<00:00, 1137.53it/s]

Bootstrapping recall:  34%|███▍      | 342/1000 [00:00<00:00, 1136.04it/s]

Bootstrapping recall:  46%|████▌     | 456/1000 [00:00<00:00, 1132.50it/s]

Bootstrapping recall:  57%|█████▋    | 571/1000 [00:00<00:00, 1138.63it/s]

Bootstrapping recall:  69%|██████▉   | 691/1000 [00:00<00:00, 1157.60it/s]

Bootstrapping recall:  81%|████████  | 811/1000 [00:00<00:00, 1169.59it/s]

Bootstrapping recall:  93%|█████████▎| 930/1000 [00:00<00:00, 1173.29it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1156.08it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 116/1000 [00:00<00:00, 1156.79it/s]

Bootstrapping f1:  23%|██▎       | 233/1000 [00:00<00:00, 1158.74it/s]

Bootstrapping f1:  35%|███▌      | 354/1000 [00:00<00:00, 1178.39it/s]

Bootstrapping f1:  48%|████▊     | 476/1000 [00:00<00:00, 1192.19it/s]

Bootstrapping f1:  60%|█████▉    | 597/1000 [00:00<00:00, 1197.35it/s]

Bootstrapping f1:  72%|███████▏  | 717/1000 [00:00<00:00, 1191.47it/s]

Bootstrapping f1:  84%|████████▎ | 837/1000 [00:00<00:00, 1193.58it/s]

Bootstrapping f1:  96%|█████████▌| 958/1000 [00:00<00:00, 1197.83it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1190.58it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 354/1000 [00:00<00:00, 3530.78it/s]

Bootstrapping accuracy:  71%|███████   | 708/1000 [00:00<00:00, 3529.25it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3497.23it/s]

Processing Simplified Golem with 12 nodes and 22 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1377.86it/s]

Bootstrapping average_precision:  28%|██▊       | 279/1000 [00:00<00:00, 1395.01it/s]

Bootstrapping average_precision:  42%|████▏     | 419/1000 [00:00<00:00, 1363.48it/s]

Bootstrapping average_precision:  56%|█████▌    | 556/1000 [00:00<00:00, 1362.30it/s]

Bootstrapping average_precision:  70%|██████▉   | 695/1000 [00:00<00:00, 1369.54it/s]

Bootstrapping average_precision:  84%|████████▎ | 836/1000 [00:00<00:00, 1381.16it/s]

Bootstrapping average_precision:  98%|█████████▊| 976/1000 [00:00<00:00, 1384.61it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1374.93it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 82/1000 [00:00<00:01, 818.45it/s]

Bootstrapping roc_auc:  17%|█▋        | 166/1000 [00:00<00:01, 830.97it/s]

Bootstrapping roc_auc:  25%|██▌       | 251/1000 [00:00<00:00, 835.47it/s]

Bootstrapping roc_auc:  34%|███▎      | 335/1000 [00:00<00:00, 832.72it/s]

Bootstrapping roc_auc:  42%|████▏     | 424/1000 [00:00<00:00, 850.92it/s]

Bootstrapping roc_auc:  51%|█████     | 512/1000 [00:00<00:00, 857.96it/s]

Bootstrapping roc_auc:  60%|█████▉    | 598/1000 [00:00<00:00, 851.32it/s]

Bootstrapping roc_auc:  68%|██████▊   | 684/1000 [00:00<00:00, 853.50it/s]

Bootstrapping roc_auc:  77%|███████▋  | 771/1000 [00:00<00:00, 858.35it/s]

Bootstrapping roc_auc:  86%|████████▌ | 859/1000 [00:01<00:00, 862.18it/s]

Bootstrapping roc_auc:  95%|█████████▍| 946/1000 [00:01<00:00, 856.44it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 842.96it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:   9%|▉         | 88/1000 [00:00<00:01, 875.20it/s]

Bootstrapping precision:  18%|█▊        | 181/1000 [00:00<00:00, 907.31it/s]

Bootstrapping precision:  30%|██▉       | 299/1000 [00:00<00:00, 1029.14it/s]

Bootstrapping precision:  42%|████▏     | 421/1000 [00:00<00:00, 1099.99it/s]

Bootstrapping precision:  54%|█████▎    | 537/1000 [00:00<00:00, 1121.03it/s]

Bootstrapping precision:  65%|██████▌   | 651/1000 [00:00<00:00, 1126.64it/s]

Bootstrapping precision:  76%|███████▋  | 764/1000 [00:00<00:00, 1124.61it/s]

Bootstrapping precision:  88%|████████▊ | 877/1000 [00:00<00:00, 1122.07it/s]

Bootstrapping precision: 100%|█████████▉| 996/1000 [00:00<00:00, 1139.81it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1098.50it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1143.80it/s]

Bootstrapping recall:  23%|██▎       | 230/1000 [00:00<00:00, 1125.84it/s]

Bootstrapping recall:  35%|███▍      | 346/1000 [00:00<00:00, 1137.33it/s]

Bootstrapping recall:  46%|████▋     | 463/1000 [00:00<00:00, 1147.92it/s]

Bootstrapping recall:  58%|█████▊    | 581/1000 [00:00<00:00, 1156.64it/s]

Bootstrapping recall:  70%|██████▉   | 697/1000 [00:00<00:00, 1146.96it/s]

Bootstrapping recall:  82%|████████▏ | 815/1000 [00:00<00:00, 1157.63it/s]

Bootstrapping recall:  94%|█████████▎| 937/1000 [00:00<00:00, 1176.77it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1157.61it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1166.14it/s]

Bootstrapping f1:  23%|██▎       | 234/1000 [00:00<00:00, 1164.20it/s]

Bootstrapping f1:  35%|███▌      | 352/1000 [00:00<00:00, 1170.22it/s]

Bootstrapping f1:  47%|████▋     | 471/1000 [00:00<00:00, 1177.20it/s]

Bootstrapping f1:  59%|█████▉    | 590/1000 [00:00<00:00, 1180.44it/s]

Bootstrapping f1:  71%|███████   | 711/1000 [00:00<00:00, 1189.95it/s]

Bootstrapping f1:  83%|████████▎ | 830/1000 [00:00<00:00, 1176.12it/s]

Bootstrapping f1:  95%|█████████▍| 948/1000 [00:00<00:00, 1161.50it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1167.97it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  35%|███▌      | 351/1000 [00:00<00:00, 3502.85it/s]

Bootstrapping accuracy:  71%|███████   | 706/1000 [00:00<00:00, 3525.05it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3516.62it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1347.60it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1333.13it/s]

Bootstrapping average_precision:  40%|████      | 405/1000 [00:00<00:00, 1340.31it/s]

Bootstrapping average_precision:  54%|█████▍    | 540/1000 [00:00<00:00, 1312.34it/s]

Bootstrapping average_precision:  67%|██████▋   | 672/1000 [00:00<00:00, 1301.30it/s]

Bootstrapping average_precision:  80%|████████  | 803/1000 [00:00<00:00, 1295.64it/s]

Bootstrapping average_precision:  93%|█████████▎| 933/1000 [00:00<00:00, 1276.71it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1297.50it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   8%|▊         | 83/1000 [00:00<00:01, 829.37it/s]

Bootstrapping roc_auc:  17%|█▋        | 167/1000 [00:00<00:00, 835.18it/s]

Bootstrapping roc_auc:  25%|██▌       | 253/1000 [00:00<00:00, 842.77it/s]

Bootstrapping roc_auc:  34%|███▍      | 339/1000 [00:00<00:00, 846.97it/s]

Bootstrapping roc_auc:  42%|████▎     | 425/1000 [00:00<00:00, 849.55it/s]

Bootstrapping roc_auc:  51%|█████     | 511/1000 [00:00<00:00, 851.81it/s]

Bootstrapping roc_auc:  60%|█████▉    | 597/1000 [00:00<00:00, 853.17it/s]

Bootstrapping roc_auc:  68%|██████▊   | 683/1000 [00:00<00:00, 854.94it/s]

Bootstrapping roc_auc:  77%|███████▋  | 769/1000 [00:00<00:00, 855.17it/s]

Bootstrapping roc_auc:  86%|████████▌ | 855/1000 [00:01<00:00, 855.63it/s]

Bootstrapping roc_auc:  94%|█████████▍| 941/1000 [00:01<00:00, 835.10it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 840.02it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  11%|█▏        | 114/1000 [00:00<00:00, 1134.35it/s]

Bootstrapping precision:  23%|██▎       | 228/1000 [00:00<00:00, 1120.88it/s]

Bootstrapping precision:  34%|███▍      | 341/1000 [00:00<00:00, 1118.07it/s]

Bootstrapping precision:  45%|████▌     | 454/1000 [00:00<00:00, 1120.57it/s]

Bootstrapping precision:  57%|█████▋    | 570/1000 [00:00<00:00, 1131.58it/s]

Bootstrapping precision:  69%|██████▊   | 687/1000 [00:00<00:00, 1144.11it/s]

Bootstrapping precision:  80%|████████  | 802/1000 [00:00<00:00, 1146.02it/s]

Bootstrapping precision:  92%|█████████▏| 919/1000 [00:00<00:00, 1150.82it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1140.46it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 116/1000 [00:00<00:00, 1153.47it/s]

Bootstrapping recall:  24%|██▎       | 236/1000 [00:00<00:00, 1177.27it/s]

Bootstrapping recall:  36%|███▌      | 356/1000 [00:00<00:00, 1187.32it/s]

Bootstrapping recall:  48%|████▊     | 475/1000 [00:00<00:00, 1185.87it/s]

Bootstrapping recall:  59%|█████▉    | 594/1000 [00:00<00:00, 1171.12it/s]

Bootstrapping recall:  71%|███████▏  | 714/1000 [00:00<00:00, 1179.42it/s]

Bootstrapping recall:  84%|████████▎ | 836/1000 [00:00<00:00, 1192.16it/s]

Bootstrapping recall:  96%|█████████▌| 956/1000 [00:00<00:00, 1194.46it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1180.27it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 117/1000 [00:00<00:00, 1164.56it/s]

Bootstrapping f1:  24%|██▎       | 236/1000 [00:00<00:00, 1177.18it/s]

Bootstrapping f1:  36%|███▌      | 357/1000 [00:00<00:00, 1189.85it/s]

Bootstrapping f1:  48%|████▊     | 477/1000 [00:00<00:00, 1190.76it/s]

Bootstrapping f1:  60%|█████▉    | 597/1000 [00:00<00:00, 1176.11it/s]

Bootstrapping f1:  72%|███████▏  | 715/1000 [00:00<00:00, 1176.59it/s]

Bootstrapping f1:  83%|████████▎ | 834/1000 [00:00<00:00, 1178.96it/s]

Bootstrapping f1:  95%|█████████▌| 954/1000 [00:00<00:00, 1184.79it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1176.66it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 344/1000 [00:00<00:00, 3430.67it/s]

Bootstrapping accuracy:  69%|██████▉   | 688/1000 [00:00<00:00, 3422.09it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3448.02it/s]

Processing Simplified Golem $\cap$ Simplified PCMB with 6 nodes and 5 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 138/1000 [00:00<00:00, 1377.69it/s]

Bootstrapping average_precision:  28%|██▊       | 276/1000 [00:00<00:00, 1342.04it/s]

Bootstrapping average_precision:  41%|████      | 411/1000 [00:00<00:00, 1335.08it/s]

Bootstrapping average_precision:  55%|█████▍    | 548/1000 [00:00<00:00, 1346.82it/s]

Bootstrapping average_precision:  68%|██████▊   | 684/1000 [00:00<00:00, 1348.86it/s]

Bootstrapping average_precision:  82%|████████▏ | 820/1000 [00:00<00:00, 1349.11it/s]

Bootstrapping average_precision:  96%|█████████▌| 957/1000 [00:00<00:00, 1355.12it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1351.10it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▉         | 88/1000 [00:00<00:01, 873.80it/s]

Bootstrapping roc_auc:  18%|█▊        | 176/1000 [00:00<00:00, 864.27it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 866.65it/s]

Bootstrapping roc_auc:  35%|███▌      | 350/1000 [00:00<00:00, 863.47it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 866.14it/s]

Bootstrapping roc_auc:  52%|█████▎    | 525/1000 [00:00<00:00, 864.06it/s]

Bootstrapping roc_auc:  61%|██████    | 612/1000 [00:00<00:00, 865.05it/s]

Bootstrapping roc_auc:  70%|███████   | 701/1000 [00:00<00:00, 871.03it/s]

Bootstrapping roc_auc:  79%|███████▉  | 790/1000 [00:00<00:00, 875.45it/s]

Bootstrapping roc_auc:  88%|████████▊ | 880/1000 [00:01<00:00, 881.20it/s]

Bootstrapping roc_auc:  97%|█████████▋| 969/1000 [00:01<00:00, 880.58it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 872.75it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1201.57it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1194.53it/s]

Bootstrapping precision:  36%|███▌      | 362/1000 [00:00<00:00, 1195.89it/s]

Bootstrapping precision:  48%|████▊     | 482/1000 [00:00<00:00, 1194.39it/s]

Bootstrapping precision:  60%|██████    | 602/1000 [00:00<00:00, 1193.44it/s]

Bootstrapping precision:  72%|███████▏  | 722/1000 [00:00<00:00, 1193.15it/s]

Bootstrapping precision:  84%|████████▍ | 842/1000 [00:00<00:00, 1193.08it/s]

Bootstrapping precision:  96%|█████████▋| 965/1000 [00:00<00:00, 1201.83it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1197.48it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 121/1000 [00:00<00:00, 1201.55it/s]

Bootstrapping recall:  24%|██▍       | 242/1000 [00:00<00:00, 1201.94it/s]

Bootstrapping recall:  36%|███▋      | 364/1000 [00:00<00:00, 1208.97it/s]

Bootstrapping recall:  48%|████▊     | 485/1000 [00:00<00:00, 1208.74it/s]

Bootstrapping recall:  61%|██████    | 606/1000 [00:00<00:00, 1198.15it/s]

Bootstrapping recall:  73%|███████▎  | 726/1000 [00:00<00:00, 1183.51it/s]

Bootstrapping recall:  84%|████████▍ | 845/1000 [00:00<00:00, 1184.74it/s]

Bootstrapping recall:  96%|█████████▋| 964/1000 [00:00<00:00, 1181.98it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1189.69it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1178.83it/s]

Bootstrapping f1:  24%|██▍       | 238/1000 [00:00<00:00, 1187.72it/s]

Bootstrapping f1:  36%|███▌      | 357/1000 [00:00<00:00, 1181.94it/s]

Bootstrapping f1:  48%|████▊     | 476/1000 [00:00<00:00, 1178.88it/s]

Bootstrapping f1:  59%|█████▉    | 594/1000 [00:00<00:00, 1166.49it/s]

Bootstrapping f1:  71%|███████▏  | 714/1000 [00:00<00:00, 1174.25it/s]

Bootstrapping f1:  84%|████████▎ | 836/1000 [00:00<00:00, 1184.80it/s]

Bootstrapping f1:  96%|█████████▌| 955/1000 [00:00<00:00, 1169.40it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1172.11it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▍      | 343/1000 [00:00<00:00, 3423.36it/s]

Bootstrapping accuracy:  69%|██████▊   | 686/1000 [00:00<00:00, 3387.09it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3392.90it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▎        | 135/1000 [00:00<00:00, 1343.60it/s]

Bootstrapping average_precision:  27%|██▋       | 270/1000 [00:00<00:00, 1299.09it/s]

Bootstrapping average_precision:  40%|████      | 401/1000 [00:00<00:00, 1281.96it/s]

Bootstrapping average_precision:  54%|█████▎    | 536/1000 [00:00<00:00, 1306.07it/s]

Bootstrapping average_precision:  67%|██████▋   | 667/1000 [00:00<00:00, 1295.39it/s]

Bootstrapping average_precision:  80%|███████▉  | 798/1000 [00:00<00:00, 1298.35it/s]

Bootstrapping average_precision:  93%|█████████▎| 928/1000 [00:00<00:00, 1288.61it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1291.53it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 851.07it/s]

Bootstrapping roc_auc:  17%|█▋        | 173/1000 [00:00<00:00, 858.37it/s]

Bootstrapping roc_auc:  26%|██▌       | 259/1000 [00:00<00:00, 853.33it/s]

Bootstrapping roc_auc:  34%|███▍      | 345/1000 [00:00<00:00, 853.69it/s]

Bootstrapping roc_auc:  43%|████▎     | 431/1000 [00:00<00:00, 842.67it/s]

Bootstrapping roc_auc:  52%|█████▏    | 516/1000 [00:00<00:00, 835.78it/s]

Bootstrapping roc_auc:  60%|██████    | 600/1000 [00:00<00:00, 811.70it/s]

Bootstrapping roc_auc:  68%|██████▊   | 682/1000 [00:00<00:00, 811.05it/s]

Bootstrapping roc_auc:  76%|███████▋  | 764/1000 [00:00<00:00, 809.76it/s]

Bootstrapping roc_auc:  85%|████████▍ | 846/1000 [00:01<00:00, 809.99it/s]

Bootstrapping roc_auc:  93%|█████████▎| 930/1000 [00:01<00:00, 816.55it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 825.62it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 120/1000 [00:00<00:00, 1199.40it/s]

Bootstrapping precision:  24%|██▍       | 240/1000 [00:00<00:00, 1181.89it/s]

Bootstrapping precision:  36%|███▌      | 359/1000 [00:00<00:00, 1161.63it/s]

Bootstrapping precision:  48%|████▊     | 476/1000 [00:00<00:00, 1141.87it/s]

Bootstrapping precision:  59%|█████▉    | 592/1000 [00:00<00:00, 1147.41it/s]

Bootstrapping precision:  71%|███████   | 709/1000 [00:00<00:00, 1154.81it/s]

Bootstrapping precision:  82%|████████▎ | 825/1000 [00:00<00:00, 1053.87it/s]

Bootstrapping precision:  94%|█████████▍| 938/1000 [00:00<00:00, 1074.45it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1113.12it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 115/1000 [00:00<00:00, 1146.71it/s]

Bootstrapping recall:  23%|██▎       | 230/1000 [00:00<00:00, 1144.91it/s]

Bootstrapping recall:  34%|███▍      | 345/1000 [00:00<00:00, 1140.18it/s]

Bootstrapping recall:  46%|████▌     | 460/1000 [00:00<00:00, 1133.20it/s]

Bootstrapping recall:  57%|█████▋    | 574/1000 [00:00<00:00, 1128.91it/s]

Bootstrapping recall:  69%|██████▊   | 687/1000 [00:00<00:00, 1125.25it/s]

Bootstrapping recall:  80%|████████  | 800/1000 [00:00<00:00, 1126.42it/s]

Bootstrapping recall:  92%|█████████▏| 917/1000 [00:00<00:00, 1139.90it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1136.45it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 118/1000 [00:00<00:00, 1170.76it/s]

Bootstrapping f1:  24%|██▍       | 239/1000 [00:00<00:00, 1190.59it/s]

Bootstrapping f1:  36%|███▌      | 362/1000 [00:00<00:00, 1205.33it/s]

Bootstrapping f1:  48%|████▊     | 483/1000 [00:00<00:00, 1186.09it/s]

Bootstrapping f1:  60%|██████    | 602/1000 [00:00<00:00, 1168.10it/s]

Bootstrapping f1:  72%|███████▏  | 719/1000 [00:00<00:00, 1164.37it/s]

Bootstrapping f1:  84%|████████▎ | 836/1000 [00:00<00:00, 1159.22it/s]

Bootstrapping f1:  95%|█████████▌| 952/1000 [00:00<00:00, 1157.63it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1165.83it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  34%|███▎      | 337/1000 [00:00<00:00, 3367.27it/s]

Bootstrapping accuracy:  67%|██████▋   | 674/1000 [00:00<00:00, 3368.14it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3374.70it/s]

Processing Simplified Clinician Consensus $\cap$ Simplified Golem with 5 nodes and 4 edges

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  14%|█▍        | 139/1000 [00:00<00:00, 1380.91it/s]

Bootstrapping average_precision:  28%|██▊       | 279/1000 [00:00<00:00, 1390.23it/s]

Bootstrapping average_precision:  42%|████▏     | 419/1000 [00:00<00:00, 1390.31it/s]

Bootstrapping average_precision:  56%|█████▌    | 560/1000 [00:00<00:00, 1395.09it/s]

Bootstrapping average_precision:  70%|███████   | 700/1000 [00:00<00:00, 1396.78it/s]

Bootstrapping average_precision:  84%|████████▍ | 840/1000 [00:00<00:00, 1396.89it/s]

Bootstrapping average_precision:  98%|█████████▊| 980/1000 [00:00<00:00, 1397.66it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1394.23it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 86/1000 [00:00<00:01, 854.71it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 868.27it/s]

Bootstrapping roc_auc:  26%|██▋       | 263/1000 [00:00<00:00, 876.53it/s]

Bootstrapping roc_auc:  35%|███▌      | 351/1000 [00:00<00:00, 859.84it/s]

Bootstrapping roc_auc:  44%|████▍     | 438/1000 [00:00<00:00, 862.67it/s]

Bootstrapping roc_auc:  53%|█████▎    | 526/1000 [00:00<00:00, 867.34it/s]

Bootstrapping roc_auc:  62%|██████▏   | 615/1000 [00:00<00:00, 873.97it/s]

Bootstrapping roc_auc:  70%|███████   | 704/1000 [00:00<00:00, 877.29it/s]

Bootstrapping roc_auc:  79%|███████▉  | 793/1000 [00:00<00:00, 881.00it/s]

Bootstrapping roc_auc:  88%|████████▊ | 882/1000 [00:01<00:00, 880.05it/s]

Bootstrapping roc_auc:  97%|█████████▋| 971/1000 [00:01<00:00, 876.08it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 872.50it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 121/1000 [00:00<00:00, 1209.77it/s]

Bootstrapping precision:  24%|██▍       | 242/1000 [00:00<00:00, 1206.73it/s]

Bootstrapping precision:  36%|███▋      | 363/1000 [00:00<00:00, 1205.13it/s]

Bootstrapping precision:  48%|████▊     | 485/1000 [00:00<00:00, 1208.21it/s]

Bootstrapping precision:  61%|██████    | 608/1000 [00:00<00:00, 1212.61it/s]

Bootstrapping precision:  73%|███████▎  | 732/1000 [00:00<00:00, 1218.24it/s]

Bootstrapping precision:  85%|████████▌ | 854/1000 [00:00<00:00, 1217.19it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1219.87it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1214.21it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1216.74it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1217.94it/s]

Bootstrapping recall:  37%|███▋      | 368/1000 [00:00<00:00, 1223.63it/s]

Bootstrapping recall:  49%|████▉     | 491/1000 [00:00<00:00, 1221.72it/s]

Bootstrapping recall:  61%|██████▏   | 614/1000 [00:00<00:00, 1219.58it/s]

Bootstrapping recall:  74%|███████▎  | 736/1000 [00:00<00:00, 1209.28it/s]

Bootstrapping recall:  86%|████████▌ | 857/1000 [00:00<00:00, 1192.32it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1188.74it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1202.74it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 122/1000 [00:00<00:00, 1216.82it/s]

Bootstrapping f1:  24%|██▍       | 244/1000 [00:00<00:00, 1184.18it/s]

Bootstrapping f1:  36%|███▋      | 363/1000 [00:00<00:00, 1181.84it/s]

Bootstrapping f1:  48%|████▊     | 482/1000 [00:00<00:00, 1169.71it/s]

Bootstrapping f1:  60%|█████▉    | 599/1000 [00:00<00:00, 1164.85it/s]

Bootstrapping f1:  72%|███████▏  | 716/1000 [00:00<00:00, 1155.24it/s]

Bootstrapping f1:  83%|████████▎ | 834/1000 [00:00<00:00, 1162.04it/s]

Bootstrapping f1:  96%|█████████▌| 956/1000 [00:00<00:00, 1177.83it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1173.13it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  33%|███▎      | 333/1000 [00:00<00:00, 3321.50it/s]

Bootstrapping accuracy:  67%|██████▋   | 674/1000 [00:00<00:00, 3367.13it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3332.35it/s]

Bootstrapping average_precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping average_precision:  13%|█▎        | 130/1000 [00:00<00:00, 1295.00it/s]

Bootstrapping average_precision:  26%|██▌       | 260/1000 [00:00<00:00, 1279.94it/s]

Bootstrapping average_precision:  39%|███▉      | 389/1000 [00:00<00:00, 1275.85it/s]

Bootstrapping average_precision:  52%|█████▏    | 517/1000 [00:00<00:00, 1270.31it/s]

Bootstrapping average_precision:  65%|██████▍   | 649/1000 [00:00<00:00, 1284.81it/s]

Bootstrapping average_precision:  78%|███████▊  | 779/1000 [00:00<00:00, 1286.66it/s]

Bootstrapping average_precision:  91%|█████████ | 908/1000 [00:00<00:00, 1278.04it/s]

Bootstrapping average_precision: 100%|██████████| 1000/1000 [00:00<00:00, 1281.94it/s]

Bootstrapping roc_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping roc_auc:   9%|▊         | 87/1000 [00:00<00:01, 864.18it/s]

Bootstrapping roc_auc:  17%|█▋        | 174/1000 [00:00<00:00, 862.92it/s]

Bootstrapping roc_auc:  26%|██▌       | 261/1000 [00:00<00:00, 850.65it/s]

Bootstrapping roc_auc:  35%|███▍      | 347/1000 [00:00<00:00, 847.72it/s]

Bootstrapping roc_auc:  43%|████▎     | 434/1000 [00:00<00:00, 852.47it/s]

Bootstrapping roc_auc:  52%|█████▏    | 521/1000 [00:00<00:00, 856.73it/s]

Bootstrapping roc_auc:  61%|██████    | 608/1000 [00:00<00:00, 860.13it/s]

Bootstrapping roc_auc:  70%|██████▉   | 695/1000 [00:00<00:00, 860.94it/s]

Bootstrapping roc_auc:  78%|███████▊  | 782/1000 [00:00<00:00, 852.99it/s]

Bootstrapping roc_auc:  87%|████████▋ | 868/1000 [00:01<00:00, 853.49it/s]

Bootstrapping roc_auc:  95%|█████████▌| 954/1000 [00:01<00:00, 855.06it/s]

Bootstrapping roc_auc: 100%|██████████| 1000/1000 [00:01<00:00, 855.56it/s]

Bootstrapping precision:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping precision:  12%|█▏        | 123/1000 [00:00<00:00, 1222.92it/s]

Bootstrapping precision:  25%|██▍       | 246/1000 [00:00<00:00, 1217.47it/s]

Bootstrapping precision:  37%|███▋      | 368/1000 [00:00<00:00, 1205.07it/s]

Bootstrapping precision:  49%|████▉     | 489/1000 [00:00<00:00, 1195.97it/s]

Bootstrapping precision:  61%|██████    | 610/1000 [00:00<00:00, 1200.36it/s]

Bootstrapping precision:  73%|███████▎  | 732/1000 [00:00<00:00, 1205.30it/s]

Bootstrapping precision:  86%|████████▌ | 855/1000 [00:00<00:00, 1211.13it/s]

Bootstrapping precision:  98%|█████████▊| 977/1000 [00:00<00:00, 1198.87it/s]

Bootstrapping precision: 100%|██████████| 1000/1000 [00:00<00:00, 1202.25it/s]

Bootstrapping recall:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping recall:  12%|█▏        | 122/1000 [00:00<00:00, 1211.14it/s]

Bootstrapping recall:  24%|██▍       | 244/1000 [00:00<00:00, 1214.73it/s]

Bootstrapping recall:  37%|███▋      | 366/1000 [00:00<00:00, 1216.91it/s]

Bootstrapping recall:  49%|████▉     | 488/1000 [00:00<00:00, 1218.08it/s]

Bootstrapping recall:  61%|██████    | 610/1000 [00:00<00:00, 1217.33it/s]

Bootstrapping recall:  73%|███████▎  | 732/1000 [00:00<00:00, 1216.97it/s]

Bootstrapping recall:  85%|████████▌ | 854/1000 [00:00<00:00, 1216.85it/s]

Bootstrapping recall:  98%|█████████▊| 977/1000 [00:00<00:00, 1219.19it/s]

Bootstrapping recall: 100%|██████████| 1000/1000 [00:00<00:00, 1216.57it/s]

Bootstrapping f1:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping f1:  12%|█▏        | 121/1000 [00:00<00:00, 1207.39it/s]

Bootstrapping f1:  24%|██▍       | 242/1000 [00:00<00:00, 1187.75it/s]

Bootstrapping f1:  36%|███▋      | 364/1000 [00:00<00:00, 1201.19it/s]

Bootstrapping f1:  49%|████▊     | 486/1000 [00:00<00:00, 1206.18it/s]

Bootstrapping f1:  61%|██████    | 607/1000 [00:00<00:00, 1202.66it/s]

Bootstrapping f1:  73%|███████▎  | 729/1000 [00:00<00:00, 1206.17it/s]

Bootstrapping f1:  85%|████████▌ | 851/1000 [00:00<00:00, 1207.57it/s]

Bootstrapping f1:  97%|█████████▋| 973/1000 [00:00<00:00, 1210.02it/s]

Bootstrapping f1: 100%|██████████| 1000/1000 [00:00<00:00, 1205.37it/s]

Bootstrapping accuracy:   0%|          | 0/1000 [00:00<?, ?it/s]

Bootstrapping accuracy:  36%|███▌      | 359/1000 [00:00<00:00, 3582.51it/s]

Bootstrapping accuracy:  72%|███████▏  | 718/1000 [00:00<00:00, 3582.43it/s]

Bootstrapping accuracy: 100%|██████████| 1000/1000 [00:00<00:00, 3581.49it/s]

In [18]:
pd.DataFrame(results).to_csv('biomarker_counts_fixed/No Drugs or Interventions.csv', index=False)
pd.DataFrame(results)

,Model,DAG,Average Precision,AUROC,Precision,Recall,F1 Score,Accuracy,ECE,# Features,# Biomarkers
0,LGBN,Control,"0.74 (0.70, 0.78)","0.89 (0.87, 0.91)","0.94 (0.93, 0.96)","0.76 (0.74, 0.79)","0.82 (0.80, 0.85)","0.94 (0.94, 0.95)",0.134,521,28
1,XGB,Control,"0.78 (0.75, 0.82)","0.92 (0.90, 0.93)","0.90 (0.88, 0.92)","0.80 (0.78, 0.82)","0.84 (0.82, 0.86)","0.95 (0.94, 0.95)",0.093,521,28
2,LGBN,Correlation,"0.69 (0.66, 0.74)","0.85 (0.82, 0.87)","0.94 (0.93, 0.96)","0.72 (0.70, 0.74)","0.78 (0.76, 0.81)","0.94 (0.93, 0.94)",0.130,53,20
3,XGB,Correlation,"0.75 (0.71, 0.78)","0.89 (0.87, 0.91)","0.90 (0.88, 0.92)","0.78 (0.76, 0.80)","0.83 (0.80, 0.85)","0.94 (0.93, 0.95)",0.114,53,20
4,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.69 (0.65, 0.73)","0.88 (0.85, 0.90)","0.91 (0.89, 0.93)","0.71 (0.69, 0.74)","0.77 (0.75, 0.80)","0.93 (0.92, 0.94)",0.144,150,8
5,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.76 (0.73, 0.80)","0.91 (0.89, 0.93)","0.90 (0.88, 0.92)","0.79 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.104,150,8
6,LGBN,Simplified Clinician Consensus $\cup$ Simplifi...,"0.72 (0.68, 0.76)","0.88 (0.86, 0.90)","0.91 (0.89, 0.93)","0.73 (0.71, 0.76)","0.79 (0.77, 0.81)","0.93 (0.93, 0.94)",0.142,223,12
7,XGB,Simplified Clinician Consensus $\cup$ Simplifi...,"0.76 (0.73, 0.80)","0.91 (0.89, 0.93)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.100,223,12
8,LGBN,Simplified Golem $\cup$ Simplified PCMB,"0.70 (0.67, 0.75)","0.88 (0.86, 0.90)","0.92 (0.90, 0.94)","0.73 (0.71, 0.76)","0.79 (0.77, 0.81)","0.94 (0.93, 0.94)",0.141,223,12
9,XGB,Simplified Golem $\cup$ Simplified PCMB,"0.77 (0.73, 0.80)","0.91 (0.89, 0.93)","0.91 (0.89, 0.93)","0.78 (0.76, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.098,223,12
10,LGBN,Simplified Clinician Consensus,"0.69 (0.65, 0.73)","0.87 (0.85, 0.89)","0.91 (0.89, 0.93)","0.71 (0.69, 0.73)","0.77 (0.74, 0.79)","0.93 (0.92, 0.94)",0.146,112,6
11,XGB,Simplified Clinician Consensus,"0.73 (0.70, 0.77)","0.90 (0.88, 0.92)","0.90 (0.87, 0.92)","0.76 (0.74, 0.79)","0.81 (0.79, 0.83)","0.94 (0.93, 0.95)",0.104,112,6
12,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.68 (0.64, 0.72)","0.87 (0.84, 0.89)","0.92 (0.90, 0.94)","0.70 (0.68, 0.72)","0.76 (0.73, 0.78)","0.93 (0.92, 0.94)",0.146,93,5
13,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.73 (0.69, 0.76)","0.89 (0.87, 0.91)","0.89 (0.87, 0.91)","0.78 (0.75, 0.80)","0.82 (0.80, 0.84)","0.94 (0.93, 0.95)",0.108,93,5
14,LGBN,Simplified PCMB,"0.69 (0.65, 0.73)","0.87 (0.85, 0.89)","0.91 (0.89, 0.93)","0.72 (0.69, 0.74)","0.77 (0.75, 0.80)","0.93 (0.92, 0.94)",0.145,131,7
15,XGB,Simplified PCMB,"0.76 (0.73, 0.80)","0.91 (0.89, 0.92)","0.89 (0.87, 0.91)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.93, 0.95)",0.104,131,7
16,LGBN,Simplified Golem,"0.69 (0.65, 0.73)","0.87 (0.85, 0.89)","0.91 (0.89, 0.93)","0.72 (0.70, 0.74)","0.78 (0.75, 0.80)","0.93 (0.92, 0.94)",0.142,149,8
17,XGB,Simplified Golem,"0.76 (0.72, 0.79)","0.91 (0.89, 0.92)","0.90 (0.88, 0.92)","0.79 (0.77, 0.81)","0.83 (0.81, 0.85)","0.94 (0.94, 0.95)",0.102,149,8
18,LGBN,Simplified Golem $\cap$ Simplified PCMB,"0.60 (0.56, 0.65)","0.85 (0.83, 0.87)","0.89 (0.86, 0.91)","0.67 (0.65, 0.69)","0.72 (0.70, 0.75)","0.92 (0.91, 0.93)",0.150,57,3
19,XGB,Simplified Golem $\cap$ Simplified PCMB,"0.71 (0.68, 0.75)","0.89 (0.87, 0.91)","0.86 (0.84, 0.89)","0.77 (0.75, 0.80)","0.81 (0.79, 0.83)","0.93 (0.93, 0.94)",0.113,57,3
20,LGBN,Simplified Clinician Consensus $\cap$ Simplifi...,"0.56 (0.51, 0.60)","0.82 (0.79, 0.84)","0.87 (0.84, 0.90)","0.63 (0.60, 0.65)","0.67 (0.64, 0.70)","0.91 (0.90, 0.92)",0.152,38,2
21,XGB,Simplified Clinician Consensus $\cap$ Simplifi...,"0.66 (0.62, 0.70)","0.86 (0.84, 0.88)","0.85 (0.82, 0.87)","0.74 (0.72, 0.76)","0.78 (0.76, 0.80)","0.93 (0.92, 0.93)",0.116,38,2

In [19]:
aurocs = []
auprcs = []
print(len(model_preds))
# Model Comparisons using DeLong Test
for (model1_name, model2_name) in combinations(model_preds.keys(), 2):
        model1 = model_preds[model1_name]
        model2 = model_preds[model2_name]
        comparison_result1, comparison_result2 = compare_models(y_test.Outcome, model1, model2)
        aurocs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Z-score': f"{comparison_result1[0]:.4f}", 'P-value': f"{comparison_result1[1]:.3e}", 'p_numeric': comparison_result1[1]})
        auprcs.append({'Model 1': model1_name, 'Model 2': model2_name, 'Avg Precision Model 1': f"{comparison_result2[0]:.4f}", 'Avg Precision Model 2': f"{comparison_result2[1]:.4f}", 'P-value': f"{comparison_result2[2]:.3e}", 'Benchmark': comparison_result2[3], 'Samples Mean': f"{comparison_result2[4]:.4f}", 'Samples Std': f"{comparison_result2[5]:.4f}"})
aurocs_df = pd.DataFrame(aurocs)
auprcs_df = pd.DataFrame(auprcs)
aurocs_df.to_csv('biomarker_counts_fixed/delong_test_only_vitals_labs_auroc.csv', index=False)
auprcs_df.to_csv('biomarker_counts_fixed/delong_test_only_vitals_labs_auprc.csv', index=False)

11

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 723.51it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 720.79it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 711.79it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 291/1000 [00:00<00:01, 706.83it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 362/1000 [00:00<00:00, 697.51it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 694.40it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 502/1000 [00:00<00:00, 692.71it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 572/1000 [00:00<00:00, 682.03it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 641/1000 [00:00<00:00, 683.94it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 711/1000 [00:01<00:00, 686.39it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 781/1000 [00:01<00:00, 689.60it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 850/1000 [00:01<00:00, 681.89it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 919/1000 [00:01<00:00, 678.24it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 988/1000 [00:01<00:00, 679.22it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 689.17it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 690.42it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 680.20it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 685.60it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 687.69it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 349/1000 [00:00<00:00, 687.34it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 418/1000 [00:00<00:00, 678.62it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 487/1000 [00:00<00:00, 680.20it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 557/1000 [00:00<00:00, 685.08it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 629/1000 [00:00<00:00, 694.71it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 699/1000 [00:01<00:00, 694.53it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 769/1000 [00:01<00:00, 690.21it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 839/1000 [00:01<00:00, 688.40it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 908/1000 [00:01<00:00, 686.06it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 977/1000 [00:01<00:00, 686.05it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 686.16it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 67/1000 [00:00<00:01, 666.46it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 675.97it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 204/1000 [00:00<00:01, 670.14it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 272/1000 [00:00<00:01, 670.75it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 342/1000 [00:00<00:00, 677.56it/s]

Computing average_precision Permutation Test p-value:  41%|████▏     | 413/1000 [00:00<00:00, 687.91it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 486/1000 [00:00<00:00, 698.85it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 558/1000 [00:00<00:00, 703.63it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 629/1000 [00:00<00:00, 704.90it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 700/1000 [00:01<00:00, 692.95it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 770/1000 [00:01<00:00, 690.12it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 840/1000 [00:01<00:00, 684.05it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 909/1000 [00:01<00:00, 682.47it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 978/1000 [00:01<00:00, 683.65it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 686.65it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 708.96it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 707.39it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 695.31it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 693.29it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 355/1000 [00:00<00:00, 701.85it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 427/1000 [00:00<00:00, 706.17it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 499/1000 [00:00<00:00, 710.61it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 712.80it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 644/1000 [00:00<00:00, 715.59it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 716/1000 [00:01<00:00, 715.01it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 789/1000 [00:01<00:00, 717.18it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 862/1000 [00:01<00:00, 718.83it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 934/1000 [00:01<00:00, 718.56it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 712.34it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 727.52it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 720.21it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 722.91it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 722.55it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 716.22it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 437/1000 [00:00<00:00, 714.62it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 509/1000 [00:00<00:00, 714.04it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 582/1000 [00:00<00:00, 717.76it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 654/1000 [00:00<00:00, 718.41it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 727/1000 [00:01<00:00, 718.98it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 800/1000 [00:01<00:00, 720.43it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 873/1000 [00:01<00:00, 720.40it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 946/1000 [00:01<00:00, 720.40it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 718.55it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 718.12it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 145/1000 [00:00<00:01, 722.26it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 714.25it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 290/1000 [00:00<00:01, 708.72it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 361/1000 [00:00<00:00, 703.74it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 695.94it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 502/1000 [00:00<00:00, 688.77it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 572/1000 [00:00<00:00, 690.44it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 644/1000 [00:00<00:00, 698.69it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 714/1000 [00:01<00:00, 690.36it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 784/1000 [00:01<00:00, 685.96it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 853/1000 [00:01<00:00, 685.29it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 923/1000 [00:01<00:00, 688.68it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 992/1000 [00:01<00:00, 681.57it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 692.09it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 709.00it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 709.52it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 709.92it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 701.34it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 357/1000 [00:00<00:00, 703.62it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 428/1000 [00:00<00:00, 701.72it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 499/1000 [00:00<00:00, 690.11it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 569/1000 [00:00<00:00, 688.58it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 640/1000 [00:00<00:00, 692.88it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 713/1000 [00:01<00:00, 702.48it/s]

Computing average_precision Permutation Test p-value:  79%|███████▊  | 786/1000 [00:01<00:00, 708.46it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 858/1000 [00:01<00:00, 711.48it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 930/1000 [00:01<00:00, 704.89it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 699.23it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 712.34it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 702.82it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 696.01it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 285/1000 [00:00<00:01, 693.95it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 355/1000 [00:00<00:00, 690.60it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 426/1000 [00:00<00:00, 696.51it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 496/1000 [00:00<00:00, 693.18it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 566/1000 [00:00<00:00, 691.98it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 636/1000 [00:00<00:00, 629.74it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 705/1000 [00:01<00:00, 645.54it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 774/1000 [00:01<00:00, 655.81it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 842/1000 [00:01<00:00, 662.18it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 910/1000 [00:01<00:00, 666.94it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 980/1000 [00:01<00:00, 675.14it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 675.54it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 698.02it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 698.16it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 706.30it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 692.99it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 353/1000 [00:00<00:00, 686.71it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 688.75it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 495/1000 [00:00<00:00, 696.55it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 565/1000 [00:00<00:00, 690.97it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 636/1000 [00:00<00:00, 695.56it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 706/1000 [00:01<00:00, 693.11it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 776/1000 [00:01<00:00, 688.65it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 845/1000 [00:01<00:00, 688.43it/s]

Computing average_precision Permutation Test p-value:  91%|█████████▏| 914/1000 [00:01<00:00, 686.43it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 983/1000 [00:01<00:00, 685.12it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 689.90it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 707.58it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 711.65it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 715.76it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:01, 709.35it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 361/1000 [00:00<00:00, 712.94it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 433/1000 [00:00<00:00, 711.76it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 505/1000 [00:00<00:00, 701.57it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 576/1000 [00:00<00:00, 704.13it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 649/1000 [00:00<00:00, 709.57it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 720/1000 [00:01<00:00, 707.73it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 791/1000 [00:01<00:00, 698.36it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 861/1000 [00:01<00:00, 697.22it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 932/1000 [00:01<00:00, 698.47it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 702.89it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 696.19it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 685.48it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 673.77it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 277/1000 [00:00<00:01, 669.68it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 345/1000 [00:00<00:00, 670.36it/s]

Computing average_precision Permutation Test p-value:  41%|████▏     | 413/1000 [00:00<00:00, 656.75it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 481/1000 [00:00<00:00, 663.04it/s]

Computing average_precision Permutation Test p-value:  55%|█████▍    | 549/1000 [00:00<00:00, 667.20it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 618/1000 [00:00<00:00, 673.78it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 689/1000 [00:01<00:00, 682.36it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 759/1000 [00:01<00:00, 686.75it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 828/1000 [00:01<00:00, 682.72it/s]

Computing average_precision Permutation Test p-value:  90%|████████▉ | 897/1000 [00:01<00:00, 680.39it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 966/1000 [00:01<00:00, 678.56it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 676.67it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 708.82it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 707.36it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 711.97it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:00, 714.96it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 358/1000 [00:00<00:00, 713.75it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 430/1000 [00:00<00:00, 693.56it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 500/1000 [00:00<00:00, 695.54it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 699.67it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 644/1000 [00:00<00:00, 706.99it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 715/1000 [00:01<00:00, 701.03it/s]

Computing average_precision Permutation Test p-value:  79%|███████▊  | 786/1000 [00:01<00:00, 691.09it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 856/1000 [00:01<00:00, 684.04it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▎| 925/1000 [00:01<00:00, 683.63it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 995/1000 [00:01<00:00, 686.25it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.78it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 694.57it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 683.21it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 689.48it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 279/1000 [00:00<00:01, 685.31it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 349/1000 [00:00<00:00, 687.71it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 418/1000 [00:00<00:00, 682.50it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 487/1000 [00:00<00:00, 680.93it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 558/1000 [00:00<00:00, 687.14it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 629/1000 [00:00<00:00, 691.86it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 701/1000 [00:01<00:00, 698.29it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 772/1000 [00:01<00:00, 698.68it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 844/1000 [00:01<00:00, 703.52it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 917/1000 [00:01<00:00, 708.34it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 988/1000 [00:01<00:00, 700.89it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 694.13it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 692.30it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 693.85it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 692.24it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 691.57it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 350/1000 [00:00<00:00, 688.05it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 420/1000 [00:00<00:00, 690.55it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 698.48it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 565/1000 [00:00<00:00, 706.97it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 636/1000 [00:00<00:00, 703.98it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 707/1000 [00:01<00:00, 693.78it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 777/1000 [00:01<00:00, 691.36it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 847/1000 [00:01<00:00, 692.21it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 919/1000 [00:01<00:00, 700.48it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 990/1000 [00:01<00:00, 697.02it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.30it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 688.70it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 692.46it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 211/1000 [00:00<00:01, 700.69it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 282/1000 [00:00<00:01, 701.36it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 707.18it/s]

Computing average_precision Permutation Test p-value:  42%|████▎     | 425/1000 [00:00<00:00, 705.77it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 497/1000 [00:00<00:00, 708.68it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 568/1000 [00:00<00:00, 700.34it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 639/1000 [00:00<00:00, 697.61it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 710/1000 [00:01<00:00, 701.29it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 781/1000 [00:01<00:00, 700.45it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 852/1000 [00:01<00:00, 691.52it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 922/1000 [00:01<00:00, 690.60it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 992/1000 [00:01<00:00, 689.67it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 696.53it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 705.16it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 691.82it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 690.43it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 282/1000 [00:00<00:01, 688.05it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 352/1000 [00:00<00:00, 689.24it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 421/1000 [00:00<00:00, 685.23it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 691.42it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 562/1000 [00:00<00:00, 693.32it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 633/1000 [00:00<00:00, 697.70it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 704/1000 [00:01<00:00, 698.85it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 774/1000 [00:01<00:00, 696.89it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 844/1000 [00:01<00:00, 689.31it/s]

Computing average_precision Permutation Test p-value:  91%|█████████▏| 914/1000 [00:01<00:00, 690.45it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 984/1000 [00:01<00:00, 690.91it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 691.41it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 705.76it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 704.20it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 699.50it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 692.87it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 353/1000 [00:00<00:00, 686.99it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 422/1000 [00:00<00:00, 683.88it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 687.30it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 564/1000 [00:00<00:00, 696.30it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 636/1000 [00:00<00:00, 701.50it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 708/1000 [00:01<00:00, 706.75it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 780/1000 [00:01<00:00, 708.84it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 851/1000 [00:01<00:00, 703.02it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 922/1000 [00:01<00:00, 700.79it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 993/1000 [00:01<00:00, 690.80it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.95it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 705.51it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 705.76it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 709.68it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 287/1000 [00:00<00:00, 713.52it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 359/1000 [00:00<00:00, 701.25it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 430/1000 [00:00<00:00, 698.88it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 500/1000 [00:00<00:00, 691.50it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 570/1000 [00:00<00:00, 689.73it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 640/1000 [00:00<00:00, 690.63it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 710/1000 [00:01<00:00, 688.10it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 779/1000 [00:01<00:00, 688.65it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 848/1000 [00:01<00:00, 687.96it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 917/1000 [00:01<00:00, 680.81it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▊| 987/1000 [00:01<00:00, 684.02it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 691.39it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 698.60it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 681.68it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 679.73it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 277/1000 [00:00<00:01, 676.77it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 347/1000 [00:00<00:00, 684.14it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 418/1000 [00:00<00:00, 690.20it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 488/1000 [00:00<00:00, 680.70it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 557/1000 [00:00<00:00, 678.88it/s]

Computing average_precision Permutation Test p-value:  62%|██████▎   | 625/1000 [00:00<00:00, 678.05it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 694/1000 [00:01<00:00, 680.86it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 763/1000 [00:01<00:00, 678.80it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 831/1000 [00:01<00:00, 678.13it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 900/1000 [00:01<00:00, 681.02it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 969/1000 [00:01<00:00, 682.51it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 681.45it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 672.61it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 688.31it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 208/1000 [00:00<00:01, 686.69it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 277/1000 [00:00<00:01, 678.61it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 345/1000 [00:00<00:00, 676.87it/s]

Computing average_precision Permutation Test p-value:  41%|████▏     | 414/1000 [00:00<00:00, 680.41it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 484/1000 [00:00<00:00, 683.83it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 553/1000 [00:00<00:00, 682.12it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 623/1000 [00:00<00:00, 686.42it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 692/1000 [00:01<00:00, 681.79it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 762/1000 [00:01<00:00, 687.27it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 833/1000 [00:01<00:00, 693.89it/s]

Computing average_precision Permutation Test p-value:  90%|█████████ | 903/1000 [00:01<00:00, 683.45it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 972/1000 [00:01<00:00, 681.27it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 682.76it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   6%|▋         | 65/1000 [00:00<00:01, 648.85it/s]

Computing average_precision Permutation Test p-value:  13%|█▎        | 133/1000 [00:00<00:01, 661.64it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 203/1000 [00:00<00:01, 674.99it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 272/1000 [00:00<00:01, 677.45it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 342/1000 [00:00<00:00, 682.21it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 411/1000 [00:00<00:00, 679.66it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 481/1000 [00:00<00:00, 684.48it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 550/1000 [00:00<00:00, 683.84it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 619/1000 [00:00<00:00, 685.68it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 689/1000 [00:01<00:00, 687.12it/s]

Computing average_precision Permutation Test p-value:  76%|███████▌  | 758/1000 [00:01<00:00, 684.67it/s]

Computing average_precision Permutation Test p-value:  83%|████████▎ | 827/1000 [00:01<00:00, 682.16it/s]

Computing average_precision Permutation Test p-value:  90%|████████▉ | 897/1000 [00:01<00:00, 685.53it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 969/1000 [00:01<00:00, 693.56it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 683.87it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 696.54it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 695.48it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 212/1000 [00:00<00:01, 704.49it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 706.73it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 355/1000 [00:00<00:00, 700.95it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 426/1000 [00:00<00:00, 695.55it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 496/1000 [00:00<00:00, 692.66it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 566/1000 [00:00<00:00, 691.60it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 636/1000 [00:00<00:00, 687.45it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 707/1000 [00:01<00:00, 692.12it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 777/1000 [00:01<00:00, 692.44it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 847/1000 [00:01<00:00, 693.60it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 917/1000 [00:01<00:00, 692.32it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 988/1000 [00:01<00:00, 696.00it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.20it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 718.44it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 716.72it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 706.18it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 287/1000 [00:00<00:01, 692.12it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 357/1000 [00:00<00:00, 689.85it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 427/1000 [00:00<00:00, 688.46it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 497/1000 [00:00<00:00, 691.15it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 567/1000 [00:00<00:00, 692.48it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 637/1000 [00:00<00:00, 688.99it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 706/1000 [00:01<00:00, 684.83it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 775/1000 [00:01<00:00, 683.94it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 844/1000 [00:01<00:00, 682.48it/s]

Computing average_precision Permutation Test p-value:  91%|█████████▏| 914/1000 [00:01<00:00, 687.46it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 985/1000 [00:01<00:00, 693.03it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 691.41it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 690.48it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 685.70it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 692.15it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 687.22it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 349/1000 [00:00<00:00, 683.15it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 418/1000 [00:00<00:00, 683.95it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 488/1000 [00:00<00:00, 685.86it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 559/1000 [00:00<00:00, 690.00it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 629/1000 [00:00<00:00, 692.10it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 699/1000 [00:01<00:00, 690.87it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 769/1000 [00:01<00:00, 688.32it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 838/1000 [00:01<00:00, 686.86it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 907/1000 [00:01<00:00, 683.53it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 976/1000 [00:01<00:00, 684.03it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 685.82it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 676.43it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 673.59it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 207/1000 [00:00<00:01, 689.50it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 280/1000 [00:00<00:01, 702.07it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 351/1000 [00:00<00:00, 703.23it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 707.33it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 494/1000 [00:00<00:00, 705.31it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 565/1000 [00:00<00:00, 696.26it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 635/1000 [00:00<00:00, 683.68it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 706/1000 [00:01<00:00, 689.89it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 776/1000 [00:01<00:00, 691.61it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 846/1000 [00:01<00:00, 690.67it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 916/1000 [00:01<00:00, 688.38it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 985/1000 [00:01<00:00, 681.93it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 690.38it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 686.25it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 683.38it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 207/1000 [00:00<00:01, 685.52it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 276/1000 [00:00<00:01, 680.36it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 347/1000 [00:00<00:00, 687.90it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 417/1000 [00:00<00:00, 691.69it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 489/1000 [00:00<00:00, 699.87it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 561/1000 [00:00<00:00, 703.60it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 632/1000 [00:00<00:00, 699.20it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 702/1000 [00:01<00:00, 693.00it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 772/1000 [00:01<00:00, 689.50it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 842/1000 [00:01<00:00, 690.99it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 912/1000 [00:01<00:00, 677.98it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 980/1000 [00:01<00:00, 668.23it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 685.11it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 67/1000 [00:00<00:01, 667.52it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 135/1000 [00:00<00:01, 672.51it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 203/1000 [00:00<00:01, 663.15it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 270/1000 [00:00<00:01, 663.48it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 338/1000 [00:00<00:00, 669.16it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 407/1000 [00:00<00:00, 674.60it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 478/1000 [00:00<00:00, 684.31it/s]

Computing average_precision Permutation Test p-value:  55%|█████▍    | 549/1000 [00:00<00:00, 689.77it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 621/1000 [00:00<00:00, 696.08it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 693/1000 [00:01<00:00, 701.93it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 765/1000 [00:01<00:00, 706.43it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 836/1000 [00:01<00:00, 696.31it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 906/1000 [00:01<00:00, 691.30it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 976/1000 [00:01<00:00, 685.61it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 684.99it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 69/1000 [00:00<00:01, 685.59it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 139/1000 [00:00<00:01, 689.19it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 696.32it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 705.65it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 355/1000 [00:00<00:00, 708.78it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 426/1000 [00:00<00:00, 703.64it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 497/1000 [00:00<00:00, 705.62it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 569/1000 [00:00<00:00, 709.84it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 641/1000 [00:00<00:00, 712.49it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 713/1000 [00:01<00:00, 714.47it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 785/1000 [00:01<00:00, 707.51it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 857/1000 [00:01<00:00, 708.90it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 929/1000 [00:01<00:00, 711.42it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 706.36it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 67/1000 [00:00<00:01, 666.70it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 138/1000 [00:00<00:01, 688.59it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 211/1000 [00:00<00:01, 704.35it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 711.74it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 357/1000 [00:00<00:00, 715.04it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 429/1000 [00:00<00:00, 709.19it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 500/1000 [00:00<00:00, 695.46it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 570/1000 [00:00<00:00, 696.02it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 640/1000 [00:00<00:00, 691.91it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 711/1000 [00:01<00:00, 695.22it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 781/1000 [00:01<00:00, 690.52it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 851/1000 [00:01<00:00, 690.83it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 922/1000 [00:01<00:00, 696.33it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 992/1000 [00:01<00:00, 697.39it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 697.01it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 716.25it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 145/1000 [00:00<00:01, 719.37it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 217/1000 [00:00<00:01, 714.79it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 289/1000 [00:00<00:01, 707.22it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 360/1000 [00:00<00:00, 707.39it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 431/1000 [00:00<00:00, 707.02it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 502/1000 [00:00<00:00, 703.93it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 573/1000 [00:00<00:00, 699.51it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 643/1000 [00:00<00:00, 695.18it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 713/1000 [00:01<00:00, 686.64it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 782/1000 [00:01<00:00, 685.80it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 851/1000 [00:01<00:00, 686.86it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 920/1000 [00:01<00:00, 687.08it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 991/1000 [00:01<00:00, 690.93it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 696.72it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 679.83it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 668.24it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 203/1000 [00:00<00:01, 656.08it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 270/1000 [00:00<00:01, 660.61it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 339/1000 [00:00<00:00, 670.83it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 407/1000 [00:00<00:00, 673.21it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 475/1000 [00:00<00:00, 668.51it/s]

Computing average_precision Permutation Test p-value:  54%|█████▍    | 543/1000 [00:00<00:00, 669.26it/s]

Computing average_precision Permutation Test p-value:  61%|██████    | 612/1000 [00:00<00:00, 672.44it/s]

Computing average_precision Permutation Test p-value:  68%|██████▊   | 681/1000 [00:01<00:00, 676.62it/s]

Computing average_precision Permutation Test p-value:  75%|███████▌  | 753/1000 [00:01<00:00, 688.96it/s]

Computing average_precision Permutation Test p-value:  82%|████████▎ | 825/1000 [00:01<00:00, 696.36it/s]

Computing average_precision Permutation Test p-value:  90%|████████▉ | 898/1000 [00:01<00:00, 703.62it/s]

Computing average_precision Permutation Test p-value:  97%|█████████▋| 971/1000 [00:01<00:00, 710.18it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 685.30it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 709.83it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 713.66it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 719.85it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 289/1000 [00:00<00:00, 721.82it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 362/1000 [00:00<00:00, 724.09it/s]

Computing average_precision Permutation Test p-value:  44%|████▎     | 435/1000 [00:00<00:00, 724.04it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 508/1000 [00:00<00:00, 720.21it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 581/1000 [00:00<00:00, 720.71it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 654/1000 [00:00<00:00, 722.92it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 727/1000 [00:01<00:00, 723.95it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 800/1000 [00:01<00:00, 724.94it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 873/1000 [00:01<00:00, 718.44it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 945/1000 [00:01<00:00, 661.73it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 704.69it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 723.07it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 724.72it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 724.70it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 721.54it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 719.18it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 439/1000 [00:00<00:00, 723.17it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 512/1000 [00:00<00:00, 722.50it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 585/1000 [00:00<00:00, 721.82it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 658/1000 [00:00<00:00, 719.42it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 730/1000 [00:01<00:00, 710.57it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 803/1000 [00:01<00:00, 714.44it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 875/1000 [00:01<00:00, 708.96it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▍| 946/1000 [00:01<00:00, 703.96it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 711.87it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 702.31it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 712.08it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 700.10it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 692.87it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 356/1000 [00:00<00:00, 691.11it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 426/1000 [00:00<00:00, 691.11it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 496/1000 [00:00<00:00, 690.57it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 566/1000 [00:00<00:00, 690.78it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 636/1000 [00:00<00:00, 691.36it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 708/1000 [00:01<00:00, 697.24it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 778/1000 [00:01<00:00, 694.85it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 848/1000 [00:01<00:00, 689.46it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 918/1000 [00:01<00:00, 690.86it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 988/1000 [00:01<00:00, 689.07it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 692.47it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 672.20it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 674.15it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 205/1000 [00:00<00:01, 677.75it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 275/1000 [00:00<00:01, 683.98it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 345/1000 [00:00<00:00, 686.52it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 415/1000 [00:00<00:00, 689.82it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 485/1000 [00:00<00:00, 690.86it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 555/1000 [00:00<00:00, 681.00it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 624/1000 [00:00<00:00, 681.45it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 695/1000 [00:01<00:00, 687.37it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 764/1000 [00:01<00:00, 685.21it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 835/1000 [00:01<00:00, 690.43it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 906/1000 [00:01<00:00, 696.19it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 976/1000 [00:01<00:00, 693.16it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 686.68it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 712.93it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 708.48it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 713.46it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:01, 711.09it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 361/1000 [00:00<00:00, 714.40it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 434/1000 [00:00<00:00, 716.65it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 506/1000 [00:00<00:00, 715.64it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 578/1000 [00:00<00:00, 711.58it/s]

Computing average_precision Permutation Test p-value:  65%|██████▌   | 650/1000 [00:00<00:00, 713.52it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 723/1000 [00:01<00:00, 716.75it/s]

Computing average_precision Permutation Test p-value:  80%|███████▉  | 795/1000 [00:01<00:00, 716.59it/s]

Computing average_precision Permutation Test p-value:  87%|████████▋ | 867/1000 [00:01<00:00, 715.93it/s]

Computing average_precision Permutation Test p-value:  94%|█████████▍| 939/1000 [00:01<00:00, 703.42it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 708.31it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 699.27it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 707.83it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 714.25it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 287/1000 [00:00<00:01, 705.50it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 358/1000 [00:00<00:00, 699.19it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 428/1000 [00:00<00:00, 694.42it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 498/1000 [00:00<00:00, 695.25it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 569/1000 [00:00<00:00, 699.81it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 640/1000 [00:00<00:00, 700.27it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 711/1000 [00:01<00:00, 692.94it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 781/1000 [00:01<00:00, 690.39it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 851/1000 [00:01<00:00, 690.69it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 923/1000 [00:01<00:00, 698.09it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 993/1000 [00:01<00:00, 692.20it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.93it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 673.16it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 675.61it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 205/1000 [00:00<00:01, 679.03it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 274/1000 [00:00<00:01, 683.32it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 345/1000 [00:00<00:00, 691.89it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 418/1000 [00:00<00:00, 702.90it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 491/1000 [00:00<00:00, 710.64it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 564/1000 [00:00<00:00, 714.94it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 636/1000 [00:00<00:00, 714.14it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 708/1000 [00:01<00:00, 714.97it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 781/1000 [00:01<00:00, 717.54it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 854/1000 [00:01<00:00, 720.66it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 927/1000 [00:01<00:00, 720.12it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 722.31it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 709.25it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 691.90it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 689.17it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 210/1000 [00:00<00:01, 692.94it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 282/1000 [00:00<00:01, 699.90it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 352/1000 [00:00<00:00, 698.52it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 422/1000 [00:00<00:00, 696.96it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 697.92it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 563/1000 [00:00<00:00, 699.69it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 633/1000 [00:00<00:00, 693.54it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 703/1000 [00:01<00:00, 692.44it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 773/1000 [00:01<00:00, 692.86it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 843/1000 [00:01<00:00, 692.30it/s]

Computing average_precision Permutation Test p-value:  91%|█████████▏| 914/1000 [00:01<00:00, 697.35it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 984/1000 [00:01<00:00, 696.53it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.38it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 694.53it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 705.14it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 711.53it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 712.95it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 358/1000 [00:00<00:00, 704.85it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 429/1000 [00:00<00:00, 697.93it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 499/1000 [00:00<00:00, 691.55it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 569/1000 [00:00<00:00, 691.92it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 639/1000 [00:00<00:00, 692.32it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 709/1000 [00:01<00:00, 689.26it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 779/1000 [00:01<00:00, 691.69it/s]

Computing average_precision Permutation Test p-value:  85%|████████▍ | 849/1000 [00:01<00:00, 690.61it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 919/1000 [00:01<00:00, 685.87it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 988/1000 [00:01<00:00, 686.18it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 693.12it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 717.27it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 703.57it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 708.27it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 288/1000 [00:00<00:01, 711.29it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 360/1000 [00:00<00:00, 702.69it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 431/1000 [00:00<00:00, 692.83it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 501/1000 [00:00<00:00, 694.01it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 571/1000 [00:00<00:00, 691.77it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 641/1000 [00:00<00:00, 687.15it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 713/1000 [00:01<00:00, 695.80it/s]

Computing average_precision Permutation Test p-value:  79%|███████▊  | 786/1000 [00:01<00:00, 703.56it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 857/1000 [00:01<00:00, 704.69it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 929/1000 [00:01<00:00, 707.52it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 702.53it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 68/1000 [00:00<00:01, 676.60it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 678.50it/s]

Computing average_precision Permutation Test p-value:  20%|██        | 204/1000 [00:00<00:01, 677.81it/s]

Computing average_precision Permutation Test p-value:  27%|██▋       | 273/1000 [00:00<00:01, 681.59it/s]

Computing average_precision Permutation Test p-value:  34%|███▍      | 342/1000 [00:00<00:00, 680.35it/s]

Computing average_precision Permutation Test p-value:  41%|████      | 411/1000 [00:00<00:00, 677.48it/s]

Computing average_precision Permutation Test p-value:  48%|████▊     | 481/1000 [00:00<00:00, 681.89it/s]

Computing average_precision Permutation Test p-value:  55%|█████▌    | 550/1000 [00:00<00:00, 678.45it/s]

Computing average_precision Permutation Test p-value:  62%|██████▏   | 620/1000 [00:00<00:00, 684.74it/s]

Computing average_precision Permutation Test p-value:  69%|██████▉   | 693/1000 [00:01<00:00, 696.43it/s]

Computing average_precision Permutation Test p-value:  76%|███████▋  | 765/1000 [00:01<00:00, 702.67it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 836/1000 [00:01<00:00, 704.16it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 908/1000 [00:01<00:00, 708.02it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 981/1000 [00:01<00:00, 711.67it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 693.96it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 724.50it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 724.92it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 725.54it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 723.58it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 724.38it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 439/1000 [00:00<00:00, 726.80it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 512/1000 [00:00<00:00, 725.77it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 585/1000 [00:00<00:00, 726.69it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 658/1000 [00:00<00:00, 727.62it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 731/1000 [00:01<00:00, 726.01it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 804/1000 [00:01<00:00, 725.42it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 877/1000 [00:01<00:00, 724.65it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 950/1000 [00:01<00:00, 724.16it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 724.63it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 721.16it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 724.11it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 722.11it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:01, 703.64it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 363/1000 [00:00<00:00, 694.51it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 433/1000 [00:00<00:00, 687.67it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 503/1000 [00:00<00:00, 689.83it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 574/1000 [00:00<00:00, 696.07it/s]

Computing average_precision Permutation Test p-value:  65%|██████▍   | 646/1000 [00:00<00:00, 702.96it/s]

Computing average_precision Permutation Test p-value:  72%|███████▏  | 717/1000 [00:01<00:00, 703.03it/s]

Computing average_precision Permutation Test p-value:  79%|███████▉  | 788/1000 [00:01<00:00, 689.08it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 857/1000 [00:01<00:00, 684.60it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 926/1000 [00:01<00:00, 679.12it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 997/1000 [00:01<00:00, 687.06it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 694.28it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 710.85it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 699.09it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 214/1000 [00:00<00:01, 693.02it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 284/1000 [00:00<00:01, 687.07it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 353/1000 [00:00<00:00, 682.15it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 686.16it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 493/1000 [00:00<00:00, 687.85it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 563/1000 [00:00<00:00, 688.61it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 632/1000 [00:00<00:00, 687.26it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 701/1000 [00:01<00:00, 686.68it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 773/1000 [00:01<00:00, 694.85it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 845/1000 [00:01<00:00, 700.36it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 916/1000 [00:01<00:00, 695.98it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▊| 986/1000 [00:01<00:00, 690.91it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 690.72it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 66/1000 [00:00<00:01, 659.42it/s]

Computing average_precision Permutation Test p-value:  14%|█▎        | 136/1000 [00:00<00:01, 681.23it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 206/1000 [00:00<00:01, 686.54it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 276/1000 [00:00<00:01, 688.72it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 348/1000 [00:00<00:00, 696.72it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 421/1000 [00:00<00:00, 707.23it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 493/1000 [00:00<00:00, 711.22it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 565/1000 [00:00<00:00, 713.88it/s]

Computing average_precision Permutation Test p-value:  64%|██████▎   | 637/1000 [00:00<00:00, 714.04it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 709/1000 [00:01<00:00, 702.42it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 780/1000 [00:01<00:00, 697.77it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 850/1000 [00:01<00:00, 697.71it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 922/1000 [00:01<00:00, 704.16it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 994/1000 [00:01<00:00, 706.92it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 701.68it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 721.02it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 718.22it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 722.68it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 720.93it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 720.00it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 721.50it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 511/1000 [00:00<00:00, 722.00it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 584/1000 [00:00<00:00, 722.08it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 657/1000 [00:00<00:00, 723.01it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 731/1000 [00:01<00:00, 725.29it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 804/1000 [00:01<00:00, 726.46it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 877/1000 [00:01<00:00, 727.07it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 950/1000 [00:01<00:00, 727.85it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 723.71it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 73/1000 [00:00<00:01, 720.82it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 146/1000 [00:00<00:01, 717.59it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 219/1000 [00:00<00:01, 720.96it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 292/1000 [00:00<00:00, 722.72it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 721.84it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 719.40it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 511/1000 [00:00<00:00, 719.60it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 585/1000 [00:00<00:00, 723.96it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 658/1000 [00:00<00:00, 724.92it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 731/1000 [00:01<00:00, 725.47it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 804/1000 [00:01<00:00, 725.12it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 877/1000 [00:01<00:00, 726.26it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 950/1000 [00:01<00:00, 723.32it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 722.93it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 717.40it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 145/1000 [00:00<00:01, 720.01it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 218/1000 [00:00<00:01, 722.55it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 291/1000 [00:00<00:00, 721.74it/s]

Computing average_precision Permutation Test p-value:  36%|███▋      | 365/1000 [00:00<00:00, 724.74it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 438/1000 [00:00<00:00, 724.02it/s]

Computing average_precision Permutation Test p-value:  51%|█████     | 511/1000 [00:00<00:00, 721.83it/s]

Computing average_precision Permutation Test p-value:  58%|█████▊    | 584/1000 [00:00<00:00, 721.78it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 657/1000 [00:00<00:00, 723.79it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 730/1000 [00:01<00:00, 724.84it/s]

Computing average_precision Permutation Test p-value:  80%|████████  | 803/1000 [00:01<00:00, 724.98it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 876/1000 [00:01<00:00, 725.41it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 950/1000 [00:01<00:00, 726.77it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 724.08it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 74/1000 [00:00<00:01, 731.33it/s]

Computing average_precision Permutation Test p-value:  15%|█▍        | 148/1000 [00:00<00:01, 727.16it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 221/1000 [00:00<00:01, 725.57it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 294/1000 [00:00<00:00, 725.03it/s]

Computing average_precision Permutation Test p-value:  37%|███▋      | 367/1000 [00:00<00:00, 723.62it/s]

Computing average_precision Permutation Test p-value:  44%|████▍     | 440/1000 [00:00<00:00, 724.49it/s]

Computing average_precision Permutation Test p-value:  51%|█████▏    | 513/1000 [00:00<00:00, 724.25it/s]

Computing average_precision Permutation Test p-value:  59%|█████▊    | 586/1000 [00:00<00:00, 723.62it/s]

Computing average_precision Permutation Test p-value:  66%|██████▌   | 659/1000 [00:00<00:00, 723.35it/s]

Computing average_precision Permutation Test p-value:  73%|███████▎  | 732/1000 [00:01<00:00, 723.57it/s]

Computing average_precision Permutation Test p-value:  81%|████████  | 806/1000 [00:01<00:00, 726.36it/s]

Computing average_precision Permutation Test p-value:  88%|████████▊ | 879/1000 [00:01<00:00, 723.57it/s]

Computing average_precision Permutation Test p-value:  95%|█████████▌| 952/1000 [00:01<00:00, 717.53it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 720.80it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 703.18it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 142/1000 [00:00<00:01, 681.26it/s]

Computing average_precision Permutation Test p-value:  21%|██▏       | 213/1000 [00:00<00:01, 693.00it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 283/1000 [00:00<00:01, 694.53it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 353/1000 [00:00<00:00, 691.19it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 691.02it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 493/1000 [00:00<00:00, 692.01it/s]

Computing average_precision Permutation Test p-value:  56%|█████▋    | 563/1000 [00:00<00:00, 625.55it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 633/1000 [00:00<00:00, 645.16it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 703/1000 [00:01<00:00, 659.19it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 773/1000 [00:01<00:00, 671.04it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 844/1000 [00:01<00:00, 682.16it/s]

Computing average_precision Permutation Test p-value:  91%|█████████▏| 913/1000 [00:01<00:00, 684.09it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 982/1000 [00:01<00:00, 681.65it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 675.75it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 71/1000 [00:00<00:01, 703.82it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 143/1000 [00:00<00:01, 711.22it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 215/1000 [00:00<00:01, 699.40it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 285/1000 [00:00<00:01, 685.41it/s]

Computing average_precision Permutation Test p-value:  35%|███▌      | 354/1000 [00:00<00:00, 685.62it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 423/1000 [00:00<00:00, 675.52it/s]

Computing average_precision Permutation Test p-value:  49%|████▉     | 492/1000 [00:00<00:00, 678.44it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 562/1000 [00:00<00:00, 682.91it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 632/1000 [00:00<00:00, 687.34it/s]

Computing average_precision Permutation Test p-value:  70%|███████   | 702/1000 [00:01<00:00, 690.90it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 772/1000 [00:01<00:00, 690.58it/s]

Computing average_precision Permutation Test p-value:  84%|████████▍ | 842/1000 [00:01<00:00, 689.21it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 912/1000 [00:01<00:00, 690.69it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 984/1000 [00:01<00:00, 699.45it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 690.69it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 70/1000 [00:00<00:01, 695.05it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 140/1000 [00:00<00:01, 685.66it/s]

Computing average_precision Permutation Test p-value:  21%|██        | 209/1000 [00:00<00:01, 683.85it/s]

Computing average_precision Permutation Test p-value:  28%|██▊       | 278/1000 [00:00<00:01, 684.31it/s]

Computing average_precision Permutation Test p-value:  35%|███▍      | 347/1000 [00:00<00:00, 683.37it/s]

Computing average_precision Permutation Test p-value:  42%|████▏     | 416/1000 [00:00<00:00, 681.81it/s]

Computing average_precision Permutation Test p-value:  49%|████▊     | 486/1000 [00:00<00:00, 685.05it/s]

Computing average_precision Permutation Test p-value:  56%|█████▌    | 556/1000 [00:00<00:00, 688.91it/s]

Computing average_precision Permutation Test p-value:  63%|██████▎   | 626/1000 [00:00<00:00, 691.93it/s]

Computing average_precision Permutation Test p-value:  70%|██████▉   | 696/1000 [00:01<00:00, 690.91it/s]

Computing average_precision Permutation Test p-value:  77%|███████▋  | 766/1000 [00:01<00:00, 690.32it/s]

Computing average_precision Permutation Test p-value:  84%|████████▎ | 836/1000 [00:01<00:00, 692.32it/s]

Computing average_precision Permutation Test p-value:  91%|█████████ | 907/1000 [00:01<00:00, 694.82it/s]

Computing average_precision Permutation Test p-value:  98%|█████████▊| 978/1000 [00:01<00:00, 697.69it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 690.54it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 714.66it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 716.40it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 696.09it/s]

Computing average_precision Permutation Test p-value:  29%|██▊       | 286/1000 [00:00<00:01, 696.67it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 357/1000 [00:00<00:00, 701.38it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 428/1000 [00:00<00:00, 690.76it/s]

Computing average_precision Permutation Test p-value:  50%|████▉     | 499/1000 [00:00<00:00, 693.94it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 569/1000 [00:00<00:00, 694.11it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 639/1000 [00:00<00:00, 690.73it/s]

Computing average_precision Permutation Test p-value:  71%|███████   | 709/1000 [00:01<00:00, 687.96it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 778/1000 [00:01<00:00, 684.27it/s]

Computing average_precision Permutation Test p-value:  85%|████████▌ | 850/1000 [00:01<00:00, 694.76it/s]

Computing average_precision Permutation Test p-value:  92%|█████████▏| 921/1000 [00:01<00:00, 698.98it/s]

Computing average_precision Permutation Test p-value:  99%|█████████▉| 991/1000 [00:01<00:00, 697.19it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 695.15it/s]

Computing average_precision Permutation Test p-value:   0%|          | 0/1000 [00:00<?, ?it/s]

Computing average_precision Permutation Test p-value:   7%|▋         | 72/1000 [00:00<00:01, 714.43it/s]

Computing average_precision Permutation Test p-value:  14%|█▍        | 144/1000 [00:00<00:01, 712.58it/s]

Computing average_precision Permutation Test p-value:  22%|██▏       | 216/1000 [00:00<00:01, 714.23it/s]

Computing average_precision Permutation Test p-value:  29%|██▉       | 289/1000 [00:00<00:00, 717.67it/s]

Computing average_precision Permutation Test p-value:  36%|███▌      | 361/1000 [00:00<00:00, 703.91it/s]

Computing average_precision Permutation Test p-value:  43%|████▎     | 432/1000 [00:00<00:00, 687.62it/s]

Computing average_precision Permutation Test p-value:  50%|█████     | 501/1000 [00:00<00:00, 686.74it/s]

Computing average_precision Permutation Test p-value:  57%|█████▋    | 570/1000 [00:00<00:00, 686.29it/s]

Computing average_precision Permutation Test p-value:  64%|██████▍   | 643/1000 [00:00<00:00, 697.54it/s]

Computing average_precision Permutation Test p-value:  71%|███████▏  | 714/1000 [00:01<00:00, 701.15it/s]

Computing average_precision Permutation Test p-value:  78%|███████▊  | 785/1000 [00:01<00:00, 694.47it/s]

Computing average_precision Permutation Test p-value:  86%|████████▌ | 855/1000 [00:01<00:00, 691.75it/s]

Computing average_precision Permutation Test p-value:  93%|█████████▎| 926/1000 [00:01<00:00, 696.07it/s]

Computing average_precision Permutation Test p-value: 100%|█████████▉| 996/1000 [00:01<00:00, 692.01it/s]

Computing average_precision Permutation Test p-value: 100%|██████████| 1000/1000 [00:01<00:00, 696.36it/s]

In [20]:
# Plot calibration curves
for dag_name in calibrations:
    plt.figure(dpi=300, layout='constrained', figsize=(8, 5))
    plt.rcParams['font.size'] = 18
    prob_true, prob_pred = calibrations[dag_name]
    plt.plot(prob_pred, prob_true, marker='o', label=f'Calibration Curve')
    plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Perfect Calibration')
    plt.xlabel('Predicted Probability')
    plt.ylabel('True Probability')
    # plt.title(f'Only vitals and labs - {dag_name}')
    # plt.legend()
    plt.xticks(np.arange(0, 1.1, 0.1))
    plt.grid()
    plt.savefig(f'biomarker_counts_fixed/Calibration Curves/Only vitals and labs - {dag_name.replace(" ", "_").replace("$\\cap$", "AND").replace("$\\cup$", "OR")}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)

In [21]:
vals = shap_values_biomarker_summary(shap_values)
auprc_top10 = pd.DataFrame(results).sort_values(by=['Average Precision'], ascending=False).head(10).DAG.unique().tolist()
plt.rcParams.update({  
'figure.figsize': (8, 10),   # Default figure size (inches)  
'figure.dpi': 300,          # Default DPI for figure creation  
'ytick.labelsize': 16,
'xtick.labelsize': 16,
'font.size': 18,
'lines.linewidth': 2,       # Default line width  
'figure.constrained_layout.use': True,
'pdf.fonttype': 42
}) 
for dag_name in auprc_top10:
    df = vals[dag_name].sort_values(ascending=True)
    plt.barh(df.index, df)
    plt.xlabel('Mean |SHAP value|')
    plt.ylabel('Biomarker')
    plt.savefig(f'biomarker_counts_fixed/Feature Importance/Only vitals and labs - {dag_name}.pdf', bbox_inches='tight', dpi=300)
    plt.close()
plt.rcParams.update(plt.rcParamsDefault)